/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.RingTheory.Localization.Cech

/-!
# Exactness of the Čech complex of a module for a cover of a basic open

Let `M` be a module over a commutative ring `R`, `f : ι → R` a finite family and `c : R` with
`D(f i) ⊆ D(c)` for all `i` (i.e. `c ∣ f i ^ n` for some `n`) and `D(c) ⊆ ⋃ D(f i)` (i.e.
`c ∈ √(f i)`). Then the Čech complex `LocalizedModule.cechObj M f •` is exact in positive
degrees (`LocalizedModule.cechD_exact_of_mem_radical`). This is the Čech complex of `M~` for the
cover of `D(c)` by the `D(f i)`; for `c = 1` it is `LocalizedModule.cechD_exact`.

The proof is local: after inverting `f j` the complex is contracted by a homotopy
(`LocalizedModule.cechD_exact_of_dvd`), so a cocycle `y` satisfies `f j ^ k • y ∈ im d` for all
`j`; since `c ^ N` lies in the ideal generated by the `f j ^ k` we get `c ^ N • y ∈ im d`, and
`c` acts invertibly on all terms of the complex.
-/

open Submonoid

namespace LocalizedModule

universe u v w

variable {R : Type u} [CommRing R] (M : Type v) [AddCommGroup M] [Module R M]
  {ι : Type w} (f : ι → R)

/-- If `c ∣ f i ^ n` for all `i`, then `c` acts invertibly on the Čech cochains of `f`. -/
lemma bijective_smul_cechObj {c : R} (hcf : ∀ i, ∃ n, c ∣ f i ^ n) (m : ℕ) :
    Function.Bijective fun x : cechObj M f m ↦ c • x := by
  have hσ (σ : Fin (m + 1) → ι) :
      Function.Bijective fun x : LocalizedModule (powers (∏ a, f (σ a))) M ↦ c • x := by
    have h : ∃ n, c ∣ (∏ a, f (σ a)) ^ n := by
      obtain ⟨n, hn⟩ := hcf (σ 0)
      exact ⟨n, hn.trans (pow_dvd_pow_of_dvd
        (Finset.dvd_prod_of_mem (fun a ↦ f (σ a)) (Finset.mem_univ 0)) n)⟩
    exact (Module.End.isUnit_iff _).1 (isUnit_algebraMap_of_dvd_pow M h)
  refine ⟨fun x y hxy ↦ funext fun σ ↦ (hσ σ).1 (congrFun hxy σ), fun y ↦ ?_⟩
  choose x hx using fun σ ↦ (hσ σ).2 (y σ)
  exact ⟨x, funext hx⟩

omit [AddCommGroup M] [Module R M] in
lemma dvd_pow_mul_self_aux (j i : ι) : ∃ m, f j * f j ∣ (f j * f i) ^ m :=
  ⟨2, Dvd.intro (f i ^ 2) (by ring)⟩

/-- A Čech cocycle becomes a coboundary after multiplying by a power of any `f j`. -/
lemma exists_pow_smul_eq_cechD [Finite ι] (n : ℕ) (y : cechObj M f (n + 1))
    (hy : cechD M f (n + 1) y = 0) (j : ι) :
    ∃ (k : ℕ) (x : cechObj M f n), f j ^ k • y = cechD M f n x := by
  let φ := fun m ↦ cechMap M (fun i ↦ dvd_mul_left (f i) (f j)) m
  have hex := cechD_exact_of_dvd M (f := fun i ↦ f j * f i) (j := j)
    (dvd_pow_mul_self_aux f j) n
  have h1 : cechD M (fun i ↦ f j * f i) (n + 1) (φ (n + 1) y) = 0 := by
    simp only [φ]
    rw [← cechMap_cechD, hy, map_zero]
  obtain ⟨z, hz⟩ := (hex (φ (n + 1) y)).1 h1
  obtain ⟨⟨x, s⟩, hs⟩ := IsLocalizedModule.surj (powers (f j)) (φ n) z
  simp only [Submonoid.smul_def] at hs
  have h2 : φ (n + 1) ((s : R) • y) = φ (n + 1) (cechD M f n x) := by
    simp only [φ] at hs ⊢
    rw [map_smul, cechMap_cechD, ← hs, ← hz, map_smul]
  obtain ⟨t, ht⟩ := IsLocalizedModule.exists_of_eq (S := powers (f j)) h2
  simp only [Submonoid.smul_def] at ht
  obtain ⟨k, hk⟩ := (t * s).2
  simp only at hk
  refine ⟨k, (t : R) • x, ?_⟩
  rw [map_smul, hk, Submonoid.coe_mul, mul_smul, ht]

/-- **Exactness of the Čech complex for a cover of `D(c)`**: if `D(f i) ⊆ D(c)` for all `i` and
`c ∈ √(f i)`, the Čech complex of `M` for the finite family `f` is exact at
`cechObj M f (n + 1)`. -/
theorem cechD_exact_of_mem_radical [Finite ι] {c : R}
    (hc : c ∈ (Ideal.span (Set.range f)).radical) (hcf : ∀ i, ∃ n, c ∣ f i ^ n) (n : ℕ) :
    Function.Exact (cechD M f n) (cechD M f (n + 1)) := by
  classical
  have := Fintype.ofFinite ι
  have hbij : ∀ m N, Function.Bijective fun x : cechObj M f m ↦ c ^ N • x := by
    intro m N
    induction N with
    | zero =>
      simp only [pow_zero, one_smul]
      exact Function.bijective_id
    | succ N ih =>
      convert (bijective_smul_cechObj M f hcf m).comp ih using 1
      funext x
      simp [pow_succ', mul_smul]
  intro y
  refine ⟨fun hy ↦ ?_, ?_⟩
  · choose k x hx using exists_pow_smul_eq_cechD M f n y hy
    let K := Finset.univ.sup k
    have hkK : ∀ j, k j ≤ K := fun j ↦ Finset.le_sup (Finset.mem_univ j)
    have hK : ∀ j, f j ^ K • y = cechD M f n (f j ^ (K - k j) • x j) := by
      intro j
      rw [map_smul, ← hx, smul_smul, ← pow_add, Nat.sub_add_cancel (hkK j)]
    have hrad : c ∈ (Ideal.span (Set.range fun j ↦ f j ^ K)).radical := by
      refine Ideal.radical_le_radical_iff.2 ?_ hc
      rw [Ideal.span_le]
      rintro _ ⟨j, rfl⟩
      exact ⟨K, Ideal.subset_span ⟨j, rfl⟩⟩
    obtain ⟨N, hN⟩ := hrad
    obtain ⟨a, ha⟩ := Ideal.mem_span_range_iff_exists_fun.1 hN
    have hu : c ^ N • y = cechD M f n (∑ j, a j • f j ^ (K - k j) • x j) := by
      rw [← ha, Finset.sum_smul, map_sum]
      refine Finset.sum_congr rfl fun j _ ↦ ?_
      rw [mul_smul, hK]
      simp only [map_smul]
    obtain ⟨x', hx'⟩ := (hbij n N).2 (∑ j, a j • f j ^ (K - k j) • x j)
    simp only at hx'
    refine ⟨x', (hbij (n + 1) N).1 ?_⟩
    simp only
    rw [← map_smul, hx', hu]
  · rintro ⟨x, rfl⟩
    exact cechD_cechD M f n x

end LocalizedModule
