/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Mathlib.LinearAlgebra.TensorProduct.RightExactness
import Mathlib.LinearAlgebra.TensorProduct.Pi
import Oka.Analytification.RET.ES.FiniteSplitting
import Oka.Analytification.RET.FiniteAnalytification
import Oka.AnalyticSpace.FiniteEtalePushforwardCoherent

/-!
# Coherence of pushforwards along analytified finite morphisms

Let `q : Y ⟶ S` be a finite morphism of affine schemes of finite type over `ℂ`. Then
`q^an_* 𝒪_{Y^an}` is a coherent `𝒪_{S^an}`-module
(`ComplexAnalytic.isCoherent_pushUnit_analytification_map`): if `b₁, …, b_m` generate
`Γ(Y, 𝒪_Y)` as a `Γ(S, 𝒪_S)`-module with relations `ρ₁, …, ρ_L`, then by
`ComplexAnalytic.finiteAnalyticSplitting` the germs of the `b_j` generate every stalk of
`q^an_* 𝒪_{Y^an}` over `𝒪_{S^an}`, with relations generated by the `ρ_l`. Consequently
`q^an_* M` is coherent for every coherent `𝒪_{Y^an}`-module `M`
(`ComplexAnalytic.isCoherent_pushforward_analytification_map`).
-/

open CategoryTheory Opposite AlgebraicGeometry TopologicalSpace
open scoped TensorProduct

universe u

namespace TensorProduct

variable {A R B : Type*} [CommRing A] [CommRing R] [Algebra A R] [AddCommGroup B] [Module A B]
  {m : ℕ} {b : Fin m → B}

/-- If `b` spans `B`, every element of `R ⊗[A] B` is `∑ j, r j ⊗ b j`. -/
lemma exists_eq_sum_tmul_of_span_eq_top (hb : Submodule.span A (Set.range b) = ⊤)
    (x : R ⊗[A] B) : ∃ r : Fin m → R, x = ∑ j, r j ⊗ₜ b j := by
  induction x using TensorProduct.induction_on with
  | zero => exact ⟨0, by simp⟩
  | tmul x y =>
    obtain ⟨a, rfl⟩ := (Submodule.mem_span_range_iff_exists_fun A).1
      (hb ▸ Submodule.mem_top : y ∈ Submodule.span A (Set.range b))
    exact ⟨fun j ↦ a j • x, by simp [tmul_sum, smul_tmul]⟩
  | add x y hx hy =>
    obtain ⟨r, rfl⟩ := hx
    obtain ⟨r', rfl⟩ := hy
    exact ⟨r + r', by simp [add_tmul, Finset.sum_add_distrib]⟩

/-- **Relations after base change**: if `ρ` generates the relations of `b`, then every relation
`∑ j, r j ⊗ b j = 0` in `R ⊗[A] B` is an `R`-linear combination of the images of the `ρ l`. -/
lemma exists_eq_sum_of_sum_tmul_eq_zero (hb : Submodule.span A (Set.range b) = ⊤) {L : ℕ}
    (ρ : Fin L → Fin m → A)
    (hρ : ∀ v : Fin m → A, ∑ j, v j • b j = 0 ↔ v ∈ Submodule.span A (Set.range ρ))
    (r : Fin m → R) (hr : ∑ j, r j ⊗ₜ[A] b j = 0) :
    ∃ c : Fin L → R, ∀ j, r j = ∑ l, c l * algebraMap A R (ρ l j) := by
  classical
  let ψ : (Fin L → A) →ₗ[A] (Fin m → A) := Fintype.linearCombination A ρ
  let π : (Fin m → A) →ₗ[A] B := Fintype.linearCombination A b
  have hπ : Function.Surjective π := by
    rw [← LinearMap.range_eq_top, Fintype.range_linearCombination, hb]
  have hex : Function.Exact ψ π := by
    rw [LinearMap.exact_iff, Fintype.range_linearCombination]
    ext v
    rw [LinearMap.mem_ker, ← hρ]
    simp [π, Fintype.linearCombination_apply]
  let u : R ⊗[A] (Fin m → A) := ∑ j, r j ⊗ₜ Pi.single j 1
  have hu : LinearMap.lTensor R π u = 0 := by
    simp only [u, map_sum, LinearMap.lTensor_tmul]
    rw [← hr]
    refine Finset.sum_congr rfl fun j _ ↦ ?_
    simp [π, Fintype.linearCombination_apply, Pi.single_apply]
  obtain ⟨w, hw⟩ := (lTensor_exact R hex hπ u).1 hu
  let Θ : ∀ n : ℕ, R ⊗[A] (Fin n → A) →ₗ[A] (Fin n → R) := fun n ↦ piScalarRightHom A A R (Fin n)
  have hΘu : Θ m u = r := by
    funext j
    simp [u, Θ, Pi.single_apply]
  have hΘψ : ∀ w, Θ m (LinearMap.lTensor R ψ w) =
      fun j ↦ ∑ l, Θ L w l * algebraMap A R (ρ l j) := by
    intro w
    induction w using TensorProduct.induction_on with
    | zero => funext j; simp
    | tmul x c =>
      funext j
      simp only [Θ, ψ, LinearMap.lTensor_tmul, piScalarRightHom_tmul,
        Fintype.linearCombination_apply, Finset.sum_apply, Pi.smul_apply, smul_eq_mul,
        Finset.sum_smul]
      refine Finset.sum_congr rfl fun l _ ↦ ?_
      rw [_root_.Algebra.smul_def, _root_.Algebra.smul_def, map_mul]
      ring
    | add w w' hw hw' =>
      funext j
      simp only [map_add, Pi.add_apply, hw, hw', add_mul, Finset.sum_add_distrib]
  refine ⟨Θ L w, fun j ↦ ?_⟩
  rw [← hΘu, ← hw, hΘψ]

end TensorProduct

namespace ComplexAnalytic

open AnalyticSpace

noncomputable section

/-- **The analytification of an affine scheme of finite type is Hausdorff.** -/
lemma t2Space_analytification_of_isAffine (Y : SchemeLFTℂ.{u}) [IsAffine Y.obj.left] :
    T2Space (analytification.obj Y) := by
  obtain ⟨n, s, hsurj, hs⟩ := Y.exists_surjective
  obtain ⟨-, -, -, -, -, -, -, hinj⟩ := SchemeLFTℂ.exists_cutOut s hs hsurj
  exact T2Space.of_injective_continuous hinj
    (SchemeLFTℂ.anToAffine s hs).toLRSHom.base.hom.continuous

/-- **`q^an_* 𝒪_{Y^an}` is coherent** for a finite morphism `q : Y ⟶ S` of affine schemes of
finite type over `ℂ`. -/
theorem isCoherent_pushUnit_analytification_map {Y S : SchemeLFTℂ.{u}} [IsAffine Y.obj.left]
    [IsAffine S.obj.left] (q : Y ⟶ S) [AlgebraicGeometry.IsFinite q.hom.left] :
    (LocallyRingedSpace.Hom.pushUnit (analytification.map q).toLRSHom).IsCoherent := by
  classical
  letI := q.hom.left.appTop.hom.toAlgebra
  haveI : Module.Finite Γ(S.obj.left, ⊤) Γ(Y.obj.left, ⊤) := q.hom.left.finite_appTop
  haveI := isNoetherianRing_of_isAffine S
  haveI := t2Space_analytification_of_isAffine Y
  haveI := isFinite_analytification_map_of_isFinite q
  obtain ⟨m, b, hb⟩ := Module.Finite.exists_fin (R := Γ(S.obj.left, ⊤)) (M := Γ(Y.obj.left, ⊤))
  let π : (Fin m → Γ(S.obj.left, ⊤)) →ₗ[Γ(S.obj.left, ⊤)] Γ(Y.obj.left, ⊤) :=
    Fintype.linearCombination _ b
  obtain ⟨L, ρ, hρ⟩ := Submodule.fg_iff_exists_fin_generating_family.1
    (IsNoetherian.noetherian (LinearMap.ker π))
  have hρ' : ∀ v : Fin m → Γ(S.obj.left, ⊤), ∑ j, v j • b j = 0 ↔
      v ∈ Submodule.span Γ(S.obj.left, ⊤) (Set.range ρ) := fun v ↦ by
    rw [hρ, LinearMap.mem_ker]
    simp [π, Fintype.linearCombination_apply]
  -- the stalk maps are bijective
  have hbij : ∀ s, Function.Bijective (pushforwardStalkTensorMap (analytification.map q)
      (analytificationΓ Y) (analytificationΓ_naturality q) s) := fun s ↦ by
    have h1 := finiteAnalyticSplitting.{u} Y S q s
    have h2 := AnalyticSpace.bijective_pushforwardStalkToPi (analytification.map q) s
    have e : ⇑(stalkTensorMap (analytification.map q) (analytificationΓ Y)
        (analytificationΓ_naturality q) s) =
        TopCat.Presheaf.pushforwardStalkToPi (analytification.map q).toLRSHom.base
          (analytification.obj Y).presheaf s ∘ pushforwardStalkTensorMap (analytification.map q)
            (analytificationΓ Y) (analytificationΓ_naturality q) s :=
      funext fun x ↦ (pushforwardStalkToPi_pushforwardStalkTensorMap _ _ _ s x).symm
    rw [e] at h1
    exact ⟨h1.1.of_comp, fun z ↦ by
      obtain ⟨x, hx⟩ := h1.2 (TopCat.Presheaf.pushforwardStalkToPi _ _ s z)
      exact ⟨x, h2.1 hx⟩⟩
  refine LocallyRingedSpace.Hom.isCoherent_pushUnit_of_stalks _
    (analytification.obj S).hasLocalTupleRelations_unit fun s ↦
      ⟨⊤, m, L, fun j ↦ analytificationΓ Y (b j), fun l j ↦ analytificationΓ S (ρ l j), trivial,
        fun l ↦ ?_, fun s' _ z ↦ ?_, fun s' _ r hr ↦ ?_⟩
  · have hl : ρ l ∈ LinearMap.ker π := hρ ▸ Submodule.subset_span ⟨l, rfl⟩
    rw [LinearMap.mem_ker] at hl
    change ∑ j, (analytification.map q).pullbackΓ (analytificationΓ S (ρ l j)) *
      analytificationΓ Y (b j) = 0
    simp only [← analytificationΓ_naturality, ← map_mul, ← map_sum]
    rw [← map_zero (analytificationΓ Y), ← hl]
    simp [π, Fintype.linearCombination_apply, Algebra.smul_def, RingHom.algebraMap_toAlgebra]
  · obtain ⟨x, rfl⟩ := (hbij s').2 z
    obtain ⟨r, rfl⟩ := TensorProduct.exists_eq_sum_tmul_of_span_eq_top hb x
    exact ⟨r, by simp only [map_sum, pushforwardStalkTensorMap_tmul]; rfl⟩
  · have h0 : pushforwardStalkTensorMap (analytification.map q) (analytificationΓ Y)
        (analytificationΓ_naturality q) s' (∑ j, r j ⊗ₜ b j) = 0 := by
      simp only [map_sum, pushforwardStalkTensorMap_tmul]
      exact hr
    obtain ⟨c, hc⟩ := TensorProduct.exists_eq_sum_of_sum_tmul_eq_zero hb ρ hρ' r
      ((injective_iff_map_eq_zero _).1 (hbij s').1 _ h0)
    exact ⟨c, fun j ↦ (hc j).trans (Finset.sum_congr rfl fun l _ ↦ rfl)⟩

/-- **Finite mapping theorem for analytified finite morphisms**: for a finite morphism
`q : Y ⟶ S` of affine schemes of finite type over `ℂ`, `q^an_* M` is coherent for every coherent
`𝒪_{Y^an}`-module `M`. -/
theorem isCoherent_pushforward_analytification_map {Y S : SchemeLFTℂ.{u}} [IsAffine Y.obj.left]
    [IsAffine S.obj.left] (q : Y ⟶ S) [AlgebraicGeometry.IsFinite q.hom.left]
    (M : SheafOfModules.{u} (analytification.obj Y).toLocallyRingedSpace.ringSheaf)
    [M.IsCoherent] :
    ((SheafOfModules.pushforward.{u} (analytification.map q).toLRSHom.toRingSheafHom).obj
      M).IsCoherent := by
  haveI := isCoherent_pushUnit_analytification_map q
  haveI := t2Space_analytification_of_isAffine Y
  haveI := isFinite_analytification_map_of_isFinite q
  exact LocallyRingedSpace.Hom.isCoherent_pushforward_of_isClosedMap _ M IsFinite.isClosedMap
    fun y ↦ (haveI := IsFinite.finite_fiber (f := analytification.map q) y; Set.toFinite _)

/-- **`q^an_* p_* 𝒪_W` is coherent** for a finite morphism `q : Y ⟶ S` of affine schemes of finite
type over `ℂ` and a finite étale morphism `p : W ⟶ Y^an` with Hausdorff source. -/
theorem isCoherent_pushforward_pushUnit_of_isFiniteEtale {Y S : SchemeLFTℂ.{u}}
    [IsAffine Y.obj.left] [IsAffine S.obj.left] (q : Y ⟶ S)
    [AlgebraicGeometry.IsFinite q.hom.left] {W : AnalyticSpace.{u}}
    (p : W ⟶ analytification.obj Y) [IsFiniteEtale p] [T2Space W] :
    ((SheafOfModules.pushforward.{u} (analytification.map q).toLRSHom.toRingSheafHom).obj
      (LocallyRingedSpace.Hom.pushUnit p.toLRSHom)).IsCoherent := by
  haveI := AnalyticSpace.isCoherent_pushUnit_of_isFiniteEtale p
  exact isCoherent_pushforward_analytification_map q _

end

end ComplexAnalytic
