/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.Geometry.RingedSpace.LocallyRingedSpace.CoherentModuleSections
import Oka.Geometry.RingedSpace.LocallyRingedSpace.ModulesClosedEmbeddingKilled

/-!
# Pushforward of coherent sheaves along closed embeddings

Let `f : X ⟶ Y` be a morphism of locally ringed spaces whose underlying map is a closed embedding
and whose stalk maps are surjective, and suppose that the ideal of the image is *locally finitely
generated*: every point of `Y` has a neighbourhood `W` with finitely many sections `h_j` of `𝒪_Y`
over `W`, killed by `f^♯`, whose germs generate the ideal `f.pushforwardStalkIdeal y'` at every
point `y' ∈ W` (`AlgebraicGeometry.LocallyRingedSpace.Hom.HasLocallyFinitelyGeneratedIdeal`).

Then `f_* M` is coherent for every coherent sheaf of `𝒪_X`-modules `M`
(`AlgebraicGeometry.LocallyRingedSpace.Hom.isCoherent_pushforward_of_isClosedEmbedding`). No
coherence of `𝒪_Y` is needed. We verify the concrete criterion
`AlgebraicGeometry.LocallyRingedSpace.isCoherent_of_hasLocalModuleRelations`, using that `M`
satisfies it (`AlgebraicGeometry.LocallyRingedSpace.hasLocalModuleRelations_of_isCoherent`):

* sections of `𝒪_X` lift locally to sections of `𝒪_Y`, since the stalk maps are surjective and
  `f` is an embedding (`AlgebraicGeometry.LocallyRingedSpace.Hom.exists_app_eq_family`);
* generators of `M` near `x` generate `f_* M` near `f x`, and `f_* M` vanishes off the image;
* the relations between sections `f_i` of `f_* M` near `f x` are generated by lifts of generators
  of the relations of `M` near `x` together with the relations `h_j eᵢ`: a relation `a` of `f_* M`
  becomes a relation of `M` after applying `f^♯`, which is locally a combination of the generators;
  subtracting the lifted combination leaves a tuple killed by `f^♯`, whose germs lie in the ideal
  of the image, hence which is locally a combination of the `h_j`.
-/

open CategoryTheory Limits TopologicalSpace Opposite SheafOfModules AlgebraicGeometry Topology

universe u

noncomputable section

namespace AlgebraicGeometry.LocallyRingedSpace

section Germs

variable (Y : LocallyRingedSpace.{u})

/-- Finitely many local properties, each holding near `y` and stable under shrinking, hold
simultaneously near `y`. -/
lemma exists_open_forall {ι : Type*} [Finite ι] (y : Y) (P : ι → Opens Y → Prop)
    (hP : ∀ i W W', W' ≤ W → P i W → P i W') (h : ∀ i, ∃ W : Opens Y, y ∈ W ∧ P i W) :
    ∃ W : Opens Y, y ∈ W ∧ ∀ i, P i W := by
  choose W hyW hPW using h
  refine ⟨⟨⋂ i, (W i : Set Y), isOpen_iInter_of_finite fun i ↦ (W i).2⟩,
    Set.mem_iInter.2 hyW, fun i ↦ hP i _ _ (fun z hz ↦ Set.mem_iInter.1 hz i) (hPW i)⟩

/-- **From germs to sections**: if the germ at `y` of a section `r` lies in the ideal generated
by the germs of finitely many sections `h_j`, then near `y`, `r` is a linear combination of the
`h_j`. -/
lemma exists_eq_sum_of_germ_mem_span {U W : Opens Y} {p : ℕ} (h : Fin p → Y.presheaf.obj (op W))
    (r : Y.presheaf.obj (op U)) (y : Y) (hyU : y ∈ U) (hyW : y ∈ W)
    (hr : Y.presheaf.germ U y hyU r ∈
      Ideal.span (Set.range fun j ↦ Y.presheaf.germ W y hyW (h j))) :
    ∃ (W' : Opens Y) (hW'U : W' ≤ U) (hW'W : W' ≤ W) (d : Fin p → Y.presheaf.obj (op W')),
      y ∈ W' ∧ Y.res hW'U r = ∑ j, d j * Y.res hW'W (h j) := by
  classical
  obtain ⟨e, he⟩ := (Submodule.mem_span_range_iff_exists_fun _).1 hr
  choose V hyV t ht using fun j ↦ TopCat.Presheaf.exists_germ_eq Y.presheaf (e j)
  obtain ⟨V₀, hyV₀, hV₀⟩ := exists_open_forall Y y (fun j V' ↦ V' ≤ V j)
    (fun _ _ _ h₁ h₂ ↦ h₁.trans h₂) (fun j ↦ ⟨V j, hyV j, le_rfl⟩)
  set V₁ : Opens Y := V₀ ⊓ U ⊓ W
  have h₁U : V₁ ≤ U := inf_le_left.trans inf_le_right
  have h₁W : V₁ ≤ W := inf_le_right
  have h₁V : ∀ j, V₁ ≤ V j := fun j ↦ (inf_le_left.trans inf_le_left).trans (hV₀ j)
  have hyV₁ : y ∈ V₁ := ⟨⟨hyV₀, hyU⟩, hyW⟩
  have hgerm : Y.presheaf.germ V₁ y hyV₁ (Y.res h₁U r) =
      Y.presheaf.germ V₁ y hyV₁ (∑ j, Y.res (h₁V j) (t j) * Y.res h₁W (h j)) := by
    erw [TopCat.Presheaf.germ_res_apply]
    rw [← he, map_sum]
    refine Finset.sum_congr rfl fun j _ ↦ ?_
    rw [map_mul]
    erw [TopCat.Presheaf.germ_res_apply, TopCat.Presheaf.germ_res_apply, ht j]
    rfl
  obtain ⟨V₂, hyV₂, i₁, i₂, heq⟩ := TopCat.Presheaf.germ_eq _ y hyV₁ hyV₁ _ _ hgerm
  have h₂ : V₂ ≤ V₁ := leOfHom i₁
  refine ⟨V₂, h₂.trans h₁U, h₂.trans h₁W, fun j ↦ Y.res (h₂.trans (h₁V j)) (t j), hyV₂, ?_⟩
  have e₁ : Y.res (h₂.trans h₁U) r = Y.res h₂ (Y.res h₁U r) := (res_res _ _ _ _).symm
  rw [e₁]
  change Y.presheaf.map i₁.op _ = _
  rw [heq]
  change Y.res h₂ _ = _
  rw [res_sum]
  refine Finset.sum_congr rfl fun j _ ↦ ?_
  rw [res_mul, res_res, res_res]

end Germs

section Lift

variable {X Y : LocallyRingedSpace.{u}} (f : X ⟶ Y)

/-- `f^♯` commutes with restriction. -/
lemma Hom.c_app_res {U V : Opens Y} (h : U ≤ V) (r : Y.presheaf.obj (op V)) :
    f.c.app (op U) (Y.res h r) =
      X.res ((Opens.map f.base).monotone h) (f.c.app (op V) r) :=
  congrArg (fun φ ↦ φ r) (congrArg CommRingCat.Hom.hom (f.c.naturality (homOfLE h).op))

/-- **Lifting sections along `f`**: if `f` is inducing with surjective stalk maps, a section of
`𝒪_X` near `x` is, near `x`, the pullback of a section of `𝒪_Y` near `f x`. -/
lemma Hom.exists_app_eq (hf : IsInducing f.base) (hs : ∀ x, Function.Surjective (f.stalkMap x))
    {U : Opens X} (x : X) (hx : x ∈ U) (c : X.presheaf.obj (op U)) :
    ∃ (W : Opens Y) (hW : (Opens.map f.base).obj W ≤ U) (d : Y.presheaf.obj (op W)),
      f.base x ∈ W ∧ f.c.app (op W) d = X.res hW c := by
  obtain ⟨r, hr⟩ := hs x (X.presheaf.germ U x hx c)
  obtain ⟨W₀, hW₀, d₀, rfl⟩ := TopCat.Presheaf.exists_germ_eq Y.presheaf r
  rw [stalkMap_germ_apply] at hr
  obtain ⟨U₁, hxU₁, i₁, i₂, heq⟩ := TopCat.Presheaf.germ_eq _ x hW₀ hx _ _ hr
  obtain ⟨W₁, hW₁, hpre⟩ := hf.isOpen_iff.1 U₁.2
  let W : Opens Y := ⟨W₁, hW₁⟩ ⊓ W₀
  have hWU₁ : (Opens.map f.base).obj W ≤ U₁ := fun z hz ↦ by
    have : z ∈ f.base ⁻¹' W₁ := hz.1
    rw [hpre] at this
    exact this
  have hxW : f.base x ∈ W := ⟨by
    have : x ∈ f.base ⁻¹' W₁ := by rw [hpre]; exact hxU₁
    exact this, hW₀⟩
  refine ⟨W, hWU₁.trans (leOfHom i₂), Y.res inf_le_right d₀, hxW, ?_⟩
  rw [Hom.c_app_res]
  have e₁ : X.res ((Opens.map f.base).monotone (inf_le_right : W ≤ W₀))
      (f.c.app (op W₀) d₀) = X.res hWU₁ (X.presheaf.map i₁.op (f.c.app (op W₀) d₀)) :=
    (res_res _ _ _ _).symm
  have e₂ : X.res (hWU₁.trans (leOfHom i₂)) c = X.res hWU₁ (X.presheaf.map i₂.op c) :=
    (res_res _ _ _ _).symm
  rw [e₁, e₂, heq]

/-- **Lifting finitely many sections along `f`** at once. -/
lemma Hom.exists_app_eq_family (hf : IsInducing f.base)
    (hs : ∀ x, Function.Surjective (f.stalkMap x)) {ι : Type*} [Finite ι]
    {U : Opens X} (x : X) (hx : x ∈ U) (c : ι → X.presheaf.obj (op U)) :
    ∃ (W : Opens Y) (hW : (Opens.map f.base).obj W ≤ U) (d : ι → Y.presheaf.obj (op W)),
      f.base x ∈ W ∧ ∀ i, f.c.app (op W) (d i) = X.res hW (c i) := by
  obtain ⟨W₁, hW₁, hpre⟩ := hf.isOpen_iff.1 U.2
  obtain ⟨W₀, hxW₀, hW₀⟩ := exists_open_forall Y (f.base x)
    (fun i W ↦ ∃ (hW : (Opens.map f.base).obj W ≤ U) (d : Y.presheaf.obj (op W)),
      f.c.app (op W) d = X.res hW (c i))
    (fun i W W' hle ⟨hW, d, hd⟩ ↦ ⟨((Opens.map f.base).monotone hle).trans hW,
      Y.res hle d, by rw [Hom.c_app_res, hd, res_res]⟩)
    (fun i ↦ by
      obtain ⟨W, hW, d, hxW, hd⟩ := f.exists_app_eq hf hs x hx (c i)
      exact ⟨W, hxW, hW, d, hd⟩)
  let W : Opens Y := W₀ ⊓ ⟨W₁, hW₁⟩
  have hWU : (Opens.map f.base).obj W ≤ U := fun z hz ↦ by
    have : z ∈ f.base ⁻¹' W₁ := hz.2
    rw [hpre] at this
    exact this
  have hxW : f.base x ∈ W := ⟨hxW₀, by
    have : x ∈ f.base ⁻¹' W₁ := by rw [hpre]; exact hx
    exact this⟩
  choose hW d hd using hW₀
  refine ⟨W, hWU, fun i ↦ Y.res inf_le_left (d i), hxW, fun i ↦ ?_⟩
  rw [Hom.c_app_res, hd, res_res]

end Lift

section Pushforward

variable {X Y : LocallyRingedSpace.{u}} (f : X ⟶ Y)

/-- **The ideal of the image of `f` is locally finitely generated**: every point of `Y` has a
neighbourhood `W` with finitely many sections of `𝒪_Y` over `W`, killed by `f^♯`, whose germs
generate the ideal `f.pushforwardStalkIdeal y'` at every point `y' ∈ W`. -/
def Hom.HasLocallyFinitelyGeneratedIdeal : Prop :=
  ∀ y : Y, ∃ (W : Opens Y) (p : ℕ) (h : Fin p → Y.presheaf.obj (op W)), y ∈ W ∧
    (∀ j, f.c.app (op W) (h j) = 0) ∧
    ∀ (y' : Y) (hy' : y' ∈ W), f.pushforwardStalkIdeal y' ≤
      Ideal.span (Set.range fun j ↦ Y.presheaf.germ W y' hy' (h j))

variable (M : SheafOfModules.{u} X.ringSheaf)

/-- Sections of a sheaf of modules over the empty open vanish. -/
lemma subsingleton_val_obj_of_eq_bot {U : Opens X} (hU : U = ⊥) :
    Subsingleton (M.val.obj (op U)) :=
  AddCommGrpCat.isZero_iff_subsingleton.1
    (TopCat.Sheaf.isTerminalOfEqEmpty ((SheafOfModules.toSheaf _).obj M) hU).isZero

variable {f}

/-- Off the closed image of `f`, sections of `f_* M` vanish. -/
lemma subsingleton_pushforward_val_obj {W : Opens Y} (hW : ∀ y ∈ W, y ∉ Set.range f.base) :
    Subsingleton (((SheafOfModules.pushforward.{u} f.toRingSheafHom).obj M).val.obj (op W)) :=
  subsingleton_val_obj_of_eq_bot M (U := (Opens.map f.base).obj W)
    (eq_bot_iff.2 fun x hx ↦ hW _ hx ⟨x, rfl⟩)

/-- The complement of the closed image of `f`. -/
abbrev Hom.rangeCompl (hf : IsClosed (Set.range f.base)) : Opens Y :=
  ⟨(Set.range f.base)ᶜ, hf.isOpen_compl⟩

/-- **Generators of `M` give generators of `f_* M`.** -/
lemma Hom.isLocallyFinitelyGeneratedModule_pushforward (hf : IsClosedEmbedding f.base)
    (hs : ∀ x, Function.Surjective (f.stalkMap x)) (hM : IsLocallyFinitelyGeneratedModule M) :
    IsLocallyFinitelyGeneratedModule
      ((SheafOfModules.pushforward.{u} f.toRingSheafHom).obj M) := by
  have hoff : ∀ (W' : Opens Y) (t : ((SheafOfModules.pushforward.{u}
      f.toRingSheafHom).obj M).val.obj (op W')) (y : Y), y ∈ W' → y ∉ Set.range f.base →
      ∀ (k : ℕ) (W : Opens Y) (hW' : W' ≤ W)
        (s : Fin k → ((SheafOfModules.pushforward.{u} f.toRingSheafHom).obj M).val.obj (op W)),
      ∃ (W'' : Opens Y) (hW'' : W'' ≤ W'), y ∈ W'' ∧ ∃ c : Fin k → Y.presheaf.obj (op W''),
        sectRes _ hW'' t = ∑ l, c l • sectRes _ (hW''.trans hW') (s l) := by
    intro W' t y hy hy' k W hW' s
    haveI := subsingleton_pushforward_val_obj M (W := W' ⊓ f.rangeCompl hf.isClosed_range)
      fun z hz ↦ hz.2
    exact ⟨W' ⊓ f.rangeCompl hf.isClosed_range, inf_le_left, ⟨hy, hy'⟩, 0,
      Subsingleton.elim _ _⟩
  intro y
  by_cases hy : y ∉ Set.range f.base
  · exact ⟨f.rangeCompl hf.isClosed_range, 0, ![], hy,
      fun W' hW' t y' hy' ↦ hoff W' t y' hy' (hW' hy') 0 _ hW' ![]⟩
  rw [not_not] at hy
  obtain ⟨x, rfl⟩ := hy
  obtain ⟨U, k, s, hxU, hgen⟩ := hM x
  obtain ⟨W₁, hW₁, hpre⟩ := hf.isInducing.isOpen_iff.1 U.2
  let W : Opens Y := ⟨W₁, hW₁⟩
  have hWU : (Opens.map f.base).obj W ≤ U := fun z hz ↦ by
    have : z ∈ f.base ⁻¹' W₁ := hz
    rw [hpre] at this
    exact this
  have hxW : f.base x ∈ W := by
    have : x ∈ f.base ⁻¹' W₁ := by rw [hpre]; exact hxU
    exact this
  refine ⟨W, k, fun l ↦ sectRes M hWU (s l), hxW, fun W' hW' t y' hy' ↦ ?_⟩
  by_cases hy'' : y' ∉ Set.range f.base
  · exact hoff W' t y' hy' hy'' k W hW' _
  rw [not_not] at hy''
  obtain ⟨x', rfl⟩ := hy''
  obtain ⟨U'', hU'', hxU'', c', hc'⟩ := hgen ((Opens.map f.base).obj W')
    (((Opens.map f.base).monotone hW').trans hWU) t x' hy'
  obtain ⟨W₂, hW₂, c, hxW₂, hc⟩ := f.exists_app_eq_family hf.isInducing hs x' hxU'' c'
  have hle : (Opens.map f.base).obj (W₂ ⊓ W') ≤ U'' := fun z hz ↦ hW₂ hz.1
  refine ⟨W₂ ⊓ W', inf_le_right, ⟨hxW₂, hy'⟩, fun l ↦ Y.res inf_le_left (c l), ?_⟩
  change sectRes M ((Opens.map f.base).monotone (inf_le_right : W₂ ⊓ W' ≤ W')) t =
    ∑ l, (show X.presheaf.obj (op ((Opens.map f.base).obj (W₂ ⊓ W'))) from
      f.c.app (op (W₂ ⊓ W')) (Y.res (inf_le_left : W₂ ⊓ W' ≤ W₂) (c l))) •
      (show M.val.obj (op ((Opens.map f.base).obj (W₂ ⊓ W'))) from
        sectRes M ((Opens.map f.base).monotone ((inf_le_right : W₂ ⊓ W' ≤ W').trans hW'))
          (sectRes M hWU (s l)))
  dsimp only
  refine (sectRes_sectRes M hle hU'' t).symm.trans ?_
  rw [hc', sectRes_sum]
  refine Finset.sum_congr rfl fun l _ ↦ ?_
  rw [sectRes_smul, sectRes_sectRes, sectRes_sectRes, Hom.c_app_res, hc l, res_res]

/-- Off the closed image of `f`, the relations of `f_* M` are generated by the standard basis. -/
lemma Hom.hasLocalModuleRelations_pushforward_of_not_mem (hf : IsClosed (Set.range f.base))
    (V : Opens Y) (m : ℕ)
    (fs : Fin m → ((SheafOfModules.pushforward.{u} f.toRingSheafHom).obj M).val.obj (op V))
    (y : Y) (hyV : y ∈ V) (hy : y ∉ Set.range f.base) :
    ∃ (W : Opens Y) (hWV : W ≤ V) (k : ℕ) (g : Fin k → (Fin m → Y.presheaf.obj (op W))),
      y ∈ W ∧ (∀ l, ∑ i, g l i • sectRes _ hWV (fs i) = 0) ∧
      ∀ (W' : Opens Y) (hW' : W' ≤ W) (a : Fin m → Y.presheaf.obj (op W')),
        (∑ i, a i • sectRes _ (hW'.trans hWV) (fs i) = 0) → ∀ y ∈ W',
          ∃ (W'' : Opens Y) (hW'' : W'' ≤ W'), y ∈ W'' ∧
            ∃ c : Fin k → Y.presheaf.obj (op W''),
              ∀ i, Y.res hW'' (a i) = ∑ l, c l * Y.res (hW''.trans hW') (g l i) := by
  classical
  haveI := subsingleton_pushforward_val_obj M (W := V ⊓ f.rangeCompl hf) fun z hz ↦ hz.2
  refine ⟨V ⊓ f.rangeCompl hf, inf_le_left, m, fun l i ↦ if l = i then 1 else 0, ⟨hyV, hy⟩,
    fun l ↦ Subsingleton.elim _ _, fun W' hW' a _ y' hy' ↦ ⟨W', le_rfl, hy', a, fun i ↦ ?_⟩⟩
  dsimp only
  rw [Finset.sum_eq_single i (fun b _ hb ↦ by rw [if_neg hb, res_zero, mul_zero])
    (by simp), if_pos rfl, res_self]
  exact (mul_one _).symm.trans (congrArg _ (map_one _).symm)

/-- Near a point `f x` of the image, the relations of `f_* M` are generated by lifts of
generators of the relations of `M` near `x` and by the relations `h_j eᵢ`, for local generators
`h_j` of the ideal of the image. -/
lemma Hom.hasLocalModuleRelations_pushforward_of_mem (hf : IsClosedEmbedding f.base)
    (hs : ∀ x, Function.Surjective (f.stalkMap x)) (hI : f.HasLocallyFinitelyGeneratedIdeal)
    (hM : HasLocalModuleRelations M) (V : Opens Y) (m : ℕ)
    (fs : Fin m → ((SheafOfModules.pushforward.{u} f.toRingSheafHom).obj M).val.obj (op V))
    (x : X) (hxV : f.base x ∈ V) :
    ∃ (W : Opens Y) (hWV : W ≤ V) (k : ℕ) (g : Fin k → (Fin m → Y.presheaf.obj (op W))),
      f.base x ∈ W ∧ (∀ l, ∑ i, g l i • sectRes _ hWV (fs i) = 0) ∧
      ∀ (W' : Opens Y) (hW' : W' ≤ W) (a : Fin m → Y.presheaf.obj (op W')),
        (∑ i, a i • sectRes _ (hW'.trans hWV) (fs i) = 0) → ∀ y ∈ W',
          ∃ (W'' : Opens Y) (hW'' : W'' ≤ W'), y ∈ W'' ∧
            ∃ c : Fin k → Y.presheaf.obj (op W''),
              ∀ i, Y.res hW'' (a i) = ∑ l, c l * Y.res (hW''.trans hW') (g l i) := by
  classical
  obtain ⟨WX, hWX, k', g', hxWX, hrelM, hgenM⟩ := hM ((Opens.map f.base).obj V) m fs x hxV
  obtain ⟨WI, p, h, hxWI, hkill, hspan⟩ := hI (f.base x)
  obtain ⟨Wg, hWg, d, hxWg, hd⟩ := f.exists_app_eq_family hf.isInducing hs x hxWX
    (fun li : Fin k' × Fin m ↦ g' li.1 li.2)
  let W : Opens Y := Wg ⊓ WI ⊓ V
  have hWV : W ≤ V := inf_le_right
  have hWWg : W ≤ Wg := inf_le_left.trans inf_le_left
  have hWWI : W ≤ WI := inf_le_left.trans inf_le_right
  let ι := Fin k' ⊕ (Fin p × Fin m)
  let e : ι ≃ Fin (Fintype.card ι) := Fintype.equivFin ι
  let G : ι → Fin m → Y.presheaf.obj (op W) := fun r i ↦ match r with
    | Sum.inl l => Y.res hWWg (d (l, i))
    | Sum.inr (j, i') => if i' = i then Y.res hWWI (h j) else 0
  refine ⟨W, hWV, Fintype.card ι, fun l ↦ G (e.symm l), ⟨⟨hxWg, hxWI⟩, hxV⟩, fun l ↦ ?_, ?_⟩
  · have hle : (Opens.map f.base).obj W ≤ WX := ((Opens.map f.base).monotone hWWg).trans hWg
    suffices H : ∀ r : ι, ∑ i, G r i •
        sectRes ((SheafOfModules.pushforward.{u} f.toRingSheafHom).obj M) hWV (fs i) = 0 from
      H (e.symm l)
    rintro (l' | ⟨j, i'⟩)
    · have key : ∀ i, Y.res hWWg (d (l', i)) •
          sectRes ((SheafOfModules.pushforward.{u} f.toRingSheafHom).obj M) hWV (fs i) =
          sectRes M hle (g' l' i • sectRes M hWX (fs i)) := by
        intro i
        change (show X.presheaf.obj (op ((Opens.map f.base).obj W)) from
          f.c.app (op W) (Y.res hWWg (d (l', i)))) •
          (show M.val.obj (op ((Opens.map f.base).obj W)) from
            sectRes M ((Opens.map f.base).monotone hWV) (fs i)) = _
        dsimp only
        rw [sectRes_smul, sectRes_sectRes, Hom.c_app_res, hd, res_res]
      dsimp only [G]
      rw [Finset.sum_congr rfl fun i _ ↦ key i]
      exact (sectRes_sum M hle _ _).symm.trans ((congrArg _ (hrelM l')).trans
        (sectRes_zero M hle))
    · dsimp only [G]
      rw [Finset.sum_eq_single i' (fun b _ hb ↦ by rw [if_neg (Ne.symm hb), zero_smul])
        (by simp), if_pos rfl]
      change (show X.presheaf.obj (op ((Opens.map f.base).obj W)) from
        f.c.app (op W) (Y.res hWWI (h j))) •
        (show M.val.obj (op ((Opens.map f.base).obj W)) from
          sectRes M ((Opens.map f.base).monotone hWV) (fs i')) = 0
      dsimp only
      rw [Hom.c_app_res, hkill j]
      erw [res_zero, zero_smul]
  intro W' hW' a hrel y' hy'
  have hW'X : (Opens.map f.base).obj W' ≤ WX :=
    ((Opens.map f.base).monotone (hW'.trans hWWg)).trans hWg
  -- Step 1: subtract a lifted combination of the relations of `M`
  obtain ⟨W4, h4, hy4, c, hc⟩ : ∃ (W4 : Opens Y) (h4 : W4 ≤ W') (hy4 : y' ∈ W4),
      ∃ c : Fin k' → Y.presheaf.obj (op W4), ∀ i,
        Y.presheaf.germ W4 y' hy4 (Y.res h4 (a i) -
          ∑ l, c l * Y.res (h4.trans (hW'.trans hWWg)) (d (l, i))) ∈
            f.pushforwardStalkIdeal y' := by
    by_cases hy'' : y' ∉ Set.range f.base
    · refine ⟨W', le_rfl, hy', 0, fun i ↦ ?_⟩
      rw [f.pushforwardStalkIdeal_eq_top hf.isClosed_range y' hy'']
      exact Submodule.mem_top
    rw [not_not] at hy''
    obtain ⟨x', rfl⟩ := hy''
    obtain ⟨U'', hU'', hxU'', c', hc'⟩ := hgenM ((Opens.map f.base).obj W') hW'X
      (fun i ↦ f.c.app (op W') (a i)) hrel x' hy'
    obtain ⟨W3, hW3, c3, hxW3, hc3⟩ := f.exists_app_eq_family hf.isInducing hs x' hxU'' c'
    refine ⟨W3 ⊓ W', inf_le_right, ⟨hxW3, hy'⟩, fun l ↦ Y.res inf_le_left (c3 l),
      fun i ↦ f.germ_mem_pushforwardStalkIdeal _ _ _ ?_⟩
    have hle : (Opens.map f.base).obj (W3 ⊓ W') ≤ U'' :=
      ((Opens.map f.base).monotone inf_le_left).trans hW3
    have e₂ := congrArg (X.res hle) (hc' i)
    rw [res_res, res_sum] at e₂
    simp only [res_mul, res_res] at e₂
    erw [map_sub, map_sum, sub_eq_zero]
    refine Eq.trans ?_ (e₂.trans (Finset.sum_congr rfl fun l _ ↦ ?_))
    · erw [Hom.c_app_res]
      rfl
    · erw [map_mul, Hom.c_app_res, Hom.c_app_res, hc3, hd, res_res, res_res]
      rfl
  -- Step 2: the remainder is locally a combination of the `h_j`
  have hy'WI : y' ∈ WI := hWWI (hW' hy')
  let b : Fin m → Y.presheaf.obj (op W4) := fun i ↦ Y.res h4 (a i) -
    ∑ l, c l * Y.res (h4.trans (hW'.trans hWWg)) (d (l, i))
  let P : Fin m → Opens Y → Prop := fun i W'' ↦ ∃ (h1 : W'' ≤ W4) (h2 : W'' ≤ WI)
    (D : Fin p → Y.presheaf.obj (op W'')), Y.res h1 (b i) = ∑ j, D j * Y.res h2 (h j)
  have hPmono : ∀ i W'' W''', W''' ≤ W'' → P i W'' → P i W''' := by
    rintro i W'' W''' hle ⟨h1, h2, D, hD⟩
    refine ⟨hle.trans h1, hle.trans h2, fun j ↦ Y.res hle (D j), ?_⟩
    rw [← res_res _ hle h1, hD, res_sum]
    simp only [res_mul, res_res]
  obtain ⟨W5, hy5, hP5⟩ := exists_open_forall Y y' P hPmono fun i ↦ by
    obtain ⟨W'', h1, h2, D, hy'', hD⟩ :=
      exists_eq_sum_of_germ_mem_span Y h (b i) y' hy4 hy'WI (hspan y' hy'WI (hc i))
    exact ⟨W'', hy'', h1, h2, D, hD⟩
  obtain ⟨W6, h65, h64, hy6⟩ : ∃ W6 : Opens Y, W6 ≤ W5 ∧ W6 ≤ W4 ∧ y' ∈ W6 :=
    ⟨W5 ⊓ W4, inf_le_left, inf_le_right, hy5, hy4⟩
  have hP6 : ∀ i, P i W6 := fun i ↦ hPmono i _ _ h65 (hP5 i)
  choose h1 h2 D hD using hP6
  -- Step 3: assemble the coefficients
  have h6 : W6 ≤ W' := h64.trans h4
  let C : ι → Y.presheaf.obj (op W6) := fun r ↦ match r with
    | Sum.inl l => Y.res h64 (c l)
    | Sum.inr (j, i') => D i' j
  refine ⟨W6, h6, hy6, fun l ↦ C (e.symm l), fun i ↦ ?_⟩
  dsimp only
  rw [Equiv.sum_comp e.symm (fun r : ι ↦ C r * Y.res (h6.trans hW') (G r i)),
    Fintype.sum_sum_type, Fintype.sum_prod_type]
  have hinr : ∀ j, ∑ i', C (Sum.inr (j, i')) * Y.res (h6.trans hW') (G (Sum.inr (j, i')) i) =
      D i j * Y.res (h2 i) (h j) := by
    intro j
    rw [Finset.sum_eq_single i (fun b _ hb ↦ by
      simp only [C, G, if_neg hb, res_zero, mul_zero]) (by simp)]
    simp only [C, G, if_pos rfl, res_res]
  rw [Finset.sum_congr rfl fun j _ ↦ hinr j, ← hD i]
  have res_sub : ∀ {U U' : Opens Y} (hU : U ≤ U') (s t : Y.presheaf.obj (op U')),
      Y.res hU (s - t) = Y.res hU s - Y.res hU t := fun _ s t ↦ map_sub _ s t
  simp only [C, G, b, res_sub, res_res, res_sum, res_mul]
  ring

/-- **Relations of `M` give relations of `f_* M`.** -/
lemma Hom.hasLocalModuleRelations_pushforward (hf : IsClosedEmbedding f.base)
    (hs : ∀ x, Function.Surjective (f.stalkMap x)) (hI : f.HasLocallyFinitelyGeneratedIdeal)
    (hM : HasLocalModuleRelations M) :
    HasLocalModuleRelations ((SheafOfModules.pushforward.{u} f.toRingSheafHom).obj M) := by
  intro V m fs y hy
  by_cases h : y ∈ Set.range f.base
  · obtain ⟨x, rfl⟩ := h
    exact f.hasLocalModuleRelations_pushforward_of_mem M hf hs hI hM V m fs x hy
  · exact hasLocalModuleRelations_pushforward_of_not_mem M hf.isClosed_range V m fs y hy h

/-- **Pushforward along a closed embedding with surjective stalk maps and locally finitely
generated ideal preserves coherence.** -/
theorem Hom.isCoherent_pushforward_of_isClosedEmbedding (hf : IsClosedEmbedding f.base)
    (hs : ∀ x, Function.Surjective (f.stalkMap x)) (hI : f.HasLocallyFinitelyGeneratedIdeal)
    [M.IsCoherent] : ((SheafOfModules.pushforward.{u} f.toRingSheafHom).obj M).IsCoherent :=
  isCoherent_of_hasLocalModuleRelations _
    (f.isLocallyFinitelyGeneratedModule_pushforward M hf hs
      (isLocallyFinitelyGeneratedModule_of_isFiniteType M))
    (f.hasLocalModuleRelations_pushforward M hf hs hI (hasLocalModuleRelations_of_isCoherent M))

end Pushforward

end AlgebraicGeometry.LocallyRingedSpace
