/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.Analytification.RET.ES.CapExtension.GapCriterion
import Oka.Analytification.RET.ES.EvaluationCramer
import Oka.Nullstellensatz.Minors

/-!
# Uniform generators of bounded sections from an increasing chain

Keep the notation of `Oka/Analytification/RET/ES/CapExtension/GapCriterion.lean`. Let `U ⊆ N` be
open with `U` connected, and let `σₙ`, `n ∈ ℕ`, be finite families of sections of `𝒜` over `U`
such that near every point `y` of `U` off a set `Z`, the families `σₙ` generate `𝒜` for all large
`n` (depending on `y`). Then near every point of `U` a single finite family generates `𝒜` at all
points off `Z` (`ComplexAnalytic.BoundedSections.exists_generatesNear_of_chain`).

## Proof

The trace pairing against one family `t` generating `𝒜` near a point `y₀ ∈ N°` embeds `𝒜|_U`
into `𝒪_U^k` (`ComplexAnalytic.BoundedSections.eq_zero_of_trace_eq_zero_of_generatesNear`): at
`y₀` the values of `t` on the fibre span `ℂ^d`, so a Gram determinant `δ` of `t` does not vanish at
`y₀`; wherever `δ ≠ 0` the values of `t` span the fibre (the number of sheets is constant), so a
section with vanishing traces vanishes there, and `{δ ≠ 0}` is dense. The images of the spans of
`σ₀, …, σₙ` form an increasing chain of subsheaves of `𝒪^k` generated by finitely many sections
over `U`, which is stationary near every point by the Noether property
(`OkaRing.exists_forall_ge_eq_of_monotone`).

## Main results

- `ComplexAnalytic.BoundedSections.eq_zero_of_trace_eq_zero_of_generatesNear`: non-degeneracy of
  the trace pairing against local generators at one point.
- `ComplexAnalytic.BoundedSections.exists_generatesNear_of_chain`: uniform generators.
-/

open CategoryTheory Opposite AlgebraicGeometry Topology TopologicalSpace Filter Set
open scoped Matrix

universe u

namespace ComplexAnalytic.BoundedSections

open AnalyticSpace AlgebraicGeometry.LocallyRingedSpace OkaRing

noncomputable section

variable {n : ℕ} {N N₀ : (AnalyticSpace.complexAffineSpace.{u} n).Opens} (h₀ : N₀ ≤ N)
  (W : FiniteEtaleOver (space N₀))

/-- The values of a combination of sections of `𝒜`. -/
lemma evalFun_sum_smul {V : (space N).Opens} {L : ℕ} (c : Fin L → (space N).presheaf.obj (op V))
    (a : Fin L → (boundedModule h₀ W).val.obj (op V)) {w : W.left} (hw : w ∈ preim h₀ W V) :
    evalFun (secVal h₀ W (∑ l, c l • a l)) w =
      ∑ l, holFun (c l) (pt W w) * evalFun (secVal h₀ W (a l)) w := by
  rw [secVal_sum, evalFun_of_mem _ hw, map_sum]
  refine Finset.sum_congr rfl fun l _ ↦ ?_
  rw [secVal_smul, map_mul, ← evalFun_of_mem _ hw, ← evalFun_of_mem _ hw,
    evalFun_pullback h₀ W _ hw]

variable [T2Space W.left] (hD : HasThinComplement N N₀)

/-- The trace of a section at a point of `N°` is the sum of its values on the fibre. -/
lemma holFun_trace_mulSec {V : (space N).Opens} (a b : (boundedModule h₀ W).val.obj (op V))
    {x : Cn.{u} n} (hx : x ∈ img V) (hxN : x ∈ N₀) :
    holFun (trace h₀ W hD (mulSec h₀ W a b)) x = ∑ w ∈ fiberFinset W x,
      evalFun (secVal h₀ W a) w * evalFun (secVal h₀ W b) w := by
  rw [holFun_trace _ _ _ _ hx hxN, traceFun]
  refine Finset.sum_congr rfl fun w hw ↦ ?_
  have hw' : w ∈ preim h₀ W V := (mem_preim_iff h₀ W).2 ((mem_fiberFinset W).1 hw ▸ hx)
  rw [secVal_mulSec, evalFun_mul W _ _ hw']

/-- **The trace pairing against local generators at one point is non-degenerate.** Let `U ⊆ N`
be open with `U` connected and let `t₁, …, t_k ∈ 𝒜(U)` generate `𝒜` near a point `y₀ ∈ N°`. A
section `a` of `𝒜` over `V ⊆ U` with `tr(a tⱼ) = 0` for all `j` vanishes. -/
theorem eq_zero_of_trace_eq_zero_of_generatesNear {U : (space N).Opens}
    (hU : IsPreconnected (img U : Set (Cn.{u} n))) {k : ℕ}
    (t : Fin k → (boundedModule h₀ W).val.obj (op U)) {y₀ : space N} (hy₀ : y₀.1 ∈ N₀)
    (hgen : GeneratesNear h₀ W t y₀) {V : (space N).Opens} (hV : V ≤ U)
    (a : (boundedModule h₀ W).val.obj (op V))
    (ha : ∀ j, trace h₀ W hD (mulSec h₀ W a (sectRes (boundedModule h₀ W) hV (t j))) = 0) :
    a = 0 := by
  classical
  obtain ⟨V', hV'U, hy₀V', hspan⟩ := hgen
  set F₀ := fiberFinset W y₀.1
  have hy₀U : y₀.1 ∈ img U := mem_img_iff.2 ⟨y₀.2, hV'U hy₀V'⟩
  -- the values of `t` on the fibre over `y₀`
  set A : Matrix F₀ (Fin k) ℂ := Matrix.of fun w i ↦ evalFun (secVal h₀ W (t i)) w.1
  have hind : ∀ w : F₀, ∃ c : Fin k → ℂ, ∀ w' : F₀,
      (if w' = w then (1 : ℂ) else 0) = ∑ i, A w' i * c i := by
    intro w
    obtain ⟨B, hBo, hwB, hBN, hind⟩ := exists_indicator W w.1
    have hptw : pt W w.1 = y₀.1 := (mem_fiberFinset W).1 w.2
    let VB : (space N).Opens := ⟨Subtype.val ⁻¹' B, hBo.preimage continuous_subtype_val⟩
    let V₁ : (space N).Opens := V' ⊓ VB
    obtain ⟨b, hb⟩ := hind (preim h₀ W V₁) fun w' hw' ↦ by
      obtain ⟨_, h⟩ := mem_img_iff.1 ((mem_preim_iff h₀ W).1 hw')
      exact h.2
    have hbmem : b ∈ boundedSubring h₀ W V₁ := by
      rw [boundedSubring_eq_top h₀ W fun z (hz : z ∈ V₁) ↦ hBN _ hz.2]
      trivial
    obtain ⟨V'', hV''V₁, hy₀V'', f, hf⟩ := hspan V₁ inf_le_left (mkSec h₀ W b hbmem) y₀
      ⟨hy₀V', show y₀.1 ∈ B from hptw ▸ hwB⟩
    refine ⟨fun i ↦ holFun (f i) y₀.1, fun w' ↦ ?_⟩
    have hptw' : pt W w'.1 = y₀.1 := (mem_fiberFinset W).1 w'.2
    have hw'V'' : w'.1 ∈ preim h₀ W V'' :=
      (mem_preim_iff h₀ W).2 (hptw' ▸ mem_img_iff.2 ⟨y₀.2, hy₀V''⟩)
    have h1 := congrArg (fun c ↦ evalFun (secVal h₀ W c) w'.1) hf
    rw [evalFun_sum_smul h₀ W _ _ hw'V'', secVal_map, evalFun_map W _ _ hw'V'', secVal_mkSec,
      hb w'.1 (preim_mono h₀ W hV''V₁ hw'V'') (hptw'.trans hptw.symm)] at h1
    rw [show (if w' = w then (1 : ℂ) else 0) = if w'.1 = w.1 then 1 else 0 from
      if_congr Subtype.ext_iff rfl rfl, h1]
    refine Finset.sum_congr rfl fun i _ ↦ ?_
    rw [secVal_map, evalFun_map W _ _ hw'V'', hptw', mul_comm]
    rfl
  choose c hc using hind
  have hAC : A * Matrix.of (fun i w ↦ c w i) = 1 := by
    ext w' w
    rw [Matrix.mul_apply, Matrix.one_apply, hc w w']
    rfl
  obtain ⟨σ, hσ⟩ := Matrix.exists_isUnit_det_submatrix_of_mul_eq_one hAC
  -- the Gram determinant
  set δ : Cn.{u} n → ℂ := fun y ↦ (Matrix.of fun p q : F₀ ↦
    holFun (trace h₀ W hD (mulSec h₀ W (t (σ p)) (t (σ q)))) y).det
  have hδd : DifferentiableOn ℂ δ (img U) :=
    ComplexAnalytic.Cap.differentiableOn_det fun p q ↦ differentiableOn_holFun _
  have hδ₀ : δ y₀.1 ≠ 0 := by
    have hG : (Matrix.of fun p q : F₀ ↦
        holFun (trace h₀ W hD (mulSec h₀ W (t (σ p)) (t (σ q)))) y₀.1) =
          (A.submatrix id σ)ᵀ * A.submatrix id σ := by
      ext p q
      rw [Matrix.of_apply, holFun_trace_mulSec h₀ W hD _ _ hy₀U hy₀, Matrix.mul_apply,
        ← Finset.sum_coe_sort]
      rfl
    change (Matrix.of fun p q : F₀ ↦
      holFun (trace h₀ W hD (mulSec h₀ W (t (σ p)) (t (σ q)))) y₀.1).det ≠ 0
    rw [hG, Matrix.det_mul, Matrix.det_transpose]
    exact mul_ne_zero (isUnit_iff_ne_zero.1 hσ) (isUnit_iff_ne_zero.1 hσ)
  have hint : interior ((img U : Set (Cn.{u} n)) ∩ δ ⁻¹' {0}) = ∅ := by
    refine eq_empty_iff_forall_notMem.2 fun y hy ↦ hδ₀ ?_
    have hyU := (interior_subset hy).1
    have h0 : δ =ᶠ[𝓝 y] 0 := Filter.mem_of_superset (isOpen_interior.mem_nhds hy)
      fun z hz ↦ (interior_subset hz).2
    have hA : AnalyticOnNhd ℂ δ (img U) := fun z hz ↦
      analyticAt_of_differentiableOn_of_finiteDimensional (img U).isOpen hδd hz
    have hEq := hA.eqOn_zero_of_preconnected_of_eventuallyEq_zero hU hyU h0
    exact hEq hy₀U
  -- off the zero set of `δ`, the section vanishes on the fibres
  have hvan : ∀ w (hw : w ∈ preim h₀ W V), δ (pt W w) ≠ 0 → evalFun (secVal h₀ W a) w = 0 := by
    intro w hw hδw
    set y := pt W w
    have hyV : y ∈ img V := (mem_preim_iff h₀ W).1 hw
    have hyN : y ∈ N₀ := pt_mem W w
    set Fy := fiberFinset W y
    have hcard : Fintype.card Fy = Fintype.card F₀ := by
      rw [Fintype.card_coe, Fintype.card_coe]
      exact card_fiberFinset_eq W hD (img U).isOpen hU (img_le U) (img_mono hV hyV) hyN hy₀U hy₀
    set e : Fy ≃ F₀ := Fintype.equivOfCardEq hcard
    set T : Matrix F₀ F₀ ℂ := Matrix.of fun p q ↦ evalFun (secVal h₀ W (t (σ q))) (e.symm p).1
    have hG : (Matrix.of fun p q : F₀ ↦
        holFun (trace h₀ W hD (mulSec h₀ W (t (σ p)) (t (σ q)))) y) = Tᵀ * T := by
      ext p q
      rw [Matrix.of_apply, holFun_trace_mulSec h₀ W hD _ _ (img_mono hV hyV) hyN,
        Matrix.mul_apply, ← Finset.sum_coe_sort]
      exact (Fintype.sum_equiv e _ _ fun w ↦ by simp [T]).trans rfl
    have hT : T.det ≠ 0 := by
      intro h0
      apply hδw
      change (Matrix.of fun p q : F₀ ↦
        holFun (trace h₀ W hD (mulSec h₀ W (t (σ p)) (t (σ q)))) y).det = 0
      rw [hG, Matrix.det_mul, h0, mul_zero]
    have hα : (fun p : F₀ ↦ evalFun (secVal h₀ W a) (e.symm p).1) ᵥ* T = 0 := by
      funext q
      have := ha (σ q)
      have h2 := holFun_trace_mulSec h₀ W hD a (sectRes (boundedModule h₀ W) hV (t (σ q))) hyV hyN
      rw [this, holFun_zero hyV] at h2
      rw [Matrix.vecMul, dotProduct, Pi.zero_apply, h2, ← Finset.sum_coe_sort Fy]
      refine Fintype.sum_equiv e.symm _ _ fun p ↦ ?_
      have hw' : (e.symm p).1 ∈ preim h₀ W V :=
        (mem_preim_iff h₀ W).2 ((mem_fiberFinset W).1 (e.symm p).2 ▸ hyV)
      simp only [T, Matrix.of_apply]
      rw [secVal_map, evalFun_map W _ _ hw']
    have := congrFun (Matrix.eq_zero_of_vecMul_eq_zero hT hα) (e ⟨w, (mem_fiberFinset W).2 rfl⟩)
    simpa using this
  -- density of `{δ ≠ 0}`
  refine secVal_injective h₀ W (eq_of_forall_eval_eq (isLocallyOpenInAffine_left W)
    fun w hw ↦ ?_)
  rw [secVal_zero, map_zero]
  obtain ⟨O, hwO, -, hsheet⟩ := exists_sheet W w
  obtain ⟨F, hFd, hF⟩ := hsheet (O' := O ⊓ preim h₀ W V) inf_le_left
    (W.left.presheaf.map (homOfLE inf_le_right).op (secVal h₀ W a))
  set G : Set (Cn.{u} n) := pt W '' ((O ⊓ preim h₀ W V : W.left.Opens) : Set W.left)
  have hFc : ContinuousOn F G := by
    rintro _ ⟨w', hw', rfl⟩
    exact (hFd w' hw').continuousAt.continuousWithinAt
  have h0 := EqOn.of_eqOn_diff_of_interior_eq_empty (isOpen_image_pt W _) hint hFc
    (continuousOn_const (c := 0)) (fun x hx ↦ ?_) ⟨w, ⟨hwO, hw⟩, rfl⟩
  · have := hF w ⟨hwO, hw⟩
    rw [eval_presheaf_map] at this
    exact this.trans h0
  · obtain ⟨⟨w', hw', rfl⟩, hxZ⟩ := hx
    have hδw' : δ (pt W w') ≠ 0 := fun h ↦ hxZ
      ⟨(image_pt_subset h₀ W O |>.trans (img_mono hV)) ⟨w', hw', rfl⟩, h⟩
    rw [← hF w' hw', eval_presheaf_map, ← evalFun_of_mem _ hw'.2]
    exact hvan w' hw'.2 hδw'

/-- The sections `σᵢ l`, `i ≤ j`, of a sequence of finite families, as one finite family. -/
def cumFamily {M : Type*} {k : ℕ → ℕ} (σ : ∀ j, Fin (k j) → M) (j : ℕ) :
    Fin (Fintype.card (Σ i : Fin (j + 1), Fin (k i))) → M :=
  fun c ↦ σ ((Fintype.equivFin _).symm c).1 ((Fintype.equivFin _).symm c).2

lemma exists_cumFamily_eq {M : Type*} {k : ℕ → ℕ} (σ : ∀ j, Fin (k j) → M) {j j' : ℕ}
    (h : j ≤ j') (c : Fin (Fintype.card (Σ i : Fin (j + 1), Fin (k i)))) :
    ∃ c', cumFamily σ j' c' = cumFamily σ j c := by
  set p := (Fintype.equivFin (Σ i : Fin (j + 1), Fin (k i))).symm c
  refine ⟨Fintype.equivFin (Σ i : Fin (j' + 1), Fin (k i))
    ⟨Fin.castLE (by omega) p.1, p.2⟩, ?_⟩
  unfold cumFamily
  rw [Equiv.symm_apply_apply]
  rfl

lemma exists_cumFamily_eq_last {M : Type*} {k : ℕ → ℕ} (σ : ∀ j, Fin (k j) → M) (j : ℕ)
    (l : Fin (k j)) : ∃ c, cumFamily σ j c = σ j l := by
  refine ⟨Fintype.equivFin (Σ i : Fin (j + 1), Fin (k i)) ⟨Fin.last j, l⟩, ?_⟩
  unfold cumFamily
  rw [Equiv.symm_apply_apply]
  rfl

include hD in
/-- **Uniform generators from an increasing chain.** Let `U ⊆ N` be open with `U` connected and
let `σⱼ` be finite families of sections of `𝒜` over `U`, one of which generates `𝒜` near a point
of `N°`. If near every point `y ∈ U` off `Z` the families `σⱼ` generate `𝒜` for all large `j`,
then near every point of `U` one finite family generates `𝒜` at all points off `Z`. -/
theorem exists_generatesNear_of_chain {U : (space N).Opens}
    (hU : IsPreconnected (img U : Set (Cn.{u} n))) {k : ℕ → ℕ}
    (σ : ∀ j, Fin (k j) → (boundedModule h₀ W).val.obj (op U)) {j₀ : ℕ} {y₀ : space N}
    (hy₀ : y₀.1 ∈ N₀) (hsep : GeneratesNear h₀ W (σ j₀) y₀) {Z : Set (Cn.{u} n)}
    (hgen : ∀ y ∈ U, y.1 ∉ Z → ∃ j₁, ∀ j, j₁ ≤ j → GeneratesNear h₀ W (σ j) y)
    {x : space N} (hx : x ∈ U) :
    ∃ (U' : (space N).Opens) (_ : U' ≤ U), x ∈ U' ∧ ∃ (r : ℕ)
      (s : Fin r → (boundedModule h₀ W).val.obj (op U')),
        ∀ y ∈ U', y.1 ∉ Z → GeneratesNear h₀ W s y := by
  classical
  set t := σ j₀
  set r : ℕ → ℕ := fun j ↦ Fintype.card (Σ i : Fin (j + 1), Fin (k i))
  -- the images of the cumulative families
  set col : ∀ j, Fin (r j) → Fin (k j₀) → OkaRing (img U) :=
    fun j c ↦ tauVec h₀ W hD t le_rfl (cumFamily σ j c)
  set A : ∀ j, Matrix (Fin (k j₀)) (Fin (r j)) (OkaRing (img U)) :=
    fun j ↦ Matrix.of fun a c ↦ col j c a
  set Nj : ℕ → Cn.{u} n → Submodule (LocalOkaRing (ULift.{u} (Fin n)))
      (Fin (k j₀) → LocalOkaRing (ULift.{u} (Fin n))) :=
    fun j y ↦ if hy : y ∈ img U then germSpan (col j) hy else ⊥
  have hNA : ∀ j y (hy : y ∈ img U), Nj j y = Submodule.span _
      (range fun c ↦ germVec hy fun a ↦ A j a c) := fun j y hy ↦ by
    simp only [Nj, dif_pos hy, germSpan, A, Matrix.of_apply]
  have hmono : Monotone Nj := by
    intro j j' hjj' y
    by_cases hy : y ∈ img U
    · simp only [Nj, dif_pos hy, germSpan, Submodule.span_le]
      rintro _ ⟨c, rfl⟩
      obtain ⟨c', hc'⟩ := exists_cumFamily_eq σ hjj' c
      refine Submodule.subset_span ⟨c', ?_⟩
      simp only [col, hc']
    · simp only [Nj, dif_neg hy, le_refl]
  have hxU : x.1 ∈ img U := mem_img_iff.2 ⟨x.2, hx⟩
  obtain ⟨V, hxV, hVU, j₁, hj₁⟩ := OkaRing.exists_forall_ge_eq_of_monotone hxU Nj hmono A hNA
  -- the open of `N` over `V`
  set U' : (space N).Opens := ⟨Subtype.val ⁻¹' (V : Set (Cn.{u} n)),
    V.isOpen.preimage continuous_subtype_val⟩
  have hU'U : U' ≤ U := fun y hy ↦ (mem_img_iff.1 (hVU hy)).2
  refine ⟨U', hU'U, hxV, r j₁, fun c ↦ sectRes (boundedModule h₀ W) hU'U (cumFamily σ j₁ c),
    fun y hy hyZ ↦ ?_⟩
  obtain ⟨j₂, hj₂⟩ := hgen y (hU'U hy) hyZ
  obtain ⟨Vy, hVyU, hyVy, hspan⟩ := hj₂ (max j₁ j₂) (le_max_right _ _)
  refine ⟨Vy ⊓ U', inf_le_right, ⟨hyVy, hy⟩, fun V'' hV'' b z hz ↦ ?_⟩
  obtain ⟨W₁, hW₁, hzW₁', f, hf⟩ := hspan V'' (hV''.trans inf_le_left) b z hz
  have hW₁U : W₁ ≤ U := hW₁.trans (hV''.trans (inf_le_left.trans hVyU))
  have hzW₁ : z.1 ∈ img W₁ := mem_img_iff.2 ⟨z.2, hzW₁'⟩
  have hzV : z.1 ∈ V := (hV''.trans inf_le_right) hz
  -- the germ of `τ(b)` lies in the span of the germs of the images of `σ_{j₁}`
  have hmem : germVec hzW₁ (tauVec h₀ W hD t hW₁U (sectRes (boundedModule h₀ W) hW₁ b)) ∈
      Nj j₁ z.1 := by
    rw [← hj₁ (max j₁ j₂) (le_max_left _ _) z.1 hzV, hf, tauVec_sum_smul, germVec_sum]
    simp only [Nj, dif_pos (img_mono hW₁U hzW₁)]
    refine Submodule.sum_mem _ fun l _ ↦ ?_
    rw [germVec_smul]
    refine Submodule.smul_mem _ _ ?_
    obtain ⟨c, hc⟩ := exists_cumFamily_eq_last σ (max j₁ j₂) l
    rw [tauVec_res h₀ W hD t le_rfl, germVec_resVec, ← hc]
    exact germVec_mem_germSpan _ _ c
  simp only [Nj, dif_pos (img_mono hW₁U hzW₁)] at hmem
  rw [← germSpan_resVec (img_mono hW₁U) (col j₁) hzW₁] at hmem
  obtain ⟨O₂, hO₂, hzO₂, e, he⟩ := exists_eq_sum_of_mem_germSpan _ _ hzW₁ hmem
  set W₂ : (space N).Opens := W₁ ⊓ ⟨Subtype.val ⁻¹' (O₂ : Set (Cn.{u} n)),
    O₂.isOpen.preimage continuous_subtype_val⟩
  have hW₂O₂ : img W₂ ≤ O₂ := fun p hp ↦ by
    obtain ⟨_, h⟩ := mem_img_iff.1 hp
    exact h.2
  refine ⟨W₂, inf_le_left.trans hW₁, ⟨hzW₁', hzO₂⟩, fun c ↦ ofOka (restrict hW₂O₂ (e c)), ?_⟩
  -- injectivity of `τ`
  have hW₂W₁ : W₂ ≤ W₁ := inf_le_left
  have hW₂U : W₂ ≤ U := hW₂W₁.trans hW₁U
  refine sub_eq_zero.1 (eq_zero_of_trace_eq_zero_of_generatesNear h₀ W hD hU t hy₀ hsep hW₂U _
    fun a ↦ ?_)
  have key : tauVec h₀ W hD t hW₂U (sectRes (boundedModule h₀ W) (hW₂W₁.trans hW₁) b) =
      tauVec h₀ W hD t hW₂U (∑ c, ofOka (restrict hW₂O₂ (e c)) • sectRes (boundedModule h₀ W)
        ((hW₂W₁.trans hW₁).trans (hV''.trans inf_le_right))
          (sectRes (boundedModule h₀ W) hU'U (cumFamily σ j₁ c))) := by
    rw [← sectRes_sectRes (boundedModule h₀ W) hW₂W₁ hW₁,
      tauVec_res h₀ W hD t hW₁U hW₂W₁, tauVec_sum_smul]
    funext i
    have := congrArg (fun w ↦ restrict hW₂O₂ (w i)) he
    simp only [resVec, Finset.sum_apply, Pi.smul_apply, smul_eq_mul, map_sum, map_mul,
      restrict_restrict] at this
    simp only [sectRes_sectRes, tauVec_res h₀ W hD t le_rfl, resVec, Finset.sum_apply,
      Pi.smul_apply, smul_eq_mul, this]
    rfl
  have := congrFun key a
  simp only [tauVec] at this
  rw [sub_eq_add_neg, mulSec_add, trace_add, this, ← trace_add, ← mulSec_add, add_neg_cancel,
    mulSec_zero_left, trace_zero]

end

end ComplexAnalytic.BoundedSections
