/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.Analytification.RET.ES.CapExtension.GapGerm
import Oka.Analytification.RET.ES.Codim2.CoordFreeness

/-!
# Coherence of bounded sections from generators off a set of codimension two

Keep the notation of `Oka/Analytification/RET/ES/ReflexiveHull.lean`: `p : W ⟶ N°` is a finite
étale cover with `W` Hausdorff, `N ∖ N°` is thin and `𝒜` is the sheaf of bounded sections. Let
`U ⊆ N` be open, `P` a family of regular pairs on `U` with zero set `Z`, and `s₁, …, s_r ∈ 𝒜(U)`
sections generating `𝒜` near every point of `U ∖ Z`. Then `𝒜` satisfies the local conditions for
coherence at every point of `U` (`ComplexAnalytic.BoundedSections.isCoherentAt_of_generates`).
Unlike `ComplexAnalytic.BoundedSections.isCoherentAt_of_criterion`, no freeness off `Z` is needed.

## Proof

The functionals `τⱼ(a) = tr(a sⱼ)` embed `𝒜|_U` into `𝒪_U^r`
(`ComplexAnalytic.BoundedSections.eq_zero_of_trace_mulSec_eq_zero`). Off `Z` the image is the
subsheaf `ℐ` generated by the columns `τ(sᵢ)` of the trace matrix. By Hartogs extension for `𝒜`
and `𝒪` across `Z`, the image is the gap sheaf of `ℐ` with respect to `Z`
(`ComplexAnalytic.BoundedSections.exists_tauVec_eq`), which is locally finitely generated
(`OkaRing.exists_gap_generators`); near every point, `Z` is the common zero set of finitely many
holomorphic functions (`RegularPairFamily.exists_local_equations`). Relations between sections of
`𝒜` are the relations between their images, which are locally finitely generated by Oka's
theorem.

## Main results

- `RegularPairFamily.exists_local_equations`: local equations for the zero set of a family of
  regular pairs.
- `ComplexAnalytic.BoundedSections.isCoherentAt_of_generates`: the criterion.
-/

open CategoryTheory Opposite AlgebraicGeometry Topology TopologicalSpace Filter Set

universe u

namespace RegularPairFamily

variable {ι : Type u} [Fintype ι] {U : Set (ι → ℂ)} (P : RegularPairFamily U)

omit [Fintype ι] in
/-- A function represented near the origin by a germ is holomorphic near the base point. -/
lemma exists_differentiableOn_of_represents [Finite ι] {g : (ι → ℂ) → ℂ} {z : ι → ℂ}
    {G : LocalOkaRing ι} (hG : (G : MvPowerSeries ι ℂ).Represents (fun w ↦ g (w + z))) :
    ∃ O : Set (ι → ℂ), IsOpen O ∧ z ∈ O ∧ DifferentiableOn ℂ g O := by
  have := Fintype.ofFinite ι
  have hA : AnalyticAt ℂ (fun w ↦ g (w + z)) 0 :=
    (G.2.analyticAt).congr (G.2.represents_eval.eventuallyEq hG)
  have hA' : AnalyticAt ℂ g z := by
    have hs : AnalyticAt ℂ (fun w : ι → ℂ ↦ w - z) z :=
      (analyticAt_id).sub analyticAt_const
    have := hA.comp_of_eq hs (sub_self z)
    exact this.congr (Eventually.of_forall fun w ↦ by simp)
  obtain ⟨O, hOs, hO, hzO⟩ := mem_nhds_iff.1 hA'.eventually_analyticAt
  exact ⟨O, hO, hzO, fun w hw ↦ (hOs hw).differentiableAt.differentiableWithinAt⟩

omit [Fintype ι] in
/-- A continuous function not vanishing at `z` does not vanish on an open neighbourhood. -/
lemma exists_isOpen_ne_zero {g : (ι → ℂ) → ℂ} {z : ι → ℂ} (hc : ContinuousAt g z)
    (hg : g z ≠ 0) : ∃ O : Set (ι → ℂ), IsOpen O ∧ z ∈ O ∧ ∀ y ∈ O, g y ≠ 0 := by
  obtain ⟨O, hOs, hO, hzO⟩ := mem_nhds_iff.1 (hc.eventually_ne hg)
  exact ⟨O, hO, hzO, fun y hy ↦ hOs hy⟩

open Classical in
/-- **Local equations for the zero set of a family of regular pairs**: near every point of `U`,
the zero set of `P` is the common zero set of finitely many holomorphic functions. -/
theorem exists_local_equations (hU : IsOpen U) {z : ι → ℂ} (hz : z ∈ U) :
    ∃ O : Opens (ι → ℂ), (O : Set (ι → ℂ)) ⊆ U ∧ z ∈ O ∧ ∃ (S : ℕ) (f : Fin S → OkaRing O),
      ∀ y (hy : y ∈ O), y ∈ P.zeroSet ↔ ∀ s, OkaRing.evalHom hy (f s) = 0 := by
  -- the pairs vanishing at `z` are holomorphic near `z`, the others do not vanish near `z`
  have hloc : ∀ i : Fin P.k, ∃ O : Set (ι → ℂ), IsOpen O ∧ z ∈ O ∧
      ((z ∈ P.zeroSetOf i → DifferentiableOn ℂ (P.g i) O ∧ DifferentiableOn ℂ (P.h i) O) ∧
        (z ∉ P.zeroSetOf i → ∀ y ∈ O, y ∉ P.zeroSetOf i)) := by
    intro i
    by_cases hi : z ∈ P.zeroSetOf i
    · obtain ⟨G, H, hG, hH, -⟩ := P.isWeaklyRegular i z hz hi.1 hi.2
      obtain ⟨O₁, hO₁, hz₁, hd₁⟩ := exists_differentiableOn_of_represents hG
      obtain ⟨O₂, hO₂, hz₂, hd₂⟩ := exists_differentiableOn_of_represents hH
      exact ⟨O₁ ∩ O₂, hO₁.inter hO₂, ⟨hz₁, hz₂⟩, fun _ ↦ ⟨hd₁.mono inter_subset_left,
        hd₂.mono inter_subset_right⟩, fun h ↦ absurd hi h⟩
    · have hne : P.g i z ≠ 0 ∨ P.h i z ≠ 0 := by
        by_contra h
        push Not at h
        exact hi ⟨h.1, h.2⟩
      rcases hne with hg | hh
      · obtain ⟨O, hO, hzO, hO'⟩ :=
          exists_isOpen_ne_zero ((P.continuousOn_g i).continuousAt (hU.mem_nhds hz)) hg
        exact ⟨O, hO, hzO, fun h ↦ absurd h hi, fun _ y hy hy' ↦ hO' y hy hy'.1⟩
      · obtain ⟨O, hO, hzO, hO'⟩ :=
          exists_isOpen_ne_zero ((P.continuousOn_h i).continuousAt (hU.mem_nhds hz)) hh
        exact ⟨O, hO, hzO, fun h ↦ absurd h hi, fun _ y hy hy' ↦ hO' y hy hy'.2⟩
  choose O hO hzO hOi using hloc
  set O₀ : Opens (ι → ℂ) := ⟨U ∩ ⋂ i, O i, hU.inter (isOpen_iInter_of_finite hO)⟩
  have hO₀U : (O₀ : Set (ι → ℂ)) ⊆ U := fun _ h ↦ h.1
  have hO₀i : ∀ i, (O₀ : Set (ι → ℂ)) ⊆ O i := fun i _ h ↦ mem_iInter.1 h.2 i
  -- the vanishing pairs at `z`
  set I : Finset (Fin P.k) := Finset.univ.filter fun i ↦ z ∈ P.zeroSetOf i
  -- the products `∏ᵢ (gᵢ or hᵢ)`
  set F : (I → Bool) → (ι → ℂ) → ℂ := fun σ y ↦
    ∏ i : I, if σ i then P.g i y else P.h i y
  have hF : ∀ σ, DifferentiableOn ℂ (F σ) O₀ := fun σ ↦ by
    have : DifferentiableOn ℂ (∏ i : I, fun y ↦ if σ i then P.g i y else P.h i y) O₀ := by
      refine Finset.prod_induction _ (p := fun g : (ι → ℂ) → ℂ ↦ DifferentiableOn ℂ g O₀)
        (fun a b (ha : DifferentiableOn ℂ a O₀) (hb : DifferentiableOn ℂ b O₀) ↦ ha.mul hb)
        (differentiableOn_const (c := (1 : ℂ))) fun i _ ↦ ?_
      have hi : z ∈ P.zeroSetOf i := (Finset.mem_filter.1 i.2).2
      obtain ⟨hgd, hhd⟩ := (hOi i).1 hi
      split_ifs
      · exact hgd.mono (hO₀i i)
      · exact hhd.mono (hO₀i i)
    convert this using 1
    funext y
    simp [F, Finset.prod_apply]
  set e := Fintype.equivFin (I → Bool)
  refine ⟨O₀, hO₀U, ⟨hz, mem_iInter.2 hzO⟩, Fintype.card (I → Bool),
    fun s ↦ OkaRing.ofDifferentiableOn (F (e.symm s)) (hF _), fun y hy ↦ ?_⟩
  simp only [OkaRing.evalHom_apply, OkaRing.ofDifferentiableOn_toFun]
  constructor
  · rintro hyZ s
    obtain ⟨i, hi⟩ := mem_iUnion.1 hyZ
    have hiI : z ∈ P.zeroSetOf i := by
      by_contra h
      exact (hOi i).2 h y (hO₀i i hy) hi
    refine Finset.prod_eq_zero (i := ⟨i, Finset.mem_filter.2 ⟨Finset.mem_univ _, hiI⟩⟩)
      (Finset.mem_univ _) ?_
    split_ifs
    · exact hi.1
    · exact hi.2
  · intro h
    by_contra hyZ
    have hne : ∀ i : I, P.g i y ≠ 0 ∨ P.h i y ≠ 0 := fun i ↦ by
      by_contra h'
      push Not at h'
      exact hyZ (mem_iUnion.2 ⟨i, h'.1, h'.2⟩)
    set σ : I → Bool := fun i ↦ decide (P.g i y ≠ 0)
    have := h (e σ)
    rw [Equiv.symm_apply_apply] at this
    refine Finset.prod_ne_zero_iff.2 (fun i _ ↦ ?_) this
    by_cases hg : P.g i y ≠ 0
    · simp [σ, hg]
    · have hh := (hne i).resolve_left hg
      simp [σ, hg, hh]

end RegularPairFamily

namespace ComplexAnalytic.BoundedSections

open AnalyticSpace AlgebraicGeometry.LocallyRingedSpace OkaRing

noncomputable section

variable {n : ℕ} {N N₀ : (AnalyticSpace.complexAffineSpace.{u} n).Opens}

/-- Restriction of sections of `𝒪_N` is restriction of holomorphic functions. -/
lemma res_eq_restrict {V V' : (space N).Opens} (h : V' ≤ V) (r : (space N).presheaf.obj (op V)) :
    (space N).presheaf.map (homOfLE h).op r = OkaRing.restrict (img_mono h) r := by
  refine OkaRing.ext (funext fun x ↦ ?_)
  have hx : (x : Cn.{u} n) ∈ img V' := x.2
  have h1 := holFun_map h r hx
  rw [holFun, holFun, OkaRing.toGlobalFun_apply _ hx,
    OkaRing.toGlobalFun_apply _ (img_mono h hx)] at h1
  exact h1

/-- A section of `𝒪_N` over `V`, as a holomorphic function on the underlying open of `ℂⁿ`. -/
abbrev toOka {V : (space N).Opens} (c : (space N).presheaf.obj (op V)) : OkaRing (img V) :=
  c

/-- A holomorphic function on the underlying open of `V`, as a section of `𝒪_N` over `V`. -/
abbrev ofOka {V : (space N).Opens} (c : OkaRing (img V)) : (space N).presheaf.obj (op V) :=
  c

variable (h₀ : N₀ ≤ N) (W : FiniteEtaleOver (space N₀)) [T2Space W.left]
  (hD : HasThinComplement N N₀) {U : (space N).Opens} {r : ℕ}
  (s : Fin r → (boundedModule h₀ W).val.obj (op U))

/-- The functionals `a ↦ tr(a sⱼ)`, as a tuple of holomorphic functions. -/
def tauVec {V : (space N).Opens} (hV : V ≤ U) (a : (boundedModule h₀ W).val.obj (op V)) :
    Fin r → OkaRing (img V) :=
  fun j ↦ trace h₀ W hD (mulSec h₀ W a (sectRes (boundedModule h₀ W) hV (s j)))

variable {V : (space N).Opens} (hV : V ≤ U)

lemma tauVec_add (a b : (boundedModule h₀ W).val.obj (op V)) :
    tauVec h₀ W hD s hV (a + b) = tauVec h₀ W hD s hV a + tauVec h₀ W hD s hV b := by
  funext j
  exact (congrArg (trace h₀ W hD) (mulSec_add h₀ W _ _ _)).trans (trace_add h₀ W hD _ _)

lemma tauVec_smul (c : (space N).presheaf.obj (op V)) (a : (boundedModule h₀ W).val.obj (op V)) :
    tauVec h₀ W hD s hV (c • a) = toOka c • tauVec h₀ W hD s hV a := by
  funext j
  exact (congrArg (trace h₀ W hD) (mulSec_smul h₀ W _ _ _)).trans (trace_smul h₀ W hD _ _)

lemma tauVec_sum_smul {L : ℕ} (c : Fin L → (space N).presheaf.obj (op V))
    (a : Fin L → (boundedModule h₀ W).val.obj (op V)) :
    tauVec h₀ W hD s hV (∑ l, c l • a l) = ∑ l, toOka (c l) • tauVec h₀ W hD s hV (a l) := by
  classical
  have : ∀ t : Finset (Fin L), tauVec h₀ W hD s hV (∑ l ∈ t, c l • a l) =
      ∑ l ∈ t, toOka (c l) • tauVec h₀ W hD s hV (a l) := fun t ↦ by
    induction t using Finset.induction_on with
    | empty =>
      funext j
      exact (congrArg (trace h₀ W hD) (mulSec_zero_left h₀ W _)).trans (trace_zero h₀ W hD)
    | insert l t hl ih =>
      rw [Finset.sum_insert hl, Finset.sum_insert hl, tauVec_add, tauVec_smul, ih]
  exact this Finset.univ

lemma tauVec_res {V' : (space N).Opens} (h : V' ≤ V) (a : (boundedModule h₀ W).val.obj (op V)) :
    tauVec h₀ W hD s (h.trans hV) (sectRes (boundedModule h₀ W) h a) =
      resVec (img_mono h) (tauVec h₀ W hD s hV a) := by
  funext j
  simp only [tauVec, resVec]
  rw [← sectRes_sectRes (boundedModule h₀ W) h hV, ← mulSec_map, trace_map, res_eq_restrict]

/-- The columns `τ(sᵢ) = (tr(sᵢ sⱼ))ⱼ` of the trace matrix. -/
def tauCol (i : Fin r) : Fin r → OkaRing (img U) :=
  tauVec h₀ W hD s le_rfl (s i)

lemma tauVec_sectRes (i : Fin r) :
    tauVec h₀ W hD s hV (sectRes (boundedModule h₀ W) hV (s i)) =
      resVec (img_mono hV) (tauCol h₀ W hD s i) := by
  have := tauVec_res h₀ W hD s (le_refl U) hV (s i)
  exact this

/-- **The sections `sᵢ` generate `𝒜` near `y`**: on a neighbourhood `V'` of `y`, every section of
`𝒜` over an open inside `V'` is, near every point, a combination of the `sᵢ`. -/
def GeneratesNear (y : space N) : Prop :=
  ∃ (V' : (space N).Opens) (hV'U : V' ≤ U), y ∈ V' ∧
    ∀ (V'' : (space N).Opens) (h : V'' ≤ V') (b : (boundedModule h₀ W).val.obj (op V''))
      (z : space N), z ∈ V'' → ∃ (W'' : (space N).Opens) (hW'' : W'' ≤ V''), z ∈ W'' ∧
        ∃ f : Fin r → (space N).presheaf.obj (op W''), sectRes (boundedModule h₀ W) hW'' b =
          ∑ i, f i • sectRes (boundedModule h₀ W) (hW''.trans (h.trans hV'U)) (s i)

variable (P : RegularPairFamily (img U : Set (Cn.{u} n)))
  (hgen : ∀ y ∈ U, y.1 ∉ P.zeroSet → GeneratesNear h₀ W s y)

include hD hgen in
/-- **The trace pairing against local generators is non-degenerate**: a section `a` of `𝒜` over
`V ⊆ U` with `tr(a sⱼ) = 0` for all `j` vanishes. At a point `w` over `U ∖ Z`, pairing with an
indicator section of the sheet through `w` gives `a(w) = 0`, and these points are dense. -/
theorem eq_zero_of_trace_mulSec_eq_zero' (a : (boundedModule h₀ W).val.obj (op V))
    (ha : ∀ j, trace h₀ W hD (mulSec h₀ W a (sectRes (boundedModule h₀ W) hV (s j))) = 0) :
    a = 0 := by
  classical
  -- the values vanish over `U ∖ Z`
  have hpt : ∀ w (hw : w ∈ preim h₀ W V), pt W w ∉ P.zeroSet →
      evalFun (secVal h₀ W a) w = 0 := by
    intro w hw hwZ
    set x := pt W w
    have hxV : x ∈ img V := (mem_preim_iff h₀ W).1 hw
    obtain ⟨hxN, hyV⟩ := mem_img_iff.1 hxV
    obtain ⟨V', hV'U, hyV', hspan⟩ := hgen ⟨x, hxN⟩ (hV hyV) hwZ
    obtain ⟨B, hBo, hxB, hBN, hind⟩ := exists_indicator W w
    let VB : (space N).Opens := ⟨Subtype.val ⁻¹' B, hBo.preimage continuous_subtype_val⟩
    let V₁ : (space N).Opens := V ⊓ V' ⊓ VB
    have hV₁V' : V₁ ≤ V' := inf_le_left.trans inf_le_right
    obtain ⟨b, hb⟩ := hind (preim h₀ W V₁) fun w' hw' ↦ by
      obtain ⟨_, h⟩ := mem_img_iff.1 ((mem_preim_iff h₀ W).1 hw')
      exact h.2
    have hbmem : b ∈ boundedSubring h₀ W V₁ := by
      rw [boundedSubring_eq_top h₀ W fun z (hz : z ∈ V₁) ↦ hBN _ hz.2]
      trivial
    obtain ⟨V'', hV''V₁, hxV'', f, hf⟩ := hspan V₁ hV₁V' (mkSec h₀ W b hbmem) ⟨x, hxN⟩
      ⟨⟨hyV, hyV'⟩, hxB⟩
    have hV''V : V'' ≤ V := hV''V₁.trans (inf_le_left.trans inf_le_left)
    have hxV''i : x ∈ img V'' := mem_img_iff.2 ⟨hxN, hxV''⟩
    set b'' := sectRes (boundedModule h₀ W) hV''V₁ (mkSec h₀ W b hbmem)
    have key : trace h₀ W hD (mulSec h₀ W (sectRes (boundedModule h₀ W) hV''V a) b'') = 0 := by
      rw [hf, mulSec_sum_smul, trace_sum_smul]
      refine Finset.sum_eq_zero fun i _ ↦ ?_
      rw [← sectRes_sectRes (boundedModule h₀ W) hV''V hV, ← mulSec_map, trace_map, ha i,
        map_zero, mul_zero]
    have hw'' : w ∈ preim h₀ W V'' := (mem_preim_iff h₀ W).2 hxV''i
    have hvb : ∀ w' ∈ preim h₀ W V'', pt W w' = x →
        evalFun (secVal h₀ W b'') w' = if w' = w then 1 else 0 := fun w' hw' hw'x ↦ by
      rw [secVal_map, evalFun_map W _ _ hw', secVal_mkSec]
      exact hb w' (preim_mono h₀ W hV''V₁ hw') hw'x
    have hva : ∀ w' ∈ preim h₀ W V'',
        evalFun (secVal h₀ W (sectRes (boundedModule h₀ W) hV''V a)) w' =
          evalFun (secVal h₀ W a) w' := fun w' hw' ↦ by
      rw [secVal_map, evalFun_map W _ _ hw']
    have := holFun_trace h₀ W hD (mulSec h₀ W (sectRes (boundedModule h₀ W) hV''V a) b'')
      hxV''i (pt_mem W w)
    rw [key, holFun_zero hxV''i, traceFun, Finset.sum_eq_single w] at this
    · rw [secVal_mulSec, evalFun_mul W _ _ hw'', hva w hw'', hvb w hw'' rfl, if_pos rfl,
        mul_one] at this
      exact this.symm
    · intro w' hw' hw'w
      have hw'x : pt W w' = x := (mem_fiberFinset W).1 hw'
      have hw'V : w' ∈ preim h₀ W V'' := (mem_preim_iff h₀ W).2 (hw'x ▸ hxV''i)
      rw [secVal_mulSec, evalFun_mul W _ _ hw'V, hvb w' hw'V hw'x, if_neg hw'w, mul_zero]
    · exact fun h ↦ (h ((mem_fiberFinset W).2 rfl)).elim
  -- density of the points over `U ∖ Z`
  refine secVal_injective h₀ W (eq_of_forall_eval_eq (isLocallyOpenInAffine_left W)
    fun w hw ↦ ?_)
  rw [secVal_zero, map_zero]
  obtain ⟨O, hwO, -, hsheet⟩ := exists_sheet W w
  obtain ⟨F, hFd, hF⟩ := hsheet (O' := O ⊓ preim h₀ W V) inf_le_left
    (W.left.presheaf.map (homOfLE inf_le_right).op (secVal h₀ W a))
  set G : Set (Cn.{u} n) := pt W '' ((O ⊓ preim h₀ W V : W.left.Opens) : Set W.left)
  have hGU : G ⊆ img U := (image_pt_subset h₀ W O).trans (img_mono hV)
  have hFc : ContinuousOn F G := by
    rintro _ ⟨w', hw', rfl⟩
    exact (hFd w' hw').continuousAt.continuousWithinAt
  have h0 := P.eqOn_of_eqOn_diff (isOpen_image_pt W _) hGU hFc (continuousOn_const (c := 0))
    (fun x hx ↦ ?_) ⟨w, ⟨hwO, hw⟩, rfl⟩
  · have := hF w ⟨hwO, hw⟩
    rw [eval_presheaf_map] at this
    exact this.trans h0
  · obtain ⟨⟨w', hw', rfl⟩, hxZ⟩ := hx
    rw [← hF w' hw', eval_presheaf_map, ← evalFun_of_mem _ hw'.2]
    exact hpt w' hw'.2 hxZ

include hD hgen in
/-- **The functionals separate sections.** -/
lemma eq_of_tauVec_eq {a b : (boundedModule h₀ W).val.obj (op V)}
    (h : tauVec h₀ W hD s hV a = tauVec h₀ W hD s hV b) : a = b := by
  refine sub_eq_zero.1 (eq_zero_of_trace_mulSec_eq_zero' h₀ W hD s hV P hgen _ fun j ↦ ?_)
  have := congrFun h j
  simp only [tauVec] at this
  rw [sub_eq_add_neg, mulSec_add, trace_add, this, ← trace_add, ← mulSec_add, add_neg_cancel,
    mulSec_zero_left, trace_zero]

include hD hgen in
/-- **Images lie in the gap sheaf**: off the zero set, the images are combinations of the
columns of the trace matrix. -/
lemma isGapGood_tauVec (a : (boundedModule h₀ W).val.obj (op V)) :
    IsGapGood (tauCol h₀ W hD s) P.zeroSet (img_mono hV) (tauVec h₀ W hD s hV a) := by
  intro y hy hyZ
  obtain ⟨hyN, hyV⟩ := mem_img_iff.1 hy
  obtain ⟨V', hV'U, hyV', hspan⟩ := hgen ⟨y, hyN⟩ (hV hyV) hyZ
  obtain ⟨V₂, hV₂, hyV₂, f, hf⟩ := hspan (V ⊓ V') inf_le_right
    (sectRes (boundedModule h₀ W) inf_le_left a) ⟨y, hyN⟩ ⟨hyV, hyV'⟩
  have hy'' : y ∈ img V₂ := mem_img_iff.2 ⟨hyN, hyV₂⟩
  have key := congrArg (tauVec h₀ W hD s (hV₂.trans (inf_le_left.trans hV))) hf
  rw [sectRes_sectRes, tauVec_res h₀ W hD s hV (hV₂.trans inf_le_left) a,
    tauVec_sum_smul] at key
  have hgerm := congrArg (germVec hy'') key
  rw [germVec_resVec] at hgerm
  rw [hgerm, ← germSpan_resVec (img_mono (hV₂.trans (inf_le_right.trans hV'U)))
    (tauCol h₀ W hD s) hy'']
  simp only [tauVec_sectRes] at *
  exact germVec_sum_smul_mem_germSpan _ _ hy''

lemma isGapGood_resVec_iff {O : Opens (Cn.{u} n)} (hO : O ≤ img U) {V' : Opens (Cn.{u} n)}
    (hV' : V' ≤ O) (v : Fin r → OkaRing V') :
    IsGapGood (fun i ↦ resVec hO (tauCol h₀ W hD s i)) P.zeroSet hV' v ↔
      IsGapGood (tauCol h₀ W hD s) P.zeroSet (hV'.trans hO) v := by
  refine forall₂_congr fun y hy ↦ ?_
  rw [germSpan_resVec]

include hD hgen in
/-- **Tuples in the gap sheaf are images**: a tuple `v` over `V ⊆ U` whose germs off the zero set
are combinations of the columns of the trace matrix is `τ(a)` for a section `a` of `𝒜` over `V`.
Local preimages exist off `Z`, glue by injectivity of `τ`, and extend across `Z`. -/
theorem exists_tauVec_eq (v : Fin r → OkaRing (img V))
    (hv : IsGapGood (tauCol h₀ W hD s) P.zeroSet (img_mono hV) v) :
    ∃ a : (boundedModule h₀ W).val.obj (op V), tauVec h₀ W hD s hV a = v := by
  classical
  set D : (space N).Opens := V ⊓ diffZeroSet N P
  have hDV : D ≤ V := inf_le_left
  -- local preimages off `Z`
  have hloc : ∀ p : D, ∃ (O : (space N).Opens) (hOD : O ≤ D), p.1 ∈ O ∧
      ∃ a : (boundedModule h₀ W).val.obj (op O),
        tauVec h₀ W hD s (hOD.trans (hDV.trans hV)) a = resVec (img_mono (hOD.trans hDV)) v := by
    intro p
    have hpV : p.1.1 ∈ img V := mem_img_iff.2 ⟨p.1.2, hDV p.2⟩
    have hpZ : p.1.1 ∉ P.zeroSet := p.2.2.2
    have hmem := hv p.1.1 hpV hpZ
    rw [← germSpan_resVec (img_mono hV) (tauCol h₀ W hD s) hpV] at hmem
    obtain ⟨O', hO'V, hpO', c, hc⟩ := exists_eq_sum_of_mem_germSpan _ v hpV hmem
    let O : (space N).Opens := D ⊓ ⟨Subtype.val ⁻¹' (O' : Set (Cn.{u} n)),
      O'.isOpen.preimage continuous_subtype_val⟩
    have hOO' : img O ≤ O' := fun x hx ↦ by
      obtain ⟨_, h⟩ := mem_img_iff.1 hx
      exact h.2
    refine ⟨O, inf_le_left, ⟨p.2, hpO'⟩, ∑ j, ofOka (restrict hOO' (c j)) •
      sectRes (boundedModule h₀ W) (show O ≤ U from inf_le_left.trans (hDV.trans hV)) (s j), ?_⟩
    rw [tauVec_sum_smul]
    funext i
    have := congrArg (fun w ↦ restrict hOO' (w i)) hc
    simp only [resVec, Finset.sum_apply, Pi.smul_apply, smul_eq_mul, map_sum, map_mul,
      restrict_restrict] at this
    simp only [tauVec_sectRes, resVec, Finset.sum_apply, Pi.smul_apply, smul_eq_mul, this]
  choose O hOD hpO a ha using hloc
  -- the local preimages agree on overlaps
  have hcompat : ∀ p q : D, sectRes (boundedModule h₀ W) (inf_le_left : O p ⊓ O q ≤ O p) (a p) =
      sectRes (boundedModule h₀ W) (inf_le_right : O p ⊓ O q ≤ O q) (a q) := by
    intro p q
    have hpq : O p ⊓ O q ≤ U := inf_le_left.trans ((hOD p).trans (hDV.trans hV))
    refine eq_of_tauVec_eq h₀ W hD s hpq P hgen ?_
    rw [tauVec_res h₀ W hD s ((hOD p).trans (hDV.trans hV)) inf_le_left,
      tauVec_res h₀ W hD s ((hOD q).trans (hDV.trans hV)) inf_le_right, ha p, ha q]
    rfl
  have hcov : D ≤ iSup O := fun p hp ↦ Opens.mem_iSup.2 ⟨⟨p, hp⟩, hpO ⟨p, hp⟩⟩
  obtain ⟨a₀, ha₀, -⟩ := modRes_existsUnique_gluing (boundedModule h₀ W) O hcov hOD a
    fun p q ↦ hcompat p q
  obtain ⟨b, hb⟩ := (bijective_boundedModule_map P h₀ W hV hDV (img_diff_subset P hV) hD).2 a₀
  refine ⟨b, funext fun j ↦ (bijective_map_of_regularPairFamily P hV hDV
    (img_diff_subset P hV)).1 (eq_of_holFun_eq fun x hx ↦ ?_)⟩
  obtain ⟨hxN, hxD⟩ := mem_img_iff.1 hx
  set p : D := ⟨⟨x, hxN⟩, hxD⟩
  have hxO : x ∈ img (O p) := mem_img_iff.2 ⟨hxN, hpO p⟩
  have h₁ := congrArg (fun w : Fin r → OkaRing (img (O p)) ↦ (w j).toGlobalFun _ x) (ha p)
  have h₂ := congrArg (fun c ↦ tauVec h₀ W hD s ((hOD p).trans (hDV.trans hV)) c) (ha₀ p)
  rw [← h₂, show modRes a₀ (O p) (hOD p) = sectRes (boundedModule h₀ W) (hOD p) a₀ from rfl,
    tauVec_res h₀ W hD s (hDV.trans hV) (hOD p), ← hb, tauVec_res h₀ W hD s hV hDV] at h₁
  simp only [resVec, OkaRing.toGlobalFun_apply _ hxO] at h₁
  rw [res_eq_restrict, res_eq_restrict, holFun, holFun, OkaRing.toGlobalFun_apply _ hx,
    OkaRing.toGlobalFun_apply _ hx]
  exact h₁

include hD hgen in
/-- **Coherence from generators off the zero set of regular pairs.** Let `P` be a family of
regular pairs on `U` with zero set `Z` and let `s₁, …, s_r ∈ 𝒜(U)` generate `𝒜` near every point
of `U ∖ Z`. Then `𝒜` satisfies the local conditions for coherence at every point of `U`. -/
theorem isCoherentAt_of_generates {x : space N} (hx : x ∈ U) : IsCoherentAt h₀ W x := by
  have hxU : x.1 ∈ img U := mem_img_iff.2 ⟨x.2, hx⟩
  obtain ⟨O, hOU, hxO, S, f, hZ⟩ := P.exists_local_equations (img U).isOpen hxU
  have hOU' : O ≤ img U := hOU
  obtain ⟨V, hVO, hxV, L, B, hBgood, hBgen⟩ :=
    exists_gap_generators (A := fun i ↦ resVec hOU' (tauCol h₀ W hD s i)) hZ hxO
  -- the open of `N` over `V`
  set V' : (space N).Opens := ⟨Subtype.val ⁻¹' (V : Set (Cn.{u} n)),
    V.isOpen.preimage continuous_subtype_val⟩
  have hV'U : V' ≤ U := fun y hy ↦ (mem_img_iff.1 (hOU' (hVO hy))).2
  have hImg : img V' ≤ V := fun y hy ↦ by
    obtain ⟨_, h⟩ := mem_img_iff.1 hy
    exact h
  have hxV' : x ∈ V' := hxV
  -- the generators, as sections of `𝒜`
  have hlift : ∀ l, ∃ b : (boundedModule h₀ W).val.obj (op V'),
      tauVec h₀ W hD s hV'U b = resVec hImg (B l) := fun l ↦
    exists_tauVec_eq h₀ W hD s hV'U P hgen _ (by
      have := ((isGapGood_resVec_iff h₀ W hD s P hOU' hVO (B l)).1 (hBgood l)).resVec hImg
      exact this)
  choose b hb using hlift
  refine ⟨⟨V', L, b, hxV', fun W' hW' t y hy ↦ ?_⟩,
    hasLocalModuleRelationsAt_of_le U hx fun V₁ hV₁ m g hxV₁ ↦ ?_⟩
  · -- local generation
    have hyW' : y.1 ∈ img W' := mem_img_iff.2 ⟨y.2, hy⟩
    have hgood := isGapGood_tauVec h₀ W hD s (hW'.trans hV'U) P hgen t
    have hmem := hBgen (img W') ((img_mono hW').trans hImg) (tauVec h₀ W hD s (hW'.trans hV'U) t)
      ((isGapGood_resVec_iff h₀ W hD s P hOU' _ _).2 hgood) y.1 hyW'
    rw [← germSpan_resVec ((img_mono hW').trans hImg) B hyW'] at hmem
    obtain ⟨O'', hO''W, hyO'', c, hc⟩ := exists_eq_sum_of_mem_germSpan _ _ hyW' hmem
    set W'' : (space N).Opens := W' ⊓ ⟨Subtype.val ⁻¹' (O'' : Set (Cn.{u} n)),
      O''.isOpen.preimage continuous_subtype_val⟩
    have hW''O : img W'' ≤ O'' := fun z hz ↦ by
      obtain ⟨_, h⟩ := mem_img_iff.1 hz
      exact h.2
    refine ⟨W'', inf_le_left, ⟨hy, hyO''⟩, fun l ↦ ofOka (restrict hW''O (c l)), ?_⟩
    refine eq_of_tauVec_eq h₀ W hD s (inf_le_left.trans (hW'.trans hV'U)) P hgen ?_
    rw [tauVec_res h₀ W hD s (hW'.trans hV'U) inf_le_left, tauVec_sum_smul]
    funext i
    have := congrArg (fun w ↦ restrict hW''O (w i)) hc
    simp only [resVec, Finset.sum_apply, Pi.smul_apply, smul_eq_mul, map_sum, map_mul,
      restrict_restrict] at this
    simp only [tauVec_res h₀ W hD s hV'U, hb, resVec, Finset.sum_apply, Pi.smul_apply,
      smul_eq_mul, restrict_restrict, this]
  · -- relations are the relations between the images
    obtain ⟨W₁, hW₁, p, g', hxW₁, hg', hgen'⟩ := ReflexiveHullData.exists_tuple_relations
      (space N).hasLocalTupleRelations_unit (fun i j ↦ tauVec h₀ W hD s hV₁ (g i) j) hxV₁
    refine ⟨W₁, hW₁, p, g', hxW₁, fun l ↦ ?_, fun W' hW' a ha ↦ hgen' W' hW' a fun j ↦ ?_⟩
    · refine eq_of_tauVec_eq h₀ W hD s (hW₁.trans hV₁) P hgen ?_
      rw [tauVec_sum_smul]
      funext j
      have := hg' l j
      simp only [tauVec_res h₀ W hD s hV₁ hW₁, resVec, Finset.sum_apply, Pi.smul_apply,
        smul_eq_mul]
      have h0 := (tauVec_sum_smul h₀ W hD s (hW₁.trans hV₁) (fun _ : Fin 0 ↦ 0) Fin.elim0)
      simp only [Finset.univ_eq_empty, Finset.sum_empty] at h0
      rw [h0]
      simp only [LocallyRingedSpace.res] at this
      exact this
    · have := congrArg (fun c ↦ tauVec h₀ W hD s (hW'.trans (hW₁.trans hV₁)) c j) ha
      simp only [tauVec_sum_smul, tauVec_res h₀ W hD s hV₁ (hW'.trans hW₁), resVec,
        Finset.sum_apply, Pi.smul_apply, smul_eq_mul] at this
      have h0 := (tauVec_sum_smul h₀ W hD s (hW'.trans (hW₁.trans hV₁)) (fun _ : Fin 0 ↦ 0)
        Fin.elim0)
      simp only [Finset.univ_eq_empty, Finset.sum_empty] at h0
      rw [h0] at this
      simp only [LocallyRingedSpace.res]
      exact this

end

end ComplexAnalytic.BoundedSections
