/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.AnalyticSpace.NoetherGerm
import Oka.Nullstellensatz.Germ
import Mathlib.RingTheory.Ideal.AssociatedPrime.Finiteness

/-!
# Gap sheaves of coherent subsheaves of `𝒪^q`

Let `U ⊆ ℂ^ι` be open, `a₁, …, a_p ∈ 𝒪(U)^q` and let `Z ⊆ U` be the common zero set of finitely
many holomorphic functions `f_s` on `U`. The **gap sheaf** of the subsheaf `ℐ` of `𝒪^q` generated
by the `aⱼ` consists of the tuples `v` whose germs lie in `ℐ` at all points off `Z`
(`OkaRing.IsGapGood`). It is coherent: near every point `x₀ ∈ U` it is generated by finitely many
tuples `b₁, …, b_L` (`OkaRing.exists_gap_generators`).

## Proof

The germs at `x₀` of the tuples in the gap sheaf form a submodule `Ŝ ⊆ 𝒪_{x₀}^q`
(`OkaRing.gapSubmodule`), generated by the germs of finitely many `b_l` since `𝒪_{x₀}` is
noetherian. The module `Q = 𝒪_{x₀}^q ⧸ Ŝ` has no nonzero element killed by all germs `f_s`: such
an element is represented by a tuple `v` with `f_s v ∈ Ŝ`, and off `Z` some `f_s` is a unit. By
prime avoidance, some `φ` in the ideal generated by the `f_s` is a nonzerodivisor on `Q`. It
vanishes on `Z`, and by Oka's theorem the relations `φ c = ∑ d_l b_l` near `x₀` are generated by
finitely many, whose first components are combinations of the `b_l` near `x₀`; hence `φ` stays a
nonzerodivisor modulo the `b_l` at all points `y` near `x₀`. If `v` lies in the gap sheaf near
`y`, the relations `c v = ∑ d_l b_l` near `y` have first components without common zeros off `Z`,
so by the Rückert Nullstellensatz `φᴺ v` is a combination of the `b_l` at `y`, and so is `v`.

## Main definitions

- `OkaRing.germSpan`: the span of the germs of finitely many tuples.
- `OkaRing.IsGapGood`: a tuple lies in the gap sheaf.

## Main results

- `OkaRing.exists_gap_generators`: the gap sheaf is locally finitely generated.
-/

open TopologicalSpace Set Filter Topology

universe u

noncomputable section

namespace OkaRing

section FinInf

variable {ι : Type u}

/-- A finite intersection of open neighbourhoods. -/
def finInf {κ : Type*} [Finite κ] (U : Opens (ι → ℂ)) (W : κ → Opens (ι → ℂ)) : Opens (ι → ℂ) :=
  ⟨(U : Set (ι → ℂ)) ∩ ⋂ k, (W k : Set (ι → ℂ)),
    U.isOpen.inter (isOpen_iInter_of_finite fun k ↦ (W k).isOpen)⟩

lemma finInf_le {κ : Type*} [Finite κ] (U : Opens (ι → ℂ)) (W : κ → Opens (ι → ℂ)) :
    finInf U W ≤ U :=
  fun _ h ↦ h.1

lemma finInf_le' {κ : Type*} [Finite κ] (U : Opens (ι → ℂ)) (W : κ → Opens (ι → ℂ)) (k : κ) :
    finInf U W ≤ W k :=
  fun _ h ↦ mem_iInter.1 h.2 k

lemma mem_finInf {κ : Type*} [Finite κ] {U : Opens (ι → ℂ)} {W : κ → Opens (ι → ℂ)}
    {y : ι → ℂ} (hU : y ∈ U) (hW : ∀ k, y ∈ W k) : y ∈ finInf U W :=
  ⟨hU, mem_iInter.2 hW⟩


end FinInf

variable {ι : Type u} [Fintype ι] {q : ℕ}

/-! ### Spans of germs -/

/-- The span of the germs at `y` of the tuples `A j`. -/
noncomputable def germSpan {U : Opens (ι → ℂ)} {p : ℕ} (A : Fin p → Fin q → OkaRing U)
    {y : ι → ℂ} (hy : y ∈ U) : Submodule (LocalOkaRing ι) (Fin q → LocalOkaRing ι) :=
  Submodule.span _ (range fun j ↦ germVec hy (A j))

/-- The restriction of a tuple. -/
def resVec {U V : Opens (ι → ℂ)} (h : V ≤ U) (v : Fin q → OkaRing U) : Fin q → OkaRing V :=
  fun i ↦ restrict h (v i)

@[simp]
lemma germVec_resVec {U V : Opens (ι → ℂ)} (h : V ≤ U) (v : Fin q → OkaRing U) {y : ι → ℂ}
    (hy : y ∈ V) : germVec hy (resVec h v) = germVec (h hy) v := by
  ext i : 1
  simp [resVec]

lemma germSpan_resVec {U V : Opens (ι → ℂ)} (h : V ≤ U) {p : ℕ} (A : Fin p → Fin q → OkaRing U)
    {y : ι → ℂ} (hy : y ∈ V) : germSpan (fun j ↦ resVec h (A j)) hy = germSpan A (h hy) := by
  simp [germSpan]

lemma germVec_smul {U : Opens (ι → ℂ)} (c : OkaRing U) (v : Fin q → OkaRing U) {y : ι → ℂ}
    (hy : y ∈ U) : germVec hy (c • v) = germ hy c • germVec hy v := by
  ext i : 1
  simp

lemma germVec_add {U : Opens (ι → ℂ)} (v w : Fin q → OkaRing U) {y : ι → ℂ} (hy : y ∈ U) :
    germVec hy (v + w) = germVec hy v + germVec hy w :=
  map_add _ _ _

lemma germVec_sum {U : Opens (ι → ℂ)} {L : ℕ} (v : Fin L → Fin q → OkaRing U) {y : ι → ℂ}
    (hy : y ∈ U) : germVec hy (∑ l, v l) = ∑ l, germVec hy (v l) :=
  map_sum _ _ _

lemma germVec_mem_germSpan {U : Opens (ι → ℂ)} {p : ℕ} (A : Fin p → Fin q → OkaRing U)
    {y : ι → ℂ} (hy : y ∈ U) (j : Fin p) : germVec hy (A j) ∈ germSpan A hy :=
  Submodule.subset_span ⟨j, rfl⟩

lemma germVec_sum_smul_mem_germSpan {U : Opens (ι → ℂ)} {p : ℕ} (A : Fin p → Fin q → OkaRing U)
    (c : Fin p → OkaRing U) {y : ι → ℂ} (hy : y ∈ U) :
    germVec hy (∑ j, c j • A j) ∈ germSpan A hy := by
  rw [germVec_sum]
  exact Submodule.sum_mem _ fun j _ ↦ by
    rw [germVec_smul]
    exact Submodule.smul_mem _ _ (germVec_mem_germSpan A hy j)

/-- Every tuple of germs is the germ of a tuple of holomorphic functions near the point. -/
lemma exists_germVec_eq (g : Fin q → LocalOkaRing ι) {y : ι → ℂ} (U : Opens (ι → ℂ))
    (hyU : y ∈ U) : ∃ (W : Opens (ι → ℂ)) (_ : W ≤ U) (hy : y ∈ W) (v : Fin q → OkaRing W),
      germVec hy v = g := by
  choose W hyW f hf using fun i ↦ LocalOkaRing.exists_okaRing_germ (g i) y
  refine ⟨finInf U W, finInf_le U W, mem_finInf hyU hyW,
    fun i ↦ restrict (finInf_le' U W i) (f i), ?_⟩
  ext i : 1
  simp [hf]

/-- If the germ of `v` at `y` lies in the span of the germs of the `B l`, then near `y` the tuple
`v` is a combination of the `B l`. -/
lemma exists_eq_sum_of_mem_germSpan {V : Opens (ι → ℂ)} {L : ℕ} (B : Fin L → Fin q → OkaRing V)
    (v : Fin q → OkaRing V) {y : ι → ℂ} (hy : y ∈ V) (h : germVec hy v ∈ germSpan B hy) :
    ∃ (W : Opens (ι → ℂ)) (hWV : W ≤ V), y ∈ W ∧ ∃ c : Fin L → OkaRing W,
      resVec hWV v = ∑ l, c l • resVec hWV (B l) := by
  obtain ⟨W, hWV, hyW, c, hc⟩ := exists_restrict_eq_mulVec (Matrix.of fun i l ↦ B l i) v hy h
  refine ⟨W, hWV, hyW, c, funext fun i ↦ ?_⟩
  simp only [resVec, hc i, Finset.sum_apply, Pi.smul_apply, smul_eq_mul, Matrix.of_apply]

/-- A tuple of germs lies in the span of the germs of the `B l` if its product with a unit
does. -/
lemma mem_germSpan_of_isUnit {U : Opens (ι → ℂ)} {L : ℕ} (B : Fin L → Fin q → OkaRing U)
    {y : ι → ℂ} (hy : y ∈ U) {c : LocalOkaRing ι} (hc : IsUnit c) {g : Fin q → LocalOkaRing ι}
    (h : c • g ∈ germSpan B hy) : g ∈ germSpan B hy := by
  obtain ⟨u, rfl⟩ := hc
  have := Submodule.smul_mem _ (↑u⁻¹ : LocalOkaRing ι) h
  rwa [smul_smul, Units.inv_mul, one_smul] at this

/-! ### The gap sheaf -/

variable {U : Opens (ι → ℂ)} {p : ℕ} (A : Fin p → Fin q → OkaRing U) (Z : Set (ι → ℂ))

/-- The tuple `v` over `W ≤ U` lies in the **gap sheaf** of the subsheaf generated by the `A j`
with respect to `Z`: its germs at the points of `W` off `Z` lie in the span of the germs of the
`A j`. -/
def IsGapGood {W : Opens (ι → ℂ)} (hWU : W ≤ U) (v : Fin q → OkaRing W) : Prop :=
  ∀ (y : ι → ℂ) (hy : y ∈ W), y ∉ Z → germVec hy v ∈ germSpan A (hWU hy)

variable {A Z}

lemma IsGapGood.resVec {W W' : Opens (ι → ℂ)} {hWU : W ≤ U} {v : Fin q → OkaRing W}
    (hv : IsGapGood A Z hWU v) (h : W' ≤ W) : IsGapGood A Z (h.trans hWU) (resVec h v) :=
  fun y hy hyZ ↦ by
    rw [germVec_resVec]
    exact hv y (h hy) hyZ

lemma isGapGood_resVec_col {W : Opens (ι → ℂ)} (hWU : W ≤ U) (j : Fin p) :
    IsGapGood A Z hWU (resVec hWU (A j)) :=
  fun y hy _ ↦ by
    rw [germVec_resVec]
    exact germVec_mem_germSpan A _ j

variable (A Z) in
/-- The germs at `x₀` of the tuples of the gap sheaf. -/
noncomputable def gapSubmodule {x₀ : ι → ℂ} (hx₀ : x₀ ∈ U) :
    Submodule (LocalOkaRing ι) (Fin q → LocalOkaRing ι) where
  carrier := {g | ∃ (W : Opens (ι → ℂ)) (hWU : W ≤ U) (hx : x₀ ∈ W) (v : Fin q → OkaRing W),
    germVec hx v = g ∧ IsGapGood A Z hWU v}
  zero_mem' := ⟨U, le_rfl, hx₀, 0, map_zero _, fun y hy _ ↦ by
    rw [map_zero]
    exact Submodule.zero_mem _⟩
  add_mem' := by
    rintro _ _ ⟨W₁, h₁, hx₁, v₁, rfl, hv₁⟩ ⟨W₂, h₂, hx₂, v₂, rfl, hv₂⟩
    refine ⟨W₁ ⊓ W₂, inf_le_left.trans h₁, ⟨hx₁, hx₂⟩,
      resVec inf_le_left v₁ + resVec inf_le_right v₂, ?_, fun y hy hyZ ↦ ?_⟩
    · rw [germVec_add, germVec_resVec, germVec_resVec]
    · rw [germVec_add]
      exact Submodule.add_mem _ ((hv₁.resVec inf_le_left) y hy hyZ)
        ((hv₂.resVec inf_le_right) y hy hyZ)
  smul_mem' := by
    rintro c _ ⟨W, hWU, hx, v, rfl, hv⟩
    obtain ⟨W₃, hyW₃, f, hf⟩ := LocalOkaRing.exists_okaRing_germ c x₀
    refine ⟨W ⊓ W₃, inf_le_left.trans hWU, ⟨hx, hyW₃⟩,
      restrict (inf_le_right : W ⊓ W₃ ≤ W₃) f • resVec (inf_le_left : W ⊓ W₃ ≤ W) v, ?_,
      fun y hy hyZ ↦ ?_⟩
    · rw [germVec_smul, germVec_resVec, germ_restrict, hf]
    · rw [germVec_smul]
      exact Submodule.smul_mem _ _ ((hv.resVec inf_le_left) y hy hyZ)

variable {S : ℕ} {f : Fin S → OkaRing U}

/-- **The gap sheaf is closed under division by the `f_s`**: if `f_s g` lies in the gap
submodule for all `s`, then so does `g`, since off `Z` some `f_s` is a unit. -/
lemma mem_gapSubmodule_of_smul_mem
    (hZ : ∀ y (hy : y ∈ U), y ∈ Z ↔ ∀ s, evalHom hy (f s) = 0) {x₀ : ι → ℂ} (hx₀ : x₀ ∈ U)
    {g : Fin q → LocalOkaRing ι} (hg : ∀ s, germ hx₀ (f s) • g ∈ gapSubmodule A Z hx₀) :
    g ∈ gapSubmodule A Z hx₀ := by
  obtain ⟨W₀, hW₀U, hx₀W₀, v, rfl⟩ := exists_germVec_eq g U hx₀
  choose W hWU hxW v' hv' hgood using hg
  -- `v' s = f_s v` near `x₀`
  have hloc : ∀ s, ∃ (W' : Opens (ι → ℂ)) (h' : W' ≤ W s ⊓ W₀), x₀ ∈ W' ∧
      resVec (h'.trans inf_le_left) (v' s) =
        restrict (h'.trans (inf_le_right.trans hW₀U)) (f s) • resVec (h'.trans inf_le_right) v := by
    intro s
    have heq : ∀ i, germ (show x₀ ∈ W s ⊓ W₀ from ⟨hxW s, hx₀W₀⟩)
        (restrict inf_le_left (v' s i) - restrict (inf_le_right.trans hW₀U) (f s) *
          restrict inf_le_right (v i)) = 0 := fun i ↦ by
      have := congrFun (hv' s) i
      simp only [germVec_apply, Pi.smul_apply, smul_eq_mul] at this
      rw [map_sub, map_mul, germ_restrict, germ_restrict, germ_restrict, this, sub_self]
    choose W' hW' hxW' hz using fun i ↦ exists_restrict_eq_zero _ (heq i)
    refine ⟨finInf (W s ⊓ W₀) W', finInf_le _ _, mem_finInf ⟨hxW s, hx₀W₀⟩ hxW',
      funext fun i ↦ ?_⟩
    have := congrArg (restrict (finInf_le' (W s ⊓ W₀) W' i)) (hz i)
    simp only [map_sub, map_mul, restrict_restrict, map_zero, sub_eq_zero] at this
    simpa [resVec] using this
  choose W' hW' hxW' hW'eq using hloc
  refine ⟨finInf W₀ W', finInf_le _ _ |>.trans hW₀U, mem_finInf hx₀W₀ hxW',
    resVec (finInf_le _ _) v, by rw [germVec_resVec], fun y hy hyZ ↦ ?_⟩
  obtain ⟨s, hs⟩ : ∃ s, evalHom (hW₀U (finInf_le _ _ hy)) (f s) ≠ 0 := by
    by_contra h
    push Not at h
    exact hyZ ((hZ y _).2 h)
  have hyW' : y ∈ W' s := finInf_le' W₀ W' s hy
  have h₁ := hgood s y ((hW' s hyW').1) hyZ
  have h₂ : germVec ((hW' s hyW').1) (v' s) =
      germ (hW₀U (finInf_le _ _ hy)) (f s) • germVec (finInf_le _ _ hy) v := by
    rw [← germVec_resVec (hW' s |>.trans inf_le_left) (v' s) hyW', hW'eq s, germVec_smul,
      germ_restrict, germVec_resVec]
  rw [h₂] at h₁
  rw [germVec_resVec]
  refine mem_germSpan_of_isUnit A _ ?_ h₁
  rw [LocalOkaRing.isUnit_iff, constantCoeff_germ]
  exact hs

/-- **A nonzerodivisor in the ideal of `Z`**: some combination `φ` of the germs of the `f_s` at
`x₀` is a nonzerodivisor on `𝒪_{x₀}^q ⧸ Ŝ`. -/
lemma exists_isSMulRegular (hZ : ∀ y (hy : y ∈ U), y ∈ Z ↔ ∀ s, evalHom hy (f s) = 0)
    {x₀ : ι → ℂ} (hx₀ : x₀ ∈ U) :
    ∃ φ ∈ Ideal.span (range fun s ↦ germ hx₀ (f s)), ∀ g : Fin q → LocalOkaRing ι,
      φ • g ∈ gapSubmodule A Z hx₀ → g ∈ gapSubmodule A Z hx₀ := by
  classical
  set M := (Fin q → LocalOkaRing ι) ⧸ gapSubmodule A Z hx₀
  set J : Ideal (LocalOkaRing ι) := Ideal.span (range fun s ↦ germ hx₀ (f s))
  by_contra hcon
  push Not at hcon
  -- every element of `J` is a zero divisor on `M`
  have hJ : (J : Set (LocalOkaRing ι)) ⊆ ⋃ P ∈ associatedPrimes (LocalOkaRing ι) M, P := by
    intro φ hφ
    obtain ⟨g, hg, hg'⟩ := hcon φ hφ
    rw [biUnion_associatedPrimes_eq_zero_divisors]
    refine ⟨Submodule.Quotient.mk g, fun h ↦ hg' ((Submodule.Quotient.mk_eq_zero _).1 h), ?_⟩
    rw [← Submodule.Quotient.mk_smul, Submodule.Quotient.mk_eq_zero]
    exact hg
  have hfin := associatedPrimes.finite (LocalOkaRing ι) M
  rw [← hfin.coe_toFinset] at hJ
  have hJ' : (J : Set (LocalOkaRing ι)) ⊆ ⋃ P ∈ (↑hfin.toFinset : Set (Ideal (LocalOkaRing ι))),
      id P := by simpa using hJ
  obtain ⟨P, hP, hJP⟩ := (Ideal.subset_union_prime (s := hfin.toFinset) (f := id) ⊥ ⊥
    (fun P hP _ _ ↦ by
      rw [Set.Finite.mem_toFinset] at hP
      exact hP.1)).1 hJ'
  rw [Set.Finite.mem_toFinset, AssociatedPrimes.mem_iff, isAssociatedPrime_iff] at hP
  obtain ⟨hPprime, x, rfl⟩ := hP
  obtain ⟨g, rfl⟩ := Submodule.Quotient.mk_surjective _ x
  have hg : g ∈ gapSubmodule A Z hx₀ := mem_gapSubmodule_of_smul_mem hZ hx₀ fun s ↦ by
    have hs : germ hx₀ (f s) ∈ J := Ideal.subset_span ⟨s, rfl⟩
    have := hJP hs
    rw [id, Submodule.mem_colon_singleton, Submodule.mem_bot, ← Submodule.Quotient.mk_smul,
      Submodule.Quotient.mk_eq_zero] at this
    exact this
  refine hPprime.ne_top (Ideal.eq_top_iff_one _ |>.2 ?_)
  rw [Submodule.mem_colon_singleton, one_smul, Submodule.mem_bot,
    Submodule.Quotient.mk_eq_zero]
  exact hg

lemma sum_mul_single {R : Type*} [CommRing R] (c : Fin q → R) (φ : R) (j : Fin q) :
    ∑ i, c i * Pi.single (M := fun _ ↦ R) i φ j = c j * φ := by
  rw [Finset.sum_eq_single j (fun i _ hij ↦ by rw [Pi.single_apply, if_neg (Ne.symm hij),
    mul_zero]) (by simp), Pi.single_eq_same]

/-- The family `(φ eᵢ)ᵢ, (b_l)_l`, whose relations are the pairs `(c, d)` with
`φ c + ∑ d_l b_l = 0`. -/
def relFamily {V : Opens (ι → ℂ)} {L : ℕ} (φ : OkaRing V) (B : Fin L → Fin q → OkaRing V) :
    Fin (q + L) → Fin q → OkaRing V :=
  Fin.append (fun i ↦ Pi.single i φ) B

lemma sum_relFamily {V W : Opens (ι → ℂ)} (h : W ≤ V) {L : ℕ} (φ : OkaRing V)
    (B : Fin L → Fin q → OkaRing V) (a : Fin (q + L) → OkaRing W) (j : Fin q) :
    ∑ i, a i * restrict h (relFamily φ B i j) =
      a (Fin.castAdd L j) * restrict h φ + ∑ l, a (Fin.natAdd q l) * restrict h (B l j) := by
  rw [Fin.sum_univ_add]
  congr 1
  · simp only [relFamily, Fin.append_left]
    rw [← sum_mul_single (fun i ↦ a (Fin.castAdd L i)) (restrict h φ) j]
    refine Finset.sum_congr rfl fun i _ ↦ ?_
    rw [Pi.single_apply, Pi.single_apply]
    split_ifs <;> simp
  · simp [relFamily]

/-- **The gap sheaf is locally finitely generated.** Let `Z ∩ U` be the common zero set of the
`f_s`. Near every point `x₀ ∈ U` there are finitely many tuples `B l` in the gap sheaf of the
subsheaf generated by the `A j` whose germs generate the germs of every tuple of the gap sheaf. -/
theorem exists_gap_generators (hZ : ∀ y (hy : y ∈ U), y ∈ Z ↔ ∀ s, evalHom hy (f s) = 0)
    {x₀ : ι → ℂ} (hx₀ : x₀ ∈ U) :
    ∃ (V : Opens (ι → ℂ)) (hVU : V ≤ U), x₀ ∈ V ∧ ∃ (L : ℕ) (B : Fin L → Fin q → OkaRing V),
      (∀ l, IsGapGood A Z hVU (B l)) ∧
      ∀ (W : Opens (ι → ℂ)) (hWV : W ≤ V) (v : Fin q → OkaRing W),
        IsGapGood A Z (hWV.trans hVU) v → ∀ y (hy : y ∈ W), germVec hy v ∈ germSpan B (hWV hy) := by
  classical
  -- generators of the gap submodule at `x₀`
  obtain ⟨L, g, hg⟩ := Submodule.fg_iff_exists_fin_generating_family.1
    (IsNoetherian.noetherian (gapSubmodule A Z hx₀))
  have hgmem : ∀ l, g l ∈ gapSubmodule A Z hx₀ := fun l ↦ hg ▸ Submodule.subset_span ⟨l, rfl⟩
  choose W₁ hW₁U hxW₁ v₁ hv₁ hgood₁ using hgmem
  set V₁ := finInf U W₁
  have hV₁U : V₁ ≤ U := finInf_le U W₁
  have hxV₁ : x₀ ∈ V₁ := mem_finInf hx₀ hxW₁
  set B₁ : Fin L → Fin q → OkaRing V₁ := fun l ↦ resVec (finInf_le' U W₁ l) (v₁ l)
  have hB₁good : ∀ l, IsGapGood A Z hV₁U (B₁ l) := fun l ↦ (hgood₁ l).resVec _
  have hB₁x : germSpan B₁ hxV₁ = gapSubmodule A Z hx₀ := by
    rw [← hg, germSpan]
    congr 1
    ext t
    simp only [mem_range]
    refine exists_congr fun l ↦ ?_
    rw [germVec_resVec, hv₁]
  -- a nonzerodivisor `φ` vanishing on `Z`
  obtain ⟨φ, hφJ, hφreg⟩ := exists_isSMulRegular (A := A) hZ hx₀
  obtain ⟨a, ha⟩ := Ideal.mem_span_range_iff_exists_fun.1 hφJ
  choose W₂ hxW₂ ã hã using fun s ↦ LocalOkaRing.exists_okaRing_germ (a s) x₀
  set V₂ := finInf V₁ W₂
  have hV₂V₁ : V₂ ≤ V₁ := finInf_le V₁ W₂
  have hxV₂ : x₀ ∈ V₂ := mem_finInf hxV₁ hxW₂
  set φ' : OkaRing V₂ :=
    ∑ s, restrict (finInf_le' V₁ W₂ s) (ã s) * restrict (hV₂V₁.trans hV₁U) (f s)
  have hφ'x : germ hxV₂ φ' = φ := by
    rw [← ha, map_sum]
    refine Finset.sum_congr rfl fun s _ ↦ ?_
    rw [map_mul, germ_restrict, germ_restrict, hã]
  have hφ'Z : ∀ y (hy : y ∈ V₂), y ∈ Z → evalHom hy φ' = 0 := by
    intro y hy hyZ
    have h := (hZ y (hV₁U (hV₂V₁ hy))).1 hyZ
    simp only [φ', map_sum, map_mul, evalHom_restrict, h, mul_zero, Finset.sum_const_zero]
  -- Oka's theorem for the relations `φ c + ∑ d_l b_l = 0`
  set B₂ : Fin L → Fin q → OkaRing V₂ := fun l ↦ resVec hV₂V₁ (B₁ l)
  obtain ⟨V₃, hV₃, K, gR, hxV₃, hrel, hgen⟩ := oka' V₂ (relFamily φ' B₂) x₀ hxV₂
  -- the first components of the generating relations are combinations of the `b_l` near `x₀`
  have hc : ∀ k, ∃ (W : Opens (ι → ℂ)) (hW : W ≤ V₃), x₀ ∈ W ∧ ∃ e : Fin L → OkaRing W,
      resVec hW (fun i ↦ gR k (Fin.castAdd L i)) =
        ∑ l, e l • resVec (hW.trans (hV₃.trans hV₂V₁)) (B₁ l) := by
    intro k
    have hrelk : restrict hV₃ φ' • (fun i ↦ gR k (Fin.castAdd L i)) =
        -∑ l, gR k (Fin.natAdd q l) • resVec (hV₃.trans hV₂V₁) (B₁ l) := by
      funext j
      have := hrel k j
      rw [sum_relFamily] at this
      simp only [Pi.smul_apply, smul_eq_mul, Pi.neg_apply, Finset.sum_apply, resVec]
      simp only [B₂, resVec, restrict_restrict] at this
      linear_combination this
    have hmem : φ • germVec hxV₃ (fun i ↦ gR k (Fin.castAdd L i)) ∈ gapSubmodule A Z hx₀ := by
      rw [← hB₁x, ← hφ'x, ← germ_restrict hV₃ hxV₃, ← germVec_smul, hrelk, map_neg]
      refine Submodule.neg_mem _ ?_
      have := germVec_sum_smul_mem_germSpan (fun l ↦ resVec (hV₃.trans hV₂V₁) (B₁ l))
        (fun l ↦ gR k (Fin.natAdd q l)) hxV₃
      rwa [germSpan_resVec] at this
    have hmem' := hφreg _ hmem
    rw [← hB₁x, ← germSpan_resVec (hV₃.trans hV₂V₁) B₁ hxV₃] at hmem'
    obtain ⟨W, hW, hxW, e, he⟩ := exists_eq_sum_of_mem_germSpan _ _ hxV₃ hmem'
    refine ⟨W, hW, hxW, e, ?_⟩
    rw [he]
    rfl
  choose W₄ hW₄ hxW₄ e he using hc
  -- the columns of `A` are combinations of the `b_l` near `x₀`
  have hA : ∀ j, ∃ (W : Opens (ι → ℂ)) (hW : W ≤ V₁), x₀ ∈ W ∧ ∃ E : Fin L → OkaRing W,
      resVec (hW.trans hV₁U) (A j) = ∑ l, E l • resVec hW (B₁ l) := by
    intro j
    have hmem : germVec (hV₁U hxV₁) (A j) ∈ germSpan B₁ hxV₁ := by
      rw [hB₁x]
      exact ⟨U, le_rfl, hx₀, A j, rfl, fun y hy _ ↦ germVec_mem_germSpan A hy j⟩
    rw [← germVec_resVec hV₁U (A j) hxV₁] at hmem
    exact exists_eq_sum_of_mem_germSpan _ _ hxV₁ hmem
  choose W₅ hW₅ hxW₅ E hE using hA
  set V : Opens (ι → ℂ) := finInf (finInf V₃ W₄) W₅
  have hVV₃ : V ≤ V₃ := (finInf_le _ _).trans (finInf_le _ _)
  have hVV₁ : V ≤ V₁ := hVV₃.trans (hV₃.trans hV₂V₁)
  have hxV : x₀ ∈ V := mem_finInf (mem_finInf hxV₃ hxW₄) hxW₅
  have hVW₄ : ∀ k, V ≤ W₄ k := fun k ↦ (finInf_le _ _).trans (finInf_le' _ _ k)
  set B : Fin L → Fin q → OkaRing V := fun l ↦ resVec hVV₁ (B₁ l)
  have hBspan : ∀ y (hy : y ∈ V), germSpan B hy = germSpan B₁ (hVV₁ hy) :=
    fun y hy ↦ germSpan_resVec hVV₁ B₁ hy
  -- `A ⊆ span B` on `V`
  have hAB : ∀ y (hy : y ∈ V), germSpan A (hV₁U (hVV₁ hy)) ≤ germSpan B hy := by
    intro y hy
    rw [germSpan, Submodule.span_le]
    rintro _ ⟨j, rfl⟩
    have hyW₅ : y ∈ W₅ j := finInf_le' _ _ j hy
    have h₁ := congrArg (germVec hyW₅) (hE j)
    rw [germVec_resVec] at h₁
    change germVec (hV₁U (hVV₁ hy)) (A j) ∈ germSpan B hy
    rw [h₁, hBspan]
    have := germVec_sum_smul_mem_germSpan (fun l ↦ resVec (hW₅ j) (B₁ l)) (E j) hyW₅
    rwa [germSpan_resVec] at this
  -- `φ` is a nonzerodivisor modulo the `b_l` at every point of `V`
  have hreg : ∀ y (hy : y ∈ V) (u : Fin q → LocalOkaRing ι),
      germ (hV₃ (hVV₃ hy)) φ' • u ∈ germSpan B hy →
        u ∈ germSpan B hy := by
    intro y hy u hu
    obtain ⟨W₆, hW₆, hyW₆, ũ, rfl⟩ := exists_germVec_eq u V hy
    have hu' : germVec hyW₆ (restrict (hW₆.trans (hVV₃.trans hV₃)) φ' • ũ) ∈
        germSpan (fun l ↦ resVec hW₆ (B l)) hyW₆ := by
      rw [germVec_smul, germ_restrict, germSpan_resVec]
      exact hu
    obtain ⟨W₇, hW₇, hyW₇, c, hc⟩ := exists_eq_sum_of_mem_germSpan _ _ hyW₆ hu'
    have hW₇V₃ : W₇ ≤ V₃ := hW₇.trans (hW₆.trans hVV₃)
    obtain ⟨W₈, hW₈, hyW₈, γ, hγ⟩ := hgen W₇ hW₇V₃
      (Fin.append (resVec hW₇ ũ) (fun l ↦ -c l)) (fun j ↦ by
        rw [sum_relFamily]
        have := congrFun hc j
        simp only [resVec, Finset.sum_apply, Pi.smul_apply, smul_eq_mul, map_mul,
          restrict_restrict, B] at this
        simp only [Fin.append_left, Fin.append_right, resVec, restrict_restrict, B₂, neg_mul,
          Finset.sum_neg_distrib]
        linear_combination this) y hyW₇
    have hũ : resVec (hW₈.trans hW₇) ũ = ∑ k, γ k • resVec (hW₈.trans hW₇V₃)
        (fun i ↦ gR k (Fin.castAdd L i)) := by
      funext i
      have := hγ (Fin.castAdd L i)
      simp only [Fin.append_left, resVec, restrict_restrict] at this
      simp only [resVec, this, Finset.sum_apply, Pi.smul_apply, smul_eq_mul]
    rw [← germVec_resVec (hW₈.trans hW₇) ũ hyW₈, hũ, germVec_sum, hBspan]
    refine Submodule.sum_mem _ fun k _ ↦ ?_
    rw [germVec_smul]
    refine Submodule.smul_mem _ _ ?_
    have hyW₄ : y ∈ W₄ k := hVW₄ k hy
    rw [germVec_resVec, ← germVec_resVec (hW₄ k) _ hyW₄, he k]
    have := germVec_sum_smul_mem_germSpan
      (fun l ↦ resVec ((hW₄ k).trans (hV₃.trans hV₂V₁)) (B₁ l)) (e k) hyW₄
    rwa [germSpan_resVec] at this
  refine ⟨V, hVV₁.trans hV₁U, hxV, L, B, fun l ↦ (hB₁good l).resVec hVV₁,
    fun W hWV v hv y hy ↦ ?_⟩
  -- a power of `φ` moves `v` into the span of the `b_l`
  set F' : Fin (1 + L) → Fin q → OkaRing W := Fin.append (fun _ ↦ v) (fun l ↦ resVec hWV (B l))
  obtain ⟨V₉, hV₉, K', gC, hyV₉, hrelC, hgenC⟩ := oka' W F' y hy
  have hV₉V : V₉ ≤ V := hV₉.trans hWV
  have hrelC' : ∀ k, gC k (Fin.castAdd L 0) • resVec hV₉ v =
      -∑ l, gC k (Fin.natAdd 1 l) • resVec hV₉V (B l) := by
    intro k
    funext j
    have := hrelC k j
    rw [Fin.sum_univ_add] at this
    simp only [F', Fin.append_left, Fin.append_right, Finset.univ_unique, Fin.default_eq_zero,
      Finset.sum_singleton] at this
    simp only [Pi.smul_apply, smul_eq_mul, Pi.neg_apply, Finset.sum_apply, resVec,
      restrict_restrict] at this ⊢
    linear_combination this
  have hrad := germ_mem_radical_span_of_eventually hyV₉ (fun k ↦ gC k (Fin.castAdd L 0))
    (restrict (hV₉V.trans (hVV₃.trans hV₃)) φ') (by
      filter_upwards [V₉.isOpen.mem_nhds hyV₉] with y' hy' hzero
      by_cases hy'Z : y' ∈ Z
      · rw [toGlobalFun_apply _ hy']
        exact hφ'Z y' _ hy'Z
      · exfalso
        have hy'W : y' ∈ W := hV₉ hy'
        have hmem := hAB y' (hWV hy'W) (hv y' hy'W hy'Z)
        rw [← germSpan_resVec hWV B hy'W] at hmem
        obtain ⟨W₁₀, hW₁₀, hy'W₁₀, d, hd⟩ := exists_eq_sum_of_mem_germSpan _ _ hy'W hmem
        obtain ⟨W₁₁, hW₁₁, hy'W₁₁, δ, hδ⟩ := hgenC (W₁₀ ⊓ V₉) inf_le_right
          (Fin.append (fun _ ↦ 1) (fun l ↦ -restrict inf_le_left (d l))) (fun j ↦ by
            rw [Fin.sum_univ_add]
            have := congrFun hd j
            simp only [F', Fin.append_left, Fin.append_right, Finset.univ_unique,
              Fin.default_eq_zero, Finset.sum_singleton, resVec, Finset.sum_apply,
              Pi.smul_apply, smul_eq_mul, restrict_restrict, one_mul, neg_mul,
              Finset.sum_neg_distrib] at this ⊢
            have := congrArg (restrict (inf_le_left : W₁₀ ⊓ V₉ ≤ W₁₀)) this
            simp only [map_sum, map_mul, restrict_restrict] at this
            rw [this]
            ring) y' ⟨hy'W₁₀, hy'⟩
        have h1 := congrArg (evalHom hy'W₁₁) (hδ (Fin.castAdd L 0))
        simp only [Fin.append_left, map_one, map_sum, map_mul, evalHom_restrict] at h1
        rw [Finset.sum_eq_zero fun k _ ↦ by
          rw [show evalHom _ (gC k (Fin.castAdd L 0)) = 0 from by
            have := hzero k
            rwa [toGlobalFun_apply _ hy'] at this, mul_zero]] at h1
        exact one_ne_zero h1)
  obtain ⟨N, hN⟩ := hrad
  obtain ⟨β, hβ⟩ := Ideal.mem_span_range_iff_exists_fun.1 hN
  have hpow : (germ (hV₃ (hVV₃ (hWV hy))) φ') ^ N • germVec hy v ∈
      germSpan B (hWV hy) := by
    rw [germ_restrict] at hβ
    rw [← hβ, Finset.sum_smul, ← germSpan_resVec hWV B hy]
    refine Submodule.sum_mem _ fun k _ ↦ ?_
    rw [mul_smul]
    refine Submodule.smul_mem _ _ ?_
    rw [← germVec_resVec hV₉ v hyV₉, ← germVec_smul, hrelC', map_neg,
      ← germSpan_resVec hV₉ (fun l ↦ resVec hWV (B l)) hyV₉]
    refine Submodule.neg_mem _ ?_
    have := germVec_sum_smul_mem_germSpan (fun l ↦ resVec hV₉V (B l))
      (fun l ↦ gC k (Fin.natAdd 1 l)) hyV₉
    exact this
  have hpowreg : ∀ (n : ℕ) (u : Fin q → LocalOkaRing ι),
      (germ (hV₃ (hVV₃ (hWV hy))) φ') ^ n • u ∈ germSpan B (hWV hy) →
        u ∈ germSpan B (hWV hy) := by
    intro n
    induction n with
    | zero => intro u hu; simpa using hu
    | succ n ih =>
      intro u hu
      refine ih u (hreg y (hWV hy) _ ?_)
      rwa [smul_smul, ← pow_succ']
  exact hpowreg N _ hpow

end OkaRing

end
