/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.Analytification.RET.ES.CapExtension.GraphRep

/-!
# Local finiteness of the sections of the cap across the zero set

Keep the notation of `Oka/Analytification/RET/ES/CapExtension/GraphRep.lean`. Near a point `z` of
`V` the graph `Φ` of the fibres of the evaluation has a holomorphic denominator: `Φ = Ψ / c`
(`ComplexAnalytic.Cap.AnnulusDecomposition.exists_graph_rep`). We show that near `z` the
evaluations of the sections of the cap are exactly the tuples `v` of holomorphic functions with
`c vₓ = ∑ₑ Ψₓₑ v_{I₀ e}`:

* the evaluation of a section satisfies these equations, since they hold at the good points
  (`ComplexAnalytic.Cap.AnnulusDecomposition.kerCond_evalVec`);
* conversely, near a point of `V ∖ Z` with local generators `s` and minor `δ`, Cramer's rule writes
  `δ v` as the evaluation of a combination of the `s`, and by saturation (Lemma L,
  `ComplexAnalytic.Cap.AnnulusDecomposition.exists_capPole_evalVec_eq_of_mul`) `v` is locally an
  evaluation; these glue over `V ∖ Z` and extend across `Z` by Hartogs
  (`ComplexAnalytic.Cap.AnnulusDecomposition.exists_capPole_of_kerCond`).

The solutions of the equations are locally finitely generated by Oka's theorem, so the sections of
the cap are locally finitely generated at `z`
(`ComplexAnalytic.Cap.AnnulusDecomposition.capLocallyFinite_of_forall_not_mem`).
-/

open CategoryTheory Opposite Topology Set Filter Metric Module
open scoped Matrix

universe u

namespace ComplexAnalytic.Cap.AnnulusDecomposition

open AnalyticSpace BoundedSections Complex.ProjectiveLineBundle AlgebraicGeometry.LocallyRingedSpace
open KummerModel (splitEquiv)

noncomputable section

variable {m : ℕ} {N N₀ : (AnalyticSpace.complexAffineSpace.{u} (m + 1)).Opens} {h₀ : N₀ ≤ N}
  {W : FiniteEtaleOver (space N₀)} [T2Space W.left] {F : WeierstrassForm N N₀}
  {D : AnnulusDecomposition W F.G F.ρ} {n : ℕ} {M : ℕ} {w : Fin M → ℂ} {r : ℕ}
  {I₀ : Fin r → D.EvIdx M} {R : RegularPairFamily F.G} {V : Set (Cm.{u} m)}

/-- A dense subset of `V` is dense in every open subset of `V`. -/
lemma subset_closure_inter_of_subset_closure {S O : Set (Cm.{u} m)} (hO : IsOpen O) (hOV : O ⊆ V)
    (hS : V ⊆ closure S) : O ⊆ closure (O ∩ S) := fun y hy ↦ by
  rw [mem_closure_iff_nhds]
  intro t ht
  obtain ⟨z, hz, hzS⟩ :=
    mem_closure_iff_nhds.1 (hS (hOV hy)) (t ∩ O) (inter_mem ht (hO.mem_nhds hy))
  exact ⟨z, hz.1, hz.2, hzS⟩

/-- The points of an open set where two functions whose zero sets have empty interior do not
vanish are dense. -/
lemma subset_closure_ne_zero {O : Set (Cm.{u} m)} (hO : IsOpen O) {g h : Cm.{u} m → ℂ}
    (hg : ContinuousOn g O) (hg0 : interior (O ∩ g ⁻¹' {0}) = ∅)
    (hh0 : interior (O ∩ h ⁻¹' {0}) = ∅) :
    O ⊆ closure (O ∩ {y | g y ≠ 0} ∩ {y | h y ≠ 0}) := by
  refine (subset_closure_diff_zero hO
    (interior_inter_preimage_zero_mul_eq_empty hg hg0 hh0)).trans
    (closure_mono fun y hy ↦ ?_)
  have hy2 : g y * h y ≠ 0 := hy.2
  exact ⟨⟨hy.1, left_ne_zero_of_mul hy2⟩, right_ne_zero_of_mul hy2⟩

omit [T2Space W.left] in
/-- **The evaluation of a section of the cap satisfies the equations of the graph.** -/
theorem kerCond_evalVec {N' : Set (Cm.{u} m)} (hN'V : N' ⊆ V) {c : Cm.{u} m → ℂ}
    {Ψ : D.EvIdx M → Fin r → Cm.{u} m → ℂ} (hc : DifferentiableOn ℂ c N')
    (hΨ : ∀ x e, DifferentiableOn ℂ (Ψ x e) N') (hc0 : interior (N' ∩ c ⁻¹' {0}) = ∅)
    (hΦ : ∀ y ∈ N', y ∈ D.goodSet h₀ n w I₀ R V → c y ≠ 0 →
      ∀ x e, D.graphFun h₀ n w I₀ x e y = Ψ x e y / c y)
    (hdense : V ⊆ closure (D.goodSet h₀ n w I₀ R V)) (hwρ : ∀ ν, w ν ∈ overlap F.ρ)
    {V' : Set (Cm.{u} m)} {hV' : IsOpen V'} (hV'N' : V' ⊆ N') (hV'G : V' ⊆ F.G)
    {t : boundedSubring h₀ W (tubeN N V' hV') × (D.ι → Cm.{u} m × ℂ → ℂ)}
    (ht : t ∈ D.capPole h₀ n (tubeN N V' hV') (V' ×ˢ ball 0 F.ρ)) :
    ∀ y ∈ V', ∀ x, c y * D.evalVec w t.1.1 y x =
      ∑ e, Ψ x e y * D.evalVec w t.1.1 y (I₀ e) := by
  intro y hy x
  have hev : ∀ x, DifferentiableOn ℂ (fun y ↦ D.evalVec w t.1.1 y x) V' := fun x ↦
    (D.differentiableOn_evalVec F.isOpen_G hwρ t.1.1 x).mono fun y hy ↦ ⟨hV'G hy, by
      rw [F.mem_img_tubeN hV'G, Homeomorph.apply_symm_apply]
      exact ⟨hy, mem_ball_zero_iff.2 (hwρ _).2⟩⟩
  set O := V' ∩ {y | c y ≠ 0}
  have hO : IsOpen O := (hc.mono hV'N').continuousOn.isOpen_inter_preimage hV' isOpen_ne
  have hV'O : V' ⊆ closure O := by
    refine (subset_closure_diff_zero hV' (subset_empty_iff.1 (hc0 ▸ interior_mono
      fun y hy ↦ ⟨hV'N' hy.1, hy.2⟩))).trans (closure_mono fun y hy ↦ ⟨hy.1, hy.2⟩)
  have hOd : O ⊆ closure (O ∩ D.goodSet h₀ n w I₀ R V) :=
    subset_closure_inter_of_subset_closure hO (fun y hy ↦ hN'V (hV'N' hy.1)) hdense
  refine Set.EqOn.of_subset_closure (s := O ∩ D.goodSet h₀ n w I₀ R V) (t := V') ?_
    ((hc.mono hV'N').continuousOn.mul (hev x).continuousOn)
    (continuousOn_finsetSum _ fun e _ ↦ ((hΨ x e).mono hV'N').continuousOn.mul
      (hev _).continuousOn) (fun y hy ↦ hy.1.1)
    (hV'O.trans (closure_minimal hOd isClosed_closure)) hy
  intro y ⟨⟨hyV', hcy⟩, hyg⟩
  have hmem := evalVec_mem_fibImage hV'G hyV' ht (w := w)
  have hsum := Submodule.eq_sum_graphVec hyg.2.1 hmem
  have hx := congrFun hsum x
  simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul] at hx
  change c y * D.evalVec w t.1.1 y x = ∑ e, Ψ x e y * D.evalVec w t.1.1 y (I₀ e)
  rw [hx, Finset.mul_sum]
  refine Finset.sum_congr rfl fun e _ ↦ ?_
  have hΦe := hΦ y (hV'N' hyV') hyg hcy x e
  rw [graphFun, dif_pos hyg.2.1] at hΦe
  have hcy' : c y ≠ 0 := hcy
  rw [hΦe]
  field_simp

section Solutions

variable (hwρ : ∀ ν, w ν ∈ overlap F.ρ) (hw : Function.Injective w)
  (hM : (∑ i, (D.deg i : ℕ)) * n < M)
  (hloc : ∀ b ∈ F.G, b ∉ R.zeroSet → D.CapLocallyFinite h₀ n b) (hVo : IsOpen V)
  (hVG : V ⊆ F.G) (hVc : IsPreconnected V)
  (hr : ∀ y ∈ V \ R.zeroSet, finrank ℂ (D.fibImage h₀ n w y) ≤ r)
  (hb₀ : ∃ b ∈ V \ R.zeroSet, D.IsGood h₀ n w I₀ b)
  {N' : Set (Cm.{u} m)} (hN'V : N' ⊆ V) {c : Cm.{u} m → ℂ}
  {Ψ : D.EvIdx M → Fin r → Cm.{u} m → ℂ} (hc : DifferentiableOn ℂ c N')
  (hΨ : ∀ x e, DifferentiableOn ℂ (Ψ x e) N') (hc0 : interior (N' ∩ c ⁻¹' {0}) = ∅)
  (hΦ : ∀ y ∈ N', y ∈ D.goodSet h₀ n w I₀ R V → c y ≠ 0 →
    ∀ x e, D.graphFun h₀ n w I₀ x e y = Ψ x e y / c y)

include hwρ hw hM hloc hVo hVG hVc hr hb₀ hN'V hc hc0 hΦ in
/-- **Solutions of the equations of the graph are locally evaluations** off `Z`, by Cramer's rule
and saturation. -/
theorem exists_local_capPole_of_kerCond {V' : Set (Cm.{u} m)} (hV' : IsOpen V') (hV'N' : V' ⊆ N')
    {v : D.EvIdx M → Cm.{u} m → ℂ} (hv : ∀ x, DifferentiableOn ℂ (v x) V')
    (hker : ∀ y ∈ V', ∀ x, c y * v x y = ∑ e, Ψ x e y * v (I₀ e) y) {b : Cm.{u} m}
    (hb : b ∈ V' \ R.zeroSet) :
    ∃ (B : Set (Cm.{u} m)) (hB : IsOpen B), B ⊆ V' \ R.zeroSet ∧ b ∈ B ∧
      ∃ t ∈ D.capPole h₀ n (tubeN N B hB) (B ×ˢ ball 0 F.ρ),
        ∀ b' ∈ B, ∀ x, D.evalVec w t.1.1 b' x = v x b' := by
  have hdense := D.subset_closure_goodSet R hwρ hloc hVo hVG hVc hr hb₀
  have hbV : b ∈ V \ R.zeroSet := ⟨hN'V (hV'N' hb.1), hb.2⟩
  obtain ⟨B₀, hB₀, hbB₀, hB₀S, -, K, s₀, hs₀, -, J, hint₀, hJ₀⟩ :=
    D.exists_chart R hwρ hloc hVo hVG hr hbV
      (D.forall_frequently_isGood R hwρ hloc hVo hVG hVc hr hb₀ b hbV)
  have hB₀G : B₀ ⊆ F.G := fun y hy ↦ hVG (hB₀S hy).1
  have hV'S : IsOpen (V' \ R.zeroSet) :=
    R.isOpen_diff_zeroSet hV' fun y hy ↦ hVG (hN'V (hV'N' hy))
  obtain ⟨ε, hε, hεB⟩ := Metric.isOpen_iff.1 (hB₀.inter hV'S) b ⟨hbB₀, hb⟩
  set B := ball b ε
  have hBB₀ : B ⊆ B₀ := fun y hy ↦ (hεB hy).1
  have hBV' : B ⊆ V' \ R.zeroSet := fun y hy ↦ (hεB hy).2
  have hBG : B ⊆ F.G := hBB₀.trans hB₀G
  have hle : tubeN N B isOpen_ball ≤ tubeN N B₀ hB₀ := tubeN_mono hBB₀
  set s := fun k ↦ D.capRestrict h₀ hle (s₀ k)
  have hs : ∀ k, s k ∈ D.capPole h₀ n (tubeN N B isOpen_ball) (B ×ˢ ball 0 F.ρ) := fun k ↦
    D.capRestrict_mem_capPole h₀ hle (prod_mono hBB₀ subset_rfl) (hs₀ k)
  set Λ : Cm.{u} m → Matrix (Fin r) (Fin r) ℂ := D.evalMat h₀ w I₀ (fun k ↦ (s₀ k).1.1) J
  set δ : Cm.{u} m → ℂ := fun y ↦ (Λ y).det
  have hδ : DifferentiableOn ℂ δ B := (D.differentiableOn_det_evalMat hwρ hB₀G _ J).mono hBB₀
  have hδ0 : interior (B ∩ δ ⁻¹' {0}) = ∅ :=
    subset_empty_iff.1 (hint₀ ▸ interior_mono fun y hy ↦ ⟨hBB₀ hy.1, hy.2⟩)
  have hΛ : ∀ i j, DifferentiableOn ℂ (fun y ↦ Λ y i j) B := fun i j ↦
    (D.differentiableOn_evalMat hwρ hB₀G _ J i j).mono hBB₀
  set a : Fin r → Cm.{u} m → ℂ := fun j y ↦ ∑ i, (Λ y).adjugate j i * v (I₀ i) y
  have ha : ∀ j, DifferentiableOn ℂ (a j) B := fun j ↦ DifferentiableOn.fun_sum fun i _ ↦
    (differentiableOn_adjugate hΛ j i).mul ((hv _).mono fun y hy ↦ (hBV' hy).1)
  have hevs : ∀ k x, DifferentiableOn ℂ (fun y ↦ D.evalVec w (s₀ k).1.1 y x) B := fun k x ↦
    (D.differentiableOn_evalVec F.isOpen_G hwρ (s₀ k).1.1 x).mono fun y hy ↦ ⟨hBG hy, by
      rw [F.mem_img_tubeN hB₀G, Homeomorph.apply_symm_apply]
      exact ⟨hBB₀ hy, mem_ball_zero_iff.2 (hwρ _).2⟩⟩
  -- Cramer's rule: `δ v = ∑ⱼ aⱼ λ(s_{J j})`
  have hkey : ∀ y ∈ B, ∀ x, δ y * v x y = ∑ j, a j y * D.evalVec w (s₀ (J j)).1.1 y x := by
    intro y hy x
    set O := B ∩ {y | δ y ≠ 0} ∩ {y | c y ≠ 0}
    have hc0B : interior (B ∩ c ⁻¹' {0}) = ∅ := subset_empty_iff.1 (hc0 ▸ interior_mono
      fun y hy ↦ ⟨hV'N' (hBV' hy.1).1, hy.2⟩)
    have hO : IsOpen O :=
      (hc.mono fun y hy ↦ hV'N' (hBV' hy.1).1).continuousOn.isOpen_inter_preimage
        (hδ.continuousOn.isOpen_inter_preimage isOpen_ball isOpen_ne) isOpen_ne
    have hBO : B ⊆ closure O := subset_closure_ne_zero isOpen_ball hδ.continuousOn hδ0 hc0B
    have hOd : O ⊆ closure (O ∩ D.goodSet h₀ n w I₀ R V) :=
      subset_closure_inter_of_subset_closure hO
        (fun y hy ↦ hN'V (hV'N' (hBV' hy.1.1).1)) hdense
    refine Set.EqOn.of_subset_closure (s := O ∩ D.goodSet h₀ n w I₀ R V) (t := B) ?_
      (hδ.continuousOn.mul ((hv x).mono fun y hy ↦ (hBV' hy).1).continuousOn)
      (continuousOn_finsetSum _ fun j _ ↦ (ha j).continuousOn.mul (hevs _ x).continuousOn)
      (fun y hy ↦ hy.1.1.1) (hBO.trans (closure_minimal hOd isClosed_closure)) hy
    intro y ⟨⟨⟨hyB, hδy⟩, hcy⟩, hyg⟩
    have hδy' : δ y ≠ 0 := hδy
    have hcy' : c y ≠ 0 := hcy
    have hcol : ∀ j, D.evalVec w (s₀ (J j)).1.1 y x = ∑ e, Λ y e j * (Ψ x e y / c y) := by
      intro j
      have hsum := Submodule.eq_sum_graphVec hyg.2.1
        (evalVec_mem_fibImage hB₀G (hBB₀ hyB) (hs₀ (J j)) (w := w))
      have := congrFun hsum x
      simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul] at this
      rw [this]
      refine Finset.sum_congr rfl fun e _ ↦ ?_
      have hΦe := hΦ y (hV'N' (hBV' hyB).1) hyg hcy' x e
      rw [graphFun, dif_pos hyg.2.1] at hΦe
      rw [hΦe]
      rfl
    have hΛa : ∀ e, ∑ j, Λ y e j * a j y = δ y * v (I₀ e) y := by
      intro e
      have := congrFun (congrFun (Matrix.mul_adjugate (Λ y)) e)
      simp only [a, Finset.mul_sum]
      rw [Finset.sum_comm]
      simp_rw [← mul_assoc]
      rw [show δ y * v (I₀ e) y = ∑ i, (Λ y * (Λ y).adjugate) e i * v (I₀ i) y by
        simp [Matrix.mul_adjugate, Matrix.smul_apply, Matrix.one_apply, δ]]
      refine Finset.sum_congr rfl fun i _ ↦ ?_
      rw [Matrix.mul_apply, Finset.sum_mul]
    change δ y * v x y = ∑ j, a j y * D.evalVec w (s₀ (J j)).1.1 y x
    simp_rw [hcol, Finset.mul_sum]
    rw [Finset.sum_comm]
    have : ∀ e, ∑ j, a j y * (Λ y e j * (Ψ x e y / c y)) =
        (Ψ x e y / c y) * (δ y * v (I₀ e) y) := fun e ↦ by
      rw [← hΛa e, Finset.mul_sum]
      exact Finset.sum_congr rfl fun j _ ↦ by ring
    simp_rw [this]
    have hk := hker y (hBV' hyB).1 x
    calc δ y * v x y = δ y / c y * (c y * v x y) := by field_simp
      _ = δ y / c y * ∑ e, Ψ x e y * v (I₀ e) y := by rw [hk]
      _ = ∑ e, Ψ x e y / c y * (δ y * v (I₀ e) y) := by
        rw [Finset.mul_sum]
        exact Finset.sum_congr rfl fun e _ ↦ by ring
  -- the combination `∑ⱼ aⱼ s_{J j}` and saturation
  obtain ⟨t₁, ht₁, ht₁v, -⟩ := D.exists_capPole_sum h₀ hBG (s := fun j ↦ s (J j))
    (fun j ↦ hs (J j)) ha
  have ht₁ev : ∀ y ∈ B, ∀ x, D.evalVec w t₁.1.1 y x = δ y * v x y := fun y hy x ↦ by
    rw [D.evalVec_eq_sum_of_evalFun h₀ hBG hwρ ht₁v hy x, hkey y hy x]
    refine Finset.sum_congr rfl fun j _ ↦ ?_
    rw [D.evalVec_capRestrict h₀ hwρ hBG hBB₀ _ hy]
  obtain ⟨t', ht', ht'v⟩ := D.exists_capPole_evalVec_eq_of_mul h₀ hBG (convex_ball b ε) ht₁ hδ
    hδ0 hM hw hwρ (fun x ↦ (hv x).mono fun y hy ↦ (hBV' hy).1) ht₁ev
  exact ⟨B, isOpen_ball, hBV', mem_ball_self hε, t', ht', ht'v⟩

include hwρ hw hM hloc hVo hVG hVc hr hb₀ hN'V hc hc0 hΦ in
/-- **Solutions of the equations of the graph are evaluations of sections of the cap**: local
evaluations off `Z` glue, and the glued section extends across `Z` by Hartogs. -/
theorem exists_capPole_of_kerCond {V' : Set (Cm.{u} m)} (hV' : IsOpen V') (hV'N' : V' ⊆ N')
    {v : D.EvIdx M → Cm.{u} m → ℂ} (hv : ∀ x, DifferentiableOn ℂ (v x) V')
    (hker : ∀ y ∈ V', ∀ x, c y * v x y = ∑ e, Ψ x e y * v (I₀ e) y) :
    ∃ t ∈ D.capPole h₀ n (tubeN N V' hV') (V' ×ˢ ball 0 F.ρ),
      ∀ y ∈ V', ∀ x, D.evalVec w t.1.1 y x = v x y := by
  have hV'G : V' ⊆ F.G := fun y hy ↦ hVG (hN'V (hV'N' hy))
  have hV'S : IsOpen (V' \ R.zeroSet) := R.isOpen_diff_zeroSet hV' hV'G
  have hSG : V' \ R.zeroSet ⊆ F.G := fun y hy ↦ hV'G hy.1
  obtain ⟨t₃, ht₃, ht₃v⟩ := D.exists_capPole_of_locally h₀ (hU := hV'S) hSG hM hw hwρ
    fun b hb ↦ by
      obtain ⟨B, hB, hBS, hbB, t, ht, htv⟩ := exists_local_capPole_of_kerCond hwρ hw hM hloc hVo
        hVG hVc hr hb₀ hN'V hc hc0 hΦ hV' hV'N' hv hker hb
      exact ⟨B, hB, hBS, hbB, t, ht, htv⟩
  obtain ⟨t, ht, htf, -⟩ := D.exists_capPole_extend h₀ (hU := hV') hV'G R hV'S ht₃
  refine ⟨t, ht, ?_⟩
  have hev : ∀ x, DifferentiableOn ℂ (fun y ↦ D.evalVec w t.1.1 y x) V' := fun x ↦
    (D.differentiableOn_evalVec F.isOpen_G hwρ t.1.1 x).mono fun y hy ↦ ⟨hV'G hy, by
      rw [F.mem_img_tubeN hV'G, Homeomorph.apply_symm_apply]
      exact ⟨hy, mem_ball_zero_iff.2 (hwρ _).2⟩⟩
  intro y hy x
  refine Set.EqOn.of_subset_closure (s := V' \ R.zeroSet) (t := V') (fun y hy ↦ ?_)
    (hev x).continuousOn (hv x).continuousOn sdiff_subset
    (subset_closure_sdiff_zeroSet R hV' hV'G) hy
  obtain ⟨p, hp, hpy, hval⟩ := D.exists_evalVec_eq_tube h₀ hwρ hSG hy x (hV := hV'S)
  rw [← ht₃v y hy x, hval, ← htf p hp,
    ← D.evalVec_capRestrict h₀ hwρ hSG sdiff_subset t hy (hV := hV') (hV' := hV'S), hval]
  simp only [capRestrict]
  rw [evalFun_map W _ _ hp]

end Solutions

/-- An element of `OkaRing U` whose values vanish is zero. -/
lemma okaRing_eq_zero {U : TopologicalSpace.Opens (Cm.{u} m)} (f : OkaRing U)
    (h : ∀ y (hy : y ∈ U), OkaRing.evalHom hy f = 0) : f = 0 :=
  OkaRing.ext (funext fun y ↦ h y.1 y.2)

/-- The equations of the graph as relations:
`∑_{x'} a_{x'} ([x' = x] c - ∑ₑ [x' = I₀ e] Ψₓₑ) = c aₓ - ∑ₑ Ψₓₑ a_{I₀ e}`. -/
lemma sum_kerCoeff {X : Type*} [Finite X] [DecidableEq X] {q : ℕ} (eX : X ≃ Fin q)
    (I₀ : Fin r → X) (a : X → ℂ) (c : ℂ) (Ψ : X → Fin r → ℂ) (x : X) :
    ∑ i, a (eX.symm i) * ((if eX.symm i = x then 1 else 0) * c -
      ∑ e, (if eX.symm i = I₀ e then 1 else 0) * Ψ x e) = c * a x - ∑ e, Ψ x e * a (I₀ e) := by
  have := Fintype.ofFinite X
  rw [Equiv.sum_comp eX.symm (fun x' ↦ a x' * ((if x' = x then 1 else 0) * c -
    ∑ e, (if x' = I₀ e then 1 else 0) * Ψ x e))]
  simp only [mul_sub, Finset.sum_sub_distrib, Finset.mul_sum]
  congr 1
  · simp [Finset.sum_ite_eq', mul_comm]
  · rw [Finset.sum_comm]
    refine Finset.sum_congr rfl fun e _ ↦ ?_
    simp [Finset.sum_ite_eq', mul_comm]

/-- **The sections of the cap are locally finitely generated at every point of `G`** if they are
at the points off the zero set of the regular pairs. -/
theorem capLocallyFinite_of_forall_not_mem
    (hloc : ∀ b ∈ F.G, b ∉ R.zeroSet → D.CapLocallyFinite h₀ n b) {z : Cm.{u} m}
    (hz : z ∈ F.G) : D.CapLocallyFinite h₀ n z := by
  classical
  obtain ⟨w, hw, hwρ⟩ := exists_nodes F.one_lt_ρ ((∑ i, (D.deg i : ℕ)) * n + 1)
  have hM : (∑ i, (D.deg i : ℕ)) * n < (∑ i, (D.deg i : ℕ)) * n + 1 := Nat.lt_succ_self _
  obtain ⟨ε, hε, hεG⟩ := Metric.isOpen_iff.1 F.isOpen_G z hz
  set V := ball z ε
  have hVo : IsOpen V := isOpen_ball
  have hVc : IsPreconnected V := (convex_ball z ε).isPreconnected
  -- the maximal dimension of the fibres off `Z`
  set S := V \ R.zeroSet
  set T : Set ℕ := (fun y ↦ finrank ℂ (D.fibImage h₀ n w y)) '' S
  obtain ⟨b₁, hb₁V, hb₁Z⟩ := exists_mem_sdiff_zeroSet R hVo hεG (mem_ball_self hε)
  have hTne : T.Nonempty := ⟨_, b₁, ⟨hb₁V, hb₁Z⟩, rfl⟩
  have hTbdd : BddAbove T := ⟨Fintype.card (D.EvIdx ((∑ i, (D.deg i : ℕ)) * n + 1)), by
    rintro _ ⟨y, -, rfl⟩
    exact (Submodule.finrank_le _).trans_eq (Module.finrank_fintype_fun_eq_card ℂ)⟩
  obtain ⟨bstar, hbstar, hbstarT⟩ := Nat.sSup_mem hTne hTbdd
  have hr : ∀ y ∈ S, finrank ℂ (D.fibImage h₀ n w y) ≤ finrank ℂ (D.fibImage h₀ n w bstar) :=
    fun y hy ↦ (le_csSup hTbdd ⟨y, hy, rfl⟩).trans_eq hbstarT.symm
  obtain ⟨I₀, hI₀⟩ := Submodule.exists_bijective_coordProj (D.fibImage h₀ n w bstar)
  have hb₀ : ∃ b ∈ S, D.IsGood h₀ n w I₀ b := ⟨bstar, hbstar, hI₀⟩
  -- the graph near `z`
  obtain ⟨N', hN'o, hzN', hN'V, c, Ψ, hc, hΨ, hc0, hΦ⟩ :=
    D.exists_graph_rep R hwρ hloc hVo hεG hVc hr hb₀ (mem_ball_self hε)
  have hdense := D.subset_closure_goodSet R hwρ hloc hVo hεG hVc hr hb₀
  -- the equations of the graph as relations, and Oka's theorem
  set X := D.EvIdx ((∑ i, (D.deg i : ℕ)) * n + 1)
  set eX := Fintype.equivFin X
  set U₀ : TopologicalSpace.Opens (Cm.{u} m) := ⟨N', hN'o⟩
  have hcoef : ∀ i j, DifferentiableOn ℂ (fun y ↦
      (if eX.symm i = eX.symm j then 1 else 0) * c y -
        ∑ e, (if eX.symm i = I₀ e then 1 else 0) * Ψ (eX.symm j) e y) U₀ := fun i j ↦
    ((differentiableOn_const _).mul hc).sub
      (DifferentiableOn.fun_sum fun e _ ↦ (differentiableOn_const _).mul (hΨ _ e))
  set col : Fin (Fintype.card X) → Fin (Fintype.card X) → OkaRing U₀ := fun i j ↦
    OkaRing.ofDifferentiableOn _ (hcoef i j)
  obtain ⟨V₀, hV₀U₀, k, g, hzV₀, hrel, hgen⟩ := oka' U₀ col z hzN'
  have hV₀N' : (V₀ : Set (Cm.{u} m)) ⊆ N' := hV₀U₀
  -- the generators of the relations are evaluations of sections of the cap
  have hgl : ∀ l, ∃ t ∈ D.capPole h₀ n (tubeN N V₀ V₀.isOpen) (V₀ ×ˢ ball 0 F.ρ),
      ∀ y ∈ V₀, ∀ x, D.evalVec w t.1.1 y x = (g l (eX x)).toGlobalFun _ y := by
    intro l
    refine exists_capPole_of_kerCond hwρ hw hM hloc hVo hεG hVc hr hb₀ hN'V hc hc0 hΦ
      V₀.isOpen hV₀N' (fun x ↦ (g l (eX x)).differentiableOn_toGlobalFun) fun y hy x ↦ ?_
    have := congrArg (OkaRing.evalHom hy) (hrel l (eX x))
    simp only [map_sum, map_mul, map_zero, OkaRing.evalHom_restrict] at this
    have key : c y * (g l (eX (eX.symm (eX x)))).toGlobalFun _ y =
        ∑ e, Ψ (eX.symm (eX x)) e y * (g l (eX (I₀ e))).toGlobalFun _ y := by
      rw [← sub_eq_zero, ← sum_kerCoeff eX I₀ (fun x' ↦ (g l (eX x')).toGlobalFun _ y) (c y)
        (fun x e ↦ Ψ x e y) (eX.symm (eX x))]
      refine (Finset.sum_congr rfl fun i _ ↦ ?_).trans this
      rw [Equiv.apply_symm_apply, OkaRing.toGlobalFun_apply _ hy]
      rfl
    simpa only [Equiv.symm_apply_apply] using key
  choose t ht htv using hgl
  refine ⟨V₀, V₀.isOpen, fun y hy ↦ hεG (hN'V (hV₀N' hy)), hzV₀, k, t, ht,
    fun b' hb' V hV hVV₀ hb'V t' ht' ↦ ?_⟩
  have hVG : V ⊆ F.G := fun y hy ↦ hεG (hN'V (hV₀N' (hVV₀ hy)))
  have hker := kerCond_evalVec hN'V hc hΨ hc0 hΦ hdense hwρ (fun y hy ↦ hV₀N' (hVV₀ hy)) hVG ht'
  have hev : ∀ x, DifferentiableOn ℂ (fun y ↦ D.evalVec w t'.1.1 y x) V := fun x ↦
    (D.differentiableOn_evalVec F.isOpen_G hwρ t'.1.1 x).mono fun y hy ↦ ⟨hVG hy, by
      rw [F.mem_img_tubeN hVG, Homeomorph.apply_symm_apply]
      exact ⟨hy, mem_ball_zero_iff.2 (hwρ _).2⟩⟩
  set UV : TopologicalSpace.Opens (Cm.{u} m) := ⟨V, hV⟩
  have hUV : UV ≤ V₀ := hVV₀
  set a : Fin (Fintype.card X) → OkaRing UV := fun i ↦
    OkaRing.ofDifferentiableOn _ (hev (eX.symm i))
  have hrel' : ∀ j, ∑ i, a i * OkaRing.restrict (hUV.trans hV₀U₀) (col i j) = 0 := by
    intro j
    refine okaRing_eq_zero _ fun y hy ↦ ?_
    simp only [map_sum, map_mul, OkaRing.evalHom_restrict]
    have h2 := sum_kerCoeff eX I₀ (fun x' ↦ D.evalVec w t'.1.1 y x') (c y)
      (fun x e ↦ Ψ x e y) (eX.symm j)
    rw [hker y hy (eX.symm j), sub_self] at h2
    rw [← h2]
    rfl
  obtain ⟨W'', hW''V, hb'W'', c', hc'⟩ := hgen UV hUV a hrel' b' hb'V
  have hW''V' : (W'' : Set (Cm.{u} m)) ⊆ V := hW''V
  refine ⟨W'', hW''V', W''.isOpen, hb'W'', fun l ↦ (c' l).toGlobalFun _,
    fun l ↦ (c' l).differentiableOn_toGlobalFun, ?_⟩
  refine D.evalFun_eq_sum_of_evalVec h₀ W''.isOpen hVG hW''V' hVV₀ ht' ht hM hw hwρ
    (fun l ↦ (c' l).differentiableOn_toGlobalFun) fun y hy x ↦ ?_
  have h1 : D.evalVec w t'.1.1 y x = OkaRing.evalHom hy (OkaRing.restrict hW''V (a (eX x))) := by
    simp [a]
  rw [h1, hc' (eX x), map_sum]
  refine Finset.sum_congr rfl fun l _ ↦ ?_
  rw [map_mul, OkaRing.evalHom_restrict, htv l y (hUV (hW''V hy)) x,
    OkaRing.toGlobalFun_apply _ hy, OkaRing.toGlobalFun_apply _ (hUV (hW''V hy))]
  rfl

end

end ComplexAnalytic.Cap.AnnulusDecomposition
