/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.Analytification.GAGA.CartanTheoremA

/-!
# Cartan's Theorem B for closed boxes

Let `f : Y ⟶ ℂ^ι` be an open immersion, where `𝒪_Y` has locally finitely generated relations,
and let `M` be a coherent sheaf of `𝒪_Y`-modules whose stalks have projective dimension `≤ d`
(on an open subset of `ℂⁿ` this holds for `d = n`). By Theorem A in the form
`ComplexAnalytic.exists_hasFreeResolutionLE_closedBox`, `M` has a finite free resolution on an
open neighbourhood `W` of a closed box `K`. Since the structure sheaf is acyclic on open boxes
(`Complex.TheoremB.subsingleton_H_restrictOpen_structureSheafAb_openBox`), dimension shifting
along the resolution gives **Theorem B**: `Hᵠ(V, M) = 0` for `q ≥ 1` and every open `V ≤ W` whose
image is an open box; such `V` form a neighbourhood basis of `K`. Moreover, on such `V`, the
sections of `M` are generated by finitely many sections over `W`, with relations generated by a
fixed finite matrix.

## Main results

- `ComplexAnalytic.exists_presentation_closedBox`: a presentation of `M` near `K` which is exact
  on sections over open boxes, and acyclicity of `M` on open boxes.
- `ComplexAnalytic.exists_subsingleton_H_closedBox`: **Cartan's Theorem B** for closed boxes.
- `ComplexAnalytic.exists_subsingleton_H_closedBox_complexAffineSpace`: the version for coherent
  sheaves on an open subset of `ℂⁿ`.
-/

universe u

open CategoryTheory TopologicalSpace Opposite AlgebraicGeometry Limits Set
open AlgebraicGeometry.LocallyRingedSpace

namespace ComplexAnalytic

variable {ι : Type u} [Fintype ι] {Y : LocallyRingedSpace.{u}} (f : Y ⟶ complexSpace ι)
  [LocallyRingedSpace.IsOpenImmersion f]

/-- Every open box inside `f(W)` is the image of an open `V ≤ W`. -/
lemma exists_image_eq_openBox {W : Opens Y.toPresheafedSpace} {a b : ι → ℂ}
    (h : Complex.openBox a b ⊆ imageOpens f W) :
    ∃ V : Opens Y.toPresheafedSpace, V ≤ W ∧
      (imageOpens f V : Set (ι → ℂ)) = Complex.openBox a b := by
  refine ⟨W ⊓ (Opens.map f.base).obj ⟨_, isOpen_openBox a b⟩, inf_le_left, ?_⟩
  ext x
  refine ⟨?_, fun hx ↦ ?_⟩
  · rintro ⟨y, hy, rfl⟩
    exact hy.2
  · obtain ⟨y, hy, rfl⟩ := h hx
    exact ⟨y, ⟨hy, hx⟩, rfl⟩

/-- **Presentations near closed boxes.** Under the hypotheses of
`ComplexAnalytic.exists_hasFreeResolutionLE_closedBox`, there are an open `W` with `K ⊆ f(W)`,
finitely many sections `g` of `M` over `W` and a finite matrix `A` of relations between them,
such that on every open `V ≤ W` whose image is an open box, `M` is acyclic, the `g|_V` generate
the sections of `M` over `V`, and their relations are generated by the rows of `A`. -/
theorem exists_presentation_closedBox (hY : Y.HasLocalRelations)
    (M : SheafOfModules.{u} Y.ringSheaf) [M.IsCoherent] {d : ℕ}
    (hpd : ∀ y, HasProjectiveDimensionLE ((Y.stalkFunctor y).obj M) d) {a b : ι → ℂ}
    (hK : Complex.closedBox a b ⊆ range f.base) (hne : (Complex.closedBox a b).Nonempty) :
    ∃ (W : Opens Y.toPresheafedSpace) (_ : Complex.closedBox a b ⊆ imageOpens f W)
      (I I' : Type u) (_ : Fintype I) (_ : Fintype I') (g : I → M.val.obj (op W))
      (A : I' → I → Y.ringSheaf.obj.obj (op W)), (∀ j, ∑ i, A j i • g i = 0) ∧
      ∀ (V : Opens Y.toPresheafedSpace) (hV : V ≤ W),
        (∃ a' b' : ι → ℂ, (imageOpens f V : Set (ι → ℂ)) = Complex.openBox a' b') →
        (∀ q, 0 < q → Subsingleton (TopCat.Sheaf.H
          ((TopCat.Sheaf.restrictOpen V).obj M.toAb) q)) ∧
        (∀ s : M.val.obj (op V), ∃ c : I → Y.ringSheaf.obj.obj (op V),
          s = ∑ i, c i • M.val.map (homOfLE hV).op (g i)) ∧
        (∀ c : I → Y.ringSheaf.obj.obj (op V),
          ∑ i, c i • M.val.map (homOfLE hV).op (g i) = 0 →
          ∃ e : I' → Y.ringSheaf.obj.obj (op V),
            ∀ i, c i = ∑ j, e j * Y.ringSheaf.obj.map (homOfLE hV).op (A j i)) := by
  obtain ⟨W, hKW, hW⟩ := exists_hasFreeResolutionLE_closedBox f hY M hpd hK hne
  obtain ⟨I, I', _, _, g, A, hA, H⟩ := exists_generators_acyclic W M hW
  exact ⟨W, hKW, I, I', inferInstance, inferInstance, g, A, hA, fun V hV ⟨a', b', hab⟩ ↦
    H V hV (subsingleton_H_structureSheafAb_of_openBox f hab)⟩

/-- **Cartan's Theorem B for closed boxes.** Under the hypotheses of
`ComplexAnalytic.exists_hasFreeResolutionLE_closedBox`, there is an open `W` with `K ⊆ f(W)` such
that `Hᵠ(V, M) = 0` for `q ≥ 1` and every open `V ≤ W` whose image is an open box. Every open box
`B` with `K ⊆ B ⊆ f(W)` is such an image, and such boxes exist. -/
theorem exists_subsingleton_H_closedBox (hY : Y.HasLocalRelations)
    (M : SheafOfModules.{u} Y.ringSheaf) [M.IsCoherent] {d : ℕ}
    (hpd : ∀ y, HasProjectiveDimensionLE ((Y.stalkFunctor y).obj M) d) {a b : ι → ℂ}
    (hK : Complex.closedBox a b ⊆ range f.base) (hne : (Complex.closedBox a b).Nonempty) :
    ∃ W : Opens Y.toPresheafedSpace, Complex.closedBox a b ⊆ imageOpens f W ∧
      (∃ a' b' : ι → ℂ, Complex.closedBox a b ⊆ Complex.openBox a' b' ∧
        Complex.openBox a' b' ⊆ imageOpens f W) ∧
      ∀ (V : Opens Y.toPresheafedSpace), V ≤ W →
        (∃ a' b' : ι → ℂ, (imageOpens f V : Set (ι → ℂ)) = Complex.openBox a' b') →
        ∀ q, 0 < q →
          Subsingleton (TopCat.Sheaf.H ((TopCat.Sheaf.restrictOpen V).obj M.toAb) q) := by
  obtain ⟨W, hKW, I, I', _, _, g, A, -, H⟩ := exists_presentation_closedBox f hY M hpd hK hne
  exact ⟨W, hKW, exists_openBox_between (imageOpens f W).isOpen hKW,
    fun V hV hbox ↦ (H V hV hbox).1⟩

section AffineSpace

variable {n : ℕ} (U : Opens (complexAffineSpace.{u} n))

/-- **Cartan's Theorem B for closed boxes in `ℂⁿ`.** Let `M` be a coherent sheaf of modules on an
open `U ⊆ ℂⁿ` and `K ⊆ U` a nonempty closed box. There is an open neighbourhood `W` of `K` in `U`
such that `Hᵠ(V, M) = 0` for `q ≥ 1` and every open `V ≤ W` which is an open box in `ℂⁿ`. -/
theorem exists_subsingleton_H_closedBox_complexAffineSpace
    (M : SheafOfModules.{u} ((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).ringSheaf)
    [M.IsCoherent] {a b : ULift.{u} (Fin n) → ℂ} (hK : ∀ x ∈ Complex.closedBox a b, x ∈ U)
    (hne : (Complex.closedBox a b).Nonempty) :
    ∃ W : Opens ((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).toPresheafedSpace,
      Complex.closedBox a b ⊆
        imageOpens ((complexAffineSpace.{u} n).ofRestrict U.isOpenEmbedding) W ∧
      (∃ a' b' : ULift.{u} (Fin n) → ℂ, Complex.closedBox a b ⊆ Complex.openBox a' b' ∧
        Complex.openBox a' b' ⊆
          imageOpens ((complexAffineSpace.{u} n).ofRestrict U.isOpenEmbedding) W) ∧
      ∀ (V : Opens ((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).toPresheafedSpace),
        V ≤ W → (∃ a' b' : ULift.{u} (Fin n) → ℂ,
          (imageOpens ((complexAffineSpace.{u} n).ofRestrict U.isOpenEmbedding) V :
            Set (ULift.{u} (Fin n) → ℂ)) = Complex.openBox a' b') →
        ∀ q, 0 < q → Subsingleton (TopCat.Sheaf.H ((TopCat.Sheaf.restrictOpen V).obj M.toAb) q) :=
  exists_subsingleton_H_closedBox ((complexAffineSpace.{u} n).ofRestrict U.isOpenEmbedding)
    ((hasLocalRelations_complexSpace _).restrict U) M
    (hasProjectiveDimensionLE_stalk_restrict_complexAffineSpace U M)
    (fun x hx ↦ ⟨⟨x, hK x hx⟩, rfl⟩) hne

end AffineSpace

end ComplexAnalytic
