/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.AnalyticSpace.LocalFreeResolution
import Oka.Analytification.GAGA.CartanBoxInduction
import Oka.Analytification.GAGA.CartanGluing
import Oka.Analytification.GAGA.CartanSectionSplit
import Oka.Analytification.GAGA.TheoremBBox
import Oka.Geometry.RingedSpace.LocallyRingedSpace.LocalFreeResolution
import Oka.Geometry.RingedSpace.LocallyRingedSpace.OpenImmersionCohomology

/-!
# Cartan's Theorem A for closed boxes

Let `f : Y ⟶ ℂ^ι` be an open immersion of locally ringed spaces and `M` a coherent sheaf of
`𝒪_Y`-modules whose stalks have projective dimension `≤ d` (e.g. `d = n` on an open subset of
`ℂⁿ`, by the syzygy theorem). Then every closed box `K ⊆ f(Y)` has an open neighbourhood `W` on
which `M` has a finite free resolution `0 → 𝒪^{p_d} → ⋯ → 𝒪^{p₀} → M|_W → 0`
(`ComplexAnalytic.exists_hasFreeResolutionLE_closedBox`). In particular `M` is generated near `K`
by finitely many sections (**Theorem A**), and it is acyclic on every open box near `K`
(**Theorem B**, `ComplexAnalytic.exists_subsingleton_H_closedBox`).

The proof is by induction on `d` and, for fixed `d`, by subdividing `K` into small boxes
(`Complex.closedBox_induction`). Two adjacent boxes `K₁`, `K₂` are merged as follows. Near `Kᵢ`,
`M` is generated by sections `s` and `t`; near `K₁ ∩ K₂` each system is a combination of the other
one (Theorem B for the small boxes), `t = A s` and `s = B t`. The systems `(s, 0)` and `(0, t)` are
then related by the invertible matrix `G = [[1, B], [-A, 1 - AB]]`, which is split by Cartan's
matrix lemma, `G = H₁ H₂`; the sections `H₁⁻¹ (s, 0)` near `K₁` and `H₂ (0, t)` near `K₂` glue to
generators of `M` near `K₁ ∪ K₂`. The kernel of the corresponding epimorphism `𝒪^p ⟶ M` has
stalks of projective dimension `≤ d - 1` and is treated by induction. For `d = 0` the sheaf is
locally free and the bases `s`, `t` are related directly by an invertible matrix.

## Main results

- `ComplexAnalytic.exists_glued_sections`: gluing families of sections along Cartan's lemma.
- `ComplexAnalytic.exists_hasFreeResolutionLE_closedBox`: finite free resolutions near closed
  boxes.
- `ComplexAnalytic.exists_epi_free_closedBox`: **Cartan's Theorem A** for closed boxes.
-/

universe u

open CategoryTheory TopologicalSpace Opposite AlgebraicGeometry Limits Set
open AlgebraicGeometry.LocallyRingedSpace

namespace ComplexAnalytic

variable {ι : Type u} [Fintype ι] {Y : LocallyRingedSpace.{u}} {f : Y ⟶ complexSpace ι}
  [LocallyRingedSpace.IsOpenImmersion f] {M : SheafOfModules.{u} Y.ringSheaf}

section Glue

variable {κ : Type*} [Fintype κ] [DecidableEq κ]

/-- **Gluing families of sections along Cartan's lemma.** Let `K₁`, `K₂` be compact with Cartan's
splitting property, `Kᵢ ⊆ f(Wᵢ)`, and let `u₁`, `u₂` be families of sections of `M` over `W₁`,
`W₂` related by an invertible matrix `G` of sections over `Ω₀` with `K₁ ∩ K₂ ⊆ f(Ω₀)`:
`u₁ = G u₂` on `Ω₀`. Then there are opens `Ωᵢ ≤ Wᵢ` with `Kᵢ ⊆ f(Ωᵢ)` and a family `w` of
sections over `Ω₁ ⊔ Ω₂` with `w = Hᵢ uᵢ` on `Ωᵢ` for invertible matrices `Hᵢ`. -/
theorem exists_glued_sections {K₁ K₂ : Set (ι → ℂ)} (hK₁ : IsCompact K₁) (hK₂ : IsCompact K₂)
    (hsplit : Complex.MatrixSplit κ K₁ K₂) {W₁ W₂ Ω₀ : Opens Y.toPresheafedSpace}
    (hK₁W : K₁ ⊆ imageOpens f W₁) (hK₂W : K₂ ⊆ imageOpens f W₂) (h₀₁ : Ω₀ ≤ W₁) (h₀₂ : Ω₀ ≤ W₂)
    (hK : K₁ ∩ K₂ ⊆ imageOpens f Ω₀) (u₁ : κ → M.val.obj (op W₁)) (u₂ : κ → M.val.obj (op W₂))
    (G G' : Matrix κ κ (Y.presheaf.obj (op Ω₀))) (hG : G * G' = 1)
    (hu : (fun k ↦ modRes (u₁ k) Ω₀ h₀₁) = matAct G fun l ↦ modRes (u₂ l) Ω₀ h₀₂) :
    ∃ (Ω₁ Ω₂ : Opens Y.toPresheafedSpace) (h₁ : Ω₁ ≤ W₁) (h₂ : Ω₂ ≤ W₂),
      K₁ ⊆ imageOpens f Ω₁ ∧ K₂ ⊆ imageOpens f Ω₂ ∧ ∃ w : κ → M.val.obj (op (Ω₁ ⊔ Ω₂)),
        (∃ H H' : Matrix κ κ (Y.presheaf.obj (op Ω₁)), H * H' = 1 ∧
          (fun k ↦ modRes (w k) Ω₁ le_sup_left) = matAct H fun l ↦ modRes (u₁ l) Ω₁ h₁) ∧
        (∃ H H' : Matrix κ κ (Y.presheaf.obj (op Ω₂)), H * H' = 1 ∧
          (fun k ↦ modRes (w k) Ω₂ le_sup_right) = matAct H fun l ↦ modRes (u₂ l) Ω₂ h₂) := by
  obtain ⟨Ω₁, Ω₂, h₁, h₂, h₀, hK₁Ω, hK₂Ω, H₁, H₁', hH₁, H₂, H₂', hH₂, hGH⟩ :=
    exists_matrix_split_sections (f := f) hK₁ hK₂ hsplit hK₁W hK₂W hK G G' hG
  have hH₁' : H₁' * H₁ = 1 := mul_eq_one_comm.1 hH₁
  set w₁ : κ → M.val.obj (op Ω₁) := matAct H₁' fun l ↦ modRes (u₁ l) Ω₁ h₁
  set w₂ : κ → M.val.obj (op Ω₂) := matAct H₂ fun l ↦ modRes (u₂ l) Ω₂ h₂
  set ρ₁ := (Y.presheaf.map (homOfLE (inf_le_left : Ω₁ ⊓ Ω₂ ≤ Ω₁)).op).hom
  set ρ₂ := (Y.presheaf.map (homOfLE (inf_le_right : Ω₁ ⊓ Ω₂ ≤ Ω₂)).op).hom
  have e₁ : (fun k ↦ modRes (u₁ k) (Ω₁ ⊓ Ω₂) (inf_le_left.trans h₁)) =
      matAct (G.map (Y.presheaf.map (homOfLE h₀).op).hom)
        (fun l ↦ modRes (u₂ l) (Ω₁ ⊓ Ω₂) (inf_le_right.trans h₂)) := by
    funext k
    have := congrArg (fun σ ↦ modRes σ (Ω₁ ⊓ Ω₂) h₀) (congrFun hu k)
    simp only [modRes_res, modRes_matAct] at this
    exact this
  have hglue : ∀ k, modRes (w₁ k) (Ω₁ ⊓ Ω₂) inf_le_left =
      modRes (w₂ k) (Ω₁ ⊓ Ω₂) inf_le_right := by
    intro k
    simp only [w₁, w₂, modRes_matAct, modRes_res]
    rw [e₁, hGH, matAct_mul, ← matAct_mul, ← Matrix.map_mul, hH₁',
      Matrix.map_one _ (map_zero _) (map_one _), matAct_one]
  choose w hw₁ hw₂ using fun k ↦ exists_glue (w₁ k) (w₂ k) (hglue k)
  exact ⟨Ω₁, Ω₂, h₁, h₂, hK₁Ω, hK₂Ω, w, ⟨H₁', H₁, hH₁', funext hw₁⟩,
    ⟨H₂, H₂', hH₂, funext hw₂⟩⟩

end Glue

section Boxes

omit [Fintype ι] in
/-- A closed box inside an open set lies in an open box inside that open set. -/
lemma exists_openBox_between [Finite ι] {a b : ι → ℂ} {U : Set (ι → ℂ)} (hU : IsOpen U)
    (hK : Complex.closedBox a b ⊆ U) :
    ∃ a' b' : ι → ℂ, Complex.closedBox a b ⊆ Complex.openBox a' b' ∧
      Complex.openBox a' b' ⊆ U := by
  cases nonempty_fintype ι
  by_cases hord : ∀ j, (a j).re ≤ (b j).re ∧ (a j).im ≤ (b j).im
  swap
  · refine ⟨0, 0, by rw [Complex.closedBox_eq_empty_of_not_le hord]; exact empty_subset _,
      fun x hx ↦ ?_⟩
    cases isEmpty_or_nonempty ι with
    | inl _ => exact absurd (fun j ↦ isEmptyElim j) hord
    | inr h =>
      obtain ⟨j⟩ := h
      have := (hx j (mem_univ _)).1
      simp only [Pi.zero_apply, Complex.zero_re] at this
      linarith [this.1, this.2]
  obtain ⟨δ, hδ, hδU⟩ := (Complex.isCompact_closedBox a b).exists_thickening_subset_open hU hK
  refine ⟨fun j ↦ a j - ⟨δ / 4, δ / 4⟩, fun j ↦ b j + ⟨δ / 4, δ / 4⟩, fun x hx j _ ↦ ?_,
    fun x hx ↦ hδU ?_⟩
  · obtain ⟨⟨h1, h2⟩, h3, h4⟩ := hx j (mem_univ _)
    simp only [Complex.mem_reProdIm, mem_Ioo, Complex.sub_re, Complex.add_re, Complex.sub_im,
      Complex.add_im]
    refine ⟨⟨?_, ?_⟩, ?_, ?_⟩ <;> linarith
  · have hxj : ∀ j, x j ∈ Complex.closedRectNhd (a j) (b j) (δ / 4) := fun j ↦ by
      obtain ⟨⟨h1, h2⟩, h3, h4⟩ := hx j (mem_univ _)
      simp only [Complex.sub_re, Complex.add_re, Complex.sub_im, Complex.add_im] at h1 h2 h3 h4
      exact ⟨⟨h1.le, h2.le⟩, h3.le, h4.le⟩
    refine Metric.mem_thickening_iff.2 ?_
    choose y hy hdist using fun j ↦ Metric.mem_thickening_iff.1
      (Complex.closedRectNhd_subset_thickening (s := δ / 4) (δ := δ) (hord j).1 (hord j).2
        (by positivity) (by linarith) (hxj j))
    refine ⟨y, fun j _ ↦ ?_, (dist_pi_lt_iff hδ).2 hdist⟩
    simpa [Complex.closedRectNhd] using hy j

omit [Fintype ι] in
lemma isOpen_openBox [Finite ι] (a b : ι → ℂ) : IsOpen (Complex.openBox a b) :=
  isOpen_set_pi finite_univ fun _ _ ↦ isOpen_Ioo.reProdIm isOpen_Ioo

variable (f) in
/-- A closed box inside `f(W)` lies in `f(W')` for an open `W' ≤ W` whose image is an open
box. -/
lemma exists_le_image_openBox {W : Opens Y.toPresheafedSpace} {a b : ι → ℂ}
    (hK : Complex.closedBox a b ⊆ imageOpens f W) :
    ∃ W' : Opens Y.toPresheafedSpace, W' ≤ W ∧ Complex.closedBox a b ⊆ imageOpens f W' ∧
      ∃ a' b' : ι → ℂ, (imageOpens f W' : Set (ι → ℂ)) = Complex.openBox a' b' := by
  obtain ⟨a', b', hab, hU⟩ := exists_openBox_between (imageOpens f W).isOpen hK
  refine ⟨W ⊓ (Opens.map f.base).obj ⟨_, isOpen_openBox a' b'⟩, inf_le_left, ?_, a', b', ?_⟩
  · intro x hx
    obtain ⟨y, hy, rfl⟩ := hK hx
    exact ⟨y, ⟨hy, hab hx⟩, rfl⟩
  · ext x
    refine ⟨?_, fun hx ↦ ?_⟩
    · rintro ⟨y, hy, rfl⟩
      exact hy.2
    · obtain ⟨y, hy, rfl⟩ := hU hx
      exact ⟨y, ⟨hy, hx⟩, rfl⟩

variable (f) in
/-- **Theorem B for the structure sheaf** on opens of `Y` whose image is an open box. -/
lemma subsingleton_H_structureSheafAb_of_openBox {W : Opens Y.toPresheafedSpace} {a b : ι → ℂ}
    (hW : (imageOpens f W : Set (ι → ℂ)) = Complex.openBox a b) (q : ℕ) (hq : 0 < q) :
    Subsingleton (TopCat.Sheaf.H ((TopCat.Sheaf.restrictOpen W).obj Y.structureSheafAb) q) :=
  (structureSheafAbImageAddEquiv f (PresheafedSpace.IsOpenImmersion.base_open (f := f.toHom)) W
    q).symm.subsingleton_congr.2
    (Complex.TheoremB.subsingleton_H_restrictOpen_structureSheafAb_openBox a b hW hq)

end Boxes

section Generators

variable (f) in
/-- **Generators from a finite free resolution.** If `M|_V` has a finite free resolution, there
is a finite family of sections of `M` over `V` which generates `M` locally on `V` and generates
the sections of `M` over every open `W ≤ V` whose image is an open box. -/
theorem exists_sections_of_hasFreeResolutionLE {V : Opens Y.toPresheafedSpace} {d : ℕ}
    (h : ((Y.restrictModules V).obj M).HasFreeResolutionLE d) :
    ∃ (I : Type u) (_ : Fintype I) (s : I → M.val.obj (op V)), GeneratesLocally s ∧
      ∀ (W : Opens Y.toPresheafedSpace) (hW : W ≤ V),
        (∃ a b : ι → ℂ, (imageOpens f W : Set (ι → ℂ)) = Complex.openBox a b) →
        ∀ σ : M.val.obj (op W), IsSecComb s hW σ := by
  obtain ⟨I, I', _, _, g, A, -, H⟩ := exists_generators_acyclic V M h
  have hbox : ∀ (W : Opens Y.toPresheafedSpace) (hW : W ≤ V),
      (∃ a b : ι → ℂ, (imageOpens f W : Set (ι → ℂ)) = Complex.openBox a b) →
      ∀ σ : M.val.obj (op W), IsSecComb g hW σ := by
    rintro W hW ⟨a, b, hab⟩ σ
    obtain ⟨c, hc⟩ := (H W hW (subsingleton_H_structureSheafAb_of_openBox f hab)).2.1 σ
    exact ⟨c, hc⟩
  refine ⟨I, inferInstance, g, fun W hW σ y hy ↦ ?_, hbox⟩
  obtain ⟨W', hW'W, hyW', a', b', hab⟩ := exists_le_image_openBox f
    (W := W) (a := show ι → ℂ from f.base y) (b := show ι → ℂ from f.base y) fun x hx ↦ by
      have hx : x = f.base y := funext fun j ↦ by
        obtain ⟨⟨h1, h2⟩, h3, h4⟩ := hx j (mem_univ _)
        exact Complex.ext (le_antisymm h2 h1) (le_antisymm h4 h3)
      exact hx ▸ ⟨y, hy, rfl⟩
  have hyW'' : y ∈ W' := by
    obtain ⟨z, hz, hzy⟩ := hyW' (show f.base y ∈ Complex.closedBox _ _ from
      fun j _ ↦ ⟨⟨le_rfl, le_rfl⟩, le_rfl, le_rfl⟩)
    rwa [← (isOpenEmbedding_base (f := f)).injective hzy]
  exact ⟨W', hW'W, hyW'', hbox W' (hW'W.trans hW) ⟨a', b', hab⟩ _⟩

/-- **Bases from a free sheaf.** If `M|_V` is free, there is a linearly independent finite family
of sections of `M` over `V` which generates the sections of `M` over every open `W ≤ V`. -/
theorem exists_basis_of_hasFreeResolutionLE_zero {V : Opens Y.toPresheafedSpace}
    (h : ((Y.restrictModules V).obj M).HasFreeResolutionLE 0) :
    ∃ (I : Type u) (_ : Fintype I) (_ : DecidableEq I) (s : I → M.val.obj (op V)),
      LinIndepSections s ∧ ∀ (W : Opens Y.toPresheafedSpace) (hW : W ≤ V)
        (σ : M.val.obj (op W)), IsSecComb s hW σ := by
  classical
  cases h with
  | free _ I e =>
    have := Fintype.ofFinite I
    let p := e.inv ≫ (restrictModulesObjIso Y V M).hom
    have : IsIso p := inferInstanceAs (IsIso (e.inv ≫ _))
    refine ⟨I, inferInstance, inferInstance, restrictGenerator V M p,
      @linIndepSections_restrictGenerator _ _ _ _ _ p this,
      fun W hW σ ↦ isSecComb_restrictGenerator p hW
        (PresheafOfModules.surjective_of_epi ((SheafOfModules.forget _).map p) _) σ⟩

end Generators

section Induction

variable (f M) in
/-- `M` has a finite free resolution of length `≤ d` near `K` (if `K` is nonempty): on an open
`W` with `K ⊆ f(W)`. -/
def NearFreeResolution (d : ℕ) (K : Set (ι → ℂ)) : Prop :=
  K.Nonempty → ∃ W : Opens Y.toPresheafedSpace, K ⊆ imageOpens f W ∧
    ((Y.restrictModules W).obj M).HasFreeResolutionLE d

lemma NearFreeResolution.mono {d : ℕ} {K K' : Set (ι → ℂ)} (h : NearFreeResolution f M d K)
    (hK : K' ⊆ K) : NearFreeResolution f M d K' :=
  fun hne ↦ (h (hne.mono hK)).imp fun _ hW ↦ ⟨hK.trans hW.1, hW.2⟩

lemma image_inf_subset {W₁ W₂ : Opens Y.toPresheafedSpace} :
    (imageOpens f W₁ : Set (ι → ℂ)) ∩ imageOpens f W₂ ⊆ imageOpens f (W₁ ⊓ W₂) := by
  rintro _ ⟨⟨y₁, hy₁, rfl⟩, ⟨y₂, hy₂, hy⟩⟩
  rw [(isOpenEmbedding_base (f := f)).injective hy] at hy₂
  exact ⟨y₁, ⟨hy₁, hy₂⟩, rfl⟩

lemma image_sup {W₁ W₂ : Opens Y.toPresheafedSpace} :
    (imageOpens f W₁ : Set (ι → ℂ)) ∪ imageOpens f W₂ ⊆ imageOpens f (W₁ ⊔ W₂) :=
  union_subset ((LocallyRingedSpace.IsOpenImmersion.opensFunctor f).monotone le_sup_left)
    ((LocallyRingedSpace.IsOpenImmersion.opensFunctor f).monotone le_sup_right)

lemma card_eq_of_mul_eq_one {I J : Type*} [Fintype I] [Fintype J] [DecidableEq I]
    [DecidableEq J] (A : Matrix J I ℂ) (B : Matrix I J ℂ) (h₁ : A * B = 1) (h₂ : B * A = 1) :
    Fintype.card I = Fintype.card J := by
  let e : (I → ℂ) ≃ₗ[ℂ] (J → ℂ) := LinearEquiv.ofLinear (Matrix.toLin' A) (Matrix.toLin' B)
    (by rw [← Matrix.toLin'_mul, h₁, Matrix.toLin'_one]) (by rw [← Matrix.toLin'_mul, h₂,
      Matrix.toLin'_one])
  simpa using e.finrank_eq

lemma isSecComb_self {V : Opens Y.toPresheafedSpace} {κ : Type*} [Fintype κ]
    (u : κ → M.val.obj (op V)) (k : κ) : IsSecComb u le_rfl (u k) :=
  by classical exact ⟨Pi.single k 1, by simp [Pi.single_apply, modRes_self]⟩

/-- **Merging free sheaves.** If `M` is free near `K₁` and near `K₂`, for compact `K₁`, `K₂` with
Cartan's splitting property meeting in a nonempty closed box, then `M` is free near
`K₁ ∪ K₂`. -/
theorem nearFreeResolution_union_zero {K₁ K₂ : Set (ι → ℂ)} (hK₁ : IsCompact K₁)
    (hK₂ : IsCompact K₂)
    (hsplit : ∀ (κ : Type u) [Fintype κ] [DecidableEq κ], Complex.MatrixSplit κ K₁ K₂)
    {a' b' : ι → ℂ} (hS₁ : Complex.closedBox a' b' ⊆ K₁) (hS₂ : Complex.closedBox a' b' ⊆ K₂)
    (hS : K₁ ∩ K₂ ⊆ Complex.closedBox a' b') (hne : (Complex.closedBox a' b').Nonempty)
    (h₁ : NearFreeResolution f M 0 K₁) (h₂ : NearFreeResolution f M 0 K₂) :
    NearFreeResolution f M 0 (K₁ ∪ K₂) := by
  intro _
  obtain ⟨W₁, hKW₁, hW₁⟩ := h₁ (hne.mono hS₁)
  obtain ⟨W₂, hKW₂, hW₂⟩ := h₂ (hne.mono hS₂)
  obtain ⟨Ω₀, hΩ₀, hSΩ₀, -⟩ := exists_le_image_openBox f (W := W₁ ⊓ W₂)
    fun x hx ↦ image_inf_subset ⟨hKW₁ (hS₁ hx), hKW₂ (hS₂ hx)⟩
  have h₀₁ : Ω₀ ≤ W₁ := hΩ₀.trans inf_le_left
  have h₀₂ : Ω₀ ≤ W₂ := hΩ₀.trans inf_le_right
  obtain ⟨I, _, _, s, hs, hsc⟩ := exists_basis_of_hasFreeResolutionLE_zero hW₁
  obtain ⟨J, _, _, t, ht, htc⟩ := exists_basis_of_hasFreeResolutionLE_zero hW₂
  choose A hA using fun j ↦ hsc Ω₀ h₀₁ (modRes (t j) Ω₀ h₀₂)
  choose B hB using fun i ↦ htc Ω₀ h₀₂ (modRes (s i) Ω₀ h₀₁)
  set A' : Matrix J I (Y.presheaf.obj (op Ω₀)) := Matrix.of A
  set B' : Matrix I J (Y.presheaf.obj (op Ω₀)) := Matrix.of B
  have eA : (fun j ↦ modRes (t j) Ω₀ h₀₂) = matAct A' fun i ↦ modRes (s i) Ω₀ h₀₁ := funext hA
  have eB : (fun i ↦ modRes (s i) Ω₀ h₀₁) = matAct B' fun j ↦ modRes (t j) Ω₀ h₀₂ := funext hB
  have hBA : B' * A' = 1 := by
    have h0 : matAct (B' * A' - 1) (fun i ↦ modRes (s i) Ω₀ h₀₁) = 0 := by
      rw [matAct_sub, matAct_mul, ← eA, ← eB, matAct_one, sub_self]
    ext i i'
    have := congrFun (hs Ω₀ h₀₁ _ (congrFun h0 i)) i'
    simpa [sub_eq_zero] using this
  have hAB : A' * B' = 1 := by
    have h0 : matAct (A' * B' - 1) (fun j ↦ modRes (t j) Ω₀ h₀₂) = 0 := by
      rw [matAct_sub, matAct_mul, ← eB, ← eA, matAct_one, sub_self]
    ext j j'
    have := congrFun (ht Ω₀ h₀₂ _ (congrFun h0 j)) j'
    simpa [sub_eq_zero] using this
  obtain ⟨x, hx⟩ := hne
  have hx₀ := hSΩ₀ hx
  have hcard : Fintype.card J = Fintype.card I :=
    (card_eq_of_mul_eq_one (B'.map (secEval f hx₀)) (A'.map (secEval f hx₀))
      (by rw [← Matrix.map_mul, hBA, Matrix.map_one _ (map_zero _) (map_one _)])
      (by rw [← Matrix.map_mul, hAB, Matrix.map_one _ (map_zero _) (map_one _)]))
  let e : J ≃ I := Fintype.equivOfCardEq hcard
  obtain ⟨Ω₁, Ω₂, hΩ₁, hΩ₂, hKΩ₁, hKΩ₂, w, ⟨H₁, H₁', hH₁, hw₁⟩, ⟨H₂, H₂', hH₂, hw₂⟩⟩ :=
    exists_glued_sections hK₁ hK₂ (hsplit I) hKW₁ hKW₂ h₀₁ h₀₂ (hS.trans hSΩ₀) s (t ∘ e.symm)
      (B'.submatrix _root_.id e.symm) (A'.submatrix e.symm _root_.id)
      (by rw [Matrix.submatrix_mul_equiv, hBA, Matrix.submatrix_id_id]) (by
        rw [eB]
        funext i
        simp only [matAct, Matrix.submatrix_apply, _root_.id, Function.comp_apply]
        exact (e.symm.sum_comp fun j ↦ B' i j • modRes (t j) Ω₀ h₀₂).symm)
  have hgen : GeneratesLocally w := by
    refine GeneratesLocally.sup ?_ ?_
    · exact ((generatesLocally_of_forall_isSecComb hsc).res hΩ₁).of_matAct
        (mul_eq_one_comm.1 hH₁) hw₁
    · refine ((generatesLocally_of_forall_isSecComb htc).of_comb fun j ↦ ?_).res hΩ₂
        |>.of_matAct (mul_eq_one_comm.1 hH₂) hw₂
      have := isSecComb_self (M := M) (t ∘ e.symm) (e j)
      simpa using this
  have hlin : LinIndepSections w :=
    LinIndepSections.sup ((hs.res hΩ₁).of_matAct hH₁ hw₁)
      (((ht.comp_equiv e.symm).res hΩ₂).of_matAct hH₂ hw₂)
  haveI := isIso_freeHomOfSections hgen hlin
  exact ⟨Ω₁ ⊔ Ω₂, (union_subset_union hKΩ₁ hKΩ₂).trans image_sup,
    .free 0 I (restrictModulesObjIso Y _ M ≪≫ (asIso (freeHomOfSections w)).symm)⟩

variable (ι) in
/-- Finite free resolutions of length `≤ d` exist near closed boxes, for coherent sheaves with
stalks of projective dimension `≤ d` on open subspaces of `ℂ^ι` with locally finitely generated
relations. -/
def BoxResolution (d : ℕ) : Prop :=
  ∀ {Y : LocallyRingedSpace.{u}} (f : Y ⟶ complexSpace ι) [LocallyRingedSpace.IsOpenImmersion f],
    Y.HasLocalRelations → ∀ (M : SheafOfModules.{u} Y.ringSheaf) [M.IsCoherent],
    (∀ y, HasProjectiveDimensionLE ((Y.stalkFunctor y).obj M) d) →
    ∀ a b : ι → ℂ, Complex.closedBox a b ⊆ range f.base →
      NearFreeResolution f M d (Complex.closedBox a b)

lemma fromBlocks_mul_fromBlocks_eq_one {I J R : Type*} [Fintype I] [Fintype J] [DecidableEq I]
    [DecidableEq J] [CommRing R] (A : Matrix J I R) (B : Matrix I J R) :
    Matrix.fromBlocks 1 B (-A) (1 - A * B) * Matrix.fromBlocks (1 - B * A) (-B) A 1 = 1 := by
  rw [Matrix.fromBlocks_multiply, ← Matrix.fromBlocks_one]
  congr 1 <;> simp only [Matrix.mul_assoc, Matrix.mul_sub, Matrix.sub_mul, Matrix.one_mul,
    Matrix.mul_one, Matrix.neg_mul, Matrix.mul_neg] <;> abel

/-- **Merging finite free resolutions.** Assume finite free resolutions of length `≤ d` exist
near closed boxes for all coherent sheaves with stalks of projective dimension `≤ d`. If `M` has
stalks of projective dimension `≤ d + 1` and finite free resolutions of length `≤ d + 1` near
`K₁` and near `K₂`, for compact `K₁`, `K₂` with Cartan's splitting property meeting in a
nonempty closed box and with union a closed box, then `M` has one near `K₁ ∪ K₂`. -/
theorem nearFreeResolution_union_succ {d : ℕ} (IH : BoxResolution ι d)
    (hY : Y.HasLocalRelations) [M.IsCoherent]
    (hpd : ∀ y, HasProjectiveDimensionLE ((Y.stalkFunctor y).obj M) (d + 1))
    {K₁ K₂ : Set (ι → ℂ)} (hK₁ : IsCompact K₁) (hK₂ : IsCompact K₂)
    (hsplit : ∀ (κ : Type u) [Fintype κ] [DecidableEq κ], Complex.MatrixSplit κ K₁ K₂)
    {a' b' : ι → ℂ} (hS₁ : Complex.closedBox a' b' ⊆ K₁) (hS₂ : Complex.closedBox a' b' ⊆ K₂)
    (hS : K₁ ∩ K₂ ⊆ Complex.closedBox a' b') (hne : (Complex.closedBox a' b').Nonempty)
    {a₀ b₀ : ι → ℂ} (hK : K₁ ∪ K₂ = Complex.closedBox a₀ b₀)
    (h₁ : NearFreeResolution f M (d + 1) K₁) (h₂ : NearFreeResolution f M (d + 1) K₂) :
    NearFreeResolution f M (d + 1) (K₁ ∪ K₂) := by
  classical
  intro _
  obtain ⟨W₁, hKW₁, hW₁⟩ := h₁ (hne.mono hS₁)
  obtain ⟨W₂, hKW₂, hW₂⟩ := h₂ (hne.mono hS₂)
  obtain ⟨Ω₀, hΩ₀, hSΩ₀, a₁, b₁, hbox⟩ := exists_le_image_openBox f (W := W₁ ⊓ W₂)
    fun x hx ↦ image_inf_subset ⟨hKW₁ (hS₁ hx), hKW₂ (hS₂ hx)⟩
  have h₀₁ : Ω₀ ≤ W₁ := hΩ₀.trans inf_le_left
  have h₀₂ : Ω₀ ≤ W₂ := hΩ₀.trans inf_le_right
  obtain ⟨I, _, s, hs, hsc⟩ := exists_sections_of_hasFreeResolutionLE f hW₁
  obtain ⟨J, _, t, ht, htc⟩ := exists_sections_of_hasFreeResolutionLE f hW₂
  choose A hA using fun j ↦ hsc Ω₀ h₀₁ ⟨a₁, b₁, hbox⟩ (modRes (t j) Ω₀ h₀₂)
  choose B hB using fun i ↦ htc Ω₀ h₀₂ ⟨a₁, b₁, hbox⟩ (modRes (s i) Ω₀ h₀₁)
  set A' : Matrix J I (Y.presheaf.obj (op Ω₀)) := Matrix.of A
  set B' : Matrix I J (Y.presheaf.obj (op Ω₀)) := Matrix.of B
  have eA : (fun j ↦ modRes (t j) Ω₀ h₀₂) = matAct A' fun i ↦ modRes (s i) Ω₀ h₀₁ := funext hA
  have eB : (fun i ↦ modRes (s i) Ω₀ h₀₁) = matAct B' fun j ↦ modRes (t j) Ω₀ h₀₂ := funext hB
  let u₁ : I ⊕ J → M.val.obj (op W₁) := Sum.elim s 0
  let u₂ : I ⊕ J → M.val.obj (op W₂) := Sum.elim 0 t
  have ht0 : matAct (1 - A' * B') (fun j ↦ modRes (t j) Ω₀ h₀₂) = 0 := by
    rw [matAct_sub, matAct_mul, ← eB, ← eA, matAct_one, sub_self]
  have hu : (fun k ↦ modRes (u₁ k) Ω₀ h₀₁) =
      matAct (Matrix.fromBlocks 1 B' (-A') (1 - A' * B')) fun l ↦ modRes (u₂ l) Ω₀ h₀₂ := by
    funext k
    rcases k with i | j
    · simp only [u₁, u₂, matAct, Fintype.sum_sum_type, Sum.elim_inl, Sum.elim_inr,
        Matrix.fromBlocks_apply₁₁, Matrix.fromBlocks_apply₁₂, Pi.zero_apply, modRes_zero,
        smul_zero, Finset.sum_const_zero, zero_add]
      exact congrFun eB i
    · simp only [u₁, u₂, matAct, Fintype.sum_sum_type, Sum.elim_inl, Sum.elim_inr,
        Matrix.fromBlocks_apply₂₁, Matrix.fromBlocks_apply₂₂, Pi.zero_apply, modRes_zero,
        smul_zero, Finset.sum_const_zero, zero_add]
      exact (congrFun ht0 j).symm
  obtain ⟨Ω₁, Ω₂, hΩ₁, hΩ₂, hKΩ₁, hKΩ₂, w, ⟨H₁, H₁', hH₁, hw₁⟩, ⟨H₂, H₂', hH₂, hw₂⟩⟩ :=
    exists_glued_sections hK₁ hK₂ (hsplit (I ⊕ J)) hKW₁ hKW₂ h₀₁ h₀₂ (hS.trans hSΩ₀) u₁ u₂ _ _
      (fromBlocks_mul_fromBlocks_eq_one A' B') hu
  have hgen : GeneratesLocally w := by
    refine GeneratesLocally.sup ?_ ?_
    · exact ((hs.res hΩ₁).of_comb fun i ↦
        isSecComb_self (fun k ↦ modRes (u₁ k) Ω₁ hΩ₁) (Sum.inl i)).of_matAct
          (mul_eq_one_comm.1 hH₁) hw₁
    · exact ((ht.res hΩ₂).of_comb fun j ↦
        isSecComb_self (fun k ↦ modRes (u₂ k) Ω₂ hΩ₂) (Sum.inr j)).of_matAct
          (mul_eq_one_comm.1 hH₂) hw₂
  let π := freeHomOfSections w ≫ (restrictModulesObjIso Y (Ω₁ ⊔ Ω₂) M).inv
  haveI : Epi π := @epi_comp _ _ _ _ _ _ (epi_freeHomOfSections hgen) _ inferInstance
  let Y' := Y.restrict (Ω₁ ⊔ Ω₂).isOpenEmbedding
  let M' := (Y.restrictModules (Ω₁ ⊔ Ω₂)).obj M
  have hY' : Y'.HasLocalRelations := hY.restrict (Ω₁ ⊔ Ω₂)
  haveI : (SheafOfModules.unit Y'.ringSheaf).IsCoherent :=
    isCoherentStructureSheaf_of_hasLocalRelations hY'
  haveI : (SheafOfModules.free (R := Y'.ringSheaf) (I ⊕ J)).IsCoherent :=
    SheafOfModules.IsCoherent.free _
  have hM' := isCoherent_restrictModules M (Ω₁ ⊔ Ω₂)
  haveI : (kernel π).IsCoherent :=
    @SheafOfModules.IsCoherent.kernel _ _ _ _ _ _ _ π inferInstance hM'
  have hS' := shortExact_kernel π
  have hpdK : ∀ y', HasProjectiveDimensionLE ((Y'.stalkFunctor y').obj (kernel π)) d :=
    fun y' ↦ hasProjectiveDimensionLE_stalk_of_shortExact _ _ _ hS' y' d
      (@Hom.hasProjectiveDimensionLE_stalk_pullbackModules _ _
        (Y.ofRestrict (Ω₁ ⊔ Ω₂).isOpenEmbedding) y' _ M (d + 1) (hpd _))
  have hrange : Complex.closedBox a₀ b₀ ⊆
      range (Y.ofRestrict (Ω₁ ⊔ Ω₂).isOpenEmbedding ≫ f).base := by
    rw [← hK]
    intro x hx
    obtain ⟨y, hy, rfl⟩ := image_sup (union_subset_union hKΩ₁ hKΩ₂ hx)
    exact ⟨⟨y, hy⟩, rfl⟩
  obtain ⟨W', hKW', hW'⟩ := IH (Y.ofRestrict (Ω₁ ⊔ Ω₂).isOpenEmbedding ≫ f) hY' (kernel π) hpdK
    a₀ b₀ hrange (hK ▸ (hne.mono (hS₁.trans subset_union_left)))
  have hW'' : ((Y'.restrictModules W').obj (kernel π)).HasFreeResolutionLE d := hW'
  haveI hfl : PreservesFiniteLimits (Y'.restrictModules W') :=
    (Y'.ofRestrict W'.isOpenEmbedding).preservesFiniteLimits_pullbackModules
      (flat_stalkMap_of_isIso _)
  haveI : (Y'.restrictModules W').IsLeftAdjoint :=
    (Y'.ofRestrict W'.isOpenEmbedding).pullbackModulesAdj.isLeftAdjoint
  haveI : PreservesColimits (Y'.restrictModules W') :=
    (Y'.ofRestrict W'.isOpenEmbedding).pullbackModulesAdj.leftAdjoint_preservesColimits
  haveI := Functor.preservesZeroMorphisms_of_isLeftAdjoint (Y'.restrictModules W')
  have hres : ((Y'.restrictModules W').obj M').HasFreeResolutionLE (d + 1) :=
    @SheafOfModules.HasFreeResolutionLE.of_shortExact_map _ _ _ _ _ _ _ _ _ _ _ _
      (Y'.restrictModules W') inferInstance hfl inferInstance
      (fun I _ ↦ (Y'.ofRestrict W'.isOpenEmbedding).pullbackModulesFreeIso I)
      _ _ _ inferInstance _ _ _ hS' _ hW''
  refine ⟨imOpen (Ω₁ ⊔ Ω₂) W', ?_,
    hasFreeResolutionLE_restrictModules_of_restrict (Ω₁ ⊔ Ω₂) W' hres⟩
  rw [hK]
  intro x hx
  obtain ⟨z, hz, rfl⟩ := hKW' hx
  exact ⟨z.1, ⟨z, hz, rfl⟩, rfl⟩

/-- **Finite free resolutions near closed boxes**, by induction on the projective dimension of
the stalks. -/
theorem boxResolution (d : ℕ) : BoxResolution ι d := by
  classical
  induction d with
  | zero =>
    intro Y f _ hY M _ hpd a b hK
    refine Complex.closedBox_induction (NearFreeResolution f M 0) (fun _ _ h hK ↦ hK.mono h)
      (fun h ↦ absurd h Set.not_nonempty_empty) ?_ ?_ fun x hx ↦ ?_
    · intro i a' b' hord x₀ x₁ hx₀ hx₁ hQ₁ hQ₂
      exact nearFreeResolution_union_zero (Complex.isCompact_closedBox _ _)
        (Complex.isCompact_closedBox _ _)
        (fun κ _ _ ↦ Complex.matrixSplit_re i (hord i).1 (hord i).2 hx₀ hx₁)
        (Complex.closedBox_subset_update_left i hx₀) (Complex.closedBox_subset_update_right i hx₁)
        (Complex.closedBox_update_inter_subset i x₀ x₁) (Complex.closedBox_nonempty hord) hQ₁ hQ₂
    · intro i a' b' hord y₀ y₁ hy₀ hy₁ hQ₁ hQ₂
      exact nearFreeResolution_union_zero (Complex.isCompact_closedBox _ _)
        (Complex.isCompact_closedBox _ _)
        (fun κ _ _ ↦ Complex.matrixSplit_im i (hord i).1 (hord i).2 hy₀ hy₁)
        (Complex.closedBox_subset_update_left_im i hy₀)
        (Complex.closedBox_subset_update_right_im i hy₁)
        (Complex.closedBox_update_inter_subset_im i y₀ y₁) (Complex.closedBox_nonempty hord) hQ₁
        hQ₂
    · obtain ⟨y, rfl⟩ := hK hx
      obtain ⟨U, hyU, hU⟩ := exists_hasFreeResolutionLE_of_stalk 0 hY M y (hpd y)
      exact ⟨imageOpens f U, (imageOpens f U).isOpen.mem_nhds ⟨y, hyU, rfl⟩,
        fun K hKU _ ↦ ⟨U, hKU, hU⟩⟩
  | succ d ih =>
    intro Y f _ hY M _ hpd a b hK
    refine Complex.closedBox_induction (NearFreeResolution f M (d + 1))
      (fun _ _ h hK ↦ hK.mono h) (fun h ↦ absurd h Set.not_nonempty_empty) ?_ ?_ fun x hx ↦ ?_
    · intro i a' b' hord x₀ x₁ hx₀ hx₁ hQ₁ hQ₂
      exact nearFreeResolution_union_succ ih hY hpd (Complex.isCompact_closedBox _ _)
        (Complex.isCompact_closedBox _ _)
        (fun κ _ _ ↦ Complex.matrixSplit_re i (hord i).1 (hord i).2 hx₀ hx₁)
        (Complex.closedBox_subset_update_left i hx₀) (Complex.closedBox_subset_update_right i hx₁)
        (Complex.closedBox_update_inter_subset i x₀ x₁) (Complex.closedBox_nonempty hord)
        (Complex.closedBox_union_re i (hord i).1 hx₀ hx₁) hQ₁ hQ₂
    · intro i a' b' hord y₀ y₁ hy₀ hy₁ hQ₁ hQ₂
      exact nearFreeResolution_union_succ ih hY hpd (Complex.isCompact_closedBox _ _)
        (Complex.isCompact_closedBox _ _)
        (fun κ _ _ ↦ Complex.matrixSplit_im i (hord i).1 (hord i).2 hy₀ hy₁)
        (Complex.closedBox_subset_update_left_im i hy₀)
        (Complex.closedBox_subset_update_right_im i hy₁)
        (Complex.closedBox_update_inter_subset_im i y₀ y₁) (Complex.closedBox_nonempty hord)
        (Complex.closedBox_union_im i (hord i).2 hy₀ hy₁) hQ₁ hQ₂
    · obtain ⟨y, rfl⟩ := hK hx
      obtain ⟨U, hyU, hU⟩ := exists_hasFreeResolutionLE_of_stalk (d + 1) hY M y (hpd y)
      exact ⟨imageOpens f U, (imageOpens f U).isOpen.mem_nhds ⟨y, hyU, rfl⟩,
        fun K hKU _ ↦ ⟨U, hKU, hU⟩⟩

end Induction

section Main

/-- A sheaf of modules with a finite free resolution is a quotient of a finite free sheaf. -/
lemma exists_epi_free_of_hasFreeResolutionLE {Z : LocallyRingedSpace.{u}}
    {N : SheafOfModules.{u} Z.ringSheaf} {d : ℕ} (h : N.HasFreeResolutionLE d) :
    ∃ (I : Type u) (_ : Finite I) (p : SheafOfModules.free I ⟶ N), Epi p := by
  cases h with
  | free _ I e => exact ⟨I, inferInstance, e.inv, inferInstance⟩
  | ext I i p w hS _ => exact ⟨I, inferInstance, p, hS.epi_g⟩

variable (f)

/-- **Finite free resolutions near closed boxes.** Let `f : Y ⟶ ℂ^ι` be an open immersion, where
`𝒪_Y` has locally finitely generated relations, and let `M` be a coherent sheaf of `𝒪_Y`-modules
whose stalks have projective dimension `≤ d`. Then every nonempty closed box `K ⊆ f(Y)` has an
open neighbourhood `f(W)` such that `M|_W` has a finite free resolution of length `≤ d`. -/
theorem exists_hasFreeResolutionLE_closedBox (hY : Y.HasLocalRelations)
    (M : SheafOfModules.{u} Y.ringSheaf)
    [M.IsCoherent] {d : ℕ} (hpd : ∀ y, HasProjectiveDimensionLE ((Y.stalkFunctor y).obj M) d)
    {a b : ι → ℂ} (hK : Complex.closedBox a b ⊆ range f.base)
    (hne : (Complex.closedBox a b).Nonempty) :
    ∃ W : Opens Y.toPresheafedSpace, Complex.closedBox a b ⊆ imageOpens f W ∧
      ((Y.restrictModules W).obj M).HasFreeResolutionLE d :=
  boxResolution d f hY M hpd a b hK hne

/-- **Cartan's Theorem A for closed boxes.** Under the hypotheses of
`ComplexAnalytic.exists_hasFreeResolutionLE_closedBox`, `M` is generated near the closed box `K`
by finitely many sections: there are an open `W` with `K ⊆ f(W)` and an epimorphism
`𝒪^I ⟶ M|_W` with `I` finite. -/
theorem exists_epi_free_closedBox (hY : Y.HasLocalRelations) (M : SheafOfModules.{u} Y.ringSheaf)
    [M.IsCoherent] {d : ℕ} (hpd : ∀ y, HasProjectiveDimensionLE ((Y.stalkFunctor y).obj M) d)
    {a b : ι → ℂ} (hK : Complex.closedBox a b ⊆ range f.base)
    (hne : (Complex.closedBox a b).Nonempty) :
    ∃ (W : Opens Y.toPresheafedSpace) (_ : Complex.closedBox a b ⊆ imageOpens f W) (I : Type u)
      (_ : Finite I) (p : SheafOfModules.free I ⟶ (Y.restrictModules W).obj M), Epi p := by
  obtain ⟨W, hKW, hW⟩ := exists_hasFreeResolutionLE_closedBox f hY M hpd hK hne
  exact ⟨W, hKW, exists_epi_free_of_hasFreeResolutionLE hW⟩

/-- **Cartan's Theorem A for closed boxes, with sections.** Under the hypotheses of
`ComplexAnalytic.exists_hasFreeResolutionLE_closedBox`, there are an open `W` with `K ⊆ f(W)` and
finitely many sections of `M` over `W` which generate `M` locally on `W` (in particular they
generate every stalk of `M` at points of `W`), and which generate the sections of `M` over every
open `V ≤ W` whose image is an open box. -/
theorem exists_sections_closedBox (hY : Y.HasLocalRelations) (M : SheafOfModules.{u} Y.ringSheaf)
    [M.IsCoherent] {d : ℕ} (hpd : ∀ y, HasProjectiveDimensionLE ((Y.stalkFunctor y).obj M) d)
    {a b : ι → ℂ} (hK : Complex.closedBox a b ⊆ range f.base)
    (hne : (Complex.closedBox a b).Nonempty) :
    ∃ (W : Opens Y.toPresheafedSpace) (_ : Complex.closedBox a b ⊆ imageOpens f W) (I : Type u)
      (_ : Fintype I) (s : I → M.val.obj (op W)), GeneratesLocally s ∧
      ∀ (V : Opens Y.toPresheafedSpace) (hV : V ≤ W),
        (∃ a' b' : ι → ℂ, (imageOpens f V : Set (ι → ℂ)) = Complex.openBox a' b') →
        ∀ σ : M.val.obj (op V), IsSecComb s hV σ := by
  obtain ⟨W, hKW, hW⟩ := exists_hasFreeResolutionLE_closedBox f hY M hpd hK hne
  exact ⟨W, hKW, exists_sections_of_hasFreeResolutionLE f hW⟩

end Main

section AffineSpace

variable {n : ℕ} (U : Opens (complexAffineSpace.{u} n))

/-- The stalks of a coherent sheaf on an open subset of `ℂⁿ` have projective dimension `≤ n`
(the syzygy theorem). -/
lemma hasProjectiveDimensionLE_stalk_restrict_complexAffineSpace
    (M : SheafOfModules.{u} ((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).ringSheaf)
    [M.IsCoherent] (y : (complexAffineSpace.{u} n).restrict U.isOpenEmbedding) :
    HasProjectiveDimensionLE
      ((((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).stalkFunctor y).obj M) n := by
  haveI := finite_stalk_of_isFiniteType M y
  exact hasFGGlobalDimensionLE_stalk_of_isIso
    ((complexAffineSpace.{u} n).ofRestrict U.isOpenEmbedding) y
    (hasFGGlobalDimensionLE_stalk_complexAffineSpace n _)
    (((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).stalkFunctor y |>.obj M)

/-- **Finite free resolutions near closed boxes in `ℂⁿ`.** Let `M` be a coherent sheaf of
modules on an open `U ⊆ ℂⁿ` and `K ⊆ U` a nonempty closed box. Then `M` has a finite free
resolution `0 → 𝒪^{pₙ} → ⋯ → 𝒪^{p₀} → M|_W → 0` of length `≤ n` on an open neighbourhood `W` of
`K` in `U`. -/
theorem exists_hasFreeResolutionLE_closedBox_complexAffineSpace
    (M : SheafOfModules.{u} ((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).ringSheaf)
    [M.IsCoherent] {a b : ULift.{u} (Fin n) → ℂ}
    (hK : ∀ x ∈ Complex.closedBox a b, x ∈ U)
    (hne : (Complex.closedBox a b).Nonempty) :
    ∃ W : Opens ((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).toPresheafedSpace,
      Complex.closedBox a b ⊆
        imageOpens ((complexAffineSpace.{u} n).ofRestrict U.isOpenEmbedding) W ∧
      ((((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).restrictModules W).obj
        M).HasFreeResolutionLE n :=
  exists_hasFreeResolutionLE_closedBox ((complexAffineSpace.{u} n).ofRestrict U.isOpenEmbedding)
    ((hasLocalRelations_complexSpace _).restrict U) M
    (hasProjectiveDimensionLE_stalk_restrict_complexAffineSpace U M)
    (fun x hx ↦ ⟨⟨x, hK x hx⟩, rfl⟩) hne

/-- **Cartan's Theorem A for closed boxes in `ℂⁿ`.** A coherent sheaf of modules on an open
`U ⊆ ℂⁿ` is, on an open neighbourhood `W` of a nonempty closed box `K ⊆ U`, a quotient of a
finite free sheaf `𝒪^I`. -/
theorem exists_epi_free_closedBox_complexAffineSpace
    (M : SheafOfModules.{u} ((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).ringSheaf)
    [M.IsCoherent] {a b : ULift.{u} (Fin n) → ℂ}
    (hK : ∀ x ∈ Complex.closedBox a b, x ∈ U)
    (hne : (Complex.closedBox a b).Nonempty) :
    ∃ (W : Opens ((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).toPresheafedSpace)
      (_ : Complex.closedBox a b ⊆
        imageOpens ((complexAffineSpace.{u} n).ofRestrict U.isOpenEmbedding) W) (I : Type u)
      (_ : Finite I) (p : SheafOfModules.free I ⟶
        (((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).restrictModules W).obj M),
      Epi p := by
  obtain ⟨W, hKW, hW⟩ := exists_hasFreeResolutionLE_closedBox_complexAffineSpace U M hK hne
  exact ⟨W, hKW, exists_epi_free_of_hasFreeResolutionLE hW⟩

end AffineSpace

end ComplexAnalytic
