/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka.Analytification.GAGA.ClosedImmersion
import Oka.Geometry.RingedSpace.LocallyRingedSpace.ModulesClosedEmbedding

/-!
# Analytification commutes with pushforward along closed immersions

Let `i : Z ⟶ X` be a closed immersion of schemes locally of finite type over `ℂ`, and
`π_X : X^an ⟶ X`, `π_Z : Z^an ⟶ Z` the comparison morphisms. For every sheaf of `𝒪_Z`-modules `G`
(no quasi-coherence is needed) the base change morphism
`ComplexAnalytic.analytificationPushforwardBaseChange i G : (i_* G)^an ⟶ (i^an)_* (G^an)`
is an isomorphism (`ComplexAnalytic.isIso_analytificationPushforwardBaseChange`).

The base change morphism is the unit of `(i^an)^* ⊣ (i^an)_*` at `A := (i_* G)^an`, followed by
`(i^an)_*` of `(i^an)^* A ≅ π_Z^* i^* i_* G ⟶ π_Z^* G`. Both `i` and `i^an` are closed embeddings
with surjective stalk maps, so (by
`Oka/Geometry/RingedSpace/LocallyRingedSpace/ModulesClosedEmbedding.lean`) the counit
`i^* i_* G ⟶ G` is an isomorphism, and the unit at `A` is an isomorphism once
- `A` vanishes off the image of `i^an`: the image is `π_X⁻¹(i(Z))`, and off it the stalks
  `A_x = 𝒪_{X^an,x} ⊗ (i_* G)_{π x}` vanish;
- the kernel of `𝒪_{X^an,x} → 𝒪_{Z^an,z}` (`x = i^an z`) kills `A_x`. This is the analytic input:
  **the kernel is generated by the image of the kernel of `𝒪_{X,π x} → (i_* 𝒪_Z)_{π x}`**
  (`ComplexAnalytic.ker_stalkMap_analytification_map_le`), which follows over an affine open
  `U ∋ π x` from `ComplexAnalytic.isCutOutBy_analytification_map`: `Z^an ∩ π⁻¹ U` is cut out by
  the pullbacks of generators of the ideal of `Z ∩ U`.
-/

open CategoryTheory Opposite AlgebraicGeometry TopologicalSpace Topology

universe u

namespace ComplexAnalytic

noncomputable section

variable {Z X : SchemeLFTℂ.{u}} (i : Z ⟶ X)

/-- For an open `U ⊆ X` and `s ∈ Γ(U, 𝒪_X)`, the germ of `π_X^♯ s` at a point of `π_X⁻¹ U`
corresponds, under the stalk isomorphism of `(X|_U)^an ≅ π_X⁻¹ U ⊆ X^an`, to the germ of the
pullback of `s` to `(X|_U)^an`. -/
lemma stalkMap_restrictι_stalkMap_germ (U : X.obj.left.Opens)
    (x' : analytification.obj (X.restrict U))
    (hV : (analytificationπLRS X).base ((analytification.map (X.restrictι U)).toLRSHom.base x') ∈
      U.ι ''ᵁ ⊤)
    (s : Γ((X.restrict U).obj.left, ⊤)) :
    (analytification.map (X.restrictι U)).toLRSHom.stalkMap x'
      ((analytificationπLRS X).stalkMap ((analytification.map (X.restrictι U)).toLRSHom.base x')
        (X.obj.left.presheaf.germ (U.ι ''ᵁ ⊤) _ hV s)) =
    (analytification.obj (X.restrict U)).presheaf.Γgerm x'
      ((LocallyRingedSpace.Γ.map (analytificationπLRS (X.restrict U)).op).hom s) := by
  have hcomp : (analytification.map (X.restrictι U)).toLRSHom ≫ analytificationπLRS X =
      analytificationπLRS (X.restrict U) ≫ U.ι.toLRSHom :=
    analytificationπLRS_naturality (X.restrictι U)
  have key : ∀ (F G : (analytification.obj (X.restrict U)).toLocallyRingedSpace ⟶
      X.obj.left.toLocallyRingedSpace) (_ : F = G) (hF : F.base x' ∈ U.ι ''ᵁ ⊤)
      (hG : G.base x' ∈ U.ι ''ᵁ ⊤),
      (analytification.obj (X.restrict U)).presheaf.germ ((Opens.map F.base).obj (U.ι ''ᵁ ⊤)) x'
        hF (F.c.app (op (U.ι ''ᵁ ⊤)) s) =
      (analytification.obj (X.restrict U)).presheaf.germ ((Opens.map G.base).obj (U.ι ''ᵁ ⊤)) x'
        hG (G.c.app (op (U.ι ''ᵁ ⊤)) s) := by
    rintro F G rfl _ _
    rfl
  have e1 := LocallyRingedSpace.stalkMap_germ_apply
    ((analytification.map (X.restrictι U)).toLRSHom ≫ analytificationπLRS X) (U.ι ''ᵁ ⊤) x' hV s
  refine Eq.trans ?_ (e1.trans ((key _ _ hcomp hV ⟨_, trivial, rfl⟩).trans ?_))
  · rw [LocallyRingedSpace.stalkMap_comp]
    rfl
  have e2 := LocallyRingedSpace.stalkMap_germ_apply (analytificationπLRS (X.restrict U))
    (U.ι ⁻¹ᵁ (U.ι ''ᵁ ⊤)) x' ⟨_, trivial, rfl⟩ (U.ι.app _ s)
  refine e2.symm.trans ?_
  have e3 := LocallyRingedSpace.stalkMap_germ_apply (analytificationπLRS (X.restrict U))
    ⊤ x' trivial s
  refine Eq.trans ?_ e3
  congr 1
  exact TopCat.Presheaf.germ_res_apply _ (homOfLE le_top) _ _ s

/-- A section of `𝒪_X` over an open `U` killed by the restriction `i⁻¹ U ⟶ U` of `i` is killed by
`i^♯`. -/
lemma app_restrictι_image_top_eq_zero (U : X.obj.left.Opens)
    (s : Γ((X.restrict U).obj.left, ⊤))
    (hs : s ∈ RingHom.ker (restrictHomLFT i U).hom.left.appTop.hom) :
    i.hom.left.app (U.ι ''ᵁ ⊤) s = 0 := by
  rw [RingHom.mem_ker, restrictHomLFT_hom_left] at hs
  erw [morphismRestrict_appTop, CommRingCat.comp_apply] at hs
  rw [eqToHom_op, eqToHom_map] at hs
  exact (ConcreteCategory.bijective_of_isIso (eqToHom _)).1 (hs.trans (map_zero _).symm)

variable [IsClosedImmersion i.hom.left]

/-- **The ideal of `Z^an` in `X^an` is generated by the ideal of `Z` in `X`, stalkwise**: at
`x = i^an z`, the kernel of `𝒪_{X^an,x} → 𝒪_{Z^an,z}` is contained in the ideal generated by the
image under `π_X` of the kernel of `𝒪_{X,π x} → (i_* 𝒪_Z)_{π x}`. -/
theorem ker_stalkMap_analytification_map_le (z : analytification.obj Z) :
    RingHom.ker ((analytification.map i).toLRSHom.stalkMap z).hom ≤
      Ideal.map ((analytificationπLRS X).stalkMap ((analytification.map i).toLRSHom.base z)).hom
        (i.hom.left.toLRSHom.pushforwardStalkIdeal
          ((analytificationπLRS X).base ((analytification.map i).toLRSHom.base z))) := by
  let P : ∀ x : analytification.obj X, (analytification.obj X).presheaf.stalk x → Prop :=
    fun x r ↦ r ∈ Ideal.map ((analytificationπLRS X).stalkMap x).hom
      (i.hom.left.toLRSHom.pushforwardStalkIdeal ((analytificationπLRS X).base x))
  have transport : ∀ (x₁ x₂ : analytification.obj X) (hs : x₂ ⤳ x₁) (_ : x₁ = x₂) (r),
      P x₂ ((analytification.obj X).presheaf.stalkSpecializes hs r) → P x₁ r := by
    rintro x₁ x₂ hs rfl r hr
    simpa using hr
  obtain ⟨U, hU⟩ := exists_affineOpens_mem X.obj.left
    ((analytificationπLRS X).base ((analytification.map i).toLRSHom.base z))
  have hz : z ∈ Set.range
      (analytification.map (Z.restrictι (i.hom.left ⁻¹ᵁ U.1))).toLRSHom.base := by
    rw [range_analytification_map_restrictι]
    change i.hom.left.base ((analytificationπLRS Z).base z) ∈ U.1
    rw [← analytificationπ_base_map]
    exact hU
  obtain ⟨w, rfl⟩ := hz
  haveI : IsAffine (X.restrict U.1).obj.left := inferInstanceAs (IsAffine U)
  obtain ⟨p, h, hh⟩ := exists_generators (restrictHomLFT i U.1)
  have hcut := isCutOutBy_analytification_map (restrictHomLFT i U.1) h hh
  have hsq : (analytification.map (Z.restrictι (i.hom.left ⁻¹ᵁ U.1))).toLRSHom ≫
      (analytification.map i).toLRSHom =
      (analytification.map (restrictHomLFT i U.1)).toLRSHom ≫
        (analytification.map (X.restrictι U.1)).toLRSHom :=
    (congrArg AnalyticSpace.Hom.toLRSHom (analytification_map_restrictHomLFT_restrictι i U.1)).symm
  intro r hr
  have hpt := congrArg (fun φ ↦ φ.base w) hsq
  refine transport _ _ (specializes_of_eq hpt.symm) hpt r ?_
  set r' := (analytification.obj X).presheaf.stalkSpecializes (specializes_of_eq hpt.symm) r
  have h1 : ((analytification.map (Z.restrictι (i.hom.left ⁻¹ᵁ U.1))).toLRSHom ≫
      (analytification.map i).toLRSHom).stalkMap w r = 0 := by
    rw [RingHom.mem_ker] at hr
    rw [LocallyRingedSpace.stalkMap_comp]
    erw [CommRingCat.comp_apply, hr]
    exact map_zero _
  have h2 : ((analytification.map (restrictHomLFT i U.1)).toLRSHom ≫
        (analytification.map (X.restrictι U.1)).toLRSHom).stalkMap w r' = 0 := by
    rw [LocallyRingedSpace.stalkMap_congr_hom _ _ hsq] at h1
    erw [CommRingCat.comp_apply] at h1
    exact h1
  set x' := (analytification.map (restrictHomLFT i U.1)).toLRSHom.base w
  have h3 : (analytification.map (X.restrictι U.1)).toLRSHom.stalkMap x' r' ∈
      RingHom.ker ((analytification.map (restrictHomLFT i U.1)).toLRSHom.stalkMap w).hom := by
    rw [LocallyRingedSpace.stalkMap_comp] at h2
    erw [CommRingCat.comp_apply] at h2
    exact h2
  rw [hcut.ker_stalkMap w] at h3
  have hbij := ConcreteCategory.bijective_of_isIso
    ((analytification.map (X.restrictι U.1)).toLRSHom.stalkMap x')
  have hV : (analytificationπLRS X).base ((analytification.map (X.restrictι U.1)).toLRSHom.base x')
      ∈ U.1.ι ''ᵁ ⊤ :=
    ⟨_, trivial, (analytificationπ_base_map (X.restrictι U.1) x').symm⟩
  have hspan : Ideal.span (Set.range fun j ↦
      (analytification.obj (X.restrict U.1)).presheaf.Γgerm x' (analytificationSections h j)) ≤
    Ideal.map ((analytification.map (X.restrictι U.1)).toLRSHom.stalkMap x').hom
      (Ideal.map ((analytificationπLRS X).stalkMap
          ((analytification.map (X.restrictι U.1)).toLRSHom.base x')).hom
        (i.hom.left.toLRSHom.pushforwardStalkIdeal
          ((analytificationπLRS X).base
            ((analytification.map (X.restrictι U.1)).toLRSHom.base x')))) := by
    refine Ideal.span_le.2 ?_
    rintro _ ⟨j, rfl⟩
    have hK : X.obj.left.presheaf.germ (U.1.ι ''ᵁ ⊤) _ hV (h j) ∈
        i.hom.left.toLRSHom.pushforwardStalkIdeal
          ((analytificationπLRS X).base
            ((analytification.map (X.restrictι U.1)).toLRSHom.base x')) := by
      rw [LocallyRingedSpace.Hom.pushforwardStalkIdeal, RingHom.mem_ker]
      erw [TopCat.Presheaf.stalkFunctor_map_germ_apply]
      have h0 : i.hom.left.toLRSHom.c.app (op (U.1.ι ''ᵁ ⊤)) (h j) = 0 :=
        app_restrictι_image_top_eq_zero i U.1 (h j)
          (hh ▸ Ideal.subset_span ⟨j, rfl⟩)
      exact (congrArg _ h0).trans (map_zero _)
    have := Ideal.mem_map_of_mem
      ((analytification.map (X.restrictι U.1)).toLRSHom.stalkMap x').hom
      (Ideal.mem_map_of_mem ((analytificationπLRS X).stalkMap
          ((analytification.map (X.restrictι U.1)).toLRSHom.base x')).hom hK)
    rw [stalkMap_restrictι_stalkMap_germ U.1 x' hV (h j)] at this
    exact this
  have h4 := hspan h3
  change r' ∈ Ideal.comap ((analytification.map (X.restrictι U.1)).toLRSHom.stalkMap x').hom
    (Ideal.map ((analytification.map (X.restrictι U.1)).toLRSHom.stalkMap x').hom _) at h4
  rwa [Ideal.comap_map_of_bijective _ hbij] at h4

/-- **Analytification commutes with pushforward along closed immersions**: for a closed immersion
`i : Z ⟶ X` and any sheaf of `𝒪_Z`-modules `G`, the base change morphism
`(i_* G)^an ⟶ (i^an)_* (G^an)` is an isomorphism. -/
theorem isIso_analytificationPushforwardBaseChange
    (G : SheafOfModules.{u} Z.obj.left.toLocallyRingedSpace.ringSheaf) :
    IsIso (analytificationPushforwardBaseChange i G) := by
  have hε : IsIso (i.hom.left.toLRSHom.pullbackModulesAdj.counit.app G) :=
    i.hom.left.toLRSHom.isIso_pullbackModulesAdj_counit_app i.hom.left.isClosedEmbedding
      i.hom.left.stalkMap_surjective G
  have hη : IsIso ((analytification.map i).toLRSHom.pullbackModulesAdj.unit.app
      ((analytificationModules X).obj
        ((SheafOfModules.pushforward.{u} i.hom.left.toLRSHom.toRingSheafHom).obj G))) := by
    refine (analytification.map i).toLRSHom.isIso_pullbackModulesAdj_unit_app
      (isClosedEmbedding_analytification_map i) (surjective_stalkMap_analytification_map i) _
      (fun y hy ↦ ?_) (fun z r hr m ↦ ?_)
    · have hy' : (analytificationπLRS X).base y ∉ Set.range i.hom.left.base := fun h ↦
        hy (by rw [range_analytification_map_of_isClosedImmersion]; exact h)
      have hM := i.hom.left.toLRSHom.subsingleton_stalk_pushforward
        i.hom.left.isClosedEmbedding.isClosed_range _ hy' G
      let e := ((analytificationπLRS X).pullbackModulesStalkIso y).app
        ((SheafOfModules.pushforward.{u} i.hom.left.toLRSHom.toRingSheafHom).obj G)
      have he : Function.Injective e.hom := (ConcreteCategory.bijective_of_isIso e.hom).1
      have h := ModuleCat.subsingleton_extendScalars ((analytificationπLRS X).stalkMap y).hom _ hM
      exact ⟨fun a b ↦ he (@Subsingleton.elim _ h _ _)⟩
    · let e := ((analytificationπLRS X).pullbackModulesStalkIso
        ((analytification.map i).toLRSHom.base z)).app
        ((SheafOfModules.pushforward.{u} i.hom.left.toLRSHom.toRingSheafHom).obj G)
      have he : Function.Injective e.hom := (ConcreteCategory.bijective_of_isIso e.hom).1
      refine he ((map_smul e.hom.hom r m).trans ((ModuleCat.smul_extendScalars_eq_zero_of_mem_map
        _ _ _ (fun k hk m' ↦ i.hom.left.toLRSHom.smul_eq_zero_of_mem_pushforwardStalkIdeal G _ k
          hk m') r (ker_stalkMap_analytification_map_le i z hr) (e.hom m)).trans
        (map_zero e.hom.hom).symm))
  have h2 := Functor.map_isIso (analytificationπLRS Z).pullbackModules
    (i.hom.left.toLRSHom.pullbackModulesAdj.counit.app G)
  have h1 : IsIso ((LocallyRingedSpace.Hom.pullbackModulesCommSqIso
      (analytificationπLRS_naturality i)).hom.app
        ((SheafOfModules.pushforward.{u} i.hom.left.toLRSHom.toRingSheafHom).obj G) ≫
      (analytificationπLRS Z).pullbackModules.map
        (i.hom.left.toLRSHom.pullbackModulesAdj.counit.app G)) :=
    IsIso.comp_isIso' inferInstance h2
  have h3 := Functor.map_isIso
    (SheafOfModules.pushforward.{u} (analytification.map i).toLRSHom.toRingSheafHom)
    ((LocallyRingedSpace.Hom.pullbackModulesCommSqIso (analytificationπLRS_naturality i)).hom.app
        ((SheafOfModules.pushforward.{u} i.hom.left.toLRSHom.toRingSheafHom).obj G) ≫
      (analytificationπLRS Z).pullbackModules.map
        (i.hom.left.toLRSHom.pullbackModulesAdj.counit.app G))
  exact IsIso.comp_isIso' hη h3

end

end ComplexAnalytic
