/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.Analytification.GAGA.ClosedImmersionPushforward
import Oka.AnalyticSpace.ZeroLocusModules
import Oka.Geometry.RingedSpace.LocallyRingedSpace.CoherentPushforwardClosedEmbedding

/-!
# Pushforward of coherent analytic sheaves along analytified closed immersions

Let `i : Z ⟶ X` be a closed immersion of schemes locally of finite type over `ℂ`. For every
coherent sheaf of modules `M` on `Z^an`, the pushforward `(i^an)_* M` is a coherent sheaf on
`X^an` (`ComplexAnalytic.isCoherent_pushforward_analytification_map`).

This is `AlgebraicGeometry.LocallyRingedSpace.Hom.isCoherent_pushforward_of_isClosedEmbedding`:
`i^an` is a closed embedding with surjective stalk maps, and its ideal is locally finitely
generated (`ComplexAnalytic.hasLocallyFinitelyGeneratedIdeal_analytification_map`). Indeed, over
an affine open `U ⊆ X` with generators `h₁, …, h_p` of the ideal of `Z ∩ U`, the analytification
of `Z ∩ U ⟶ U` is cut out by the `π^♯ h_j` (`ComplexAnalytic.isCutOutBy_analytification_map`), so
at every point of `π⁻¹ U` the germs of the `π^♯ h_j` generate the ideal of `Z^an`
(`ComplexAnalytic.IsCutOutBy.pushforwardStalkIdeal_le`, transported along the open embedding
`(X|_U)^an ⟶ X^an`).
-/

open CategoryTheory Opposite AlgebraicGeometry TopologicalSpace Topology

universe u

namespace ComplexAnalytic

noncomputable section

variable {Z X : SchemeLFTℂ.{u}} (i : Z ⟶ X) [IsClosedImmersion i.hom.left]

/-- **The ideal of `Z^an` in `X^an` is locally finitely generated**: near a point over an affine
open `U ⊆ X` it is generated by the pullbacks `π^♯ h_j` of generators `h_j` of the ideal of
`Z ∩ U`. -/
theorem hasLocallyFinitelyGeneratedIdeal_analytification_map :
    (analytification.map i).toLRSHom.HasLocallyFinitelyGeneratedIdeal := by
  intro y
  obtain ⟨U, hU⟩ := exists_affineOpens_mem X.obj.left ((analytificationπLRS X).base y)
  haveI : IsAffine (X.restrict U.1).obj.left := inferInstanceAs (IsAffine U)
  obtain ⟨p, h, hh⟩ := exists_generators (restrictHomLFT i U.1)
  have hcut := isCutOutBy_analytification_map (restrictHomLFT i U.1) h hh
  let W₀ : X.obj.left.Opens := U.1.ι ''ᵁ ⊤
  let W : Opens (analytification.obj X) := (Opens.map (analytificationπLRS X).base).obj W₀
  let H : Fin p → (analytification.obj X).presheaf.obj (op W) :=
    fun j ↦ (analytificationπLRS X).c.app (op W₀) (h j)
  refine ⟨W, p, H, ⟨⟨_, hU⟩, trivial, rfl⟩, fun j ↦ ?_, fun y' hy' ↦ ?_⟩
  · have key : ∀ φ ψ : (analytification.obj Z).toLocallyRingedSpace ⟶
        X.obj.left.toLocallyRingedSpace, φ = ψ → ψ.c.app (op W₀) (h j) = 0 →
        φ.c.app (op W₀) (h j) = 0 := by
      rintro _ _ rfl h
      exact h
    refine key ((analytification.map i).toLRSHom ≫ analytificationπLRS X)
      (analytificationπLRS Z ≫ i.hom.left.toLRSHom) (analytificationπLRS_naturality i) ?_
    change (analytificationπLRS Z).c.app _ (i.hom.left.toLRSHom.c.app (op W₀) (h j)) = 0
    have h0 : i.hom.left.toLRSHom.c.app (op W₀) (h j) = 0 :=
      app_restrictι_image_top_eq_zero i U.1 (h j) (hh ▸ Ideal.subset_span ⟨j, rfl⟩)
    rw [h0]
    exact map_zero _
  -- transport along the open embedding `(X|_U)^an ⟶ X^an`
  have hy'' : y' ∈ Set.range (analytification.map (X.restrictι U.1)).toLRSHom.base := by
    rw [range_analytification_map_restrictι]
    obtain ⟨u, -, hu⟩ := hy'
    change (analytificationπLRS X).base y' ∈ U.1
    rw [← hu]
    exact u.2
  obtain ⟨x', rfl⟩ := hy''
  set jU := (analytification.map (X.restrictι U.1)).toLRSHom
  have hsq : (analytification.map (restrictHomLFT i U.1)).toLRSHom ≫ jU =
      (analytification.map (Z.restrictι (i.hom.left ⁻¹ᵁ U.1))).toLRSHom ≫
        (analytification.map i).toLRSHom :=
    congrArg AnalyticSpace.Hom.toLRSHom (analytification_map_restrictHomLFT_restrictι i U.1)
  have h1 := (analytification.map i).toLRSHom.map_pushforwardStalkIdeal_le hsq x'
  have h2 := hcut.pushforwardStalkIdeal_le x'
  have hbij := ConcreteCategory.bijective_of_isIso (jU.stalkMap x')
  have hV : (analytificationπLRS X).base (jU.base x') ∈ W₀ :=
    ⟨_, trivial, (analytificationπ_base_map (X.restrictι U.1) x').symm⟩
  have hgen : ∀ j, (analytification.obj (X.restrict U.1)).presheaf.Γgerm x'
      (analytificationSections h j) =
      jU.stalkMap x' ((analytification.obj X).presheaf.germ W (jU.base x') hy' (H j)) := by
    intro j
    rw [← stalkMap_restrictι_stalkMap_germ U.1 x' hV (h j)]
    congr 1
    exact LocallyRingedSpace.stalkMap_germ_apply (analytificationπLRS X) W₀ (jU.base x') hV
      (h j)
  have hspan : Ideal.span (Set.range fun j ↦ (analytification.obj (X.restrict U.1)).presheaf.Γgerm
      x' (analytificationSections h j)) = Ideal.map (jU.stalkMap x').hom
      (Ideal.span (Set.range fun j ↦
        (analytification.obj X).presheaf.germ W (jU.base x') hy' (H j))) := by
    rw [Ideal.map_span, ← Set.range_comp]
    exact congrArg Ideal.span (congrArg Set.range (funext hgen))
  intro r hr
  have h3 := h2 (h1 (Ideal.mem_map_of_mem _ hr))
  rw [hspan] at h3
  change r ∈ Ideal.comap (jU.stalkMap x').hom (Ideal.map (jU.stalkMap x').hom _) at h3
  rwa [Ideal.comap_map_of_bijective _ hbij] at h3

/-- **Pushforward along the analytification of a closed immersion preserves coherence**: for a
coherent sheaf of modules `M` on `Z^an`, `(i^an)_* M` is coherent on `X^an`. -/
theorem isCoherent_pushforward_analytification_map
    (M : SheafOfModules.{u} (analytification.obj Z).toLocallyRingedSpace.ringSheaf)
    [M.IsCoherent] :
    ((SheafOfModules.pushforward.{u}
      (analytification.map i).toLRSHom.toRingSheafHom).obj M).IsCoherent :=
  (analytification.map i).toLRSHom.isCoherent_pushforward_of_isClosedEmbedding M
    (isClosedEmbedding_analytification_map i) (surjective_stalkMap_analytification_map i)
    (hasLocallyFinitelyGeneratedIdeal_analytification_map i)

end

end ComplexAnalytic
