/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.AlgebraicGeometry.IdealSheaf.StalkIdeal
import Oka.Analytification.GAGA.ClosedImmersionPushforward

/-!
# The ideal of the analytification of a closed immersion

Let `i : Z ⟶ X` be a closed immersion of schemes locally of finite type over `ℂ`, with comparison
morphism `π : X^an ⟶ X`. At every point `x` of `X^an`, the kernel of
`𝒪_{X^an,x} → (i^an_* 𝒪_{Z^an})_x` is generated by the image of the kernel of
`𝒪_{X,π x} → (i_* 𝒪_Z)_{π x}` (`ComplexAnalytic.pushforwardStalkIdeal_analytification_map`).

We also package the closed subscheme `V(I)` of a quasi-coherent ideal sheaf `I` as a scheme
locally of finite type over `ℂ` (`ComplexAnalytic.SchemeLFTℂ.subscheme`), and deduce that the
ideal of `V(Iⁿ)^an` is stalkwise the `n`-th power of the ideal of `V(I)^an`
(`ComplexAnalytic.pushforwardStalkIdeal_analytification_map_subschemeι_pow`).
-/

open CategoryTheory AlgebraicGeometry TopologicalSpace

universe u

noncomputable section

namespace ComplexAnalytic

/-- **The ideal of the analytification of a closed immersion** at `x ∈ X^an` is generated by the
image of the ideal of the closed immersion at `π x`. -/
theorem pushforwardStalkIdeal_analytification_map {Z X : SchemeLFTℂ.{u}} (i : Z ⟶ X)
    [IsClosedImmersion i.hom.left] (x : analytification.obj X) :
    (analytification.map i).toLRSHom.pushforwardStalkIdeal x =
      Ideal.map ((analytificationπLRS X).stalkMap x).hom
        (i.hom.left.toLRSHom.pushforwardStalkIdeal ((analytificationπLRS X).base x)) := by
  refine le_antisymm ?_
    (LocallyRingedSpace.Hom.map_pushforwardStalkIdeal_le (f := i.hom.left.toLRSHom)
      (f' := (analytification.map i).toLRSHom) (g := analytificationπLRS X)
      (g' := analytificationπLRS Z)
      (analytificationπLRS_naturality i) x)
  by_cases hx : x ∈ Set.range (analytification.map i).toLRSHom.base
  · obtain ⟨z, rfl⟩ := hx
    rw [(analytification.map i).toLRSHom.pushforwardStalkIdeal_eq_ker
      (isClosedEmbedding_analytification_map i).isInducing z]
    exact ker_stalkMap_analytification_map_le i z
  · have hx' : (analytificationπLRS X).base x ∉ Set.range i.hom.left.toLRSHom.base := fun h ↦
      hx (by rw [range_analytification_map_of_isClosedImmersion]; exact h)
    rw [i.hom.left.toLRSHom.pushforwardStalkIdeal_eq_top i.hom.left.isClosedEmbedding.isClosed_range
      _ hx', Ideal.map_top]
    exact le_top

/-! ### Closed subschemes -/

variable (X : SchemeLFTℂ.{u}) (I : X.obj.left.IdealSheafData)

/-- **The closed subscheme `V(I)`** of a quasi-coherent ideal sheaf `I` on `X`, as a scheme locally
of finite type over `ℂ`. -/
def SchemeLFTℂ.subscheme : SchemeLFTℂ.{u} :=
  ⟨Over.mk (I.subschemeι ≫ X.obj.hom), by
    haveI : LocallyOfFiniteType X.obj.hom := X.property
    change LocallyOfFiniteType (I.subschemeι ≫ X.obj.hom)
    infer_instance⟩

/-- The inclusion of the closed subscheme `V(I)`. -/
def SchemeLFTℂ.subschemeι : X.subscheme I ⟶ X :=
  ObjectProperty.homMk (Over.homMk I.subschemeι rfl)

@[simp]
lemma SchemeLFTℂ.subschemeι_hom_left : (X.subschemeι I).hom.left = I.subschemeι :=
  rfl

/-- The inclusion of a closed subscheme is a closed immersion. -/
instance : IsClosedImmersion (X.subschemeι I).hom.left :=
  inferInstanceAs (IsClosedImmersion I.subschemeι)

/-- The image of the closed subscheme `V(I)` is the support of `I`. -/
lemma SchemeLFTℂ.range_subschemeι :
    Set.range (X.subschemeι I).hom.left.base = I.support :=
  Scheme.IdealSheafData.range_subschemeι I

/-- The ideal of `V(Iⁿ)^an` is stalkwise the `n`-th power of the ideal of `V(I)^an`. -/
theorem pushforwardStalkIdeal_analytification_map_subschemeι_pow (n : ℕ)
    (x : analytification.obj X) :
    (analytification.map (X.subschemeι (I ^ n))).toLRSHom.pushforwardStalkIdeal x =
      (analytification.map (X.subschemeι I)).toLRSHom.pushforwardStalkIdeal x ^ n := by
  rw [pushforwardStalkIdeal_analytification_map, pushforwardStalkIdeal_analytification_map,
    ← Ideal.map_pow]
  exact congrArg _ ((I.pushforwardStalkIdeal_subschemeι_pow n _))

end ComplexAnalytic

end
