/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.AlgebraicGeometry.ProjectiveSpace.HyperplaneIdeal
import Oka.Analytification.GAGA.ClosedImmersionPushforward
import Oka.Analytification.GAGA.ProjectiveSpaceTwistGAGA
import Oka.AnalyticSpace.PullbackCoherent

/-!
# Sheaves on `ℙⁿ⁺¹_an` killed by the equation of a hyperplane

Let `i : Z ⟶ X` be a closed immersion of schemes locally of finite type over `ℂ`. The stalk at
`y ∈ X^an` of the ideal of `Z^an` is generated by the stalk at `π y` of the ideal of `Z`
(`ComplexAnalytic.pushforwardStalkIdeal_analytification_map_eq`). For the hyperplane
`ι : ℙⁿ ⟶ ℙⁿ⁺¹`, `{Xₙ₊₁ = 0}`, and a point `y` with `π y` in the chart `U_l = D₊(X_l)`, it is
therefore the principal ideal generated by the germ `projectiveSpaceAn.hyperplaneGerm l y` of the
local equation `Xₙ₊₁ / X_l` (`ComplexAnalytic.projectiveSpaceAn.pushforwardStalkIdeal_eq`).

Consequently a sheaf of modules `A` on `ℙⁿ⁺¹_an` whose stalks are killed by these germs is the
pushforward of the sheaf `ι^* A` on `ℙⁿ_an`: the unit `A ⟶ ι_* ι^* A` is an isomorphism
(`ComplexAnalytic.projectiveSpaceAn.isIso_unit_hyperplane`), and conversely every pushforward is
killed by the germs (`ComplexAnalytic.projectiveSpaceAn.hyperplaneGerm_smul_pushforward`). For such
`A`, `Hᵠ(ℙⁿ⁺¹_an, A) ≃ Hᵠ(ℙⁿ_an, ι^* A)`
(`ComplexAnalytic.projectiveSpaceAn.hyperplaneHAddEquiv`), and `ι^* A` is coherent if `A` is
(`ComplexAnalytic.isCoherent_pullbackModules_of_isCoherent`).

No identification of `ℙⁿ_an` with a zero locus is needed: the analytified hyperplane is a closed
embedding with surjective stalk maps (`ComplexAnalytic.isClosedEmbedding_analytification_map`,
`ComplexAnalytic.surjective_stalkMap_analytification_map`), and the criterion
`AlgebraicGeometry.LocallyRingedSpace.Hom.isIso_pullbackModulesAdj_unit_app_iff` only involves
the stalks of its ideal.
-/

open CategoryTheory Opposite AlgebraicGeometry TopologicalSpace Topology

universe u

noncomputable section

namespace ComplexAnalytic

section ClosedImmersion

variable {Z X : SchemeLFTℂ.{u}} (i : Z ⟶ X)

/-- The stalk map of `π_X` carries the ideal of `Z` into the ideal of `Z^an`. -/
lemma map_pushforwardStalkIdeal_le_analytification_map (y : analytification.obj X) :
    Ideal.map ((analytificationπLRS X).stalkMap y).hom
        (i.hom.left.toLRSHom.pushforwardStalkIdeal ((analytificationπLRS X).base y)) ≤
      (analytification.map i).toLRSHom.pushforwardStalkIdeal y :=
  LocallyRingedSpace.Hom.map_pushforwardStalkIdeal_le _ (analytificationπLRS_naturality i) y

variable [IsClosedImmersion i.hom.left]

/-- **The ideal of `Z^an` is generated by the ideal of `Z`, stalkwise**: at every `y ∈ X^an`, the
kernel of `𝒪_{X^an,y} → (i^an_* 𝒪_{Z^an})_y` is generated by the image of the kernel of
`𝒪_{X,π y} → (i_* 𝒪_Z)_{π y}`. -/
theorem pushforwardStalkIdeal_analytification_map_eq (y : analytification.obj X) :
    (analytification.map i).toLRSHom.pushforwardStalkIdeal y =
      Ideal.map ((analytificationπLRS X).stalkMap y).hom
        (i.hom.left.toLRSHom.pushforwardStalkIdeal ((analytificationπLRS X).base y)) := by
  refine le_antisymm ?_ (map_pushforwardStalkIdeal_le_analytification_map i y)
  by_cases hy : y ∈ Set.range (analytification.map i).toLRSHom.base
  · obtain ⟨z, rfl⟩ := hy
    rw [LocallyRingedSpace.Hom.pushforwardStalkIdeal_eq_ker _
      (isClosedEmbedding_analytification_map i).isInducing z]
    exact ker_stalkMap_analytification_map_le i z
  · have hy' : (analytificationπLRS X).base y ∉ Set.range i.hom.left.toLRSHom.base := fun h ↦
      hy (by rw [range_analytification_map_of_isClosedImmersion]; exact h)
    rw [LocallyRingedSpace.Hom.pushforwardStalkIdeal_eq_top _
      i.hom.left.isClosedEmbedding.isClosed_range _ hy', Ideal.map_top]
    exact le_top

end ClosedImmersion

namespace projectiveSpaceAn

variable {n : ℕ}

/-- The comparison morphism `ℙⁿ_an ⟶ ℙⁿ` as a morphism of locally ringed spaces. -/
abbrev πLRS (n : ℕ) :
    (projectiveSpaceAn.{u} n).toLocallyRingedSpace ⟶ ℙ(n; ULift.{u} ℂ).toLocallyRingedSpace :=
  analytificationπLRS (projectiveSpace.{u} n)

/-- The analytified hyperplane `ι^an : ℙⁿ_an ⟶ ℙⁿ⁺¹_an`, `{Xₙ₊₁ = 0}`, as a morphism of locally
ringed spaces. -/
abbrev hyperplaneLRS (n : ℕ) :
    (projectiveSpaceAn.{u} n).toLocallyRingedSpace ⟶
      (projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace :=
  (analytification.map (projectiveSpaceHyperplane.{u} n)).toLRSHom

/-- **The germ of the local equation of the hyperplane**: for `y ∈ ℙⁿ⁺¹_an` over the chart
`U_l = D₊(X_l)`, the germ at `y` of the holomorphic function `Xₙ₊₁ / X_l`. -/
def hyperplaneGerm (l : Fin (n + 1 + 1)) (y : projectiveSpaceAn.{u} (n + 1))
    (hy : (πLRS (n + 1)).base y ∈ ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l) :
    (projectiveSpaceAn.{u} (n + 1)).presheaf.stalk y :=
  (πLRS (n + 1)).stalkMap y
    (ℙ(n + 1; ULift.{u} ℂ).presheaf.germ _ _ hy (ProjectiveSpace.xDiv l (Fin.last _)))

/-- The germ of the local equation is the germ of the pulled-back section `π^♯ (Xₙ₊₁ / X_l)` over
`π⁻¹ U_l`. -/
lemma hyperplaneGerm_eq (l : Fin (n + 1 + 1)) (y : projectiveSpaceAn.{u} (n + 1))
    (hy : (πLRS (n + 1)).base y ∈ ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l) :
    hyperplaneGerm l y hy = (projectiveSpaceAn.{u} (n + 1)).presheaf.germ
      ((Opens.map (πLRS (n + 1)).base).obj (ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l)) y hy
      ((πLRS (n + 1)).c.app (op (ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l))
        (ProjectiveSpace.xDiv l (Fin.last _))) :=
  LocallyRingedSpace.stalkMap_germ_apply _ _ _ _ _

/-- **A criterion on sections**: if `π^♯ (Xₙ₊₁ / X_l)` acts by zero on all sections of `A` over
opens inside `π⁻¹ U_l`, its germ kills the stalks of `A` there. -/
lemma hyperplaneGerm_smul_eq_zero_of_forall
    (A : SheafOfModules.{u} (projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.ringSheaf)
    (l : Fin (n + 1 + 1))
    (hA : ∀ (V : Opens (projectiveSpaceAn.{u} (n + 1)))
      (hV : V ≤ (Opens.map (πLRS (n + 1)).base).obj (ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l))
      (t : A.val.obj (op V)),
      (show (projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.ringSheaf.obj.obj (op V) from
        (projectiveSpaceAn.{u} (n + 1)).presheaf.map (homOfLE hV).op
          ((πLRS (n + 1)).c.app (op (ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l))
            (ProjectiveSpace.xDiv l (Fin.last _)))) • t = 0)
    (y : projectiveSpaceAn.{u} (n + 1))
    (hy : (πLRS (n + 1)).base y ∈ ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l)
    (m : ((projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.stalkFunctor y).obj A) :
    hyperplaneGerm l y hy • m = 0 := by
  rw [hyperplaneGerm_eq]
  exact LocallyRingedSpace.germ_smul_eq_zero_of_forall A _ hA y hy m

/-- Every point of `ℙⁿ⁺¹_an` lies over some chart `U_l`. -/
lemma exists_mem_U (y : projectiveSpaceAn.{u} (n + 1)) :
    ∃ l, (πLRS (n + 1)).base y ∈ ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l :=
  Opens.mem_iSup.1 (by rw [ProjectiveSpace.iSup_U]; trivial)

/-- **The ideal of the hyperplane in `ℙⁿ⁺¹_an` is locally principal**: at a point `y` over the
chart `U_l`, the stalk of the ideal of `ℙⁿ_an` is generated by the germ of `Xₙ₊₁ / X_l`. -/
theorem pushforwardStalkIdeal_eq (l : Fin (n + 1 + 1)) (y : projectiveSpaceAn.{u} (n + 1))
    (hy : (πLRS (n + 1)).base y ∈ ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l) :
    (hyperplaneLRS.{u} n).pushforwardStalkIdeal y = Ideal.span {hyperplaneGerm l y hy} := by
  rw [hyperplaneLRS, pushforwardStalkIdeal_analytification_map_eq]
  change Ideal.map ((πLRS (n + 1)).stalkMap y).hom
    ((ProjectiveSpace.hyperplane n (ULift.{u} ℂ)).toLRSHom.pushforwardStalkIdeal _) = _
  rw [ProjectiveSpace.pushforwardStalkIdeal_hyperplane_eq l _ hy, Ideal.map_span,
    Set.image_singleton]
  rfl

/-- The germ of the local equation lies in the ideal of the hyperplane. -/
lemma hyperplaneGerm_mem (l : Fin (n + 1 + 1)) (y : projectiveSpaceAn.{u} (n + 1))
    (hy : (πLRS (n + 1)).base y ∈ ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l) :
    hyperplaneGerm l y hy ∈ (hyperplaneLRS.{u} n).pushforwardStalkIdeal y := by
  rw [pushforwardStalkIdeal_eq l y hy]
  exact Ideal.subset_span rfl

/-- The analytified hyperplane is a closed embedding. -/
lemma isClosedEmbedding_hyperplaneLRS : IsClosedEmbedding (hyperplaneLRS.{u} n).base :=
  isClosedEmbedding_analytification_map _

/-- The stalk maps of the analytified hyperplane are surjective. -/
lemma surjective_stalkMap_hyperplaneLRS (z : projectiveSpaceAn.{u} n) :
    Function.Surjective ((hyperplaneLRS.{u} n).stalkMap z) :=
  surjective_stalkMap_analytification_map _ z

variable (A : SheafOfModules.{u} (projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.ringSheaf)

/-- Stalks killed by the germs of the local equations are killed by the ideal of the
hyperplane. -/
lemma smul_eq_zero_of_mem_pushforwardStalkIdeal
    (hA : ∀ (l : Fin (n + 1 + 1)) (y : projectiveSpaceAn.{u} (n + 1))
      (hy : (πLRS (n + 1)).base y ∈ ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l)
      (m : ((projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.stalkFunctor y).obj A),
      hyperplaneGerm l y hy • m = 0)
    (y : projectiveSpaceAn.{u} (n + 1)) (r) (hr : r ∈ (hyperplaneLRS.{u} n).pushforwardStalkIdeal y)
    (m : ((projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.stalkFunctor y).obj A) :
    r • m = 0 := by
  obtain ⟨l, hl⟩ := exists_mem_U y
  rw [pushforwardStalkIdeal_eq l y hl] at hr
  obtain ⟨a, rfl⟩ := Ideal.mem_span_singleton'.1 hr
  rw [mul_smul, hA l y hl m, smul_zero]

/-- **Sheaves killed by the equation of the hyperplane come from the hyperplane**: if at every
`y` over a chart `U_l` the germ of `Xₙ₊₁ / X_l` kills `A_y`, the unit `A ⟶ ι_* ι^* A` of the
analytified hyperplane `ι : ℙⁿ_an ⟶ ℙⁿ⁺¹_an` is an isomorphism. -/
theorem isIso_unit_hyperplane
    (hA : ∀ (l : Fin (n + 1 + 1)) (y : projectiveSpaceAn.{u} (n + 1))
      (hy : (πLRS (n + 1)).base y ∈ ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l)
      (m : ((projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.stalkFunctor y).obj A),
      hyperplaneGerm l y hy • m = 0) :
    IsIso ((hyperplaneLRS.{u} n).pullbackModulesAdj.unit.app A) :=
  (hyperplaneLRS.{u} n).isIso_pullbackModulesAdj_unit_app_of_smul_eq_zero
    isClosedEmbedding_hyperplaneLRS surjective_stalkMap_hyperplaneLRS A
    (smul_eq_zero_of_mem_pushforwardStalkIdeal A hA)

/-- The isomorphism `A ≅ ι_* ι^* A` for a sheaf `A` killed by the equation of the hyperplane. -/
def hyperplaneUnitIso
    (hA : ∀ (l : Fin (n + 1 + 1)) (y : projectiveSpaceAn.{u} (n + 1))
      (hy : (πLRS (n + 1)).base y ∈ ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l)
      (m : ((projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.stalkFunctor y).obj A),
      hyperplaneGerm l y hy • m = 0) :
    A ≅ (SheafOfModules.pushforward.{u} (hyperplaneLRS.{u} n).toRingSheafHom).obj
      ((hyperplaneLRS.{u} n).pullbackModules.obj A) :=
  (hyperplaneLRS.{u} n).unitIsoOfSMulEqZero isClosedEmbedding_hyperplaneLRS
    surjective_stalkMap_hyperplaneLRS A (smul_eq_zero_of_mem_pushforwardStalkIdeal A hA)

/-- For a sheaf `A` on `ℙⁿ⁺¹_an` killed by the equation of the hyperplane,
`Hᵠ(ℙⁿ⁺¹_an, A) ≃ Hᵠ(ℙⁿ_an, ι^* A)`. -/
def hyperplaneHAddEquiv
    (hA : ∀ (l : Fin (n + 1 + 1)) (y : projectiveSpaceAn.{u} (n + 1))
      (hy : (πLRS (n + 1)).base y ∈ ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l)
      (m : ((projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.stalkFunctor y).obj A),
      hyperplaneGerm l y hy • m = 0) (q : ℕ) :
    LocallyRingedSpace.H A q ≃+
      LocallyRingedSpace.H ((hyperplaneLRS.{u} n).pullbackModules.obj A) q :=
  (hyperplaneLRS.{u} n).HAddEquivOfSMulEqZero isClosedEmbedding_hyperplaneLRS
    surjective_stalkMap_hyperplaneLRS A (smul_eq_zero_of_mem_pushforwardStalkIdeal A hA) q

/-- The pullback of a coherent sheaf on `ℙⁿ⁺¹_an` to the hyperplane `ℙⁿ_an` is coherent. -/
theorem isCoherent_pullbackModules_hyperplane [A.IsCoherent] :
    ((hyperplaneLRS.{u} n).pullbackModules.obj A).IsCoherent :=
  isCoherent_pullbackModules_of_isCoherent (Z := projectiveSpaceAn.{u} n) _ A

/-- Conversely, the germs of the local equations kill every pushforward from the hyperplane. -/
lemma hyperplaneGerm_smul_pushforward
    (G : SheafOfModules.{u} (projectiveSpaceAn.{u} n).toLocallyRingedSpace.ringSheaf)
    (l : Fin (n + 1 + 1)) (y : projectiveSpaceAn.{u} (n + 1))
    (hy : (πLRS (n + 1)).base y ∈ ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l)
    (m : ((projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.stalkFunctor y).obj
      ((SheafOfModules.pushforward.{u} (hyperplaneLRS.{u} n).toRingSheafHom).obj G)) :
    hyperplaneGerm l y hy • m = 0 :=
  (hyperplaneLRS.{u} n).smul_eq_zero_of_mem_pushforwardStalkIdeal G y _
    (hyperplaneGerm_mem l y hy) m

end projectiveSpaceAn

end ComplexAnalytic
