/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.Analytification.GAGA.ProjectiveSpaceAnTheoremA
import Oka.AnalyticSpace.PullbackCoherent

/-!
# GAGA-3 on `ℙⁿ`: every coherent analytic sheaf is algebraic

We assemble Serre's proof of GAGA-3 on `ℙⁿ` by induction on `n`:

- `n = 0`: `ℙ⁰_an` is a point, and a coherent sheaf on it is generated by finitely many global
  sections (`ComplexAnalytic.projectiveSpaceAn.coherentIsAlgebraic_zero`).
- `n → n + 1`: by Serre's argument (`isAlgGeneratedAt_of_mem_range_hyperplane`), a coherent sheaf
  on `ℙⁿ⁺¹_an` is algebraically generated at the points of the hyperplane `ℙⁿ_an`. Along an
  automorphism `g` of `ℙⁿ⁺¹` algebraic generation is transported from `z` to `g^an z`
  (`isAlgGeneratedAt_of_iso`); if the translates of the hyperplane under automorphisms cover
  `ℙⁿ⁺¹_an` (`HyperplaneTranslatesCover`), every coherent sheaf is algebraically generated at every
  point, hence algebraic (`exists_iso_of_forall_isAlgGeneratedAt`).

The two inputs are explicit hypotheses of
`ComplexAnalytic.projectiveSpaceAn.gaga₃_of_hyperplaneTranslatesCover`: finite-dimensionality of
`H¹` of coherent sheaves (Cartan–Serre) and the covering property of the translates of the
hyperplane; the latter is proved in
`Oka/Analytification/GAGA/ProjectiveSpaceAnHyperplaneCover.lean`.
-/

open CategoryTheory Limits TopologicalSpace Opposite AlgebraicGeometry
open AlgebraicGeometry.LocallyRingedSpace

universe u

noncomputable section

namespace ComplexAnalytic.projectiveSpaceAn

/-! ### The case `n = 0` -/

/-- `ℙ⁰_an` is a point. -/
instance subsingleton_projectiveSpaceAn_zero : Subsingleton (projectiveSpaceAn.{u} 0) := by
  refine ⟨fun x x' ↦ ?_⟩
  obtain ⟨i, z, rfl⟩ := exists_mem_range_chart x
  obtain ⟨i', z', rfl⟩ := exists_mem_range_chart x'
  obtain rfl : i = i' := Subsingleton.elim (α := Fin 1) _ _
  obtain rfl : z = z' := funext fun k ↦ k.down.elim0
  rfl

/-- **GAGA-3 on `ℙ⁰`**: `ℙ⁰_an` is a point, so every coherent sheaf on it is generated by finitely
many global sections at the point. -/
theorem coherentIsAlgebraic_zero : CoherentIsAlgebraic.{u} 0 := by
  refine exists_iso_of_forall_isAlgGeneratedAt fun M hM y ↦ ?_
  haveI := hM
  haveI : Subsingleton (projectiveSpaceAn.{u} 0).toLocallyRingedSpace :=
    subsingleton_projectiveSpaceAn_zero
  obtain ⟨J, hJ, σ, hσ⟩ := exists_surjective_stalk_of_subsingleton M y
  haveI : IsLocallyNoetherian ℙ(0; ULift.{u} ℂ) :=
    haveI : IsNoetherianRing (ULift.{u} ℂ) :=
      isNoetherianRing_of_ringEquiv ℂ ULift.ringEquiv.symm
    LocallyOfFiniteType.isLocallyNoetherian (ProjectiveSpace.toSpec 0 (ULift.{u} ℂ))
  refine ⟨SheafOfModules.free J, Scheme.isCoherent_free (X := ℙ(0; ULift.{u} ℂ)) J,
    ((πLRS 0).pullbackModulesFreeIso J).hom ≫ σ, ?_⟩
  exact (surjective_stalk_iso_comp_iff ((πLRS 0).pullbackModulesFreeIso J) σ y).2 hσ

/-! ### Transport along automorphisms -/

section Transport

variable {N : ℕ} (g : projectiveSpace.{u} N ≅ projectiveSpace.{u} N)

/-- The analytification of an automorphism of `ℙᴺ`, as a morphism of locally ringed spaces. -/
abbrev autAn : (projectiveSpaceAn.{u} N).toLocallyRingedSpace ⟶
    (projectiveSpaceAn.{u} N).toLocallyRingedSpace :=
  (analytification.map g.hom).toLRSHom

lemma autAn_inv_base_autAn_base (x : projectiveSpaceAn.{u} N) :
    (autAn g.symm).base ((autAn g).base x) = x := by
  exact congrArg (fun φ ↦ φ.toLRSHom.base x) (analytification.mapIso g).hom_inv_id

/-- The analytification of an automorphism is an isomorphism. -/
instance : IsIso (autAn g) :=
  (AnalyticSpace.forgetToLocallyRingedSpace.mapIso (analytification.mapIso g)).isIso_hom

/-- An automorphism of `ℙᴺ` is a closed immersion. -/
instance : IsClosedImmersion g.hom.hom.left :=
  haveI : IsIso g.hom.hom.left :=
    ((ObjectProperty.ι _ ⋙ Over.forget _).mapIso g).isIso_hom
  inferInstance

/-- `M ≅ a_* a^* M` for the analytification `a` of an automorphism. -/
def autAnUnitIso (M : SheafOfModules.{u} (projectiveSpaceAn.{u} N).toLocallyRingedSpace.ringSheaf) :
    M ≅ (SheafOfModules.pushforward.{u} (autAn g).toRingSheafHom).obj
      ((autAn g).pullbackModules.obj M) :=
  (autAn g).unitIsoOfSMulEqZero (isClosedEmbedding_analytification_map g.hom)
    (surjective_stalkMap_analytification_map g.hom) M fun y r hr m ↦ by
      obtain ⟨x, rfl⟩ : ∃ x, (autAn g).base x = y :=
        ⟨(autAn g.symm).base y, autAn_inv_base_autAn_base g.symm y⟩
      rw [(autAn g).pushforwardStalkIdeal_eq_ker
        (isClosedEmbedding_analytification_map g.hom).isInducing x, RingHom.mem_ker] at hr
      have hr0 : r = 0 := ((ConcreteCategory.bijective_of_isIso ((autAn g).stalkMap x)).1
        (hr.trans (map_zero _).symm))
      rw [hr0, zero_smul]

/-- **Transport of algebraic generation along automorphisms**: if `a^* M` is algebraically
generated at `z`, where `a` is the analytification of an automorphism `g` of `ℙᴺ`, then `M` is
algebraically generated at `a z`. -/
theorem isAlgGeneratedAt_of_iso
    (M : SheafOfModules.{u} (projectiveSpaceAn.{u} N).toLocallyRingedSpace.ringSheaf)
    (z : projectiveSpaceAn.{u} N) (h : IsAlgGeneratedAt ((autAn g).pullbackModules.obj M) z) :
    IsAlgGeneratedAt M ((autAn g).base z) := by
  obtain ⟨F, hF, f, hf⟩ := h
  haveI := hF
  haveI : IsLocallyNoetherian (projectiveSpace.{u} N).obj.left :=
    LocallyOfFiniteType.isLocallyNoetherian (projectiveSpace.{u} N).obj.hom
  haveI := isIso_analytificationPushforwardBaseChange g.hom F
  have key := surjective_stalk_pushforward (autAn g) (autAn g.symm) (autAn_inv_base_autAn_base g)
    (autAn_inv_base_autAn_base g.symm) f z hf
  exact ⟨_, isCoherent_pushforward_of_isClosedImmersion g.hom.hom.left F, _,
    (surjective_stalk_iso_comp_iff (asIso (analytificationPushforwardBaseChange g.hom F)) _ _).2
      ((surjective_stalk_comp_iso_iff _ (autAnUnitIso g M).symm _).2 key)⟩

end Transport

/-! ### The induction -/

variable (n : ℕ) in
/-- **The translates of the hyperplane cover `ℙⁿ⁺¹_an`**: every point of `ℙⁿ⁺¹_an` is the image of
a point of the hyperplane `ℙⁿ_an` under the analytification of an automorphism of `ℙⁿ⁺¹`. -/
def HyperplaneTranslatesCover : Prop :=
  ∀ y : projectiveSpaceAn.{u} (n + 1), ∃ (g : projectiveSpace.{u} (n + 1) ≅
    projectiveSpace.{u} (n + 1)) (z : projectiveSpaceAn.{u} (n + 1)),
      z ∈ Set.range (hyperplaneLRS.{u} n).base ∧ (autAn g).base z = y

/-- **The induction step**: GAGA-3 on `ℙⁿ` implies GAGA-3 on `ℙⁿ⁺¹`, given finite-dimensionality
of `H¹` of coherent sheaves on `ℙⁿ⁺¹_an` and the covering property of the translates of the
hyperplane. -/
theorem coherentIsAlgebraic_succ {n : ℕ} (hP : CoherentIsAlgebraic.{u} n)
    (hFin : ∀ M : SheafOfModules.{u} (projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.ringSheaf,
      M.IsCoherent → FiniteDimensional ℂ (H M 1))
    (hCover : HyperplaneTranslatesCover.{u} n) : CoherentIsAlgebraic.{u} (n + 1) := by
  refine exists_iso_of_forall_isAlgGeneratedAt fun M hM y ↦ ?_
  haveI := hM
  obtain ⟨g, z, hz, rfl⟩ := hCover y
  haveI := isCoherent_pullbackModules_of_isCoherent (Z := projectiveSpaceAn.{u} (n + 1))
    (autAn g) M
  exact isAlgGeneratedAt_of_iso g M z (isAlgGeneratedAt_of_mem_range_hyperplane hP hFin _ z hz)

/-- **Serre's GAGA-3 on `ℙⁿ`**: every coherent analytic sheaf on `ℙⁿ_an` is isomorphic to the
analytification of a coherent algebraic sheaf on `ℙⁿ`, given

- (Cartan–Serre) `H¹(ℙⁿ_an, M)` is finite-dimensional for every coherent analytic `M`, and
- the translates of the hyperplane `ℙⁿ_an ⊆ ℙⁿ⁺¹_an` under automorphisms of `ℙⁿ⁺¹` cover
  `ℙⁿ⁺¹_an`. -/
theorem gaga₃_of_hyperplaneTranslatesCover
    (hFin : ∀ (n : ℕ)
      (M : SheafOfModules.{u} (projectiveSpaceAn.{u} n).toLocallyRingedSpace.ringSheaf),
      M.IsCoherent → FiniteDimensional ℂ (H M 1))
    (hCover : ∀ n, HyperplaneTranslatesCover.{u} n) (n : ℕ)
    (M : SheafOfModules.{u} (projectiveSpaceAn.{u} n).toLocallyRingedSpace.ringSheaf)
    (hM : M.IsCoherent) :
    ∃ F : SheafOfModules.{u} (projectiveSpace.{u} n).obj.left.toLocallyRingedSpace.ringSheaf,
      F.IsCoherent ∧ Nonempty ((analytificationModules (projectiveSpace.{u} n)).obj F ≅ M) := by
  induction n with
  | zero => exact coherentIsAlgebraic_zero M hM
  | succ n ih => exact coherentIsAlgebraic_succ (fun N hN ↦ ih N hN) (hFin (n + 1)) (hCover n) M hM

end ComplexAnalytic.projectiveSpaceAn
