/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.Analytification.GAGA.ProjectiveLineCoherentVanishing
import Oka.Analytification.GAGA.Proper.RelativeSerreAn

/-!
# Relative Theorem A on `U × ℙ¹`

Let `𝒢` be a coherent sheaf on `U × ℙ¹ ⊆ P^an` and `K ⊆ U` a closed box. We show that there are
an open box `B₁ ⊇ K` and `n₀` such that for `n ≥ n₀` the sections of `𝒢(n)` over `B₁ × ℙ¹`
generate `𝒢(n)` near every point of `B₁ × ℙ¹`
(`ComplexAnalytic.relProjectiveLine.exists_generates_twistMod`): the map `π^* π_* 𝒢(n) → 𝒢(n)`
is surjective over `B₁`.

Let `x₀` be a point of the chart `0` with fibre coordinate `c`, `‖c‖ ≤ 1`. We write `𝒢` as a
quotient of the vector bundle `E` of `ComplexAnalytic.relProjectiveLine.BundleData`, generated by
`s` near the chart box at `0`, and split `sⱼ / (z - c)` on an annulus `{4/3 < ‖z‖ < 3}`
avoiding `c` (`ComplexAnalytic.relProjectiveLine.BundleData.exists_split`). Multiplying by the
section `z - c` of `𝒪(1)` gives sections `Σⱼ` of `𝒢(n)` over `B₁ × ℙ¹` with `Σⱼ = sⱼ - (z - c) Φⱼ`
near `x₀`, where `Φⱼ` is an explicit combination of the `s`. The matrix expressing the `Σⱼ` in
terms of the `sⱼ` is the identity at `x₀`, hence invertible near `x₀`, so the `Σⱼ` generate `𝒢(n)`
near `x₀` (`ComplexAnalytic.relProjectiveLine.exists_generates_of_matrix`). Points of the chart
`1` are treated in the same way with the generators `t`, the section `w - c` and the annulus
`{1/3 < ‖z‖ < 3/4}`.
-/

open CategoryTheory Opposite TopologicalSpace AlgebraicGeometry
open AlgebraicGeometry.LocallyRingedSpace

universe u

noncomputable section

namespace ComplexAnalytic.relProjectiveLine

open relProjectiveSpaceAn Complex.ProjectiveLineBundle Matrix

variable {m : ℕ}

set_option hygiene false in
/-- Sections of `𝒪` over an open of `P^an`. -/
local notation "Γₚ(" W ")" => (relProjectiveSpaceAn.{u} m 1).presheaf.obj (op W)

/-! ### Small chart boxes -/

lemma exists_rect_subset {z : ℂ} {ε : ℝ} (hε : 0 < ε) :
    ∃ c d : ℂ, z ∈ rectOpens c d ∧ (rectOpens c d : Set ℂ) ⊆ Metric.ball z ε := by
  set δ : ℝ := ε / 4
  have hδ : 0 < δ := by positivity
  refine ⟨z - (δ + δ * Complex.I), z + (δ + δ * Complex.I), ?_, fun w hw ↦ ?_⟩
  · simp only [mem_rectOpens, Complex.mem_reProdIm, Set.mem_Ioo, Complex.sub_re,
      Complex.add_re, Complex.ofReal_re, Complex.mul_re, Complex.I_re, Complex.ofReal_im,
      Complex.I_im, Complex.sub_im, Complex.add_im, Complex.mul_im]
    constructor <;> constructor <;> linarith
  · simp only [SetLike.mem_coe, mem_rectOpens, Complex.mem_reProdIm, Set.mem_Ioo,
      Complex.sub_re, Complex.add_re, Complex.ofReal_re, Complex.mul_re, Complex.I_re,
      Complex.ofReal_im, Complex.I_im, Complex.sub_im, Complex.add_im, Complex.mul_im] at hw
    rw [Metric.mem_ball, dist_eq_norm]
    refine (Complex.norm_le_abs_re_add_abs_im _).trans_lt ?_
    simp only [Complex.sub_re, Complex.sub_im]
    have h1 : |w.re - z.re| < 2 * δ := abs_lt.2 ⟨by linarith, by linarith⟩
    have h2 : |w.im - z.im| < 2 * δ := abs_lt.2 ⟨by linarith, by linarith⟩
    have hδε : δ = ε / 4 := rfl
    linarith

/-- **The chart boxes over boxes form a neighbourhood basis** of every point of the chart `i`. -/
lemma exists_chartBox_subset (i : Fin 2) {W : (relProjectiveSpaceAn.{u} m 1).Opens}
    {p : (Fin m → ℂ) × ℂ} (hp : chartPt.{u} i p ∈ W) :
    ∃ (a b : Fin m → ℂ) (c d : ℂ), chartPt.{u} i p ∈ chartBox.{u} i
      (prodOpens (boxOpens a b) (rectOpens c d)) ∧
      chartBox.{u} i (prodOpens (boxOpens a b) (rectOpens c d)) ≤ W := by
  have hS : IsOpen (chartPt.{u} i ⁻¹' (W : Set (relProjectiveSpaceAn.{u} m 1))) :=
    W.isOpen.preimage (isOpenEmbedding_chartPt i).continuous
  obtain ⟨ε, hε, hball⟩ := Metric.isOpen_iff.1 hS p hp
  obtain ⟨a, b, hab, habε⟩ := exists_openBox_subset (m := m) Metric.isOpen_ball
    (Metric.mem_ball_self hε) (z := p.1)
  obtain ⟨c, d, hcd, hcdε⟩ := exists_rect_subset (z := p.2) hε
  refine ⟨a, b, c, d, ⟨p, ⟨hab, hcd⟩, rfl⟩, ?_⟩
  rintro _ ⟨q, ⟨hq1, hq2⟩, rfl⟩
  refine hball ?_
  rw [Metric.mem_ball, Prod.dist_eq, max_lt_iff]
  exact ⟨habε hq1, hcdε hq2⟩

/-! ### Generators from a matrix which is the identity at a point -/

/-- A section of `𝒪` which does not vanish at `x` is invertible near `x`. -/
lemma exists_isUnit_restrictOpen {W : (relProjectiveSpaceAn.{u} m 1).Opens} (a : Γₚ(W))
    {x : relProjectiveSpaceAn.{u} m 1} (hx : x ∈ W)
    (ha : (relProjectiveSpaceAn.{u} m 1).eval x hx a ≠ 0) :
    ∃ (V : (relProjectiveSpaceAn.{u} m 1).Opens) (h : V ≤ W), x ∈ V ∧
      IsUnit (TopCat.Presheaf.restrictOpen a V h) := by
  have hu : IsUnit ((relProjectiveSpaceAn.{u} m 1).presheaf.germ W x hx a) :=
    (AnalyticSpace.evalStalk_ne_zero_iff_isUnit _).1 ha
  obtain ⟨V, i, hxV, hV⟩ := RingedSpace.isUnit_res_of_isUnit_germ
    (X := (relProjectiveSpaceAn.{u} m 1).toLocallyRingedSpace.toRingedSpace) W a x hx hu
  exact ⟨V, i.le, hxV, hV⟩

lemma exists_chartPt_of_mem_stdOpen {i : Fin 2} {x : relProjectiveSpaceAn.{u} m 1}
    (hx : x ∈ stdOpen.{u} m 1 i) : ∃ p, chartPt.{u} i p = x := by
  rw [stdOpen_eq_chartOpens] at hx
  obtain ⟨w, rfl⟩ := hx
  exact ⟨(yPart w, zPart w 0), by rw [chartPt, cpt_yPart_zPart]⟩

variable (𝒢 : SheafOfModules.{u} (relProjectiveSpaceAn.{u} m 1).toLocallyRingedSpace.ringSheaf)

/-- **Generators from a matrix which is the identity at a point.** Let `g` be acyclic generating
sections of `𝒢` over `N`, `D ≤ N` inside the chart `i`, and `T` a square matrix of sections of
`𝒪` over `D` with `T(x₀) = 1`. Then the sections `Aⱼ = ∑ᵢ Tⱼᵢ gᵢ` generate `𝒢` near `x₀`. -/
theorem exists_generates_of_matrix {i : Fin 2} {N D : (relProjectiveSpaceAn.{u} m 1).Opens}
    {I : Type u} [Fintype I] [DecidableEq I] (g : I → 𝒢.val.obj (op N))
    (hg : IsAcyclicGenerating 𝒢 g) (hDN : D ≤ N) (hDi : D ≤ stdOpen.{u} m 1 i)
    (T : Matrix I I Γₚ(D)) {x₀ : relProjectiveSpaceAn.{u} m 1} (hx₀ : x₀ ∈ D)
    (hT : ∀ j j', (relProjectiveSpaceAn.{u} m 1).eval x₀ hx₀ (T j j') = if j = j' then 1 else 0) :
    ∃ (W : (relProjectiveSpaceAn.{u} m 1).Opens) (hWD : W ≤ D), x₀ ∈ W ∧
      ∀ (W' : (relProjectiveSpaceAn.{u} m 1).Opens) (hW' : W' ≤ W) (σ : 𝒢.val.obj (op W'))
        (x : relProjectiveSpaceAn.{u} m 1), x ∈ W' →
        ∃ (W'' : (relProjectiveSpaceAn.{u} m 1).Opens) (h : W'' ≤ W'), x ∈ W'' ∧
          ∃ c : I → Γₚ(W''), modRes σ W'' h =
            ∑ j, c j • modRes (∑ i', T j i' • modRes (g i') D hDN) W''
              (h.trans (hW'.trans hWD)) := by
  classical
  set φ := (relProjectiveSpaceAn.{u} m 1).eval x₀ hx₀
  have hTφ : φ.mapMatrix T = 1 := by
    ext j j'
    rw [RingHom.mapMatrix_apply, map_apply, hT, one_apply]
  obtain ⟨W, hWD, hx₀W, hu⟩ := exists_isUnit_restrictOpen T.det hx₀ (by
    rw [RingHom.map_det, hTφ, det_one]
    exact one_ne_zero)
  let res : Γₚ(D) →+* Γₚ(W) := ((relProjectiveSpaceAn.{u} m 1).presheaf.map (homOfLE hWD).op).hom
  set TW := res.mapMatrix T
  have hTW : IsUnit TW := by
    have e : TW.det = res T.det := (RingHom.map_det res T).symm
    rw [isUnit_iff_isUnit_det, e]
    exact hu
  set Tinv := TW⁻¹
  have hinv : Tinv * TW = 1 := nonsing_inv_mul TW ((isUnit_iff_isUnit_det TW).1 hTW)
  -- `gᵢ = ∑ⱼ (T⁻¹)ᵢⱼ Aⱼ` on `W`
  have hgW : ∀ i', modRes (g i') W (hWD.trans hDN) =
      ∑ j, Tinv i' j • modRes (∑ i'', T j i'' • modRes (g i'') D hDN) W hWD := by
    intro i'
    simp only [modRes_sum, modRes_smul, modRes_res, Finset.smul_sum, smul_smul]
    rw [Finset.sum_comm]
    have e : ∀ i'', ∑ j, (Tinv i' j * TopCat.Presheaf.restrictOpen (T j i'') W hWD) =
        (Tinv * TW) i' i'' := fun i'' ↦ by
      rw [mul_apply]
      rfl
    simp_rw [← Finset.sum_smul, e, hinv, one_apply, ite_smul, one_smul, zero_smul,
      Finset.sum_ite_eq, Finset.mem_univ, if_true]
  refine ⟨W, hWD, hx₀W, fun W' hW' σ x hx ↦ ?_⟩
  obtain ⟨p, rfl⟩ := exists_chartPt_of_mem_stdOpen (hDi (hWD (hW' hx)))
  obtain ⟨a, b, c, d, hpW'', hW''⟩ := exists_chartBox_subset i hx
  set W'' := chartBox.{u} i (prodOpens (boxOpens a b) (rectOpens c d))
  obtain ⟨-, hgen⟩ := hg W'' (hW''.trans (hW'.trans (hWD.trans hDN)))
    (fun q hq ↦ subsingleton_H_chartBox i a b c d hq)
  obtain ⟨e, he⟩ := hgen (modRes σ W'' hW'')
  refine ⟨W'', hW'', hpW'', fun j ↦ ∑ i', e i' *
    TopCat.Presheaf.restrictOpen (Tinv i' j) W'' (hW''.trans hW'), ?_⟩
  rw [he]
  have hg' : ∀ i', modRes (g i') W'' (hW''.trans (hW'.trans (hWD.trans hDN))) =
      ∑ j, TopCat.Presheaf.restrictOpen (Tinv i' j) W'' (hW''.trans hW') •
        modRes (∑ i'', T j i'' • modRes (g i'') D hDN) W'' (hW''.trans (hW'.trans hWD)) := by
    intro i'
    have e' := congrArg (fun y ↦ modRes y W'' (hW''.trans hW')) (hgW i')
    simp only [modRes_sum, modRes_smul, modRes_res, yres_res] at e' ⊢
    exact e'
  simp_rw [hg', Finset.smul_sum, smul_smul, Finset.sum_smul]
  rw [Finset.sum_comm]

/-- **Generators of `𝒢(n)` from a matrix which is the identity at a point.** Let `g` be acyclic
generating sections of `𝒢` over `N`, `D ≤ N` inside the chart `i`, and `Σ` sections of `𝒢(n)`
over `V ⊇ D` whose trivialisations on `D` are `∑ᵢ Tⱼᵢ gᵢ` with `T(x₀) = 1`. Then the `Σ`
generate `𝒢(n)` near `x₀`. -/
theorem exists_generates_twistMod_of_matrix {i : Fin 2}
    {N D V : (relProjectiveSpaceAn.{u} m 1).Opens} {I : Type u} [Fintype I] [DecidableEq I]
    (g : I → 𝒢.val.obj (op N)) (hg : IsAcyclicGenerating 𝒢 g) (hDN : D ≤ N)
    (hDi : D ≤ stdOpen.{u} m 1 i) (hDV : D ≤ V) (n : ℤ)
    (σ : I → (twistMod 𝒢 n).val.obj (op V)) (T : Matrix I I Γₚ(D))
    (hσ : ∀ j, modTwistSectionsEquiv (N := 𝒢) (twistModCocycle.{u} m 1 n) i hDi
      (modRes (σ j) D hDV) = ∑ i', T j i' • modRes (g i') D hDN)
    {x₀ : relProjectiveSpaceAn.{u} m 1} (hx₀ : x₀ ∈ D)
    (hT : ∀ j j', (relProjectiveSpaceAn.{u} m 1).eval x₀ hx₀ (T j j') = if j = j' then 1 else 0) :
    ∃ (W : (relProjectiveSpaceAn.{u} m 1).Opens) (hWV : W ≤ V), x₀ ∈ W ∧
      ∀ (W' : (relProjectiveSpaceAn.{u} m 1).Opens) (hW' : W' ≤ W)
        (τ : (twistMod 𝒢 n).val.obj (op W')) (x : relProjectiveSpaceAn.{u} m 1), x ∈ W' →
        ∃ (W'' : (relProjectiveSpaceAn.{u} m 1).Opens) (h : W'' ≤ W'), x ∈ W'' ∧
          ∃ c : I → Γₚ(W''), modRes τ W'' h =
            ∑ j, c j • modRes (σ j) W'' (h.trans (hW'.trans hWV)) := by
  obtain ⟨W, hWD, hx₀W, hW⟩ := exists_generates_of_matrix 𝒢 g hg hDN hDi T hx₀ hT
  refine ⟨W, hWD.trans hDV, hx₀W, fun W' hW' τ x hx ↦ ?_⟩
  have hW'i : W' ≤ stdOpen.{u} m 1 i := hW'.trans (hWD.trans hDi)
  obtain ⟨W'', h, hxW'', c, hc⟩ := hW W' hW'
    (modTwistSectionsEquiv (N := 𝒢) (twistModCocycle.{u} m 1 n) i hW'i τ) x hx
  refine ⟨W'', h, hxW'', c, ?_⟩
  apply (modTwistSectionsEquiv (N := 𝒢) (twistModCocycle.{u} m 1 n) i (h.trans hW'i)).injective
  rw [modTwistSectionsEquiv_res _ i hW'i h τ, hc, map_sum]
  refine Finset.sum_congr rfl fun j _ ↦ ?_
  rw [LinearEquiv.map_smul, ← hσ j, ← modTwistSectionsEquiv_res _ i hDi (h.trans (hW'.trans hWD)),
    modRes_res]

variable {𝒢} in
/-- The splitting property of the vector bundle of `d` for the twist `k`, on `B` times the annulus
`{l / ρ < ‖z‖ < l ρ}`. -/
def BundleData.Splits {B₀ : Opens (Fin m → ℂ)} {S : ℝ} (d : BundleData.{u} 𝒢 B₀ S)
    (B : Opens (Fin m → ℂ)) (l ρ : ℝ) (k : ℕ) : Prop :=
  ∀ h : (Fin m → ℂ) × ℂ → d.I₀ ⊕ d.I₁ → ℂ,
    DifferentiableOn ℂ h ((B : Set (Fin m → ℂ)) ×ˢ annulusSet (l * ρ) (ρ / l)) →
    ∃ s₀ t : (Fin m → ℂ) × ℂ → d.I₀ ⊕ d.I₁ → ℂ,
      DifferentiableOn ℂ s₀ ((B : Set (Fin m → ℂ)) ×ˢ Metric.ball 0 (l * ρ)) ∧
      DifferentiableOn ℂ t ((B : Set (Fin m → ℂ)) ×ˢ Metric.ball 0 (ρ / l)) ∧
      ∀ z ∈ (B : Set (Fin m → ℂ)), ∀ w ∈ annulusSet (l * ρ) (ρ / l),
        h (z, w) = s₀ (z, w) - w ^ k • d.G (z, w) *ᵥ t (z, w⁻¹)

lemma mem_discOverlap_of {B : Opens (Fin m → ℂ)} {r₀ r₁ : ℝ} (hr₁ : 0 < r₁)
    {p : (Fin m → ℂ) × ℂ} (hp : p.1 ∈ B ∧ p.2 ∈ annulusSet r₀ r₁) :
    chartPt.{u} 0 p ∈ discOverlap.{u} B r₀ r₁ :=
  ⟨p, (mem_overlapOpens_ballOpens hr₁).2 hp, rfl⟩

lemma ne_zero_of_mem_annulusSet {r₀ r₁ : ℝ} (hr₁ : 0 < r₁) {z : ℂ} (hz : z ∈ annulusSet r₀ r₁) :
    z ≠ 0 :=
  norm_pos_iff.1 ((inv_pos.2 hr₁).trans hz.1)

/-- Two sections of `𝒪` over `discOverlap B r₀ r₁` with the same values in the chart `0` on
`B` times the annulus are equal. -/
lemma eq_of_f0_eq_discOverlap {B : Opens (Fin m → ℂ)} {r₀ r₁ : ℝ} (hr₁ : 0 < r₁)
    {a b : Γₚ(discOverlap.{u} B r₀ r₁)}
    (h : ∀ p : (Fin m → ℂ) × ℂ, p.1 ∈ B → p.2 ∈ annulusSet r₀ r₁ → f0 a p = f0 b p) : a = b :=
  eq_of_f0_eq fun p hp ↦ by
    rw [mem_overlapOpens_ballOpens hr₁] at hp
    exact h p hp.1 hp.2

/-- A holomorphic function on `B` times the annulus is a section of `𝒪` over
`discOverlap B r₀ r₁`. -/
lemma exists_f0_eq_discOverlap (B : Opens (Fin m → ℂ)) {r₀ r₁ : ℝ} (hr₁ : 0 < r₁)
    (F : (Fin m → ℂ) × ℂ → ℂ)
    (hF : DifferentiableOn ℂ F ((B : Set (Fin m → ℂ)) ×ˢ annulusSet r₀ r₁)) :
    ∃ a : Γₚ(discOverlap.{u} B r₀ r₁), ∀ p : (Fin m → ℂ) × ℂ, p.1 ∈ B →
      p.2 ∈ annulusSet r₀ r₁ → f0 a p = F p := by
  obtain ⟨a, ha⟩ := exists_f0_eq.{u} (overlapOpens (prodOpens B (ballOpens r₀))
    (prodOpens B (ballOpens r₁))) F (hF.mono fun p hp ↦ (mem_overlapOpens_ballOpens hr₁).1 hp)
  exact ⟨a, fun p h1 h2 ↦ ha p ((mem_overlapOpens_ballOpens hr₁).2 ⟨h1, h2⟩)⟩

lemma differentiableOn_f0_discOverlap {B : Opens (Fin m → ℂ)} {r₀ r₁ : ℝ} (hr₁ : 0 < r₁)
    (a : Γₚ(discOverlap.{u} B r₀ r₁)) :
    DifferentiableOn ℂ (f0 a) ((B : Set (Fin m → ℂ)) ×ˢ annulusSet r₀ r₁) :=
  (differentiableOn_f0 a).mono fun _ hp ↦ (mem_overlapOpens_ballOpens hr₁).2 hp

lemma modRes_neg' {V W : (relProjectiveSpaceAn.{u} m 1).Opens} (h : W ≤ V)
    (x : 𝒢.val.obj (op V)) : modRes (-x) W h = -modRes x W h :=
  map_neg _ _

lemma discOverlap_le_discBox_zero (B : Opens (Fin m → ℂ)) (r₀ r₁ : ℝ) :
    discOverlap.{u} B r₀ r₁ ≤ discBox 0 B r₀ :=
  (discOverlap_eq B r₀ r₁).le.trans inf_le_left

lemma discOverlap_le_discBox_one (B : Opens (Fin m → ℂ)) (r₀ r₁ : ℝ) :
    discOverlap.{u} B r₀ r₁ ≤ discBox 1 B r₁ :=
  (discOverlap_eq B r₀ r₁).le.trans inf_le_right

namespace BundleData

variable {𝒢} {B₀ : Opens (Fin m → ℂ)} {S : ℝ} (d : BundleData.{u} 𝒢 B₀ S)

open scoped AlgebraicGeometry.Scheme.Modules in
/-- The sections `Σⱼ` of `𝒢(k + 1)` over `B × ℙ¹` with `Σⱼ = sⱼ - ℓ₀ Φⱼ` on the chart disc at
`0`, obtained by splitting `q sⱼ` for sections `q`, `ℓ₀`, `ℓ₁` of `𝒪` with `ℓ₀ q = 1` and
`ℓ₀ zᵏ = -zᵏ⁺¹ ℓ₁` on the annulus. -/
theorem exists_section_chart_zero {B : Opens (Fin m → ℂ)} (hBB₀ : B ≤ B₀) {l ρ : ℝ}
    (hr₀ : 0 < l * ρ) (hr₁ : 0 < ρ / l) (hr : 1 < l * ρ * (ρ / l)) (hr₀S : l * ρ ≤ S)
    (hr₁S : ρ / l ≤ S) {k : ℕ} (hsplit : d.Splits B l ρ k)
    (q : Γₚ(discOverlap.{u} B (l * ρ) (ρ / l))) (ℓ₀ : Γₚ(discBox.{u} 0 B (l * ρ)))
    (ℓ₁ : Γₚ(discBox.{u} 1 B (ρ / l)))
    (hℓq : TopCat.Presheaf.restrictOpen ℓ₀ _ (discOverlap_le_discBox_zero B _ _) * q = 1)
    (hℓz : TopCat.Presheaf.restrictOpen ℓ₀ _ (discOverlap_le_discBox_zero B _ _) *
      TopCat.Presheaf.restrictOpen (zSec (k : ℤ)) _ (discOverlap_le_stdOpen B _ _) =
      -(TopCat.Presheaf.restrictOpen (zSec ((k : ℤ) + 1)) _ (discOverlap_le_stdOpen B _ _) *
        TopCat.Presheaf.restrictOpen ℓ₁ _ (discOverlap_le_discBox_one B (l * ρ) (ρ / l))))
    (j : d.I₀) :
    ∃ (σ : (twistMod 𝒢 ((k : ℤ) + 1)).val.obj (op (tube.{u} (N := 1) B)))
      (ψ : d.I₀ ⊕ d.I₁ → Γₚ(discBox.{u} 0 B (l * ρ))),
      modTwistSectionsEquiv (N := 𝒢) (twistModCocycle.{u} m 1 ((k : ℤ) + 1)) 0
        (chartBox_le_stdOpen 0 _) (modRes σ _ (chartBox_prodOpens_le_tube 0 B _)) =
        modRes (d.s j) _ ((discBox_le_sqBox 0 hBB₀ hr₀S).trans d.hN₀) -
          ℓ₀ • ∑ a, ψ a • modRes (d.u₀ a) _ ((discBox_le_sqBox 0 hBB₀ hr₀S).trans d.hN₀) := by
  classical
  have hO₀ := discOverlap_le_discBox_zero.{u} B (l * ρ) (ρ / l)
  have hO₁ := discOverlap_le_discBox_one.{u} B (l * ρ) (ρ / l)
  have hOD : discOverlap.{u} B (l * ρ) (ρ / l) = discBox 0 B (l * ρ) ⊓ discBox 1 B (ρ / l) :=
    discOverlap_eq B _ _
  have hD₀st : discBox.{u} 0 B (l * ρ) ≤ stdOpen.{u} m 1 0 := chartBox_le_stdOpen 0 _
  have hD₁st : discBox.{u} 1 B (ρ / l) ≤ stdOpen.{u} m 1 1 := chartBox_le_stdOpen 1 _
  have hD₀T : discBox.{u} 0 B (l * ρ) ≤ tube.{u} (N := 1) B := chartBox_prodOpens_le_tube 0 B _
  have hD₁T : discBox.{u} 1 B (ρ / l) ≤ tube.{u} (N := 1) B := chartBox_prodOpens_le_tube 1 B _
  have hOst := discOverlap_le_stdOpen.{u} B (l * ρ) (ρ / l)
  have hsup : discBox.{u} 0 B (l * ρ) ⊔ discBox 1 B (ρ / l) = tube.{u} (N := 1) B :=
    chartBox_sup B _ _ (zero_mem_ballOpens hr₀) (zero_mem_ballOpens hr₁)
      (ballOpens_or_inv hr₀ hr)
  let ĥ : d.I₀ ⊕ d.I₁ → Γₚ(discOverlap.{u} B (l * ρ) (ρ / l)) :=
    Sum.elim (fun j' ↦ if j' = j then q else 0) 0
  obtain ⟨φ₀, φ₁, hφ₀, hφ₁, hrel⟩ := hsplit (fun p a ↦ f0 (ĥ a) p)
    (differentiableOn_pi.2 fun a ↦ differentiableOn_f0_discOverlap hr₁ (ĥ a))
  obtain ⟨ψ₀, ψ₁, -, -, hΦ⟩ := d.exists_split hBB₀ hr₁ hr₀S hr₁S k ĥ φ₀ φ₁ hφ₀ hφ₁
    fun y hy w hw ↦ hrel y hy w hw
  have hL : ∑ a, ĥ a • modRes (d.u₀ a) (discOverlap.{u} B (l * ρ) (ρ / l))
      ((discOverlap_le_sqOverlap hBB₀ hr₀S hr₁S).trans d.sqOverlap_le_N₀) =
      q • modRes (d.s j) (discOverlap.{u} B (l * ρ) (ρ / l))
        ((discOverlap_le_sqOverlap hBB₀ hr₀S hr₁S).trans d.sqOverlap_le_N₀) := by
    simp only [ĥ, Fintype.sum_sum_type, BundleData.u₀, Sum.elim_inl, Sum.elim_inr,
      Pi.zero_apply, zero_smul, Finset.sum_const_zero, add_zero, ite_smul,
      Finset.sum_ite_eq', Finset.mem_univ, if_true]
  have hD₀N : discBox.{u} 0 B (l * ρ) ≤ d.N₀ := (discBox_le_sqBox 0 hBB₀ hr₀S).trans d.hN₀
  have hD₁N : discBox.{u} 1 B (ρ / l) ≤ d.N₁ := (discBox_le_sqBox 1 hBB₀ hr₁S).trans d.hN₁
  set Φ₀ := ∑ a, ψ₀ a • modRes (d.u₀ a) _ hD₀N
  set Φ₁ := ∑ b, ψ₁ b • modRes (d.u₁ b) _ hD₁N
  have e := congrArg (fun y ↦ TopCat.Presheaf.restrictOpen ℓ₀ _ hO₀ • y) hΦ
  rw [hL, smul_smul, hℓq, one_smul, smul_sub, smul_smul, hℓz, neg_smul, sub_neg_eq_add] at e
  have hcompat : modRes (modRes (d.s j) _ hD₀N - ℓ₀ • Φ₀) _ hO₀ =
      TopCat.Presheaf.restrictOpen (zSec ((k : ℤ) + 1)) _ hOst • modRes (ℓ₁ • Φ₁) _ hO₁ := by
    rw [modRes_sub, modRes_smul, modRes_smul, modRes_res, e, smul_smul, add_sub_cancel_left]
  obtain ⟨T₀, hT₀⟩ : ∃ T₀, modTwistSectionsEquiv (N := 𝒢) (twistModCocycle.{u} m 1 ((k : ℤ) + 1))
      0 hD₀st T₀ = modRes (d.s j) _ hD₀N - ℓ₀ • Φ₀ := ⟨_, LinearEquiv.apply_symm_apply _ _⟩
  obtain ⟨T₁, hT₁⟩ : ∃ T₁, modTwistSectionsEquiv (N := 𝒢) (twistModCocycle.{u} m 1 ((k : ℤ) + 1))
      1 hD₁st T₁ = ℓ₁ • Φ₁ := ⟨_, LinearEquiv.apply_symm_apply _ _⟩
  obtain ⟨σ, hσ₀, -⟩ := exists_modRes_eq_of_two (twistMod 𝒢 ((k : ℤ) + 1)) hsup.ge hD₀T hD₁T
    T₀ T₁ (by
      apply (modTwistSectionsEquiv (N := 𝒢) (twistModCocycle.{u} m 1 ((k : ℤ) + 1)) 0
        (inf_le_left.trans hD₀st)).injective
      rw [modTwistSectionsEquiv_change _ 0 _ 1 (inf_le_right.trans hD₁st) (modRes T₁ _ _),
        modTwistSectionsEquiv_res _ 0 hD₀st inf_le_left T₀,
        modTwistSectionsEquiv_res _ 1 hD₁st inf_le_right T₁, hT₀, hT₁]
      have e2 := congrArg (fun y ↦ modRes y (discBox 0 B (l * ρ) ⊓ discBox 1 B (ρ / l)) hOD.ge)
        hcompat
      rw [modRes_res, modRes_smul, yres_res, modRes_res] at e2
      exact e2)
  exact ⟨σ, ψ₀, by rw [hσ₀, hT₀]⟩

open scoped AlgebraicGeometry.Scheme.Modules in
/-- **Generators near a point of the chart `0`.** Let `B ≤ B₀`, and suppose the vector bundle of
`d` splits (twist `k`) on `B` times the annulus `{l / ρ < ‖z‖ < l ρ}`. For `y₀ ∈ B` and
`‖c‖ < l / ρ` there are sections of `𝒢(k + 1)` over `B × ℙ¹` generating `𝒢(k + 1)` near the
point with fibre coordinate `c` over `y₀` in the chart `0`. -/
theorem exists_generates_chart_zero (hs : IsAcyclicGenerating 𝒢 d.s) {B : Opens (Fin m → ℂ)}
    (hBB₀ : B ≤ B₀) {l ρ : ℝ} (hr₀ : 0 < l * ρ) (hr₁ : 0 < ρ / l) (hr : 1 < l * ρ * (ρ / l))
    (hr₀S : l * ρ ≤ S) (hr₁S : ρ / l ≤ S) {k : ℕ} (hsplit : d.Splits B l ρ k)
    {y₀ : Fin m → ℂ} (hy₀ : y₀ ∈ B) {c : ℂ} (hc : ‖c‖ < (ρ / l)⁻¹) :
    ∃ (σ : d.I₀ → (twistMod 𝒢 ((k : ℤ) + 1)).val.obj (op (tube.{u} (N := 1) B)))
      (W : (relProjectiveSpaceAn.{u} m 1).Opens) (hW : W ≤ tube.{u} (N := 1) B),
      chartPt.{u} 0 (y₀, c) ∈ W ∧
      ∀ (W' : (relProjectiveSpaceAn.{u} m 1).Opens) (hW' : W' ≤ W)
        (τ : (twistMod 𝒢 ((k : ℤ) + 1)).val.obj (op W')) (x : relProjectiveSpaceAn.{u} m 1),
        x ∈ W' → ∃ (W'' : (relProjectiveSpaceAn.{u} m 1).Opens) (h : W'' ≤ W'), x ∈ W'' ∧
          ∃ e : d.I₀ → Γₚ(W''), modRes τ W'' h =
            ∑ j, e j • modRes (σ j) W'' (h.trans (hW'.trans hW)) := by
  classical
  have hOD : discOverlap.{u} B (l * ρ) (ρ / l) = discBox 0 B (l * ρ) ⊓ discBox 1 B (ρ / l) :=
    discOverlap_eq B _ _
  have hO₀ : discOverlap.{u} B (l * ρ) (ρ / l) ≤ discBox 0 B (l * ρ) := hOD.le.trans inf_le_left
  have hO₁ : discOverlap.{u} B (l * ρ) (ρ / l) ≤ discBox 1 B (ρ / l) := hOD.le.trans inf_le_right
  have hD₀N : discBox.{u} 0 B (l * ρ) ≤ d.N₀ := (discBox_le_sqBox 0 hBB₀ hr₀S).trans d.hN₀
  have hD₀st : discBox.{u} 0 B (l * ρ) ≤ stdOpen.{u} m 1 0 := chartBox_le_stdOpen 0 _
  have hD₁st : discBox.{u} 1 B (ρ / l) ≤ stdOpen.{u} m 1 1 := chartBox_le_stdOpen 1 _
  have hOst := discOverlap_le_stdOpen.{u} B (l * ρ) (ρ / l)
  have hD₀T : discBox.{u} 0 B (l * ρ) ≤ tube.{u} (N := 1) B := chartBox_prodOpens_le_tube 0 B _
  have hD₁T : discBox.{u} 1 B (ρ / l) ≤ tube.{u} (N := 1) B := chartBox_prodOpens_le_tube 1 B _
  have hsup : discBox.{u} 0 B (l * ρ) ⊔ discBox 1 B (ρ / l) = tube.{u} (N := 1) B :=
    chartBox_sup B _ _ (zero_mem_ballOpens hr₀) (zero_mem_ballOpens hr₁) (ballOpens_or_inv hr₀ hr)
  have hann_c : ∀ w ∈ annulusSet (l * ρ) (ρ / l), w - c ≠ 0 := fun w hw h ↦ by
    rw [sub_eq_zero] at h
    subst h
    exact absurd hw.1 (not_lt.2 hc.le)
  have hinv_ball : ∀ w ∈ annulusSet (l * ρ) (ρ / l), w⁻¹ ∈ Metric.ball (0 : ℂ) (ρ / l) := by
    intro w hw
    have h0 : 0 < ‖w‖ := (inv_pos.2 hr₁).trans hw.1
    rw [Metric.mem_ball, dist_zero_right, norm_inv]
    exact (inv_lt_comm₀ h0 hr₁).2 hw.1
  -- the sections `q = 1 / (z - c)`, `ℓ₀ = z - c` and `ℓ₁ = c w - 1`
  obtain ⟨q, hq⟩ := exists_f0_eq_discOverlap.{u} B hr₁ (fun p ↦ (p.2 - c)⁻¹) (fun p hp ↦
    ((differentiableAt_snd.sub_const c).inv (hann_c _ hp.2)).differentiableWithinAt)
  obtain ⟨ℓ₀, hℓ₀⟩ := exists_f0_eq.{u} (prodOpens B (ballOpens (l * ρ))) (fun p ↦ p.2 - c)
    (differentiable_snd.sub_const c).differentiableOn
  obtain ⟨ℓ₁, hℓ₁⟩ := exists_f1_eq.{u} (prodOpens B (ballOpens (ρ / l))) (fun p ↦ c * p.2 - 1)
    ((differentiable_snd.const_mul c).sub_const 1).differentiableOn
  have hℓq : (ℓ₀ |ₒ discOverlap.{u} B (l * ρ) (ρ / l)) * q = 1 :=
    eq_of_f0_eq_discOverlap hr₁ fun p hp1 hp2 ↦ by
      have hpO := mem_discOverlap_of.{u} hr₁ ⟨hp1, hp2⟩
      rw [f0_mul, Pi.mul_apply, f0_restrictOpen _ _ hpO, hℓ₀ p ⟨hp1, ?_⟩, hq p hp1 hp2,
        f0_one hpO]
      · exact mul_inv_cancel₀ (hann_c _ hp2)
      · change p.2 ∈ Metric.ball (0 : ℂ) (l * ρ)
        rw [Metric.mem_ball, dist_zero_right]
        exact hp2.2
  have hℓz : (ℓ₀ |ₒ discOverlap.{u} B (l * ρ) (ρ / l)) *
      (zSec (k : ℤ) |ₒ discOverlap.{u} B (l * ρ) (ρ / l)) =
      -((zSec ((k : ℤ) + 1) |ₒ discOverlap.{u} B (l * ρ) (ρ / l)) *
        (ℓ₁ |ₒ discOverlap.{u} B (l * ρ) (ρ / l))) :=
    eq_of_f0_eq_discOverlap hr₁ fun p hp1 hp2 ↦ by
      have hpO := mem_discOverlap_of.{u} hr₁ ⟨hp1, hp2⟩
      have h2 := ne_zero_of_mem_annulusSet hr₁ hp2
      have hneg : f0 (-((zSec ((k : ℤ) + 1) |ₒ discOverlap.{u} B (l * ρ) (ρ / l)) *
          (ℓ₁ |ₒ discOverlap.{u} B (l * ρ) (ρ / l)))) p = -(f0 ((zSec ((k : ℤ) + 1) |ₒ
            discOverlap.{u} B (l * ρ) (ρ / l)) * (ℓ₁ |ₒ discOverlap.{u} B (l * ρ) (ρ / l))) p) := by
        rw [neg_eq_zero_sub, f0_sub, f0_zero]
        simp
      have hp₀ : p ∈ prodOpens B (ballOpens (l * ρ)) := ⟨hp1, by
        change p.2 ∈ Metric.ball (0 : ℂ) (l * ρ)
        rw [Metric.mem_ball, dist_zero_right]
        exact hp2.2⟩
      have hp₁ : (p.1, p.2⁻¹) ∈ prodOpens B (ballOpens (ρ / l)) := ⟨hp1, hinv_ball _ hp2⟩
      rw [hneg, f0_mul, f0_mul, Pi.mul_apply, Pi.mul_apply, f0_restrictOpen _ _ hpO,
        f0_restrictOpen _ _ hpO, f0_restrictOpen _ _ hpO, f0_restrictOpen _ _ hpO,
        f0_twistModCocycle _ (hOst hpO), f0_twistModCocycle _ (hOst hpO), hℓ₀ p hp₀,
        ← f1_inv_eq_f0 ℓ₁ h2, hℓ₁ _ hp₁, zpow_add₀ h2, zpow_one, zpow_natCast]
      field_simp
      ring
  choose σ ψ hσψ using d.exists_section_chart_zero hBB₀ hr₀ hr₁ hr hr₀S hr₁S hsplit q ℓ₀ ℓ₁
    hℓq hℓz
  let T : Matrix d.I₀ d.I₀ Γₚ(discBox.{u} 0 B (l * ρ)) :=
    fun j j' ↦ (if j = j' then 1 else 0) - ℓ₀ * ψ j (Sum.inl j')
  have hTσ : ∀ j, modTwistSectionsEquiv (N := 𝒢) (twistModCocycle.{u} m 1 ((k : ℤ) + 1)) 0
      hD₀st (modRes (σ j) _ hD₀T) = ∑ j', T j j' • modRes (d.s j') _ hD₀N := by
    intro j
    rw [hσψ j]
    simp only [T, sub_smul, Finset.sum_sub_distrib, ite_smul, one_smul, zero_smul,
      Finset.sum_ite_eq, Finset.mem_univ, if_true, mul_smul, ← Finset.smul_sum,
      Fintype.sum_sum_type, BundleData.u₀, Sum.elim_inl, Sum.elim_inr, Pi.zero_apply,
      modRes_zero, smul_zero, Finset.sum_const_zero, add_zero]
  have hx₀ : chartPt.{u} 0 (y₀, c) ∈ discBox.{u} 0 B (l * ρ) := by
    refine ⟨(y₀, c), ⟨hy₀, ?_⟩, rfl⟩
    change c ∈ Metric.ball (0 : ℂ) (l * ρ)
    rw [Metric.mem_ball, dist_zero_right]
    refine hc.trans ?_
    rw [inv_lt_iff_one_lt_mul₀ hr₁]
    exact hr
  have hℓ₀x : (relProjectiveSpaceAn.{u} m 1).eval _ hx₀ ℓ₀ = 0 := by
    rw [← f0_eq_eval, hℓ₀ _ ⟨hy₀, ?_⟩, sub_self]
    change c ∈ Metric.ball (0 : ℂ) (l * ρ)
    rw [Metric.mem_ball, dist_zero_right]
    refine hc.trans ?_
    rw [inv_lt_iff_one_lt_mul₀ hr₁]
    exact hr
  have hT : ∀ j j', (relProjectiveSpaceAn.{u} m 1).eval _ hx₀ (T j j') =
      if j = j' then 1 else 0 := by
    intro j j'
    simp only [T, map_sub, map_mul, hℓ₀x, zero_mul, sub_zero]
    split_ifs <;> simp
  obtain ⟨W, hWV, hx₀W, hgen⟩ := exists_generates_twistMod_of_matrix 𝒢 d.s hs hD₀N hD₀st hD₀T
    ((k : ℤ) + 1) σ T hTσ hx₀ hT
  exact ⟨σ, W, hWV, hx₀W, hgen⟩

/-- The sections `Σₗ` of `𝒢(k + 1)` over `B × ℙ¹` with `Σₗ = tₗ + ℓ₁ Φₗ` on the chart disc at
`1`, obtained by splitting `r tₗ` for sections `r`, `ℓ₀`, `ℓ₁` of `𝒪` with `ℓ₀ r = zᵏ⁺¹` and
`ℓ₀ zᵏ = zᵏ⁺¹ ℓ₁` on the annulus. -/
theorem exists_section_chart_one {B : Opens (Fin m → ℂ)} (hBB₀ : B ≤ B₀) {l ρ : ℝ}
    (hr₀ : 0 < l * ρ) (hr₁ : 0 < ρ / l) (hr : 1 < l * ρ * (ρ / l)) (hr₀S : l * ρ ≤ S)
    (hr₁S : ρ / l ≤ S) {k : ℕ} (hsplit : d.Splits B l ρ k)
    (r : Γₚ(discOverlap.{u} B (l * ρ) (ρ / l))) (ℓ₀ : Γₚ(discBox.{u} 0 B (l * ρ)))
    (ℓ₁ : Γₚ(discBox.{u} 1 B (ρ / l)))
    (hℓr : TopCat.Presheaf.restrictOpen ℓ₀ _ (discOverlap_le_discBox_zero B _ _) * r =
      TopCat.Presheaf.restrictOpen (zSec ((k : ℤ) + 1)) _ (discOverlap_le_stdOpen B _ _))
    (hℓz : TopCat.Presheaf.restrictOpen ℓ₀ _ (discOverlap_le_discBox_zero B _ _) *
      TopCat.Presheaf.restrictOpen (zSec (k : ℤ)) _ (discOverlap_le_stdOpen B _ _) =
      TopCat.Presheaf.restrictOpen (zSec ((k : ℤ) + 1)) _ (discOverlap_le_stdOpen B _ _) *
        TopCat.Presheaf.restrictOpen ℓ₁ _ (discOverlap_le_discBox_one B (l * ρ) (ρ / l)))
    (l₁ : d.I₁) :
    ∃ (σ : (twistMod 𝒢 ((k : ℤ) + 1)).val.obj (op (tube.{u} (N := 1) B)))
      (ψ : d.I₀ ⊕ d.I₁ → Γₚ(discBox.{u} 1 B (ρ / l))),
      modTwistSectionsEquiv (N := 𝒢) (twistModCocycle.{u} m 1 ((k : ℤ) + 1)) 1
        (chartBox_le_stdOpen 1 _) (modRes σ _ (chartBox_prodOpens_le_tube 1 B _)) =
        modRes (d.t l₁) _ ((discBox_le_sqBox 1 hBB₀ hr₁S).trans d.hN₁) +
          ℓ₁ • ∑ b, ψ b • modRes (d.u₁ b) _ ((discBox_le_sqBox 1 hBB₀ hr₁S).trans d.hN₁) := by
  classical
  have hO₀ := discOverlap_le_discBox_zero.{u} B (l * ρ) (ρ / l)
  have hO₁ := discOverlap_le_discBox_one.{u} B (l * ρ) (ρ / l)
  have hOD : discOverlap.{u} B (l * ρ) (ρ / l) = discBox 0 B (l * ρ) ⊓ discBox 1 B (ρ / l) :=
    discOverlap_eq B _ _
  have hOS : discOverlap.{u} B (l * ρ) (ρ / l) ≤ sqOverlap B₀ S :=
    discOverlap_le_sqOverlap hBB₀ hr₀S hr₁S
  have hD₀st : discBox.{u} 0 B (l * ρ) ≤ stdOpen.{u} m 1 0 := chartBox_le_stdOpen 0 _
  have hD₁st : discBox.{u} 1 B (ρ / l) ≤ stdOpen.{u} m 1 1 := chartBox_le_stdOpen 1 _
  have hD₀T : discBox.{u} 0 B (l * ρ) ≤ tube.{u} (N := 1) B := chartBox_prodOpens_le_tube 0 B _
  have hD₁T : discBox.{u} 1 B (ρ / l) ≤ tube.{u} (N := 1) B := chartBox_prodOpens_le_tube 1 B _
  have hOst := discOverlap_le_stdOpen.{u} B (l * ρ) (ρ / l)
  have hsup : discBox.{u} 0 B (l * ρ) ⊔ discBox 1 B (ρ / l) = tube.{u} (N := 1) B :=
    chartBox_sup B _ _ (zero_mem_ballOpens hr₀) (zero_mem_ballOpens hr₁)
      (ballOpens_or_inv hr₀ hr)
  let ĥ : d.I₀ ⊕ d.I₁ → Γₚ(discOverlap.{u} B (l * ρ) (ρ / l)) :=
    Sum.elim (fun j ↦ r * TopCat.Presheaf.restrictOpen (d.A l₁ j) _ hOS) 0
  obtain ⟨φ₀, φ₁, hφ₀, hφ₁, hrel⟩ := hsplit (fun p a ↦ f0 (ĥ a) p)
    (differentiableOn_pi.2 fun a ↦ differentiableOn_f0_discOverlap hr₁ (ĥ a))
  obtain ⟨ψ₀, ψ₁, -, -, hΦ⟩ := d.exists_split hBB₀ hr₁ hr₀S hr₁S k ĥ φ₀ φ₁ hφ₀ hφ₁
    fun y hy w hw ↦ hrel y hy w hw
  have hL : ∑ a, ĥ a • modRes (d.u₀ a) (discOverlap.{u} B (l * ρ) (ρ / l))
      (hOS.trans d.sqOverlap_le_N₀) =
      r • modRes (d.t l₁) (discOverlap.{u} B (l * ρ) (ρ / l)) (hOS.trans d.sqOverlap_le_N₁) := by
    have e := congrArg (fun y ↦ modRes y (discOverlap.{u} B (l * ρ) (ρ / l)) hOS) (d.hA l₁)
    simp only [modRes_sum, modRes_smul, modRes_res] at e
    rw [e, Finset.smul_sum]
    simp only [ĥ, Fintype.sum_sum_type, BundleData.u₀, Sum.elim_inl, Sum.elim_inr,
      Pi.zero_apply, zero_smul, Finset.sum_const_zero, add_zero, mul_smul]
  have hD₀N : discBox.{u} 0 B (l * ρ) ≤ d.N₀ := (discBox_le_sqBox 0 hBB₀ hr₀S).trans d.hN₀
  have hD₁N : discBox.{u} 1 B (ρ / l) ≤ d.N₁ := (discBox_le_sqBox 1 hBB₀ hr₁S).trans d.hN₁
  set Φ₀ := ∑ a, ψ₀ a • modRes (d.u₀ a) _ hD₀N
  set Φ₁ := ∑ b, ψ₁ b • modRes (d.u₁ b) _ hD₁N
  have e := congrArg (fun y ↦ TopCat.Presheaf.restrictOpen ℓ₀ _ hO₀ • y) hΦ
  rw [hL, smul_smul, hℓr, smul_sub, smul_smul, hℓz, mul_smul] at e
  have hcompat : modRes (ℓ₀ • Φ₀) _ hO₀ =
      TopCat.Presheaf.restrictOpen (zSec ((k : ℤ) + 1)) _ hOst •
        modRes (modRes (d.t l₁) _ hD₁N + ℓ₁ • Φ₁) _ hO₁ := by
    rw [modRes_add, modRes_smul, modRes_res, smul_add, e, modRes_smul, sub_add_cancel]
  obtain ⟨T₀, hT₀⟩ : ∃ T₀, modTwistSectionsEquiv (N := 𝒢) (twistModCocycle.{u} m 1 ((k : ℤ) + 1))
      0 hD₀st T₀ = ℓ₀ • Φ₀ := ⟨_, LinearEquiv.apply_symm_apply _ _⟩
  obtain ⟨T₁, hT₁⟩ : ∃ T₁, modTwistSectionsEquiv (N := 𝒢) (twistModCocycle.{u} m 1 ((k : ℤ) + 1))
      1 hD₁st T₁ = modRes (d.t l₁) _ hD₁N + ℓ₁ • Φ₁ := ⟨_, LinearEquiv.apply_symm_apply _ _⟩
  obtain ⟨σ, -, hσ₁⟩ := exists_modRes_eq_of_two (twistMod 𝒢 ((k : ℤ) + 1)) hsup.ge hD₀T hD₁T
    T₀ T₁ (by
      apply (modTwistSectionsEquiv (N := 𝒢) (twistModCocycle.{u} m 1 ((k : ℤ) + 1)) 0
        (inf_le_left.trans hD₀st)).injective
      rw [modTwistSectionsEquiv_change _ 0 _ 1 (inf_le_right.trans hD₁st) (modRes T₁ _ _),
        modTwistSectionsEquiv_res _ 0 hD₀st inf_le_left T₀,
        modTwistSectionsEquiv_res _ 1 hD₁st inf_le_right T₁, hT₀, hT₁]
      have e2 := congrArg (fun y ↦ modRes y (discBox 0 B (l * ρ) ⊓ discBox 1 B (ρ / l)) hOD.ge)
        hcompat
      rw [modRes_res] at e2
      conv_rhs at e2 => rw [modRes_smul, yres_res, modRes_res]
      exact e2)
  exact ⟨σ, ψ₁, by rw [hσ₁, hT₁]⟩

open scoped AlgebraicGeometry.Scheme.Modules in
/-- **Generators near a point of the chart `1`.** Let `B ≤ B₀`, and suppose the vector bundle of
`d` splits (twist `k`) on `B` times the annulus `{l / ρ < ‖z‖ < l ρ}`. For `y₀ ∈ B` and
`‖c‖ < 1 / (l ρ)` there are sections of `𝒢(k + 1)` over `B × ℙ¹` generating `𝒢(k + 1)` near the
point with fibre coordinate `c` over `y₀` in the chart `1`. -/
theorem exists_generates_chart_one (ht : IsAcyclicGenerating 𝒢 d.t) {B : Opens (Fin m → ℂ)}
    (hBB₀ : B ≤ B₀) {l ρ : ℝ} (hr₀ : 0 < l * ρ) (hr₁ : 0 < ρ / l) (hr : 1 < l * ρ * (ρ / l))
    (hr₀S : l * ρ ≤ S) (hr₁S : ρ / l ≤ S) {k : ℕ} (hsplit : d.Splits B l ρ k)
    {y₀ : Fin m → ℂ} (hy₀ : y₀ ∈ B) {c : ℂ} (hc : ‖c‖ < (l * ρ)⁻¹) :
    ∃ (σ : d.I₁ → (twistMod 𝒢 ((k : ℤ) + 1)).val.obj (op (tube.{u} (N := 1) B)))
      (W : (relProjectiveSpaceAn.{u} m 1).Opens) (hW : W ≤ tube.{u} (N := 1) B),
      chartPt.{u} 1 (y₀, c) ∈ W ∧
      ∀ (W' : (relProjectiveSpaceAn.{u} m 1).Opens) (hW' : W' ≤ W)
        (τ : (twistMod 𝒢 ((k : ℤ) + 1)).val.obj (op W')) (x : relProjectiveSpaceAn.{u} m 1),
        x ∈ W' → ∃ (W'' : (relProjectiveSpaceAn.{u} m 1).Opens) (h : W'' ≤ W'), x ∈ W'' ∧
          ∃ e : d.I₁ → Γₚ(W''), modRes τ W'' h =
            ∑ j, e j • modRes (σ j) W'' (h.trans (hW'.trans hW)) := by
  classical
  have hD₁N : discBox.{u} 1 B (ρ / l) ≤ d.N₁ := (discBox_le_sqBox 1 hBB₀ hr₁S).trans d.hN₁
  have hD₁st : discBox.{u} 1 B (ρ / l) ≤ stdOpen.{u} m 1 1 := chartBox_le_stdOpen 1 _
  have hOst := discOverlap_le_stdOpen.{u} B (l * ρ) (ρ / l)
  have hO₀ := discOverlap_le_discBox_zero.{u} B (l * ρ) (ρ / l)
  have hO₁ := discOverlap_le_discBox_one.{u} B (l * ρ) (ρ / l)
  have hD₁T : discBox.{u} 1 B (ρ / l) ≤ tube.{u} (N := 1) B := chartBox_prodOpens_le_tube 1 B _
  have hann_c : ∀ w ∈ annulusSet (l * ρ) (ρ / l), 1 - c * w ≠ 0 := fun w hw h ↦ by
    have h1 : ‖c * w‖ < 1 := by
      rw [norm_mul]
      calc ‖c‖ * ‖w‖ ≤ ‖c‖ * (l * ρ) := by gcongr; exact hw.2.le
        _ < (l * ρ)⁻¹ * (l * ρ) := by gcongr
        _ = 1 := inv_mul_cancel₀ hr₀.ne'
    rw [sub_eq_zero] at h
    rw [← h, norm_one] at h1
    exact lt_irrefl _ h1
  have hinv_ball : ∀ w ∈ annulusSet (l * ρ) (ρ / l), w⁻¹ ∈ Metric.ball (0 : ℂ) (ρ / l) := by
    intro w hw
    have h0 : 0 < ‖w‖ := (inv_pos.2 hr₁).trans hw.1
    rw [Metric.mem_ball, dist_zero_right, norm_inv]
    exact (inv_lt_comm₀ h0 hr₁).2 hw.1
  -- the sections `r = zᵏ⁺¹ / (1 - c z)`, `ℓ₀ = 1 - c z` and `ℓ₁ = w - c`
  obtain ⟨r, hr'⟩ := exists_f0_eq_discOverlap.{u} B hr₁ (fun p ↦ p.2 ^ (k + 1) * (1 - c * p.2)⁻¹)
    (fun p hp ↦ ((differentiableAt_snd.pow _).mul ((differentiableAt_snd.const_mul c).const_sub 1
      |>.inv (hann_c _ hp.2))).differentiableWithinAt)
  obtain ⟨ℓ₀, hℓ₀⟩ := exists_f0_eq.{u} (prodOpens B (ballOpens (l * ρ))) (fun p ↦ 1 - c * p.2)
    ((differentiable_snd.const_mul c).const_sub 1).differentiableOn
  obtain ⟨ℓ₁, hℓ₁⟩ := exists_f1_eq.{u} (prodOpens B (ballOpens (ρ / l))) (fun p ↦ p.2 - c)
    (differentiable_snd.sub_const c).differentiableOn
  have hp₀ : ∀ p : (Fin m → ℂ) × ℂ, p.1 ∈ B → p.2 ∈ annulusSet (l * ρ) (ρ / l) →
      p ∈ prodOpens B (ballOpens (l * ρ)) := fun p hp1 hp2 ↦ ⟨hp1, by
    change p.2 ∈ Metric.ball (0 : ℂ) (l * ρ)
    rw [Metric.mem_ball, dist_zero_right]
    exact hp2.2⟩
  have hℓr : (ℓ₀ |ₒ discOverlap.{u} B (l * ρ) (ρ / l)) * r =
      (zSec ((k : ℤ) + 1) |ₒ discOverlap.{u} B (l * ρ) (ρ / l)) :=
    eq_of_f0_eq_discOverlap hr₁ fun p hp1 hp2 ↦ by
      have hpO := mem_discOverlap_of.{u} hr₁ ⟨hp1, hp2⟩
      rw [f0_mul, Pi.mul_apply, f0_restrictOpen _ _ hpO, f0_restrictOpen _ _ hpO,
        hℓ₀ p (hp₀ p hp1 hp2), hr' p hp1 hp2, f0_twistModCocycle _ (hOst hpO), zpow_add₀
        (ne_zero_of_mem_annulusSet hr₁ hp2), zpow_one, zpow_natCast]
      have := hann_c _ hp2
      field_simp
      ring
  have hℓz : (ℓ₀ |ₒ discOverlap.{u} B (l * ρ) (ρ / l)) *
      (zSec (k : ℤ) |ₒ discOverlap.{u} B (l * ρ) (ρ / l)) =
      (zSec ((k : ℤ) + 1) |ₒ discOverlap.{u} B (l * ρ) (ρ / l)) *
        (ℓ₁ |ₒ discOverlap.{u} B (l * ρ) (ρ / l)) :=
    eq_of_f0_eq_discOverlap hr₁ fun p hp1 hp2 ↦ by
      have hpO := mem_discOverlap_of.{u} hr₁ ⟨hp1, hp2⟩
      have h2 := ne_zero_of_mem_annulusSet hr₁ hp2
      have hp₁ : (p.1, p.2⁻¹) ∈ prodOpens B (ballOpens (ρ / l)) := ⟨hp1, hinv_ball _ hp2⟩
      rw [f0_mul, f0_mul, Pi.mul_apply, Pi.mul_apply, f0_restrictOpen _ _ hpO,
        f0_restrictOpen _ _ hpO, f0_restrictOpen _ _ hpO, f0_restrictOpen _ _ hpO,
        f0_twistModCocycle _ (hOst hpO), f0_twistModCocycle _ (hOst hpO), hℓ₀ p (hp₀ p hp1 hp2),
        ← f1_inv_eq_f0 ℓ₁ h2, hℓ₁ _ hp₁, zpow_add₀ h2, zpow_one, zpow_natCast]
      field_simp
  choose σ ψ hσψ using d.exists_section_chart_one hBB₀ hr₀ hr₁ hr hr₀S hr₁S hsplit r ℓ₀ ℓ₁
    hℓr hℓz
  let T : Matrix d.I₁ d.I₁ Γₚ(discBox.{u} 1 B (ρ / l)) :=
    fun j j' ↦ (if j = j' then 1 else 0) + ℓ₁ * ψ j (Sum.inr j')
  have hTσ : ∀ j, modTwistSectionsEquiv (N := 𝒢) (twistModCocycle.{u} m 1 ((k : ℤ) + 1)) 1
      hD₁st (modRes (σ j) _ hD₁T) = ∑ j', T j j' • modRes (d.t j') _ hD₁N := by
    intro j
    rw [hσψ j]
    simp only [T, add_smul, Finset.sum_add_distrib, ite_smul, one_smul, zero_smul,
      Finset.sum_ite_eq, Finset.mem_univ, if_true, mul_smul, ← Finset.smul_sum,
      Fintype.sum_sum_type, BundleData.u₁, Sum.elim_inl, Sum.elim_inr, Pi.zero_apply,
      modRes_zero, smul_zero, Finset.sum_const_zero, zero_add]
  have hcball : c ∈ ballOpens (ρ / l) := by
    change c ∈ Metric.ball (0 : ℂ) (ρ / l)
    rw [Metric.mem_ball, dist_zero_right]
    refine hc.trans ?_
    rw [inv_lt_iff_one_lt_mul₀ hr₀, mul_comm]
    exact hr
  have hx₀ : chartPt.{u} 1 (y₀, c) ∈ discBox.{u} 1 B (ρ / l) := ⟨(y₀, c), ⟨hy₀, hcball⟩, rfl⟩
  have hℓ₁x : (relProjectiveSpaceAn.{u} m 1).eval _ hx₀ ℓ₁ = 0 := by
    rw [← f1_eq_eval, hℓ₁ _ ⟨hy₀, hcball⟩, sub_self]
  have hT : ∀ j j', (relProjectiveSpaceAn.{u} m 1).eval _ hx₀ (T j j') =
      if j = j' then 1 else 0 := by
    intro j j'
    simp only [T, map_add, map_mul, hℓ₁x, zero_mul, add_zero]
    split_ifs <;> simp
  obtain ⟨W, hWV, hx₀W, hgen⟩ := exists_generates_twistMod_of_matrix 𝒢 d.t ht hD₁N hD₁st hD₁T
    ((k : ℤ) + 1) σ T hTσ hx₀ hT
  exact ⟨σ, W, hWV, hx₀W, hgen⟩

end BundleData

/-- Local generation of `M` on `W` by the restrictions of sections over `V ⊇ W`. -/
lemma generatesLocally_of
    {M : SheafOfModules.{u} (relProjectiveSpaceAn.{u} m 1).toLocallyRingedSpace.ringSheaf}
    {V W : (relProjectiveSpaceAn.{u} m 1).Opens} {I : Type u} [Fintype I]
    {σ : I → M.val.obj (op V)} {hW : W ≤ V}
    (h : ∀ (W' : (relProjectiveSpaceAn.{u} m 1).Opens) (hW' : W' ≤ W) (τ : M.val.obj (op W'))
      (y : relProjectiveSpaceAn.{u} m 1), y ∈ W' → ∃ (W'' : (relProjectiveSpaceAn.{u} m 1).Opens)
        (h : W'' ≤ W'), y ∈ W'' ∧ ∃ e : I → Γₚ(W''),
          modRes τ W'' h = ∑ i, e i • modRes (σ i) W'' (h.trans (hW'.trans hW))) :
    GeneratesLocally fun i ↦ modRes (σ i) W hW := fun W' hW' τ y hy ↦ by
  obtain ⟨W'', h', hy'', e, he⟩ := h W' hW' τ y hy
  exact ⟨W'', h', hy'', e, by rw [he]; simp only [modRes_res]⟩

/-- Every point of `B × ℙ¹` has fibre coordinate of norm `≤ 1` in one of the charts. -/
lemma exists_chartPt_norm_le_one {B : Opens (Fin m → ℂ)} {x : relProjectiveSpaceAn.{u} m 1}
    (hx : x ∈ tube.{u} (N := 1) B) :
    ∃ p : (Fin m → ℂ) × ℂ, p.1 ∈ B ∧ ‖p.2‖ ≤ 1 ∧ (chartPt.{u} 0 p = x ∨ chartPt.{u} 1 p = x) := by
  rw [mem_tube] at hx
  obtain ⟨p, rfl⟩ | ⟨p, rfl⟩ := exists_chartPt x
  · rw [baseY_chartPt] at hx
    by_cases hp : ‖p.2‖ ≤ 1
    · exact ⟨p, hx, hp, Or.inl rfl⟩
    · push Not at hp
      have h0 : p.2 ≠ 0 := norm_pos_iff.1 (zero_lt_one.trans hp)
      refine ⟨(p.1, p.2⁻¹), hx, ?_, Or.inr (chartPt_zero_eq_chartPt_one h0).symm⟩
      rw [norm_inv]
      exact inv_le_one_of_one_le₀ hp.le
  · rw [baseY_chartPt] at hx
    by_cases hp : ‖p.2‖ ≤ 1
    · exact ⟨p, hx, hp, Or.inr rfl⟩
    · push Not at hp
      have h0 : p.2 ≠ 0 := norm_pos_iff.1 (zero_lt_one.trans hp)
      refine ⟨(p.1, p.2⁻¹), hx, ?_, Or.inl ?_⟩
      · rw [norm_inv]
        exact inv_le_one_of_one_le₀ hp.le
      · rw [chartPt_zero_eq_chartPt_one (inv_ne_zero h0), inv_inv]

/-- **Relative Theorem A on `U × ℙ¹`, uniform in sub-boxes.** Let `𝒢` be a sheaf of modules on
`P^an = ℂᵐ × ℙ¹` which is coherent over `U × ℙ¹`, and `K ⊆ U` a nonempty closed box. There are an
open box `B₁` with `K ⊆ B₁ ⊆ U` and `n₀` such that for all `n ≥ n₀`, every point `x` of `B₁ × ℙ¹`
has a neighbourhood `W` on which finitely many sections of `𝒢(n)` over `B₁ × ℙ¹` generate
`𝒢(n)`: every section over an open `W' ⊆ W` is, near each point of `W'`, a combination of their
restrictions. In other words, `π^* π_* 𝒢(n) → 𝒢(n)` is surjective over `B₁`. -/
theorem exists_generates_twistMod {U : Opens (Fin m → ℂ)}
    (h𝒢 : (((relProjectiveSpaceAn.{u} m 1).toLocallyRingedSpace.restrictModules
      (tube.{u} (N := 1) U)).obj 𝒢).IsCoherent)
    {a b : Fin m → ℂ} (hK : Complex.closedBox a b ⊆ U) (hne : (Complex.closedBox a b).Nonempty) :
    ∃ a' b' : Fin m → ℂ, Complex.closedBox a b ⊆ Complex.openBox a' b' ∧
      Complex.openBox a' b' ⊆ U ∧ ∃ n₀ : ℤ, ∀ n : ℤ, n₀ ≤ n →
        ∀ x ∈ tube.{u} (N := 1) (boxOpens a' b'), ∃ (I : Type u) (_ : Fintype I)
          (σ : I → (twistMod 𝒢 n).val.obj (op (tube.{u} (N := 1) (boxOpens a' b'))))
          (W : (relProjectiveSpaceAn.{u} m 1).Opens)
          (hW : W ≤ tube.{u} (N := 1) (boxOpens a' b')), x ∈ W ∧
          GeneratesLocally fun i ↦ modRes (σ i) W hW := by
  obtain ⟨a₀, b₀, hab₀, hB₀U, d, hs, ht⟩ := exists_bundleData 𝒢 h𝒢 hK hne (S := 3) (by norm_num)
  have hann : ∀ {l ρ : ℝ}, 0 < ρ / l → l * ρ ≤ 3 → ρ / l ≤ 3 →
      (boxOpens a₀ b₀ : Set (Fin m → ℂ)) ×ˢ annulusSet (l * ρ) (ρ / l) ⊆
        overlapOpens (prodOpens (boxOpens a₀ b₀) (squareOpens 3))
          (prodOpens (boxOpens a₀ b₀) (squareOpens 3)) := fun hr₁ h₀ h₁ p hp ↦
    overlapOpens_mono (prodOpens_mono le_rfl (ballOpens_le_squareOpens h₀))
      (prodOpens_mono le_rfl (ballOpens_le_squareOpens h₁))
      ((mem_overlapOpens_ballOpens hr₁).2 hp)
  -- the splittings for the annuli `{4/3 < ‖z‖ < 3}` and `{1/3 < ‖z‖ < 3/4}`
  obtain ⟨U₀, hU₀o, hKU₀, hU₀U, k₀, hk₀⟩ := exists_vanishing_scaled (l := 2) (ρ := 3 / 2)
    (by norm_num) (by norm_num) (isOpen_openBox a₀ b₀)
    (d.differentiableOn_G.mono (hann (by norm_num) (by norm_num) (by norm_num)))
    (fun p hp ↦ d.isUnit_G (hann (by norm_num) (by norm_num) (by norm_num) hp))
    (Complex.isCompact_closedBox a b) hab₀
  obtain ⟨U₁, hU₁o, hKU₁, hU₁U, k₁, hk₁⟩ := exists_vanishing_scaled (l := 1 / 2) (ρ := 3 / 2)
    (by norm_num) (by norm_num) (isOpen_openBox a₀ b₀)
    (d.differentiableOn_G.mono (hann (by norm_num) (by norm_num) (by norm_num)))
    (fun p hp ↦ d.isUnit_G (hann (by norm_num) (by norm_num) (by norm_num) hp))
    (Complex.isCompact_closedBox a b) hab₀
  obtain ⟨a', b', hab', hsub'⟩ := exists_openBox_between (hU₀o.inter hU₁o)
    (fun x hx ↦ ⟨hKU₀ hx, hKU₁ hx⟩)
  refine ⟨a', b', hab', fun x hx ↦ hB₀U (hU₀U (hsub' hx).1), (max k₀ k₁ : ℕ) + 1,
    fun n hn x hx ↦ ?_⟩
  obtain ⟨k, rfl⟩ : ∃ k : ℕ, n = (k : ℤ) + 1 := ⟨(n - 1).toNat, by omega⟩
  have hk₀' : k₀ ≤ k := by omega
  have hk₁' : k₁ ≤ k := by omega
  have hBB₀ : boxOpens a' b' ≤ boxOpens a₀ b₀ := fun y hy ↦ hU₀U (hsub' hy).1
  have hsplit₀ : d.Splits (boxOpens a' b') 2 (3 / 2) k :=
    hk₀ k hk₀' _ (fun y hy ↦ (hsub' hy).1) (boxOpens a' b').isOpen
  have hsplit₁ : d.Splits (boxOpens a' b') (1 / 2) (3 / 2) k :=
    hk₁ k hk₁' _ (fun y hy ↦ (hsub' hy).2) (boxOpens a' b').isOpen
  obtain ⟨p, hp1, hp2, hp | hp⟩ := exists_chartPt_norm_le_one hx
  · obtain ⟨σ, W, hW, hxW, hgen⟩ := d.exists_generates_chart_zero hs hBB₀ (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) hsplit₀ hp1
      (c := p.2) (hp2.trans_lt (by norm_num))
    exact ⟨d.I₀, inferInstance, σ, W, hW, hp ▸ hxW, generatesLocally_of hgen⟩
  · obtain ⟨σ, W, hW, hxW, hgen⟩ := d.exists_generates_chart_one ht hBB₀ (by norm_num)
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) hsplit₁ hp1
      (c := p.2) (hp2.trans_lt (by norm_num))
    exact ⟨d.I₁, inferInstance, σ, W, hW, hp ▸ hxW, generatesLocally_of hgen⟩

end ComplexAnalytic.relProjectiveLine

end
