/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.Analytification.GAGA.ProjectiveSpaceAlgebraization
import Oka.Analytification.GAGA.ProjectiveSpaceAnTwistModules
import Oka.AlgebraicGeometry.ProjectiveSpace.SerreVanishing
import Oka.AnalyticSpace.CohomologyModule

/-!
# Analytic Theorem A on `ℙⁿ⁺¹_an` at the points of the hyperplane

Let `M` be a coherent analytic sheaf on `X = ℙⁿ⁺¹_an`, and let `φ : M(-1) ⟶ M` be multiplication
by the last variable `Xₙ₊₁` (`mulXModZero`), with kernel `A` and cokernel `C`. Assume GAGA-3 on
`ℙⁿ` (`ComplexAnalytic.projectiveSpaceAn.CoherentIsAlgebraic n`, the induction hypothesis) and that
`H¹(X, N)` is finite-dimensional for coherent `N` on `X` (Cartan–Serre). Serre's argument:

1. `A` and `C` are killed by the equation of the hyperplane `ι : ℙⁿ_an ⟶ ℙⁿ⁺¹_an`
   (`hyperplaneGerm_smul_kernel`, `hyperplaneGerm_smul_cokernel`), so they are pushed forward from
   `ℙⁿ_an`; by the induction hypothesis, and since analytification commutes with pushforward along
   closed immersions, they are algebraic (`exists_iso_of_hyperplaneGerm_smul`).
2. Hence `Hᵠ(A(m)) = Hᵠ(C(m)) = 0` for `q ≥ 1` and `m ≫ 0` (GAGA-1 and Serre's vanishing theorem,
   `exists_H_twistMod_eq_zero_of_iso`).
3. The maps `H¹(M(m - 1)) → H¹(M(m))` are then surjective for `m ≫ 0`; by finite-dimensionality
   they are eventually bijective, which forces `Γ(M(m)) → Γ(C(m))` to be surjective
   (`exists_surjective_app_top_twistMod_cokernel`, for any `φ : M(-1) ⟶ M`).
4. `C(m)` is generated by finitely many global sections for `m ≫ 0` (algebraic Theorem A,
   `exists_epi_free_twistMod_of_iso`); lifting them to `M(m)` gives `𝒪^I ⟶ M(m)` which is
   surjective on stalks at points of the hyperplane by Nakayama's lemma, since the image of `φ` is
   `Xₙ₊₁ · M` locally and the local equation of the hyperplane vanishes there.
5. Untwisting (`isAlgGeneratedAt_of_surjective_stalk`): `M` is algebraically generated at every
   point of the hyperplane (`isAlgGeneratedAt_of_mem_range_hyperplane`).
-/

open CategoryTheory Limits TopologicalSpace Opposite AlgebraicGeometry
open AlgebraicGeometry.LocallyRingedSpace

universe u

noncomputable section

namespace ComplexAnalytic.projectiveSpaceAn

variable {n : ℕ}

/-- **Algebraic sheaves have vanishing higher cohomology after twisting enough**: if
`A ≅ F^an` with `F` coherent on `ℙⁿ`, then `Hᵠ(ℙⁿ_an, A(m)) = 0` for `q ≥ 1` and `m ≫ 0`. -/
theorem exists_H_twistMod_eq_zero_of_iso
    (A : SheafOfModules.{u} (projectiveSpaceAn.{u} n).toLocallyRingedSpace.ringSheaf)
    (F : SheafOfModules.{u} (projectiveSpace.{u} n).obj.left.toLocallyRingedSpace.ringSheaf)
    [F.IsCoherent] (e : (analytificationModules (projectiveSpace.{u} n)).obj F ≅ A) :
    ∃ m₀ : ℤ, ∀ m : ℤ, m₀ ≤ m → ∀ (q : ℕ) (x : H (twistMod A m) (q + 1)), x = 0 := by
  haveI : IsNoetherianRing (ULift.{u} ℂ) := isNoetherianRing_of_ringEquiv ℂ ULift.ringEquiv.symm
  obtain ⟨m₀, h⟩ := @ProjectiveSpace.exists_locallyRingedSpaceH_twist_eq_zero n (ULift.{u} ℂ) _ _
    F ‹_›
  refine ⟨m₀, fun m hm q x ↦ ?_⟩
  have hc := @ProjectiveSpace.isCoherent_twist n (ULift.{u} ℂ) _ F ‹_› m
  let e' : (analytificationModules (projectiveSpace.{u} n)).obj (ProjectiveSpace.twist F m) ≅
      twistMod A m :=
    analytificationTwistIso F m ≪≫ (twistModFunctor n m).mapIso e
  obtain ⟨y, hy⟩ := (@gaga_projectiveSpace n (ProjectiveSpace.twist F m) hc (q + 1)).2
    (H.map e'.inv (q + 1) x)
  rw [h m hm q y] at hy
  have hy' : H.map e'.inv (q + 1) x = 0 := hy.symm.trans (map_zero _)
  calc x = H.map (e'.inv ≫ e'.hom) (q + 1) x := by
        rw [e'.inv_hom_id]; exact (H.map_id_apply x).symm
    _ = H.map e'.hom (q + 1) (H.map e'.inv (q + 1) x) := H.map_comp_apply _ _ x
    _ = 0 := by rw [hy']; exact map_zero _

variable (n) in
/-- **GAGA-3 on `ℙⁿ`** as a proposition: every coherent analytic sheaf on `ℙⁿ_an` is isomorphic to
the analytification of a coherent algebraic sheaf on `ℙⁿ`. -/
def CoherentIsAlgebraic : Prop :=
  ∀ M : SheafOfModules.{u} (projectiveSpaceAn.{u} n).toLocallyRingedSpace.ringSheaf,
    M.IsCoherent → ∃ F : SheafOfModules.{u}
      (projectiveSpace.{u} n).obj.left.toLocallyRingedSpace.ringSheaf,
      F.IsCoherent ∧ Nonempty ((analytificationModules (projectiveSpace.{u} n)).obj F ≅ M)

/-- **Coherent sheaves on `ℙⁿ⁺¹_an` killed by the equation of the hyperplane are algebraic**,
given GAGA-3 on `ℙⁿ`: such a sheaf is `ι_* N` for the coherent `N = ι^* A` on `ℙⁿ_an`, and
`N ≅ G^an` gives `A ≅ ι_* (G^an) ≅ (ι_* G)^an`. -/
theorem exists_iso_of_hyperplaneGerm_smul (hP : CoherentIsAlgebraic.{u} n)
    (A : SheafOfModules.{u} (projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.ringSheaf)
    [A.IsCoherent]
    (hA : ∀ (l : Fin (n + 1 + 1)) (y : projectiveSpaceAn.{u} (n + 1))
      (hy : (πLRS (n + 1)).base y ∈ ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l)
      (m : ((projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.stalkFunctor y).obj A),
      hyperplaneGerm l y hy • m = 0) :
    ∃ F : SheafOfModules.{u} (projectiveSpace.{u} (n + 1)).obj.left.toLocallyRingedSpace.ringSheaf,
      F.IsCoherent ∧
        Nonempty ((analytificationModules (projectiveSpace.{u} (n + 1))).obj F ≅ A) := by
  obtain ⟨G, hG, ⟨e⟩⟩ := hP _ (isCoherent_pullbackModules_hyperplane A)
  haveI := hG
  haveI : IsLocallyNoetherian (projectiveSpace.{u} (n + 1)).obj.left :=
    LocallyOfFiniteType.isLocallyNoetherian (projectiveSpace.{u} (n + 1)).obj.hom
  exact ⟨_,
    isCoherent_pushforward_of_isClosedImmersion (projectiveSpaceHyperplane.{u} n).hom.left G,
    ⟨asIso (analytificationPushforwardBaseChange (projectiveSpaceHyperplane.{u} n) G) ≪≫
      (SheafOfModules.pushforward.{u} (hyperplaneLRS.{u} n).toRingSheafHom).mapIso e ≪≫
      (hyperplaneUnitIso A hA).symm⟩⟩

section Killed

variable (M : SheafOfModules.{u} (projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.ringSheaf)

/-- The kernel of multiplication by `Xₙ₊₁` is killed by the equation of the hyperplane. -/
lemma hyperplaneGerm_smul_kernel (l : Fin (n + 1 + 1)) (y : projectiveSpaceAn.{u} (n + 1))
    (hy : (πLRS (n + 1)).base y ∈ ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l)
    (a : ((projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.stalkFunctor y).obj
      (kernel (mulXModZero M (Fin.last (n + 1))))) :
    hyperplaneGerm l y hy • a = 0 := by
  rw [hyperplaneGerm_eq]
  exact germ_smul_stalk_kernel_eq_zero _ (xDivAn (n + 1) l (Fin.last _))
    (sMulKerEqZero_mulXModZero M _ l) hy a

/-- The cokernel of multiplication by `Xₙ₊₁` is killed by the equation of the hyperplane. -/
lemma hyperplaneGerm_smul_cokernel (l : Fin (n + 1 + 1)) (y : projectiveSpaceAn.{u} (n + 1))
    (hy : (πLRS (n + 1)).base y ∈ ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l)
    (c : ((projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.stalkFunctor y).obj
      (cokernel (mulXModZero M (Fin.last (n + 1))))) :
    hyperplaneGerm l y hy • c = 0 := by
  rw [hyperplaneGerm_eq]
  exact germ_smul_stalk_cokernel_eq_zero _ (xDivAn (n + 1) l (Fin.last _))
    (sMulLERange_mulXModZero M _ l) hy c

end Killed

section Serre

/-- An antitone sequence of natural numbers is eventually constant. -/
lemma exists_eq_of_succ_le (f : ℕ → ℕ) (hf : ∀ k, f (k + 1) ≤ f k) :
    ∃ K, ∀ k, K ≤ k → f k = f K := by
  have hanti : Antitone f := antitone_nat_of_succ_le hf
  obtain ⟨K, hK⟩ := Nat.sInf_mem (s := Set.range f) ⟨f 0, 0, rfl⟩
  refine ⟨K, fun k hk ↦ le_antisymm (hanti hk) ?_⟩
  rw [hK]
  exact Nat.sInf_le ⟨k, rfl⟩

variable {N : ℕ}

/-- The `ℂ`-linear equivalence on cohomology induced by an isomorphism of sheaves of modules on
`ℙᴺ_an`. -/
def HLinearEquivOfIso
    {P Q : SheafOfModules.{u} (projectiveSpaceAn.{u} N).toLocallyRingedSpace.ringSheaf}
    (e : P ≅ Q) (q : ℕ) : H P q ≃ₗ[ℂ] H Q q :=
  { AnalyticSpace.hMapₗ e.hom q with
    invFun := H.map e.inv q
    left_inv := fun x ↦ by
      change H.map e.inv q (H.map e.hom q x) = x
      rw [← H.map_comp_apply, e.hom_inv_id, H.map_id_apply]
    right_inv := fun x ↦ by
      change H.map e.hom q (H.map e.inv q x) = x
      rw [← H.map_comp_apply, e.inv_hom_id, H.map_id_apply] }

/-- Vanishing of a cohomology group transfers along isomorphisms. -/
lemma H_eq_zero_of_iso
    {P Q : SheafOfModules.{u} (projectiveSpaceAn.{u} N).toLocallyRingedSpace.ringSheaf}
    (e : P ≅ Q) {q : ℕ} (h : ∀ x : H P q, x = 0) (x : H Q q) : x = 0 :=
  (HLinearEquivOfIso e q).symm.injective ((h _).trans (map_zero _).symm)

variable (M : SheafOfModules.{u} (projectiveSpaceAn.{u} N).toLocallyRingedSpace.ringSheaf)
  (φ : twistMod M (-1) ⟶ M)

/-- The short exact sequence `0 → ker φ → M(-1) → im φ → 0`. -/
abbrev imageSeq₁ : ShortComplex (SheafOfModules.{u}
    (projectiveSpaceAn.{u} N).toLocallyRingedSpace.ringSheaf) :=
  ShortComplex.mk (kernel.ι (Abelian.factorThruImage φ)) (Abelian.factorThruImage φ)
    (kernel.condition _)

lemma imageSeq₁_shortExact : (imageSeq₁ M φ).ShortExact :=
  { exact := ShortComplex.exact_of_f_is_kernel _ (kernelIsKernel _) }

/-- The short exact sequence `0 → im φ → M → coker φ → 0`. -/
abbrev imageSeq₂ : ShortComplex (SheafOfModules.{u}
    (projectiveSpaceAn.{u} N).toLocallyRingedSpace.ringSheaf) :=
  ShortComplex.mk (Abelian.image.ι φ) (cokernel.π φ) (kernel.condition _)

lemma imageSeq₂_shortExact : (imageSeq₂ M φ).ShortExact :=
  { exact := ShortComplex.exact_of_f_is_kernel _ (kernelIsKernel _) }

/-- `ker (M(-1) → im φ) ≅ ker φ`. -/
def kernelFactorThruImageIso : kernel (Abelian.factorThruImage φ) ≅ kernel φ :=
  (kernelCompMono _ (Abelian.image.ι φ)).symm ≪≫ kernelIsoOfEq (Abelian.image.fac φ)

variable {M φ} (m : ℤ)
  (hA : ∀ x : H (twistMod (kernel φ) m) 2, x = 0)
  (hC : ∀ x : H (twistMod (cokernel φ) m) 1, x = 0)

include hA in
lemma surjective_H_one_factorThruImage :
    Function.Surjective (H.map ((twistModFunctor N m).map (Abelian.factorThruImage φ)) 1) :=
  fun z ↦ (H.exact₃ ((imageSeq₁_shortExact M φ).map_of_exact (twistModFunctor N m)) 1 2 rfl z).1
    (H_eq_zero_of_iso ((twistModFunctor N m).mapIso (kernelFactorThruImageIso M φ)).symm hA _)

include hC in
lemma surjective_H_one_imageι :
    Function.Surjective (H.map ((twistModFunctor N m).map (Abelian.image.ι φ)) 1) :=
  fun z ↦ (H.exact₂ ((imageSeq₂_shortExact M φ).map_of_exact (twistModFunctor N m)) 1 z).1
    (hC _)

variable (φ) in
/-- `H¹(M(-1)(m)) → H¹(M(m))` induced by `φ`, as a `ℂ`-linear map. -/
def twistHOneMap : H (twistMod (twistMod M (-1)) m) 1 →ₗ[ℂ] H (twistMod M m) 1 :=
  AnalyticSpace.hMapₗ ((twistModFunctor N m).map φ) 1

lemma twistHOneMap_apply (z : H (twistMod (twistMod M (-1)) m) 1) :
    twistHOneMap φ m z = H.map ((twistModFunctor N m).map (Abelian.image.ι φ)) 1
      (H.map ((twistModFunctor N m).map (Abelian.factorThruImage φ)) 1 z) := by
  rw [← H.map_comp_apply, ← Functor.map_comp, Abelian.image.fac]
  rfl

include hA hC in
lemma surjective_twistHOneMap : Function.Surjective (twistHOneMap φ m) := fun z ↦ by
  obtain ⟨z₁, rfl⟩ := surjective_H_one_imageι m hC z
  obtain ⟨z₂, rfl⟩ := surjective_H_one_factorThruImage m hA z₁
  exact ⟨z₂, twistHOneMap_apply m z₂⟩

variable (M) in
/-- `H¹(M(-1)(m)) ≃ H¹(M(m - 1))`. -/
def twistHOneEquiv : H (twistMod (twistMod M (-1)) m) 1 ≃ₗ[ℂ] H (twistMod M (m - 1)) 1 :=
  HLinearEquivOfIso (twistModTwistModIso M (-1) m ≪≫ twistModCongr M (by ring)) 1

include hA hC in
lemma finrank_H_one_twistMod_le [FiniteDimensional ℂ (H (twistMod M (m - 1)) 1)] :
    Module.finrank ℂ (H (twistMod M m) 1) ≤ Module.finrank ℂ (H (twistMod M (m - 1)) 1) := by
  haveI := LinearEquiv.finiteDimensional (twistHOneEquiv M m).symm
  exact (LinearMap.finrank_le_finrank_of_surjective (surjective_twistHOneMap m hA hC)).trans_eq
    (twistHOneEquiv M m).finrank_eq

include hA hC in
/-- If `H¹(M(m - 1))` and `H¹(M(m))` have the same finite dimension, then
`Γ(M(m)) → Γ((coker φ)(m))` is surjective. -/
lemma surjective_app_top_of_finrank_eq [FiniteDimensional ℂ (H (twistMod M (m - 1)) 1)]
    [FiniteDimensional ℂ (H (twistMod M m) 1)]
    (hd : Module.finrank ℂ (H (twistMod M m) 1) = Module.finrank ℂ (H (twistMod M (m - 1)) 1)) :
    Function.Surjective (((twistModFunctor N m).map (cokernel.π φ)).val.app (op ⊤)) := by
  haveI := LinearEquiv.finiteDimensional (twistHOneEquiv M m).symm
  have hLinj : Function.Injective (twistHOneMap φ m) :=
    (LinearMap.injective_iff_surjective_of_finrank_eq_finrank
      ((twistHOneEquiv M m).finrank_eq.trans hd.symm)).2 (surjective_twistHOneMap m hA hC)
  have hinj₂ : Function.Injective
      (H.map ((twistModFunctor N m).map (Abelian.image.ι φ)) 1) := by
    intro a b hab
    obtain ⟨a', ha'⟩ := surjective_H_one_factorThruImage m hA a
    obtain ⟨b', hb'⟩ := surjective_H_one_factorThruImage m hA b
    have h1 : twistHOneMap φ m a' = H.map ((twistModFunctor N m).map (Abelian.image.ι φ)) 1 a :=
      (twistHOneMap_apply m a').trans (congrArg _ ha')
    have h2 : twistHOneMap φ m b' = H.map ((twistModFunctor N m).map (Abelian.image.ι φ)) 1 b :=
      (twistHOneMap_apply m b').trans (congrArg _ hb')
    have : twistHOneMap φ m a' = twistHOneMap φ m b' := h1.trans (hab.trans h2.symm)
    exact ha'.symm.trans ((congrArg _ (hLinj this)).trans hb')
  have hS := (imageSeq₂_shortExact M φ).map_of_exact (twistModFunctor N m)
  intro t
  obtain ⟨w, hw⟩ := (H.equiv₀ ((twistModFunctor N m).obj (cokernel φ))).surjective t
  obtain ⟨v, hv⟩ := (H.exact₃ hS 0 1 rfl w).1
    (hinj₂ (((H.exact₁ hS 0 1 rfl _).2 ⟨w, rfl⟩).trans (map_zero _).symm))
  refine ⟨H.equiv₀ _ v, ?_⟩
  rw [← hw, ← hv]
  exact (H.equiv₀_map _ v).symm

variable (M φ) in
/-- **Serre's dimension argument.** Let `φ : M(-1) ⟶ M` be such that the twists of its kernel and
cokernel have vanishing higher cohomology for `m ≫ 0`, and `H¹(M(k))` is finite-dimensional for
all `k`. Then `Γ(M(m)) → Γ((coker φ)(m))` is surjective for `m ≫ 0`: the maps
`H¹(M(m-1)) → H¹(M(m))` are eventually surjective, hence eventually bijective by finiteness,
which kills the connecting map `H⁰((coker φ)(m)) → H¹((im φ)(m))`. -/
theorem exists_surjective_app_top_twistMod_cokernel
    (hfin : ∀ k : ℤ, FiniteDimensional ℂ (H (twistMod M k) 1))
    (hA : ∃ m₀ : ℤ, ∀ m : ℤ, m₀ ≤ m → ∀ (q : ℕ) (x : H (twistMod (kernel φ) m) (q + 1)), x = 0)
    (hC : ∃ m₀ : ℤ, ∀ m : ℤ, m₀ ≤ m →
      ∀ (q : ℕ) (x : H (twistMod (cokernel φ) m) (q + 1)), x = 0) :
    ∃ m₁ : ℤ, ∀ m : ℤ, m₁ ≤ m →
      Function.Surjective (((twistModFunctor N m).map (cokernel.π φ)).val.app (op ⊤)) := by
  obtain ⟨a₀, ha⟩ := hA
  obtain ⟨c₀, hc⟩ := hC
  let m₀ := max a₀ c₀
  have hA' (m : ℤ) (hm : m₀ ≤ m) := ha m ((le_max_left _ _).trans hm) 1
  have hC' (m : ℤ) (hm : m₀ ≤ m) := hc m ((le_max_right _ _).trans hm) 0
  let d : ℤ → ℕ := fun k ↦ Module.finrank ℂ (H (twistMod M k) 1)
  have hd (m : ℤ) (hm : m₀ ≤ m) : d m ≤ d (m - 1) :=
    haveI := hfin (m - 1)
    finrank_H_one_twistMod_le m (hA' m hm) (hC' m hm)
  obtain ⟨K, hK⟩ := exists_eq_of_succ_le (fun k ↦ d (m₀ + k)) fun k ↦ by
    have := hd (m₀ + (k + 1 : ℕ)) (by omega)
    rwa [show m₀ + ((k + 1 : ℕ) : ℤ) - 1 = m₀ + k by push_cast; ring] at this
  refine ⟨m₀ + K + 1, fun m hm ↦ ?_⟩
  have hm₀ : m₀ ≤ m := by omega
  have hdm : d m = d (m - 1) := by
    obtain ⟨k, rfl⟩ : ∃ k : ℕ, m = m₀ + (k + 1 : ℕ) := ⟨(m - m₀ - 1).toNat, by omega⟩
    have h1 := hK (k + 1) (by omega)
    have h2 := hK k (by omega)
    rw [show m₀ + ((k + 1 : ℕ) : ℤ) - 1 = m₀ + k by push_cast; ring]
    exact h1.trans h2.symm
  haveI := hfin (m - 1)
  haveI := hfin m
  exact surjective_app_top_of_finrank_eq m (hA' m hm₀) (hC' m hm₀) hdm

end Serre

/-- At a point of the hyperplane, the germ of its local equation lies in the maximal ideal. -/
lemma hyperplaneGerm_mem_maximalIdeal (l : Fin (n + 1 + 1)) (y : projectiveSpaceAn.{u} (n + 1))
    (hy : (πLRS (n + 1)).base y ∈ ProjectiveSpace.U (n + 1) (ULift.{u} ℂ) l)
    (hyr : y ∈ Set.range (hyperplaneLRS.{u} n).base) :
    hyperplaneGerm l y hy ∈ IsLocalRing.maximalIdeal _ := by
  obtain ⟨z, rfl⟩ := hyr
  have h := hyperplaneGerm_mem l _ hy
  rw [(hyperplaneLRS.{u} n).pushforwardStalkIdeal_eq_ker
    isClosedEmbedding_hyperplaneLRS.isInducing z, RingHom.mem_ker] at h
  rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff]
  intro hu
  have := hu.map ((hyperplaneLRS.{u} n).stalkMap z).hom
  rw [h] at this
  exact not_isUnit_zero this

section Generation

variable {N : ℕ}

/-- **Algebraic sheaves are globally generated after twisting enough** (Serre's theorem A on `ℙᴺ`,
analytified): if `C ≅ F^an` with `F` coherent, then for `m ≫ 0` there is an epimorphism
`𝒪^I ⟶ C(m)` with `I` finite. -/
theorem exists_epi_free_twistMod_of_iso
    (C : SheafOfModules.{u} (projectiveSpaceAn.{u} N).toLocallyRingedSpace.ringSheaf)
    (F : SheafOfModules.{u} (projectiveSpace.{u} N).obj.left.toLocallyRingedSpace.ringSheaf)
    [hF : F.IsCoherent] (e : (analytificationModules (projectiveSpace.{u} N)).obj F ≅ C) :
    ∃ m₂ : ℕ, ∀ m : ℕ, m₂ ≤ m → ∃ (I : Type u) (_ : Finite I)
      (τ : SheafOfModules.free I ⟶ twistMod C m), Epi τ := by
  have hq := SheafOfModules.IsCoherent.isQuasicoherent (F : ℙ(N; ULift.{u} ℂ).Modules)
  obtain ⟨m₂, hm₂⟩ := @ProjectiveSpace.exists_epi_freeMk_twist N (ULift.{u} ℂ) _ F hq
    hF.isFiniteType
  refine ⟨m₂, fun m hm ↦ ?_⟩
  obtain ⟨I, hI, σ, hσ⟩ := hm₂ m hm
  let an := analytificationModules (projectiveSpace.{u} N)
  haveI : Epi (C := SheafOfModules.{u}
      (projectiveSpace.{u} N).obj.left.toLocallyRingedSpace.ringSheaf)
      (Scheme.Modules.freeMk (ProjectiveSpace.twist (F : ℙ(N; ULift.{u} ℂ).Modules) m) σ) :=
    hσ
  have h₂ : Epi (an.map
      (Scheme.Modules.freeMk (ProjectiveSpace.twist (F : ℙ(N; ULift.{u} ℂ).Modules) m) σ)) :=
    an.map_epi _
  have h₁ : Epi ((πLRS N).pullbackModulesFreeIso I).inv := inferInstance
  have h₃ : Epi (analytificationTwistIso F m ≪≫ (twistModFunctor _ m).mapIso e).hom :=
    inferInstance
  exact ⟨I, hI, ((πLRS N).pullbackModulesFreeIso I).inv ≫ an.map
      (Scheme.Modules.freeMk (ProjectiveSpace.twist (F : ℙ(N; ULift.{u} ℂ).Modules) m) σ) ≫
      (analytificationTwistIso F m ≪≫ (twistModFunctor _ m).mapIso e).hom,
    @epi_comp _ _ _ _ _ _ h₁ _ (@epi_comp _ _ _ _ _ _ h₂ _ h₃)⟩

/-- Every point of `ℙᴺ_an` lies in some `π⁻¹ Uₖ`. -/
lemma exists_mem_stdOpenAn (y : projectiveSpaceAn.{u} N) : ∃ k, y ∈ stdOpenAn.{u} N k :=
  Opens.mem_iSup.1 (by rw [iSup_stdOpenAn]; trivial)

/-- **Untwisting**: a morphism `𝒪^I ⟶ M(m)` surjective on the stalk at `y` makes `M`
algebraically generated at `y`, through `(𝒪^I(-m))^an ≅ 𝒪^I(-m) ⟶ M`. -/
theorem isAlgGeneratedAt_of_surjective_stalk
    (M : SheafOfModules.{u} (projectiveSpaceAn.{u} N).toLocallyRingedSpace.ringSheaf)
    {m : ℕ} {I : Type u} [Finite I] (σ : SheafOfModules.free I ⟶ twistMod M m)
    (y : projectiveSpaceAn.{u} N)
    (hσ : Function.Surjective
      (((projectiveSpaceAn.{u} N).toLocallyRingedSpace.stalkFunctor y).map σ)) :
    IsAlgGeneratedAt M y := by
  haveI : IsNoetherianRing (ULift.{u} ℂ) := isNoetherianRing_of_ringEquiv ℂ ULift.ringEquiv.symm
  haveI : IsLocallyNoetherian ℙ(N; ULift.{u} ℂ) :=
    LocallyOfFiniteType.isLocallyNoetherian (ProjectiveSpace.toSpec N (ULift.{u} ℂ))
  haveI := Scheme.isCoherent_free (X := ℙ(N; ULift.{u} ℂ)) I
  obtain ⟨k, hk⟩ := exists_mem_stdOpenAn y
  have h : Function.Surjective
      (((projectiveSpaceAn.{u} N).toLocallyRingedSpace.stalkFunctor y).map
        ((twistModFunctor N (-(m : ℤ))).map σ)) :=
    (surjective_stalk_modTwistMap_iff _ iSup_stdOpenAn hk σ).2 hσ
  let e₁ := analytificationTwistIso (SheafOfModules.free I) (-(m : ℤ)) ≪≫
    (twistModFunctor N (-(m : ℤ))).mapIso ((πLRS N).pullbackModulesFreeIso I)
  let e₂ := twistModTwistModIso M m (-(m : ℤ)) ≪≫ twistModCongr M (add_neg_cancel _) ≪≫
    twistModZeroIso M
  refine ⟨_, ProjectiveSpace.isCoherent_twist
    (SheafOfModules.free I : ℙ(N; ULift.{u} ℂ).Modules) (-(m : ℤ)),
    e₁.hom ≫ (twistModFunctor N (-(m : ℤ))).map σ ≫ e₂.hom, ?_⟩
  rw [surjective_stalk_iso_comp_iff, surjective_stalk_comp_iso_iff]
  exact h

end Generation

/-- **Analytic Theorem A at the points of the hyperplane** (Serre): assume GAGA-3 on `ℙⁿ` and
finite-dimensionality of `H¹` of coherent sheaves on `ℙⁿ⁺¹_an`. Then every coherent sheaf `M` on
`ℙⁿ⁺¹_an` is algebraically generated at every point of the hyperplane `ℙⁿ_an ⊆ ℙⁿ⁺¹_an`: for
`m ≫ 0`, global sections of `M(m)` generate the stalks of `M(m)` at these points. -/
theorem isAlgGeneratedAt_of_mem_range_hyperplane (hP : CoherentIsAlgebraic.{u} n)
    (hFin : ∀ M : SheafOfModules.{u} (projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.ringSheaf,
      M.IsCoherent → FiniteDimensional ℂ (H M 1))
    (M : SheafOfModules.{u} (projectiveSpaceAn.{u} (n + 1)).toLocallyRingedSpace.ringSheaf)
    [M.IsCoherent] (y : projectiveSpaceAn.{u} (n + 1))
    (hyr : y ∈ Set.range (hyperplaneLRS.{u} n).base) :
    IsAlgGeneratedAt M y := by
  haveI : IsNoetherianRing (ULift.{u} ℂ) := isNoetherianRing_of_ringEquiv ℂ ULift.ringEquiv.symm
  haveI : IsLocallyNoetherian ℙ(n + 1; ULift.{u} ℂ) :=
    LocallyOfFiniteType.isLocallyNoetherian (ProjectiveSpace.toSpec (n + 1) (ULift.{u} ℂ))
  let φ := mulXModZero M (Fin.last (n + 1))
  haveI := isCoherent_twistMod M (-1)
  haveI : (kernel φ).IsCoherent := SheafOfModules.IsCoherent.kernel φ
  haveI : (cokernel φ).IsCoherent := SheafOfModules.IsCoherent.cokernel φ
  obtain ⟨FA, hFA, ⟨eA⟩⟩ := exists_iso_of_hyperplaneGerm_smul hP (kernel φ)
    (hyperplaneGerm_smul_kernel M)
  obtain ⟨FC, hFC, ⟨eC⟩⟩ := exists_iso_of_hyperplaneGerm_smul hP (cokernel φ)
    (hyperplaneGerm_smul_cokernel M)
  haveI := hFA
  haveI := hFC
  obtain ⟨m₁, hm₁⟩ := exists_surjective_app_top_twistMod_cokernel M φ
    (fun k ↦ hFin _ (isCoherent_twistMod M k)) (exists_H_twistMod_eq_zero_of_iso _ FA eA)
    (exists_H_twistMod_eq_zero_of_iso _ FC eC)
  obtain ⟨m₂, hm₂⟩ := exists_epi_free_twistMod_of_iso (cokernel φ) FC eC
  let m : ℕ := max m₂ m₁.toNat
  have hm : m₁ ≤ (m : ℤ) := by omega
  obtain ⟨I, hI, τ, hτ⟩ := hm₂ m (le_max_left _ _)
  haveI := hI
  haveI := hτ
  obtain ⟨σ', hσ'⟩ := exists_surjective_stalk_comp_of_surjective_app_top (M := twistMod M m)
    (C := twistMod (cokernel φ) m) ((twistModFunctor _ m).map (cokernel.π φ)) (hm₁ m hm) τ
  obtain ⟨k, hk⟩ := exists_mem_stdOpenAn y
  have hx := hyperplaneGerm_mem_maximalIdeal k y hk hyr
  rw [hyperplaneGerm_eq] at hx
  refine isAlgGeneratedAt_of_surjective_stalk M σ' y ?_
  haveI : ((twistModFunctor (n + 1) m).obj M).IsFiniteType := (isCoherent_twistMod M m).isFiniteType
  refine surjective_stalk_of_surjective_stalk_comp_cokernel ((twistModFunctor _ m).map φ)
    (xDivAn (n + 1) k (Fin.last _)) σ'
    ((rangeLESMul_mulXModZero M (Fin.last _) k).modTwistMap _ k le_rfl) hk hx ?_
  rw [← PreservesCokernel.π_iso_hom, ← Category.assoc, surjective_stalk_comp_iso_iff]
  exact hσ' y

end ComplexAnalytic.projectiveSpaceAn
