/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.AlgebraicGeometry.Modules.Support

/-!
# Stalks of the ideal of a closed subscheme

Let `I` be a quasi-coherent ideal sheaf on a scheme `X`, with closed subscheme
`ι : V(I) ⟶ X`. Write `I_y = ι.pushforwardStalkIdeal y ⊆ 𝒪_{X,y}` for the kernel of
`𝒪_{X,y} → (ι_* 𝒪_{V(I)})_y`. For an affine open `U ∋ y`, `I_y` is generated by the germs of
`I(U)` (`AlgebraicGeometry.Scheme.IdealSheafData.pushforwardStalkIdeal_subschemeι`). Consequently
the stalk of the ideal of `V(Iⁿ)` is the `n`-th power of that of `V(I)`
(`AlgebraicGeometry.Scheme.IdealSheafData.pushforwardStalkIdeal_subschemeι_pow`), and for closed
subsets `Z, Z'` agreeing near `y` up to `Z ⊆ Z'`, the stalk at `y` of the ideal of `Z'_red` is
contained in that of `Z_red`
(`AlgebraicGeometry.Scheme.IdealSheafData.pushforwardStalkIdeal_subschemeι_vanishingIdeal_le`).
-/

open CategoryTheory TopologicalSpace Opposite

universe u

namespace AlgebraicGeometry.Scheme.IdealSheafData

variable {X : Scheme.{u}} (I : X.IdealSheafData)

/-- The germ of a section of `I` over an affine open lies in the stalk of the ideal of `V(I)`. -/
lemma germ_mem_pushforwardStalkIdeal_subschemeι (U : X.affineOpens) (y : X) (hy : y ∈ U.1)
    (s : Γ(X, U.1)) (hs : s ∈ I.ideal U) :
    X.presheaf.germ U.1 y hy s ∈ I.subschemeι.toLRSHom.pushforwardStalkIdeal y := by
  refine I.subschemeι.toLRSHom.germ_mem_pushforwardStalkIdeal y hy s ?_
  rw [← I.ker_subschemeι_app U] at hs
  exact hs

/-- **The stalk of the ideal of a closed subscheme**: for an affine open `U ∋ y`, the kernel of
`𝒪_{X,y} → (ι_* 𝒪_{V(I)})_y` is generated by the germs of `I(U)`. -/
theorem pushforwardStalkIdeal_subschemeι (U : X.affineOpens) (y : X) (hy : y ∈ U.1) :
    I.subschemeι.toLRSHom.pushforwardStalkIdeal y =
      (I.ideal U).map (X.presheaf.germ U.1 y hy).hom := by
  refine le_antisymm (fun r hr ↦ ?_) (Ideal.map_le_iff_le_comap.2 fun s hs ↦
    I.germ_mem_pushforwardStalkIdeal_subschemeι U y hy s hs)
  obtain ⟨V, hyV, s, hs0, rfl⟩ :=
    I.subschemeι.toLRSHom.exists_germ_eq_of_mem_pushforwardStalkIdeal y r hr
  obtain ⟨h, hhV, hyh⟩ := U.2.exists_basicOpen_le (V := V) ⟨y, hyV⟩ hy
  let s' : Γ(X, X.basicOpen h) := X.presheaf.map (homOfLE hhV).op s
  have hs' : s' ∈ I.ideal (X.affineBasicOpen h) := by
    rw [← I.ker_subschemeι_app]
    exact I.subschemeι.app_map_eq_zero hhV s hs0
  rw [← I.map_ideal (X.affineBasicOpen_le h)] at hs'
  have key : (I.ideal U).map (X.presheaf.map (homOfLE (X.affineBasicOpen_le h)).op).hom ≤
      ((I.ideal U).map (X.presheaf.germ U.1 y hy).hom).comap
        (X.presheaf.germ (X.basicOpen h) y hyh).hom := by
    refine Ideal.map_le_iff_le_comap.2 fun a ha ↦ ?_
    have e : X.presheaf.germ (X.basicOpen h) y hyh
        (X.presheaf.map (homOfLE (X.affineBasicOpen_le h)).op a) = X.presheaf.germ U.1 y hy a :=
      TopCat.Presheaf.germ_res_apply _ _ _ _ _
    refine Ideal.mem_comap.2 ?_
    change X.presheaf.germ (X.basicOpen h) y hyh
      (X.presheaf.map (homOfLE (X.affineBasicOpen_le h)).op a) ∈
        (I.ideal U).map (X.presheaf.germ U.1 y hy).hom
    rw [e]
    exact Ideal.mem_map_of_mem _ ha
  have e2 : X.presheaf.germ (X.basicOpen h) y hyh s' = X.presheaf.germ V y hyV s :=
    TopCat.Presheaf.germ_res_apply _ _ _ _ _
  rw [← e2]
  exact key hs'

/-- The stalk of the ideal of `V(Iⁿ)` is the `n`-th power of the stalk of the ideal of `V(I)`. -/
theorem pushforwardStalkIdeal_subschemeι_pow (n : ℕ) (y : X) :
    (I ^ n).subschemeι.toLRSHom.pushforwardStalkIdeal y =
      I.subschemeι.toLRSHom.pushforwardStalkIdeal y ^ n := by
  obtain ⟨U, hU⟩ : ∃ U : X.affineOpens, y ∈ (U : X.Opens) :=
    Opens.mem_iSup.1 (by rw [iSup_affineOpens_eq_top]; trivial)
  rw [pushforwardStalkIdeal_subschemeι _ U y hU, pushforwardStalkIdeal_subschemeι _ U y hU,
    ← Ideal.map_pow, ideal_pow, Pi.pow_apply]

/-- If `Z ⊆ Z'` near `y`, the stalk at `y` of the ideal of the reduced subscheme on `Z'` is
contained in that of the reduced subscheme on `Z`. -/
theorem pushforwardStalkIdeal_subschemeι_vanishingIdeal_le {Z Z' : Closeds X} {y : X}
    {V : X.Opens} (hyV : y ∈ V) (hV : (Z : Set X) ∩ V ⊆ Z') :
    (vanishingIdeal Z').subschemeι.toLRSHom.pushforwardStalkIdeal y ≤
      (vanishingIdeal Z).subschemeι.toLRSHom.pushforwardStalkIdeal y := by
  obtain ⟨_, ⟨U, hU, rfl⟩, hyU, hUV⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open (SetLike.mem_coe.2 hyV) V.isOpen
  rw [pushforwardStalkIdeal_subschemeι _ ⟨U, hU⟩ y hyU,
    pushforwardStalkIdeal_subschemeι _ ⟨U, hU⟩ y hyU]
  refine Ideal.map_mono ?_
  rw [vanishingIdeal_ideal, vanishingIdeal_ideal]
  refine PrimeSpectrum.vanishingIdeal_anti_mono fun p hp ↦ hV ⟨hp, hUV ?_⟩
  exact hU.range_fromSpec ▸ Set.mem_range_self p

end AlgebraicGeometry.Scheme.IdealSheafData
