/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.Statement
import Oka.StructureSheaf
import Oka.Algebra.Category.ModuleCat.Sheaf.Coherent.Criterion

/-!
# Oka's coherence theorem

We deduce from `oka` that the structure sheaf of `ℂ^ι` is a coherent sheaf of modules over
itself.
-/

open CategoryTheory Limits TopologicalSpace Opposite SheafOfModules

universe u

section OpensSite

variable {T : Type u} [TopologicalSpace T]

/-- A family of open subsets of `X` covering `X` covers the terminal object of the slice site
over `X`. -/
lemma coversTop_over (X : Opens T) {A : Type u} (V : A → Opens T) (hle : ∀ a, V a ≤ X)
    (hcov : ∀ x ∈ X, ∃ a, x ∈ V a) :
    ((Opens.grothendieckTopology T).over X).CoversTop (fun a ↦ Over.mk (homOfLE (hle a))) := by
  intro Z
  let S : Sieve Z.left :=
    ⟨fun W _ ↦ ∃ a, W ≤ V a, by rintro W₁ W₂ f ⟨a, ha⟩ g; exact ⟨a, (leOfHom g).trans ha⟩⟩
  have hS : S ∈ Opens.grothendieckTopology T Z.left := by
    intro x hx
    obtain ⟨a, ha⟩ := hcov x (leOfHom Z.hom hx)
    exact ⟨Z.left ⊓ V a, homOfLE inf_le_left, ⟨a, inf_le_right⟩, ⟨hx, ha⟩⟩
  refine GrothendieckTopology.superset_covering _ ?_
    (GrothendieckTopology.overEquiv_symm_mem_over _ Z S hS)
  rintro W g ⟨a, ha⟩
  exact ⟨a, ⟨Over.homMk (homOfLE ha)⟩⟩

end OpensSite

section LinOfFun

variable {A : Type*} [CommRing A] {n : ℕ}

lemma linOfFun_apply (f : Fin n → A) (a : Fin n → A) :
    linOfFun f a = ∑ i, a i * f i := by
  simp [linOfFun, Module.Basis.constr_apply_fintype, mul_comm]

end LinOfFun

variable (ι : Type u) [Fintype ι]

set_option maxHeartbeats 1000000 in
-- the proof repeatedly identifies sections of the (iterated) restrictions of the sheaves of
-- modules involved with rings of holomorphic functions, which is definitionally expensive
/-- **Oka's coherence theorem**: the structure sheaf of `ℂ^ι` is a coherent sheaf of modules
over itself. -/
theorem isCoherent_unit_okaSheaf : (unit (okaSheaf ι)).IsCoherent := by
  classical
  haveI : (unit (okaSheaf ι)).IsFiniteType := by apply SheafOfModules.isFiniteType_unit
  refine isCoherent_of_forall_kernel (M := unit (okaSheaf ι)) ?_
  intro X I hI φ
  haveI := hI
  haveI : Fintype I := Fintype.ofFinite I
  obtain ⟨m, ⟨e⟩⟩ := Finite.exists_equiv_fin I
  -- the family of sections of `𝒪` over `X` defined by `φ`
  set f : Fin m → OkaRing X := fun i ↦
    PresheafOfModules.sections.eval (freeHomEquiv _ φ (e.symm i)) (op (Over.mk (𝟙 X))) with hf
  -- `oka` provides, near every point of `X`, finitely many generators of the relations
  choose V hVX k g hxV hgen using fun (x : X) ↦ oka (U := X) f x.1 x.2
  refine ⟨↥X, fun a ↦ Over.mk (homOfLE (hVX a)),
    coversTop_over X V hVX (fun x hx ↦ ⟨⟨x, hx⟩, hxV ⟨x, hx⟩⟩), fun a ↦ ?_⟩
  -- the open set on which the relations between the `f i` are generated by the `g l`
  set Ya : Over X := Over.mk (homOfLE (hVX a))
  set L := ULift.{u} (Fin (k a))
  -- for an object `W` over `Ya`, the underlying open set is contained in `V a`
  have hWV : ∀ W : (Over Ya)ᵒᵖ, W.unop.left.left ≤ V a := fun W ↦ leOfHom W.unop.hom.left
  have hWX : ∀ W : (Over Ya)ᵒᵖ, W.unop.left.left ≤ X := fun W ↦ (hWV W).trans (hVX a)
  -- the generators, as sections of the free sheaf over `Ya`
  set ψ : free L ⟶ (free I).over Ya :=
    (freeHomEquiv _).symm (fun l ↦ sectionOfTerminal Over.mkIdTerminal ((free I).over Ya)
      (freeEvalSymm (R := (okaSheaf ι).over X) (I := I) (op (Over.mk (𝟙 Ya)).left)
        (fun i ↦ g a l.down (e i)))) with hψ
  -- the coordinates of `φ` applied to a section of the free sheaf
  have key_φ : ∀ (W : (Over Ya)ᵒᵖ) (b : ((free I).over Ya).val.obj W)
      (bc : I → OkaRing W.unop.left.left) (_ : ∀ i, bc i = freeEval (op W.unop.left) b i)
      (v : OkaRing W.unop.left.left) (_ : v = (φ.over Ya).val.app W b),
      v = ∑ i : I, bc i * OkaRing.restrict (hWX W) (f (e i)) := by
    intro W b bc hbc v hv
    have hsec : ∀ i : I, (PresheafOfModules.sections.eval (freeHomEquiv _ φ i)
        (op W.unop.left) : OkaRing W.unop.left.left) =
        OkaRing.restrict (hWX W) (f (e i)) := by
      intro i
      simp only [hf, Equiv.symm_apply_apply]
      exact (PresheafOfModules.sections_property (freeHomEquiv _ φ i)
        (Over.mkIdTerminal.from W.unop.left).op).symm
    rw [hv, show (φ.over Ya).val.app W b = φ.val.app (op W.unop.left) b from rfl,
      val_app_eq_sum]
    refine Finset.sum_congr rfl (fun i _ ↦ ?_)
    rw [hbc i, ← hsec i]
    rfl
  -- the coordinates of `ψ` applied to a section of the free sheaf
  have key_ψ : ∀ (W : (Over Ya)ᵒᵖ) (c : (free L).val.obj W)
      (cc : L → OkaRing W.unop.left.left) (_ : ∀ l, cc l = freeEval W c l) (i : I)
      (v : OkaRing W.unop.left.left) (_ : v = freeEval (op W.unop.left) (ψ.val.app W c) i),
      v = ∑ l : L, cc l * OkaRing.restrict (hWV W) (g a l.down (e i)) := by
    intro W c cc hcc i v hv
    -- the coefficients and the rows of `g`, as sections of the sheaf of rings
    obtain ⟨cc', hcc'⟩ : ∃ cc' : L → ((okaSheaf ι).over X).obj.obj (op W.unop.left),
        ∀ l, cc' l = cc l := ⟨fun l ↦ cc l, fun _ ↦ rfl⟩
    obtain ⟨vv, hvv⟩ : ∃ vv : L → I → ((okaSheaf ι).over X).obj.obj (op W.unop.left),
        ∀ l i, vv l i = OkaRing.restrict (hWV W) (g a l.down (e i)) :=
      ⟨fun l i ↦ OkaRing.restrict (hWV W) (g a l.down (e i)), fun _ _ ↦ rfl⟩
    -- the sections defining `ψ` are the restrictions of the rows of `g`
    have hsec : ∀ l : L, PresheafOfModules.sections.eval (freeHomEquiv _ ψ l) W =
        freeEvalSymm (op W.unop.left) (vv l) := by
      intro l
      rw [hψ, Equiv.apply_symm_apply, sectionOfTerminal_val,
        show vv l = fun i ↦ OkaRing.restrict (hWV W) (g a l.down (e i)) from funext (hvv l)]
      exact map_freeEvalSymm (R := (okaSheaf ι).over X) (I := I)
        ((Over.mkIdTerminal.from W.unop).left).op (fun i ↦ g a l.down (e i))
    -- hence `ψ` acts by multiplication with the matrix `g`
    have h1 : ψ.val.app W c = freeEvalSymm (op W.unop.left)
        (fun i ↦ ∑ l : L, cc l * OkaRing.restrict (hWV W) (g a l.down (e i))) := by
      have hrhs : freeEvalSymm (R := (okaSheaf ι).over X) (I := I) (op W.unop.left)
          (fun i ↦ ∑ l : L, cc l * OkaRing.restrict (hWV W) (g a l.down (e i))) =
          ∑ l : L, cc' l • freeEvalSymm (op W.unop.left) (vv l) := by
        have hpi : (fun i ↦ ∑ l : L, cc l * OkaRing.restrict (hWV W) (g a l.down (e i))) =
            ∑ l : L, cc' l • vv l := by
          funext i
          rw [Finset.sum_apply]
          refine Finset.sum_congr rfl (fun l _ ↦ ?_)
          rw [Pi.smul_apply, hcc', hvv]
          rfl
        refine (congrArg (freeEvalSymm (R := (okaSheaf ι).over X) (I := I)
          (op W.unop.left)) hpi).trans ((map_sum _ _ _).trans ?_)
        exact Finset.sum_congr rfl (fun l _ ↦ map_smul _ _ _)
      rw [val_app_eq_sum, hrhs]
      simp only [hsec, hcc', hcc]
      rfl
    rw [hv, h1]
    exact congrFun (freeEval_freeEvalSymm _ _) i
  -- the generators are relations between the `f i`
  have hgker : ∀ (W' : Opens (ι → ℂ)) (h : W' ≤ V a) (l : Fin (k a)),
      ∑ j : Fin m, OkaRing.restrict h (g a l j) *
        OkaRing.restrict (h.trans (hVX a)) (f j) = 0 := by
    intro W' h l
    have hmem : (fun j ↦ OkaRing.restrict h (g a l j)) ∈
        LinearMap.ker (linOfFun fun j : Fin m ↦ OkaRing.restrict (le_trans h (hVX a)) (f j)) := by
      rw [hgen a W' h h]
      exact Submodule.subset_span ⟨l, rfl⟩
    rw [LinearMap.mem_ker, linOfFun_apply] at hmem
    exact hmem
  refine ⟨L, inferInstance, ψ, ?_, ?_⟩
  · -- the sections `g l` are relations between the `f i`
    ext W c
    obtain ⟨cc, hcc⟩ : ∃ cc : L → OkaRing W.unop.left.left, ∀ l, cc l = freeEval W c l :=
      ⟨fun l ↦ freeEval W c l, fun _ ↦ rfl⟩
    obtain ⟨v, hv⟩ : ∃ v : OkaRing W.unop.left.left,
        v = (φ.over Ya).val.app W (ψ.val.app W c) := ⟨_, rfl⟩
    have h0 : v = 0 := by
      rw [key_φ W (ψ.val.app W c)
        (fun i ↦ ∑ l : L, cc l * OkaRing.restrict (hWV W) (g a l.down (e i)))
        (fun i ↦ (key_ψ W c cc hcc i _ rfl).symm) v hv]
      have hterm : ∀ i : I, (∑ l : L, cc l *
          OkaRing.restrict (hWV W) (g a l.down (e i))) *
            OkaRing.restrict (hWX W) (f (e i)) =
          ∑ l : L, cc l *
            (OkaRing.restrict (hWV W) (g a l.down (e i)) *
              OkaRing.restrict (hWX W) (f (e i))) := by
        intro i
        rw [Finset.sum_mul]
        exact Finset.sum_congr rfl (fun l _ ↦ mul_assoc _ _ _)
      simp only [hterm]
      rw [Finset.sum_comm]
      refine Finset.sum_eq_zero (fun l _ ↦ ?_)
      rw [← Finset.mul_sum, Equiv.sum_comp e (fun j : Fin m ↦
        OkaRing.restrict (hWV W) (g a l.down j) * OkaRing.restrict (hWX W) (f j)),
        hgker _ (hWV W) l.down, mul_zero]
    exact hv.symm.trans h0
  · -- every relation is generated by the sections `g l`
    intro W b hb
    obtain ⟨bc, hbc⟩ : ∃ bc : I → OkaRing W.unop.left.left,
        ∀ i, bc i = freeEval (op W.unop.left) b i :=
      ⟨fun i ↦ freeEval (op W.unop.left) b i, fun _ ↦ rfl⟩
    have hcker : (fun j ↦ bc (e.symm j)) ∈ LinearMap.ker
        (linOfFun fun j : Fin m ↦ OkaRing.restrict (hWX W) (f j)) := by
      rw [LinearMap.mem_ker, linOfFun_apply,
        ← Equiv.sum_comp e (fun j : Fin m ↦ bc (e.symm j) * OkaRing.restrict (hWX W) (f j))]
      obtain ⟨v, hv⟩ : ∃ v : OkaRing W.unop.left.left,
          v = (φ.over Ya).val.app W b := ⟨_, rfl⟩
      have h0 : v = 0 := hv.trans hb
      rw [key_φ W b bc hbc v hv] at h0
      simpa only [Equiv.symm_apply_apply] using h0
    rw [hgen a W.unop.left.left (hWV W) (hWV W)] at hcker
    obtain ⟨r, hr⟩ :=
      (Submodule.mem_span_range_iff_exists_fun (OkaRing W.unop.left.left)).1 hcker
    refine ⟨freeEvalSymm W (fun l : L ↦ (r l.down : OkaRing W.unop.left.left)), ?_⟩
    refine freeEval_injective (op W.unop.left) (funext fun i ↦ ?_)
    have h1 := key_ψ W (freeEvalSymm W (fun l : L ↦ (r l.down : OkaRing W.unop.left.left)))
      (fun l ↦ r l.down)
      (fun l ↦ (congrFun (freeEval_freeEvalSymm (R := ((okaSheaf ι).over X).over Ya) (I := L) W
        (fun l : L ↦ (r l.down : OkaRing W.unop.left.left))) l).symm) i _ rfl
    have hsum : (∑ l : L, (r l.down : OkaRing W.unop.left.left) *
        OkaRing.restrict (hWV W) (g a l.down (e i))) =
        ∑ j : Fin (k a), r j * OkaRing.restrict (hWV W) (g a j (e i)) :=
      Fintype.sum_equiv Equiv.ulift _ _ (fun _ ↦ rfl)
    have h2 : (∑ j : Fin (k a), r j * OkaRing.restrict (hWV W) (g a j (e i))) = bc i := by
      simpa only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul, Equiv.symm_apply_apply]
        using congrFun hr (e i)
    exact h1.trans (hsum.trans (h2.trans (hbc i)))

/-- The structure sheaf of `ℂ^n` is a coherent sheaf of modules over itself. -/
theorem isCoherent_unit_okaSheaf_fin (n : ℕ) : (unit (okaSheaf (Fin n))).IsCoherent :=
  isCoherent_unit_okaSheaf _
