/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka.OkaRing
import Oka.LocalOkaRing

/-!
# Oka's coherence lemma

We state Oka's coherence lemma: the relations between finitely many holomorphic functions on an
open subset of `ℂ^ι` are, near every point, generated by finitely many of them.

This is the analytic input to the whole development. Everything else is deduced from it: see
`Oka.AnalyticSpace.Relations` for the structure sheaf of `ℂ^ι` and `Oka.AnalyticSpace.Coherent`
for arbitrary complex analytic spaces.
-/

open TopologicalSpace

variable {ι : Type*} [Fintype ι]
variable (U : Opens (ι → ℂ))

theorem oka {m : ℕ} (f : Fin m → OkaRing U) (x : ι → ℂ) (hx : x ∈ U) :
    ∃ (V : Opens (ι → ℂ)) (hV : V ≤ U) (k : ℕ) (g : Fin k → (Fin m → OkaRing V)),
      x ∈ V ∧ (∀ l, ∑ i, g l i * OkaRing.restrict hV (f i) = 0) ∧
      ∀ (W : Opens (ι → ℂ)) (hWV : W ≤ V) (a : Fin m → OkaRing W),
        (∑ i, a i * OkaRing.restrict (hWV.trans hV) (f i) = 0) → ∀ y ∈ W,
          ∃ (W' : Opens (ι → ℂ)) (hW' : W' ≤ W), y ∈ W' ∧
            ∃ c : Fin k → OkaRing W', ∀ i,
              OkaRing.restrict hW' (a i) =
                ∑ l, c l * OkaRing.restrict (hW'.trans hWV) (g l i) :=
  sorry
