/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.OkaRing

/-!
# Oka's coherence lemma

We state Oka's coherence lemma: the relations between finitely many holomorphic functions on an
open subset of `ℂ^ι` are, near every point, generated by finitely many of them.

This is the analytic input to the whole development. Everything else is deduced from it: see
`Oka.Coherent` for the structure sheaf of `ℂ^ι` and `Oka.AnalyticSpace.Coherent` for arbitrary
complex analytic spaces.
-/

open TopologicalSpace

variable {n : ℕ} {ι : Type*} [Fintype ι] [DecidableEq ι]
variable (U : Opens (ι → ℂ))

-- `U ⊆ ℂⁿ`
omit [DecidableEq ι] in
theorem oka {m : ℕ}
    -- (L : (Fin m → OkaRing U) →ₗ[OkaRing U] OkaRing U)
    (f : Fin m → OkaRing U) (x : ι → ℂ) (hx : x ∈ U) :
    ∃ (V : Opens (ι → ℂ)) (hV : V ≤ U) (k : ℕ)
      (g : Fin k → (Fin m → OkaRing V)), x ∈ V ∧
      ∀ (W : Opens (ι → ℂ)) (hWV : W ≤ V), W ≤ V →
        LinearMap.ker (linOfFun <| fun i : Fin m ↦
          OkaRing.restrict (le_trans hWV hV) (f i)) =
        Submodule.span (OkaRing W)
          (Set.range fun j : Fin k ↦
            (fun a : Fin m ↦ OkaRing.restrict hWV (g j a))) :=
  sorry
