/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka.OkaRing
import Oka.LocalOkaRing

/-!
# Oka's coherence lemma

We state Oka's coherence lemma: the relations between finitely many holomorphic functions on an
open subset of `ℂ^ι` are, near every point, generated by finitely many of them. The statement is
made for vectors of holomorphic functions in `oka'`, and only assumed for the index type `Fin n`
in `oka_fin`; the general index type is reduced to this case by a linear change of coordinates.

This is the analytic input to the whole development. Everything else is deduced from it: see
`Oka.AnalyticSpace.Relations` for the structure sheaf of `ℂ^ι` and `Oka.AnalyticSpace.Coherent`
for arbitrary complex analytic spaces.
-/

open TopologicalSpace

variable {ι : Type*} [Fintype ι]
variable (U : Opens (ι → ℂ))

/-- Oka's coherence lemma on `ℂ^n`, for a family `f` of `m` vectors of holomorphic functions on
`U`, each of length `q`: the relations `a` between the `f i`, i.e. the tuples `a` with
`∑ i, a i • f i = 0` in `(OkaRing W)^q`, are, near every point, generated by finitely many
relations `g l` defined on a fixed neighbourhood `V` of `x`.

This is the analytic input; the case of an arbitrary finite index type is deduced from it in
`oka'` by a linear change of coordinates. -/
theorem oka_fin {n m q : ℕ} (U : Opens (Fin n → ℂ)) (f : Fin m → (Fin q → OkaRing U))
    (x : Fin n → ℂ) (hx : x ∈ U) :
    ∃ (V : Opens (Fin n → ℂ)) (hV : V ≤ U) (k : ℕ) (g : Fin k → (Fin m → OkaRing V)),
      x ∈ V ∧ (∀ l, ∀ j, ∑ i, g l i * OkaRing.restrict hV (f i j) = 0) ∧
      ∀ (W : Opens (Fin n → ℂ)) (hWV : W ≤ V) (a : Fin m → OkaRing W),
        (∀ j, ∑ i, a i * OkaRing.restrict (hWV.trans hV) (f i j) = 0) → ∀ y ∈ W,
          ∃ (W' : Opens (Fin n → ℂ)) (hW' : W' ≤ W), y ∈ W' ∧
            ∃ c : Fin k → OkaRing W', ∀ i,
              OkaRing.restrict hW' (a i) =
                ∑ l, c l * OkaRing.restrict (hW'.trans hWV) (g l i) := by
  induction n
  · -- `ℂ^0` is a point, so evaluation identifies each `OkaRing V` with `ℂ`, and the relations
    -- between the `f i` are the kernel of a `ℂ`-linear map between finite dimensional spaces
    have hinj : ∀ {V : Opens (Fin 0 → ℂ)} {y : Fin 0 → ℂ} (hy : y ∈ V),
        Function.Injective (OkaRing.evalHom hy) := by
      intro V y hy u v huv
      refine OkaRing.ext (funext fun z ↦ ?_)
      rw [Subsingleton.elim z ⟨y, hy⟩]
      exact huv
    set T : (Fin m → ℂ) →ₗ[ℂ] (Fin q → ℂ) :=
      ∑ i, (LinearMap.proj i).smulRight (fun j ↦ OkaRing.evalHom hx (f i j)) with hT
    have hTapply : ∀ (a : Fin m → ℂ) (j : Fin q),
        T a j = ∑ i, a i * OkaRing.evalHom hx (f i j) := by
      intro a j
      simp [hT]
    obtain ⟨k, s, hs⟩ := Module.Finite.exists_fin (R := ℂ) (M := LinearMap.ker T)
    refine ⟨U, le_rfl, k, fun l i ↦ algebraMap ℂ (OkaRing U) ((s l : Fin m → ℂ) i), hx,
      fun l j ↦ ?_, fun W hWV a ha y hy ↦ ?_⟩
    · refine hinj hx ?_
      have h0 : ∑ i, (s l : Fin m → ℂ) i * OkaRing.evalHom hx (f i j) = 0 := by
        rw [← hTapply]
        exact congrFun (LinearMap.mem_ker.mp (s l).2) j
      simpa only [map_sum, map_mul, map_zero, OkaRing.restrict_self,
        OkaRing.evalHom_algebraMap] using h0
    · have hxW : x ∈ W := by rwa [Subsingleton.elim x y]
      have hker : (fun i ↦ OkaRing.evalHom hxW (a i)) ∈ LinearMap.ker T := by
        rw [LinearMap.mem_ker]
        funext j
        rw [hTapply]
        simpa only [map_sum, map_mul, map_zero, Pi.zero_apply, OkaRing.evalHom_restrict] using
          congrArg (OkaRing.evalHom hxW) (ha j)
      obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun ℂ).mp
        (hs ▸ Submodule.mem_top : (⟨_, hker⟩ : LinearMap.ker T) ∈ Submodule.span ℂ (Set.range s))
      refine ⟨W, le_rfl, hy, fun l ↦ algebraMap ℂ (OkaRing W) (c l), fun i ↦ ?_⟩
      refine hinj hxW ?_
      have hci : ∑ l, c l * (s l : Fin m → ℂ) i = OkaRing.evalHom hxW (a i) := by
        simpa using congrFun (congrArg Subtype.val hc) i
      simpa only [map_sum, map_mul, OkaRing.restrict_self, AlgHom.commutes,
        OkaRing.evalHom_algebraMap] using hci.symm
  · sorry

/-- Oka's coherence lemma for a family `f` of `m` vectors of holomorphic functions on `U`, each
of length `q`: the relations `a` between the `f i`, i.e. the tuples `a` with
`∑ i, a i • f i = 0` in `(OkaRing W)^q`, are, near every point, generated by finitely many
relations `g l` defined on a fixed neighbourhood `V` of `x`.

This is deduced from `oka_fin` via the linear change of coordinates `ℂ^ι ≃ ℂ^{card ι}`. -/
theorem oka' {m q : ℕ} (f : Fin m → (Fin q → OkaRing U)) (x : ι → ℂ) (hx : x ∈ U) :
    ∃ (V : Opens (ι → ℂ)) (hV : V ≤ U) (k : ℕ) (g : Fin k → (Fin m → OkaRing V)),
      x ∈ V ∧ (∀ l, ∀ j, ∑ i, g l i * OkaRing.restrict hV (f i j) = 0) ∧
      ∀ (W : Opens (ι → ℂ)) (hWV : W ≤ V) (a : Fin m → OkaRing W),
        (∀ j, ∑ i, a i * OkaRing.restrict (hWV.trans hV) (f i j) = 0) → ∀ y ∈ W,
          ∃ (W' : Opens (ι → ℂ)) (hW' : W' ≤ W), y ∈ W' ∧
            ∃ c : Fin k → OkaRing W', ∀ i,
              OkaRing.restrict hW' (a i) =
                ∑ l, c l * OkaRing.restrict (hW'.trans hWV) (g l i) := by
  set φ := ContinuousLinearEquiv.piCongrLeft ℂ (fun _ : Fin (Fintype.card ι) ↦ ℂ)
    (Fintype.equivFin ι)
  obtain ⟨V', hV', k, g', hxV', hrel', hgen'⟩ :=
    oka_fin (φ.opensCongr U) (fun i j ↦ OkaRing.congr φ U (f i j)) (φ x) (by simp [hx])
  obtain ⟨V, rfl⟩ : ∃ V, φ.opensCongr V = V' :=
    ⟨φ.opensCongr.symm V', φ.opensCongr.apply_symm_apply V'⟩
  have hVU : V ≤ U := φ.opensCongr.le_iff_le.mp hV'
  refine ⟨V, hVU, k, fun l i ↦ (OkaRing.congr φ V).symm (g' l i), by simpa using hxV',
    fun l j ↦ ?_, fun W hWV a ha y hy ↦ ?_⟩
  · have h := congrArg (OkaRing.congr φ V).symm (hrel' l j)
    simpa [map_sum, OkaRing.congr_symm_restrict] using h
  · have ha' : ∀ j, ∑ i, OkaRing.congr φ W (a i) *
        OkaRing.restrict ((φ.opensCongr.monotone hWV).trans hV')
          (OkaRing.congr φ U (f i j)) = 0 := by
      intro j
      have h := congrArg (OkaRing.congr φ W) (ha j)
      simpa [map_sum, OkaRing.congr_restrict] using h
    obtain ⟨W', hW', hyW', c, hc⟩ :=
      hgen' (φ.opensCongr W) (φ.opensCongr.monotone hWV) (fun i ↦ OkaRing.congr φ W (a i)) ha'
        (φ y) (by simp [hy])
    obtain ⟨W₀, rfl⟩ : ∃ W₀, φ.opensCongr W₀ = W' :=
      ⟨φ.opensCongr.symm W', φ.opensCongr.apply_symm_apply W'⟩
    refine ⟨W₀, φ.opensCongr.le_iff_le.mp hW', by simpa using hyW',
      fun l ↦ (OkaRing.congr φ W₀).symm (c l), fun i ↦ ?_⟩
    have h := congrArg (OkaRing.congr φ W₀).symm (hc i)
    simpa [map_sum, OkaRing.congr_symm_restrict] using h

/-- Oka's coherence lemma: the relations between finitely many holomorphic functions on `U` are,
near every point, generated by finitely many of them. This is the case `q = 1` of `oka'`. -/
theorem oka {m : ℕ} (f : Fin m → OkaRing U) (x : ι → ℂ) (hx : x ∈ U) :
    ∃ (V : Opens (ι → ℂ)) (hV : V ≤ U) (k : ℕ) (g : Fin k → (Fin m → OkaRing V)),
      x ∈ V ∧ (∀ l, ∑ i, g l i * OkaRing.restrict hV (f i) = 0) ∧
      ∀ (W : Opens (ι → ℂ)) (hWV : W ≤ V) (a : Fin m → OkaRing W),
        (∑ i, a i * OkaRing.restrict (hWV.trans hV) (f i) = 0) → ∀ y ∈ W,
          ∃ (W' : Opens (ι → ℂ)) (hW' : W' ≤ W), y ∈ W' ∧
            ∃ c : Fin k → OkaRing W', ∀ i,
              OkaRing.restrict hW' (a i) =
                ∑ l, c l * OkaRing.restrict (hW'.trans hWV) (g l i) := by
  obtain ⟨V, hV, k, g, hxV, hrel, hgen⟩ := oka' U (q := 1) (fun i _ ↦ f i) x hx
  exact ⟨V, hV, k, g, hxV, fun l ↦ hrel l 0,
    fun W hWV a ha ↦ hgen W hWV a fun _ ↦ ha⟩
