/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.ComplexSpace

/-!
# Complex analytic spaces

We define complex analytic spaces following the definition of `AlgebraicGeometry.Scheme` in
mathlib: an analytic space is a locally ringed space every point of which has an open
neighbourhood isomorphic, as a locally ringed space, to a *local model*.

A local model is the common zero locus `A` of finitely many holomorphic functions
`f₁, …, f_k` on an open subset `U ⊆ ℂ^n`, equipped with the structure sheaf
`(𝒪_U / (f₁, …, f_k))|_A`. Rather than constructing this quotient sheaf, we characterise the
result by the closed immersion `i : A ⟶ U` it comes with, in the style of
`AlgebraicGeometry.IsClosedImmersion`: the underlying map of `i` is a closed embedding onto
the zero locus of the `fⱼ`, the maps on stalks are surjective, and their kernels are the
ideals generated by the germs of the `fⱼ`. This determines `(A, 𝒪_A)` up to isomorphism and
is what the classical definition amounts to.

## Main definitions

- `ComplexAnalytic.IsCutOutBy i f`: the closed immersion `i : X ⟶ Y` exhibits `X` as the
  analytic subspace of `Y` cut out by the global sections `f`.
- `ComplexAnalytic.IsLocalModel X`: `X` is a local model, i.e. an analytic subspace of an open
  subset of some `ℂ^n`.
- `ComplexAnalytic.AnalyticSpace`: a complex analytic space.
- `ComplexAnalytic.AnalyticSpace.complexAffineSpace`: `ℂ^n` as a complex analytic space.

## References

- [Hans Grauert and Reinhold Remmert, *Coherent analytic sheaves*][grauert-remmert1984]
- [Hans Grauert and Reinhold Remmert, *Theory of Stein spaces*][grauert-remmert1979]
-/

open CategoryTheory TopologicalSpace Opposite AlgebraicGeometry Topology

universe u

namespace ComplexAnalytic

variable {X Y : LocallyRingedSpace.{u}}

/-- A closed immersion `i : X ⟶ Y` of locally ringed spaces *cuts out* `X` by the global
sections `f₁, …, f_k` of `𝒪_Y` if `X` is the common zero locus of the `fⱼ` and `𝒪_X` is the
quotient of `𝒪_Y` by the ideal they generate.

This is the intrinsic characterisation of the locally ringed space `(V(f), (𝒪_Y/(f))|_{V(f)})`:
any two closed immersions cutting out the same sections are canonically isomorphic. -/
structure IsCutOutBy (i : X ⟶ Y) {k : ℕ} (f : Fin k → Y.presheaf.obj (op ⊤)) : Prop where
  /-- `i` is a closed embedding of topological spaces. -/
  isClosedEmbedding : IsClosedEmbedding i.base
  /-- The image of `i` is the common zero locus of the `fⱼ`, i.e. the set of points at which
  every germ of every `fⱼ` is not a unit. -/
  range_base : Set.range i.base =
    {y | ∀ j, Y.presheaf.Γgerm y (f j) ∈ IsLocalRing.maximalIdeal (Y.presheaf.stalk y)}
  /-- The structure sheaf of `X` is a quotient of the structure sheaf of `Y`. -/
  surjective_stalkMap : ∀ x, Function.Surjective (i.stalkMap x).hom
  /-- The kernel of `𝒪_Y → 𝒪_X` is the ideal generated by the germs of the `fⱼ`. -/
  ker_stalkMap : ∀ x, RingHom.ker (i.stalkMap x).hom =
    Ideal.span (Set.range fun j ↦ Y.presheaf.Γgerm (i.base x) (f j))

/-- A locally ringed space is a **local model** for complex analytic geometry if it is the
common zero locus of finitely many holomorphic functions on an open subset of some `ℂ^n`,
equipped with the corresponding quotient of the structure sheaf.

This is the analytic analogue of an affine scheme. -/
def IsLocalModel (X : LocallyRingedSpace.{u}) : Prop :=
  ∃ (n k : ℕ) (U : Opens (complexAffineSpace.{u} n))
    (i : X ⟶ (complexAffineSpace.{u} n).restrict U.isOpenEmbedding)
    (f : Fin k → ((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).presheaf.obj (op ⊤)),
    IsCutOutBy i f

/-- A **complex analytic space** is a locally ringed space `X` such that every point of `X` has
an open neighbourhood `U` for which the restriction of `X` to `U` is isomorphic, as a locally
ringed space, to a local model.

Compare `AlgebraicGeometry.Scheme`, where the local models are the spectra of commutative
rings. -/
structure AnalyticSpace extends LocallyRingedSpace.{u} where
  /-- Every point has a neighbourhood isomorphic to a local model. -/
  local_model : ∀ x : toLocallyRingedSpace,
    ∃ (U : OpenNhds x) (M : LocallyRingedSpace.{u}), IsLocalModel M ∧
      Nonempty (toLocallyRingedSpace.restrict U.isOpenEmbedding ≅ M)

namespace AnalyticSpace

instance : CoeSort AnalyticSpace (Type u) where
  coe X := X.carrier

/-- The type of open sets of a complex analytic space. -/
abbrev Opens (X : AnalyticSpace.{u}) : Type u := TopologicalSpace.Opens X

/-- A morphism of complex analytic spaces is a morphism of the underlying locally ringed
spaces. -/
@[ext]
structure Hom (X Y : AnalyticSpace.{u}) extends
  toLRSHom' : X.toLocallyRingedSpace.Hom Y.toLocallyRingedSpace where

/-- Cast a morphism of analytic spaces to a morphism of locally ringed spaces. -/
abbrev Hom.toLRSHom {X Y : AnalyticSpace.{u}} (f : X.Hom Y) :
    X.toLocallyRingedSpace ⟶ Y.toLocallyRingedSpace :=
  f.toLRSHom'

/-- Complex analytic spaces form a full subcategory of locally ringed spaces. -/
instance : Category AnalyticSpace.{u} where
  Hom := Hom
  id X := ⟨𝟙 X.toLocallyRingedSpace⟩
  comp f g := ⟨f.toLRSHom ≫ g.toLRSHom⟩

/-- The forgetful functor from complex analytic spaces to locally ringed spaces. -/
def forgetToLocallyRingedSpace : AnalyticSpace.{u} ⥤ LocallyRingedSpace.{u} where
  obj X := X.toLocallyRingedSpace
  map f := f.toLRSHom

instance : forgetToLocallyRingedSpace.Faithful where
  map_injective {_ _ f g} h := by
    obtain ⟨f⟩ := f
    obtain ⟨g⟩ := g
    exact congrArg Hom.mk h

end AnalyticSpace

section ComplexAffineSpace

variable (n : ℕ)

/-- Complex affine `n`-space, restricted to its top open subset, is a local model: it is cut
out inside itself by the empty family of holomorphic functions. -/
theorem isLocalModel_complexAffineSpace_restrict_top :
    IsLocalModel ((complexAffineSpace.{u} n).restrict
      (⊤ : Opens (complexAffineSpace.{u} n)).isOpenEmbedding) := by
  refine ⟨n, 0, ⊤, 𝟙 _, Fin.elim0, ?_, ?_, ?_, ?_⟩
  · simpa using IsClosedEmbedding.id
  · simp
  · intro x
    simp only [LocallyRingedSpace.stalkMap_id]
    exact fun y ↦ ⟨y, rfl⟩
  · intro x
    simp only [LocallyRingedSpace.stalkMap_id, Set.range_eq_empty, Ideal.span_empty]
    ext a
    exact Iff.rfl

/-- Complex affine `n`-space `ℂ^n` as a complex analytic space. -/
noncomputable def AnalyticSpace.complexAffineSpace (n : ℕ) : AnalyticSpace.{u} where
  toLocallyRingedSpace := _root_.complexAffineSpace.{u} n
  local_model _ :=
    ⟨⟨⊤, trivial⟩, _, isLocalModel_complexAffineSpace_restrict_top n, ⟨Iso.refl _⟩⟩

end ComplexAffineSpace

end ComplexAnalytic
