/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.ComplexSpace

/-!
# Complex analytic spaces

We define complex analytic spaces following the definition of `AlgebraicGeometry.Scheme` in
mathlib: an analytic space is a locally ringed space every point of which has an open
neighbourhood isomorphic, as a locally ringed space, to a *local model*.

A local model is the common zero locus `A` of finitely many holomorphic functions
`f₁, …, f_k` on an open subset `U ⊆ ℂ^n`, equipped with the structure sheaf
`(𝒪_U / (f₁, …, f_k))|_A`. Rather than constructing this quotient sheaf, we characterise the
result by the closed immersion `i : A ⟶ U` it comes with, in the style of
`AlgebraicGeometry.IsClosedImmersion`: the underlying map of `i` is a closed embedding onto
the zero locus of the `fⱼ`, the maps on stalks are surjective, and their kernels are the
ideals generated by the germs of the `fⱼ`. This determines `(A, 𝒪_A)` up to isomorphism and
is what the classical definition amounts to.

## Main definitions

- `ComplexAnalytic.IsCutOutBy i f`: the closed immersion `i : X ⟶ Y` exhibits `X` as the
  analytic subspace of `Y` cut out by the global sections `f`.
- `ComplexAnalytic.IsLocalModel X`: `X` is a local model, i.e. an analytic subspace of an open
  subset of some `ℂ^n`.
- `ComplexAnalytic.AnalyticSpace`: a complex analytic space.
- `ComplexAnalytic.AnalyticSpace.complexAffineSpace`: `ℂ^n` as a complex analytic space.

## References

- [Hans Grauert and Reinhold Remmert, *Coherent analytic sheaves*][grauert-remmert1984]
- [Hans Grauert and Reinhold Remmert, *Theory of Stein spaces*][grauert-remmert1979]
-/

open CategoryTheory TopologicalSpace Opposite AlgebraicGeometry Topology

universe u

namespace ComplexAnalytic

variable {X Y : LocallyRingedSpace.{u}}

/-- A closed immersion `i : X ⟶ Y` of locally ringed spaces *cuts out* `X` by the global
sections `f₁, …, f_k` of `𝒪_Y` if `X` is the common zero locus of the `fⱼ` and `𝒪_X` is the
quotient of `𝒪_Y` by the ideal they generate.

This is the intrinsic characterisation of the locally ringed space `(V(f), (𝒪_Y/(f))|_{V(f)})`:
any two closed immersions cutting out the same sections are canonically isomorphic. -/
structure IsCutOutBy (i : X ⟶ Y) {k : ℕ} (f : Fin k → Y.presheaf.obj (op ⊤)) : Prop where
  /-- `i` is a closed embedding of topological spaces. -/
  isClosedEmbedding : IsClosedEmbedding i.base
  /-- The image of `i` is the common zero locus of the `fⱼ`, i.e. the set of points at which
  every germ of every `fⱼ` is not a unit. -/
  range_base : Set.range i.base =
    {y | ∀ j, Y.presheaf.Γgerm y (f j) ∈ IsLocalRing.maximalIdeal (Y.presheaf.stalk y)}
  /-- The structure sheaf of `X` is a quotient of the structure sheaf of `Y`. -/
  surjective_stalkMap : ∀ x, Function.Surjective (i.stalkMap x).hom
  /-- The kernel of `𝒪_Y → 𝒪_X` is the ideal generated by the germs of the `fⱼ`. -/
  ker_stalkMap : ∀ x, RingHom.ker (i.stalkMap x).hom =
    Ideal.span (Set.range fun j ↦ Y.presheaf.Γgerm (i.base x) (f j))

/-- A locally ringed space is a **local model** for complex analytic geometry if it is the
common zero locus of finitely many holomorphic functions on an open subset of some `ℂ^n`,
equipped with the corresponding quotient of the structure sheaf.

This is the analytic analogue of an affine scheme. -/
def IsLocalModel (X : LocallyRingedSpace.{u}) : Prop :=
  ∃ (n k : ℕ) (U : Opens (complexAffineSpace.{u} n))
    (i : X ⟶ (complexAffineSpace.{u} n).restrict U.isOpenEmbedding)
    (f : Fin k → ((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).presheaf.obj (op ⊤)),
    IsCutOutBy i f

/-- The underlying homeomorphism of an isomorphism of locally ringed spaces. -/
noncomputable def _root_.AlgebraicGeometry.LocallyRingedSpace.homeoOfIso (e : X ≅ Y) : X ≃ₜ Y :=
  TopCat.homeoOfIso (LocallyRingedSpace.forgetToTop.mapIso e)

@[simp]
lemma _root_.AlgebraicGeometry.LocallyRingedSpace.homeoOfIso_apply (e : X ≅ Y) (x : X) :
    LocallyRingedSpace.homeoOfIso e x = e.hom.base x :=
  rfl

/-- Cutting out by a family of sections is invariant under precomposition with an isomorphism:
if `i : X ⟶ Y` cuts out `X` by `f` and `e : X' ≅ X`, then `e.hom ≫ i` cuts out `X'` by `f`. -/
theorem IsCutOutBy.comp_iso {X' : LocallyRingedSpace.{u}} {i : X ⟶ Y} {k : ℕ}
    {f : Fin k → Y.presheaf.obj (op ⊤)} (hf : IsCutOutBy i f) (e : X' ≅ X) :
    IsCutOutBy (e.hom ≫ i) f := by
  have hstalk (x : X') : Function.Bijective (e.hom.stalkMap x).hom :=
    ConcreteCategory.bijective_of_isIso _
  have hcomp (x : X') (a : Y.presheaf.stalk ((e.hom ≫ i).base x)) :
      ((e.hom ≫ i).stalkMap x).hom a =
        (e.hom.stalkMap x).hom ((i.stalkMap (e.hom.base x)).hom a) := by
    rw [LocallyRingedSpace.stalkMap_comp]
    rfl
  have hsurj : Function.Surjective ⇑e.hom.base :=
    (LocallyRingedSpace.homeoOfIso e).surjective
  refine ⟨hf.isClosedEmbedding.comp (LocallyRingedSpace.homeoOfIso e).isClosedEmbedding, ?_,
    fun x ↦ ?_, fun x ↦ ?_⟩
  · rw [show ⇑(e.hom ≫ i).base = ⇑i.base ∘ ⇑e.hom.base from rfl, Set.range_comp,
      hsurj.range_eq, Set.image_univ]
    exact hf.range_base
  · rw [show ⇑((e.hom ≫ i).stalkMap x).hom =
      ⇑(e.hom.stalkMap x).hom ∘ ⇑(i.stalkMap (e.hom.base x)).hom from funext (hcomp x)]
    exact (hstalk x).surjective.comp (hf.surjective_stalkMap _)
  · have hker : RingHom.ker ((e.hom ≫ i).stalkMap x).hom =
        RingHom.ker (i.stalkMap (e.hom.base x)).hom := by
      ext a
      simp only [RingHom.mem_ker, hcomp x a]
      exact ⟨fun h ↦ (hstalk x).injective (h.trans (map_zero _).symm),
        fun h ↦ by rw [h, map_zero]⟩
    rw [hker]
    exact hf.ker_stalkMap _

/-- The sections cutting out `X` inside `Y` pull back to zero on `X`. -/
lemma IsCutOutBy.c_app_eq_zero {i : X ⟶ Y} {k : ℕ} {f : Fin k → Y.presheaf.obj (op ⊤)}
    (hcut : IsCutOutBy i f) (j : Fin k) :
    i.c.app (op ⊤) (f j) = 0 := by
  refine TopCat.Presheaf.section_ext X.sheaf _ _ _ fun x _ ↦ ?_
  have hker : Y.presheaf.Γgerm (i.base x) (f j) ∈ RingHom.ker (i.stalkMap x).hom := by
    rw [hcut.ker_stalkMap x]
    exact Submodule.subset_span ⟨j, rfl⟩
  have h0 : (i.stalkMap x) (Y.presheaf.Γgerm (i.base x) (f j)) = 0 := hker
  exact ((LocallyRingedSpace.stalkMap_germ_apply i ⊤ x trivial (f j)).symm.trans h0).trans
    (map_zero _).symm


/-- Being a local model is invariant under isomorphism of locally ringed spaces. -/
theorem IsLocalModel.of_iso {M N : LocallyRingedSpace.{u}} (e : N ≅ M) (hM : IsLocalModel M) :
    IsLocalModel N := by
  obtain ⟨n, k, U, i, f, hcut⟩ := hM
  exact ⟨n, k, U, e.hom ≫ i, f, hcut.comp_iso e⟩

/-- A **complex analytic space** is a locally ringed space `X` such that every point of `X` has
an open neighbourhood `U` for which the restriction of `X` to `U` is isomorphic, as a locally
ringed space, to a local model.

Compare `AlgebraicGeometry.Scheme`, where the local models are the spectra of commutative
rings. -/
structure AnalyticSpace extends LocallyRingedSpace.{u} where
  /-- Every point has a neighbourhood isomorphic to a local model. -/
  local_model : ∀ x : toLocallyRingedSpace,
    ∃ (U : OpenNhds x) (M : LocallyRingedSpace.{u}), IsLocalModel M ∧
      Nonempty (toLocallyRingedSpace.restrict U.isOpenEmbedding ≅ M)

namespace AnalyticSpace

instance : CoeSort AnalyticSpace (Type u) where
  coe X := X.carrier

/-- The type of open sets of a complex analytic space. -/
abbrev Opens (X : AnalyticSpace.{u}) : Type u := TopologicalSpace.Opens X

/-- A morphism of complex analytic spaces is a morphism of the underlying locally ringed
spaces. -/
@[ext]
structure Hom (X Y : AnalyticSpace.{u}) extends
  toLRSHom' : X.toLocallyRingedSpace.Hom Y.toLocallyRingedSpace where

/-- Cast a morphism of analytic spaces to a morphism of locally ringed spaces. -/
abbrev Hom.toLRSHom {X Y : AnalyticSpace.{u}} (f : X.Hom Y) :
    X.toLocallyRingedSpace ⟶ Y.toLocallyRingedSpace :=
  f.toLRSHom'

/-- Complex analytic spaces form a full subcategory of locally ringed spaces. -/
instance : Category AnalyticSpace.{u} where
  Hom := Hom
  id X := ⟨𝟙 X.toLocallyRingedSpace⟩
  comp f g := ⟨f.toLRSHom ≫ g.toLRSHom⟩

/-- The forgetful functor from complex analytic spaces to locally ringed spaces. -/
def forgetToLocallyRingedSpace : AnalyticSpace.{u} ⥤ LocallyRingedSpace.{u} where
  obj X := X.toLocallyRingedSpace
  map f := f.toLRSHom

instance : forgetToLocallyRingedSpace.Faithful where
  map_injective {_ _ f g} h := by
    obtain ⟨f⟩ := f
    obtain ⟨g⟩ := g
    exact congrArg Hom.mk h

end AnalyticSpace

section ComplexAffineSpace

variable (n : ℕ)

/-- Complex affine `n`-space, restricted to its top open subset, is a local model: it is cut
out inside itself by the empty family of holomorphic functions. -/
theorem isLocalModel_complexAffineSpace_restrict_top :
    IsLocalModel ((complexAffineSpace.{u} n).restrict
      (⊤ : Opens (complexAffineSpace.{u} n)).isOpenEmbedding) := by
  refine ⟨n, 0, ⊤, 𝟙 _, Fin.elim0, ?_, ?_, ?_, ?_⟩
  · simpa using IsClosedEmbedding.id
  · simp
  · intro x
    simp only [LocallyRingedSpace.stalkMap_id]
    exact fun y ↦ ⟨y, rfl⟩
  · intro x
    simp only [LocallyRingedSpace.stalkMap_id, Set.range_eq_empty, Ideal.span_empty]
    ext a
    exact Iff.rfl

/-- Complex affine `n`-space `ℂ^n` as a complex analytic space. -/
noncomputable def AnalyticSpace.complexAffineSpace (n : ℕ) : AnalyticSpace.{u} where
  toLocallyRingedSpace := _root_.complexAffineSpace.{u} n
  local_model _ :=
    ⟨⟨⊤, trivial⟩, _, isLocalModel_complexAffineSpace_restrict_top n, ⟨Iso.refl _⟩⟩

end ComplexAffineSpace

end ComplexAnalytic
