/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.AnalyticSpace.Basic
import Oka.AnalyticSpace.Relations

/-!
# Coherence of the structure sheaf of a complex analytic space

We deduce from Oka's coherence theorem for `ℂ^n` that the structure sheaf of an arbitrary
complex analytic space is coherent.

## Strategy

Coherence is reached through the concrete condition
`AlgebraicGeometry.LocallyRingedSpace.HasLocalRelations` of `Oka.AnalyticSpace.Relations`,
which implies coherence and, unlike `SheafOfModules.IsCoherent`, mentions only open subsets,
sections and restriction maps. It is therefore a local condition
(`hasLocalRelations_of_openCover`), and no transport of sites is needed anywhere.

Since an analytic space is locally isomorphic to a local model, and being a local model is
invariant under isomorphism (`ComplexAnalytic.IsLocalModel.of_iso`), it remains to see that
the structure sheaf of a local model has locally finitely generated relations. This is
`ComplexAnalytic.IsLocalModel.hasLocalRelationsOn`, the one ingredient still open, and it is
where Oka's theorem for `ℂ^n` enters: a local model is cut out by finitely many holomorphic
functions `f₁, …, f_k` inside an open subset `Y` of some `ℂ^n`, and near a point of it a
relation between sections `s₁, …, s_m` of `𝒪_M` is obtained by lifting the `sᵢ` to sections
`t₁, …, t_m` of `𝒪_Y` and applying Oka's theorem to the family `t₁, …, t_m, f₁, …, f_k`: the
relations of that family generate, and projecting away the last `k` coordinates gives the
relations between the `sᵢ`.

## Main results

- `ComplexAnalytic.AnalyticSpace.isCoherentStructureSheaf`: the structure sheaf of any complex
  analytic space is coherent.

## References

- [Hans Grauert and Reinhold Remmert, *Coherent analytic sheaves*][grauert-remmert1984], §A
- [Jean-Pierre Serre, *Faisceaux algébriques cohérents*][serre1955], §2
-/

open CategoryTheory TopologicalSpace Opposite Limits SheafOfModules AlgebraicGeometry

universe u

namespace ComplexAnalytic

/-- If the restriction of `X` to an open set `U` is a local model, then `𝒪_X` has locally
finitely generated relations over `U`.

This is the geometric heart of the deduction, and the point at which Oka's coherence theorem
for `ℂ^n` is used. Writing the local model as a closed immersion `i : X|_U ⟶ Y` into an open
subset `Y` of `ℂ^n` cutting out `X|_U` by `f₁, …, f_k`:

1. near a point, finitely many sections `s₁, …, s_m` of `𝒪_X` lift along the surjection
   `𝒪_Y ↠ i_*𝒪_{X|_U}` to sections `t₁, …, t_m` of `𝒪_Y`;
2. `𝒪_Y` has locally finitely generated relations, by `hasLocalRelations_complexSpace`
   restricted to `Y`, so the relations between `t₁, …, t_m, f₁, …, f_k` are generated by
   finitely many of them;
3. discarding the last `k` coordinates of those generators gives generators for the relations
   between the `sᵢ`, since a relation `∑ aᵢ sᵢ = 0` lifts to `∑ aᵢ tᵢ ∈ (f₁, …, f_k)`.

Note on the strength of the statement. `HasLocalRelationsOn` asks, following `oka`, that the
generators generate *sectionwise* over every smaller open set. Step 1 above only lifts sections
locally, because `𝒪_Y ↠ i_*𝒪_M` is surjective on stalks and not on sections, so the argument
delivers generation only locally and this statement is probably too strong to be provable as
it stands — as is `oka` itself, for the same kind of reason. The fix is to weaken
`HasLocalRelations` to local generation and reprove
`isCoherentStructureSheaf_of_hasLocalRelations` using
`SheafOfModules.isCoherent_of_forall_kernel_of_locally` in place of
`SheafOfModules.isCoherent_of_forall_kernel`; the former was added for exactly this purpose. -/
theorem IsLocalModel.hasLocalRelationsOn {X : LocallyRingedSpace.{u}} (U : Opens X)
    (h : IsLocalModel (X.restrict U.isOpenEmbedding)) :
    X.HasLocalRelationsOn U :=
  sorry

/-- **Coherence of the structure sheaf of a complex analytic space.**

Every point of an analytic space has a neighbourhood isomorphic to a local model, whose
structure sheaf has locally finitely generated relations; since that condition is local it
holds on all of `X`, and hence `𝒪_X` is coherent. -/
theorem AnalyticSpace.isCoherentStructureSheaf (X : AnalyticSpace.{u}) :
    X.toLocallyRingedSpace.IsCoherentStructureSheaf := by
  choose U M hM he using X.local_model
  refine LocallyRingedSpace.isCoherentStructureSheaf_of_hasLocalRelations _
    (LocallyRingedSpace.hasLocalRelations_of_openCover
      (fun x : X.toLocallyRingedSpace ↦ (U x).1) (fun x ↦ ⟨x, (U x).2⟩) fun x ↦ ?_)
  exact IsLocalModel.hasLocalRelationsOn _ (IsLocalModel.of_iso (he x).some (hM x))

end ComplexAnalytic
