/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.AnalyticSpace.ChartSections
import Oka.Analysis.Normed.Operator.Compact.Pi
import Oka.Analytification.GAGA.ClosureTheorem
import Oka.Geometry.RingedSpace.LocallyRingedSpace.CohomologyModule
import Oka.Geometry.RingedSpace.LocallyRingedSpace.FreeResolutionAcyclic
import Oka.Topology.Algebra.Module.QuotientLocallyConvex
import Oka.Weierstrass

/-!
# Fréchet models for the sections of a coherent sheaf over chart boxes

Let `M` be a sheaf of modules on a complex analytic space `Z`, with generators `g : I → M(N)` on
an open `N` whose relations are generated by the rows of a matrix `A`, both on every open
`W ≤ N` on which `𝒪_Z` is acyclic (`ComplexAnalytic.GeneratorData`; this is the output of
`AlgebraicGeometry.LocallyRingedSpace.exists_generators_acyclic`). For a chart `φ : ℂⁿ ⟶ Z` and
an open `V ⊆ ℂⁿ` with `φ(V) ≤ N` on which `𝒪_Z` is acyclic, the map
`ψ : 𝒪(V)^I → M(φ(V))`, `f ↦ ∑ᵢ fᵢ • gᵢ` is surjective, and its kernel is **closed**: by Cartan's
closure theorem it is the set of `f` whose germs lie pointwise in the span of the germs of the
columns of `A` (`ComplexAnalytic.GeneratorData.isClosed_kerSub`). Hence `M(φ(V))` is the quotient
of a Fréchet space by a closed subspace (`ComplexAnalytic.GeneratorData.ModelSpace`).

Restrictions between such model spaces are continuous, for arbitrary charts and generator data
(`ComplexAnalytic.GeneratorData.continuous_modelRes`), because restriction of functions between
chart images is continuous (`ComplexAnalytic.chartRestrictCLM`); for the same chart and data and
`V'` of compact closure in `V`, restriction is a compact operator (Montel,
`ComplexAnalytic.GeneratorData.isCompactOperator_modelRes`).
-/

universe u

open CategoryTheory TopologicalSpace Opposite AlgebraicGeometry Topology Filter Set
open scoped Matrix

namespace OkaRing

variable {ι : Type u} [Fintype ι] {V : Opens (ι → ℂ)} {σ τ : Type*} [Finite σ] [Fintype τ]

/-- **Local representation.** If the germ at `y` of `f ∈ 𝒪(V)^σ` lies in the span of the germs of
the columns of a matrix `A`, then near `y` the function `f` is `A *ᵥ c` for some holomorphic
`c`. -/
theorem exists_restrict_eq_mulVec (A : Matrix σ τ (OkaRing V)) (f : σ → OkaRing V)
    {y : ι → ℂ} (hy : y ∈ V)
    (hf : germVec hy f ∈ Submodule.span (LocalOkaRing ι)
      (range fun j ↦ germVec hy fun i ↦ A i j)) :
    ∃ (V₀ : Opens (ι → ℂ)) (h : V₀ ≤ V), y ∈ V₀ ∧ ∃ c : τ → OkaRing V₀,
      ∀ i, restrict h (f i) = ∑ j, c j * restrict h (A i j) := by
  classical
  obtain ⟨a, ha⟩ := (Submodule.mem_span_range_iff_exists_fun _).1 hf
  choose W hyW h hh using fun j ↦ LocalOkaRing.exists_okaRing_germ (a j) y
  let V₁ : Opens (ι → ℂ) := ⟨(V : Set (ι → ℂ)) ∩ ⋂ j, (W j : Set (ι → ℂ)),
    V.isOpen.inter (isOpen_iInter_of_finite fun j ↦ (W j).isOpen)⟩
  have hV₁ : V₁ ≤ V := fun _ hx ↦ hx.1
  have hV₁W : ∀ j, V₁ ≤ W j := fun j _ hx ↦ mem_iInter.1 hx.2 j
  have hyV₁ : y ∈ V₁ := ⟨hy, mem_iInter.2 hyW⟩
  have hgerm : ∀ i, germ hyV₁ (restrict hV₁ (f i) -
      ∑ j, restrict (hV₁W j) (h j) * restrict hV₁ (A i j)) = 0 := fun i ↦ by
    rw [map_sub, map_sum, germ_restrict, sub_eq_zero]
    have := congrFun ha i
    simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul, germVec_apply] at this
    rw [← this]
    refine Finset.sum_congr rfl fun j _ ↦ ?_
    rw [map_mul, germ_restrict, germ_restrict, hh]
  choose V₂ hV₂ hyV₂ hz using fun i ↦ exists_restrict_eq_zero hyV₁ (hgerm i)
  let V₀ : Opens (ι → ℂ) := ⟨(V₁ : Set (ι → ℂ)) ∩ ⋂ i, (V₂ i : Set (ι → ℂ)),
    V₁.isOpen.inter (isOpen_iInter_of_finite fun i ↦ (V₂ i).isOpen)⟩
  have hV₀ : V₀ ≤ V₁ := fun _ hx ↦ hx.1
  have hV₀₂ : ∀ i, V₀ ≤ V₂ i := fun i _ hx ↦ mem_iInter.1 hx.2 i
  refine ⟨V₀, hV₀.trans hV₁, ⟨hyV₁, mem_iInter.2 hyV₂⟩,
    fun j ↦ restrict (hV₀.trans (hV₁W j)) (h j), fun i ↦ ?_⟩
  have := congrArg (restrict (hV₀₂ i)) (hz i)
  rw [restrict_restrict, map_zero, map_sub, sub_eq_zero, map_sum, restrict_restrict] at this
  rw [this]
  refine Finset.sum_congr rfl fun j _ ↦ ?_
  simp only [map_mul, restrict_restrict]

end OkaRing

namespace ComplexAnalytic

noncomputable section

variable {Z : AnalyticSpace.{u}}

/-- The structure sheaf of `Z` is acyclic on the open `W`. -/
def StructureAcyclic (W : Opens Z.toPresheafedSpace) : Prop :=
  ∀ q, 0 < q → Subsingleton (TopCat.Sheaf.H
    ((TopCat.Sheaf.restrictOpen W).obj Z.toLocallyRingedSpace.structureSheafAb) q)

variable (M : SheafOfModules.{u} Z.toLocallyRingedSpace.ringSheaf)

/-- **Generators with generated relations on an open `N`**, valid on every open `W ≤ N` on which
the structure sheaf is acyclic: sections `g : I → M(N)` and a matrix `A` with `∑ᵢ A j i • gᵢ = 0`
such that on such `W`, `M` is acyclic, the `gᵢ|_W` generate `M(W)`, and the relations between
them are generated by the rows of `A`. -/
structure GeneratorData where
  /-- The open on which the generators are defined. -/
  N : Opens Z.toPresheafedSpace
  /-- The index type of the generators. -/
  I : Type u
  /-- The index type of the relations. -/
  I' : Type u
  [fintypeI : Fintype I]
  [fintypeI' : Fintype I']
  /-- The generators. -/
  g : I → M.val.obj (op N)
  /-- The matrix of relations. -/
  A : I' → I → Z.toLocallyRingedSpace.ringSheaf.obj.obj (op N)
  rel : ∀ j, ∑ i, A j i • g i = 0
  acyclic : ∀ (W : Opens Z.toPresheafedSpace), W ≤ N → StructureAcyclic W →
    ∀ q, 0 < q → Subsingleton (TopCat.Sheaf.H ((TopCat.Sheaf.restrictOpen W).obj M.toAb) q)
  surj : ∀ (W : Opens Z.toPresheafedSpace) (hW : W ≤ N), StructureAcyclic W →
    ∀ s : M.val.obj (op W), ∃ f : I → Z.toLocallyRingedSpace.ringSheaf.obj.obj (op W),
      s = ∑ i, f i • M.val.map (homOfLE hW).op (g i)
  ker : ∀ (W : Opens Z.toPresheafedSpace) (hW : W ≤ N), StructureAcyclic W →
    ∀ f : I → Z.toLocallyRingedSpace.ringSheaf.obj.obj (op W),
      ∑ i, f i • M.val.map (homOfLE hW).op (g i) = 0 →
      ∃ c : I' → Z.toLocallyRingedSpace.ringSheaf.obj.obj (op W),
        ∀ i, f i = ∑ j, c j * Z.toLocallyRingedSpace.ringSheaf.obj.map (homOfLE hW).op (A j i)

attribute [instance] GeneratorData.fintypeI GeneratorData.fintypeI'

/-- A finite free resolution of `M` on `N` gives generator data on `N`. -/
theorem exists_generatorData (N : Opens Z.toPresheafedSpace) {d : ℕ}
    (h : ((Z.toLocallyRingedSpace.restrictModules N).obj M).HasFreeResolutionLE d) :
    ∃ D : GeneratorData M, D.N = N := by
  obtain ⟨I, I', _, _, g, A, hrel, H⟩ :=
    LocallyRingedSpace.exists_generators_acyclic N M h
  exact ⟨⟨N, I, I', g, A, hrel, fun W hW hWa ↦ (H W hW hWa).1,
    fun W hW hWa ↦ (H W hW hWa).2.1, fun W hW hWa ↦ (H W hW hWa).2.2⟩, rfl⟩

namespace GeneratorData

variable {M} (D : GeneratorData M) {n : ℕ} (φ : AnalyticSpace.complexAffineSpace.{u} n ⟶ Z)
  [LocallyRingedSpace.IsOpenImmersion φ.toLRSHom]

/-- `chartRingEquiv`, with values in the sections of the sheaf of rings `𝒪_Z` over which
sections of sheaves of modules are modules. -/
noncomputable def chartRing (V : Opens (ULift.{u} (Fin n) → ℂ)) :
    OkaRing V ≃+* Z.toLocallyRingedSpace.ringSheaf.obj.obj (op (chartOpen φ V)) :=
  chartRingEquiv φ V

lemma chartRing_restrict {V V' : Opens (ULift.{u} (Fin n) → ℂ)} (h : V' ≤ V) (f : OkaRing V) :
    chartRing φ V' (OkaRing.restrict h f) =
      Z.toLocallyRingedSpace.ringSheaf.obj.map (homOfLE (chartOpen_mono h)).op
        (chartRing φ V f) :=
  chartRingEquiv_restrict φ h f

variable {V : Opens (ULift.{u} (Fin n) → ℂ)} (hV : chartOpen φ V ≤ D.N)

/-- The restriction of the `i`-th generator to `φ(V)`. -/
noncomputable def gRes (i : D.I) : M.val.obj (op (chartOpen φ V)) :=
  M.val.map (homOfLE hV).op (D.g i)

/-- The map `ψ : 𝒪(V)^I → M(φ(V))`, `f ↦ ∑ᵢ fᵢ • gᵢ`. -/
noncomputable def psi : (D.I → OkaRing V) →+ M.val.obj (op (chartOpen φ V)) where
  toFun f := ∑ i, chartRing φ V (f i) • D.gRes φ hV i
  map_zero' := by simp
  map_add' f g := by simp [add_smul, Finset.sum_add_distrib]

lemma psi_apply (f : D.I → OkaRing V) :
    D.psi φ hV f = ∑ i, chartRing φ V (f i) • D.gRes φ hV i :=
  rfl

lemma gRes_apply (i : D.I) : D.gRes φ hV i = M.val.map (homOfLE hV).op (D.g i) :=
  rfl

/-- `ψ` is surjective on `φ(V)` if `𝒪_Z` is acyclic on `φ(V)`. -/
lemma psi_surjective (hacyc : StructureAcyclic (chartOpen φ V)) :
    Function.Surjective (D.psi φ hV) := fun s ↦ by
  obtain ⟨f, hf⟩ := D.surj _ hV hacyc s
  refine ⟨fun i ↦ (chartRing φ V).symm (f i), ?_⟩
  rw [psi_apply, hf]
  simp only [RingEquiv.apply_symm_apply, gRes_apply]
  rfl

variable (Z) in
/-- The constant `c`, as a section of `𝒪_Z` over `W`. -/
noncomputable def constRes (c : ℂ) (W : Opens Z.toPresheafedSpace) :
    Z.toLocallyRingedSpace.ringSheaf.obj.obj (op W) :=
  Z.presheaf.map (homOfLE le_top).op (Z.algebraMap c)

/-- `ψ` is compatible with the `ℂ`-actions. -/
lemma psi_smul (c : ℂ) (f : D.I → OkaRing V) :
    D.psi φ hV (c • f) = constRes Z c (chartOpen φ V) • D.psi φ hV f := by
  rw [psi_apply, psi_apply, Finset.smul_sum]
  refine Finset.sum_congr rfl fun i _ ↦ ?_
  rw [Pi.smul_apply, Algebra.smul_def, map_mul, mul_smul]
  congr 1
  exact chartRingEquiv_algebraMap φ V c

/-- `ψ` commutes with restriction to a smaller open in the same chart. -/
lemma psi_restrict {V' : Opens (ULift.{u} (Fin n) → ℂ)} (h : V' ≤ V) (f : D.I → OkaRing V) :
    D.psi φ ((chartOpen_mono h).trans hV) (fun i ↦ OkaRing.restrict h (f i)) =
      M.val.map (homOfLE (chartOpen_mono h)).op (D.psi φ hV f) := by
  rw [psi_apply, psi_apply, LocallyRingedSpace.sheafOfModules_map_sum_smul]
  refine Finset.sum_congr rfl fun i _ ↦ ?_
  rw [chartRing_restrict, gRes_apply, gRes_apply, LocallyRingedSpace.sheafOfModules_map_map]
  rfl

/-- The kernel of `ψ`, a `ℂ`-subspace. -/
noncomputable def kerSub : Submodule ℂ (D.I → OkaRing V) where
  carrier := {f | D.psi φ hV f = 0}
  add_mem' {a b} ha hb := by
    change D.psi φ hV (a + b) = 0
    rw [map_add, show D.psi φ hV a = 0 from ha, show D.psi φ hV b = 0 from hb, add_zero]
  zero_mem' := map_zero _
  smul_mem' c f hf := by
    change D.psi φ hV (c • f) = 0
    rw [psi_smul, show D.psi φ hV f = 0 from hf, smul_zero]

lemma mem_kerSub {f : D.I → OkaRing V} : f ∈ D.kerSub φ hV ↔ D.psi φ hV f = 0 :=
  Iff.rfl

attribute [irreducible] kerSub

/-- The matrix of relations, read in the chart. -/
noncomputable def relMatrix : Matrix D.I D.I' (OkaRing V) := fun i j ↦
  (chartRing φ V).symm (Z.toLocallyRingedSpace.ringSheaf.obj.map (homOfLE hV).op (D.A j i))

/-- The relations, restricted to `φ(V)`. -/
lemma sum_gRes_eq_zero (j : D.I') :
    ∑ i, Z.toLocallyRingedSpace.ringSheaf.obj.map (homOfLE hV).op (D.A j i) • D.gRes φ hV i =
      0 := by
  have := (LocallyRingedSpace.sheafOfModules_map_sum_smul M hV Finset.univ (D.A j) D.g).symm
  rw [D.rel j, map_zero] at this
  exact this

/-- Combinations of the rows of the relation matrix are killed by `ψ`. -/
lemma psi_sum_relMatrix {V₀ : Opens (ULift.{u} (Fin n) → ℂ)} (h₀ : V₀ ≤ V)
    (c : D.I' → OkaRing V₀) :
    D.psi φ ((chartOpen_mono h₀).trans hV)
      (fun i ↦ ∑ j, c j * OkaRing.restrict h₀ (D.relMatrix φ hV i j)) = 0 := by
  have h₁ : ∀ i j, chartRing φ V₀ (OkaRing.restrict h₀ (D.relMatrix φ hV i j)) =
      Z.toLocallyRingedSpace.ringSheaf.obj.map (homOfLE ((chartOpen_mono h₀).trans hV)).op
        (D.A j i) := fun i j ↦ by
    rw [chartRing_restrict, relMatrix, RingEquiv.apply_symm_apply,
      LocallyRingedSpace.ringSheaf_map_map]
  rw [psi_apply]
  simp_rw [map_sum, map_mul, h₁, Finset.sum_smul, mul_smul]
  rw [Finset.sum_comm]
  refine Finset.sum_eq_zero fun j _ ↦ ?_
  rw [← Finset.smul_sum, D.sum_gRes_eq_zero φ ((chartOpen_mono h₀).trans hV) j, smul_zero]

/-- The set of `f` whose germs lie pointwise in the span of the germs of the columns of the
relation matrix. -/
def germSet : Set (D.I → OkaRing V) :=
  {f | ∀ (x : ULift.{u} (Fin n) → ℂ) (hx : x ∈ V), OkaRing.germVec hx f ∈
    Submodule.span (LocalOkaRing (ULift.{u} (Fin n)))
      (range fun j ↦ OkaRing.germVec hx fun i ↦ D.relMatrix φ hV i j)}

lemma germSet_of_mem_kerSub (hacyc : StructureAcyclic (chartOpen φ V))
    {f : D.I → OkaRing V} (hf : f ∈ D.kerSub φ hV) : f ∈ D.germSet φ hV := fun x hx ↦ by
  obtain ⟨c, hc⟩ := D.ker _ hV hacyc (fun i ↦ chartRing φ V (f i)) ((D.mem_kerSub φ hV).1 hf)
  have : f = D.relMatrix φ hV *ᵥ fun j ↦ (chartRing φ V).symm (c j) := funext fun i ↦ by
    apply (chartRing φ V).injective
    rw [hc i, Matrix.mulVec, dotProduct, map_sum]
    refine Finset.sum_congr rfl fun j _ ↦ ?_
    rw [map_mul, relMatrix, RingEquiv.apply_symm_apply, RingEquiv.apply_symm_apply]
    exact LocallyRingedSpace.mul_comm_ringSheaf _ _
  rw [this]
  exact OkaRing.germVec_mulVec_mem_span _ _ hx

lemma exists_map_psi_eq_zero {f : D.I → OkaRing V} (hf : f ∈ D.germSet φ hV)
    {y : ULift.{u} (Fin n) → ℂ} (hy : y ∈ V) : ∃ (V₀ : Opens (ULift.{u} (Fin n) → ℂ))
      (h₀ : V₀ ≤ V), y ∈ V₀ ∧ M.val.map (homOfLE (chartOpen_mono h₀)).op (D.psi φ hV f) = 0 := by
  classical
  obtain ⟨V₀, h₀, hy₀, c, hc⟩ := OkaRing.exists_restrict_eq_mulVec _ f hy (hf y hy)
  refine ⟨V₀, h₀, hy₀, ?_⟩
  rw [← psi_restrict D φ hV h₀ f]
  have : (fun i ↦ OkaRing.restrict h₀ (f i)) =
      fun i ↦ ∑ j, c j * OkaRing.restrict h₀ (D.relMatrix φ hV i j) := funext hc
  rw [this, psi_sum_relMatrix]
  rfl

lemma mem_kerSub_of_germSet {f : D.I → OkaRing V} (hf : f ∈ D.germSet φ hV) :
    f ∈ D.kerSub φ hV := by
  choose V₀ h₀ hy₀ hV₀ using fun y (hy : y ∈ V) ↦ D.exists_map_psi_eq_zero φ hV hf hy
  rw [mem_kerSub]
  refine TopCat.Sheaf.eq_of_locally_eq' (F := (M.toAb : TopCat.Sheaf AddCommGrpCat.{u} _))
    (fun y : V ↦ chartOpen φ (V₀ y.1 y.2)) (chartOpen φ V)
    (fun y ↦ homOfLE (chartOpen_mono (h₀ y.1 y.2))) ?_ _ 0 fun y ↦ ?_
  · rintro _ ⟨y, hy, rfl⟩
    exact Opens.mem_iSup.2 ⟨⟨y, hy⟩, y, hy₀ y hy, rfl⟩
  · exact (hV₀ y.1 y.2).trans (map_zero _).symm

/-- **The kernel of `ψ` is described by germs**: `ψ f = 0` iff at every point the germ of `f`
lies in the span of the germs of the columns of the relation matrix. -/
lemma kerSub_eq (hacyc : StructureAcyclic (chartOpen φ V)) :
    (D.kerSub φ hV : Set (D.I → OkaRing V)) = D.germSet φ hV :=
  Set.ext fun _ ↦ ⟨D.germSet_of_mem_kerSub φ hV hacyc, D.mem_kerSub_of_germSet φ hV⟩

/-- **The kernel of `ψ` is closed** (Cartan's closure theorem). -/
lemma isClosed_kerSub (hacyc : StructureAcyclic (chartOpen φ V)) :
    IsClosed (D.kerSub φ hV : Set (D.I → OkaRing V)) := by
  rw [D.kerSub_eq φ hV hacyc]
  exact OkaRing.isClosed_setOf_forall_germVec_mem_span _

variable (hacyc : StructureAcyclic (chartOpen φ V))

/-- **The model of `M(φ(V))`**: the quotient `𝒪(V)^I / ker ψ` of a Fréchet space by a closed
subspace. -/
@[nolint unusedArguments]
def ModelSpace (_hacyc : StructureAcyclic (chartOpen φ V)) : Type u :=
  (D.I → OkaRing V) ⧸ D.kerSub φ hV

namespace ModelSpace

instance : AddCommGroup (D.ModelSpace φ hV hacyc) :=
  inferInstanceAs (AddCommGroup ((D.I → OkaRing V) ⧸ D.kerSub φ hV))

instance : Module ℂ (D.ModelSpace φ hV hacyc) :=
  inferInstanceAs (Module ℂ ((D.I → OkaRing V) ⧸ D.kerSub φ hV))

instance : TopologicalSpace (D.ModelSpace φ hV hacyc) :=
  inferInstanceAs (TopologicalSpace ((D.I → OkaRing V) ⧸ D.kerSub φ hV))

instance : IsTopologicalAddGroup (D.ModelSpace φ hV hacyc) :=
  inferInstanceAs (IsTopologicalAddGroup ((D.I → OkaRing V) ⧸ D.kerSub φ hV))

instance : ContinuousSMul ℂ (D.ModelSpace φ hV hacyc) :=
  inferInstanceAs (ContinuousSMul ℂ ((D.I → OkaRing V) ⧸ D.kerSub φ hV))

/-- The projection onto the model space, as an `ℝ`-linear map. -/
def projR : (D.I → OkaRing V) →ₗ[ℝ] D.ModelSpace φ hV hacyc where
  toFun f := Submodule.Quotient.mk (p := D.kerSub φ hV) f
  map_add' _ _ := rfl
  map_smul' r f := Submodule.Quotient.mk_smul (D.kerSub φ hV) (r : ℂ) f

instance : LocallyConvexSpace ℝ (D.ModelSpace φ hV hacyc) :=
  LocallyConvexSpace.of_isOpenQuotientMap (projR D φ hV hacyc)
    (Submodule.isOpenQuotientMap_mkQ (D.kerSub φ hV))

instance : UniformSpace (D.ModelSpace φ hV hacyc) :=
  IsTopologicalAddGroup.rightUniformSpace _

instance : IsUniformAddGroup (D.ModelSpace φ hV hacyc) :=
  isUniformAddGroup_of_addCommGroup

instance : FirstCountableTopology (D.ModelSpace φ hV hacyc) :=
  inferInstanceAs (FirstCountableTopology ((D.I → OkaRing V) ⧸ (D.kerSub φ hV).toAddSubgroup))

instance : CompleteSpace (D.ModelSpace φ hV hacyc) :=
  QuotientAddGroup.completeSpace_right (D.I → OkaRing V) (D.kerSub φ hV).toAddSubgroup

instance : T2Space (D.ModelSpace φ hV hacyc) := by
  haveI : IsClosed (D.kerSub φ hV : Set (D.I → OkaRing V)) := D.isClosed_kerSub φ hV hacyc
  exact inferInstanceAs (T2Space ((D.I → OkaRing V) ⧸ D.kerSub φ hV))

end ModelSpace

/-- The projection `𝒪(V)^I → M(φ(V))` onto the model. -/
def proj (f : D.I → OkaRing V) : D.ModelSpace φ hV hacyc :=
  Submodule.Quotient.mk (p := D.kerSub φ hV) f

lemma proj_surjective : Function.Surjective (D.proj φ hV hacyc) :=
  Submodule.Quotient.mk_surjective (D.kerSub φ hV)

lemma proj_add (f g : D.I → OkaRing V) :
    D.proj φ hV hacyc (f + g) = D.proj φ hV hacyc f + D.proj φ hV hacyc g :=
  rfl

lemma proj_smul (c : ℂ) (f : D.I → OkaRing V) :
    D.proj φ hV hacyc (c • f) = c • D.proj φ hV hacyc f :=
  rfl

lemma proj_eq_zero_iff {f : D.I → OkaRing V} : D.proj φ hV hacyc f = 0 ↔ D.psi φ hV f = 0 :=
  (Submodule.Quotient.mk_eq_zero (D.kerSub φ hV)).trans (D.mem_kerSub φ hV)

lemma isQuotientMap_proj : IsQuotientMap (D.proj φ hV hacyc) :=
  Submodule.isQuotientMap_mkQ (D.kerSub φ hV)

lemma isOpenMap_proj : IsOpenMap (D.proj φ hV hacyc) :=
  Submodule.isOpenMap_mkQ (D.kerSub φ hV)

lemma continuous_proj : Continuous (D.proj φ hV hacyc) :=
  Submodule.continuous_mkQ (D.kerSub φ hV)

/-- The map from the model to the sections, `[f] ↦ ψ f`. -/
def εHom : D.ModelSpace φ hV hacyc →+ M.val.obj (op (chartOpen φ V)) :=
  QuotientAddGroup.lift (D.kerSub φ hV).toAddSubgroup (D.psi φ hV)
    fun _ hx ↦ (D.mem_kerSub φ hV).1 hx

lemma εHom_proj (f : D.I → OkaRing V) : D.εHom φ hV hacyc (D.proj φ hV hacyc f) = D.psi φ hV f :=
  rfl

/-- **The model space is the space of sections**: `𝒪(V)^I / ker ψ ≃ M(φ(V))`. -/
def ε : D.ModelSpace φ hV hacyc ≃+ M.val.obj (op (chartOpen φ V)) :=
  AddEquiv.ofBijective (D.εHom φ hV hacyc) ⟨by
    rw [injective_iff_map_eq_zero]
    intro x hx
    obtain ⟨f, rfl⟩ := D.proj_surjective φ hV hacyc x
    exact (D.proj_eq_zero_iff φ hV hacyc).2 hx, fun s ↦ by
    obtain ⟨f, rfl⟩ := D.psi_surjective φ hV hacyc s
    exact ⟨D.proj φ hV hacyc f, rfl⟩⟩

lemma ε_proj (f : D.I → OkaRing V) : D.ε φ hV hacyc (D.proj φ hV hacyc f) = D.psi φ hV f :=
  rfl

lemma ε_symm_psi (f : D.I → OkaRing V) :
    (D.ε φ hV hacyc).symm (D.psi φ hV f) = D.proj φ hV hacyc f :=
  (D.ε φ hV hacyc).symm_apply_eq.2 rfl

/-- The model is compatible with the `ℂ`-actions. -/
lemma ε_smul (c : ℂ) (x : D.ModelSpace φ hV hacyc) :
    D.ε φ hV hacyc (c • x) = constRes Z c (chartOpen φ V) • D.ε φ hV hacyc x := by
  obtain ⟨f, rfl⟩ := D.proj_surjective φ hV hacyc x
  rw [← proj_smul, ε_proj, ε_proj, psi_smul]

section Restriction

variable {D φ hV hacyc} (D' : GeneratorData M) {φ' : AnalyticSpace.complexAffineSpace.{u} n ⟶ Z}
  [LocallyRingedSpace.IsOpenImmersion φ'.toLRSHom] {V' : Opens (ULift.{u} (Fin n) → ℂ)}
  (hV' : chartOpen φ' V' ≤ D'.N) (hacyc' : StructureAcyclic (chartOpen φ' V'))
  (h : chartOpen φ' V' ≤ chartOpen φ V)

lemma chartRing_chartRestrict (f : OkaRing V) :
    chartRing φ' V' (chartRestrict φ φ' h f) =
      Z.toLocallyRingedSpace.ringSheaf.obj.map (homOfLE h).op (chartRing φ V f) :=
  chartRingEquiv_chartRestrict φ φ' h f

/-- Restriction of sections from `φ(V)` to `φ'(V')`, read in the models. -/
def modelRes (x : D.ModelSpace φ hV hacyc) : D'.ModelSpace φ' hV' hacyc' :=
  (D'.ε φ' hV' hacyc').symm (M.val.map (homOfLE h).op (D.ε φ hV hacyc x))

/-- Restriction of a section of `M` from `φ(V)` to `φ'(V')`. -/
def resSec (s : M.val.obj (op (chartOpen φ V))) : M.val.obj (op (chartOpen φ' V')) :=
  M.val.map (homOfLE h).op s

lemma resSec_sum_smul (r : D.I → Z.toLocallyRingedSpace.ringSheaf.obj.obj (op (chartOpen φ V)))
    (σ : D.I → M.val.obj (op (chartOpen φ V))) :
    resSec h (∑ i, r i • σ i) =
      ∑ i, Z.toLocallyRingedSpace.ringSheaf.obj.map (homOfLE h).op (r i) • resSec h (σ i) :=
  LocallyRingedSpace.sheafOfModules_map_sum_smul M h Finset.univ r σ

include hacyc' in
/-- Restriction lifts to a continuous map `𝒪(V)^I → 𝒪(V')^{I'}`: the generators of `D`
restricted to `φ'(V')` are combinations of the generators of `D'`. -/
lemma exists_lift_res : ∃ L : (D.I → OkaRing V) → (D'.I → OkaRing V'), Continuous L ∧
    ∀ f, D'.psi φ' hV' (L f) = resSec h (D.psi φ hV f) := by
  choose G hG using fun i ↦ D'.psi_surjective φ' hV' hacyc' (resSec h (D.gRes φ hV i))
  refine ⟨fun f i' ↦ ∑ i, chartRestrictCLM h (f i) * G i i', ?_, fun f ↦ ?_⟩
  · exact continuous_pi fun i' ↦ continuous_finsetSum _ fun i _ ↦
      ((chartRestrictCLM h).continuous.comp (continuous_apply i)).mul continuous_const
  · have key : D'.psi φ' hV' (fun i' ↦ ∑ i, chartRestrictCLM h (f i) * G i i') =
        ∑ i, chartRing φ' V' (chartRestrict φ φ' h (f i)) • D'.psi φ' hV' (G i) := by
      simp_rw [chartRestrictCLM_apply, psi_apply, map_sum, map_mul, Finset.sum_smul, mul_smul,
        Finset.smul_sum]
      exact Finset.sum_comm
    rw [key, psi_apply, resSec_sum_smul]
    refine Finset.sum_congr rfl fun i _ ↦ ?_
    rw [hG, chartRing_chartRestrict]

lemma continuous_modelRes :
    Continuous (D.modelRes D' hV' hacyc' h (hV := hV) (hacyc := hacyc)) := by
  obtain ⟨L, hLc, hL⟩ := D.exists_lift_res D' hV' hacyc' h (hV := hV)
  have : D.modelRes D' hV' hacyc' h ∘ D.proj φ hV hacyc = D'.proj φ' hV' hacyc' ∘ L := by
    funext f
    simp only [Function.comp_apply, modelRes, ε_proj]
    rw [← resSec, ← hL, ε_symm_psi]
  refine (D.isQuotientMap_proj φ hV hacyc).continuous_iff.2 ?_
  rw [this]
  exact (D'.continuous_proj φ' hV' hacyc').comp hLc

end Restriction

/-- A map out of an open quotient whose composite with the projection is a compact operator is a
compact operator. -/
lemma _root_.IsCompactOperator.of_comp_isOpenMap {E F G : Type*} [Zero E] [Zero F]
    [TopologicalSpace E] [TopologicalSpace F] [TopologicalSpace G] {π : E → F}
    (hπ : IsOpenMap π) (hπ0 : π 0 = 0) {g : F → G} {k : E → G} (hk : IsCompactOperator k)
    (hcomm : ∀ x, g (π x) = k x) : IsCompactOperator g := by
  obtain ⟨K, hK, hKn⟩ := hk
  refine ⟨K, hK, ?_⟩
  have := hπ.image_mem_nhds hKn
  rw [hπ0] at this
  exact Filter.mem_of_superset this (by rintro _ ⟨x, hx, rfl⟩; simpa [Set.mem_preimage, hcomm]
    using hx)

/-- **Restriction to a relatively compact open in the same chart is a compact operator** (Montel's
theorem). -/
theorem isCompactOperator_modelRes {V' : Opens (ULift.{u} (Fin n) → ℂ)} (hVV' : V' ≤ V)
    (hc : IsCompact (closure (V' : Set (ULift.{u} (Fin n) → ℂ))))
    (hcl : closure (V' : Set (ULift.{u} (Fin n) → ℂ)) ⊆ V)
    (hV' : chartOpen φ V' ≤ D.N) (hacyc' : StructureAcyclic (chartOpen φ V')) :
    IsCompactOperator (D.modelRes D hV' hacyc' (chartOpen_mono hVV') (hV := hV)
      (hacyc := hacyc)) := by
  have hR : IsCompactOperator (fun (f : D.I → OkaRing V) (i : D.I) ↦
      OkaRing.restrictCLM (fun _ hx ↦ hcl (subset_closure hx)) (f i)) :=
    IsCompactOperator.piMap fun _ ↦ OkaRing.isCompactOperator_restrictCLM hc hcl
  refine IsCompactOperator.of_comp_isOpenMap (D.isOpenMap_proj φ hV hacyc) rfl
    (hR.continuous_comp (D.continuous_proj φ hV' hacyc')) fun f ↦ ?_
  simp only [Function.comp_apply, modelRes, ε_proj, OkaRing.restrictCLM_apply]
  rw [← psi_restrict D φ hV hVV' f, ε_symm_psi]

end GeneratorData

end

end ComplexAnalytic
