/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.AnalyticSpace.Nullstellensatz
import Oka.Geometry.RingedSpace.LocallyRingedSpace.CoherentModuleSections
import Oka.Geometry.RingedSpace.LocallyRingedSpace.HomSheafStalk
import Oka.Geometry.RingedSpace.LocallyRingedSpace.CocycleTwist

/-!
# Sections of coherent sheaves across sets of positive depth

Let `X` be a complex analytic space, `M` a coherent sheaf of `𝒪_X`-modules and `T ⊆ X`. Suppose
that at every point `z ∈ T` some germ `g ∈ 𝒪_{X,z}` vanishing on `T` near `z` is a nonzerodivisor
on the stalk `M_z` (`M` has depth at least one along `T`). Then a section of `M` over an open set
`V` which vanishes on `V \ T` is zero (`ComplexAnalytic.AnalyticSpace.eq_zero_of_isSMulRegular`).

If moreover `T` is closed and every point of `T` has arbitrarily small open neighbourhoods `W`
such that every section of `M` over `W \ T` extends to `W`, then restriction
`M(V) → M(V \ T)` is bijective for every open `V`
(`ComplexAnalytic.AnalyticSpace.bijective_restrict_of_forall_exists_extend`): the local
extensions glue since they are unique.

## Strategy

Let `s ∈ M(V)` vanish on `V \ T` and `z ∈ T`. Since `M` is coherent, the relations `a • s = 0`
are generated near `z` by finitely many sections `a₁, …, a_k`. At a point `y ∉ T` near `z` the
section `s` vanishes, so `1` is a relation and some `aₗ(y) ≠ 0`. Hence the common zero set of
the `aₗ` lies in `T`, where `g` vanishes, and the Rückert Nullstellensatz puts a power of `g`
into the ideal generated by the germs of the `aₗ`, which kill the germ of `s`. As `g` is a
nonzerodivisor on `M_z`, the germ of `s` at `z` vanishes.

## Main results

- `ComplexAnalytic.AnalyticSpace.exists_pow_smul_mgerm_eq_zero`: a power of a germ vanishing on
  `T` kills the germ of a section vanishing off `T`.
- `ComplexAnalytic.AnalyticSpace.eq_zero_of_isSMulRegular`: sections vanishing off a set along
  which `M` has depth at least one are zero.
- `ComplexAnalytic.AnalyticSpace.injective_restrict_of_isSMulRegular`: the injectivity of
  restriction.
- `ComplexAnalytic.AnalyticSpace.bijective_restrict_of_forall_exists_extend`: local extensions
  give bijectivity of restriction.
-/

universe u

open CategoryTheory TopologicalSpace Opposite Filter Topology AlgebraicGeometry

namespace ComplexAnalytic.AnalyticSpace

open LocallyRingedSpace

variable {X : AnalyticSpace.{u}} (M : SheafOfModules.{u} X.ringSheaf)

/-- The value of the restriction of a section is the value of the section. -/
lemma eval_res {V W : X.Opens} (h : V ≤ W) {y : X} (hy : y ∈ V) (s : X.presheaf.obj (op W)) :
    X.eval y hy (X.res h s) = X.eval y (h hy) s :=
  eval_map_homOfLE h hy s

/-- **A section vanishing off `T` is killed by a power of a germ vanishing on `T`.** Let `M` be
coherent, `s ∈ M(V)` a section whose restriction to `W` vanishes, where `W ⊆ V` contains
`V \ T`, and `g ∈ 𝒪(U)` a section vanishing on `U ∩ T`. Then at every `z ∈ U ∩ V` a power of
the germ of `g` kills the germ of `s`. -/
theorem exists_pow_smul_mgerm_eq_zero [M.IsCoherent] {T : Set X} {V W : X.Opens} (hWV : W ≤ V)
    (hVW : ∀ y ∈ V, y ∉ T → y ∈ W) (s : M.val.obj (op V)) (hs : modRes s W hWV = 0)
    {U : X.Opens} (g : X.presheaf.obj (op U)) (hgT : ∀ y (hy : y ∈ U), y ∈ T → X.eval y hy g = 0)
    {z : X} (hzU : z ∈ U) (hzV : z ∈ V) :
    ∃ N : ℕ, X.presheaf.germ U z hzU g ^ N • mgerm M V z hzV s = 0 := by
  obtain ⟨W₁, hW₁V, k, a, hzW₁, hrel, hgen⟩ :=
    hasLocalModuleRelations_of_isCoherent M V 1 (fun _ ↦ s) z hzV
  -- off `T`, some relation `aₗ` does not vanish
  have hoff : ∀ y (hy : y ∈ W₁), y ∉ T → ∃ l, X.eval y hy (a l 0) ≠ 0 := by
    intro y hy hyT
    have hyW : y ∈ W := hVW y (hW₁V hy) hyT
    obtain ⟨W₂, hW₂, hyW₂, c, hc⟩ := hgen (W₁ ⊓ W) inf_le_left (fun _ ↦ 1) (by
      simp only [Fin.sum_univ_one, one_smul]
      rw [← sectRes_sectRes M (inf_le_right : W₁ ⊓ W ≤ W) hWV]
      change sectRes M _ (modRes s W hWV) = 0
      rw [hs]
      exact sectRes_zero M _) y ⟨hy, hyW⟩
    by_contra! H
    have := congrArg (X.eval y hyW₂) (hc 0)
    simp only [map_sum, map_mul] at this
    rw [Finset.sum_eq_zero fun l _ ↦ ?_] at this
    · exact one_ne_zero ((map_one _).symm.trans ((eval_res _ _ _).symm.trans this))
    · rw [eval_res, H l, mul_zero]
  -- the Rückert Nullstellensatz
  have hzWn : z ∈ W₁ ⊓ U := ⟨hzW₁, hzU⟩
  obtain ⟨N, hN⟩ := X.isNullstellensatzAt z (W₁ ⊓ U) hzWn
    (fun l ↦ X.res inf_le_left (a l 0)) (X.res inf_le_right g)
    (Eventually.of_forall fun y hy hall ↦ by
      rw [eval_res]
      by_cases hyT : y ∈ T
      · exact hgT y _ hyT
      · obtain ⟨l, hl⟩ := hoff y hy.1 hyT
        exact absurd ((eval_res _ _ _).symm.trans (hall l)) hl)
  refine ⟨N, ?_⟩
  have hg : X.presheaf.germ (W₁ ⊓ U) z hzWn (X.res inf_le_right g) =
      X.presheaf.germ U z hzU g :=
    TopCat.Presheaf.germ_res_apply _ _ _ _ _
  rw [hg] at hN
  -- the germs of the relations kill the germ of `s`
  have hker : Ideal.span (Set.range fun l ↦ X.presheaf.germ (W₁ ⊓ U) z hzWn
      (X.res inf_le_left (a l 0))) ≤
        (LinearMap.toSpanSingleton (X.presheaf.stalk z) _ (mgerm M V z hzV s)).ker := by
    rw [Ideal.span_le]
    rintro _ ⟨l, rfl⟩
    rw [SetLike.mem_coe, LinearMap.mem_ker, LinearMap.toSpanSingleton_apply]
    have h1 : X.presheaf.germ (W₁ ⊓ U) z hzWn (X.res inf_le_left (a l 0)) =
        X.presheaf.germ W₁ z hzW₁ (a l 0) :=
      TopCat.Presheaf.germ_res_apply _ _ _ _ _
    change X.presheaf.germ (W₁ ⊓ U) z hzWn (X.res inf_le_left (a l 0)) • mgerm M V z hzV s = 0
    rw [h1, ← mgerm_modRes hW₁V z hzW₁ s, ← mgerm_smul]
    have := hrel l
    simp only [Fin.sum_univ_one] at this
    exact (congrArg _ this).trans (mgerm_zero _ _ _)
  have := LinearMap.mem_ker.mp (hker hN)
  rwa [LinearMap.toSpanSingleton_apply] at this

variable {M}

/-- **Sections vanishing off a set of positive depth are zero.** Let `M` be coherent and suppose
that at every `z ∈ T` some section `g` of `𝒪_X` near `z`, vanishing on `T`, has germ a
nonzerodivisor on `M_z`. If `s ∈ M(V)` restricts to zero on an open `W ⊆ V` containing `V \ T`,
then `s = 0`. -/
theorem eq_zero_of_isSMulRegular [M.IsCoherent] {T : Set X}
    (hT : ∀ z ∈ T, ∃ (U : X.Opens) (hzU : z ∈ U) (g : X.presheaf.obj (op U)),
      (∀ y (hy : y ∈ U), y ∈ T → X.eval y hy g = 0) ∧
      IsSMulRegular ((X.stalkFunctor z).obj M) (X.presheaf.germ U z hzU g))
    {V W : X.Opens} (hWV : W ≤ V) (hVW : ∀ y ∈ V, y ∉ T → y ∈ W) {s : M.val.obj (op V)}
    (hs : modRes s W hWV = 0) : s = 0 := by
  have hgerm : ∀ z (hz : z ∈ V), mgerm M V z hz s = 0 := by
    intro z hz
    by_cases hzT : z ∈ T
    · obtain ⟨U, hzU, g, hgT, hreg⟩ := hT z hzT
      obtain ⟨N, hN⟩ := exists_pow_smul_mgerm_eq_zero M hWV hVW s hs g hgT hzU hz
      exact (hreg.pow N).right_eq_zero_of_smul hN
    · rw [← mgerm_modRes hWV z (hVW z hz hzT) s, hs]
      exact mgerm_zero _ _ _
  choose O hOV hzO hO using fun z : V ↦
    exists_modRes_eq_zero_of_mgerm_eq_zero (N := M) z.1 z.2 s (hgerm z.1 z.2)
  exact modRes_eq_of_cover M O (fun z hz ↦ Opens.mem_iSup.mpr ⟨⟨z, hz⟩, hzO ⟨z, hz⟩⟩) hOV s 0
    fun a ↦ (hO a).trans (modRes_zero _).symm

/-- **Restriction is injective across a set of positive depth.** Under the hypotheses of
`ComplexAnalytic.AnalyticSpace.eq_zero_of_isSMulRegular`, restriction `M(V) → M(W)` is injective
for every open `W ⊆ V` containing `V \ T`. -/
theorem injective_restrict_of_isSMulRegular [M.IsCoherent] {T : Set X}
    (hT : ∀ z ∈ T, ∃ (U : X.Opens) (hzU : z ∈ U) (g : X.presheaf.obj (op U)),
      (∀ y (hy : y ∈ U), y ∈ T → X.eval y hy g = 0) ∧
      IsSMulRegular ((X.stalkFunctor z).obj M) (X.presheaf.germ U z hzU g))
    {V W : X.Opens} (hWV : W ≤ V) (hVW : ∀ y ∈ V, y ∉ T → y ∈ W) :
    Function.Injective fun s : M.val.obj (op V) ↦ modRes s W hWV := by
  intro s t hst
  rw [← sub_eq_zero]
  refine eq_zero_of_isSMulRegular hT hWV hVW ?_
  exact (map_sub (M.val.map (homOfLE hWV).op).hom s t).trans (sub_eq_zero.mpr hst)

/-- Two sections with equal restrictions to `A` have equal restrictions to every `B ≤ A`. -/
private lemma modRes_eq_of_modRes_eq {V V' A B : X.Opens} {x : M.val.obj (op V)}
    {y : M.val.obj (op V')} {hA : A ≤ V} {hA' : A ≤ V'} (h : modRes x A hA = modRes y A hA')
    (hBA : B ≤ A) : modRes x B (hBA.trans hA) = modRes y B (hBA.trans hA') := by
  rw [← modRes_res hA hBA, h, modRes_res]

/-- **Local extensions across a set of positive depth glue.** Let `M` be coherent, `O` the
complement of a set `T` along which `M` has depth at least one, and suppose that every point of
`T` has arbitrarily small open neighbourhoods `W` such that every section of `M` over `W ∩ O`
extends to `W`. Then restriction `M(V) → M(V ∩ O)` is bijective for every open `V`. -/
theorem bijective_restrict_of_forall_exists_extend [M.IsCoherent] {T : Set X} (O : X.Opens)
    (hO : (O : Set X) = Tᶜ)
    (hT : ∀ z ∈ T, ∃ (U : X.Opens) (hzU : z ∈ U) (g : X.presheaf.obj (op U)),
      (∀ y (hy : y ∈ U), y ∈ T → X.eval y hy g = 0) ∧
      IsSMulRegular ((X.stalkFunctor z).obj M) (X.presheaf.germ U z hzU g))
    (hext : ∀ z ∈ T, ∀ V : X.Opens, z ∈ V → ∃ W : X.Opens, W ≤ V ∧ z ∈ W ∧
      ∀ s : M.val.obj (op (W ⊓ O)), ∃ t : M.val.obj (op W), modRes t (W ⊓ O) inf_le_left = s)
    (V : X.Opens) :
    Function.Bijective fun t : M.val.obj (op V) ↦ modRes t (V ⊓ O) inf_le_left := by
  have hVO : ∀ {V : X.Opens}, ∀ y ∈ V, y ∉ T → y ∈ V ⊓ O := fun y hy hyT ↦
    ⟨hy, by rw [hO]; exact hyT⟩
  refine ⟨injective_restrict_of_isSMulRegular hT inf_le_left fun y hy hyT ↦ hVO y hy hyT,
    fun s ↦ ?_⟩
  -- local extensions of `s`
  have hloc : ∀ z : V, ∃ (W : X.Opens) (hWV : W ≤ V), z.1 ∈ W ∧ ∃ t : M.val.obj (op W),
      modRes t (W ⊓ O) inf_le_left = modRes s (W ⊓ O) (inf_le_inf_right O hWV) := by
    intro z
    by_cases hzT : z.1 ∈ T
    · obtain ⟨W, hWV, hzW, hW⟩ := hext z.1 hzT V z.2
      obtain ⟨t, ht⟩ := hW (modRes s (W ⊓ O) (inf_le_inf_right O hWV))
      exact ⟨W, hWV, hzW, t, ht⟩
    · exact ⟨V ⊓ O, inf_le_left, hVO z.1 z.2 hzT, s, rfl⟩
  choose W hWV hzW t ht using hloc
  -- the local extensions agree on overlaps, by injectivity
  have hglue : ∀ a b, modRes (t a) (W a ⊓ W b) inf_le_left =
      modRes (t b) (W a ⊓ W b) inf_le_right := by
    intro a b
    refine injective_restrict_of_isSMulRegular hT (V := W a ⊓ W b) (W := W a ⊓ W b ⊓ O)
      inf_le_left (fun y hy hyT ↦ hVO y hy hyT) ?_
    simp only [modRes_res]
    exact (modRes_eq_of_modRes_eq (ht a) (inf_le_inf_right O inf_le_left)).trans
      (modRes_eq_of_modRes_eq (ht b) (inf_le_inf_right O inf_le_right)).symm
  obtain ⟨u, hu, -⟩ := modRes_existsUnique_gluing M W
    (fun z hz ↦ Opens.mem_iSup.mpr ⟨⟨z, hz⟩, hzW ⟨z, hz⟩⟩) hWV t hglue
  refine ⟨u, modRes_eq_of_cover M (fun z ↦ W z ⊓ O)
    (fun y (hy : y ∈ V ⊓ O) ↦ Opens.mem_iSup.mpr ⟨⟨y, hy.1⟩, hzW ⟨y, hy.1⟩, hy.2⟩)
    (fun z ↦ inf_le_inf_right O (hWV z)) _ s fun z ↦ ?_⟩
  simp only [modRes_res]
  rw [← modRes_res (hWV z) inf_le_left, hu z, ht z]

end ComplexAnalytic.AnalyticSpace
