/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.AnalyticSpace.HartogsModule
import Oka.AnalyticSpace.FiniteEtalePushforwardCoherent
import Mathlib.RingTheory.Regular.RegularSequence

/-!
# Hartogs extension for coherent submodules of free modules

Let `X` be a complex analytic space, `T ⊆ X` with open complement `O`, `U ⊇ T` open and
`g, h ∈ 𝒪(U)` vanishing on `T`. Let `M` be a coherent sheaf of `𝒪_X`-modules together with
`𝒪`-linear functionals `τ₁, …, τ_m` on `M` over `U` which jointly separate sections
(`AlgebraicGeometry.LocallyRingedSpace.SeparatingFunctionals`), i.e. an embedding
`M|_U ↪ 𝒪_U^m`. Suppose that

* restriction `𝒪(V) → 𝒪(V ∩ O)` is surjective for every open `V ⊆ U` (scalar Hartogs extension);
* at every `z ∈ T` the germ of `g` is a nonzerodivisor on `𝒪_{X,z}` and `[g, h]` is a weakly
  regular sequence on the stalk `M_z` (`M` has depth at least two along `T`).

Then restriction `M(V) → M(V ∩ O)` is bijective for every open `V`
(`ComplexAnalytic.AnalyticSpace.bijective_restrict_of_separatingFunctionals`). This provides
the local extensions required by
`ComplexAnalytic.AnalyticSpace.bijective_restrict_of_forall_exists_extend`.

## Proof

Let `s ∈ M(V ∩ O)`. The functionals of `s` extend to `f ∈ 𝒪(V)^m`. At `z ∈ T ∩ V` consider the
ideal of germs `a` with `a f ∈ τ(M)` near `z` (`AlgebraicGeometry.LocallyRingedSpace.conductor`).
It contains the first coordinates of the relations between `f` and `τ(e₁), …, τ(e_k)` for local
generators `eᵢ` of `M`, which are locally finitely generated by Oka's theorem. Off `T` the vector
`f` is `τ(s)`, so these first coordinates have no common zero off `T`, and the Rückert
Nullstellensatz puts powers `gᵃ`, `hᵇ` into the ideal
(`AlgebraicGeometry.LocallyRingedSpace.exists_pow_mem_conductor`). If `gᵃ f = τ(t₁)` and
`hᵇ f = τ(t₂)`, then `hᵇ t₁ = gᵃ t₂`, so by regularity `t₁ = gᵃ t` and `f = τ(t)` near `z`: `t`
extends `s` near `z` (`AlgebraicGeometry.LocallyRingedSpace.exists_extend_of_mem_conductor`).
The local extensions glue as they are unique, since `g` is a nonzerodivisor on the stalks of `M`
along `T` (`ComplexAnalytic.AnalyticSpace.bijective_restrict_of_forall_exists_extend'`).

## Main definitions

- `AlgebraicGeometry.LocallyRingedSpace.SeparatingFunctionals M U`: functionals embedding `M|_U`
  into a free module.
- `AlgebraicGeometry.LocallyRingedSpace.conductor`: the ideal of germs `a` with `a f ∈ τ(M)`.

## Main results

- `RingTheory.Sequence.IsWeaklyRegular.exists_eq_pow_smul_of_pow_smul_eq`: if `[g, h]` is weakly
  regular on `M` and `hᵇ m = gᵃ m'`, then `m ∈ gᵃ M`.
- `ComplexAnalytic.AnalyticSpace.bijective_restrict_of_forall_exists_extend'`: extensions of
  individual sections near the points of a set of positive depth glue.
- `ComplexAnalytic.AnalyticSpace.bijective_restrict_of_separatingFunctionals`: Hartogs extension
  for `M`.
-/

open CategoryTheory TopologicalSpace Opposite Filter Topology AlgebraicGeometry
open RingTheory.Sequence Pointwise

universe u

/-! ### Powers of a weakly regular pair -/

section Algebra

variable {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M] {g h : R}

/-- If `[g, h]` is weakly regular on `M` and `h m = g m'`, then `m ∈ g M`. -/
theorem RingTheory.Sequence.IsWeaklyRegular.exists_eq_smul_of_smul_eq
    (H : IsWeaklyRegular M [g, h]) {m m' : M} (e : h • m = g • m') : ∃ m'', m = g • m'' := by
  rw [isWeaklyRegular_cons_iff, isWeaklyRegular_cons_iff] at H
  obtain ⟨-, H, -⟩ := H
  have hmem : ∀ x : M, Submodule.Quotient.mk (p := g • (⊤ : Submodule R M)) x = 0 ↔
      ∃ m'', x = g • m'' := fun x ↦ by
    rw [Submodule.Quotient.mk_eq_zero, Submodule.mem_smul_pointwise_iff_exists]
    simp [eq_comm]
  refine (hmem m).1 (H.right_eq_zero_of_smul ?_)
  rw [← Submodule.Quotient.mk_smul, e]
  exact (hmem _).2 ⟨m', rfl⟩

/-- If `[g, h]` is weakly regular on `M` and `hᵇ m = gᵃ m'`, then `m ∈ gᵃ M`. -/
theorem RingTheory.Sequence.IsWeaklyRegular.exists_eq_pow_smul_of_pow_smul_eq
    (H : IsWeaklyRegular M [g, h]) (a b : ℕ) {m m' : M} (e : h ^ b • m = g ^ a • m') :
    ∃ m'', m = g ^ a • m'' := by
  have hg : IsSMulRegular M g := ((isWeaklyRegular_cons_iff M g [h]).1 H).1
  -- the case `a = 1`
  have h1 : ∀ (b : ℕ) (m m' : M), h ^ b • m = g • m' → ∃ m'', m = g • m'' := by
    intro b
    induction b with
    | zero => exact fun m m' e ↦ ⟨m', by simpa using e⟩
    | succ b ih =>
      intro m m' e
      obtain ⟨m₁, hm₁⟩ := ih (h • m) m' (by rw [← mul_smul, ← pow_succ]; exact e)
      exact H.exists_eq_smul_of_smul_eq hm₁
  induction a generalizing m m' with
  | zero => exact ⟨m, by simp⟩
  | succ a ih =>
    obtain ⟨m₁, rfl⟩ := h1 b m (g ^ a • m') (by rw [e, pow_succ', mul_smul])
    have e' : h ^ b • m₁ = g ^ a • m' := by
      refine hg ?_
      change g • h ^ b • m₁ = g • g ^ a • m'
      rw [smul_comm, e, pow_succ', mul_smul]
    obtain ⟨m'', rfl⟩ := ih e'
    exact ⟨m'', by rw [pow_succ', mul_smul]⟩

end Algebra

/-! ### Separating functionals -/

namespace AlgebraicGeometry.LocallyRingedSpace

variable {Y : LocallyRingedSpace.{u}}

/-- **Separating functionals** on a sheaf of `𝒪_Y`-modules `M` over an open `U`: `𝒪`-linear
functionals `τ₁, …, τ_m` on the sections of `M` over opens inside `U`, compatible with
restriction, which jointly separate sections. Equivalently, an embedding `M|_U ↪ 𝒪_U^m`. -/
structure SeparatingFunctionals (M : SheafOfModules.{u} Y.ringSheaf) (U : Opens Y) where
  /-- The number of functionals. -/
  m : ℕ
  /-- The functionals. -/
  τ : Fin m → ∀ V : Opens Y, V ≤ U → M.val.obj (op V) → Y.presheaf.obj (op V)
  τ_add : ∀ j V hV (a b : M.val.obj (op V)), τ j V hV (a + b) = τ j V hV a + τ j V hV b
  τ_smul : ∀ j V hV (r : Y.presheaf.obj (op V)) (a : M.val.obj (op V)),
    τ j V hV (r • a) = r * τ j V hV a
  τ_res : ∀ j V hV V' hV' (h : V' ≤ V) (a : M.val.obj (op V)),
    τ j V' hV' (sectRes M h a) = Y.res h (τ j V hV a)
  eq_zero_of_τ : ∀ V hV (a : M.val.obj (op V)), (∀ j, τ j V hV a = 0) → a = 0

namespace SeparatingFunctionals

variable {M : SheafOfModules.{u} Y.ringSheaf} {U : Opens Y} (D : SeparatingFunctionals M U)

lemma τ_zero (j : Fin D.m) {V : Opens Y} (hV : V ≤ U) : D.τ j V hV 0 = 0 := by
  simpa using D.τ_smul j V hV 0 0

lemma τ_neg (j : Fin D.m) {V : Opens Y} (hV : V ≤ U) (a : M.val.obj (op V)) :
    D.τ j V hV (-a) = -D.τ j V hV a := by
  simpa using D.τ_smul j V hV (-1) a

lemma τ_sub (j : Fin D.m) {V : Opens Y} (hV : V ≤ U) (a b : M.val.obj (op V)) :
    D.τ j V hV (a - b) = D.τ j V hV a - D.τ j V hV b := by
  rw [sub_eq_add_neg, D.τ_add, D.τ_neg, ← sub_eq_add_neg]

lemma τ_sum (j : Fin D.m) {V : Opens Y} (hV : V ≤ U) {k : ℕ} (a : Fin k → M.val.obj (op V)) :
    D.τ j V hV (∑ i, a i) = ∑ i, D.τ j V hV (a i) := by
  classical
  have : ∀ s : Finset (Fin k), D.τ j V hV (∑ i ∈ s, a i) = ∑ i ∈ s, D.τ j V hV (a i) := by
    intro s
    induction s using Finset.induction_on with
    | empty => simpa using D.τ_zero j hV
    | insert i s hi ih => rw [Finset.sum_insert hi, Finset.sum_insert hi, D.τ_add, ih]
  exact this Finset.univ

/-- Sections with the same values of all functionals are equal. -/
lemma ext {V : Opens Y} (hV : V ≤ U) {a b : M.val.obj (op V)}
    (h : ∀ j, D.τ j V hV a = D.τ j V hV b) : a = b :=
  sub_eq_zero.1 (D.eq_zero_of_τ V hV _ fun j ↦ by rw [D.τ_sub, h j, sub_self])

/-- Separating functionals restrict to smaller opens. -/
def restrict {U' : Opens Y} (hU' : U' ≤ U) : SeparatingFunctionals M U' where
  m := D.m
  τ j V hV := D.τ j V (hV.trans hU')
  τ_add j V _ := D.τ_add j V _
  τ_smul j V _ := D.τ_smul j V _
  τ_res j V _ V' _ := D.τ_res j V _ V' _
  eq_zero_of_τ V _ := D.eq_zero_of_τ V _

end SeparatingFunctionals

end AlgebraicGeometry.LocallyRingedSpace

namespace ComplexAnalytic.AnalyticSpace

open LocallyRingedSpace

variable {X : AnalyticSpace.{u}} {M : SheafOfModules.{u} X.ringSheaf}

/-! ### Gluing local extensions -/

/-- **Extensions of sections near a set of positive depth glue.** Let `M` be coherent, `O` the
complement of a set `T` along which `M` has depth at least one, and suppose that every section of
`M` over `V ∩ O` extends to a neighbourhood in `V` of each point of `T ∩ V`. Then restriction
`M(V) → M(V ∩ O)` is bijective for every open `V`. -/
theorem bijective_restrict_of_forall_exists_extend' [M.IsCoherent] {T : Set X} (O : X.Opens)
    (hO : (O : Set X) = Tᶜ)
    (hT : ∀ z ∈ T, ∃ (U : X.Opens) (hzU : z ∈ U) (g : X.presheaf.obj (op U)),
      (∀ y (hy : y ∈ U), y ∈ T → X.eval y hy g = 0) ∧
      IsSMulRegular ((X.stalkFunctor z).obj M) (X.presheaf.germ U z hzU g))
    (hext : ∀ (V : X.Opens) (s : M.val.obj (op (V ⊓ O))) (z : X), z ∈ V → z ∈ T →
      ∃ (W : X.Opens) (hWV : W ≤ V), z ∈ W ∧ ∃ t : M.val.obj (op W),
        modRes t (W ⊓ O) inf_le_left = modRes s (W ⊓ O) (inf_le_inf_right O hWV))
    (V : X.Opens) :
    Function.Bijective fun t : M.val.obj (op V) ↦ modRes t (V ⊓ O) inf_le_left := by
  have hVO : ∀ {V : X.Opens}, ∀ y ∈ V, y ∉ T → y ∈ V ⊓ O := fun y hy hyT ↦
    ⟨hy, by rw [hO]; exact hyT⟩
  refine ⟨injective_restrict_of_isSMulRegular hT inf_le_left fun y hy hyT ↦ hVO y hy hyT,
    fun s ↦ ?_⟩
  -- local extensions of `s`
  have hloc : ∀ z : V, ∃ (W : X.Opens) (hWV : W ≤ V), z.1 ∈ W ∧ ∃ t : M.val.obj (op W),
      modRes t (W ⊓ O) inf_le_left = modRes s (W ⊓ O) (inf_le_inf_right O hWV) := by
    intro z
    by_cases hzT : z.1 ∈ T
    · exact hext V s z.1 z.2 hzT
    · exact ⟨V ⊓ O, inf_le_left, hVO z.1 z.2 hzT, s, rfl⟩
  choose W hWV hzW t ht using hloc
  -- the local extensions agree on overlaps, by injectivity
  have hglue : ∀ a b, modRes (t a) (W a ⊓ W b) inf_le_left =
      modRes (t b) (W a ⊓ W b) inf_le_right := by
    intro a b
    refine injective_restrict_of_isSMulRegular hT (V := W a ⊓ W b) (W := W a ⊓ W b ⊓ O)
      inf_le_left (fun y hy hyT ↦ hVO y hy hyT) ?_
    simp only [modRes_res]
    have ha : modRes (t a) (W a ⊓ W b ⊓ O) (inf_le_inf_right O inf_le_left |>.trans inf_le_left) =
        modRes s (W a ⊓ W b ⊓ O) (inf_le_inf_right O (inf_le_left.trans (hWV a))) := by
      rw [← modRes_res inf_le_left (inf_le_inf_right O inf_le_left), ht a, modRes_res]
    have hb : modRes (t b) (W a ⊓ W b ⊓ O)
        (inf_le_inf_right O inf_le_right |>.trans inf_le_left) =
        modRes s (W a ⊓ W b ⊓ O) (inf_le_inf_right O (inf_le_right.trans (hWV b))) := by
      rw [← modRes_res inf_le_left (inf_le_inf_right O inf_le_right), ht b, modRes_res]
    exact ha.trans hb.symm
  obtain ⟨u, hu, -⟩ := modRes_existsUnique_gluing M W
    (fun z hz ↦ Opens.mem_iSup.mpr ⟨⟨z, hz⟩, hzW ⟨z, hz⟩⟩) hWV t hglue
  refine ⟨u, modRes_eq_of_cover M (fun z ↦ W z ⊓ O)
    (fun y (hy : y ∈ V ⊓ O) ↦ Opens.mem_iSup.mpr ⟨⟨y, hy.1⟩, hzW ⟨y, hy.1⟩, hy.2⟩)
    (fun z ↦ inf_le_inf_right O (hWV z)) _ s fun z ↦ ?_⟩
  simp only [modRes_res]
  rw [← modRes_res (hWV z) inf_le_left, hu z, ht z]

end ComplexAnalytic.AnalyticSpace

/-! ### The conductor -/

namespace AlgebraicGeometry.LocallyRingedSpace

section Conductor

variable {Y : LocallyRingedSpace.{u}} {M : SheafOfModules.{u} Y.ringSheaf} {U : Opens Y}
  (D : SeparatingFunctionals M U) {V : Opens Y} (hV : V ≤ U)
  (f : Fin D.m → Y.presheaf.obj (op V)) (z : Y)

/-- The germ `a` at `z` satisfies `a f = τ(t)` near `z` for a section `t` of `M`. -/
def ConductorMem (a : Y.presheaf.stalk z) : Prop :=
  ∃ (W : Opens Y) (hWV : W ≤ V) (hzW : z ∈ W) (r : Y.presheaf.obj (op W))
    (t : M.val.obj (op W)), Y.presheaf.germ W z hzW r = a ∧
      ∀ j, r * Y.res hWV (f j) = D.τ j W (hWV.trans hV) t

variable {D hV f z}

lemma conductorMem_zero (hz : z ∈ V) : ConductorMem D hV f z 0 :=
  ⟨V, le_rfl, hz, 0, 0, map_zero _, fun j ↦ by rw [zero_mul, D.τ_zero]⟩

/-- The defining equation of the conductor restricts to smaller opens. -/
lemma conductor_eq_res {W : Opens Y} (hWV : W ≤ V) {r : Y.presheaf.obj (op W)}
    {t : M.val.obj (op W)} (e : ∀ j, r * Y.res hWV (f j) = D.τ j W (hWV.trans hV) t)
    {W' : Opens Y} (h : W' ≤ W) :
    ∀ j, Y.res h r * Y.res (h.trans hWV) (f j) = D.τ j W' ((h.trans hWV).trans hV)
      (sectRes M h t) := fun j ↦ by
  rw [D.τ_res _ _ (hWV.trans hV), ← e j, res_mul, res_res]

lemma conductor_eq_add {W : Opens Y} (hWV : W ≤ V) {r r' : Y.presheaf.obj (op W)}
    {t t' : M.val.obj (op W)} (e : ∀ j, r * Y.res hWV (f j) = D.τ j W (hWV.trans hV) t)
    (e' : ∀ j, r' * Y.res hWV (f j) = D.τ j W (hWV.trans hV) t') :
    ∀ j, (r + r') * Y.res hWV (f j) = D.τ j W (hWV.trans hV) (t + t') := fun j ↦ by
  rw [D.τ_add, ← e j, ← e' j, add_mul]

lemma conductor_eq_mul {W : Opens Y} (hWV : W ≤ V) (c : Y.presheaf.obj (op W))
    {r : Y.presheaf.obj (op W)} {t : M.val.obj (op W)}
    (e : ∀ j, r * Y.res hWV (f j) = D.τ j W (hWV.trans hV) t) :
    ∀ j, (c * r) * Y.res hWV (f j) = D.τ j W (hWV.trans hV) (c • t) := fun j ↦ by
  rw [D.τ_smul, ← e j, mul_assoc]

lemma ConductorMem.add {a b : Y.presheaf.stalk z} (ha : ConductorMem D hV f z a)
    (hb : ConductorMem D hV f z b) : ConductorMem D hV f z (a + b) := by
  obtain ⟨W₁, h₁, hz₁, r₁, t₁, rfl, e₁⟩ := ha
  obtain ⟨W₂, h₂, hz₂, r₂, t₂, rfl, e₂⟩ := hb
  refine ⟨W₁ ⊓ W₂, inf_le_left.trans h₁, ⟨hz₁, hz₂⟩, _, _, ?_,
    conductor_eq_add (hV := hV) _ (conductor_eq_res (hV := hV) h₁ e₁ inf_le_left)
      (conductor_eq_res (hV := hV) h₂ e₂ inf_le_right)⟩
  rw [map_add, germ_res, germ_res]

lemma ConductorMem.mul (c : Y.presheaf.stalk z) {a : Y.presheaf.stalk z}
    (ha : ConductorMem D hV f z a) : ConductorMem D hV f z (c * a) := by
  obtain ⟨W₁, h₁, hz₁, r₁, t₁, rfl, e₁⟩ := ha
  obtain ⟨W₂, hz₂, c', rfl⟩ := Y.presheaf.exists_germ_eq c
  refine ⟨W₁ ⊓ W₂, inf_le_left.trans h₁, ⟨hz₁, hz₂⟩, _, _, ?_,
    conductor_eq_mul (hV := hV) _ (Y.res inf_le_right c')
      (conductor_eq_res (hV := hV) h₁ e₁ inf_le_left)⟩
  rw [map_mul, germ_res, germ_res]

variable (D hV f z) in
/-- **The conductor** at `z ∈ V` of a vector `f ∈ 𝒪(V)^m`: the ideal of germs `a` at `z` such
that near `z`, `a f = τ(t)` for a section `t` of `M`. -/
def conductor (hz : z ∈ V) : Ideal (Y.presheaf.stalk z) where
  carrier := {a | ConductorMem D hV f z a}
  zero_mem' := conductorMem_zero (D := D) (hV := hV) (f := f) hz
  add_mem' ha hb := ConductorMem.add (hV := hV) ha hb
  smul_mem' c _ ha := ConductorMem.mul (hV := hV) c ha

lemma mem_conductor_iff (hz : z ∈ V) (a : Y.presheaf.stalk z) :
    a ∈ conductor D hV f z hz ↔ ConductorMem D hV f z a :=
  Iff.rfl

end Conductor

/-! ### Powers of germs vanishing along `T` lie in the conductor -/

section Local

variable {Y : LocallyRingedSpace.{u}} {M : SheafOfModules.{u} Y.ringSheaf} {U : Opens Y}
  (D : SeparatingFunctionals M U) {T : Set Y} (O : Opens Y) (hO : (O : Set Y) = Tᶜ)
  {V : Opens Y} (hV : V ≤ U) (s : M.val.obj (op (V ⊓ O))) (f : Fin D.m → Y.presheaf.obj (op V))
  (hf : ∀ j, Y.res inf_le_left (f j) = D.τ j (V ⊓ O) (inf_le_left.trans hV) s)

include hO hf in
/-- **A germ satisfying the Nullstellensatz along `T` has a power in the conductor.** Let `M` be
coherent with separating functionals on `U`, and `f ∈ 𝒪(V)^m`, `V ⊆ U`, a vector extending the
values of the functionals at a section `s` of `M` over `V ∩ O`, where `O` is the complement of
`T`. If a germ `a` at `z ∈ V` has a power in the ideal generated by the germs of any sections
`φ_l` near `z` without common zero off `T` (the Rückert Nullstellensatz for `a` vanishing on
`T`), then a power of `a` lies in the conductor of `f` at `z`. -/
theorem exists_pow_mem_conductor [M.IsCoherent]
    (hTup : HasLocalTupleRelations (SheafOfModules.unit Y.ringSheaf)) {z : Y} (hz : z ∈ V)
    (a : Y.presheaf.stalk z)
    (hNS : ∀ (W : Opens Y) (hzW : z ∈ W) {K : ℕ} (φ : Fin K → Y.presheaf.obj (op W)),
      (∀ y (hy : y ∈ W), y ∉ T → Ideal.span (Set.range fun l ↦ Y.presheaf.germ W y hy (φ l)) = ⊤) →
      ∃ N : ℕ, a ^ N ∈ Ideal.span (Set.range fun l ↦ Y.presheaf.germ W z hzW (φ l))) :
    ∃ N : ℕ, a ^ N ∈ conductor D hV f z hz := by
  -- local generators of `M`
  obtain ⟨W₀, k, e₀, hzW₀, hgen₀⟩ := isLocallyFinitelyGeneratedModule_of_isFiniteType M z
  set W₁ : Opens Y := W₀ ⊓ V
  have hW₁V : W₁ ≤ V := inf_le_right
  have hW₁₀ : W₁ ≤ W₀ := inf_le_left
  -- the tuple `(f, τ(e₁), …, τ(e_k))` and its relations
  let v : Fin (k + 1) → Fin D.m → Y.presheaf.obj (op W₁) :=
    Fin.cons (fun j ↦ Y.res hW₁V (f j)) fun l j ↦ D.τ j W₁ (hW₁V.trans hV) (sectRes M hW₁₀ (e₀ l))
  obtain ⟨W₂, hW₂, K, ρ, hzW₂, hrel, hgen⟩ := hTup W₁ (k + 1) D.m v z ⟨hzW₀, hz⟩
  have hrel' : ∀ l j, ∑ i, ρ l i * Y.res hW₂ (v i j) = 0 := hrel
  -- off `T`, the germs of the first coordinates `ρ l 0` generate the unit ideal
  have hoff : ∀ y (hy : y ∈ W₂), y ∉ T →
      Ideal.span (Set.range fun l ↦ Y.presheaf.germ W₂ y hy (ρ l 0)) = ⊤ := by
    intro y hy hyT
    have hyO : y ∈ O := by
      have : y ∈ (O : Set Y) := by rw [hO]; exact hyT
      exact this
    have hle : W₂ ⊓ O ≤ W₀ := inf_le_left.trans (hW₂.trans hW₁₀)
    obtain ⟨W₃, hW₃, hyW₃, c, hc⟩ := hgen₀ (W₂ ⊓ O) hle
      (sectRes M (inf_le_inf_right O (hW₂.trans hW₁V)) s) y ⟨hy, hyO⟩
    have hW₃₂ : W₃ ≤ W₂ := hW₃.trans inf_le_left
    let a : Fin (k + 1) → Y.presheaf.obj (op W₃) := Fin.cons 1 fun l ↦ -c l
    have hW₃V : W₃ ≤ V ⊓ O := hW₃.trans (inf_le_inf_right O (hW₂.trans hW₁V))
    have hW₃U : W₃ ≤ U := (hW₃V.trans inf_le_left).trans hV
    have ha : ∀ j, ∑ i, a i * Y.res (hW₃₂.trans hW₂) (v i j) = 0 := by
      intro j
      have E1 : D.τ j W₃ hW₃U (sectRes M hW₃V s) = Y.res (hW₃V.trans inf_le_left) (f j) :=
        (D.τ_res j (V ⊓ O) (inf_le_left.trans hV) W₃ hW₃U hW₃V s).trans
          ((congrArg (Y.res hW₃V) (hf j).symm).trans (res_res _ _ _ _))
      have E2 : sectRes M hW₃V s =
          ∑ l, c l • sectRes M (hW₃₂.trans (hW₂.trans hW₁₀)) (e₀ l) := by
        rw [← hc, sectRes_sectRes]
      have E3 : ∀ l, Y.res (hW₃₂.trans hW₂) (D.τ j W₁ (hW₁V.trans hV) (sectRes M hW₁₀ (e₀ l))) =
          D.τ j W₃ hW₃U (sectRes M (hW₃₂.trans (hW₂.trans hW₁₀)) (e₀ l)) := fun l ↦
        (D.τ_res j W₁ (hW₁V.trans hV) W₃ hW₃U (hW₃₂.trans hW₂) (sectRes M hW₁₀ (e₀ l))).symm.trans
          (congrArg (D.τ j W₃ hW₃U) (sectRes_sectRes M _ _ _))
      rw [E2] at E1
      simp only [D.τ_sum, D.τ_smul] at E1
      refine (Fin.sum_univ_succ _).trans ?_
      simp only [a, v, Fin.cons_zero, Fin.cons_succ, res_res, one_mul, neg_mul,
        Finset.sum_neg_distrib]
      simp only [E3, E1, add_neg_cancel]
    obtain ⟨W₄, hW₄, hyW₄, d, hd⟩ := hgen W₃ hW₃₂ a ha y hyW₃
    have h0 := congrArg (Y.presheaf.germ W₄ y hyW₄) (hd 0)
    simp only [a, Fin.cons_zero, map_one, map_sum, map_mul, germ_res] at h0
    rw [Ideal.eq_top_iff_one, h0]
    exact Ideal.sum_mem _ fun l _ ↦ Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨l, rfl⟩)
  obtain ⟨N, hN⟩ := hNS W₂ hzW₂ (fun l ↦ ρ l 0) hoff
  refine ⟨N, Ideal.span_le.2 ?_ hN⟩
  rintro _ ⟨l, rfl⟩
  have hW₂V : W₂ ≤ V := hW₂.trans hW₁V
  have hW₂U : W₂ ≤ U := hW₂V.trans hV
  refine ⟨W₂, hW₂V, hzW₂, ρ l 0,
    -∑ i, ρ l i.succ • sectRes M (hW₂.trans hW₁₀) (e₀ i), rfl, fun j ↦ ?_⟩
  have E3 : ∀ i, Y.res hW₂ (D.τ j W₁ (hW₁V.trans hV) (sectRes M hW₁₀ (e₀ i))) =
      D.τ j W₂ hW₂U (sectRes M (hW₂.trans hW₁₀) (e₀ i)) := fun i ↦
    (D.τ_res j W₁ (hW₁V.trans hV) W₂ hW₂U hW₂ (sectRes M hW₁₀ (e₀ i))).symm.trans
      (congrArg (D.τ j W₂ hW₂U) (sectRes_sectRes M _ _ _))
  have hr := hrel' l j
  rw [Fin.sum_univ_succ] at hr
  simp only [v, Fin.cons_zero, Fin.cons_succ, res_res, E3] at hr
  simp only [D.τ_neg, D.τ_sum, D.τ_smul]
  exact eq_neg_of_add_eq_zero_left hr

/-- A point lying in finitely many opens has a neighbourhood inside all of them. -/
lemma exists_opens_le_forall {ι : Type*} [Finite ι] {x : Y} {W : Opens Y} (hx : x ∈ W)
    (W' : ι → Opens Y) (hW' : ∀ i, x ∈ W' i) :
    ∃ W'' : Opens Y, x ∈ W'' ∧ W'' ≤ W ∧ ∀ i, W'' ≤ W' i := by
  haveI := Fintype.ofFinite ι
  refine ⟨W ⊓ Finset.univ.inf W', ⟨hx, ?_⟩, inf_le_left,
    fun i ↦ inf_le_right.trans (Finset.inf_le (Finset.mem_univ i))⟩
  rw [Opens.coe_finset_inf]
  simpa using hW'

lemma mgerm_sectRes {W W' : Opens Y} (h : W ≤ W') {x : Y} (hx : x ∈ W)
    (t : M.val.obj (op W')) : mgerm M W x hx (sectRes M h t) = mgerm M W' x (h hx) t :=
  mgerm_modRes h x hx t

include hf in
/-- **Local extension from the conductor.** If `gᵃ` and `hᵇ` lie in the conductor of `f` at `z`,
where the germ `g` is a nonzerodivisor on `𝒪_{Y,z}` and `[g, h]` is weakly regular on `M_z`,
then `s` extends to a neighbourhood of `z` in `V`. -/
theorem exists_extend_of_mem_conductor {z : Y} (hz : z ∈ V) {g h : Y.presheaf.stalk z}
    (hg : IsSMulRegular (Y.presheaf.stalk z) g)
    (hreg : IsWeaklyRegular ((Y.stalkFunctor z).obj M) [g, h]) {a b : ℕ}
    (ha : g ^ a ∈ conductor D hV f z hz) (hb : h ^ b ∈ conductor D hV f z hz) :
    ∃ (W : Opens Y) (hWV : W ≤ V), z ∈ W ∧ ∃ t : M.val.obj (op W),
      sectRes M (inf_le_left : W ⊓ O ≤ W) t = sectRes M (inf_le_inf_right O hWV) s := by
  obtain ⟨W₁, h₁, hz₁, r₁, t₁, hr₁, e₁⟩ := ha
  obtain ⟨W₂, h₂, hz₂, r₂, t₂, hr₂, e₂⟩ := hb
  set W₃ := W₁ ⊓ W₂
  have hW₃V : W₃ ≤ V := inf_le_left.trans h₁
  have hW₃U : W₃ ≤ U := hW₃V.trans hV
  have hz₃ : z ∈ W₃ := ⟨hz₁, hz₂⟩
  -- `hᵇ t₁ = gᵃ t₂` near `z`
  have key : (Y.res (inf_le_right : W₃ ≤ W₂) r₂ : Y.presheaf.obj (op W₃)) •
      (sectRes M (inf_le_left : W₃ ≤ W₁) t₁ : M.val.obj (op W₃)) =
      (Y.res (inf_le_left : W₃ ≤ W₁) r₁ : Y.presheaf.obj (op W₃)) •
      (sectRes M (inf_le_right : W₃ ≤ W₂) t₂ : M.val.obj (op W₃)) := by
    refine D.ext hW₃U fun j ↦ ?_
    refine (conductor_eq_mul (hV := hV) hW₃V (Y.res inf_le_right r₂)
      (conductor_eq_res (hV := hV) h₁ e₁ inf_le_left) j).symm.trans ?_
    refine Eq.trans ?_ (conductor_eq_mul (hV := hV) hW₃V (Y.res inf_le_left r₁)
      (conductor_eq_res (hV := hV) h₂ e₂ inf_le_right) j)
    exact congrArg (· * _) (mul_comm _ _)
  have hgerm := congrArg (mgerm M W₃ z hz₃) key
  simp only [mgerm_smul, germ_res, hr₁, hr₂, mgerm_sectRes] at hgerm
  -- `t₁ = gᵃ t₄` near `z`
  obtain ⟨μ, hμ⟩ := hreg.exists_eq_pow_smul_of_pow_smul_eq a b hgerm
  obtain ⟨W₄, hz₄, t₄, rfl⟩ := exists_mgerm_eq z μ
  have hμ' : mgerm M W₁ z hz₁ t₁ = mgerm M (W₁ ⊓ W₄) z ⟨hz₁, hz₄⟩
      ((Y.res (inf_le_left : W₁ ⊓ W₄ ≤ W₁) r₁ : Y.presheaf.obj (op (W₁ ⊓ W₄))) •
        (sectRes M (inf_le_right : W₁ ⊓ W₄ ≤ W₄) t₄ : M.val.obj (op (W₁ ⊓ W₄)))) := by
    simp only [mgerm_smul, germ_res, hr₁, mgerm_sectRes]
    exact hμ
  obtain ⟨W₅, h₅₁, h₅₂, hz₅, e₅⟩ := exists_modRes_eq_of_mgerm_eq z hz₁ _ _ _ hμ'
  have hW₅V : W₅ ≤ V := h₅₁.trans h₁
  have hW₅U : W₅ ≤ U := hW₅V.trans hV
  have hW₅₄ : W₅ ≤ W₄ := h₅₂.trans inf_le_right
  have E5 : sectRes M h₅₁ t₁ = Y.res h₅₁ r₁ • sectRes M hW₅₄ t₄ := by
    refine e₅.trans ?_
    change sectRes M h₅₂ _ = _
    rw [sectRes_smul, sectRes_sectRes, res_res]
  -- the germs of `f - τ(t₄)` vanish at `z`
  have hj : ∀ j, Y.presheaf.germ W₅ z hz₅
      (Y.res hW₅V (f j) - D.τ j W₅ hW₅U (sectRes M hW₅₄ t₄)) = 0 := by
    intro j
    refine (hg.pow a) ?_
    have e := conductor_eq_res (hV := hV) h₁ e₁ h₅₁ j
    rw [E5, D.τ_smul] at e
    change g ^ a * _ = g ^ a * 0
    rw [mul_zero, ← hr₁, ← germ_res h₅₁ z hz₅, ← map_mul, mul_sub, e, sub_self, map_zero]
  -- hence `f = τ(t₄)` near `z`
  have hloc : ∀ j, ∃ W : Opens Y, ∃ hW : W ≤ W₅, z ∈ W ∧
      Y.res hW (Y.res hW₅V (f j)) = D.τ j W (hW.trans hW₅U) (sectRes M (hW.trans hW₅₄) t₄) := by
    intro j
    obtain ⟨W, hzW, iU, iV, e⟩ :=
      Y.presheaf.germ_eq z hz₅ hz₅ _ 0 ((hj j).trans (map_zero _).symm)
    refine ⟨W, leOfHom iU, hzW, ?_⟩
    have e' : Y.res (leOfHom iU) (Y.res hW₅V (f j)) =
        Y.res (leOfHom iU) (D.τ j W₅ hW₅U (sectRes M hW₅₄ t₄)) :=
      sub_eq_zero.1 ((map_sub _ _ _).symm.trans (e.trans (map_zero _)))
    exact e'.trans ((D.τ_res j W₅ hW₅U W _ (leOfHom iU) _).symm.trans
      (congrArg _ (sectRes_sectRes M _ _ _)))
  choose W hW hzW hWf using hloc
  obtain ⟨W₆, hz₆, h₆₅, h₆⟩ := exists_opens_le_forall hz₅ W hzW
  have hW₆V : W₆ ≤ V := h₆₅.trans hW₅V
  refine ⟨W₆, hW₆V, hz₆, sectRes M (h₆₅.trans hW₅₄) t₄, ?_⟩
  have hU' : W₆ ⊓ O ≤ U := (inf_le_left.trans hW₆V).trans hV
  refine D.ext hU' fun j ↦ ?_
  have hle : W₆ ⊓ O ≤ W j := inf_le_left.trans (h₆ j)
  calc D.τ j _ hU' (sectRes M inf_le_left (sectRes M (h₆₅.trans hW₅₄) t₄))
      = D.τ j _ hU' (sectRes M hle (sectRes M ((hW j).trans hW₅₄) t₄)) :=
        congrArg _ (by rw [sectRes_sectRes, sectRes_sectRes])
    _ = Y.res hle (D.τ j (W j) (((hW j).trans hW₅V).trans hV) (sectRes M ((hW j).trans hW₅₄) t₄)) :=
        D.τ_res _ _ _ _ _ _ _
    _ = Y.res hle (Y.res (hW j) (Y.res hW₅V (f j))) := congrArg _ (hWf j).symm
    _ = Y.res (inf_le_inf_right O hW₆V) (Y.res inf_le_left (f j)) := by simp only [res_res]
    _ = Y.res (inf_le_inf_right O hW₆V) (D.τ j (V ⊓ O) (inf_le_left.trans hV) s) :=
        congrArg _ (hf j)
    _ = D.τ j _ hU' (sectRes M (inf_le_inf_right O hW₆V) s) := (D.τ_res _ _ _ _ _ _ _).symm

end Local

end AlgebraicGeometry.LocallyRingedSpace

/-! ### Hartogs extension on analytic spaces -/

namespace ComplexAnalytic.AnalyticSpace

open LocallyRingedSpace

variable {X : AnalyticSpace.{u}} {M : SheafOfModules.{u} X.ringSheaf}

/-- **The Rückert Nullstellensatz along `T`**: if `g` vanishes on `T` and sections `φ_l` near `z`
have no common zero off `T` (their germs generate the unit ideal there), then a power of the germ
of `g` at `z` lies in the ideal generated by the germs of the `φ_l`. -/
lemma exists_pow_germ_mem_span {T : Set X} {U : X.Opens} (g : X.presheaf.obj (op U))
    (hg : ∀ y (hy : y ∈ U), y ∈ T → X.eval y hy g = 0) {z : X} (hzU : z ∈ U)
    (W : X.Opens) (hzW : z ∈ W) {K : ℕ} (φ : Fin K → X.presheaf.obj (op W))
    (hφ : ∀ y (hy : y ∈ W), y ∉ T →
      Ideal.span (Set.range fun l ↦ X.presheaf.germ W y hy (φ l)) = ⊤) :
    ∃ N : ℕ, X.presheaf.germ U z hzU g ^ N ∈
      Ideal.span (Set.range fun l ↦ X.presheaf.germ W z hzW (φ l)) := by
  have hev : ∀ᶠ y in 𝓝 z, ∀ hy : y ∈ W ⊓ U,
      (∀ l, X.eval y hy (X.res inf_le_left (φ l)) = 0) →
        X.eval y hy (X.res inf_le_right g) = 0 := by
    refine Eventually.of_forall fun y hy hall ↦ ?_
    rw [eval_res]
    by_cases hyT : y ∈ T
    · exact hg y hy.2 hyT
    · refine absurd (hφ y hy.1 hyT) fun htop ↦
        (IsLocalRing.maximalIdeal.isMaximal (X.presheaf.stalk y)).ne_top ?_
      rw [eq_top_iff, ← htop, Ideal.span_le]
      rintro _ ⟨l, rfl⟩
      exact (eval_eq_zero_iff X).1 ((eval_res _ _ _).symm.trans (hall l))
  obtain ⟨N, hN⟩ := X.isNullstellensatzAt z (W ⊓ U) ⟨hzW, hzU⟩
    (fun l ↦ X.res inf_le_left (φ l)) (X.res inf_le_right g) hev
  refine ⟨N, ?_⟩
  have h1 : X.presheaf.germ (W ⊓ U) z ⟨hzW, hzU⟩ (X.res inf_le_right g) =
      X.presheaf.germ U z hzU g := TopCat.Presheaf.germ_res_apply _ _ _ _ _
  have h2 : (fun l ↦ X.presheaf.germ (W ⊓ U) z ⟨hzW, hzU⟩ (X.res inf_le_left (φ l))) =
      fun l ↦ X.presheaf.germ W z hzW (φ l) :=
    funext fun l ↦ TopCat.Presheaf.germ_res_apply _ _ _ _ _
  rw [h1, h2] at hN
  exact hN

/-- **Hartogs extension for coherent submodules of free modules.** Let `M` be coherent with
separating functionals on `U` (an embedding `M|_U ↪ 𝒪_U^m`), `T ⊆ U` with open complement `O`,
and `g, h ∈ 𝒪(U)` vanishing on `T`. Suppose that restriction `𝒪(V) → 𝒪(V ∩ O)` is surjective
for every open `V ⊆ U`, and that at every `z ∈ T` the germ of `g` is a nonzerodivisor on
`𝒪_{X,z}` and `[g, h]` is weakly regular on `M_z`. Then restriction `M(V) → M(V ∩ O)` is
bijective for every open `V`. -/
theorem bijective_restrict_of_separatingFunctionals [M.IsCoherent] {U : X.Opens}
    (D : SeparatingFunctionals M U) {T : Set X} (hTU : T ⊆ U) (O : X.Opens)
    (hO : (O : Set X) = Tᶜ) (g h : X.presheaf.obj (op U))
    (hg : ∀ y (hy : y ∈ U), y ∈ T → X.eval y hy g = 0)
    (hh : ∀ y (hy : y ∈ U), y ∈ T → X.eval y hy h = 0)
    (hg𝒪 : ∀ z (hz : z ∈ T), IsSMulRegular (X.presheaf.stalk z) (X.presheaf.germ U z (hTU hz) g))
    (hreg : ∀ z (hz : z ∈ T), IsWeaklyRegular ((X.stalkFunctor z).obj M)
      [X.presheaf.germ U z (hTU hz) g, X.presheaf.germ U z (hTU hz) h])
    (h𝒪 : ∀ V : X.Opens, V ≤ U → Function.Surjective (X.res (inf_le_left : V ⊓ O ≤ V)))
    (V : X.Opens) :
    Function.Bijective fun t : M.val.obj (op V) ↦ modRes t (V ⊓ O) inf_le_left := by
  refine bijective_restrict_of_forall_exists_extend' O hO
    (fun z hz ↦ ⟨U, hTU hz, g, hg, ((isWeaklyRegular_cons_iff _ _ _).1 (hreg z hz)).1⟩)
    (fun V s z hzV hzT ↦ ?_) V
  -- work inside `V ⊓ U`
  set V' := V ⊓ U
  have hV' : V' ≤ U := inf_le_right
  have hzV' : z ∈ V' := ⟨hzV, hTU hzT⟩
  let s' : M.val.obj (op (V' ⊓ O)) := sectRes M (inf_le_inf_right O inf_le_left) s
  choose f hf using fun j ↦ h𝒪 V' hV' (D.τ j (V' ⊓ O) (inf_le_left.trans hV') s')
  obtain ⟨a, ha⟩ := exists_pow_mem_conductor D O hO hV' s' f hf (hasLocalTupleRelations_unit X)
    hzV' _ fun W hzW {_} φ hφ ↦ exists_pow_germ_mem_span g hg (hTU hzT) W hzW φ hφ
  obtain ⟨b, hb⟩ := exists_pow_mem_conductor D O hO hV' s' f hf (hasLocalTupleRelations_unit X)
    hzV' _ fun W hzW {_} φ hφ ↦ exists_pow_germ_mem_span h hh (hTU hzT) W hzW φ hφ
  obtain ⟨W, hWV', hzW, t, ht⟩ :=
    exists_extend_of_mem_conductor D O hV' s' f hf hzV' (hg𝒪 z hzT) (hreg z hzT) ha hb
  refine ⟨W, hWV'.trans inf_le_left, hzW, t, ht.trans ?_⟩
  exact sectRes_sectRes M _ _ _

end ComplexAnalytic.AnalyticSpace
