/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.Geometry.RingedSpace.LocallyRingedSpace.CoherentModuleSections

/-!
# Local relations between tuples of sections

Let `M` be a sheaf of `𝒪_Y`-modules on a locally ringed space `Y` with locally finitely
generated relations (`AlgebraicGeometry.LocallyRingedSpace.HasLocalModuleRelations`). Then the
relations between finitely many `m`-tuples of sections of `M`, i.e. the relations holding in
every component simultaneously, are locally finitely generated as well
(`AlgebraicGeometry.LocallyRingedSpace.HasLocalModuleRelations.hasLocalTupleRelations`); the
proof is an induction on `m`.

This gives a criterion for local relations of a family of sections `t₁, …, t_k` of a second
sheaf `N`: if the relations of the `tᵢ` are, locally, exactly the projections to the first `k`
coordinates of the relations of a family of `k + L` tuples of sections of `M`, then the `tᵢ` have
locally finitely generated relations
(`AlgebraicGeometry.LocallyRingedSpace.exists_localRelations_of_tuple`).
-/

open CategoryTheory TopologicalSpace Opposite

universe u

noncomputable section

namespace AlgebraicGeometry.LocallyRingedSpace

variable {Y : LocallyRingedSpace.{u}} (M : SheafOfModules.{u} Y.ringSheaf)

/-- `M` has **locally finitely generated tuple relations**: for every finite family of
`m`-tuples of sections of `M`, the relations holding in all components are locally generated by
finitely many of them. -/
def HasLocalTupleRelations : Prop :=
  ∀ (V : Opens Y) (q m : ℕ) (v : Fin q → Fin m → M.val.obj (op V)) (x : Y), x ∈ V →
    ∃ (W : Opens Y) (hWV : W ≤ V) (k : ℕ) (g : Fin k → Fin q → Y.presheaf.obj (op W)),
      x ∈ W ∧ (∀ l j, ∑ i, g l i • sectRes M hWV (v i j) = 0) ∧
      ∀ (W' : Opens Y) (hW' : W' ≤ W) (a : Fin q → Y.presheaf.obj (op W')),
        (∀ j, ∑ i, a i • sectRes M (hW'.trans hWV) (v i j) = 0) → ∀ y ∈ W',
          ∃ (W'' : Opens Y) (hW'' : W'' ≤ W'), y ∈ W'' ∧
            ∃ c : Fin k → Y.presheaf.obj (op W''),
              ∀ i, Y.res hW'' (a i) = ∑ l, c l * Y.res (hW''.trans hW') (g l i)

variable {M}

lemma sectRes_sum_smul {U V : Opens Y} (h : U ≤ V) {q : ℕ} (a : Fin q → Y.presheaf.obj (op V))
    (s : Fin q → M.val.obj (op V)) :
    sectRes M h (∑ i, a i • s i) = ∑ i, Y.res h (a i) • sectRes M h (s i) := by
  rw [sectRes_sum]
  exact Finset.sum_congr rfl fun i _ ↦ sectRes_smul M h _ _

/-- **Tuple relations from relations**, by induction on the length of the tuples. -/
theorem HasLocalModuleRelations.hasLocalTupleRelations (hM : HasLocalModuleRelations M) :
    HasLocalTupleRelations M := by
  classical
  intro V q m
  induction m generalizing V q with
  | zero =>
    intro v x hx
    refine ⟨V, le_rfl, q, fun l i ↦ if l = i then 1 else 0, hx, fun l j ↦ j.elim0,
      fun W' hW' a _ y hy ↦ ⟨W', le_rfl, hy, a, fun i ↦ ?_⟩⟩
    dsimp only
    rw [Finset.sum_eq_single i (fun b _ hb ↦ by rw [if_neg hb, res_zero, mul_zero])
      (by simp), if_pos rfl, res_self]
    exact (mul_one _).symm.trans (congrArg _ (map_one _).symm)
  | succ m ih =>
    intro v x hx
    obtain ⟨W₁, h₁, k₁, r, hx₁, hr, hrgen⟩ := hM V q (fun i ↦ v i 0) x hx
    let w : Fin k₁ → Fin m → M.val.obj (op W₁) := fun σ j ↦
      ∑ i, r σ i • sectRes M h₁ (v i j.succ)
    obtain ⟨W, h, k, ρ, hxW, hρ, hρgen⟩ := ih W₁ k₁ w x hx₁
    refine ⟨W, h.trans h₁, k, fun l i ↦ ∑ σ, ρ l σ * Y.res h (r σ i), hxW, fun l j ↦ ?_,
      fun W' hW' a ha y hy ↦ ?_⟩
    · have e : ∑ i, (∑ σ, ρ l σ * Y.res h (r σ i)) • sectRes M (h.trans h₁) (v i j) =
          ∑ σ, ρ l σ • sectRes M h (∑ i, r σ i • sectRes M h₁ (v i j)) := by
        simp only [Finset.sum_smul, sectRes_sum_smul, sectRes_sectRes, Finset.smul_sum,
          mul_smul]
        exact Finset.sum_comm
      rw [e]
      induction j using Fin.cases with
      | zero => simp only [hr, sectRes_zero, smul_zero, Finset.sum_const_zero]
      | succ j => exact hρ l j
    · -- the first component
      have ha0 : ∑ i, a i • sectRes M (hW'.trans (h.trans h₁)) (v i 0) = 0 := ha 0
      obtain ⟨W₂, h₂, hy₂, c₁, hc₁⟩ := hrgen W' (hW'.trans h) a ha0 y hy
      -- `c₁` is a relation of `w`
      have hc₁rel : ∀ j, ∑ σ, c₁ σ • sectRes M (h₂.trans (hW'.trans h)) (w σ j) = 0 := by
        intro j
        have e : ∑ σ, c₁ σ • sectRes M (h₂.trans (hW'.trans h)) (w σ j) =
            sectRes M h₂ (∑ i, a i • sectRes M (hW'.trans (h.trans h₁)) (v i j.succ)) := by
          simp only [w, sectRes_sum_smul, sectRes_sectRes, Finset.smul_sum, hc₁,
            Finset.sum_smul, mul_smul]
          exact Finset.sum_comm
        rw [e, ha j.succ, sectRes_zero]
      obtain ⟨W₃, h₃, hy₃, c₂, hc₂⟩ := hρgen W₂ (h₂.trans hW') c₁ hc₁rel y hy₂
      refine ⟨W₃, h₃.trans h₂, hy₃, c₂, fun i ↦ ?_⟩
      rw [← res_res _ h₃ h₂, hc₁, res_sum]
      simp only [res_mul, res_res, hc₂, Finset.sum_mul, res_sum, Finset.mul_sum, mul_assoc]
      exact Finset.sum_comm

/-- **Relations from tuple relations**: if, near `x`, the relations of `t₁, …, t_k` are the
projections of the relations of a family of `k + L` tuples of sections of `M`, then the `tᵢ`
have locally finitely generated relations near `x`. -/
theorem exists_localRelations_of_tuple (hM : HasLocalTupleRelations M)
    (N : SheafOfModules.{u} Y.ringSheaf) {V : Opens Y} {k : ℕ} (t : Fin k → N.val.obj (op V))
    {x : Y} {W₀ : Opens Y} (hW₀ : W₀ ≤ V) (hx : x ∈ W₀) {L m : ℕ}
    (v : Fin (k + L) → Fin m → M.val.obj (op W₀))
    (hsound : ∀ (W' : Opens Y) (h : W' ≤ W₀) (b : Fin (k + L) → Y.presheaf.obj (op W')),
      (∀ j, ∑ i, b i • sectRes M h (v i j) = 0) →
        ∑ i, b (Fin.castAdd L i) • sectRes N (h.trans hW₀) (t i) = 0)
    (hcompl : ∀ (W' : Opens Y) (h : W' ≤ W₀) (a : Fin k → Y.presheaf.obj (op W')),
      ∑ i, a i • sectRes N (h.trans hW₀) (t i) = 0 → ∀ y ∈ W',
        ∃ (W'' : Opens Y) (h'' : W'' ≤ W'), y ∈ W'' ∧ ∃ c : Fin L → Y.presheaf.obj (op W''),
          ∀ j, ∑ i, Fin.append (fun i ↦ Y.res h'' (a i)) c i • sectRes M (h''.trans h) (v i j)
            = 0) :
    ∃ (W : Opens Y) (hWV : W ≤ V) (n : ℕ) (g : Fin n → (Fin k → Y.presheaf.obj (op W))),
      x ∈ W ∧ (∀ l, ∑ i, g l i • sectRes N hWV (t i) = 0) ∧
      ∀ (W' : Opens Y) (hW' : W' ≤ W) (a : Fin k → Y.presheaf.obj (op W')),
        (∑ i, a i • sectRes N (hW'.trans hWV) (t i) = 0) → ∀ y ∈ W',
          ∃ (W'' : Opens Y) (hW'' : W'' ≤ W'), y ∈ W'' ∧
            ∃ c : Fin n → Y.presheaf.obj (op W''),
              ∀ i, Y.res hW'' (a i) = ∑ l, c l * Y.res (hW''.trans hW') (g l i) := by
  obtain ⟨W, hW, n, G, hxW, hG, hGgen⟩ := hM W₀ (k + L) m v x hx
  refine ⟨W, hW.trans hW₀, n, fun l i ↦ G l (Fin.castAdd L i), hxW,
    fun l ↦ hsound W hW (G l) (hG l), fun W' hW' a ha y hy ↦ ?_⟩
  obtain ⟨W'', h'', hy'', c, hc⟩ := hcompl W' (hW'.trans hW) a ha y hy
  obtain ⟨W₃, h₃, hy₃, d, hd⟩ := hGgen W'' (h''.trans hW') _ hc y hy''
  refine ⟨W₃, h₃.trans h'', hy₃, d, fun i ↦ ?_⟩
  have := hd (Fin.castAdd L i)
  rw [Fin.append_left, res_res] at this
  rw [this]

end AlgebraicGeometry.LocallyRingedSpace
