/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.AnalyticSpace.NoetherGerm
import Oka.Analytification.GAGA.CartanTheoremA

/-!
# The Noether property of coherent sheaves

Let `f : Y ⟶ ℂ^ι` be an open immersion of locally ringed spaces such that `𝒪_Y` has locally
finitely generated relations (e.g. `Y` an open subset of `ℂⁿ`), and let `φₖ : Fₖ ⟶ 𝒪_Y^b`,
`k ∈ ℕ`, be morphisms from coherent sheaves whose images form an increasing chain of subsheaves
of `𝒪_Y^b`. Then the chain is locally stationary: every point has an open neighbourhood `V` and
an index `k₀` such that on `V` the images of all `φₖ`, `k ≥ k₀`, agree with the image of `φₖ₀`
(`ComplexAnalytic.exists_locallyInRange_stationary`).

Images are encoded by `ComplexAnalytic.LocallyInRange φ s`: the section `s` of `𝒪_Y^b` lies
locally in the image of `φ`.

The proof reduces to `OkaRing.exists_forall_ge_eq_of_monotone`. Near a closed box `K` about the
given point, each `Fₖ` is generated by finitely many sections (Cartan's Theorem A,
`ComplexAnalytic.exists_sections_closedBox`); their images under `φₖ` form a matrix of holomorphic
functions on a fixed open ball inside `K`, whose columns generate the stalks of the image of `φₖ`
at every point of the ball.

## Main definitions

- `ComplexAnalytic.LocallyInRange`: a section lies locally in the image of a morphism.
- `ComplexAnalytic.freeOka`: the coordinates of a section of `𝒪_Y^b`, as holomorphic functions.

## Main results

- `ComplexAnalytic.exists_locallyInRange_stationary`: **the Noether property** near a point of
  `Y`.
- `ComplexAnalytic.exists_locallyInRange_stationary_complexAffineSpace`: the same for coherent
  sheaves on an open subset of `ℂⁿ`.
-/

universe u

open CategoryTheory TopologicalSpace Opposite AlgebraicGeometry Set Metric
open AlgebraicGeometry.LocallyRingedSpace
open scoped Matrix

namespace ComplexAnalytic

section Range

variable {Y : LocallyRingedSpace.{u}} {F M : SheafOfModules.{u} Y.ringSheaf}

/-- The section `s` of `M` over `W` lies locally in the image of `φ : F ⟶ M`: every point of `W`
has an open neighbourhood `W' ≤ W` on which `s` is the image of a section of `F`. -/
def LocallyInRange (φ : F ⟶ M) {W : Opens Y.toPresheafedSpace} (s : M.val.obj (op W)) : Prop :=
  ∀ y ∈ W, ∃ (W' : Opens Y.toPresheafedSpace) (h : W' ≤ W), y ∈ W' ∧
    ∃ t : F.val.obj (op W'), φ.val.app (op W') t = modRes s W' h

/-- Images of sections lie in the image. -/
lemma locallyInRange_app (φ : F ⟶ M) {W : Opens Y.toPresheafedSpace} (t : F.val.obj (op W)) :
    LocallyInRange φ (φ.val.app (op W) t) :=
  fun _ hy ↦ ⟨W, le_rfl, hy, t, (modRes_self _).symm⟩

/-- Morphisms of sheaves of modules commute with restriction. -/
lemma app_modRes (φ : F ⟶ M) {W W' : Opens Y.toPresheafedSpace} (h : W' ≤ W)
    (t : F.val.obj (op W)) :
    φ.val.app (op W') (modRes t W' h) = modRes (φ.val.app (op W) t) W' h :=
  PresheafOfModules.naturality_apply φ.val (homOfLE h).op t

end Range

section Free

variable {ι : Type u} [Fintype ι] {Y : LocallyRingedSpace.{u}} (f : Y ⟶ complexSpace ι)
  [LocallyRingedSpace.IsOpenImmersion f] {b : Type u} [DecidableEq b]

/-- The coordinates of a section of `𝒪_Y^b` over `W`, as holomorphic functions on `f(W)`. -/
noncomputable def freeOka {W : Opens Y.toPresheafedSpace}
    (s : (SheafOfModules.free (R := Y.ringSheaf) b).val.obj (op W)) :
    b → OkaRing (imageOpens f W) :=
  fun i ↦ secOka f (SheafOfModules.freeEval (op W) s i)

variable {f} {W W' : Opens Y.toPresheafedSpace}

/-- The values of `freeOka` are the values of the coordinates. -/
lemma evalHom_freeOka {x : ι → ℂ} (hx : x ∈ imageOpens f W)
    (s : (SheafOfModules.free (R := Y.ringSheaf) b).val.obj (op W)) (i : b) :
    OkaRing.evalHom hx (freeOka f s i) = secEval f hx (SheafOfModules.freeEval (op W) s i) :=
  rfl

/-- `freeOka` commutes with restriction. -/
lemma evalHom_freeOka_modRes (h : W' ≤ W) {x : ι → ℂ} (hx : x ∈ imageOpens f W')
    (s : (SheafOfModules.free (R := Y.ringSheaf) b).val.obj (op W)) (i : b) :
    OkaRing.evalHom hx (freeOka f (modRes s W' h) i) =
      OkaRing.evalHom (mem_imageOpens_of_le h hx) (freeOka f s i) := by
  rw [evalHom_freeOka, evalHom_freeOka, modRes, SheafOfModules.freeEval_naturality]
  exact secEval_map h hx _

/-- The values of `freeOka` of a linear combination of sections. -/
lemma evalHom_freeOka_sum_smul {κ : Type*} [Fintype κ] {x : ι → ℂ} (hx : x ∈ imageOpens f W)
    (c : κ → Y.presheaf.obj (op W))
    (s : κ → (SheafOfModules.free (R := Y.ringSheaf) b).val.obj (op W)) (i : b) :
    OkaRing.evalHom hx (freeOka f (∑ j, c j • s j) i) =
      ∑ j, secEval f hx (c j) * OkaRing.evalHom hx (freeOka f (s j) i) := by
  let ev : Y.ringSheaf.obj.obj (op W) →+* ℂ := secEval f hx
  rw [evalHom_freeOka]
  change ev _ = ∑ j, ev (c j) * ev _
  rw [map_sum, Finset.sum_apply, map_sum]
  refine Finset.sum_congr rfl fun j _ ↦ ?_
  have h := (SheafOfModules.freeEval (R := Y.ringSheaf) (I := b) (op W)).map_smul (c j) (s j)
  exact (congrArg (fun v ↦ ev (v i)) h).trans (map_mul ev (c j) _)

/-- Sections of `𝒪_Y^b` are determined by the values of their coordinates. -/
lemma free_ext [Finite b] {s s' : (SheafOfModules.free (R := Y.ringSheaf) b).val.obj (op W)}
    (h : ∀ i (x : ι → ℂ) (hx : x ∈ imageOpens f W),
      OkaRing.evalHom hx (freeOka f s i) = OkaRing.evalHom hx (freeOka f s' i)) : s = s' :=
  SheafOfModules.freeEval_injective (op W) (funext fun i ↦ sec_ext fun x hx ↦ h i x hx)

/-- A point whose image lies in `f(W)` lies in `W`. -/
lemma mem_of_mem_imageOpens {y : Y} (h : f.base y ∈ imageOpens f W) : y ∈ W := by
  obtain ⟨z, hz, hzy⟩ := h
  rwa [← (isOpenEmbedding_base (f := f)).injective hzy]

end Free

section Generators

variable {ι : Type u} [Fintype ι] {Y : LocallyRingedSpace.{u}} (f : Y ⟶ complexSpace ι)
  [LocallyRingedSpace.IsOpenImmersion f] {b : Type u} [DecidableEq b]
  {F : SheafOfModules.{u} Y.ringSheaf} (φ : F ⟶ SheafOfModules.free b)
  {W₀ : Opens Y.toPresheafedSpace} {I : Type u} (g : I → F.val.obj (op W₀))
  {O : Opens (ι → ℂ)} (hO : O ≤ imageOpens f W₀)

/-- The images under `φ` of the sections `g` over `W₀`, as a matrix of holomorphic functions on
`O ⊆ f(W₀)`. -/
noncomputable def genMatrix : Matrix b I (OkaRing O) :=
  fun i j ↦ OkaRing.restrict hO (freeOka f (φ.val.app (op W₀) (g j)) i)

variable {g}

/-- If the sections `g` generate `F` locally on `W₀`, the germ of every section of `𝒪_Y^b` lying
locally in the image of `φ` lies in the span of the germs of the columns of `genMatrix`, at
every point of `O`. -/
theorem germVec_freeOka_mem_span [Fintype I] (hg : GeneratesLocally g)
    {W : Opens Y.toPresheafedSpace}
    {s : (SheafOfModules.free (R := Y.ringSheaf) b).val.obj (op W)} (hs : LocallyInRange φ s)
    {y : ι → ℂ} (hy : y ∈ imageOpens f W) (hyO : y ∈ O) :
    OkaRing.germVec hy (freeOka f s) ∈ Submodule.span (LocalOkaRing ι)
      (range fun j ↦ OkaRing.germVec hyO fun i ↦ genMatrix f φ g hO i j) := by
  obtain ⟨y', hy'W, hyy⟩ := id hy
  have hy'W₀ : y' ∈ W₀ := mem_of_mem_imageOpens (f := f) (hyy ▸ hO hyO)
  obtain ⟨W₁, h₁, hy'₁, t, ht⟩ := hs y' hy'W
  obtain ⟨W₃, h₃, hy'₃, c, hc⟩ :=
    hg (W₁ ⊓ W₀) inf_le_right (modRes t _ inf_le_left) y' ⟨hy'₁, hy'W₀⟩
  have h₃₁ : W₃ ≤ W := h₃.trans (inf_le_left.trans h₁)
  have e : modRes s W₃ h₃₁ =
      ∑ j, c j • modRes (φ.val.app _ (g j)) W₃ (h₃.trans inf_le_right) := by
    rw [← modRes_res h₁ (h₃.trans inf_le_left), ← ht, ← app_modRes, ← modRes_res inf_le_left h₃,
      hc, map_sum]
    refine Finset.sum_congr rfl fun j _ ↦ ?_
    rw [map_smul, app_modRes]
  let V : Opens (ι → ℂ) := imageOpens f W₃ ⊓ O
  have hV₃ : V ≤ imageOpens f W₃ := inf_le_left
  have hVO : V ≤ O := inf_le_right
  have hyV : y ∈ V := ⟨⟨y', hy'₃, hyy⟩, hyO⟩
  let c' : I → OkaRing V := fun j ↦ OkaRing.restrict hV₃ (secOka f (c j))
  have heq : OkaRing.germVec hy (freeOka f s) =
      OkaRing.germVec hyV ((genMatrix f φ g hO).map (OkaRing.restrict hVO) *ᵥ c') := by
    refine OkaRing.germVec_eq_of_evalHom_eq (V'' := V)
      (fun x hx ↦ mem_imageOpens_of_le h₃₁ (hV₃ hx)) le_rfl hyV _ _ fun i x hx ↦ ?_
    have := evalHom_freeOka_modRes h₃₁ (hV₃ hx) s i
    rw [e, evalHom_freeOka_sum_smul] at this
    rw [← this]
    simp only [Matrix.mulVec, dotProduct, Matrix.map_apply, map_sum, map_mul,
      OkaRing.evalHom_restrict, genMatrix, c']
    refine Finset.sum_congr rfl fun j _ ↦ ?_
    rw [mul_comm, evalHom_freeOka_modRes]
    rfl
  rw [heq]
  exact OkaRing.germVec_restrict_mulVec_mem_span hVO _ c' hyV

/-- Conversely, a section of `𝒪_Y^b` whose germ at a point of `O` lies in the span of the germs
of the columns of `genMatrix` is the image of a section of `F` near that point. -/
theorem exists_app_eq_modRes_of_germVec_mem_span [Finite b] [Finite I]
    {W : Opens Y.toPresheafedSpace}
    (s : (SheafOfModules.free (R := Y.ringSheaf) b).val.obj (op W)) {y' : Y} (hy' : y' ∈ W)
    (hyO : f.base y' ∈ O) (hy : f.base y' ∈ imageOpens f W)
    (hmem : OkaRing.germVec hy (freeOka f s) ∈ Submodule.span (LocalOkaRing ι)
      (range fun j ↦ OkaRing.germVec hyO fun i ↦ genMatrix f φ g hO i j)) :
    ∃ (W₃ : Opens Y.toPresheafedSpace) (h : W₃ ≤ W), y' ∈ W₃ ∧
      ∃ t : F.val.obj (op W₃), φ.val.app (op W₃) t = modRes s W₃ h := by
  have := Fintype.ofFinite I
  have hy'W₀ : y' ∈ W₀ := mem_of_mem_imageOpens (f := f) (hO hyO)
  let V : Opens (ι → ℂ) := imageOpens f W ⊓ O
  have hVW : V ≤ imageOpens f W := inf_le_left
  have hVO : V ≤ O := inf_le_right
  have hyV : f.base y' ∈ V := ⟨hy, hyO⟩
  let A' := (genMatrix f φ g hO).map (OkaRing.restrict hVO)
  let f' : b → OkaRing V := fun i ↦ OkaRing.restrict hVW (freeOka f s i)
  have hmem' : OkaRing.germVec hyV f' ∈ Submodule.span (LocalOkaRing ι)
      (range fun j ↦ OkaRing.germVec hyV fun i ↦ A' i j) := by
    have h1 : OkaRing.germVec hyV f' = OkaRing.germVec hy (freeOka f s) :=
      OkaRing.germVec_eq_of_evalHom_eq le_rfl hVW hyV _ _ fun _ _ _ ↦ rfl
    have h2 : ∀ j, OkaRing.germVec hyV (fun i ↦ A' i j) =
        OkaRing.germVec hyO fun i ↦ genMatrix f φ g hO i j := fun j ↦
      OkaRing.germVec_eq_of_evalHom_eq le_rfl hVO hyV _ _ fun _ _ _ ↦ rfl
    simp_rw [h1, h2]
    exact hmem
  obtain ⟨V₀, h₀, hy₀, c, hc⟩ := OkaRing.exists_restrict_eq_mulVec A' f' hyV hmem'
  let W₃ : Opens Y.toPresheafedSpace := W ⊓ W₀ ⊓ (Opens.map f.base).obj V₀
  have hW₃W : W₃ ≤ W := inf_le_left.trans inf_le_left
  have hW₃W₀ : W₃ ≤ W₀ := inf_le_left.trans inf_le_right
  have himg : ∀ x ∈ imageOpens f W₃, x ∈ V₀ := by
    rintro x ⟨z, hz, rfl⟩
    exact hz.2
  choose c'' hc'' using fun j ↦ exists_secEval_eq (f := f) (W := W₃)
    (OkaRing.toGlobalFun _ (c j)) ((c j).differentiableOn_toGlobalFun.mono himg)
  refine ⟨W₃, hW₃W, ⟨⟨hy', hy'W₀⟩, hy₀⟩, ∑ j, c'' j • modRes (g j) W₃ hW₃W₀,
    free_ext (f := f) fun i x hx ↦ ?_⟩
  have e : φ.val.app (op W₃) (∑ j, c'' j • modRes (g j) W₃ hW₃W₀) =
      ∑ j, c'' j • modRes (φ.val.app _ (g j)) W₃ hW₃W₀ := by
    rw [map_sum]
    refine Finset.sum_congr rfl fun j _ ↦ ?_
    rw [map_smul, app_modRes]
  have hxV₀ := himg x hx
  have := congrArg (OkaRing.evalHom hxV₀) (hc i)
  simp only [map_sum, map_mul, OkaRing.evalHom_restrict, f', A', Matrix.map_apply,
    genMatrix] at this
  rw [e, evalHom_freeOka_sum_smul, evalHom_freeOka_modRes, this]
  refine Finset.sum_congr rfl fun j _ ↦ ?_
  rw [hc'' j x hx, OkaRing.toGlobalFun_apply _ hxV₀, evalHom_freeOka_modRes]
  rfl

end Generators

section Box

variable {ι : Type u} [Fintype ι]

/-- The closed box of half side `δ` about `p` contains the open ball of radius `δ`. -/
lemma ball_subset_closedBox (p : ι → ℂ) (δ : ℝ) :
    ball p δ ⊆ Complex.closedBox (p - fun _ ↦ ⟨δ, δ⟩) (p + fun _ ↦ ⟨δ, δ⟩) := by
  intro x hx
  rw [mem_ball] at hx
  rw [dist_pi_lt_iff (dist_nonneg.trans_lt hx)] at hx
  intro j _
  have h := hx j
  rw [dist_eq_norm] at h
  have hre := (abs_le.1 ((Complex.abs_re_le_norm _).trans h.le))
  have him := (abs_le.1 ((Complex.abs_im_le_norm _).trans h.le))
  simp only [Complex.sub_re, Complex.sub_im] at hre him
  refine Complex.mem_reProdIm.2 ⟨⟨?_, ?_⟩, ?_, ?_⟩ <;> simp <;> linarith

/-- The closed box of half side `δ ≥ 0` about `p` lies in the closed ball of radius `2δ`. -/
lemma closedBox_subset_closedBall (p : ι → ℂ) {δ : ℝ} (hδ : 0 ≤ δ) :
    Complex.closedBox (p - fun _ ↦ ⟨δ, δ⟩) (p + fun _ ↦ ⟨δ, δ⟩) ⊆ closedBall p (2 * δ) := by
  intro x hx
  rw [mem_closedBall, dist_pi_le_iff (by linarith)]
  intro j
  obtain ⟨⟨h1, h2⟩, h3, h4⟩ := Complex.mem_reProdIm.1 (hx j (mem_univ j))
  simp only [Pi.sub_apply, Pi.add_apply, Complex.sub_re, Complex.add_re, Complex.sub_im,
    Complex.add_im] at h1 h2 h3 h4
  rw [dist_eq_norm]
  refine (Complex.norm_le_abs_re_add_abs_im _).trans ?_
  simp only [Complex.sub_re, Complex.sub_im]
  rw [two_mul]
  exact add_le_add (abs_le.2 ⟨by linarith, by linarith⟩) (abs_le.2 ⟨by linarith, by linarith⟩)

end Box

section Main

variable {Y : LocallyRingedSpace.{u}} {b : Type u}

/-- An increasing chain of images: `Im φₖ ⊆ Im φₖ'` for `k ≤ k'`. -/
lemma LocallyInRange.of_le {F : ℕ → SheafOfModules.{u} Y.ringSheaf}
    {φ : ∀ k, F k ⟶ SheafOfModules.free b}
    (hφ : ∀ k (W : Opens Y.toPresheafedSpace)
      (s : (SheafOfModules.free (R := Y.ringSheaf) b).val.obj (op W)),
      LocallyInRange (φ k) s → LocallyInRange (φ (k + 1)) s)
    {k k' : ℕ} (hkk' : k ≤ k') {W : Opens Y.toPresheafedSpace}
    {s : (SheafOfModules.free (R := Y.ringSheaf) b).val.obj (op W)}
    (hs : LocallyInRange (φ k) s) : LocallyInRange (φ k') s := by
  induction hkk' with
  | refl => exact hs
  | step _ ih => exact hφ _ W s ih

/-- **The Noether property of coherent sheaves.** Let `f : Y ⟶ ℂ^ι` be an open immersion, where
`𝒪_Y` has locally finitely generated relations, and let `φₖ : Fₖ ⟶ 𝒪_Y^b` be morphisms from
coherent sheaves (with stalks of bounded projective dimension) whose images increase with `k`.
Then every point `y₀` of `Y` has an open neighbourhood `V` on which the chain of images is
stationary: there is `k₀` such that for `k ≥ k₀`, every section over an open `W ≤ V` lying locally
in the image of `φₖ` lies locally in the image of `φₖ₀`. -/
theorem exists_locallyInRange_stationary [Finite b] {ι : Type u} [Fintype ι]
    (f : Y ⟶ complexSpace ι) [LocallyRingedSpace.IsOpenImmersion f] (hY : Y.HasLocalRelations)
    {F : ℕ → SheafOfModules.{u} Y.ringSheaf} [∀ k, (F k).IsCoherent]
    (hpd : ∀ k, ∃ d : ℕ, ∀ y, HasProjectiveDimensionLE ((Y.stalkFunctor y).obj (F k)) d)
    (φ : ∀ k, F k ⟶ SheafOfModules.free b)
    (hφ : ∀ k (W : Opens Y.toPresheafedSpace)
      (s : (SheafOfModules.free (R := Y.ringSheaf) b).val.obj (op W)),
      LocallyInRange (φ k) s → LocallyInRange (φ (k + 1)) s) (y₀ : Y) :
    ∃ V : Opens Y.toPresheafedSpace, y₀ ∈ V ∧ ∃ k₀ : ℕ, ∀ k, k₀ ≤ k →
      ∀ (W : Opens Y.toPresheafedSpace), W ≤ V →
        ∀ s : (SheafOfModules.free (R := Y.ringSheaf) b).val.obj (op W),
          LocallyInRange (φ k) s → LocallyInRange (φ k₀) s := by
  classical
  set p : ι → ℂ := f.base y₀
  obtain ⟨ε, hε, hεr⟩ :=
    Metric.isOpen_iff.1 (isOpenEmbedding_base (f := f)).isOpen_range p (mem_range_self y₀)
  set δ := ε / 4
  have hδ : 0 < δ := by positivity
  have h2δ : 2 * δ < ε := by rw [show δ = ε / 4 from rfl]; linarith
  have hK : Complex.closedBox (p - fun _ ↦ ⟨δ, δ⟩) (p + fun _ ↦ ⟨δ, δ⟩) ⊆ range f.base :=
    (closedBox_subset_closedBall p hδ.le).trans
      ((closedBall_subset_ball h2δ).trans hεr)
  have hpO : p ∈ ball p δ := mem_ball_self hδ
  have hne : (Complex.closedBox (p - fun _ ↦ ⟨δ, δ⟩) (p + fun _ ↦ ⟨δ, δ⟩)).Nonempty :=
    ⟨p, ball_subset_closedBox p δ hpO⟩
  choose d hd using hpd
  choose W hKW I hI g hg _ using fun k ↦ exists_sections_closedBox f hY (F k) (hd k) hK hne
  let O : Opens (ι → ℂ) := ⟨ball p δ, isOpen_ball⟩
  have hO : ∀ k, O ≤ imageOpens f (W k) := fun k ↦ (ball_subset_closedBox p δ).trans (hKW k)
  let A : ∀ k, Matrix b (I k) (OkaRing O) := fun k ↦ genMatrix f (φ k) (g k) (hO k)
  let N : ℕ → (ι → ℂ) → Submodule (LocalOkaRing ι) (b → LocalOkaRing ι) := fun k y ↦
    if hy : y ∈ O then Submodule.span _ (range fun j ↦ OkaRing.germVec hy fun i ↦ A k i j) else ⊥
  have hNA : ∀ k (y : ι → ℂ) (hy : y ∈ O),
      N k y = Submodule.span _ (range fun j ↦ OkaRing.germVec hy fun i ↦ A k i j) :=
    fun k y hy ↦ dif_pos hy
  have hN : Monotone N := by
    intro k k' hkk' y
    by_cases hy : y ∈ O
    · rw [hNA k y hy, hNA k' y hy, Submodule.span_le]
      refine range_subset_iff.2 fun j ↦ ?_
      have h1 : OkaRing.germVec hy (fun i ↦ A k i j) =
          OkaRing.germVec (hO k hy) (freeOka f ((φ k).val.app _ (g k j))) :=
        OkaRing.germVec_eq_of_evalHom_eq le_rfl (hO k) hy _ _ fun _ _ _ ↦ rfl
      rw [h1]
      exact germVec_freeOka_mem_span f (φ k') (hO k') (hg k')
        (LocallyInRange.of_le hφ hkk' (locallyInRange_app _ _)) (hO k hy) hy
    · simp only [N, dif_neg hy, le_refl]
  obtain ⟨V, hpV, hVO, k₀, hk₀⟩ := OkaRing.exists_forall_ge_eq_of_monotone hpO N hN A hNA
  refine ⟨(Opens.map f.base).obj V, hpV, k₀, fun k hk W' hW' s hs y' hy' ↦ ?_⟩
  have hyV : f.base y' ∈ V := hW' hy'
  have hyO : f.base y' ∈ O := hVO hyV
  have hy : f.base y' ∈ imageOpens f W' := ⟨y', hy', rfl⟩
  have hmem := germVec_freeOka_mem_span f (φ k) (hO k) (hg k) hs hy hyO
  rw [← hNA k _ hyO, hk₀ k hk _ hyV, hNA k₀ _ hyO] at hmem
  exact exists_app_eq_modRes_of_germVec_mem_span f (φ k₀) (hO k₀) s hy' hyO hy hmem

end Main

section AffineSpace

variable {n : ℕ} (U : Opens (complexAffineSpace.{u} n)) {b : Type u} [Finite b]

/-- **The Noether property of coherent sheaves on an open subset `U ⊆ ℂⁿ`.** Let
`φₖ : Fₖ ⟶ 𝒪_U^b` be morphisms from coherent sheaves whose images increase with `k`. Then every
point of `U` has an open neighbourhood `V` on which the chain of images is stationary. -/
theorem exists_locallyInRange_stationary_complexAffineSpace
    {F : ℕ → SheafOfModules.{u} ((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).ringSheaf}
    [∀ k, (F k).IsCoherent] (φ : ∀ k, F k ⟶ SheafOfModules.free b)
    (hφ : ∀ k (W : Opens ((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).toPresheafedSpace)
      (s : (SheafOfModules.free
        (R := ((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).ringSheaf) b).val.obj (op W)),
      LocallyInRange (φ k) s → LocallyInRange (φ (k + 1)) s)
    (y₀ : (complexAffineSpace.{u} n).restrict U.isOpenEmbedding) :
    ∃ V : Opens ((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).toPresheafedSpace,
      y₀ ∈ V ∧ ∃ k₀ : ℕ, ∀ k, k₀ ≤ k →
      ∀ (W : Opens ((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).toPresheafedSpace),
        W ≤ V → ∀ s : (SheafOfModules.free
          (R := ((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).ringSheaf) b).val.obj
            (op W),
          LocallyInRange (φ k) s → LocallyInRange (φ k₀) s :=
  exists_locallyInRange_stationary ((complexAffineSpace.{u} n).ofRestrict U.isOpenEmbedding)
    ((hasLocalRelations_complexSpace _).restrict U)
    (fun k ↦ ⟨n, hasProjectiveDimensionLE_stalk_restrict_complexAffineSpace U (F k)⟩) φ hφ y₀

end AffineSpace

end ComplexAnalytic
