/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.AnalyticSpace.Evaluation
import Oka.Nullstellensatz.Germ
import Oka.StalkEquiv

/-!
# The Rückert Nullstellensatz on complex analytic spaces

Let `X` be a complex analytic space, `x : X`, and let `φ₁, …, φ_s` and `g` be sections of `𝒪_X`
over an open neighbourhood `W` of `x`. If `g` vanishes at every point near `x` at which all `φⱼ`
vanish, then some power of the germ of `g` at `x` lies in the ideal of `𝒪_{X,x}` generated by the
germs of the `φⱼ` (`ComplexAnalytic.AnalyticSpace.isNullstellensatzAt`).

The statement is `ComplexAnalytic.AnalyticSpace.IsNullstellensatzAt X x`. On `ℂⁿ` it is
`OkaRing.germ_mem_radical_span_of_eventually` read through the Taylor expansion of stalks
(`ComplexAnalytic.isNullstellensatzAt_complexAffineSpace`). It descends along morphisms which
are surjective on stalks and embeddings on points, provided the image is cut out near the point
by sections whose germs are killed
(`ComplexAnalytic.AnalyticSpace.IsNullstellensatzAt.of_hom`): this covers both open subspaces and
the closed subspaces cut out in a chart. Finally it ascends from an open subspace
(`ComplexAnalytic.AnalyticSpace.IsNullstellensatzAt.of_restrict`).

## Main definitions

- `ComplexAnalytic.AnalyticSpace.IsNullstellensatzAt X x`: the Nullstellensatz at `x`.

## Main results

- `ComplexAnalytic.AnalyticSpace.isNullstellensatzAt`: every complex analytic space satisfies
  the Nullstellensatz at every point.
-/

universe u

open CategoryTheory TopologicalSpace Opposite Filter Topology AlgebraicGeometry

namespace Ideal

variable {R S : Type*} [CommRing R] [CommRing S] {ι : Type*}

/-- A ring homomorphism maps the radical of the ideal spanned by `v` into the radical of the
ideal spanned by the image of `v`. -/
theorem map_mem_radical_span (f : R →+* S) {v : ι → R} {x : R}
    (h : x ∈ (Ideal.span (Set.range v)).radical) :
    f x ∈ (Ideal.span (Set.range (f ∘ v))).radical := by
  obtain ⟨k, hk⟩ := h
  refine ⟨k, ?_⟩
  have := Ideal.mem_map_of_mem f hk
  rwa [Ideal.map_span, ← Set.range_comp, map_pow] at this

end Ideal

namespace ComplexAnalytic

namespace AnalyticSpace

variable (X : AnalyticSpace.{u})

/-- The **Nullstellensatz at `x`**: for sections `φ₁, …, φ_s` and `g` of `𝒪_X` over an open
neighbourhood `W` of `x`, if `g` vanishes at every point near `x` at which all `φⱼ` vanish, then
the germ of `g` at `x` lies in the radical of the ideal generated by the germs of the `φⱼ`. -/
def IsNullstellensatzAt (x : X) : Prop :=
  ∀ (W : X.Opens) (hxW : x ∈ W) {s : ℕ} (φ : Fin s → X.presheaf.obj (op W))
    (g : X.presheaf.obj (op W)),
    (∀ᶠ y in 𝓝 x, ∀ hy : y ∈ W, (∀ j, X.eval y hy (φ j) = 0) → X.eval y hy g = 0) →
      X.presheaf.germ W x hxW g ∈
        (Ideal.span (Set.range fun j ↦ X.presheaf.germ W x hxW (φ j))).radical

variable {X}

/-- The value of the restriction of a section is the value of the section. -/
lemma eval_map_homOfLE {V W : X.Opens} (h : V ≤ W) {y : X} (hy : y ∈ V)
    (s : X.presheaf.obj (op W)) :
    X.eval y hy (X.presheaf.map (homOfLE h).op s) = X.eval y (h hy) s := by
  rw [eval_apply, eval_apply, TopCat.Presheaf.germ_res_apply]

/-- Two sections with the same germ at `x` have the same values near `x`. -/
lemma eventually_eval_eq_of_germ_eq {V W : X.Opens} {x : X} (hxV : x ∈ V) (hxW : x ∈ W)
    {s : X.presheaf.obj (op V)} {t : X.presheaf.obj (op W)}
    (h : X.presheaf.germ V x hxV s = X.presheaf.germ W x hxW t) :
    ∀ᶠ y in 𝓝 x, ∀ (hyV : y ∈ V) (hyW : y ∈ W), X.eval y hyV s = X.eval y hyW t := by
  obtain ⟨O, hxO, iV, iW, hO⟩ := X.presheaf.germ_eq x hxV hxW s t h
  filter_upwards [O.isOpen.mem_nhds hxO] with y hyO hyV hyW
  rw [← eval_map_homOfLE (leOfHom iV) hyO, ← eval_map_homOfLE (leOfHom iW) hyO]
  exact congrArg (X.eval y hyO) hO

end AnalyticSpace

section ComplexAffineSpace

variable {n : ℕ}

/-- Complex affine `n`-space, as a complex analytic space. -/
local notation "𝔸" => AnalyticSpace.complexAffineSpace n

/-- **On `ℂⁿ` the value of a section is its value as a holomorphic function.** -/
theorem eval_complexAffineSpace_of_mem {W : Opens (complexAffineSpace.{u} n)}
    (y : 𝔸) (hy : y ∈ W)
    (s : (𝔸).presheaf.obj (op W)) :
    (𝔸).eval (U := W) y hy s =
      OkaRing.evalHom (U := W) (x := y) hy s := by
  set c := OkaRing.evalHom (U := W) (x := y) hy s with hc
  set t : (𝔸).presheaf.obj (op W) :=
    (𝔸).presheaf.map (homOfLE (le_top : W ≤ ⊤)).op ((𝔸).algebraMap c)
  have h1 : (𝔸).stalkAlgMap y c = (𝔸).presheaf.germ W y hy t :=
    (TopCat.Presheaf.germ_res_apply (𝔸).presheaf (homOfLE (le_top : W ≤ ⊤)) y hy _).symm
  have h2 : (𝔸).presheaf.germ W y hy s - (𝔸).stalkAlgMap y c = (𝔸).presheaf.germ W y hy (s - t) :=
    (congrArg ((𝔸).presheaf.germ W y hy s - ·) h1).trans (map_sub _ _ _).symm
  have h3 : OkaRing.evalHom (U := W) (x := y) hy (s - t) = 0 := by
    change c - c = 0
    exact sub_self c
  exact ((𝔸).evalStalk_eq_iff _ _).2 (h2 ▸
    (germ_mem_maximalIdeal_iff (ι := ULift.{u} (Fin n)) (y := y) (U := W) hy _).2 h3)

/-- **The Nullstellensatz on `ℂⁿ`.** -/
theorem isNullstellensatzAt_complexAffineSpace (w : AnalyticSpace.complexAffineSpace.{u} n) :
    (𝔸).IsNullstellensatzAt w := by
  intro W hwW s φ g h
  have h' : ∀ᶠ y in 𝓝 (w : ULift.{u} (Fin n) → ℂ),
      (∀ j, OkaRing.toGlobalFun W (φ j : OkaRing W) y = 0) →
        OkaRing.toGlobalFun W (g : OkaRing W) y = 0 := by
    filter_upwards [h, W.isOpen.mem_nhds hwW] with y hy hyW hφ
    have := hy hyW fun j ↦ by
      rw [eval_complexAffineSpace_of_mem y hyW, OkaRing.evalHom_apply,
        ← OkaRing.toGlobalFun_apply]
      exact hφ j
    rwa [eval_complexAffineSpace_of_mem y hyW, OkaRing.evalHom_apply,
      ← OkaRing.toGlobalFun_apply] at this
  have hmem := Ideal.map_mem_radical_span
    (okaStalkEquiv (ι := ULift.{u} (Fin n)) w).symm.toRingHom
    (OkaRing.germ_mem_radical_span_of_eventually hwW (fun j ↦ (φ j : OkaRing W)) g h')
  have hgerm : ∀ t : OkaRing W, (okaStalkEquiv (ι := ULift.{u} (Fin n)) w).symm
      (OkaRing.germ hwW t) = (𝔸).presheaf.germ W w hwW t :=
    fun t ↦ by
      rw [RingEquiv.symm_apply_eq]
      exact (okaStalkEquiv_germ hwW t).symm
  have e1 : (okaStalkEquiv (ι := ULift.{u} (Fin n)) w).symm.toRingHom (OkaRing.germ hwW g) =
      (𝔸).presheaf.germ W w hwW g := hgerm g
  have e2 : ((okaStalkEquiv (ι := ULift.{u} (Fin n)) w).symm.toRingHom ∘
      fun j ↦ OkaRing.germ hwW (φ j : OkaRing W)) = fun j ↦ (𝔸).presheaf.germ W w hwW (φ j) :=
    funext fun j ↦ hgerm _
  rw [e1, e2] at hmem
  exact hmem

end ComplexAffineSpace

namespace AnalyticSpace

namespace IsNullstellensatzAt

/-- **The Nullstellensatz descends along a morphism which is an embedding on points and
surjective on stalks**, provided that near the image point the image is cut out by sections
`f₁, …, f_k` whose germs are killed by the stalk map. This applies to the inclusion of an open
subspace (with no `fₗ`) and to a closed subspace cut out in a chart. -/
theorem of_hom {Z Y : AnalyticSpace.{u}} (i : Z.toLocallyRingedSpace ⟶ Y.toLocallyRingedSpace)
    (hlin : IsCLinearHom i Z.algebraMap Y.algebraMap) (hi : Topology.IsInducing i.base) {z : Z}
    (hsurj : Function.Surjective (i.stalkMap z).hom) {O : Y.Opens} (hzO : i.base z ∈ O)
    {k : ℕ} (f : Fin k → Y.presheaf.obj (op O))
    (hf : ∀ l, (i.stalkMap z).hom (Y.presheaf.germ O (i.base z) hzO (f l)) = 0)
    (hrange : ∀ᶠ w in 𝓝 (i.base z), ∀ hw : w ∈ O, (∀ l, Y.eval w hw (f l) = 0) →
      w ∈ Set.range i.base)
    (hY : Y.IsNullstellensatzAt (i.base z)) : Z.IsNullstellensatzAt z := by
  classical
  intro W hzW s φ g hyp
  -- lift the germs of the `φⱼ` and of `g` to sections near `i z`
  have hlift : ∀ a : Z.presheaf.stalk z, ∃ (V : Y.Opens) (hV : i.base z ∈ V)
      (b : Y.presheaf.obj (op V)), (i.stalkMap z).hom (Y.presheaf.germ V (i.base z) hV b) = a := by
    intro a
    obtain ⟨c, rfl⟩ := hsurj a
    obtain ⟨V, hV, b, rfl⟩ := Y.presheaf.exists_germ_eq c
    exact ⟨V, hV, b, rfl⟩
  choose V hV Φ hΦ using fun j ↦ hlift (Z.presheaf.germ W z hzW (φ j))
  obtain ⟨VG, hVG, G, hG⟩ := hlift (Z.presheaf.germ W z hzW g)
  -- the pulled back sections agree with the given ones near `z`
  have hev : ∀ {V' : Y.Opens} (hV' : i.base z ∈ V') (b : Y.presheaf.obj (op V'))
      (a : Z.presheaf.obj (op W)),
      (i.stalkMap z).hom (Y.presheaf.germ V' (i.base z) hV' b) = Z.presheaf.germ W z hzW a →
      ∀ᶠ y in 𝓝 z, ∀ (hyW : y ∈ W) (hyV : i.base y ∈ V'),
        Z.eval y hyW a = Y.eval (i.base y) hyV b := by
    intro V' hV' b a hab
    rw [LocallyRingedSpace.stalkMap_germ_apply] at hab
    filter_upwards [eventually_eval_eq_of_germ_eq _ hzW hab] with y hy hyW hyV
    rw [← hy hyV hyW]
    exact eval_c_app i hlin y hyV b
  -- the common open and the combined family
  set O' : Y.Opens := O ⊓ VG ⊓ Finset.univ.inf V with hO'
  have hO'O : O' ≤ O := inf_le_left.trans inf_le_left
  have hO'G : O' ≤ VG := inf_le_left.trans inf_le_right
  have hO'V : ∀ j, O' ≤ V j := fun j ↦ inf_le_right.trans (Finset.inf_le (Finset.mem_univ j))
  have hzO' : i.base z ∈ O' :=
    ⟨⟨hzO, hVG⟩, TopologicalSpace.Opens.mem_finset_inf.mpr fun j _ ↦ hV j⟩
  set F : Fin (s + k) → Y.presheaf.obj (op O') :=
    Fin.append (fun j ↦ Y.presheaf.map (homOfLE (hO'V j)).op (Φ j))
      (fun l ↦ Y.presheaf.map (homOfLE hO'O).op (f l)) with hF
  set G' : Y.presheaf.obj (op O') := Y.presheaf.map (homOfLE hO'G).op G with hG'
  -- the hypothesis of the Nullstellensatz upstairs
  have hZ : ∀ᶠ y in 𝓝 z, (∀ j, ∀ (hyW : y ∈ W) (hyV : i.base y ∈ V j),
        Z.eval y hyW (φ j) = Y.eval (i.base y) hyV (Φ j)) ∧
      (∀ (hyW : y ∈ W) (hyV : i.base y ∈ VG), Z.eval y hyW g = Y.eval (i.base y) hyV G) ∧
      y ∈ W ∧ (∀ hy : y ∈ W, (∀ j, Z.eval y hy (φ j) = 0) → Z.eval y hy g = 0) :=
    (eventually_all.mpr fun j ↦ hev (hV j) (Φ j) (φ j) (hΦ j)).and
      ((hev hVG G g hG).and (Filter.Eventually.and (W.isOpen.mem_nhds hzW) hyp))
  rw [hi.nhds_eq_comap z, Filter.eventually_comap] at hZ
  have hYhyp : ∀ᶠ w in 𝓝 (i.base z), ∀ hw : w ∈ O',
      (∀ m, Y.eval w hw (F m) = 0) → Y.eval w hw G' = 0 := by
    filter_upwards [hZ, hrange] with w hw hwr hwO' hFw
    obtain ⟨y, rfl⟩ := hwr (hO'O hwO') fun l ↦ by
      have := hFw (Fin.natAdd s l)
      rwa [hF, Fin.append_right, eval_map_homOfLE] at this
    obtain ⟨hφΦ, hgG, hyW, hyp'⟩ := hw y rfl
    rw [hG', eval_map_homOfLE, ← hgG hyW (hO'G hwO')]
    refine hyp' hyW fun j ↦ ?_
    rw [hφΦ j hyW (hO'V j hwO')]
    have := hFw (Fin.castAdd k j)
    rwa [hF, Fin.append_left, eval_map_homOfLE] at this
  -- map the conclusion upstairs along the stalk map
  have hmem := Ideal.map_mem_radical_span (i.stalkMap z).hom (hY O' hzO' F G' hYhyp)
  have hGz : (i.stalkMap z).hom (Y.presheaf.germ O' (i.base z) hzO' G') =
      Z.presheaf.germ W z hzW g := by
    rw [hG', TopCat.Presheaf.germ_res_apply]
    exact hG
  rw [hGz] at hmem
  refine Ideal.radical_mono ?_ hmem
  rw [Ideal.span_le]
  rintro _ ⟨m, rfl⟩
  refine Fin.addCases (fun j ↦ ?_) (fun l ↦ ?_) m
  · rw [Function.comp_apply, hF, Fin.append_left, TopCat.Presheaf.germ_res_apply, hΦ j]
    exact Ideal.subset_span ⟨j, rfl⟩
  · rw [Function.comp_apply, hF, Fin.append_right, TopCat.Presheaf.germ_res_apply, hf l]
    exact zero_mem _

/-- **The Nullstellensatz ascends from an open subspace.** -/
theorem of_restrict {X : AnalyticSpace.{u}} {U : X.Opens} {x : X.restrict U}
    (h : (X.restrict U).IsNullstellensatzAt x) : X.IsNullstellensatzAt x.1 := by
  intro W hxW s φ g hyp
  set i := (X.ofRestrict U).toLRSHom with hi
  have hlin : IsCLinearHom i (X.restrict U).algebraMap X.algebraMap := (X.ofRestrict U).isCLinear
  have hx : i.base x ∈ W := hxW
  have ht : Tendsto i.base (𝓝 x) (𝓝 (i.base x)) := i.base.hom.continuous.tendsto x
  have hyp' : ∀ᶠ y in 𝓝 x, ∀ hy : i.base y ∈ W,
      (∀ j, (X.restrict U).eval y hy (i.c.app (op W) (φ j)) = 0) →
        (X.restrict U).eval y hy (i.c.app (op W) g) = 0 := by
    filter_upwards [ht.eventually hyp] with y hy hyW hφ
    rw [eval_c_app i hlin y hyW]
    exact hy hyW fun j ↦ by rw [← eval_c_app i hlin y hyW]; exact hφ j
  have hmem := h ((Opens.map i.base).obj W) hx (fun j ↦ i.c.app (op W) (φ j))
    (i.c.app (op W) g) hyp'
  set e := (asIso (i.stalkMap x)).commRingCatIsoToRingEquiv with he
  have hmem' := Ideal.map_mem_radical_span e.symm.toRingHom hmem
  have hgerm : ∀ a : X.presheaf.obj (op W), e.symm.toRingHom
      ((X.restrict U).presheaf.germ ((Opens.map i.base).obj W) x hx (i.c.app (op W) a)) =
        X.presheaf.germ W (i.base x) hx a := fun a ↦ by
    rw [← LocallyRingedSpace.stalkMap_germ_apply]
    exact e.symm_apply_apply _
  have e2 : (e.symm.toRingHom ∘ fun j ↦ (X.restrict U).presheaf.germ ((Opens.map i.base).obj W)
      x hx (i.c.app (op W) (φ j))) = fun j ↦ X.presheaf.germ W (i.base x) hx (φ j) :=
    funext fun j ↦ hgerm (φ j)
  rw [hgerm, e2] at hmem'
  exact hmem'

end IsNullstellensatzAt

/-- **The Rückert Nullstellensatz on complex analytic spaces.** For sections `φ₁, …, φ_s` and `g`
of `𝒪_X` over an open neighbourhood `W` of `x`, if `g` vanishes at every point near `x` at which
all `φⱼ` vanish, then some power of the germ of `g` at `x` lies in the ideal generated by the
germs of the `φⱼ`. -/
theorem isNullstellensatzAt (X : AnalyticSpace.{u}) (x : X) : X.IsNullstellensatzAt x := by
  obtain ⟨U, n, k, V, i, f, hcut, hlin⟩ := X.local_model x
  refine IsNullstellensatzAt.of_restrict (U := U.1) (x := ⟨x, U.2⟩) ?_
  have hY : ((AnalyticSpace.complexAffineSpace.{u} n).restrict V).IsNullstellensatzAt
      (i.base ⟨x, U.2⟩) := by
    refine IsNullstellensatzAt.of_hom
      ((AnalyticSpace.complexAffineSpace.{u} n).ofRestrict V).toLRSHom
      ((AnalyticSpace.complexAffineSpace.{u} n).ofRestrict V).isCLinear
      V.isOpenEmbedding.isInducing (ConcreteCategory.bijective_of_isIso _).surjective
      (O := ⊤) trivial Fin.elim0 (fun l ↦ l.elim0) ?_ (isNullstellensatzAt_complexAffineSpace _)
    filter_upwards [V.isOpen.mem_nhds (i.base ⟨x, U.2⟩).2] with w hw _ _
    exact ⟨⟨w, hw⟩, rfl⟩
  refine IsNullstellensatzAt.of_hom (Z := X.restrict U.1)
    (Y := (AnalyticSpace.complexAffineSpace.{u} n).restrict V) i hlin
    hcut.isClosedEmbedding.isInducing (hcut.surjective_stalkMap _) (O := ⊤) trivial f
    (fun l ↦ ?_) ?_ hY
  · have hker : ((_root_.complexAffineSpace.{u} n).restrict V.isOpenEmbedding).presheaf.Γgerm
        (i.base ⟨x, U.2⟩) (f l) ∈ RingHom.ker (i.stalkMap ⟨x, U.2⟩).hom := by
      rw [hcut.ker_stalkMap]
      exact Ideal.subset_span ⟨l, rfl⟩
    exact hker
  · refine Filter.Eventually.of_forall fun w _ hw ↦ ?_
    refine (Set.ext_iff.mp hcut.range_base w).mpr fun j ↦ ?_
    exact (eval_eq_zero_iff _).1 (hw j)

end AnalyticSpace

end ComplexAnalytic
