/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.AlgebraicGeometry.Modules.Support
import Oka.AnalyticSpace.SupportAnnihilator

/-!
# Coherent sheaves supported over the image of a morphism of schemes

Let `Y` be a complex analytic space, `p : Y ⟶ X` a morphism of locally ringed spaces to a locally
noetherian scheme `X` and `i : T ⟶ X` a morphism of schemes. Write
`I_x = i.pushforwardStalkIdeal x ⊆ 𝒪_{X,x}` for the kernel of `𝒪_{X,x} → (i_* 𝒪_T)_x`. If a
coherent sheaf `M` on `Y` has zero stalks at the points `y` with `p y ∉ i(T)`, then near every
point of `Y` a power of the ideal generated by `p^♯ I_{p y}` kills `M_y`
(`ComplexAnalytic.AnalyticSpace.exists_nhds_pow_map_pushforwardStalkIdeal_le_annihilator`), and
if `Y` is compact the power can be chosen uniformly
(`ComplexAnalytic.AnalyticSpace.exists_pow_map_pushforwardStalkIdeal_le_annihilator`).

On an affine open `W ∋ p y`, `I_x` is generated for `x ∈ W` by the germs of the sections of
`𝒪_X(W)` whose basic open misses `i(T)`
(`AlgebraicGeometry.Scheme.Hom.pushforwardStalkIdeal_le_map_basicOpenAvoidingIdeal`). These
form a finitely generated ideal, and their pullbacks to `p⁻¹ W` are sections of `𝒪_Y` off whose
zero loci `M` vanishes, so Rückert's Nullstellensatz in the form
`ComplexAnalytic.AnalyticSpace.exists_pow_le_annihilator` applies on the open subspace `p⁻¹ W`.
-/

universe u

open CategoryTheory TopologicalSpace Opposite AlgebraicGeometry

namespace ComplexAnalytic.AnalyticSpace

variable {Y : AnalyticSpace.{u}} {X T : Scheme.{u}}
  (p : Y.toLocallyRingedSpace ⟶ X.toLocallyRingedSpace) (i : T ⟶ X)

/-- **Rückert's Nullstellensatz over a scheme, locally.** If the stalks of a coherent sheaf `M` on
`Y` vanish at the points `y` with `p y ∉ i(T)`, then every point of `Y` has a neighbourhood `U`
and an exponent `k` such that `(p^♯ I_{p y})^k` kills `M_y` for all `y ∈ U`. -/
theorem exists_nhds_pow_map_pushforwardStalkIdeal_le_annihilator [IsLocallyNoetherian X]
    (M : SheafOfModules.{u} Y.ringSheaf) [M.IsCoherent]
    (hM : ∀ y : Y, p.base y ∉ Set.range i.base → Subsingleton ((Y.stalkFunctor y).obj M))
    (y₀ : Y) :
    ∃ U : Y.Opens, y₀ ∈ U ∧ ∃ k : ℕ, ∀ y ∈ U,
      Ideal.map (p.stalkMap y).hom (i.toLRSHom.pushforwardStalkIdeal (p.base y)) ^ k ≤
        Module.annihilator (Y.presheaf.stalk y) ((Y.stalkFunctor y).obj M) := by
  obtain ⟨W, hW⟩ : ∃ W : X.affineOpens, p.base y₀ ∈ (W : X.Opens) :=
    Opens.mem_iSup.1 (by rw [iSup_affineOpens_eq_top]; trivial)
  haveI : IsNoetherianRing Γ(X, W) := IsLocallyNoetherian.component_noetherian W
  obtain ⟨r, h, hh⟩ := Submodule.fg_iff_exists_fin_generating_family.1
    (IsNoetherian.noetherian (i.basicOpenAvoidingIdeal W.1))
  let V : Y.Opens := (Opens.map p.base).obj W.1
  have hy₀ : y₀ ∈ V := hW
  let g : (Y.restrict V).toLocallyRingedSpace ⟶ X.toLocallyRingedSpace :=
    (Y.ofRestrict V).toLRSHom ≫ p
  have hle : (⊤ : (Y.restrict V).Opens) ≤ (Opens.map g.base).obj W.1 := fun y _ ↦ y.2
  let gs : Fin r → (Y.restrict V).presheaf.obj (op ⊤) := fun j ↦
    (Y.restrict V).presheaf.map (homOfLE hle).op (g.c.app (op W.1) (h j))
  have hgerm : ∀ (y : Y.restrict V) j, (Y.restrict V).presheaf.Γgerm y (gs j) =
      g.stalkMap y (X.presheaf.germ W.1 (g.base y) y.2 (h j)) := by
    intro y j
    rw [LocallyRingedSpace.stalkMap_germ_apply]
    exact TopCat.Presheaf.germ_res_apply _ _ _ _ _
  let N := (Y.toLocallyRingedSpace.restrictModules V).obj M
  haveI hN : N.IsCoherent := LocallyRingedSpace.isCoherent_restrictModules M V
  obtain ⟨U', hU', k, hk⟩ := @exists_pow_le_annihilator (Y.restrict V) N hN r gs
    (fun y ⟨j, hj⟩ ↦ by
      have hu : IsUnit (X.presheaf.germ W.1 (g.base y) y.2 (h j)) := by
        haveI : IsLocalHom (g.stalkMap y).hom := g.prop y
        rw [← isUnit_map_iff (g.stalkMap y).hom, ← hgerm,
          ← evalStalk_ne_zero_iff_isUnit (Z := Y.restrict V)]
        exact hj
      have hb : g.base y ∈ X.basicOpen (h j) := (X.mem_basicOpen (h j) _ y.2).2 hu
      have hmem : h j ∈ i.basicOpenAvoidingIdeal W.1 := hh ▸ Submodule.subset_span ⟨j, rfl⟩
      haveI := hM y.1 ((i.mem_basicOpenAvoidingIdeal _).1 hmem _ hb)
      exact subsingleton_stalk_restrict V M y) ⟨y₀, hy₀⟩
  refine ⟨LocallyRingedSpace.imOpen V U', LocallyRingedSpace.mem_imOpen V U' hy₀ hU', k, ?_⟩
  rintro _ ⟨y, hyU', rfl⟩
  have hspan' : Ideal.map (g.stalkMap y).hom (i.toLRSHom.pushforwardStalkIdeal (p.base y.1)) ≤
      Ideal.span (Set.range fun j ↦ (Y.restrict V).presheaf.Γgerm y (gs j)) := by
    refine (Ideal.map_mono (i.pushforwardStalkIdeal_le_map_basicOpenAvoidingIdeal W.2 _ y.2)).trans
      ?_
    rw [← hh, Ideal.map_span, Ideal.map_span, ← Set.range_comp, ← Set.range_comp]
    refine le_of_eq (congrArg Ideal.span (congrArg Set.range (funext fun j ↦ ?_)))
    exact (hgerm y j).symm
  have hφ : ∀ a, (Y.ofRestrict V).toLRSHom.stalkMap y (p.stalkMap y.1 a) = g.stalkMap y a := by
    intro a
    change _ = ((Y.ofRestrict V).toLRSHom ≫ p).stalkMap y a
    rw [LocallyRingedSpace.stalkMap_comp]
    rfl
  have hspan : Ideal.map ((Y.ofRestrict V).toLRSHom.stalkMap y).hom
      (Ideal.map (p.stalkMap y.1).hom (i.toLRSHom.pushforwardStalkIdeal (p.base y.1))) ≤
      Ideal.span (Set.range fun j ↦ (Y.restrict V).presheaf.Γgerm y (gs j)) := by
    refine Ideal.map_le_iff_le_comap.2 (Ideal.map_le_iff_le_comap.2 fun a ha ↦ ?_)
    rw [Ideal.mem_comap, Ideal.mem_comap]
    erw [hφ]
    exact hspan' (Ideal.mem_map_of_mem _ ha)
  intro a ha
  refine (stalkMap_mem_annihilator_iff V M y a).1 (hk y hyU' ?_)
  have hpow : Ideal.map ((Y.ofRestrict V).toLRSHom.stalkMap y).hom
      (Ideal.map (p.stalkMap y.1).hom (i.toLRSHom.pushforwardStalkIdeal (p.base y.1)) ^ k) ≤
      Ideal.span (Set.range fun j ↦ (Y.restrict V).presheaf.Γgerm y (gs j)) ^ k := by
    rw [Ideal.map_pow]
    exact Ideal.pow_right_mono hspan k
  exact hpow (Ideal.mem_map_of_mem _ ha)

/-- **Rückert's Nullstellensatz over a scheme.** Let `Y` be a compact complex analytic space. If
the stalks of a coherent sheaf `M` on `Y` vanish at the points `y` with `p y ∉ i(T)`, then there
is `n` such that `(p^♯ I_{p y})ⁿ` kills `M_y` for all `y`. -/
theorem exists_pow_map_pushforwardStalkIdeal_le_annihilator [IsLocallyNoetherian X]
    [CompactSpace Y] (M : SheafOfModules.{u} Y.ringSheaf) [M.IsCoherent]
    (hM : ∀ y : Y, p.base y ∉ Set.range i.base → Subsingleton ((Y.stalkFunctor y).obj M)) :
    ∃ n : ℕ, ∀ y : Y,
      Ideal.map (p.stalkMap y).hom (i.toLRSHom.pushforwardStalkIdeal (p.base y)) ^ n ≤
        Module.annihilator (Y.presheaf.stalk y) ((Y.stalkFunctor y).obj M) := by
  classical
  choose U hyU k hk using exists_nhds_pow_map_pushforwardStalkIdeal_le_annihilator p i M hM
  obtain ⟨s, hs⟩ := isCompact_univ.elim_finite_subcover (fun y ↦ (U y : Set Y))
    (fun y ↦ (U y).isOpen) (fun y _ ↦ Set.mem_iUnion.2 ⟨y, hyU y⟩)
  refine ⟨s.sup k, fun y ↦ ?_⟩
  obtain ⟨z, hz, hyz⟩ := Set.mem_iUnion₂.1 (hs (Set.mem_univ y))
  exact (Ideal.pow_le_pow_right (Finset.le_sup hz)).trans (hk z y hyz)

end ComplexAnalytic.AnalyticSpace
