/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.AnalyticSpace.Coherent
import Oka.AnalyticSpace.Nullstellensatz
import Oka.Geometry.RingedSpace.LocallyRingedSpace.LocalFreeResolution
import Oka.Geometry.RingedSpace.LocallyRingedSpace.ModulesStalkNakayama
import Oka.Nullstellensatz.Minors

/-!
# Sections vanishing on the support of a coherent sheaf kill it up to a power

Let `X` be a complex analytic space, `N` a coherent sheaf of `𝒪_X`-modules and `g₁, …, g_r`
global sections of `𝒪_X`. If the stalk `N_y` vanishes at every point `y` at which some `gᵢ` does
not vanish, then every point has a neighbourhood `U` and an exponent `k` such that
`(g₁, …, g_r)^k` kills `N_y` for all `y ∈ U`
(`ComplexAnalytic.AnalyticSpace.exists_pow_le_annihilator`).

## Strategy

Near a point, `N` has a finite presentation `𝒪^J → 𝒪^I → N → 0`. The maximal minors of the
presentation matrix are finitely many global sections which kill every stalk of `N` and at least
one of which does not vanish at any point where the stalk of `N` vanishes
(`Oka/Nullstellensatz/Minors.lean`). Hence each `gᵢ` vanishes wherever all these minors vanish,
and the Nullstellensatz on analytic spaces (`ComplexAnalytic.AnalyticSpace.isNullstellensatzAt`)
puts a power of `gᵢ` into the ideal generated by the minors at the point, hence, the membership
spreading to a neighbourhood, into the annihilator of `N_y` for all nearby `y`.

## Main results

- `ComplexAnalytic.AnalyticSpace.exists_pow_le_annihilator`: the statement above.
- `ComplexAnalytic.AnalyticSpace.exists_pow_smul_eq_zero`: the version for a single section.
-/

universe u

open CategoryTheory TopologicalSpace Opposite Filter Topology AlgebraicGeometry Limits

namespace Ideal

/-- If the `k`-th powers of `f₁, …, f_r` lie in `A`, then so does the `(r * k + 1)`-st power of
the ideal they generate. -/
theorem span_range_pow_le_of_forall_pow_mem {R : Type*} [CommRing R] {A : Ideal R} {k : ℕ} :
    ∀ {r : ℕ} (f : Fin r → R), (∀ i, f i ^ k ∈ A) →
      Ideal.span (Set.range f) ^ (r * k + 1) ≤ A
  | 0, f, _ => by
    rw [Set.range_eq_empty, Ideal.span_empty, zero_mul, zero_add, pow_one]
    exact bot_le
  | r + 1, f, hf => by
    rw [← Fin.cons_self_tail f, Fin.range_cons, Ideal.span_insert,
      show (r + 1) * k + 1 = k + (r * k + 1) by ring]
    refine Ideal.sup_pow_add_le_pow_sup_pow.trans (sup_le ?_ ?_)
    · rw [Ideal.span_singleton_pow, Ideal.span_le, Set.singleton_subset_iff]
      exact hf 0
    · exact span_range_pow_le_of_forall_pow_mem (Fin.tail f) fun i ↦ hf i.succ

end Ideal

namespace TopCat.Presheaf

/-- If the germ at `x` of a global section lies in the ideal generated by the germs of finitely
many global sections, the same holds at all points near `x`. -/
theorem eventually_Γgerm_mem_span {X : TopCat.{u}} (F : X.Presheaf CommRingCat.{u}) {x : X}
    {m : ℕ} (s : F.obj (op ⊤)) (ψ : Fin m → F.obj (op ⊤))
    (h : F.Γgerm x s ∈ Ideal.span (Set.range fun j ↦ F.Γgerm x (ψ j))) :
    ∀ᶠ y in 𝓝 x, F.Γgerm y s ∈ Ideal.span (Set.range fun j ↦ F.Γgerm y (ψ j)) := by
  classical
  obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun _).mp h
  choose O hxO c' hc' using fun j ↦ F.exists_germ_eq (c j)
  set O' : Opens X := Finset.univ.inf O
  have hxO' : x ∈ O' := TopologicalSpace.Opens.mem_finset_inf.mpr fun j _ ↦ hxO j
  have hle : ∀ j, O' ≤ O j := fun j ↦ Finset.inf_le (Finset.mem_univ j)
  set t : F.obj (op O') := F.map (homOfLE le_top).op s -
    ∑ j, F.map (homOfLE (hle j)).op (c' j) * F.map (homOfLE le_top).op (ψ j) with ht
  have hgerm : ∀ y (hy : y ∈ O'), F.germ O' y hy t =
      F.Γgerm y s - ∑ j, F.germ (O j) y (hle j hy) (c' j) * F.Γgerm y (ψ j) := by
    intro y hy
    rw [ht, map_sub, map_sum, germ_res_apply]
    congr 1
    refine Finset.sum_congr rfl fun j _ ↦ ?_
    rw [map_mul, germ_res_apply, germ_res_apply]
    rfl
  have ht0 : F.germ O' x hxO' t = F.germ O' x hxO' 0 := by
    rw [hgerm, map_zero, sub_eq_zero, ← hc]
    exact Finset.sum_congr rfl fun j _ ↦ by rw [hc' j, smul_eq_mul]
  obtain ⟨W, hxW, i1, i2, hW⟩ := F.germ_eq x hxO' hxO' t 0 ht0
  filter_upwards [W.isOpen.mem_nhds hxW] with y hyW
  have hyO' : y ∈ O' := leOfHom i1 hyW
  have key : F.germ O' y hyO' t = 0 := by
    rw [← germ_res_apply F i1 y hyW, hW, germ_res_apply, map_zero]
  rw [hgerm, sub_eq_zero] at key
  rw [key]
  exact Ideal.sum_mem _ fun j _ ↦ Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨j, rfl⟩)

end TopCat.Presheaf


namespace AlgebraicGeometry.LocallyRingedSpace

variable {Y : LocallyRingedSpace.{u}}

section Presentation

variable {I J : Type u} [Finite I] [DecidableEq I]
  (φ : SheafOfModules.free (R := Y.ringSheaf) J ⟶ SheafOfModules.free I)

/-- The matrix of a morphism of finite free sheaves of modules, with entries global sections of
the structure sheaf: the `(i, j)` entry is the `i`-th coordinate of the image of the `j`-th
generator. -/
noncomputable def freeHomMatrix : Matrix I J (Y.presheaf.obj (op ⊤)) :=
  Matrix.of fun i j ↦ SheafOfModules.freeEval (op ⊤) (generatorSection φ j) i

/-- In the bases of germs of generators, the stalk of a morphism of finite free sheaves has
matrix the germs of `freeHomMatrix`. -/
lemma basisStalkFree_repr_stalkFunctor_map [Finite J] (y : Y) (j : J) (i : I) :
    (basisStalkFree I y).repr ((Y.stalkFunctor y).map φ (basisStalkFree J y j)) i =
      Y.presheaf.Γgerm y (freeHomMatrix φ i j) := by
  haveI := Fintype.ofFinite I
  have hgen : φ.val.app (op ⊤) (generatorSection (𝟙 _) j) = generatorSection φ j := by
    rw [← generatorSection_comp, Category.id_comp]
  set b := generatorSection φ j with hb
  have hsum : b = ∑ i', SheafOfModules.freeEval (op ⊤) b i' •
      generatorSection (𝟙 (SheafOfModules.free (R := Y.ringSheaf) I)) i' :=
    SheafOfModules.val_app_eq_sum (op ⊤) (𝟙 (SheafOfModules.free (R := Y.ringSheaf) I)) b
  rw [basisStalkFree_apply, stalkFunctor_map_germTop, hgen, hsum]
  have hgerm : germTop (SheafOfModules.free (R := Y.ringSheaf) I) y
      (∑ i', SheafOfModules.freeEval (op ⊤) b i' •
        generatorSection (𝟙 (SheafOfModules.free (R := Y.ringSheaf) I)) i') =
      ∑ i', Y.presheaf.Γgerm y (SheafOfModules.freeEval (op ⊤) b i') • basisStalkFree I y i' := by
    rw [germTop]
    erw [map_sum]
    refine Finset.sum_congr rfl fun i' _ ↦ ?_
    rw [basisStalkFree_apply]
    exact germMod_smul (M := SheafOfModules.free (R := Y.ringSheaf) I) (W := ⊤) trivial _ _
  rw [hgerm, Module.Basis.repr_sum_self]
  rfl

/-- The germ at `y` of a maximal minor of `freeHomMatrix` is the corresponding maximal minor of
the matrix of the stalk map. -/
lemma Γgerm_det_submatrix [Fintype I] [Finite J] (y : Y) (σ : I → J) :
    Y.presheaf.Γgerm y ((freeHomMatrix φ).submatrix _root_.id σ).det =
      ((Matrix.of fun i j ↦ (basisStalkFree I y).repr
        ((Y.stalkFunctor y).map φ (basisStalkFree J y j)) i).submatrix _root_.id σ).det := by
  have hM : ((freeHomMatrix φ).submatrix _root_.id σ).map (Y.presheaf.Γgerm y).hom =
      (Matrix.of fun i j ↦ (basisStalkFree I y).repr
        ((Y.stalkFunctor y).map φ (basisStalkFree J y j)) i).submatrix _root_.id σ := by
    ext i k
    exact (basisStalkFree_repr_stalkFunctor_map φ y (σ k) i).symm
  rw [← hM]
  exact RingHom.map_det _ _

variable {N : SheafOfModules.{u} Y.ringSheaf} (p : SheafOfModules.free I ⟶ N)

/-- **The maximal minors of a presentation matrix kill the stalks** of the presented sheaf. -/
theorem Γgerm_det_mem_annihilator [Fintype I] [Finite J] [Epi p] {y : Y}
    (hex : Function.Exact ((Y.stalkFunctor y).map φ) ((Y.stalkFunctor y).map p)) (σ : I → J) :
    Y.presheaf.Γgerm y ((freeHomMatrix φ).submatrix _root_.id σ).det ∈
      Module.annihilator (Y.presheaf.stalk y) ((Y.stalkFunctor y).obj N) := by
  refine (Γgerm_det_submatrix φ y σ) ▸ Module.det_submatrix_mem_annihilator (basisStalkFree I y)
    (fun j ↦ (Y.stalkFunctor y).map φ (basisStalkFree J y j)) ((Y.stalkFunctor y).map p).hom
    (surjective_stalk_of_epi p y) ?_ σ
  rw [Submodule.span_le]
  rintro _ ⟨j, rfl⟩
  exact hex.apply_apply_eq_zero _

/-- **Where the stalk of the presented sheaf vanishes, some maximal minor of the presentation
matrix is a unit.** -/
theorem exists_isUnit_Γgerm_det [Fintype I] [Finite J] {y : Y}
    (hex : Function.Exact ((Y.stalkFunctor y).map φ) ((Y.stalkFunctor y).map p))
    [Subsingleton ((Y.stalkFunctor y).obj N)] :
    ∃ σ : I → J, IsUnit (Y.presheaf.Γgerm y ((freeHomMatrix φ).submatrix _root_.id σ).det) := by
  haveI := Fintype.ofFinite J
  obtain ⟨σ, hσ⟩ := Module.exists_isUnit_det_submatrix (basisStalkFree I y)
    (fun j ↦ (Y.stalkFunctor y).map φ (basisStalkFree J y j)) ((Y.stalkFunctor y).map p).hom
    (by
      rw [LinearMap.exact_iff.mp hex]
      rintro _ ⟨w, rfl⟩
      rw [← (basisStalkFree J y).sum_repr w, map_sum]
      refine Submodule.sum_mem _ fun j _ ↦ ?_
      rw [map_smul]
      exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨j, rfl⟩))
  exact ⟨σ, (Γgerm_det_submatrix φ y σ) ▸ hσ⟩

end Presentation

end AlgebraicGeometry.LocallyRingedSpace

namespace ComplexAnalytic.AnalyticSpace

variable (Z : AnalyticSpace.{u})

/-- **Sections vanishing on the support of a finitely presented sheaf kill it up to a power**,
near every point, given a global finite presentation `𝒪^J → 𝒪^I → N → 0` (exact on stalks). -/
theorem exists_pow_mem_annihilator_of_presentation {N : SheafOfModules.{u} Z.ringSheaf}
    {I J : Type u} [Finite I] [Finite J]
    (φ : SheafOfModules.free (R := Z.ringSheaf) J ⟶ SheafOfModules.free I)
    (p : SheafOfModules.free I ⟶ N) [Epi p]
    (hex : ∀ y : Z, Function.Exact ((Z.stalkFunctor y).map φ) ((Z.stalkFunctor y).map p))
    {r : ℕ} (g : Fin r → Z.presheaf.obj (op ⊤))
    (hN : ∀ y : Z, (∃ i, Z.eval (U := ⊤) y trivial (g i) ≠ 0) →
      Subsingleton ((Z.stalkFunctor y).obj N))
    (x : Z) :
    ∃ U : Z.Opens, x ∈ U ∧ ∃ k : ℕ, ∀ y ∈ U, ∀ i, Z.presheaf.Γgerm y (g i) ^ k ∈
      Module.annihilator (Z.presheaf.stalk y) ((Z.stalkFunctor y).obj N) := by
  classical
  haveI := Fintype.ofFinite I
  haveI := Fintype.ofFinite J
  set e := Fintype.equivFin (I → J)
  set ψ : Fin (Fintype.card (I → J)) → Z.presheaf.obj (op ⊤) := fun m ↦
    ((LocallyRingedSpace.freeHomMatrix φ).submatrix _root_.id (e.symm m)).det with hψ
  have hψann : ∀ y m, Z.presheaf.Γgerm y (ψ m) ∈
      Module.annihilator (Z.presheaf.stalk y) ((Z.stalkFunctor y).obj N) := fun y m ↦
    LocallyRingedSpace.Γgerm_det_mem_annihilator φ p (hex y) _
  have hvan : ∀ i, ∀ y : Z, (∀ m, Z.eval (U := ⊤) y trivial (ψ m) = 0) →
      Z.eval (U := ⊤) y trivial (g i) = 0 := by
    intro i y hy
    by_contra hne
    haveI := hN y ⟨i, hne⟩
    obtain ⟨σ, hσ⟩ := LocallyRingedSpace.exists_isUnit_Γgerm_det φ p (hex y)
    have h1 := hy (e σ)
    rw [eval_apply] at h1
    refine (evalStalk_ne_zero_iff_isUnit (Z := Z)).2 ?_ h1
    have h2 : ψ (e σ) = ((LocallyRingedSpace.freeHomMatrix φ).submatrix _root_.id σ).det := by
      simp [hψ]
    rw [h2]
    exact hσ
  have hk : ∀ i, ∃ k, ∀ᶠ y in 𝓝 x, Z.presheaf.Γgerm y (g i) ^ k ∈
      Ideal.span (Set.range fun m ↦ Z.presheaf.Γgerm y (ψ m)) := by
    intro i
    obtain ⟨k, hk⟩ := Z.isNullstellensatzAt x ⊤ trivial ψ (g i)
      (Eventually.of_forall fun y _ h ↦ hvan i y h)
    refine ⟨k, ?_⟩
    have := TopCat.Presheaf.eventually_Γgerm_mem_span Z.presheaf (g i ^ k) ψ
      (by rw [map_pow]; exact hk)
    filter_upwards [this] with y hy
    rwa [map_pow] at hy
  choose k hk using hk
  have hall : ∀ᶠ y in 𝓝 x, ∀ i, Z.presheaf.Γgerm y (g i) ^ (∑ i, k i) ∈
      Module.annihilator (Z.presheaf.stalk y) ((Z.stalkFunctor y).obj N) := by
    filter_upwards [eventually_all.mpr hk] with y hy i
    refine Ideal.pow_mem_of_pow_mem (I := Module.annihilator _ _) ?_
      (Finset.single_le_sum (fun _ _ ↦ Nat.zero_le _) (Finset.mem_univ i))
    refine (Ideal.span_le.mpr ?_) (hy i)
    rintro _ ⟨m, rfl⟩
    exact hψann y m
  obtain ⟨U, hUt, hUo, hxU⟩ := mem_nhds_iff.mp hall
  exact ⟨⟨U, hUo⟩, hxU, ∑ i, k i, fun y hy ↦ hUt hy⟩


section Restrict

variable {X : AnalyticSpace.{u}} (U : X.Opens) (N : SheafOfModules.{u} X.ringSheaf)

/-- The germ of the restriction of a global section is the image of its germ under the stalk
map of the inclusion. -/
lemma Γgerm_resΓ (y : X.restrict U) (g : X.presheaf.obj (op ⊤)) :
    (X.restrict U).presheaf.Γgerm y (X.resΓ U g) =
      ((X.ofRestrict U).toLRSHom.stalkMap y).hom (X.presheaf.Γgerm y.1 g) :=
  (LocallyRingedSpace.stalkMap_germ_apply (X.ofRestrict U).toLRSHom ⊤ y trivial g).symm

/-- The value of the restriction of a global section is the value of the section. -/
lemma eval_resΓ (y : X.restrict U) (g : X.presheaf.obj (op ⊤)) :
    (X.restrict U).eval (U := ⊤) y trivial (X.resΓ U g) = X.eval (U := ⊤) y.1 trivial g :=
  eval_c_app (X.ofRestrict U).toLRSHom (X.ofRestrict U).isCLinear (U := ⊤) y trivial g

attribute [local instance] RingHomInvPair.of_ringEquiv in
/-- The annihilator of a stalk of the restriction of a sheaf of modules to an open subspace
corresponds to the annihilator of the stalk of the sheaf. -/
lemma stalkMap_mem_annihilator_iff (y : X.restrict U) (a : X.presheaf.stalk y.1) :
    ((X.ofRestrict U).toLRSHom.stalkMap y).hom a ∈ Module.annihilator _
        (((X.restrict U).stalkFunctor y).obj ((X.toLocallyRingedSpace.restrictModules U).obj N)) ↔
      a ∈ Module.annihilator _ ((X.stalkFunctor y.1).obj N) := by
  set σ := (X.toLocallyRingedSpace.ofRestrict U.isOpenEmbedding).stalkPullbackModulesSemilinearEquiv
    y N
  simp only [Module.mem_annihilator]
  constructor
  · intro h m
    exact σ.injective ((σ.map_smulₛₗ a m).trans ((h (σ m)).trans (map_zero σ).symm))
  · intro h m
    obtain ⟨m, rfl⟩ := σ.surjective m
    exact (σ.map_smulₛₗ a m).symm.trans ((congrArg σ (h m)).trans (map_zero σ))

/-- Vanishing of a stalk transfers to the restriction to an open subspace. -/
lemma subsingleton_stalk_restrict (y : X.restrict U)
    [Subsingleton ((X.stalkFunctor y.1).obj N)] :
    Subsingleton (((X.restrict U).stalkFunctor y).obj
      ((X.toLocallyRingedSpace.restrictModules U).obj N)) :=
  haveI : Subsingleton ((X.stalkFunctor
      ((X.toLocallyRingedSpace.ofRestrict U.isOpenEmbedding).base y)).obj N) := ‹_›
  LocallyRingedSpace.Hom.subsingleton_stalk_pullbackModules
    (X.toLocallyRingedSpace.ofRestrict U.isOpenEmbedding) y N

/-- **Powers of global sections killing the stalks near a point can be found on an open
subspace.** -/
theorem exists_pow_mem_annihilator_of_restrict {r : ℕ} (g : Fin r → X.presheaf.obj (op ⊤))
    {x : X} (hx : x ∈ U)
    (h : ∃ W : (X.restrict U).Opens, (⟨x, hx⟩ : X.restrict U) ∈ W ∧ ∃ k : ℕ, ∀ y ∈ W, ∀ i,
      (X.restrict U).presheaf.Γgerm y (X.resΓ U (g i)) ^ k ∈
        Module.annihilator ((X.restrict U).presheaf.stalk y)
          (((X.restrict U).stalkFunctor y).obj
            ((X.toLocallyRingedSpace.restrictModules U).obj N))) :
    ∃ W : X.Opens, x ∈ W ∧ ∃ k : ℕ, ∀ y ∈ W, ∀ i, X.presheaf.Γgerm y (g i) ^ k ∈
      Module.annihilator (X.presheaf.stalk y) ((X.stalkFunctor y).obj N) := by
  obtain ⟨W, hxW, k, hk⟩ := h
  refine ⟨LocallyRingedSpace.imOpen U W, LocallyRingedSpace.mem_imOpen U W hx hxW, k, ?_⟩
  rintro _ ⟨y, hyW, rfl⟩ i
  have := hk y hyW i
  rw [Γgerm_resΓ, ← map_pow] at this
  exact (stalkMap_mem_annihilator_iff U N y _).1 this

end Restrict


section PresentationExists

variable (Z : AnalyticSpace.{u})

/-- **Local finite presentations.** A coherent sheaf which is a quotient of `𝒪^I` has, on an open
neighbourhood `V` of every point, a finite presentation `𝒪^J → 𝒪^I → N|_V → 0`, exact on
stalks. -/
theorem exists_presentation_restrict {M : SheafOfModules.{u} Z.ringSheaf} [M.IsCoherent]
    {I : Type u} [Finite I] (π : SheafOfModules.free I ⟶ M) [Epi π] (z : Z) :
    ∃ (V : Z.Opens) (_ : z ∈ V) (J : Type u) (_ : Finite J)
      (φ : SheafOfModules.free (R := (Z.restrict V).ringSheaf) J ⟶ SheafOfModules.free I)
      (p : SheafOfModules.free I ⟶ (Z.toLocallyRingedSpace.restrictModules V).obj M),
      Epi p ∧ ∀ y : Z.restrict V,
        Function.Exact (((Z.restrict V).stalkFunctor y).map φ)
          (((Z.restrict V).stalkFunctor y).map p) := by
  haveI : (SheafOfModules.unit Z.ringSheaf).IsCoherent := Z.isCoherentStructureSheaf
  haveI : (SheafOfModules.free (R := Z.ringSheaf) I).IsCoherent :=
    SheafOfModules.IsCoherent.free I
  haveI : (kernel π).IsCoherent := SheafOfModules.IsCoherent.kernel π
  obtain ⟨V, hzV, J, _, π', _⟩ :=
    LocallyRingedSpace.exists_epi_free_restrictModules (kernel π) z
  haveI : PreservesFiniteLimits (Z.toLocallyRingedSpace.restrictModules V) :=
    (Z.toLocallyRingedSpace.ofRestrict V.isOpenEmbedding).preservesFiniteLimits_pullbackModules
      (LocallyRingedSpace.flat_stalkMap_of_isIso _)
  haveI : (Z.toLocallyRingedSpace.restrictModules V).IsLeftAdjoint :=
    (Z.toLocallyRingedSpace.ofRestrict V.isOpenEmbedding).pullbackModulesAdj.isLeftAdjoint
  haveI : PreservesColimits (Z.toLocallyRingedSpace.restrictModules V) :=
    (Z.toLocallyRingedSpace.ofRestrict
      V.isOpenEmbedding).pullbackModulesAdj.leftAdjoint_preservesColimits
  haveI := Functor.preservesZeroMorphisms_of_isLeftAdjoint
    (Z.toLocallyRingedSpace.restrictModules V)
  obtain ⟨η, hη⟩ : ∃ η, η =
      (Z.toLocallyRingedSpace.ofRestrict V.isOpenEmbedding).pullbackModulesFreeIso I :=
    ⟨_, rfl⟩
  have hS := (LocallyRingedSpace.shortExact_kernel π).map_of_exact
    (Z.toLocallyRingedSpace.restrictModules V)
  refine ⟨V, hzV, J, inferInstance,
    π' ≫ (Z.toLocallyRingedSpace.restrictModules V).map (kernel.ι π) ≫ η.hom,
    η.inv ≫ (Z.toLocallyRingedSpace.restrictModules V).map π, ?_, fun y ↦ ?_⟩
  · haveI : Epi ((Z.toLocallyRingedSpace.restrictModules V).map π) :=
      (Z.toLocallyRingedSpace.restrictModules V).map_epi π
    exact epi_comp _ _
  · have hex := LocallyRingedSpace.exact_stalk _ hS.exact y
    have hsurj := LocallyRingedSpace.surjective_stalk_of_epi π' y
    set S := (Z.restrict V).stalkFunctor y
    have hHH' : ∀ v, S.map η.hom (S.map η.inv v) = v := fun v ↦
      (S.mapIso η).toLinearEquiv.apply_symm_apply v
    have hH'H : ∀ v, S.map η.inv (S.map η.hom v) = v := fun v ↦
      (S.mapIso η).toLinearEquiv.symm_apply_apply v
    have hφ : ∀ w, S.map (π' ≫ (Z.toLocallyRingedSpace.restrictModules V).map (kernel.ι π) ≫
        η.hom) w = S.map η.hom (S.map ((Z.toLocallyRingedSpace.restrictModules V).map
          (kernel.ι π)) (S.map π' w)) := fun w ↦ by
      simp only [Functor.map_comp, ConcreteCategory.comp_apply]
    have hp : ∀ v, S.map (η.inv ≫ (Z.toLocallyRingedSpace.restrictModules V).map π) v =
        S.map ((Z.toLocallyRingedSpace.restrictModules V).map π) (S.map η.inv v) := fun v ↦ by
      simp only [Functor.map_comp, ConcreteCategory.comp_apply]
    intro v
    refine ⟨fun hv ↦ ?_, fun hv ↦ ?_⟩
    · obtain ⟨u, hu⟩ := (hex _).1 ((hp v).symm.trans hv)
      obtain ⟨w, rfl⟩ := hsurj u
      exact ⟨w, (hφ w).trans ((congrArg (S.map η.hom) hu).trans (hHH' v))⟩
    · obtain ⟨w, rfl⟩ := hv
      exact (hp _).trans ((congrArg (S.map ((Z.toLocallyRingedSpace.restrictModules V).map π))
        ((congrArg (S.map η.inv) (hφ w)).trans (hH'H _))).trans ((hex _).2 ⟨_, rfl⟩))

end PresentationExists


section Main

variable (X : AnalyticSpace.{u})

/-- **Sections vanishing on the support of a coherent sheaf kill it up to a power.** Let `N` be a
coherent sheaf on `X` and `g₁, …, g_r` global sections of `𝒪_X` such that `N_y = 0` whenever
some `gᵢ(y) ≠ 0`. Then every point has a neighbourhood `U` and an exponent `k` such that
`gᵢ^k` kills `N_y` for all `y ∈ U` and all `i`. -/
theorem exists_pow_mem_annihilator (N : SheafOfModules.{u} X.ringSheaf) [N.IsCoherent] {r : ℕ}
    (g : Fin r → X.presheaf.obj (op ⊤))
    (hN : ∀ y : X, (∃ i, X.eval (U := ⊤) y trivial (g i) ≠ 0) →
      Subsingleton ((X.stalkFunctor y).obj N))
    (x : X) :
    ∃ U : X.Opens, x ∈ U ∧ ∃ k : ℕ, ∀ y ∈ U, ∀ i, X.presheaf.Γgerm y (g i) ^ k ∈
      Module.annihilator (X.presheaf.stalk y) ((X.stalkFunctor y).obj N) := by
  obtain ⟨U₁, hxU₁, I, _, π, hπ⟩ := LocallyRingedSpace.exists_epi_free_restrictModules N x
  refine exists_pow_mem_annihilator_of_restrict U₁ N g hxU₁ ?_
  have hcoh : ((X.toLocallyRingedSpace.restrictModules U₁).obj N).IsCoherent :=
    LocallyRingedSpace.isCoherent_restrictModules N U₁
  obtain ⟨U₂, hxU₂, J, _, φ, p, hp, hex⟩ := @exists_presentation_restrict (X.restrict U₁)
    ((X.toLocallyRingedSpace.restrictModules U₁).obj N) hcoh I _ π hπ ⟨x, hxU₁⟩
  refine exists_pow_mem_annihilator_of_restrict U₂ _ (fun i ↦ X.resΓ U₁ (g i)) hxU₂ ?_
  refine @exists_pow_mem_annihilator_of_presentation _ _ I J _ _ φ p hp hex _ _ ?_ _
  rintro y ⟨i, hi⟩
  rw [eval_resΓ, eval_resΓ] at hi
  haveI := hN y.1.1 ⟨i, hi⟩
  haveI := subsingleton_stalk_restrict U₁ N y.1
  exact subsingleton_stalk_restrict U₂ _ y

/-- **Sections vanishing on the support of a coherent sheaf kill it up to a power**, in ideal
form: if `N_y = 0` whenever some `gᵢ(y) ≠ 0`, then every point has a neighbourhood `U` and an
exponent `k` such that `(g₁, …, g_r)^k` kills `N_y` for all `y ∈ U`. -/
theorem exists_pow_le_annihilator (N : SheafOfModules.{u} X.ringSheaf) [N.IsCoherent] {r : ℕ}
    (g : Fin r → X.presheaf.obj (op ⊤))
    (hN : ∀ y : X, (∃ i, X.eval (U := ⊤) y trivial (g i) ≠ 0) →
      Subsingleton ((X.stalkFunctor y).obj N))
    (x : X) :
    ∃ U : X.Opens, x ∈ U ∧ ∃ k : ℕ, ∀ y ∈ U,
      Ideal.span (Set.range fun i ↦ X.presheaf.Γgerm y (g i)) ^ k ≤
        Module.annihilator (X.presheaf.stalk y) ((X.stalkFunctor y).obj N) := by
  obtain ⟨U, hxU, k, hk⟩ := exists_pow_mem_annihilator X N g hN x
  exact ⟨U, hxU, r * k + 1, fun y hy ↦
    Ideal.span_range_pow_le_of_forall_pow_mem _ fun i ↦ hk y hy i⟩

/-- **A section vanishing on the support of a coherent sheaf kills it up to a power**: if
`N_y = 0` wherever `g(y) ≠ 0`, then every point has a neighbourhood `U` and an exponent `k` such
that `g^k` kills `N_y` for all `y ∈ U`. -/
theorem exists_pow_smul_eq_zero (N : SheafOfModules.{u} X.ringSheaf) [N.IsCoherent]
    (g : X.presheaf.obj (op ⊤))
    (hN : ∀ y : X, X.eval (U := ⊤) y trivial g ≠ 0 → Subsingleton ((X.stalkFunctor y).obj N))
    (x : X) :
    ∃ U : X.Opens, x ∈ U ∧ ∃ k : ℕ, ∀ y ∈ U, ∀ m : (X.stalkFunctor y).obj N,
      X.presheaf.Γgerm y g ^ k • m = 0 := by
  obtain ⟨U, hxU, k, hk⟩ := exists_pow_mem_annihilator X N (fun _ : Fin 1 ↦ g)
    (fun y ⟨_, hy⟩ ↦ hN y hy) x
  exact ⟨U, hxU, k, fun y hy m ↦ Module.mem_annihilator.mp (hk y hy 0) m⟩

end Main

end ComplexAnalytic.AnalyticSpace
