/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.AnalyticSpace.PullbackCoherent
import Oka.AnalyticSpace.ZeroLocus
import Oka.Geometry.RingedSpace.LocallyRingedSpace.ModulesClosedEmbeddingKilled

/-!
# Sheaves of modules killed by functions come from the zero locus

Let `i : Z ⟶ Y` cut out `Z` by global sections `f₁, …, f_k` of `𝒪_Y`
(`ComplexAnalytic.IsCutOutBy`), e.g. the inclusion of the zero locus
`ComplexAnalytic.AnalyticSpace.zeroLocusSubspace X f` of global sections of an analytic space.
A sheaf of `𝒪_Y`-modules `A` is *killed by the `f_j`* if multiplication by each `f_j`
(`AlgebraicGeometry.LocallyRingedSpace.modulesSMul`) is the zero endomorphism of `A`.

- The ideal of `Z` at `y` is generated by the germs of the `f_j`
  (`ComplexAnalytic.IsCutOutBy.pushforwardStalkIdeal_le`).
- **`A` is killed by the `f_j` if and only if the unit `A ⟶ i_* i^* A` is an isomorphism**
  (`ComplexAnalytic.IsCutOutBy.isIso_pullbackModulesAdj_unit_app_iff`,
  `ComplexAnalytic.IsCutOutBy.unitIso`); every pushforward `i_* G` is killed by the `f_j`
  (`ComplexAnalytic.IsCutOutBy.modulesSMul_pushforward_eq_zero`).
- For such `A`, `Hᵠ(Y, A) ≃ Hᵠ(Z, i^* A)` (`ComplexAnalytic.IsCutOutBy.HAddEquiv`).
- If `Z` is an analytic space and `A` is coherent, `i^* A` is coherent
  (`ComplexAnalytic.isCoherent_pullbackModules_of_isCoherent`); in particular for the zero locus of
  global sections of an analytic space
  (`ComplexAnalytic.AnalyticSpace.isCoherent_pullbackModules_zeroLocusSubspaceι`).
-/

open CategoryTheory TopologicalSpace Opposite Limits AlgebraicGeometry

universe u

noncomputable section

namespace ComplexAnalytic

variable {Z Y : LocallyRingedSpace.{u}} {i : Z ⟶ Y} {k : ℕ} {f : Fin k → Y.presheaf.obj (op ⊤)}

/-- **The ideal of a cut-out subspace is generated by the cutting sections, stalkwise**: at every
point `y`, the kernel of `𝒪_{Y,y} → (i_* 𝒪_Z)_y` lies in the ideal generated by the germs of the
`f_j` (off `Z` the germs generate the unit ideal). -/
theorem IsCutOutBy.pushforwardStalkIdeal_le (hcut : IsCutOutBy i f) (y : Y) :
    i.pushforwardStalkIdeal y ≤ Ideal.span (Set.range fun j ↦ Y.presheaf.Γgerm y (f j)) := by
  by_cases hy : y ∈ Set.range i.base
  · obtain ⟨x, rfl⟩ := hy
    rw [i.pushforwardStalkIdeal_eq_ker hcut.isClosedEmbedding.isInducing x, hcut.ker_stalkMap x]
  · have hy' : ¬ ∀ j, Y.presheaf.Γgerm y (f j) ∈ IsLocalRing.maximalIdeal _ := fun h ↦
      hy (by rw [hcut.range_base]; exact h)
    obtain ⟨j, hj⟩ := not_forall.1 hy'
    rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff, not_not] at hj
    have hmem : Y.presheaf.Γgerm y (f j) ∈
        Ideal.span (Set.range fun j ↦ Y.presheaf.Γgerm y (f j)) := Ideal.subset_span ⟨j, rfl⟩
    rw [Ideal.eq_top_of_isUnit_mem _ hmem hj]
    exact le_top

/-- If multiplication by every `f_j` is zero on `A`, the ideal of the cut-out subspace kills every
stalk of `A`. -/
theorem IsCutOutBy.smul_eq_zero_of_mem_pushforwardStalkIdeal (hcut : IsCutOutBy i f)
    (A : SheafOfModules.{u} Y.ringSheaf) (hA : ∀ j, LocallyRingedSpace.modulesSMul A (f j) = 0)
    (y : Y) (r : Y.presheaf.stalk y) (hr : r ∈ i.pushforwardStalkIdeal y)
    (m : (Y.stalkFunctor y).obj A) : r • m = 0 :=
  LocallyRingedSpace.smul_eq_zero_of_mem_span _
    (fun j ↦ LocallyRingedSpace.Γgerm_smul_eq_zero_of_modulesSMul_eq_zero A (f j) (hA j) y)
    (hcut.pushforwardStalkIdeal_le y hr) m

/-- **Sheaves killed by the cutting sections are pushforwards from the zero locus**: if
multiplication by every `f_j` is zero on `A`, the unit `A ⟶ i_* i^* A` is an isomorphism. -/
theorem IsCutOutBy.isIso_pullbackModulesAdj_unit_app (hcut : IsCutOutBy i f)
    (A : SheafOfModules.{u} Y.ringSheaf) (hA : ∀ j, LocallyRingedSpace.modulesSMul A (f j) = 0) :
    IsIso (i.pullbackModulesAdj.unit.app A) :=
  i.isIso_pullbackModulesAdj_unit_app_of_smul_eq_zero hcut.isClosedEmbedding
    hcut.surjective_stalkMap A (hcut.smul_eq_zero_of_mem_pushforwardStalkIdeal A hA)

/-- The isomorphism `A ≅ i_* i^* A` for a sheaf `A` killed by the cutting sections. -/
def IsCutOutBy.unitIso (hcut : IsCutOutBy i f) (A : SheafOfModules.{u} Y.ringSheaf)
    (hA : ∀ j, LocallyRingedSpace.modulesSMul A (f j) = 0) :
    A ≅ (SheafOfModules.pushforward.{u} i.toRingSheafHom).obj (i.pullbackModules.obj A) :=
  i.unitIsoOfSMulEqZero hcut.isClosedEmbedding hcut.surjective_stalkMap A
    (hcut.smul_eq_zero_of_mem_pushforwardStalkIdeal A hA)

/-- The isomorphism `A ≅ i_* i^* A` is the unit of `i^* ⊣ i_*`. -/
@[simp]
lemma IsCutOutBy.unitIso_hom (hcut : IsCutOutBy i f) (A : SheafOfModules.{u} Y.ringSheaf)
    (hA : ∀ j, LocallyRingedSpace.modulesSMul A (f j) = 0) :
    (hcut.unitIso A hA).hom = i.pullbackModulesAdj.unit.app A :=
  rfl

/-- Multiplication by a cutting section is zero on every pushforward `i_* G`. -/
theorem IsCutOutBy.modulesSMul_pushforward_eq_zero (hcut : IsCutOutBy i f)
    (G : SheafOfModules.{u} Z.ringSheaf) (j : Fin k) :
    LocallyRingedSpace.modulesSMul
      ((SheafOfModules.pushforward.{u} i.toRingSheafHom).obj G) (f j) = 0 :=
  LocallyRingedSpace.modulesSMul_pushforward_eq_zero i G (f j) (hcut.c_app_eq_zero j)

/-- **Characterisation of pushforwards from a cut-out subspace**: the unit `A ⟶ i_* i^* A` is an
isomorphism if and only if multiplication by every cutting section is zero on `A`. -/
theorem IsCutOutBy.isIso_pullbackModulesAdj_unit_app_iff (hcut : IsCutOutBy i f)
    (A : SheafOfModules.{u} Y.ringSheaf) :
    IsIso (i.pullbackModulesAdj.unit.app A) ↔
      ∀ j, LocallyRingedSpace.modulesSMul A (f j) = 0 := by
  refine ⟨fun _ j ↦ ?_, hcut.isIso_pullbackModulesAdj_unit_app A⟩
  have h := LocallyRingedSpace.modulesSMul_naturality (i.pullbackModulesAdj.unit.app A) (f j)
  have h0 := hcut.modulesSMul_pushforward_eq_zero (i.pullbackModules.obj A) j
  erw [h0, comp_zero] at h
  exact (cancel_mono (i.pullbackModulesAdj.unit.app A)).1 (h.symm.trans zero_comp.symm)

/-- For a sheaf `A` killed by the cutting sections, `Hᵠ(Y, A) ≃ Hᵠ(Z, i^* A)`. -/
def IsCutOutBy.HAddEquiv (hcut : IsCutOutBy i f) (A : SheafOfModules.{u} Y.ringSheaf)
    (hA : ∀ j, LocallyRingedSpace.modulesSMul A (f j) = 0) (q : ℕ) :
    LocallyRingedSpace.H A q ≃+ LocallyRingedSpace.H (i.pullbackModules.obj A) q :=
  i.HAddEquivOfSMulEqZero hcut.isClosedEmbedding hcut.surjective_stalkMap A
    (hcut.smul_eq_zero_of_mem_pushforwardStalkIdeal A hA) q

namespace AnalyticSpace

variable (X : AnalyticSpace.{u}) {p : ℕ} (s : Fin p → X.presheaf.obj (op ⊤))

/-- **Coherent sheaves killed by `s` are pushforwards of coherent sheaves on the zero locus**: for
a coherent `A` on `X` killed by the `s_j`, `A ≅ ι_* ι^* A` with `ι^* A` coherent on the zero
locus `Z(s)`. -/
theorem isCoherent_pullbackModules_zeroLocusSubspaceι
    (A : SheafOfModules.{u} X.toLocallyRingedSpace.ringSheaf) [A.IsCoherent] :
    ((zeroLocusSubspaceι X s).toLRSHom.pullbackModules.obj A).IsCoherent :=
  isCoherent_pullbackModules_of_isCoherent (Z := zeroLocusSubspace X s) _ A

end AnalyticSpace

end ComplexAnalytic
