/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.Analytic.HartogsRegularCoord
import Oka.Analytification.RET.ES.Codim2.ChartModule
import Oka.Analytification.RET.ES.Codim2.NormalCrossingsLocal
import Oka.Analytification.RET.ES.ReflexiveHull

/-!
# Local coherence of bounded sections from local data

Keep the notation of `Oka/Analytification/RET/ES/ReflexiveHull.lean`. This file packages the
pointwise form of the reflexive hull criterion: if near `x` there are a family of regular pairs
with zero set `Z ⊇ S` and sections of `𝒜` spanning local bases at all points off `S`, then `𝒜`
satisfies the local conditions for coherence at `x`
(`ComplexAnalytic.BoundedSections.isCoherentAt_of_criterion`). The local conditions also hold if
`𝒜` is free near `x` (`ComplexAnalytic.BoundedSections.isCoherentAt_of_isFreeSpanAt`), e.g. if
near `x` the complement of `N°` is a union of coordinate hyperplanes in holomorphic coordinates
`Φ : ℂⁿ ⊇ O ≅ O' ⊆ ℂⁿ` (`ComplexAnalytic.BoundedSections.exists_isFreeSpanAt_of_coords`).

## Main results

- `ComplexAnalytic.BoundedSections.isCoherentAt_of_criterion`: the pointwise reflexive hull
  criterion.
- `ComplexAnalytic.BoundedSections.isCoherentAt_of_isFreeSpanAt`: local coherence from local
  freeness.
- `ComplexAnalytic.BoundedSections.exists_isFreeSpanAt_of_coords`: freeness at normal crossings
  in coordinates of `ℂⁿ`.
-/

open CategoryTheory Opposite AlgebraicGeometry Topology TopologicalSpace Filter Set

universe u

namespace ComplexAnalytic.BoundedSections

open AnalyticSpace AlgebraicGeometry.LocallyRingedSpace

noncomputable section

variable {n : ℕ} {N N₀ : (AnalyticSpace.complexAffineSpace.{u} n).Opens} (h₀ : N₀ ≤ N)
  (W : FiniteEtaleOver (space N₀))

/-! ### The pointwise criterion -/

/-- **The pointwise reflexive hull criterion.** -/
theorem isCoherentAt_of_reflexiveHullData {U : (space N).Opens}
    (D : ReflexiveHullData (boundedModule h₀ W) U) {x : space N} (hx : x ∈ U) :
    IsCoherentAt h₀ W x := by
  have hO := (space N).hasLocalTupleRelations_unit
  refine ⟨?_, fun V k f hxV ↦ D.exists_relations_of_mem hO f hxV hx⟩
  obtain ⟨L⟩ := D.nonempty_localData hO hx
  obtain ⟨k, t, ht⟩ := L.exists_generators
  exact ⟨L.W, k, t, L.mem, ht⟩

/-- **Local coherence from local freeness.** If `𝒜` is free near `x`, then its sections are
generated by a local basis near `x`, and relations between sections are the relations between
their coordinate tuples, which are locally finitely generated by Oka's theorem. -/
theorem isCoherentAt_of_isFreeSpanAt {U : (space N).Opens} {m : ℕ}
    {s : Fin m → (boundedModule h₀ W).val.obj (op U)} {x : space N}
    (hfree : IsFreeSpanAt h₀ W s x) : IsCoherentAt h₀ W x := by
  obtain ⟨V, -, r, e, -, hxV, -, hspan, hindep⟩ := hfree
  refine ⟨⟨V, r, e, hxV, fun W' hW' t y hy ↦ ?_⟩,
    hasLocalModuleRelationsAt_of_le V hxV fun V₁ hV₁ q f hxV₁ ↦ ?_⟩
  · obtain ⟨c, hc⟩ := hspan W' hW' t
    refine ⟨W', le_rfl, hy, fun k ↦ (space N).res le_rfl (c k), ?_⟩
    subst hc
    rw [sectRes_sum_smul]
    refine Finset.sum_congr rfl fun k _ ↦ ?_
    rw [sectRes_sectRes]
  · have hO := (space N).hasLocalTupleRelations_unit
    choose c hc using fun i ↦ hspan V₁ hV₁ (f i)
    obtain ⟨W₁, hW₁, p, g, hxW₁, hg, hgen⟩ := ReflexiveHullData.exists_tuple_relations hO c hxV₁
    have hexp : ∀ (W' : (space N).Opens) (hW' : W' ≤ V₁) (a : Fin q → (space N).presheaf.obj
        (op W')), ∑ i, a i • sectRes (boundedModule h₀ W) hW' (f i) =
          ∑ k, (∑ i, a i * (space N).res hW' (c i k)) •
            sectRes (boundedModule h₀ W) (hW'.trans hV₁) (e k) := by
      intro W' hW' a
      simp only [hc, sectRes_sum_smul, sectRes_sectRes, Finset.smul_sum, Finset.sum_smul,
        mul_smul]
      exact Finset.sum_comm
    refine ⟨W₁, hW₁, p, g, hxW₁, fun l ↦ ?_, fun W' hW' a ha y hy ↦ ?_⟩
    · rw [hexp W₁ hW₁]
      refine Finset.sum_eq_zero fun k _ ↦ ?_
      rw [hg l k, zero_smul]
    · have hrel : ∀ k, ∑ i, a i * (space N).res (hW'.trans hW₁) (c i k) = 0 := by
        rw [hexp W' (hW'.trans hW₁)] at ha
        exact hindep W' ((hW'.trans hW₁).trans hV₁) _ ha
      exact hgen W' hW' a hrel y hy

section Criterion

variable [T2Space W.left] (hD : HasThinComplement N N₀)
include hD

/-- **Local coherence from local bases off the zero set of regular pairs.** Let `P` be a family
of regular pairs on an open `U ∋ x` whose zero set contains `S`, and let `s₁, …, s_m ∈ 𝒜(U)` span
local bases of `𝒜` at all points of `U ∖ S`. Then `𝒜` satisfies the local conditions for
coherence at `x`. -/
theorem isCoherentAt_of_criterion {U : (space N).Opens}
    (P : RegularPairFamily (img U : Set (Cn.{u} n))) {S : Set (Cn.{u} n)} {m : ℕ}
    (s : Fin m → (boundedModule h₀ W).val.obj (op U)) {x : space N} (hx : x ∈ U)
    (hS : S ⊆ P.zeroSet) (hfree : ∀ y ∈ U, y.1 ∉ S → IsFreeSpanAt h₀ W s y) :
    IsCoherentAt h₀ W x :=
  isCoherentAt_of_reflexiveHullData h₀ W (reflexiveHullData h₀ W hD P s hS hfree) hx

end Criterion

/-! ### Normal crossings in coordinates of `ℂⁿ` -/

/-- The splitting of `ℂⁿ` into the coordinates off a finite set `J` and those in `J`. -/
def coordSplit (J : Finset (ULift.{u} (Fin n))) (x : Cn.{u} n) :
    ({j // j ∉ J} → ℂ) × (Fin J.card → ℂ) :=
  (fun j ↦ x j, fun i ↦ x (J.equivFin.symm i))

/-- The inverse of `ComplexAnalytic.BoundedSections.coordSplit`. -/
def coordJoin (J : Finset (ULift.{u} (Fin n))) (p : ({j // j ∉ J} → ℂ) × (Fin J.card → ℂ)) :
    Cn.{u} n :=
  fun j ↦ if h : j ∈ J then p.2 (J.equivFin ⟨j, h⟩) else p.1 ⟨j, h⟩

lemma coordJoin_coordSplit (J : Finset (ULift.{u} (Fin n))) (x : Cn.{u} n) :
    coordJoin J (coordSplit J x) = x := by
  funext j
  by_cases h : j ∈ J <;> simp [coordJoin, coordSplit, h]

lemma coordSplit_coordJoin (J : Finset (ULift.{u} (Fin n)))
    (p : ({j // j ∉ J} → ℂ) × (Fin J.card → ℂ)) : coordSplit J (coordJoin J p) = p := by
  refine Prod.ext (funext fun j ↦ ?_) (funext fun i ↦ ?_)
  · simp [coordSplit, coordJoin, j.2]
  · simp [coordSplit, coordJoin]

lemma differentiable_coordSplit (J : Finset (ULift.{u} (Fin n))) :
    Differentiable ℂ (coordSplit J) := by
  unfold coordSplit
  fun_prop

lemma differentiable_coordJoin (J : Finset (ULift.{u} (Fin n))) :
    Differentiable ℂ (coordJoin J) := by
  refine differentiable_pi.2 fun j ↦ ?_
  by_cases h : j ∈ J
  · simp only [coordJoin, dif_pos h]
    fun_prop
  · simp only [coordJoin, dif_neg h]
    fun_prop

variable [T2Space W.left] in
/-- **`𝒜` is free near a normal crossings point, in coordinates of `ℂⁿ`.** Let `Φ` be holomorphic
on an open `O ⊆ N` with holomorphic inverse `Φ'` on an open `O'`, such that `x ∈ N°` if and only
if the coordinates `j ∈ J` of `Φ(x)` are nonzero, and let `x₀ ∈ O` with `Φ(x₀)ⱼ = 0` for
`j ∈ J`. Then `𝒜` is free near every point of a neighbourhood of `x₀`. -/
theorem exists_isFreeSpanAt_of_coords {O : Set (Cn.{u} n)} (hO : IsOpen O)
    (hON : ∀ x ∈ O, x ∈ N) {O' : Set (Cn.{u} n)} (hO' : IsOpen O') {Φ Φ' : Cn.{u} n → Cn.{u} n}
    (hΦ : DifferentiableOn ℂ Φ O) (hΦ' : DifferentiableOn ℂ Φ' O') (hmaps : MapsTo Φ O O')
    (hmaps' : MapsTo Φ' O' O) (hleft : ∀ x ∈ O, Φ' (Φ x) = x) (hright : ∀ z ∈ O', Φ (Φ' z) = z)
    (J : Finset (ULift.{u} (Fin n))) (hmem : ∀ x ∈ O, x ∈ N₀ ↔ ∀ j ∈ J, Φ x j ≠ 0)
    {x₀ : Cn.{u} n} (hx₀ : x₀ ∈ O) (hx₀0 : ∀ j ∈ J, Φ x₀ j = 0) :
    ∃ (U : (space N).Opens) (k : ℕ) (e : Fin k → (boundedModule h₀ W).val.obj (op U)),
      x₀ ∈ img U ∧ ∀ y ∈ U, IsFreeSpanAt h₀ W e y := by
  refine exists_isFreeSpanAt_of_local h₀ W hO hON (O' := coordJoin J ⁻¹' O')
    (hO'.preimage (differentiable_coordJoin J).continuous) (Φ := fun x ↦ coordSplit J (Φ x))
    (Φ' := fun p ↦ Φ' (coordJoin J p))
    ((differentiable_coordSplit J).comp_differentiableOn hΦ)
    (hΦ'.comp (differentiable_coordJoin J).differentiableOn fun p hp ↦ hp)
    (fun x hx ↦ by simpa [mem_preimage, coordJoin_coordSplit] using hmaps hx)
    (fun p hp ↦ hmaps' hp) (fun x hx ↦ by simp [coordJoin_coordSplit, hleft x hx])
    (fun p hp ↦ by simp [hright _ hp, coordSplit_coordJoin]) (fun x hx ↦ ?_) hx₀ fun i ↦ ?_
  · rw [hmem x hx]
    refine ⟨fun h i ↦ h _ (J.equivFin.symm i).2, fun h j hj ↦ ?_⟩
    have := h (J.equivFin ⟨j, hj⟩)
    simpa [coordSplit] using this
  · exact hx₀0 _ (J.equivFin.symm i).2

end

end ComplexAnalytic.BoundedSections
