/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.Analytification.RET.ES.Codim2.BlowupSheaf
import Oka.Analytification.RET.ES.Codim2.ContactOrder
import Oka.Geometry.RingedSpace.LocallyRingedSpace.CoherentPushforwardClosedEmbedding

/-!
# Pushforward along holomorphic embeddings with a holomorphic retraction

Let `A ⊆ ℂⁿ` and `B ⊆ ℂᵐ` be open and let `Γ : A → B` be holomorphic with a holomorphic
retraction `L : B → A`, `L ∘ Γ = id`. Suppose moreover that there is a holomorphic function `h`
on `B` and a holomorphic map `Θ` on an open subset of `A × ℂ` with `Θ(a, 0) = Γ(a)` and
`Θ(L(p), h(p)) = p` (`ComplexAnalytic.BoundedSections.GraphEmbeddingData`): in the coordinates
`(L, h)` the image of `Γ` is the hyperplane `h = 0`. This is the situation of a graph, and of the
charts of a blow-up.

Then the morphism `Γ : A ⟶ B` of analytic spaces (`…GraphEmbeddingData.hom`) is a closed
embedding with surjective stalk maps (via `L`) whose ideal is generated by `h`: a function
vanishing on the image of `Γ` near a point is `h` times a holomorphic function
(`Codim2.exists_eq_mul_of_apply_zero` in the coordinates `(L, h)`). Hence pushing forward along
`Γ` preserves coherence (`…GraphEmbeddingData.isCoherent_pushforward`).

## Main definitions

- `ComplexAnalytic.BoundedSections.GraphEmbeddingData A B`: the data `Γ`, `L`, `h`, `Θ`.
- `ComplexAnalytic.BoundedSections.GraphEmbeddingData.hom`: `Γ` as a morphism of analytic spaces.

## Main results

- `ComplexAnalytic.BoundedSections.GraphEmbeddingData.isCoherent_pushforward`: `Γ_*` preserves
  coherence.
-/

open CategoryTheory Opposite AlgebraicGeometry Topology TopologicalSpace Filter

universe u

namespace ComplexAnalytic.BoundedSections

open AnalyticSpace AlgebraicGeometry.LocallyRingedSpace

noncomputable section

variable {n m : ℕ} (A : (AnalyticSpace.complexAffineSpace.{u} n).Opens)
  (B : (AnalyticSpace.complexAffineSpace.{u} m).Opens)

/-- **A holomorphic embedding `Γ : A → B` with retraction `L`**, whose image is the hyperplane
`h = 0` in the coordinates `(L, h)`: `Θ(a, 0) = Γ(a)` and `Θ(L(p), h(p)) = p`. -/
structure GraphEmbeddingData where
  /-- The embedding. -/
  Γ : Cn.{u} n → Cn.{u} m
  /-- The retraction. -/
  L : Cn.{u} m → Cn.{u} n
  /-- The equation of the image. -/
  h : Cn.{u} m → ℂ
  /-- The inverse of the coordinates `(L, h)`. -/
  Θ : Cn.{u} n × ℂ → Cn.{u} m
  /-- The domain of `Θ`. -/
  domΘ : Set (Cn.{u} n × ℂ)
  isOpen_domΘ : IsOpen domΘ
  differentiableOn_Γ : DifferentiableOn ℂ Γ {a : Cn.{u} n | a ∈ A}
  differentiableOn_L : DifferentiableOn ℂ L {p : Cn.{u} m | p ∈ B}
  differentiableOn_h : DifferentiableOn ℂ h {p : Cn.{u} m | p ∈ B}
  differentiableOn_Θ : DifferentiableOn ℂ Θ domΘ
  Γ_mem : ∀ a ∈ A, Γ a ∈ B
  L_mem : ∀ p ∈ B, L p ∈ A
  L_Γ : ∀ a ∈ A, L (Γ a) = a
  h_Γ : ∀ a ∈ A, h (Γ a) = 0
  mem_domΘ : ∀ p ∈ B, (L p, h p) ∈ domΘ
  Θ_zero : ∀ a ∈ A, Θ (a, 0) = Γ a
  Θ_L : ∀ p ∈ B, Θ (L p, h p) = p

namespace GraphEmbeddingData

variable {A B} (G : GraphEmbeddingData A B)

/-- The coordinates of `Γ`, as holomorphic functions on `A`. -/
def coord (k : ULift.{u} (Fin m)) : (space A).presheaf.obj (op ⊤) :=
  OkaRing.ofDifferentiableOn (fun a ↦ G.Γ a k)
    (((differentiableOn_pi.1 G.differentiableOn_Γ) k).mono fun a ha ↦
      (mem_functor_obj_top_iff A a).1 ha)

lemma okaMapOpen_base (a : space A) :
    (okaMapOpen G.coord).toLRSHom.base a = G.Γ a.1 := by
  change okaMapOpenFun G.coord a.1 = _
  funext k
  exact OkaRing.toGlobalFun_apply (U := img (⊤ : (space A).Opens)) _
    ((mem_functor_obj_top_iff A a.1).2 a.2)

lemma range_subset : Set.range (okaMapOpen G.coord).toLRSHom.base ⊆ (B : Set _) := by
  rintro _ ⟨a, rfl⟩
  rw [okaMapOpen_base]
  exact G.Γ_mem _ a.2

/-- **`Γ` as a morphism of analytic spaces `A ⟶ B`.** -/
def hom : space A ⟶ space B :=
  AnalyticSpace.liftRestrict (okaMapOpen G.coord) B G.range_subset

lemma hom_base (a : space A) : (G.hom.toLRSHom.base a).1 = G.Γ a.1 :=
  (congrArg (fun φ ↦ φ.toLRSHom.base a) (AnalyticSpace.liftRestrict_fac _ B G.range_subset)).trans
    (G.okaMapOpen_base a)

/-- The retraction `L`, as a map of points `B → A`. -/
def retr (p : space B) : space A :=
  ⟨G.L p.1, G.L_mem _ p.2⟩

lemma continuous_retr : Continuous G.retr :=
  (G.differentiableOn_L.continuousOn.comp_continuous continuous_subtype_val
    fun p ↦ p.2).subtype_mk _

lemma retr_hom (a : space A) : G.retr (G.hom.toLRSHom.base a) = a :=
  Subtype.ext (by simp only [retr, hom_base, G.L_Γ _ a.2])

/-- **`Γ` is a closed embedding.** -/
theorem isClosedEmbedding_hom : IsClosedEmbedding G.hom.toLRSHom.base :=
  Function.LeftInverse.isClosedEmbedding (f := G.retr) G.retr_hom G.continuous_retr
    G.hom.toLRSHom.base.hom.continuous

lemma eval_c_app_hom {V : (space B).Opens} (s : (space B).presheaf.obj (op V)) (a : space A)
    (ha : a ∈ (Opens.map G.hom.toLRSHom.base).obj V) :
    (space A).eval a ha (G.hom.toLRSHom.c.app (op V) s) = holFun s (G.Γ a.1) := by
  rw [eval_c_app G.hom.toLRSHom G.hom.isCLinear a ha s, eval_space, hom_base]

/-- **The stalk maps of `Γ` are surjective**: a germ `f` at `a` is the pullback of `f ∘ L`. -/
theorem surjective_stalkMap (x : space A) :
    Function.Surjective (G.hom.toLRSHom.stalkMap x) := by
  intro g
  obtain ⟨U, hxU, s, rfl⟩ := TopCat.Presheaf.exists_germ_eq _ g
  let V : (space B).Opens := ⟨G.retr ⁻¹' U, U.isOpen.preimage G.continuous_retr⟩
  have hV : ∀ p ∈ img V, p ∈ B ∧ G.L p ∈ img U := by
    intro p hp
    obtain ⟨hpB, hpV⟩ := mem_img_iff.1 hp
    exact ⟨hpB, mem_img_iff.2 ⟨_, hpV⟩⟩
  have hd : DifferentiableOn ℂ (fun p ↦ holFun s (G.L p)) (img V) := fun p hp ↦
    (((differentiableOn_holFun s) _ (hV p hp).2).differentiableAt
      ((img U).isOpen.mem_nhds (hV p hp).2)).comp_differentiableWithinAt p
      ((G.differentiableOn_L p (hV p hp).1).mono fun q hq ↦ (hV q hq).1)
  have hxV : G.hom.toLRSHom.base x ∈ V := by
    change G.retr (G.hom.toLRSHom.base x) ∈ U
    rw [retr_hom]
    exact hxU
  refine ⟨(space B).presheaf.germ V _ hxV (OkaRing.ofDifferentiableOn _ hd), ?_⟩
  rw [LocallyRingedSpace.stalkMap_germ_apply]
  have hx' : x ∈ (Opens.map G.hom.toLRSHom.base).obj V ⊓ U := ⟨hxV, hxU⟩
  rw [← TopCat.Presheaf.germ_res_apply _ (homOfLE inf_le_left) x hx',
    ← TopCat.Presheaf.germ_res_apply _ (homOfLE inf_le_right) x hx']
  congr 1
  refine eq_of_forall_eval_eq_restrict A fun a ha ↦ ?_
  rw [eval_presheaf_map, eval_presheaf_map, eval_c_app_hom, eval_space,
    holFun_ofDifferentiableOn hd (mem_img_iff.2 ⟨G.Γ_mem _ a.2, by
      have := ha.1
      change G.hom.toLRSHom.base a ∈ V at this
      exact (Subtype.ext (G.hom_base a).symm : (⟨G.Γ a.1, _⟩ : space B) = _) ▸ this⟩),
    G.L_Γ _ a.2]

/-- The equation `h` of the image, as a holomorphic function on `B`. -/
def hSec : (space B).presheaf.obj (op ⊤) :=
  OkaRing.ofDifferentiableOn G.h (G.differentiableOn_h.mono fun p hp ↦
    (mem_functor_obj_top_iff B p).1 hp)

lemma holFun_hSec {p : Cn.{u} m} (hp : p ∈ B) : holFun G.hSec p = G.h p :=
  holFun_ofDifferentiableOn _ ((mem_functor_obj_top_iff B p).2 hp)

lemma mem_range_hom_of_h_eq_zero (p : space B) (hp : G.h p.1 = 0) :
    p ∈ Set.range G.hom.toLRSHom.base := by
  refine ⟨G.retr p, Subtype.ext ?_⟩
  rw [hom_base, retr]
  simp only
  rw [← G.Θ_zero _ (G.L_mem _ p.2), ← hp, G.Θ_L _ p.2]

/-- **Division by the equation of the image**: a holomorphic function on an open `V ⊆ B` which
vanishes on the image of `Γ` is `h` times a holomorphic function on `V`. -/
lemma exists_eq_h_mul {V : Set (Cn.{u} m)} (hV : IsOpen V) (hVB : V ⊆ {p : Cn.{u} m | p ∈ B})
    {F : Cn.{u} m → ℂ}
    (hF : DifferentiableOn ℂ F V) (hF0 : ∀ a ∈ A, G.Γ a ∈ V → F (G.Γ a) = 0) :
    ∃ Q : Cn.{u} m → ℂ, DifferentiableOn ℂ Q V ∧ ∀ p ∈ V, F p = G.h p * Q p := by
  set Vδ : Set (Cn.{u} n × ℂ) := (G.domΘ ∩ G.Θ ⁻¹' V) ∩ Prod.fst ⁻¹' {a | a ∈ A}
  have hVδ : IsOpen Vδ :=
    (G.differentiableOn_Θ.continuousOn.isOpen_inter_preimage G.isOpen_domΘ hV).inter
      (A.isOpen.preimage continuous_fst)
  have hδ : DifferentiableOn ℂ (fun q ↦ F (G.Θ q)) Vδ :=
    hF.comp (G.differentiableOn_Θ.mono fun q hq ↦ hq.1.1) fun q hq ↦ hq.1.2
  obtain ⟨δ₁, hδ₁, hδδ₁⟩ := Codim2.exists_eq_mul_of_apply_zero hVδ hδ fun q hq hq0 ↦ by
    obtain ⟨⟨-, hqV⟩, hqA⟩ := hq
    obtain ⟨a, η⟩ := q
    change η = 0 at hq0
    subst hq0
    change G.Θ (a, 0) ∈ V at hqV
    change a ∈ A at hqA
    rw [G.Θ_zero _ hqA] at hqV ⊢
    exact hF0 _ hqA hqV
  have hmem : ∀ p ∈ V, (G.L p, G.h p) ∈ Vδ := fun p hp ↦
    ⟨⟨G.mem_domΘ _ (hVB hp), show G.Θ (G.L p, G.h p) ∈ V by rw [G.Θ_L _ (hVB hp)]; exact hp⟩,
      G.L_mem _ (hVB hp)⟩
  refine ⟨fun p ↦ δ₁ (G.L p, G.h p), fun p hp ↦ ?_, fun p hp ↦ ?_⟩
  · exact (hδ₁ _ (hmem p hp)).comp p (((G.differentiableOn_L p (hVB hp)).mono hVB).prodMk
      ((G.differentiableOn_h p (hVB hp)).mono hVB)) fun q hq ↦ hmem q hq
  · have := hδδ₁ _ (hmem p hp)
    simp only at this
    rw [← this, G.Θ_L _ (hVB hp)]

/-- **The ideal of the image of `Γ` is generated by `h`.** -/
theorem hasLocallyFinitelyGeneratedIdeal : G.hom.toLRSHom.HasLocallyFinitelyGeneratedIdeal := by
  intro y
  refine ⟨⊤, 1, fun _ ↦ G.hSec, trivial, fun _ ↦ ?_, fun y' hy' ↦ ?_⟩
  · refine eq_of_forall_eval_eq_restrict A fun a ha ↦ ?_
    rw [eval_c_app_hom]
    change holFun G.hSec (G.Γ a.1) = _
    rw [holFun_hSec _ (G.Γ_mem _ a.2), G.h_Γ _ a.2]
    exact (map_zero _).symm
  intro r hr
  obtain ⟨W', hy'W', s, hs0, rfl⟩ :=
    G.hom.toLRSHom.exists_germ_eq_of_mem_pushforwardStalkIdeal y' r hr
  by_cases hy'r : y' ∈ Set.range G.hom.toLRSHom.base
  swap
  · have hne : G.h y'.1 ≠ 0 := fun h0 ↦ hy'r (G.mem_range_hom_of_h_eq_zero y' h0)
    have hunit : IsUnit ((space B).presheaf.germ ⊤ y' hy' G.hSec) := by
      rw [← evalStalk_ne_zero_iff_isUnit, ← eval_apply, eval_space, holFun_hSec _ y'.2]
      exact hne
    have hmem : (space B).presheaf.germ ⊤ y' hy' G.hSec ∈
        Ideal.span (Set.range fun _ : Fin 1 ↦ (space B).presheaf.germ ⊤ y' hy' G.hSec) :=
      Ideal.subset_span ⟨0, rfl⟩
    convert Submodule.mem_top
    exact Ideal.eq_top_of_isUnit_mem _ hmem hunit
  -- `s` vanishes on the image of `Γ`, hence is `h` times a holomorphic function
  have hF0 : ∀ a ∈ A, G.Γ a ∈ img W' → holFun s (G.Γ a) = 0 := by
    intro a ha hΓa
    obtain ⟨hΓaB, hw⟩ := mem_img_iff.1 hΓa
    have hmem : (⟨a, ha⟩ : space A) ∈ (Opens.map G.hom.toLRSHom.base).obj W' := by
      change G.hom.toLRSHom.base ⟨a, ha⟩ ∈ W'
      have e : G.hom.toLRSHom.base ⟨a, ha⟩ = ⟨G.Γ a, hΓaB⟩ := Subtype.ext (G.hom_base _)
      rw [e]
      exact hw
    have := G.eval_c_app_hom s ⟨a, ha⟩ hmem
    rw [hs0] at this
    exact this.symm.trans (map_zero _)
  obtain ⟨Q, hQ, hsQ⟩ := G.exists_eq_h_mul (img W').isOpen (fun p hp ↦ img_le W' p hp)
    (differentiableOn_holFun s) hF0
  let Qs : (space B).presheaf.obj (op W') := OkaRing.ofDifferentiableOn Q hQ
  have hQs : ∀ p ∈ img W', holFun Qs p = Q p := fun p hp ↦ holFun_ofDifferentiableOn hQ hp
  have key : s = TopCat.Presheaf.restrictOpen G.hSec W' le_top * Qs := by
    refine eq_of_forall_eval_eq_restrict B fun p hp ↦ ?_
    rw [map_mul, AnalyticSpace.eval_restrictOpen, eval_space, eval_space, eval_space,
      holFun_hSec _ p.2]
    exact (hsQ _ ⟨p, hp, rfl⟩).trans (congrArg _ (hQs _ ⟨p, hp, rfl⟩).symm)
  rw [key, map_mul]
  erw [TopCat.Presheaf.germ_res_apply]
  exact Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨0, rfl⟩)

/-- **Pushing forward along `Γ` preserves coherence.** -/
theorem isCoherent_pushforward (M : SheafOfModules.{u} (space A).ringSheaf) [M.IsCoherent] :
    ((SheafOfModules.pushforward.{u} G.hom.toLRSHom.toRingSheafHom).obj M).IsCoherent :=
  G.hom.toLRSHom.isCoherent_pushforward_of_isClosedEmbedding M G.isClosedEmbedding_hom
    G.surjective_stalkMap G.hasLocallyFinitelyGeneratedIdeal

end GraphEmbeddingData

end

end ComplexAnalytic.BoundedSections
