/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.Analytic.Hartogs
import Oka.Analytic.RiemannExtensionOkaRing
import Oka.Nullstellensatz.Germ
import Mathlib.RingTheory.Regular.RegularSequence

/-!
# Hartogs extension across the zero set of a regular sequence

Let `U ⊆ ℂ^ι` be open and `g, h` holomorphic on `U` such that at every common zero `z ∈ U` the
germs of `g` and `h` at `z` form a regular sequence in the ring of germs. Then every holomorphic
function on `U \ {g = h = 0}` extends uniquely to a holomorphic function on `U`.

## Strategy

At a common zero, after a linear change of coordinates the germ of `g` is a unit times a
Weierstrass polynomial `W` in the last variable, so `𝒪_{n+1}/(g)` is finite over `𝒪_n`. The germ
of `h` acts injectively on it, and the constant term of its minimal monic equation over `𝒪_n` is a
nonzero germ `c ∈ (g, h) ∩ 𝒪_n` (`exists_ne_zero_algebraMap_mem_span_singleton`). Near the point,
the roots of `W` in the last variable are small, so the common zero set of `g` and `h` misses the
circles of a fixed small radius in the last variable, and it lies over the zero set of `c`, which
has empty interior. This is the slicing condition `HasHartogsSlicesAt` of
`Oka/Analytic/Hartogs.lean`.

## Main results

- `exists_ne_zero_algebraMap_mem_span_singleton`: for an integral algebra `A` over `R` and a
  nonzerodivisor `x` of `A`, some nonzero element of `R` becomes a multiple of `x` in `A`.
- `LocalOkaRing.exists_slices`: the slicing of the common zero set of a regular sequence of germs
  in suitable coordinates.
- `hasHartogsSlicesAt_of_isWeaklyRegular`: the common zero set of `g` and `h` is sliced by discs
  at every common zero at which their germs form a regular sequence.
- `exists_differentiableOn_eqOn_of_isWeaklyRegular`: **Hartogs extension** across the common
  zero set of a regular sequence.
- `OkaRing.existsUnique_restrict_eq_of_isWeaklyRegular`: the same for the rings `OkaRing U`.
-/

open Set Filter Metric Polynomial
open scoped Topology

section Algebra

/-- If `A` is integral over `R` and `x` is a nonzerodivisor of `A`, then some nonzero `c ∈ R`
maps into the ideal generated by `x`: the constant term of a monic equation of `x` of minimal
degree. -/
theorem exists_ne_zero_algebraMap_mem_span_singleton {R A : Type*} [CommRing R] [Nontrivial R]
    [CommRing A] [Algebra R A] [Algebra.IsIntegral R A] {x : A} (hx : IsSMulRegular A x) :
    ∃ c : R, c ≠ 0 ∧ algebraMap R A c ∈ Ideal.span {x} := by
  classical
  have hex : ∃ d, ∃ p : R[X], p.Monic ∧ p.natDegree = d ∧ aeval x p = 0 := by
    obtain ⟨p, hp, hpx⟩ := Algebra.IsIntegral.isIntegral (R := R) x
    exact ⟨_, p, hp, rfl, by rwa [aeval_def]⟩
  obtain ⟨p, hp, hpd, hpx⟩ := Nat.find_spec hex
  have hsplit : aeval x (divX p) * x + algebraMap R A (p.coeff 0) = 0 := by
    rw [← hpx]
    conv_rhs => rw [← divX_mul_X_add p]
    simp
  refine ⟨p.coeff 0, fun h0 ↦ ?_, ?_⟩
  · have hdeg : p.natDegree ≠ 0 := fun h ↦ by
      rw [Polynomial.Monic.natDegree_eq_zero hp] at h
      simp [h] at h0
    have hq : (divX p).Monic := by
      rw [Monic, leadingCoeff, natDegree_divX_eq_natDegree_tsub_one, coeff_divX,
        Nat.sub_add_cancel (Nat.one_le_iff_ne_zero.mpr hdeg)]
      exact hp.coeff_natDegree
    have hqx : aeval x (divX p) = 0 := by
      refine hx.right_eq_zero_of_smul ?_
      rw [smul_eq_mul, mul_comm]
      simpa [h0] using hsplit
    have := Nat.find_min' hex ⟨divX p, hq, rfl, hqx⟩
    rw [natDegree_divX_eq_natDegree_tsub_one, hpd] at this
    omega
  · refine Ideal.mem_span_singleton'.mpr ⟨-aeval x (divX p), ?_⟩
    rw [neg_mul, neg_eq_iff_eq_neg, ← add_eq_zero_iff_eq_neg']
    rw [add_comm]
    exact hsplit

open RingTheory.Sequence Pointwise in
/-- The second element of a weakly regular sequence `[g, h]` of a ring is a nonzerodivisor
modulo the first. -/
theorem RingTheory.Sequence.IsWeaklyRegular.dvd_of_dvd_mul {R : Type*} [CommRing R] {g h : R}
    (H : IsWeaklyRegular R [g, h]) {y : R} (hy : g ∣ h * y) : g ∣ y := by
  rw [isWeaklyRegular_cons_iff, isWeaklyRegular_cons_iff] at H
  obtain ⟨-, H, -⟩ := H
  have hmem : ∀ z : R, Submodule.Quotient.mk (p := g • (⊤ : Submodule R R)) z = 0 ↔ g ∣ z :=
    fun z ↦ by
      rw [Submodule.Quotient.mk_eq_zero, Submodule.mem_smul_pointwise_iff_exists]
      simp [dvd_def, eq_comm]
  rw [← hmem] at hy ⊢
  refine H.right_eq_zero_of_smul ?_
  rw [← Submodule.Quotient.mk_smul, smul_eq_mul, hy]

end Algebra

namespace LocalOkaRing

variable {n : ℕ}

/-- **Elimination for a regular pair.** Let `g` be a unit times a Weierstrass polynomial in the
last variable and let `h` be a nonzerodivisor modulo `g`. Then the ideal `(g, h)` contains a
nonzero germ in the first `n` variables. -/
theorem exists_ne_zero_incl_mem_span_pair {W : (LocalOkaRing (Fin n))[X]}
    (hW : IsLocalWeierstrassPolynomial
      (W.map (Subring.subtype (localOkaSubring (Fin n)).toSubring)))
    {u : LocalOkaRing (Fin (n + 1))} (hu : IsUnit u) {g h : LocalOkaRing (Fin (n + 1))}
    (hgW : g = fromPolynomial W * u) (hreg : ∀ y, g ∣ h * y → g ∣ y) :
    ∃ c : LocalOkaRing (Fin n), c ≠ 0 ∧ incl c ∈ Ideal.span {g, h} := by
  haveI := module_finite_quotient_fromPolynomial hW
  set I := Ideal.span {fromPolynomial W}
  have hdvd : ∀ y, y ∈ I ↔ g ∣ y := fun y ↦ by
    rw [Ideal.mem_span_singleton, hgW, hu.mul_right_dvd]
  have hx : IsSMulRegular (LocalOkaRing (Fin (n + 1)) ⧸ I) (Ideal.Quotient.mk I h) := by
    intro a b hab
    obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective a
    obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective b
    simp only [smul_eq_mul, ← map_mul, Ideal.Quotient.eq] at hab ⊢
    rw [hdvd] at hab ⊢
    exact hreg _ (by rwa [mul_sub])
  obtain ⟨c, hc0, hc⟩ := exists_ne_zero_algebraMap_mem_span_singleton
    (R := LocalOkaRing (Fin n)) hx
  obtain ⟨a, ha⟩ := Ideal.mem_span_singleton'.mp hc
  obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective a
  have halg : algebraMap (LocalOkaRing (Fin n)) (LocalOkaRing (Fin (n + 1)) ⧸ I) c =
      Ideal.Quotient.mk I (incl c) := by
    change Ideal.Quotient.mk I (fromPolynomial (C c)) = _
    rw [fromPolynomial_C]
  rw [halg, ← map_mul, Ideal.Quotient.eq, hdvd] at ha
  obtain ⟨k, hk⟩ := ha
  refine ⟨c, hc0, Ideal.mem_span_pair.mpr ⟨-k, b, ?_⟩⟩
  linear_combination hk

/-- The roots of a Weierstrass polynomial in the last variable are small: for every `ε > 0` and
all `z'` near the origin, `W(z', w) ≠ 0` whenever `‖w‖ ≥ ε`. -/
lemma eventually_fromPolynomial_ne_zero_of_le (q : (LocalOkaRing (Fin n))[X])
    (hq : IsLocalWeierstrassPolynomial
      (Polynomial.map (localOkaSubring (Fin n)).val.toRingHom q))
    {ε : ℝ} (hε : 0 < ε) :
    ∀ᶠ z' : Fin n → ℂ in 𝓝 0, ∀ w : ℂ, ε ≤ ‖w‖ →
      ((fromPolynomial q : LocalOkaRing (Fin (n + 1))) : MvPowerSeries (Fin (n + 1)) ℂ).eval
        (Fin.snoc z' w : Fin (n + 1) → ℂ) ≠ 0 := by
  filter_upwards [eventually_summableAt_coeffs q, eventually_error_lt q hq hε]
    with z' hsummable herror w hw
  have hwc : ∀ j, ((q.coeff j : LocalOkaRing (Fin n)) : MvPowerSeries (Fin n) ℂ).SummableAt z' :=
    fun j ↦ by
      by_cases hj : j ≤ q.natDegree
      · exact hsummable j (Finset.mem_range.mpr (by omega))
      · rw [Polynomial.coeff_eq_zero_of_natDegree_lt (by omega)]
        simpa using MvPowerSeries.summableAt_zero z'
  set c : ℕ → ℂ := fun i ↦ ((q.coeff i : LocalOkaRing (Fin n)) : MvPowerSeries (Fin n) ℂ).eval z'
  have hS : ((fromPolynomial q : LocalOkaRing (Fin (n + 1))) :
      MvPowerSeries (Fin (n + 1)) ℂ).eval (Fin.snoc z' w : Fin (n + 1) → ℂ) =
        w ^ q.natDegree + ∑ i ∈ Finset.range q.natDegree, c i * w ^ i := by
    rw [eval_fromPolynomial_snoc q z' hwc w, Finset.sum_range_succ, add_comm]
    simp only [c, eval_coeff_natDegree q hq z', one_mul]
  have hwε : 1 ≤ ‖w‖ / ε := (one_le_div hε).mpr hw
  have hT : ‖∑ i ∈ Finset.range q.natDegree, c i * w ^ i‖ < ‖w‖ ^ q.natDegree := by
    calc ‖∑ i ∈ Finset.range q.natDegree, c i * w ^ i‖
        ≤ ∑ i ∈ Finset.range q.natDegree, ‖c i‖ * ε ^ i * (‖w‖ / ε) ^ q.natDegree := by
          refine (norm_sum_le _ _).trans (Finset.sum_le_sum fun i hi ↦ ?_)
          rw [norm_mul, norm_pow, mul_assoc]
          refine mul_le_mul_of_nonneg_left ?_ (norm_nonneg _)
          calc ‖w‖ ^ i = ε ^ i * (‖w‖ / ε) ^ i := by
                rw [← mul_pow, mul_div_cancel₀ _ hε.ne']
            _ ≤ ε ^ i * (‖w‖ / ε) ^ q.natDegree := by
                refine mul_le_mul_of_nonneg_left ?_ (by positivity)
                exact pow_le_pow_right₀ hwε (Finset.mem_range.mp hi).le
      _ = (∑ i ∈ Finset.range q.natDegree, ‖c i‖ * ε ^ i) * (‖w‖ / ε) ^ q.natDegree := by
          rw [Finset.sum_mul]
      _ < ε ^ q.natDegree * (‖w‖ / ε) ^ q.natDegree :=
          mul_lt_mul_of_pos_right herror (by positivity)
      _ = ‖w‖ ^ q.natDegree := by rw [← mul_pow, mul_div_cancel₀ _ hε.ne']
  rw [hS]
  intro h0
  rw [add_eq_zero_iff_eq_neg] at h0
  have := congrArg norm h0
  rw [norm_neg, norm_pow] at this
  exact hT.ne' this

/-- The sup norm of `Fin.snoc a t` is less than `ρ` if the norms of `a` and `t` are. -/
lemma norm_snoc_lt {a : Fin n → ℂ} {t : ℂ} {ρ : ℝ} (hρ : 0 < ρ) (ha : ‖a‖ < ρ) (ht : ‖t‖ < ρ) :
    ‖(Fin.snoc a t : Fin (n + 1) → ℂ)‖ < ρ := by
  refine (pi_norm_lt_iff hρ).mpr fun i ↦ ?_
  induction i using Fin.lastCases with
  | last => simpa using ht
  | cast j => simpa using (norm_le_pi_norm a j).trans_lt ha

/-- **Slicing the common zero set of a regular sequence.** Let `G ≠ 0` and `H` be germs at the
origin, `H` a nonzerodivisor modulo `G`, representing `g` and `h`. Then in suitable coordinates
`(a, t) ∈ ℂⁿ × ℂ`, for all `a` in a small ball and `‖t‖ ≤ 3ε`, the point lies in the prescribed
neighbourhood `N`, `g` does not vanish for `ε ≤ ‖t‖`, and the set of `a` over which `g` and `h`
have a common zero has empty interior. -/
theorem exists_slices {G H : LocalOkaRing (Fin (n + 1))} (hG0 : G ≠ 0)
    (hreg : ∀ y, G ∣ H * y → G ∣ y)
    {g h : (Fin (n + 1) → ℂ) → ℂ} (hg : (G : MvPowerSeries (Fin (n + 1)) ℂ).Represents g)
    (hh : (H : MvPowerSeries (Fin (n + 1)) ℂ).Represents h) {N : Set (Fin (n + 1) → ℂ)}
    (hN : N ∈ 𝓝 0) :
    ∃ (φ : (Fin (n + 1) → ℂ) ≃L[ℂ] (Fin (n + 1) → ℂ)) (ε δ : ℝ), 0 < ε ∧ 0 < δ ∧
      (∀ a ∈ ball (0 : Fin n → ℂ) δ, ∀ t : ℂ, ‖t‖ ≤ 3 * ε →
        φ.symm (Fin.snoc a t) ∈ N ∧ (ε ≤ ‖t‖ → g (φ.symm (Fin.snoc a t)) ≠ 0)) ∧
      interior {a ∈ ball (0 : Fin n → ℂ) δ | ∃ t : ℂ, ‖t‖ ≤ 3 * ε ∧
        g (φ.symm (Fin.snoc a t)) = 0 ∧ h (φ.symm (Fin.snoc a t)) = 0} = ∅ := by
  obtain ⟨φ, u, hu, W, hW, heq⟩ := exists_congr_localweierstrass_preparation hG0
  set e := congr φ
  have hreg' : ∀ y, e G ∣ e H * y → e G ∣ y := fun y hy ↦ by
    have := hreg (e.symm y) (by simpa using map_dvd e.symm hy)
    simpa using map_dvd e this
  obtain ⟨c, hc0, hc⟩ := exists_ne_zero_incl_mem_span_pair hW hu heq hreg'
  obtain ⟨α, β, hαβ⟩ := Ideal.mem_span_pair.mp hc
  set v : LocalOkaRing (Fin (n + 1)) := ↑hu.unit⁻¹
  have hWG : fromPolynomial W = e G * v := by
    rw [heq, mul_assoc, IsUnit.mul_val_inv, mul_one]
  -- the identities between the germs hold as identities of functions near the origin
  have hφ0 : Tendsto φ.symm (𝓝 0) (𝓝 0) := by
    simpa using φ.symm.continuous.tendsto (0 : Fin (n + 1) → ℂ)
  have hE : ∀ᶠ y in 𝓝 (0 : Fin (n + 1) → ℂ), φ.symm y ∈ N ∧
      ((e G : LocalOkaRing (Fin (n + 1))) : MvPowerSeries (Fin (n + 1)) ℂ).eval y =
        g (φ.symm y) ∧
      ((e H : LocalOkaRing (Fin (n + 1))) : MvPowerSeries (Fin (n + 1)) ℂ).eval y =
        h (φ.symm y) ∧
      ((fromPolynomial W : LocalOkaRing (Fin (n + 1))) : MvPowerSeries (Fin (n + 1)) ℂ).eval y =
        ((e G : LocalOkaRing (Fin (n + 1))) : MvPowerSeries (Fin (n + 1)) ℂ).eval y *
          (v : MvPowerSeries (Fin (n + 1)) ℂ).eval y ∧
      ((incl c : LocalOkaRing (Fin (n + 1))) : MvPowerSeries (Fin (n + 1)) ℂ).eval y =
        (α : MvPowerSeries (Fin (n + 1)) ℂ).eval y *
          ((e G : LocalOkaRing (Fin (n + 1))) : MvPowerSeries (Fin (n + 1)) ℂ).eval y +
        (β : MvPowerSeries (Fin (n + 1)) ℂ).eval y *
          ((e H : LocalOkaRing (Fin (n + 1))) : MvPowerSeries (Fin (n + 1)) ℂ).eval y := by
    filter_upwards [hφ0.eventually hN, (congr_represents (φ := φ) hg).eval_eq,
      (congr_represents (φ := φ) hh).eval_eq, eventually_eval_mul (e G) v,
      eventually_eval_add (α * e G) (β * e H), eventually_eval_mul α (e G),
      eventually_eval_mul β (e H)] with y hN hg hh hmul hadd hmα hmβ
    refine ⟨hN, hg, hh, by rw [hWG, hmul], ?_⟩
    rw [← hαβ, hadd, hmα, hmβ]
  obtain ⟨ρ, hρ, hρE⟩ := Metric.eventually_nhds_iff.mp hE
  set ε := ρ / 4 with hε
  have hε0 : 0 < ε := by positivity
  obtain ⟨δ₁, hδ₁, hroot⟩ := Metric.eventually_nhds_iff.mp
    (eventually_fromPolynomial_ne_zero_of_le W hW hε0)
  obtain ⟨ρc, hρc, hcball⟩ := c.locallyConvergent.hasFPowerSeriesOnBall
  set δ := min δ₁ (min ρ ρc)
  have hδ : 0 < δ := lt_min hδ₁ (lt_min hρ hρc)
  have hpt : ∀ a ∈ ball (0 : Fin n → ℂ) δ, ∀ t : ℂ, ‖t‖ ≤ 3 * ε →
      dist (Fin.snoc a t : Fin (n + 1) → ℂ) 0 < ρ := fun a ha t ht ↦ by
    rw [dist_zero_right]
    refine norm_snoc_lt hρ ((mem_ball_zero_iff.mp ha).trans_le
      ((min_le_right _ _).trans (min_le_left _ _))) (by linarith)
  refine ⟨φ, ε, δ, hε0, hδ, fun a ha t ht ↦ ⟨(hρE (hpt a ha t ht)).1, fun hεt hzero ↦ ?_⟩, ?_⟩
  · obtain ⟨-, hg, -, hW', -⟩ := hρE (hpt a ha t ht)
    have ha₁ : dist a 0 < δ₁ := by
      rw [dist_zero_right]
      exact (mem_ball_zero_iff.mp ha).trans_le (min_le_left _ _)
    refine hroot ha₁ t hεt ?_
    rw [hW', hg, hzero, zero_mul]
  -- the common zeros lie over the zero set of `c`
  have hsub : {a ∈ ball (0 : Fin n → ℂ) δ | ∃ t : ℂ, ‖t‖ ≤ 3 * ε ∧
      g (φ.symm (Fin.snoc a t)) = 0 ∧ h (φ.symm (Fin.snoc a t)) = 0} ⊆
        ball (0 : Fin n → ℂ) δ ∩ (c : MvPowerSeries (Fin n) ℂ).eval ⁻¹' {0} := by
    rintro a ⟨ha, t, ht, hgz, hhz⟩
    obtain ⟨-, hg, hh, -, hcE⟩ := hρE (hpt a ha t ht)
    refine ⟨ha, ?_⟩
    have := hcE
    rw [hg, hh, hgz, hhz, mul_zero, mul_zero, add_zero, eval_incl] at this
    simpa [Fin.snoc_castSucc] using this
  refine subset_empty_iff.mp (le_of_le_of_eq (interior_mono hsub) ?_)
  have hana : AnalyticOnNhd ℂ (c : MvPowerSeries (Fin n) ℂ).eval (ball 0 δ) := fun a ha ↦
    hcball.analyticAt_of_mem (by
      rw [Metric.eball_ofReal]
      exact ball_subset_ball ((min_le_right _ _).trans (min_le_right _ _)) ha)
  obtain ⟨a₀, ha₀, hca₀⟩ :
      ∃ a ∈ ball (0 : Fin n → ℂ) δ, (c : MvPowerSeries (Fin n) ℂ).eval a ≠ 0 := by
    by_contra! H
    exact hc0 (eq_zero_of_eventually_eval_eq_zero
      (Filter.mem_of_superset (ball_mem_nhds 0 hδ) H))
  exact hana.interior_inter_preimage_zero_eq_empty (convex_ball 0 δ).isPreconnected ha₀ hca₀

end LocalOkaRing

open RingTheory.Sequence in
/-- The first element of a weakly regular sequence in a nontrivial ring is nonzero. -/
theorem RingTheory.Sequence.IsWeaklyRegular.ne_zero_of_cons {R : Type*} [CommRing R]
    [Nontrivial R] {r : R} {rs : List R} (H : IsWeaklyRegular R (r :: rs)) : r ≠ 0 := by
  rintro rfl
  rw [isWeaklyRegular_cons_iff] at H
  exact one_ne_zero (H.1.right_eq_zero_of_smul (by simp) : (1 : R) = 0)

section Slices

variable {n : ℕ}

/-- Moving `Fin.snoc a s` in the direction of the last coordinate moves its last entry. -/
lemma Fin.snoc_add_smul_single_last (a : Fin n → ℂ) (s t : ℂ) :
    (Fin.snoc a s : Fin (n + 1) → ℂ) + t • Pi.single (Fin.last n) 1 = Fin.snoc a (s + t) := by
  funext i
  induction i using Fin.lastCases with
  | last => simp
  | cast j => simp [(Fin.castSucc_lt_last j).ne]

/-- The common zero set of `g` and `h` is sliced by discs near `z₀ ∈ U ⊆ ℂⁿ⁺¹` if their germs
`G ≠ 0` and `H` at `z₀` are such that `H` is a nonzerodivisor modulo `G`. -/
theorem hasHartogsSlicesAt_fin {U : Set (Fin (n + 1) → ℂ)} (hU : IsOpen U)
    {g h : (Fin (n + 1) → ℂ) → ℂ} {z₀ : Fin (n + 1) → ℂ} (hz₀ : z₀ ∈ U)
    {G H : LocalOkaRing (Fin (n + 1))} (hG0 : G ≠ 0) (hreg : ∀ y, G ∣ H * y → G ∣ y)
    (hG : (G : MvPowerSeries (Fin (n + 1)) ℂ).Represents fun w ↦ g (w + z₀))
    (hH : (H : MvPowerSeries (Fin (n + 1)) ℂ).Represents fun w ↦ h (w + z₀)) :
    HasHartogsSlicesAt U {z | g z = 0 ∧ h z = 0} z₀ := by
  have hN : {w | w + z₀ ∈ U} ∈ 𝓝 (0 : Fin (n + 1) → ℂ) :=
    (hU.preimage (continuous_add_const z₀)).mem_nhds (by simpa using hz₀)
  obtain ⟨φ, ε, δ, hε, hδ, hgood, hbad⟩ := LocalOkaRing.exists_slices hG0 hreg hG hH hN
  set π : (Fin (n + 1) → ℂ) → Fin n → ℂ := fun z ↦ Fin.init (φ (z - z₀))
  set τ : (Fin (n + 1) → ℂ) → ℂ := fun z ↦ φ (z - z₀) (Fin.last n)
  set v : Fin (n + 1) → ℂ := φ.symm (Pi.single (Fin.last n) 1)
  have hkey : ∀ z (t : ℂ), z + t • v = φ.symm (Fin.snoc (π z) (τ z + t)) + z₀ := fun z t ↦ by
    rw [← Fin.snoc_add_smul_single_last, Fin.snoc_init_self, map_add, map_smul,
      ContinuousLinearEquiv.symm_apply_apply]
    abel
  have hπc : Continuous π := by fun_prop
  have hτc : Continuous τ := by fun_prop
  refine ⟨{z | π z ∈ ball 0 δ ∧ ‖τ z‖ < ε}, ?_, v, 2 * ε, by positivity, ?_, ?_, ?_⟩
  · refine ((isOpen_ball.preimage hπc).inter (isOpen_lt hτc.norm continuous_const)).mem_nhds ?_
    simp [π, τ, hδ, hε]
  · rintro z ⟨hzπ, hzτ⟩ t ht
    rw [hkey]
    exact (hgood _ hzπ _ ((norm_add_le _ _).trans (by linarith))).1
  · rintro z ⟨hzπ, hzτ⟩ t ht ⟨hgz, -⟩
    rw [hkey] at hgz
    refine (hgood _ hzπ _ ((norm_add_le _ _).trans (by linarith))).2 ?_ hgz
    have := norm_sub_norm_le t (-τ z)
    rw [norm_neg, sub_neg_eq_add, add_comm] at this
    linarith
  · -- the discs meeting the zero set lie over a set with empty interior
    refine subset_empty_iff.mp fun z hz ↦ ?_
    set Bad := {a ∈ ball (0 : Fin n → ℂ) δ | ∃ t : ℂ, ‖t‖ ≤ 3 * ε ∧
      g (φ.symm (Fin.snoc a t) + z₀) = 0 ∧ h (φ.symm (Fin.snoc a t) + z₀) = 0}
    have hsub : {z | π z ∈ ball 0 δ ∧ ‖τ z‖ < ε} ∩
        {z | ∃ t : ℂ, ‖t‖ ≤ 2 * ε ∧ z + t • v ∈ {z | g z = 0 ∧ h z = 0}} ⊆ π ⁻¹' Bad := by
      rintro w ⟨⟨hwπ, hwτ⟩, t, ht, hgw, hhw⟩
      rw [hkey] at hgw hhw
      exact ⟨hwπ, τ w + t, (norm_add_le _ _).trans (by linarith), hgw, hhw⟩
    set σ : (Fin n → ℂ) → Fin (n + 1) → ℂ := fun a ↦ φ.symm (Fin.snoc a (τ z)) + z₀
    have hσc : Continuous σ := by fun_prop
    have hπσ : ∀ a, π (σ a) = a := fun a ↦ by simp [π, σ]
    have hσπ : σ (π z) = z := by
      simp only [σ, π, τ, Fin.snoc_init_self, ContinuousLinearEquiv.symm_apply_apply,
        sub_add_cancel]
    have hopen : IsOpen (σ ⁻¹' interior {z ∈ {z | π z ∈ ball 0 δ ∧ ‖τ z‖ < ε} |
        ∃ t : ℂ, ‖t‖ ≤ 2 * ε ∧ z + t • v ∈ {z | g z = 0 ∧ h z = 0}}) :=
      isOpen_interior.preimage hσc
    have hmem : π z ∈ interior Bad := by
      refine interior_maximal (fun a ha ↦ ?_) hopen (by rwa [Set.mem_preimage, hσπ])
      have := hsub (interior_subset ha)
      rwa [Set.mem_preimage, hπσ] at this
    rw [hbad] at hmem
    exact hmem

variable {ι : Type*} [Fintype ι]

/-- **The common zero set of a regular sequence is sliced by discs.** If `g` vanishes at
`z₀ ∈ U` and the germs of `g` and `h` at `z₀` form a regular sequence, then `{g = h = 0}` is
sliced by discs near `z₀`. -/
theorem hasHartogsSlicesAt_of_isWeaklyRegular {U : Set (ι → ℂ)} (hU : IsOpen U)
    {g h : (ι → ℂ) → ℂ} {z₀ : ι → ℂ} (hz₀ : z₀ ∈ U) (hgz₀ : g z₀ = 0) {G H : LocalOkaRing ι}
    (hG : (G : MvPowerSeries ι ℂ).Represents fun w ↦ g (w + z₀))
    (hH : (H : MvPowerSeries ι ℂ).Represents fun w ↦ h (w + z₀))
    (hreg : RingTheory.Sequence.IsWeaklyRegular (LocalOkaRing ι) [G, H]) :
    HasHartogsSlicesAt U {z | g z = 0 ∧ h z = 0} z₀ := by
  have hG0 := hreg.ne_zero_of_cons
  cases hn : Fintype.card ι with
  | zero =>
    -- in no variables, a nonzero germ is a unit and so does not vanish at the origin
    haveI : IsEmpty ι := Fintype.card_eq_zero_iff.mp hn
    have hu := LocalOkaRing.isUnit_iff_ne_zero.mpr hG0
    rw [LocalOkaRing.isUnit_iff, LocalOkaRing.constantCoeff_apply, ← hG.apply_zero] at hu
    exact (hu (by rw [zero_add]; exact hgz₀)).elim
  | succ m =>
    set φ : (ι → ℂ) ≃L[ℂ] (Fin (m + 1) → ℂ) :=
      (LinearEquiv.funCongrLeft ℂ ℂ (Fintype.equivFinOfCardEq hn).symm).toContinuousLinearEquiv
    set e := LocalOkaRing.congr φ
    have hrep : ∀ {P : LocalOkaRing ι} {f : (ι → ℂ) → ℂ},
        (P : MvPowerSeries ι ℂ).Represents (fun w ↦ f (w + z₀)) →
        ((e P : LocalOkaRing (Fin (m + 1))) : MvPowerSeries (Fin (m + 1)) ℂ).Represents
          (fun w ↦ (f ∘ φ.symm) (w + φ z₀)) := fun hP ↦
      (LocalOkaRing.congr_represents hP).congr (Eventually.of_forall fun w ↦ by
        simp [map_add])
    refine HasHartogsSlicesAt.of_continuousLinearEquiv φ ?_
    refine hasHartogsSlicesAt_fin (g := g ∘ φ.symm) (h := h ∘ φ.symm)
      (hU.preimage φ.symm.continuous) (by simpa using hz₀) (G := e G) (H := e H)
      ((map_ne_zero_iff e e.injective).mpr hG0) (fun y hy ↦ ?_) (hrep hG) (hrep hH)
    have := hreg.dvd_of_dvd_mul (y := e.symm y) (by simpa using map_dvd e.symm hy)
    simpa using map_dvd e this

end Slices

section Extension

variable {ι : Type*} [Finite ι] {U : Set (ι → ℂ)} {g h : (ι → ℂ) → ℂ}

/-- The complement in `U` of the common zero set of two functions continuous on `U` is open. -/
lemma isOpen_diff_setOf_eq_zero_and_eq_zero {X : Type*} [TopologicalSpace X] {U : Set X}
    {g h : X → ℂ} (hU : IsOpen U) (hg : ContinuousOn g U)
    (hh : ContinuousOn h U) : IsOpen (U \ {z | g z = 0 ∧ h z = 0}) := by
  have : U \ {z | g z = 0 ∧ h z = 0} = (U ∩ g ⁻¹' {0}ᶜ) ∪ (U ∩ h ⁻¹' {0}ᶜ) := by
    ext z
    simp only [Set.mem_sdiff, mem_setOf_eq, not_and_or, mem_union, mem_inter_iff, mem_preimage,
      mem_compl_iff, mem_singleton_iff]
    tauto
  rw [this]
  exact (hg.isOpen_inter_preimage hU isOpen_compl_singleton).union
    (hh.isOpen_inter_preimage hU isOpen_compl_singleton)

/-- **Hartogs extension across the zero set of a regular sequence.** Let `g, h` be continuous
on the open set `U ⊆ ℂ^ι` such that at every common zero `z ∈ U` some germs representing `g`
and `h` at `z` form a regular sequence. Then every holomorphic function on `U \ {g = h = 0}`
extends to a holomorphic function on `U`. -/
theorem exists_differentiableOn_eqOn_of_isWeaklyRegular (hU : IsOpen U) (hg : ContinuousOn g U)
    (hh : ContinuousOn h U)
    (hreg : ∀ z ∈ U, g z = 0 → h z = 0 → ∃ G H : LocalOkaRing ι,
      (G : MvPowerSeries ι ℂ).Represents (fun w ↦ g (w + z)) ∧
      (H : MvPowerSeries ι ℂ).Represents (fun w ↦ h (w + z)) ∧
      RingTheory.Sequence.IsWeaklyRegular (LocalOkaRing ι) [G, H])
    {f : (ι → ℂ) → ℂ} (hf : DifferentiableOn ℂ f (U \ {z | g z = 0 ∧ h z = 0})) :
    ∃ F : (ι → ℂ) → ℂ, DifferentiableOn ℂ F U ∧ EqOn F f (U \ {z | g z = 0 ∧ h z = 0}) := by
  haveI := Fintype.ofFinite ι
  refine exists_differentiableOn_eqOn_of_hasHartogsSlicesAt
    (isOpen_diff_setOf_eq_zero_and_eq_zero hU hg hh) (fun a ⟨haU, hga, hha⟩ ↦ ?_) hf
  obtain ⟨G, H, hG, hH, hGH⟩ := hreg a haU hga hha
  exact hasHartogsSlicesAt_of_isWeaklyRegular hU haU hga hG hH hGH

/-- The common zero set in `U` of `g` and `h` has empty interior if at every common zero some
germs representing `g` and `h` form a regular sequence. -/
theorem interior_inter_setOf_eq_zero_and_eq_zero_eq_empty (hU : IsOpen U)
    (hg : ContinuousOn g U) (hh : ContinuousOn h U)
    (hreg : ∀ z ∈ U, g z = 0 → h z = 0 → ∃ G H : LocalOkaRing ι,
      (G : MvPowerSeries ι ℂ).Represents (fun w ↦ g (w + z)) ∧
      (H : MvPowerSeries ι ℂ).Represents (fun w ↦ h (w + z)) ∧
      RingTheory.Sequence.IsWeaklyRegular (LocalOkaRing ι) [G, H]) :
    interior (U ∩ {z | g z = 0 ∧ h z = 0}) = ∅ := by
  haveI := Fintype.ofFinite ι
  refine interior_inter_eq_empty_of_hasHartogsSlicesAt
    (isOpen_diff_setOf_eq_zero_and_eq_zero hU hg hh) fun a ⟨haU, hga, hha⟩ ↦ ?_
  obtain ⟨G, H, hG, hH, hGH⟩ := hreg a haU hga hha
  exact hasHartogsSlicesAt_of_isWeaklyRegular hU haU hga hG hH hGH

end Extension

namespace OkaRing

variable {ι : Type*} [Fintype ι]

/-- **Hartogs extension for holomorphic functions on opens of `ℂ^ι`.** Let `g, h` be holomorphic
on `U` such that at every common zero `z ∈ U` their germs form a regular sequence, and let
`V ⊆ U` be open containing `U \ {g = h = 0}`. Then every holomorphic function on `V` is the
restriction of a unique holomorphic function on `U`. -/
theorem existsUnique_restrict_eq_of_isWeaklyRegular {U V : TopologicalSpace.Opens (ι → ℂ)}
    (hVU : V ≤ U) (g h : OkaRing U)
    (hreg : ∀ z (hz : z ∈ U), g.toGlobalFun _ z = 0 → h.toGlobalFun _ z = 0 →
      RingTheory.Sequence.IsWeaklyRegular (LocalOkaRing ι) [germ hz g, germ hz h])
    (hV : (U : Set (ι → ℂ)) \ {z | g.toGlobalFun _ z = 0 ∧ h.toGlobalFun _ z = 0} ⊆ V)
    (f : OkaRing V) :
    ∃! F : OkaRing U, OkaRing.restrict hVU F = f := by
  set S := {z | g.toGlobalFun _ z = 0 ∧ h.toGlobalFun _ z = 0}
  have hreg' : ∀ z ∈ (U : Set (ι → ℂ)), g.toGlobalFun _ z = 0 → h.toGlobalFun _ z = 0 →
      ∃ G H : LocalOkaRing ι,
        (G : MvPowerSeries ι ℂ).Represents (fun w ↦ g.toGlobalFun _ (w + z)) ∧
        (H : MvPowerSeries ι ℂ).Represents (fun w ↦ h.toGlobalFun _ (w + z)) ∧
        RingTheory.Sequence.IsWeaklyRegular (LocalOkaRing ι) [G, H] :=
    fun z hz hgz hhz ↦ ⟨_, _, germ_represents hz g, germ_represents hz h, hreg z hz hgz hhz⟩
  have hZ : interior ((U : Set (ι → ℂ)) ∩ S) = ∅ :=
    interior_inter_setOf_eq_zero_and_eq_zero_eq_empty U.isOpen g.continuousOn_toGlobalFun
      h.continuousOn_toGlobalFun hreg'
  obtain ⟨F₀, hF₀d, hF₀f⟩ := exists_differentiableOn_eqOn_of_isWeaklyRegular U.isOpen
    g.continuousOn_toGlobalFun h.continuousOn_toGlobalFun hreg'
    (f.differentiableOn_toGlobalFun.mono hV)
  -- `F₀` agrees with `f` on all of `V`, as `V \ S` is dense in `V`.
  have hF₀V : EqOn F₀ (f.toGlobalFun _) V :=
    EqOn.of_eqOn_diff_of_interior_eq_empty V.isOpen hZ (hF₀d.continuousOn.mono hVU)
      f.continuousOn_toGlobalFun fun x hx ↦ hF₀f ⟨hVU hx.1, fun hS ↦ hx.2 ⟨hVU hx.1, hS⟩⟩
  refine ⟨ofDifferentiableOn F₀ hF₀d, ?_, fun F hF ↦ ?_⟩
  · ext x
    simp [hF₀V x.2, f.toGlobalFun_apply x.2]
  · have hFU : EqOn (F.toGlobalFun _) F₀ U := by
      refine EqOn.of_eqOn_diff_of_interior_eq_empty U.isOpen hZ F.continuousOn_toGlobalFun
        hF₀d.continuousOn fun x hx ↦ ?_
      have hxV : x ∈ V := hV ⟨hx.1, fun hS ↦ hx.2 ⟨hx.1, hS⟩⟩
      rw [hF₀V hxV, F.toGlobalFun_apply hx.1, f.toGlobalFun_apply hxV, ← hF]
      rfl
    ext x
    simp [← hFU x.2, F.toGlobalFun_apply x.2]

end OkaRing
