/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.AnalyticSpace.Nullstellensatz
import Oka.Analytification.GAGA.StalkFlat
import Oka.Analytification.RET.ConnectedZeroLocus
import Oka.Analytification.RET.Full
import Oka.Analytification.GAGA.Proper.Induction

/-!
# The analytification of a connected scheme is connected

For a connected scheme `X` locally of finite type over `ℂ`, the analytification `X^an` is
connected (`ComplexAnalytic.connectedSpace_analytification`).

* **Density.** For `X` integral and `V ⊆ X` a nonempty open, `π⁻¹ V` is dense in `X^an`
  (`ComplexAnalytic.dense_preimage_analytificationπ`): if a section `f ≠ 0` of `𝒪_X` pulled back to
  `X^an` vanished on an open set, then by the Rückert Nullstellensatz its germ would be nilpotent,
  and by faithful flatness of the stalk maps of `π` so would be the germ of `f`.
* **The integral affine case.** For `X = Spec (ℂ[z] ⧸ I)` with `I` prime, `X^an` is the zero
  locus of `I`, which is connected by `ComplexAnalytic.isPreconnected_zeroLocus_of_isPrime`; its
  density hypothesis is the density statement above.
* **The integral case.** A nonempty affine open `U` of an integral `X` has connected `U^an`, which
  is dense in `X^an`.
* **The general case.** Closed points of a connected `X` are linked by chains in which consecutive
  points lie in a common irreducible component `Z`
  (`AlgebraicGeometry.Scheme.reflTransGen_irreducibleComponents`), and the analytification of the
  reduced subscheme on `Z` is connected and contains the points of `X^an` over the closed points
  of `Z`.

## Main results

- `ComplexAnalytic.dense_preimage_analytificationπ`
- `ComplexAnalytic.preconnectedSpace_analytification_of_isIntegral`
- `ComplexAnalytic.connectedSpace_analytification`
- `ComplexAnalytic.analytificationPreservesConnected`
-/

open CategoryTheory Opposite AlgebraicGeometry TopologicalSpace Topology

universe u

namespace ComplexAnalytic

open AnalyticSpace

noncomputable section

/-! ### Density -/

/-- **For `X` integral, the preimage in `X^an` of a nonempty open of `X` is dense.** -/
theorem dense_preimage_analytificationπ (X : SchemeLFTℂ.{u}) [IsIntegral X.obj.left]
    {V : X.obj.left.Opens} (hV : (V : Set X.obj.left).Nonempty) :
    Dense ((analytificationπLRS X).base ⁻¹' (V : Set X.obj.left)) := by
  set π := analytificationπLRS X
  refine dense_iff_inter_open.2 fun O hO ⟨y, hyO⟩ ↦ ?_
  by_contra hne
  obtain ⟨⟨U, hUa⟩, hU⟩ := exists_affineOpens_mem X.obj.left (π.base y)
  obtain ⟨x, hxV, hxU⟩ := nonempty_preirreducible_inter V.isOpen U.isOpen
    hV ⟨_, hU⟩
  obtain ⟨f, hfle, hxf⟩ := hUa.exists_basicOpen_le (V := V ⊓ U)
    ⟨x, hxV, hxU⟩ hxU
  set W : (analytification.obj X).Opens := (Opens.map π.base).obj U
  set s := π.c.app (op U) f
  have hgerm (y' : analytification.obj X) (hy' : y' ∈ W) :
      (analytification.obj X).presheaf.germ W y' hy' s =
        π.stalkMap y' (X.obj.left.presheaf.germ U (π.base y') hy' f) :=
    (LocallyRingedSpace.stalkMap_germ_apply π U y' hy' f).symm
  have heval (y' : analytification.obj X) (hy' : y' ∈ W) :
      (analytification.obj X).eval y' hy' s = 0 ↔ π.base y' ∉ X.obj.left.basicOpen f := by
    rw [← not_iff_not, ← ne_eq, AnalyticSpace.eval_apply,
      AnalyticSpace.evalStalk_ne_zero_iff_isUnit, not_not, hgerm, isUnit_map_iff,
      Scheme.mem_basicOpen]
  have hN := AnalyticSpace.isNullstellensatzAt (analytification.obj X) y W hU (s := 0)
    Fin.elim0 s (by
      filter_upwards [hO.mem_nhds hyO] with y' hy'O hy'W _
      rw [heval]
      exact fun hb ↦ hne ⟨y', hy'O, (hfle hb).1⟩)
  obtain ⟨m, hm⟩ := hN
  have hm' : (analytification.obj X).presheaf.germ W y hU s ^ m = 0 := by
    simpa [Set.range_eq_empty] using hm
  rw [hgerm, ← map_pow] at hm'
  have hinj := (faithfullyFlat_stalkMap_analytificationπ X y).injective
  have hf0 : X.obj.left.presheaf.germ U (π.base y) hU f = 0 :=
    IsNilpotent.eq_zero ⟨m, hinj (hm'.trans (map_zero _).symm)⟩
  have : f = 0 := germ_injective_of_isIntegral X.obj.left (π.base y) hU
    (hf0.trans (map_zero _).symm)
  rw [this, Scheme.basicOpen_zero] at hxf
  exact hxf

/-! ### The integral affine case -/

/-- The zero locus of the ideal generated by a tuple of polynomials is the common zero locus of
the tuple. -/
lemma forall_mem_span_eval_eq_zero_iff {σ : Type*} {k : ℕ} (g : Fin k → MvPolynomial σ ℂ)
    (z : σ → ℂ) :
    (∀ f ∈ Ideal.span (Set.range g), MvPolynomial.eval z f = 0) ↔
      ∀ j, MvPolynomial.eval z (g j) = 0 := by
  refine ⟨fun h j ↦ h _ (Ideal.subset_span ⟨j, rfl⟩), fun h f hf ↦ ?_⟩
  induction hf using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨j, rfl⟩ := hx
    exact h j
  | zero => simp
  | add x y _ _ hx hy => simp [hx, hy]
  | smul a x _ hx => simp [hx]

/-- An analytic space isomorphic to a preconnected one is preconnected. -/
lemma preconnectedSpace_of_isIso {A B : AnalyticSpace.{u}} (φ : A ⟶ B) [IsIso φ]
    [PreconnectedSpace A] : PreconnectedSpace B :=
  (bijective_base_of_isIso φ).2.denseRange.preconnectedSpace φ.toLRSHom.base.hom.continuous

variable {n k : ℕ} (g : Fin k → MvPolynomial (ULift.{u} (Fin n)) ℂ)

/-- **The analytification of `Spec (ℂ[z] ⧸ (g))` is connected** if `ℂ[z] ⧸ (g)` is a domain. -/
theorem preconnectedSpace_analytification_specPresentation
    [IsDomain (PresentedAlgebra n k g)] :
    PreconnectedSpace (analytification.obj (SchemeLFTℂ.specPresentation g)) := by
  set Y := SchemeLFTℂ.specPresentation g
  haveI : IsIntegral Y.obj.left := inferInstanceAs (IsIntegral (Spec _))
  haveI : (presentationIdeal g).IsPrime := (Ideal.Quotient.isDomain_iff_prime _).1 ‹_›
  set ψ := (analytificationSpecIso g).hom
  let F : analytification.obj Y → (ULift.{u} (Fin n) → ℂ) := fun y ↦ (ψ.toLRSHom.base y).1.1
  have hF : Continuous F :=
    continuous_subtype_val.comp (continuous_subtype_val.comp ψ.toLRSHom.base.hom.continuous)
  have hdense (f : MvPolynomial (ULift.{u} (Fin n)) ℂ) (hf : f ∉ presentationIdeal g) :
      {z : ULift.{u} (Fin n) → ℂ | ∀ f ∈ presentationIdeal g, MvPolynomial.eval z f = 0} ⊆
        closure {z | (∀ f ∈ presentationIdeal g, MvPolynomial.eval z f = 0) ∧
          MvPolynomial.eval z f ≠ 0} := by
    intro z hz
    let w : AnalyticSpace.analytification.{u} g :=
      ⟨⟨z, trivial⟩, (mem_zeroLocus_polySection_iff g _).2
        ((forall_mem_span_eval_eq_zero_iff g z).1 hz)⟩
    obtain ⟨y, hy⟩ := (bijective_base_of_isIso ψ).2 w
    let D : Y.obj.left.Opens := PrimeSpectrum.basicOpen (Ideal.Quotient.mk (presentationIdeal g) f)
    have hD : (D : Set Y.obj.left).Nonempty := by
      refine (Opens.ne_bot_iff_nonempty _).1 fun h ↦ hf ?_
      have h' : PrimeSpectrum.basicOpen (Ideal.Quotient.mk (presentationIdeal g) f) = ⊥ := h
      rw [PrimeSpectrum.basicOpen_eq_bot_iff] at h'
      exact Ideal.Quotient.eq_zero_iff_mem.1 h'.eq_zero
    have hy' := dense_preimage_analytificationπ Y hD y
    have hFy : F y = z := by
      change (ψ.toLRSHom.base y).1.1 = z
      rw [hy]
    rw [← hFy]
    refine closure_mono ?_ (mem_closure_image hF.continuousAt hy')
    rintro _ ⟨y', hy'D, rfl⟩
    refine ⟨(forall_mem_span_eval_eq_zero_iff g _).2 (eval_eq_zero_of_mem g _), ?_⟩
    change (analytificationπ Y).left.base y' ∈ PrimeSpectrum.basicOpen _ at hy'D
    rw [analytificationπ_specPresentation_base_apply] at hy'D
    have := (PrimeSpectrum.mem_basicOpen _ _).1 hy'D
    rwa [mem_analytificationToSpec_base_asIdeal_iff] at this
  have hZ := isPreconnected_zeroLocus_of_isPrime (presentationIdeal g) hdense
  have hrange : Set.range (analytificationIncl.{u} g).base =
      {z : ULift.{u} (Fin n) → ℂ | ∀ f ∈ presentationIdeal g, MvPolynomial.eval z f = 0} := by
    rw [range_base_analytificationIncl]
    ext z
    exact (forall_mem_span_eval_eq_zero_iff g z).symm
  haveI : PreconnectedSpace (AnalyticSpace.analytification.{u} g) := by
    refine ⟨(isClosedEmbedding_base_analytificationIncl g).isInducing.isPreconnected_image.1 ?_⟩
    rw [Set.image_univ, hrange]
    exact hZ
  exact preconnectedSpace_of_isIso (analytificationSpecIso g).inv

/-- **The analytification of an integral affine scheme of finite type over `ℂ` is
connected.** -/
theorem preconnectedSpace_analytification_of_isAffine (T : SchemeLFTℂ.{u}) [IsAffine T.obj.left]
    [IsIntegral T.obj.left] : PreconnectedSpace (analytification.obj T) := by
  obtain ⟨n, k, g, ⟨e⟩⟩ := SchemeLFTℂ.exists_iso_specPresentation T
  haveI : IsIso e.hom.hom.left :=
    (Functor.map_isIso (locallyOfFiniteTypeℂ.ι ⋙ Over.forget _) e.hom :)
  haveI : Nonempty (SchemeLFTℂ.specPresentation g).obj.left :=
    ⟨inv e.hom.hom.left (Nonempty.some inferInstance)⟩
  haveI : IsIntegral (SchemeLFTℂ.specPresentation g).obj.left :=
    isIntegral_of_isOpenImmersion e.hom.hom.left
  haveI : IsDomain (PresentedAlgebra n k g) :=
    (affine_isIntegral_iff (CommRingCat.of (PresentedAlgebra n k g))).1 ‹_›
  haveI := preconnectedSpace_analytification_specPresentation g
  exact preconnectedSpace_of_isIso (analytification.map e.hom)

/-! ### The integral case -/

/-- The analytification of a nonempty scheme locally of finite type over `ℂ` is nonempty. -/
lemma nonempty_analytification (X : SchemeLFTℂ.{u}) [Nonempty X.obj.left] :
    Nonempty (analytification.obj X) := by
  obtain ⟨x, -, hx⟩ := nonempty_inter_closedPoints (X := X.obj.left) Set.univ_nonempty
    isClosed_univ.isLocallyClosed
  obtain ⟨y, -⟩ := (mem_range_analytificationπ_base_iff X x).2 hx
  exact ⟨y⟩

/-- **The analytification of an integral scheme locally of finite type over `ℂ` is
connected.** -/
theorem preconnectedSpace_analytification_of_isIntegral (X : SchemeLFTℂ.{u})
    [IsIntegral X.obj.left] : PreconnectedSpace (analytification.obj X) := by
  obtain ⟨x⟩ := (inferInstance : Nonempty X.obj.left)
  obtain ⟨U, hU⟩ := exists_affineOpens_mem X.obj.left x
  haveI : IsAffine (X.restrict U).obj.left := U.2
  haveI : Nonempty (X.restrict U).obj.left := ⟨⟨x, hU⟩⟩
  haveI : IsOpenImmersion (X.restrictι U).hom.left :=
    (inferInstance : IsOpenImmersion (U : X.obj.left.Opens).ι)
  haveI : IsIntegral (X.restrict U).obj.left :=
    isIntegral_of_isOpenImmersion (X.restrictι U).hom.left
  haveI := preconnectedSpace_analytification_of_isAffine (X.restrict U)
  have hd : DenseRange (analytification.map (X.restrictι U)).toLRSHom.base := by
    rw [DenseRange, range_analytification_map_restrictι]
    exact dense_preimage_analytificationπ X ⟨x, hU⟩
  exact hd.preconnectedSpace (analytification.map (X.restrictι U)).toLRSHom.base.hom.continuous

/-! ### The general case -/

variable (X : SchemeLFTℂ.{u})

/-- The analytification of the reduced closed subscheme on an irreducible closed subset is
preconnected. -/
lemma preconnectedSpace_analytification_reducedSubscheme (Z : Closeds X.obj.left)
    (hZ : IsIrreducible (Z : Set X.obj.left)) :
    PreconnectedSpace (analytification.obj (X.reducedSubscheme Z)) := by
  set Y := X.reducedSubscheme Z
  have hι : IsClosedEmbedding (X.reducedSubschemeι Z).hom.left.base :=
    (X.reducedSubschemeι Z).hom.left.isClosedEmbedding
  have hr : IsIrreducible (Set.range (X.reducedSubschemeι Z).hom.left.base) := by
    rw [X.range_reducedSubschemeι Z]
    exact hZ
  haveI := Subtype.irreducibleSpace hr
  haveI : IrreducibleSpace Y.obj.left := hι.isEmbedding.toHomeomorph.irreducibleSpace_iff.2 ‹_›
  haveI : IsReduced Y.obj.left := inferInstanceAs (IsReduced (X.reducedSubscheme Z).obj.left)
  haveI : IsIntegral Y.obj.left := isIntegral_of_irreducibleSpace_of_isReduced Y.obj.left
  exact preconnectedSpace_analytification_of_isIntegral Y

/-- **The analytification of a connected scheme locally of finite type over `ℂ` is
connected.** -/
theorem connectedSpace_analytification [ConnectedSpace X.obj.left] :
    ConnectedSpace (analytification.obj X) := by
  haveI := nonempty_analytification X
  obtain ⟨y₀⟩ := (inferInstance : Nonempty (analytification.obj X))
  have hlift (a : X.obj.left) (ha : IsClosed {a}) :
      ∃ y, (analytificationπ X).left.base y = a :=
    (mem_range_analytificationπ_base_iff X a).2 ha
  have key (c : X.obj.left) (hc : Relation.ReflTransGen (fun a b : X.obj.left ↦
      IsClosed {a} ∧ IsClosed {b} ∧ ∃ Z ∈ irreducibleComponents X.obj.left, a ∈ Z ∧ b ∈ Z)
      ((analytificationπ X).left.base y₀) c) :
      ∀ y, (analytificationπ X).left.base y = c → y ∈ connectedComponent y₀ := by
    induction hc with
    | refl =>
      intro y hy
      rw [analytificationπ_base_injective X hy]
      exact mem_connectedComponent
    | @tail a b _ hab ih =>
      obtain ⟨ha, hb, Z, hZ, haZ, hbZ⟩ := hab
      intro yb hyb
      obtain ⟨ya, hya⟩ := hlift a ha
      set Zc : Closeds X.obj.left := ⟨Z, isClosed_of_mem_irreducibleComponents Z hZ⟩
      set ι := X.reducedSubschemeι Zc
      have hinj : Function.Injective ι.hom.left.base := ι.hom.left.isClosedEmbedding.injective
      haveI := preconnectedSpace_analytification_reducedSubscheme X Zc hZ.1
      have hS := isPreconnected_range (analytification.map ι).toLRSHom.base.hom.continuous
      have hmem (c : X.obj.left) (hc : IsClosed {c}) (hcZ : c ∈ Z) (yc : analytification.obj X)
          (hyc : (analytificationπ X).left.base yc = c) :
          yc ∈ Set.range (analytification.map ι).toLRSHom.base := by
        have hcZ' : c ∈ Set.range ι.hom.left.base := by
          rw [X.range_reducedSubschemeι Zc]
          exact hcZ
        obtain ⟨c', rfl⟩ := hcZ'
        have hc' : IsClosed {c'} := by
          have := hc.preimage ι.hom.left.base.hom.continuous
          rwa [← Set.image_singleton, hinj.preimage_image] at this
        obtain ⟨y', hy'⟩ := (mem_range_analytificationπ_base_iff _ c').2 hc'
        refine ⟨y', analytificationπ_base_injective X ?_⟩
        rw [analytificationπ_base_map_apply, hy', hyc]
      exact (connectedComponent_eq (ih ya hya)).superset
        (hS.subset_connectedComponent (hmem a ha haZ ya hya) (hmem b hb hbZ yb hyb))
  refine connectedSpace_iff_connectedComponent.2 ⟨y₀, Set.eq_univ_of_forall fun y ↦ ?_⟩
  exact key _ (Scheme.reflTransGen_irreducibleComponents X.obj.left
    ((mem_range_analytificationπ_base_iff X _).1 ⟨y₀, rfl⟩)
    ((mem_range_analytificationπ_base_iff X _).1 ⟨y, rfl⟩)) y rfl

/-- **The analytification preserves connectedness.** -/
theorem analytificationPreservesConnected : AnalytificationPreservesConnected.{u} :=
  fun Y _ ↦ connectedSpace_analytification Y

end

end ComplexAnalytic
