/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Mathlib.RingTheory.Polynomial.Resultant.Basic
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.Combinatorics.Pigeonhole

/-!
# Common roots of complex polynomials detected by resultants

For a monic `w ∈ ℂ[X]` and finitely many `b₀, …, b_{r-1} ∈ ℂ[X]`, a common root of `w` and all
`bᵢ` is detected by the vanishing of finitely many resultants, namely those of `w` with the
combinations `∑ᵢ sⁱ bᵢ` for `s = 0, …, deg w * r`. These resultants are universal polynomial
expressions in the coefficients, which is what makes them usable for families of polynomials
depending on parameters.

## Main results

- `Polynomial.exists_isRoot_of_resultant_eq_zero`: if `Res(w, b) = 0` (with any size bound for
  `b`) then `w` and `b` have a common root.
- `Polynomial.exists_common_root_of_forall_resultant_eq_zero`: the version for several `bᵢ`.
- `Polynomial.mem_span_of_resultant`: over any commutative ring, `C (Res(w, b))` lies in the
  ideal generated by `w` and `b`.
- `Polynomial.norm_lt_of_isRoot`: a root bound for monic polynomials with small lower
  coefficients.
-/

open Finset

namespace Polynomial

/-- The resultant of `w` and `b`, with sizes `m ≥ deg w` and `n ≥ deg b` not both zero, lies in
the ideal generated by `w` and `b`. -/
theorem mem_span_of_resultant {R : Type*} [CommRing R] (w b : R[X]) {m n : ℕ}
    (hw : w.natDegree ≤ m) (hb : b.natDegree ≤ n) (hmn : m ≠ 0 ∨ n ≠ 0) :
    C (resultant w b m n) ∈ Ideal.span {w, b} := by
  obtain ⟨p, q, -, -, e⟩ := exists_mul_add_mul_eq_C_resultant w b hw hb hmn
  rw [← e]
  exact Ideal.add_mem _ (Ideal.mul_mem_right _ _ (Ideal.subset_span (by simp)))
    (Ideal.mul_mem_right _ _ (Ideal.subset_span (by simp)))

/-- If the resultant of a monic complex polynomial `w` and a polynomial `b`, computed with any
size bound `n ≥ deg b`, vanishes, then `w` and `b` have a common root. -/
theorem exists_isRoot_of_resultant_eq_zero {w b : ℂ[X]} (hw : w.Monic) {n : ℕ}
    (hb : b.natDegree ≤ n) (h : resultant w b w.natDegree n = 0) :
    ∃ t, w.IsRoot t ∧ b.IsRoot t := by
  by_contra hne
  push Not at hne
  have hcop : IsCoprime w b := by
    rw [isCoprime_iff_aeval_ne_zero_of_isAlgClosed ℂ ℂ]
    intro a
    by_contra hc
    push Not at hc
    exact hne a (by simpa using hc.1) (by simpa using hc.2)
  have hu := (isUnit_resultant_iff_isCoprime hw).mpr hcop
  obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le hb
  rw [resultant_add_right_deg _ _ _ _ k le_rfl, hw.coeff_natDegree, one_pow, one_mul] at h
  exact hu.ne_zero h

/-- A common root of a monic complex polynomial `w` of degree `d` and of polynomials
`b₀, …, b_{r-1}` exists as soon as the resultants of `w` with the combinations `∑ᵢ sⁱ bᵢ`
vanish for `s = 0, …, d * r`. -/
theorem exists_common_root_of_forall_resultant_eq_zero {r : ℕ} {w : ℂ[X]} (hw : w.Monic)
    (b : Fin r → ℂ[X]) {n : ℕ} (hb : ∀ i, (b i).natDegree ≤ n)
    (h : ∀ s ∈ range (w.natDegree * r + 1),
      resultant w (∑ i : Fin r, C ((s : ℂ) ^ (i : ℕ)) * b i) w.natDegree n = 0) :
    ∃ t, w.IsRoot t ∧ ∀ i, (b i).IsRoot t := by
  classical
  have hdeg : ∀ s : ℕ, (∑ i : Fin r, C ((s : ℂ) ^ (i : ℕ)) * b i).natDegree ≤ n := fun s ↦
    (natDegree_sum_le_of_forall_le _ _ fun i _ ↦ (natDegree_C_mul_le _ _).trans (hb i))
  choose! t ht using fun s hs ↦ exists_isRoot_of_resultant_eq_zero hw (hdeg s) (h s hs)
  have hmaps : ∀ s ∈ range (w.natDegree * r + 1), t s ∈ w.roots.toFinset := fun s hs ↦
    Multiset.mem_toFinset.mpr ((mem_roots hw.ne_zero).mpr (ht s hs).1)
  have hcard : #w.roots.toFinset * r < #(range (w.natDegree * r + 1)) := by
    rw [card_range]
    exact Nat.lt_succ_of_le (Nat.mul_le_mul_right _
      ((Multiset.toFinset_card_le _).trans (card_roots' w)))
  obtain ⟨y, hy, hfib⟩ := exists_lt_card_fiber_of_mul_lt_card_of_maps_to hmaps hcard
  refine ⟨y, (mem_roots hw.ne_zero).mp (Multiset.mem_toFinset.mp hy), fun i ↦ ?_⟩
  -- the polynomial `Y ↦ ∑ᵢ bᵢ(y) Yⁱ` has degree `< r` and more than `r` roots
  set Q : ℂ[X] := ∑ j : Fin r, C ((b j).eval y) * X ^ (j : ℕ) with hQ
  have hQdeg : Q.natDegree < r := by
    rcases Nat.eq_zero_or_pos r with rfl | hr
    · exact absurd i.2 (Nat.not_lt_zero _)
    refine lt_of_le_of_lt (natDegree_sum_le_of_forall_le _ _ fun j _ ↦ ?_) (Nat.sub_lt hr one_pos)
    exact (natDegree_C_mul_X_pow_le _ _).trans (Nat.le_sub_one_of_lt j.2)
  set S : Finset ℂ := ((range (w.natDegree * r + 1)).filter fun s ↦ t s = y).image
    (fun s : ℕ ↦ (s : ℂ)) with hS
  have hScard : #S = #((range (w.natDegree * r + 1)).filter fun s ↦ t s = y) :=
    card_image_of_injective _ Nat.cast_injective
  have hQ0 : Q = 0 := by
    refine eq_zero_of_natDegree_lt_card_of_eval_eq_zero' Q S (fun c hc ↦ ?_) (by omega)
    obtain ⟨s, hs, rfl⟩ := mem_image.mp hc
    obtain ⟨hs1, hs2⟩ := mem_filter.mp hs
    have := (ht s hs1).2
    rw [hs2, IsRoot, eval_finsetSum] at this
    rw [hQ, eval_finsetSum, ← this]
    refine sum_congr rfl fun j _ ↦ ?_
    rw [eval_mul, eval_mul, eval_C, eval_C, eval_pow, eval_X, mul_comm]
  have := congrArg (coeff · (i : ℕ)) hQ0
  simp only [hQ, finsetSum_coeff, coeff_C_mul_X_pow, coeff_zero] at this
  rw [sum_eq_single i (fun j _ hj ↦ if_neg (fun h ↦ hj (Fin.ext h.symm))) (by simp),
    if_pos rfl] at this
  exact this

/-- A root of a monic complex polynomial whose lower coefficients satisfy
`∑_{i < d} ‖cᵢ‖ εⁱ < εᵈ` has norm less than `ε`. -/
theorem norm_lt_of_isRoot {w : ℂ[X]} (hw : w.Monic) {ε : ℝ} (hε : 0 < ε)
    (hsmall : ∑ i ∈ range w.natDegree, ‖w.coeff i‖ * ε ^ i < ε ^ w.natDegree) {t : ℂ}
    (ht : w.IsRoot t) : ‖t‖ < ε := by
  by_contra hle
  push Not at hle
  set d := w.natDegree
  have heval : t ^ d = -∑ i ∈ range d, w.coeff i * t ^ i := by
    have := ht.eq_zero
    rw [eval_eq_sum_range, sum_range_succ, hw.coeff_natDegree, one_mul] at this
    linear_combination this
  set ρ := ‖t‖ / ε
  have hρ : 1 ≤ ρ := (one_le_div hε).mpr hle
  have htρ : ‖t‖ = ρ * ε := by rw [div_mul_cancel₀ _ hε.ne']
  have hbound : ‖t‖ ^ d ≤ ρ ^ d * ∑ i ∈ range d, ‖w.coeff i‖ * ε ^ i := by
    calc ‖t‖ ^ d = ‖∑ i ∈ range d, w.coeff i * t ^ i‖ := by rw [← norm_pow, heval, norm_neg]
      _ ≤ ∑ i ∈ range d, ‖w.coeff i‖ * ‖t‖ ^ i := by
          refine (norm_sum_le _ _).trans (le_of_eq (sum_congr rfl fun i _ ↦ ?_))
          rw [norm_mul, norm_pow]
      _ ≤ ∑ i ∈ range d, ρ ^ d * (‖w.coeff i‖ * ε ^ i) := by
          refine sum_le_sum fun i hi ↦ ?_
          rw [htρ, mul_pow]
          have : ρ ^ i ≤ ρ ^ d := pow_le_pow_right₀ hρ (mem_range.mp hi).le
          have h0 : 0 ≤ ‖w.coeff i‖ * ε ^ i := mul_nonneg (norm_nonneg _) (pow_pos hε i).le
          calc ‖w.coeff i‖ * (ρ ^ i * ε ^ i) = ρ ^ i * (‖w.coeff i‖ * ε ^ i) := by ring
            _ ≤ ρ ^ d * (‖w.coeff i‖ * ε ^ i) := mul_le_mul_of_nonneg_right this h0
      _ = ρ ^ d * ∑ i ∈ range d, ‖w.coeff i‖ * ε ^ i := by rw [mul_sum]
  have hpos : 0 < ρ ^ d := pow_pos (by linarith) d
  have := mul_lt_mul_of_pos_left hsmall hpos
  rw [htρ, mul_pow] at hbound
  linarith

end Polynomial
