/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.Nullstellensatz.Lifting
import Mathlib.RingTheory.Ideal.GoingUp
import Oka.Nullstellensatz

/-!
# The Rückert Nullstellensatz for germs

Let `f₁, …, f_r` be germs at the origin of holomorphic functions on `ℂⁿ`. If a germ `g` vanishes
near the origin at every point at which all `fᵢ` vanish, then some power of `g` lies in the ideal
generated by the `fᵢ` (`LocalOkaRing.mem_radical_span_of_eventually`).

The zero locus is described by a generating family rather than by the ideal itself, since the
value of a germ at a point is only meaningful close enough to the origin, depending on the germ.

## Strategy

The heart of the proof is `LocalOkaRing.frequently_forall_eval_eq_zero_and_ne_zero`: if `P` is
a prime ideal generated by `f₁, …, f_r` and `g ∉ P`, then there are points arbitrarily close to
the origin at which all `fᵢ` vanish but `g` does not. This is proved by induction on `n`. If
`P = 0` it is the identity theorem. Otherwise, after a linear change of coordinates, `P` contains
a Weierstrass polynomial `W` in the last variable, so `𝒪_{n+1}/P` is finite over `𝒪_n`. Since it
is a domain, the nonzero element `g` divides modulo `P` a germ `c` of `𝒪_n` not in the
elimination ideal `P' = P ∩ 𝒪_n` (going up). By induction there are points `a` near the origin in
the zero locus of `P'` with `c(a) ≠ 0`, and these lift to points `(a, t)` in the zero locus of
`P` (`LocalOkaRing.eventually_exists_lift`), at which `g` cannot vanish.

## Main results

- `LocalOkaRing.frequently_forall_eval_eq_zero_and_ne_zero`: the statement above.
- `LocalOkaRing.mem_radical_span_of_eventually`: **the Rückert Nullstellensatz**, for germs in any
  finite set of variables; `LocalOkaRing.mem_radical_span_of_eventually_fin` is the case of
  `Fin n`.
- `OkaRing.germ_mem_radical_span_of_eventually`: the same for holomorphic functions on an open
  set, at any point of it.
-/

open Filter Topology Polynomial

namespace LocalOkaRing

variable {n : ℕ}

/-- If the prime ideal `P` of germs in `n + 1` variables contains a Weierstrass polynomial in the
last variable and `g ∉ P`, then modulo `P` the germ `g` divides a germ in the first `n`
variables which does not lie in `P`. -/
theorem exists_incl_sub_mul_mem {W : (LocalOkaRing (Fin n))[X]}
    (hW : IsLocalWeierstrassPolynomial
      (W.map (Subring.subtype (localOkaSubring (Fin n)).toSubring)))
    {P : Ideal (LocalOkaRing (Fin (n + 1)))} [P.IsPrime] (hWP : fromPolynomial W ∈ P)
    {g : LocalOkaRing (Fin (n + 1))} (hg : g ∉ P) :
    ∃ (c : LocalOkaRing (Fin n)) (h : LocalOkaRing (Fin (n + 1))), incl c ∉ P ∧
      incl c - g * h ∈ P := by
  haveI := module_finite_quotient_fromPolynomial hW
  have hle : Ideal.span {fromPolynomial W} ≤ P := (Ideal.span_singleton_le_iff_mem P).mpr hWP
  haveI : Module.Finite (LocalOkaRing (Fin n)) (LocalOkaRing (Fin (n + 1)) ⧸ P) :=
    Module.Finite.of_surjective
      (Ideal.Quotient.factorₐ (LocalOkaRing (Fin n)) hle).toLinearMap
      (Ideal.Quotient.factor_surjective hle)
  have hint : IsIntegral (LocalOkaRing (Fin n)) (Ideal.Quotient.mk P g) :=
    Algebra.IsIntegral.isIntegral _
  have hne : Ideal.Quotient.mk P g ≠ 0 := by rwa [Ne, Ideal.Quotient.eq_zero_iff_mem]
  have hlt := Ideal.comap_lt_comap_of_integral_mem_sdiff (R := LocalOkaRing (Fin n))
    (I := (⊥ : Ideal (LocalOkaRing (Fin (n + 1)) ⧸ P)))
    (J := Ideal.span {Ideal.Quotient.mk P g}) bot_le
    ⟨Ideal.mem_span_singleton_self _, hne⟩ hint
  obtain ⟨c, hcJ, hcI⟩ := SetLike.exists_of_lt hlt
  have halg : ∀ x, algebraMap (LocalOkaRing (Fin n)) (LocalOkaRing (Fin (n + 1)) ⧸ P) x =
      Ideal.Quotient.mk P (incl x) := fun x ↦ by
    change Ideal.Quotient.mk P (fromPolynomial (C x)) = _
    rw [fromPolynomial_C]
  rw [Ideal.mem_comap, Ideal.mem_span_singleton'] at hcJ
  obtain ⟨y, hy⟩ := hcJ
  obtain ⟨h, rfl⟩ := Ideal.Quotient.mk_surjective y
  refine ⟨c, h, fun hc ↦ hcI ?_, ?_⟩
  · rw [Ideal.mem_comap, halg, Ideal.mem_bot, Ideal.Quotient.eq_zero_iff_mem]
    exact hc
  · rw [← Ideal.Quotient.eq_zero_iff_mem, map_sub, map_mul, ← halg, ← hy]
    ring

section Frequently

variable {ι : Type*}

/-- The statement of `frequently_forall_eval_eq_zero_and_ne_zero` for the zero ideal: the
identity theorem. -/
theorem frequently_of_eq_bot [Finite ι] {r : ℕ} {f : Fin r → LocalOkaRing ι}
    (hf : Ideal.span (Set.range f) = ⊥) {g : LocalOkaRing ι} (hg : g ≠ 0) :
    ∃ᶠ z in 𝓝 (0 : ι → ℂ), (∀ i, ((f i : LocalOkaRing ι) : MvPowerSeries ι ℂ).eval z = 0) ∧
      (g : MvPowerSeries ι ℂ).eval z ≠ 0 := by
  have hf0 : ∀ i, f i = 0 := fun i ↦ by
    rw [← Ideal.mem_bot, ← hf]
    exact Ideal.subset_span ⟨i, rfl⟩
  have hfreq : ∃ᶠ z in 𝓝 (0 : ι → ℂ), (g : MvPowerSeries ι ℂ).eval z ≠ 0 :=
    fun h ↦ hg (eq_zero_of_eventually_eval_eq_zero (by simpa using h))
  refine hfreq.mono fun z hz ↦ ⟨fun i ↦ ?_, hz⟩
  rw [hf0 i, ZeroMemClass.coe_zero, MvPowerSeries.eval_of_zero]

/-- Points of the zero locus near the origin at which `g` does not vanish can be found after a
linear change of coordinates. -/
theorem frequently_of_congr [Fintype ι] (φ : (ι → ℂ) ≃L[ℂ] (ι → ℂ)) {r : ℕ}
    (f : Fin r → LocalOkaRing ι) (g : LocalOkaRing ι)
    (h : ∃ᶠ z in 𝓝 (0 : ι → ℂ),
      (∀ i, ((congr φ (f i) : LocalOkaRing ι) : MvPowerSeries ι ℂ).eval z = 0) ∧
        ((congr φ g : LocalOkaRing ι) : MvPowerSeries ι ℂ).eval z ≠ 0) :
    ∃ᶠ z in 𝓝 (0 : ι → ℂ), (∀ i, ((f i : LocalOkaRing ι) : MvPowerSeries ι ℂ).eval z = 0) ∧
      (g : MvPowerSeries ι ℂ).eval z ≠ 0 := by
  have hE : ∀ P : LocalOkaRing ι, ∀ᶠ z in 𝓝 (0 : ι → ℂ),
      ((congr φ P : LocalOkaRing ι) : MvPowerSeries ι ℂ).eval z =
        (P : MvPowerSeries ι ℂ).eval (φ.symm z) := fun P ↦
    (congr_represents (φ := φ) P.2.represents_eval).eval_eq
  have h' : ∃ᶠ z in 𝓝 (0 : ι → ℂ),
      (∀ i, ((f i : LocalOkaRing ι) : MvPowerSeries ι ℂ).eval (φ.symm z) = 0) ∧
        (g : MvPowerSeries ι ℂ).eval (φ.symm z) ≠ 0 := by
    refine (h.and_eventually ((eventually_all.mpr fun i ↦ hE (f i)).and (hE g))).mono ?_
    rintro z ⟨⟨hf, hg⟩, hEf, hEg⟩
    exact ⟨fun i ↦ (hEf i) ▸ hf i, hEg ▸ hg⟩
  have ht : Tendsto φ.symm (𝓝 0) (𝓝 0) := by
    simpa using φ.symm.continuous.tendsto (0 : ι → ℂ)
  exact ht.frequently h'

end Frequently

/-- The inductive step of `frequently_forall_eval_eq_zero_and_ne_zero`, in the situation where
the prime ideal contains a Weierstrass polynomial in the last variable. -/
theorem frequently_step
    (IH : ∀ (P : Ideal (LocalOkaRing (Fin n))) [P.IsPrime] {r : ℕ}
      (f : Fin r → LocalOkaRing (Fin n)), Ideal.span (Set.range f) = P →
      ∀ {g : LocalOkaRing (Fin n)}, g ∉ P →
        ∃ᶠ z in 𝓝 (0 : Fin n → ℂ),
          (∀ i, ((f i : LocalOkaRing (Fin n)) : MvPowerSeries (Fin n) ℂ).eval z = 0) ∧
            (g : MvPowerSeries (Fin n) ℂ).eval z ≠ 0)
    {P : Ideal (LocalOkaRing (Fin (n + 1)))} [P.IsPrime] {r : ℕ}
    (f : Fin r → LocalOkaRing (Fin (n + 1))) (hf : Ideal.span (Set.range f) = P)
    {W : (LocalOkaRing (Fin n))[X]}
    (hW : IsLocalWeierstrassPolynomial
      (W.map (Subring.subtype (localOkaSubring (Fin n)).toSubring)))
    (hWP : fromPolynomial W ∈ P) {g : LocalOkaRing (Fin (n + 1))} (hg : g ∉ P) :
    ∃ᶠ z in 𝓝 (0 : Fin (n + 1) → ℂ),
      (∀ i, ((f i : LocalOkaRing (Fin (n + 1))) : MvPowerSeries (Fin (n + 1)) ℂ).eval z = 0) ∧
        (g : MvPowerSeries (Fin (n + 1)) ℂ).eval z ≠ 0 := by
  classical
  obtain ⟨c, h, hcP, hch⟩ := exists_incl_sub_mul_mem hW hWP hg
  -- generators of the elimination ideal
  obtain ⟨m, p, hp⟩ := Submodule.fg_iff_exists_fin_generating_family.mp
    (IsNoetherian.noetherian (P.comap (incl (n := n))))
  have hIH := IH (P.comap (incl (n := n))) p hp (g := c) (by rwa [Ideal.mem_comap])
  -- `incl c = g h + ∑ kᵢ fᵢ`
  rw [← hf] at hch
  obtain ⟨k, hk⟩ := (Submodule.mem_span_range_iff_exists_fun
    (R := LocalOkaRing (Fin (n + 1)))).mp hch
  have hE : ∀ᶠ z in 𝓝 (0 : Fin (n + 1) → ℂ),
      ((incl c : LocalOkaRing (Fin (n + 1))) : MvPowerSeries (Fin (n + 1)) ℂ).eval z =
        (g : MvPowerSeries (Fin (n + 1)) ℂ).eval z *
          (h : MvPowerSeries (Fin (n + 1)) ℂ).eval z +
        ∑ i, ((k i : LocalOkaRing (Fin (n + 1))) : MvPowerSeries (Fin (n + 1)) ℂ).eval z *
          ((f i : LocalOkaRing (Fin (n + 1))) : MvPowerSeries (Fin (n + 1)) ℂ).eval z := by
    filter_upwards [g.locallyConvergent, h.locallyConvergent,
      eventually_all.mpr fun i ↦ (k i).locallyConvergent,
      eventually_all.mpr fun i ↦ (f i).locallyConvergent] with z hgz hhz hkz hfz
    have hsum : incl c = g * h + ∑ i, k i * f i := by
      rw [← sub_eq_iff_eq_add', ← hk]
      rfl
    rw [hsum, AddMemClass.coe_add, MulMemClass.coe_mul, AddSubmonoidClass.coe_finsetSum,
      MvPowerSeries.eval_add_of_summableAt (hgz.mul hhz)
        (MvPowerSeries.SummableAt.sum (P := fun i ↦
          ((k i * f i : LocalOkaRing (Fin (n + 1))) : MvPowerSeries (Fin (n + 1)) ℂ))
          fun i _ ↦ (hkz i).mul (hfz i)),
      MvPowerSeries.eval_mul_of_summableAt hgz hhz,
      MvPowerSeries.eval_sum_of_summableAt (P := fun i ↦
        ((k i * f i : LocalOkaRing (Fin (n + 1))) : MvPowerSeries (Fin (n + 1)) ℂ))
        (fun i _ ↦ (hkz i).mul (hfz i))]
    congr 1
    refine Finset.sum_congr rfl fun i _ ↦ ?_
    rw [MulMemClass.coe_mul, MvPowerSeries.eval_mul_of_summableAt (hkz i) (hfz i)]
  rw [Filter.frequently_iff]
  intro U hU
  have hL := eventually_exists_lift hW f (hf ▸ hWP) p (by rw [hf]; exact hp.ge)
    (inter_mem hU hE)
  obtain ⟨a, ⟨hpa, hca⟩, hlift⟩ := (hIH.and_eventually hL).exists
  obtain ⟨t, ⟨htU, htE⟩, hft⟩ := hlift hpa
  refine ⟨Fin.snoc a t, htU, hft, fun hgz ↦ hca ?_⟩
  have hsnoc : (fun j : Fin n ↦ (Fin.snoc a t : Fin (n + 1) → ℂ) j.castSucc) = a :=
    funext fun j ↦ by simp [Fin.snoc_castSucc]
  have := htE
  simp only [Set.mem_setOf_eq, eval_incl, hsnoc, hgz, zero_mul, hft, mul_zero,
    Finset.sum_const_zero, add_zero] at this
  exact this

/-- **Points of a germ of an analytic set avoiding a hypersurface.** If `P` is a prime ideal of
germs generated by `f₁, …, f_r` and `g ∉ P`, then there are points arbitrarily close to the
origin at which all `fᵢ` vanish but `g` does not. -/
theorem frequently_forall_eval_eq_zero_and_ne_zero :
    ∀ {n : ℕ} (P : Ideal (LocalOkaRing (Fin n))) [P.IsPrime] {r : ℕ}
      (f : Fin r → LocalOkaRing (Fin n)), Ideal.span (Set.range f) = P →
      ∀ {g : LocalOkaRing (Fin n)}, g ∉ P →
        ∃ᶠ z in 𝓝 (0 : Fin n → ℂ),
          (∀ i, ((f i : LocalOkaRing (Fin n)) : MvPowerSeries (Fin n) ℂ).eval z = 0) ∧
            (g : MvPowerSeries (Fin n) ℂ).eval z ≠ 0
  | 0, P, _, r, f, hf, g, hg => by
    have hP : P = ⊥ := by
      refine (Submodule.eq_bot_iff P).mpr fun x hx ↦ by_contra fun hx0 ↦ ?_
      exact Ideal.IsPrime.ne_top ‹_› (Ideal.eq_top_of_isUnit_mem P hx
        (isUnit_iff_ne_zero.mpr hx0))
    exact frequently_of_eq_bot (hf.trans hP) fun h ↦ hg (h ▸ zero_mem P)
  | n + 1, P, _, r, f, hf, g, hg => by
    by_cases hP : P = ⊥
    · exact frequently_of_eq_bot (hf.trans hP) fun h ↦ hg (h ▸ zero_mem P)
    obtain ⟨f₀, hf₀P, hf₀⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hP
    obtain ⟨φ, u, hu, W, hW, heq⟩ := exists_congr_localweierstrass_preparation hf₀
    set e := congr φ
    haveI : (P.map e).IsPrime := Ideal.map_isPrime_of_equiv e
    have hf' : Ideal.span (Set.range fun i ↦ e (f i)) = P.map e := by
      rw [← hf, Ideal.map_span, ← Set.range_comp]
      rfl
    have hWP : fromPolynomial W ∈ P.map e := by
      have h1 : fromPolynomial W * u ∈ P.map e := heq ▸ Ideal.mem_map_of_mem e hf₀P
      refine (Ideal.IsPrime.mem_or_mem ‹_› h1).resolve_right fun hu' ↦ ?_
      exact Ideal.IsPrime.ne_top ‹_› (Ideal.eq_top_of_isUnit_mem _ hu' hu)
    have hg' : e g ∉ P.map e := by
      rw [Ideal.mem_map_of_equiv]
      rintro ⟨x, hx, hxe⟩
      exact hg (e.injective hxe ▸ hx)
    exact frequently_of_congr φ f g (frequently_step
      (fun P _ r f hf g hg ↦ frequently_forall_eval_eq_zero_and_ne_zero P f hf hg)
      (fun i ↦ e (f i)) hf' hW hWP hg')

/-- **The Rückert Nullstellensatz.** If a germ `g` vanishes, near the origin, at every point at
which the germs `f₁, …, f_r` all vanish, then some power of `g` lies in the ideal generated by
the `fᵢ`. -/
theorem mem_radical_span_of_eventually_fin {r : ℕ} (f : Fin r → LocalOkaRing (Fin n))
    {g : LocalOkaRing (Fin n)}
    (h : ∀ᶠ z in 𝓝 (0 : Fin n → ℂ),
      (∀ i, ((f i : LocalOkaRing (Fin n)) : MvPowerSeries (Fin n) ℂ).eval z = 0) →
        (g : MvPowerSeries (Fin n) ℂ).eval z = 0) :
    g ∈ (Ideal.span (Set.range f)).radical := by
  by_contra hg
  rw [Ideal.radical_eq_sInf, Submodule.mem_sInf] at hg
  push Not at hg
  obtain ⟨P, ⟨hIP, hPprime⟩, hgP⟩ := hg
  obtain ⟨m, p, hp⟩ := Submodule.fg_iff_exists_fin_generating_family.mp
    (IsNoetherian.noetherian P)
  have hF : Ideal.span (Set.range (Fin.append p f)) = P := by
    refine le_antisymm (Ideal.span_le.mpr ?_) (hp ▸ Ideal.span_mono ?_)
    · rintro _ ⟨k, rfl⟩
      refine Fin.addCases (fun j ↦ ?_) (fun i ↦ ?_) k
      · rw [Fin.append_left, ← hp]
        exact Ideal.subset_span ⟨j, rfl⟩
      · rw [Fin.append_right]
        exact hIP (Ideal.subset_span ⟨i, rfl⟩)
    · rintro _ ⟨j, rfl⟩
      exact ⟨Fin.castAdd r j, Fin.append_left p f j⟩
  obtain ⟨z, ⟨hFz, hgz⟩, hz⟩ :=
    ((frequently_forall_eval_eq_zero_and_ne_zero P (Fin.append p f) hF hgP).and_eventually
      h).exists
  exact hgz (hz fun i ↦ by simpa using hFz (Fin.natAdd m i))

/-- **The Rückert Nullstellensatz**, for germs in an arbitrary finite set of variables: if a
germ `g` vanishes, near the origin, at every point at which the germs `f₁, …, f_r` all vanish,
then some power of `g` lies in the ideal generated by the `fᵢ`. -/
theorem mem_radical_span_of_eventually {ι : Type*} [Finite ι] {r : ℕ}
    (f : Fin r → LocalOkaRing ι) {g : LocalOkaRing ι}
    (h : ∀ᶠ z in 𝓝 (0 : ι → ℂ),
      (∀ i, ((f i : LocalOkaRing ι) : MvPowerSeries ι ℂ).eval z = 0) →
        (g : MvPowerSeries ι ℂ).eval z = 0) :
    g ∈ (Ideal.span (Set.range f)).radical := by
  haveI := Fintype.ofFinite ι
  set φ : (ι → ℂ) ≃L[ℂ] (Fin (Fintype.card ι) → ℂ) :=
    (LinearEquiv.funCongrLeft ℂ ℂ (Fintype.equivFin ι).symm).toContinuousLinearEquiv
  have hE : ∀ P : LocalOkaRing ι, ∀ᶠ z in 𝓝 (0 : Fin (Fintype.card ι) → ℂ),
      ((congr φ P : LocalOkaRing (Fin (Fintype.card ι))) :
        MvPowerSeries (Fin (Fintype.card ι)) ℂ).eval z =
        (P : MvPowerSeries ι ℂ).eval (φ.symm z) := fun P ↦
    (congr_represents (φ := φ) P.2.represents_eval).eval_eq
  have ht : Tendsto φ.symm (𝓝 0) (𝓝 0) := by
    simpa using φ.symm.continuous.tendsto (0 : Fin (Fintype.card ι) → ℂ)
  have h' : ∀ᶠ z in 𝓝 (0 : Fin (Fintype.card ι) → ℂ),
      (∀ i, ((congr φ (f i) : LocalOkaRing (Fin (Fintype.card ι))) :
        MvPowerSeries (Fin (Fintype.card ι)) ℂ).eval z = 0) →
        ((congr φ g : LocalOkaRing (Fin (Fintype.card ι))) :
          MvPowerSeries (Fin (Fintype.card ι)) ℂ).eval z = 0 := by
    filter_upwards [ht.eventually h, eventually_all.mpr fun i ↦ hE (f i), hE g]
      with z hz hf hg hvan
    rw [hg]
    exact hz fun i ↦ (hf i) ▸ hvan i
  obtain ⟨k, hk⟩ := mem_radical_span_of_eventually_fin (fun i ↦ congr φ (f i)) h'
  refine ⟨k, ?_⟩
  have := Ideal.mem_map_of_mem (congr φ).symm hk
  rw [Ideal.map_span, ← Set.range_comp, map_pow, AlgEquiv.symm_apply_apply] at this
  convert this using 3
  funext i
  exact ((congr φ).symm_apply_apply (f i)).symm

end LocalOkaRing

namespace OkaRing

/-- **The Rückert Nullstellensatz for holomorphic functions.** Let `F₁, …, F_r` and `G` be
holomorphic functions on an open set `U ∋ w`. If `G` vanishes near `w` wherever all `Fᵢ`
vanish, then some power of the germ of `G` at `w` lies in the ideal generated by the germs of
the `Fᵢ`. -/
theorem germ_mem_radical_span_of_eventually {ι : Type*} [Fintype ι]
    {U : TopologicalSpace.Opens (ι → ℂ)} {w : ι → ℂ} (hw : w ∈ U) {r : ℕ}
    (F : Fin r → OkaRing U) (G : OkaRing U)
    (h : ∀ᶠ y in 𝓝 w, (∀ i, (F i).toGlobalFun _ y = 0) → G.toGlobalFun _ y = 0) :
    germ hw G ∈ (Ideal.span (Set.range fun i ↦ germ hw (F i))).radical := by
  refine LocalOkaRing.mem_radical_span_of_eventually _ ?_
  have ht : Tendsto (fun z : ι → ℂ ↦ z + w) (𝓝 0) (𝓝 w) := by
    have := (continuous_add_const w).tendsto (0 : ι → ℂ)
    rwa [zero_add] at this
  filter_upwards [ht.eventually h, eventually_all.mpr fun i ↦ (germ_represents hw (F i)).eval_eq,
    (germ_represents hw G).eval_eq] with z hz hF hG hvan
  rw [hG]
  exact hz fun i ↦ (hF i) ▸ hvan i

end OkaRing
