/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
module

public import Mathlib.Algebra.Category.ModuleCat.Sheaf.Abelian
public import Mathlib.Algebra.Category.ModuleCat.Sheaf.Quasicoherent
public import Oka.Algebra.Category.ModuleCat.Sheaf.Generators

/-!
# Coherent sheaves of modules

A sheaf of modules `M` over a sheaf of rings `R` on a site `(C, J)` is *coherent* if

- `M` is of finite type (i.e. locally generated by finitely many sections), and
- for every object `X : C` and every morphism `φ : free I ⟶ M.over X` with `I` finite,
  the kernel of `φ` is of finite type.

The second condition says that, locally, every finite family of sections of `M` has a
sheaf of relations which is again locally finitely generated.

This is the sheaf-theoretic notion underlying the theory of coherent analytic and
algebraic sheaves; the classical references develop it for ringed spaces, which
correspond to the site of opens of a topological space.

## Main definitions

- `SheafOfModules.IsCoherent`: the coherence condition described above.
- `SheafOfModules.isCoherent`: coherence as an `ObjectProperty`, which is closed
  under isomorphisms.

## References

- [Jean-Pierre Serre, *Faisceaux algébriques cohérents*][serre1955], §2
- [Hans Grauert and Reinhold Remmert, *Coherent analytic sheaves*][grauert-remmert1984]
- https://stacks.math.columbia.edu/tag/01BU

-/

@[expose] public section

universe u v₁ u₁

open CategoryTheory Limits

variable {C : Type u₁} [Category.{v₁} C] {J : GrothendieckTopology C} {R : Sheaf J RingCat.{u}}
  [∀ (X : C), HasSheafify (J.over X) AddCommGrpCat.{u}]
  [∀ (X : C), (J.over X).WEqualsLocallyBijective AddCommGrpCat.{u}]
  [∀ (X : C) (Y : Over X), HasWeakSheafify ((J.over X).over Y) AddCommGrpCat.{u}]
  [∀ (X : C) (Y : Over X), ((J.over X).over Y).WEqualsLocallyBijective AddCommGrpCat.{u}]

namespace SheafOfModules

/-- A sheaf of modules `M` has finite type relations at `X : C` if for every morphism
`φ : free I ⟶ M.over X` with `I` finite, the kernel of `φ` is of finite type. This is
the relation-finiteness condition entering the definition of coherence,
see `SheafOfModules.IsCoherent`. -/
def HasFiniteTypeRelations (M : SheafOfModules.{u} R) (X : C) : Prop :=
  ∀ ⦃I : Type u⦄ [Finite I] (φ : free I ⟶ M.over X), (kernel φ).IsFiniteType

/-- A sheaf of modules `M` over a sheaf of rings `R` is *coherent* if it is of finite type
and if, for every object `X : C` and every morphism `φ : free I ⟶ M.over X` with `I`
finite, the kernel of `φ` is of finite type. -/
class IsCoherent (M : SheafOfModules.{u} R) : Prop where
  isFiniteType (M) : M.IsFiniteType
  hasFiniteTypeRelations (M) (X : C) : M.HasFiniteTypeRelations X

attribute [instance] IsCoherent.isFiniteType

variable {M : SheafOfModules.{u} R}

/-- If `M` is coherent, the kernel of any morphism `free I ⟶ M.over X` with `I` finite
is of finite type. -/
lemma IsCoherent.isFiniteType_kernel [M.IsCoherent] {X : C} {I : Type u} [Finite I]
    (φ : free I ⟶ M.over X) : (kernel φ).IsFiniteType :=
  IsCoherent.hasFiniteTypeRelations M X φ

/-- If `M` is coherent, the sheaf of relations of any finite family of generating
sections of `M` over any object is of finite type. -/
lemma IsCoherent.isFiniteType_kernel_π [M.IsCoherent] {X : C}
    (σ : (M.over X).GeneratingSections) [σ.IsFiniteType] :
    (kernel σ.π).IsFiniteType :=
  IsCoherent.isFiniteType_kernel σ.π

variable (R) in
@[inherit_doc IsCoherent]
abbrev isCoherent : ObjectProperty (SheafOfModules.{u} R) :=
  IsCoherent

instance : (isCoherent R).IsClosedUnderIsomorphisms where
  of_iso {M N} e h := by
    letI := h
    constructor
    · exact .of_iso e
    · intro X I _ φ
      have : (kernel (φ ≫ e.inv.over X)).IsFiniteType :=
        IsCoherent.isFiniteType_kernel (φ ≫ e.inv.over X)
      exact (isFiniteType (R.over X)).prop_of_iso (kernelCompMono φ (e.inv.over X)) this

lemma IsCoherent.of_iso {M N : SheafOfModules.{u} R} (e : M ≅ N) [M.IsCoherent] :
    N.IsCoherent :=
  (isCoherent R).prop_of_iso e ‹_›

end SheafOfModules
