/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
module

public import Mathlib.Algebra.Category.Grp.FilteredColimits
public import Mathlib.CategoryTheory.Limits.Constructions.Over.Products
public import Oka.Algebra.Category.ModuleCat.Sheaf.Coherent.Basic
public import Oka.Algebra.Category.ModuleCat.Sheaf.Free

/-!
# A criterion for coherence

Checking that a sheaf of modules is coherent amounts to producing, locally, finitely many
generators for the sheaf of relations between finitely many sections. This file provides the
translation between such concrete data and the abstract definitions:

- `SheafOfModules.epi_kernelLift`: if every section of `P` killed by `φ : P ⟶ Q` is in the image
  of `ψ : free L ⟶ P`, then `ψ` induces an epimorphism onto `kernel φ`;
- `SheafOfModules.isFiniteType_kernel_of_coversTop`: if, on a covering of the terminal object,
  the kernel of `φ` is generated by finitely many sections in this sense, then it is of
  finite type;
- `SheafOfModules.isCoherent_of_forall_kernel`: the resulting criterion for coherence.
-/

@[expose] public section

universe u v' u'

open CategoryTheory Limits

namespace SheafOfModules

section Epi

variable {C : Type u'} [Category.{v'} C] {J : GrothendieckTopology C} {R : Sheaf J RingCat.{u}}
  [HasSheafify J AddCommGrpCat.{u}] [J.WEqualsLocallyBijective AddCommGrpCat.{u}]
  {P Q : SheafOfModules.{u} R}

omit [HasSheafify J AddCommGrpCat.{u}] [J.WEqualsLocallyBijective AddCommGrpCat.{u}] in
lemma kernel_ι_val_app_injective (φ : P ⟶ Q) (Z : Cᵒᵖ) :
    Function.Injective ((kernel.ι φ).val.app Z) := by
  have : Mono ((evaluation R Z).map (kernel.ι φ)) :=
    Functor.map_mono (evaluation R Z) (kernel.ι φ)
  rwa [ModuleCat.mono_iff_injective] at this

omit [HasSheafify J AddCommGrpCat.{u}] [J.WEqualsLocallyBijective AddCommGrpCat.{u}] in
lemma val_app_apply_eq_zero_of_mem_kernel (φ : P ⟶ Q) (Z : Cᵒᵖ)
    (n : (kernel φ).val.obj Z) :
    φ.val.app Z ((kernel.ι φ).val.app Z n) = 0 := by
  have h : (kernel.ι φ ≫ φ).val.app Z n = (0 : kernel φ ⟶ Q).val.app Z n := by
    rw [kernel.condition]
  exact h

/-- If every section of `P` annihilated by `φ` is in the image of `ψ`, then the morphism
`free L ⟶ kernel φ` induced by `ψ` is an epimorphism. -/
lemma epi_kernelLift {L : Type u} (φ : P ⟶ Q) (ψ : free L ⟶ P) (hzero : ψ ≫ φ = 0)
    (hsurj : ∀ (Z : Cᵒᵖ) (b : P.val.obj Z), φ.val.app Z b = 0 →
      ∃ c, ψ.val.app Z c = b) :
    Epi (kernel.lift φ ψ hzero) := by
  refine (forget R).epi_of_epi_map (PresheafOfModules.epi_of_surjective (fun Z n ↦ ?_))
  obtain ⟨c, hc⟩ := hsurj Z _ (val_app_apply_eq_zero_of_mem_kernel φ Z n)
  refine ⟨c, kernel_ι_val_app_injective φ Z ?_⟩
  have h : (kernel.lift φ ψ hzero ≫ kernel.ι φ).val.app Z c = ψ.val.app Z c := by
    rw [kernel.lift_ι]
  exact h.trans hc

end Epi

section Criterion

variable {C : Type u} [SmallCategory C] [HasPullbacks C] {J : GrothendieckTopology C}
  {R : Sheaf J RingCat.{u}}
  [HasSheafify J AddCommGrpCat.{u}] [J.WEqualsLocallyBijective AddCommGrpCat.{u}]
  [∀ (X : C), HasSheafify (J.over X) AddCommGrpCat.{u}]
  [∀ (X : C), (J.over X).WEqualsLocallyBijective AddCommGrpCat.{u}]
  [∀ (X : C) (Y : Over X), HasSheafify ((J.over X).over Y) AddCommGrpCat.{u}]
  [∀ (X : C) (Y : Over X), ((J.over X).over Y).WEqualsLocallyBijective AddCommGrpCat.{u}]

/-- If, locally on a covering of the terminal object, the sections annihilated by `φ` are
generated by finitely many sections, then the kernel of `φ` is of finite type. -/
lemma isFiniteType_kernel_of_coversTop {P Q : SheafOfModules.{u} R} (φ : P ⟶ Q)
    {A : Type u} (Y : A → C) (hY : J.CoversTop Y)
    (h : ∀ a : A, ∃ (L : Type u) (_ : Finite L) (ψ : free L ⟶ P.over (Y a))
      (_ : ψ ≫ φ.over (Y a) = 0),
      ∀ (W : (Over (Y a))ᵒᵖ) (b : (P.over (Y a)).val.obj W),
        (φ.over (Y a)).val.app W b = 0 → ∃ c, ψ.val.app W c = b) :
    (kernel φ).IsFiniteType := by
  refine IsFiniteType.of_coversTop_of_forall _ Y hY (fun a ↦ ?_)
  haveI : HasBinaryProducts (Over (Y a)) :=
    Over.ConstructProducts.over_binaryProduct_of_pullback
  obtain ⟨L, _, ψ, hzero, hsurj⟩ := h a
  haveI : Epi (kernel.lift (φ.over (Y a)) ψ hzero) := epi_kernelLift _ ψ hzero hsurj
  haveI : IsFiniteType (kernel (φ.over (Y a))) :=
    IsFiniteType.of_generatingSections
      ((freeGeneratingSections L).ofEpi (kernel.lift (φ.over (Y a)) ψ hzero))
  exact IsFiniteType.of_iso (overKernelIso φ (Y a)).symm

variable [HasBinaryProducts C]

instance isFiniteType_unit : (unit R).IsFiniteType :=
  haveI : (free (R := R) PUnit.{u + 1}).IsFiniteType :=
    IsFiniteType.of_generatingSections (freeGeneratingSections PUnit.{u + 1})
  IsFiniteType.of_iso freePUnitIso

omit [HasSheafify J AddCommGrpCat.{u}] [J.WEqualsLocallyBijective AddCommGrpCat.{u}]
  [HasBinaryProducts C] in
/-- A sheaf of modules of finite type all of whose sheaves of relations are, locally,
finitely generated in the concrete sense above, is coherent. -/
lemma isCoherent_of_forall_kernel {M : SheafOfModules.{u} R} [M.IsFiniteType]
    (h : ∀ (X : C) (I : Type u) (_ : Finite I) (φ : free I ⟶ M.over X),
      ∃ (A : Type u) (Y : A → Over X) (_ : (J.over X).CoversTop Y),
        ∀ a : A, ∃ (L : Type u) (_ : Finite L) (ψ : free L ⟶ (free I).over (Y a))
          (_ : ψ ≫ φ.over (Y a) = 0),
          ∀ (W : (Over (Y a))ᵒᵖ) (b : ((free I).over (Y a)).val.obj W),
            (φ.over (Y a)).val.app W b = 0 → ∃ c, ψ.val.app W c = b) :
    M.IsCoherent where
  isFiniteType := inferInstance
  hasFiniteTypeRelations X := by
    intro I _ φ
    obtain ⟨A, Y, hY, hgen⟩ := h X I ‹_› φ
    exact isFiniteType_kernel_of_coversTop φ Y hY hgen

end Criterion

end SheafOfModules
