/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Mathlib.AlgebraicGeometry.IdealSheaf.Subscheme
import Mathlib.AlgebraicGeometry.Noetherian
import Oka.AlgebraicGeometry.Modules.QuasicoherentCover
import Oka.AlgebraicGeometry.Modules.QuasicoherentSections
import Oka.Geometry.RingedSpace.LocallyRingedSpace.ModulesClosedEmbeddingKilled

/-!
# Coherent sheaves supported on the image of a morphism

Let `i : T ⟶ Y` be a morphism of schemes, and write `I_y = i.pushforwardStalkIdeal y ⊆ 𝒪_{Y,y}`
for the kernel of `𝒪_{Y,y} → (i_* 𝒪_T)_y`. For a closed immersion this is the stalk of the ideal
sheaf of `T`.

The main result is `AlgebraicGeometry.exists_pow_pushforwardStalkIdeal_le_annihilator`: on a
quasi-compact locally noetherian scheme `Y`, if a coherent sheaf `K` has zero stalks off the image
of `i`, then there is `n` with `I_yⁿ K_y = 0` for all `y`.

The proof works on an affine open `W` with `M = Γ(W, K)` finite over `B = Γ(W, 𝒪_Y)`. The
elements `b ∈ B` whose basic open `D(b)` misses the image of `i` form an ideal `J`
(`AlgebraicGeometry.Scheme.Hom.basicOpenAvoidingIdeal`). Every `b ∈ J` acts nilpotently on `M`,
since `K|_{D(b)} = 0` and `K` is quasi-coherent, so `Jⁿ M = 0` for some `n` as `J` is finitely
generated; and `I_y` is generated by the germs of elements of `J` for `y ∈ W`.

We also record `AlgebraicGeometry.Scheme.Hom.pushforwardStalkIdeal_eq_bot`: on a reduced scheme,
`I_y = 0` at points `y` having a neighbourhood contained in the image of `i`; and that the reduced
induced closed subscheme on a closed subset is reduced
(`AlgebraicGeometry.Scheme.IdealSheafData.isReduced_subscheme_vanishingIdeal`).
-/

open CategoryTheory TopologicalSpace Opposite

universe u

noncomputable section

namespace AlgebraicGeometry

variable {Y T : Scheme.{u}} (i : T ⟶ Y)

/-- If `i^♯ s = 0`, the basic open `D(s)` does not meet the image of `i`. -/
lemma Scheme.Hom.notMem_range_of_mem_basicOpen {V : Y.Opens} (s : Γ(Y, V))
    (hs : i.app V s = 0) {y : Y} (hy : y ∈ Y.basicOpen s) : y ∉ Set.range i.base := by
  rintro ⟨t, rfl⟩
  have ht : t ∈ i ⁻¹ᵁ Y.basicOpen s := hy
  rw [Scheme.preimage_basicOpen, hs, Scheme.basicOpen_zero] at ht
  exact ht

/-- If `i^♯ s = 0`, then `i^♯` kills every restriction of `s`. -/
lemma Scheme.Hom.app_map_eq_zero {V W : Y.Opens} (h : W ≤ V) (s : Γ(Y, V)) (hs : i.app V s = 0) :
    i.app W (Y.presheaf.map (homOfLE h).op s) = 0 := by
  have := ConcreteCategory.congr_hom (i.naturality (homOfLE h).op) s
  simp only [CommRingCat.comp_apply] at this
  refine this.trans ?_
  rw [hs, map_zero]

/-- The ideal of sections `b ∈ Γ(Y, V)` whose basic open `D(b)` does not meet the image of `i`. -/
def Scheme.Hom.basicOpenAvoidingIdeal (V : Y.Opens) : Ideal Γ(Y, V) where
  carrier := {b | ∀ y ∈ Y.basicOpen b, y ∉ Set.range i.base}
  add_mem' {a b} ha hb y hy := (Y.basicOpen_add_le a b hy).elim (ha y) (hb y)
  zero_mem' y hy := by
    rw [Scheme.basicOpen_zero] at hy
    exact hy.elim
  smul_mem' c b hb y hy := by
    rw [smul_eq_mul, Scheme.basicOpen_mul] at hy
    exact hb y hy.2

/-- Membership in `Scheme.Hom.basicOpenAvoidingIdeal`. -/
lemma Scheme.Hom.mem_basicOpenAvoidingIdeal {V : Y.Opens} (b : Γ(Y, V)) :
    b ∈ i.basicOpenAvoidingIdeal V ↔ ∀ y ∈ Y.basicOpen b, y ∉ Set.range i.base :=
  Iff.rfl

variable (K : Y.Modules)

/-- A section of a sheaf of modules all of whose stalks on its domain vanish is zero. -/
lemma Scheme.Modules.eq_zero_of_subsingleton_stalk {V : Y.Opens} (t : Γ(K, V))
    (h : ∀ y ∈ V, Subsingleton ((Y.toLocallyRingedSpace.stalkFunctor y).obj K)) : t = 0 := by
  refine TopCat.Presheaf.section_ext (⟨K.val.presheaf, K.isSheaf⟩ : TopCat.Sheaf Ab.{u} Y) V t 0
    fun y hy ↦ ?_
  haveI := h y hy
  exact Subsingleton.elim (α := (Y.toLocallyRingedSpace.stalkFunctor y).obj K) _ _

variable {K} [K.IsQuasicoherent]

/-- On an affine open `W`, an element of `Γ(Y, W)` whose basic open misses the image of `i` acts
nilpotently on `Γ(K, W)`, provided the stalks of `K` vanish off the image of `i`. -/
lemma Scheme.Hom.radical_annihilator_of_isAffineOpen {W : Y.Opens} (hW : IsAffineOpen W)
    [Module.Finite Γ(Y, W) Γ(K, W)]
    (hK : ∀ y ∉ Set.range i.base, Subsingleton ((Y.toLocallyRingedSpace.stalkFunctor y).obj K)) :
    i.basicOpenAvoidingIdeal W ≤ (Module.annihilator Γ(Y, W) Γ(K, W)).radical := by
  classical
  intro b hb
  have hz : ∀ m : Γ(K, W), ∃ k : ℕ, b ^ k • m = 0 := by
    intro m
    refine hW.exists_pow_smul_eq_zero K b m ?_
    exact Scheme.Modules.eq_zero_of_subsingleton_stalk K _ fun y hy ↦ hK y (hb y hy)
  choose k hk using hz
  obtain ⟨s, hs⟩ := Module.Finite.fg_top (R := Γ(Y, W)) (M := Γ(K, W))
  refine ⟨∑ m ∈ s, k m, Module.mem_annihilator.2 fun m ↦ ?_⟩
  have hm : m ∈ Submodule.span Γ(Y, W) (s : Set Γ(K, W)) := hs ▸ Submodule.mem_top
  induction hm using Submodule.span_induction with
  | mem x hx =>
    rw [← Finset.sum_erase_add s k hx, pow_add, mul_smul, hk x, smul_zero]
  | zero => exact smul_zero _
  | add x y _ _ hx hy => rw [smul_add, hx, hy, add_zero]
  | smul a x _ hx => rw [smul_comm, hx, smul_zero]

/-- On an affine open `W`, the ideal `I_y = i.pushforwardStalkIdeal y` at `y ∈ W` is generated by
the germs of the sections `b ∈ Γ(Y, W)` whose basic open misses the image of `i`. -/
lemma Scheme.Hom.pushforwardStalkIdeal_le_map_basicOpenAvoidingIdeal {W : Y.Opens}
    (hW : IsAffineOpen W) (y : Y) (hy : y ∈ W) :
    i.toLRSHom.pushforwardStalkIdeal y ≤
      (i.basicOpenAvoidingIdeal W).map (Y.presheaf.germ W y hy).hom := by
  intro r hr
  obtain ⟨V, hyV, s, hs0, rfl⟩ := i.toLRSHom.exists_germ_eq_of_mem_pushforwardStalkIdeal y r hr
  obtain ⟨h, hhV, hyh⟩ := hW.exists_basicOpen_le (V := V) ⟨y, hyV⟩ hy
  let s' : Γ(Y, Y.basicOpen h) := Y.presheaf.map (homOfLE hhV).op s
  have hs' : i.app _ s' = 0 := i.app_map_eq_zero hhV s hs0
  haveI := hW.isLocalization_basicOpen h
  obtain ⟨⟨a, ⟨_, k, rfl⟩⟩, ha⟩ := IsLocalization.surj (Submonoid.powers h) s'
  simp only at ha
  have hres : ∀ c : Γ(Y, W), algebraMap Γ(Y, W) Γ(Y, Y.basicOpen h) c =
      Y.presheaf.map (homOfLE (Y.basicOpen_le h)).op c := fun c ↦ by
    rw [RingHom.algebraMap_toAlgebra]
  have hb : h * a ∈ i.basicOpenAvoidingIdeal W := by
    intro z hz
    rw [Scheme.basicOpen_mul] at hz
    have hz' : z ∈ Y.basicOpen (algebraMap Γ(Y, W) Γ(Y, Y.basicOpen h) a) := by
      rw [hres, Scheme.basicOpen_res]
      exact ⟨hz.1, hz.2⟩
    rw [← ha, Scheme.basicOpen_mul] at hz'
    exact i.notMem_range_of_mem_basicOpen s' hs' hz'.1
  have hu : IsUnit (Y.presheaf.germ W y hy h) := (Y.mem_basicOpen h y hy).1 hyh
  have hgerm : ∀ c : Γ(Y, W), Y.presheaf.germ _ y hyh (algebraMap _ _ c) =
      Y.presheaf.germ W y hy c := fun c ↦ by
    rw [hres, TopCat.Presheaf.germ_res_apply]
  have hs'germ : Y.presheaf.germ _ y hyh s' = Y.presheaf.germ V y hyV s :=
    TopCat.Presheaf.germ_res_apply _ _ _ _ _
  have key : Y.presheaf.germ W y hy (h * a) =
      Y.presheaf.germ W y hy h ^ (k + 1) * Y.presheaf.germ V y hyV s := by
    rw [map_mul, ← hgerm a, ← ha, map_mul, hs'germ, hgerm, map_pow, pow_succ]
    ring
  obtain ⟨u, hu⟩ := hu.pow (k + 1)
  have : Y.presheaf.germ V y hyV s = ↑u⁻¹ * Y.presheaf.germ W y hy (h * a) := by
    rw [key, ← hu, Units.inv_mul_cancel_left]
  rw [this]
  exact Ideal.mul_mem_left _ _ (Ideal.mem_map_of_mem _ hb)

/-- On an affine open `W`, the germ at `y ∈ W` of a section killing `Γ(K, W)` kills `K_y`. -/
lemma IsAffineOpen.map_annihilator_le {W : Y.Opens} (hW : IsAffineOpen W) (y : Y) (hy : y ∈ W) :
    (Module.annihilator Γ(Y, W) Γ(K, W)).map (Y.presheaf.germ W y hy).hom ≤
      Module.annihilator (Y.presheaf.stalk y) ((Y.toLocallyRingedSpace.stalkFunctor y).obj K) := by
  rw [Ideal.map_le_iff_le_comap]
  intro b hb
  rw [Ideal.mem_comap, Module.mem_annihilator]
  intro m
  obtain ⟨V, hyV, t, rfl⟩ := TopCat.Presheaf.exists_germ_eq K.val.presheaf m
  obtain ⟨h, hhV, hyh⟩ := hW.exists_basicOpen_le (V := V) ⟨y, hyV⟩ hy
  obtain ⟨k, u, hu⟩ := hW.exists_restrictOpen_eq_pow_smul K h
    (TopCat.Presheaf.restrictOpen t _ hhV)
  let g : ∀ {U : Y.Opens} (_ : y ∈ U), Γ(K, U) → (Y.toLocallyRingedSpace.stalkFunctor y).obj K :=
    fun {U} hU s ↦ TopCat.Presheaf.germ K.val.presheaf U y hU s
  have hunit : IsUnit (Y.presheaf.germ W y hy h ^ k) :=
    ((Y.mem_basicOpen h y hy).1 hyh).pow k
  have e1 : g hy u = Y.presheaf.germ W y hy h ^ k • g hyV t := by
    have r1 : g hy u = g hyh (TopCat.Presheaf.restrictOpen u _ (Y.basicOpen_le h)) :=
      (TopCat.Presheaf.germ_res_apply K.val.presheaf (homOfLE (Y.basicOpen_le h)) y hyh u).symm
    have r2 : g hyV t = g hyh (TopCat.Presheaf.restrictOpen t _ hhV) :=
      (TopCat.Presheaf.germ_res_apply K.val.presheaf (homOfLE hhV) y hyh t).symm
    have r3 : Y.presheaf.germ W y hy h ^ k = Y.presheaf.germ _ y hyh
        (TopCat.Presheaf.restrictOpen h _ (Y.basicOpen_le h) ^ k) := by
      rw [map_pow]
      exact congrArg (· ^ k)
        (TopCat.Presheaf.germ_res_apply Y.presheaf (homOfLE (Y.basicOpen_le h)) y hyh h).symm
    rw [r1, r2, hu, r3]
    exact PresheafOfModules.germ_smul (M := K.val) y _ hyh _ _
  have e2 : Y.presheaf.germ W y hy b • g hy u = 0 := by
    refine (PresheafOfModules.germ_smul (M := K.val) y W hy b u).symm.trans ?_
    change TopCat.Presheaf.germ K.val.presheaf W y hy (b • u) = 0
    rw [Module.mem_annihilator.1 hb u]
    exact map_zero _
  change Y.presheaf.germ W y hy b • g hyV t = 0
  rw [e1, smul_smul, mul_comm, ← smul_smul] at e2
  exact (hunit.smul_left_cancel).1 (e2.trans (smul_zero _).symm)

/-- On an affine open `W` with noetherian ring of sections over which `Γ(K, W)` is finite, if the
stalks of `K` vanish off the image of `i`, then `I_yⁿ` kills `K_y` for some `n` and all `y ∈ W`. -/
lemma Scheme.Hom.exists_pow_pushforwardStalkIdeal_le_annihilator_of_isAffineOpen {W : Y.Opens}
    (hW : IsAffineOpen W) [IsNoetherianRing Γ(Y, W)] [Module.Finite Γ(Y, W) Γ(K, W)]
    (hK : ∀ y ∉ Set.range i.base, Subsingleton ((Y.toLocallyRingedSpace.stalkFunctor y).obj K)) :
    ∃ n : ℕ, ∀ y ∈ W, i.toLRSHom.pushforwardStalkIdeal y ^ n ≤
      Module.annihilator (Y.presheaf.stalk y) ((Y.toLocallyRingedSpace.stalkFunctor y).obj K) := by
  obtain ⟨n, hn⟩ := Ideal.exists_pow_le_of_le_radical_of_fg
    (i.radical_annihilator_of_isAffineOpen hW hK) (IsNoetherian.noetherian _)
  refine ⟨n, fun y hy ↦ ?_⟩
  calc i.toLRSHom.pushforwardStalkIdeal y ^ n
      ≤ ((i.basicOpenAvoidingIdeal W).map (Y.presheaf.germ W y hy).hom) ^ n :=
        Ideal.pow_right_mono (i.pushforwardStalkIdeal_le_map_basicOpenAvoidingIdeal hW y hy) n
    _ = ((i.basicOpenAvoidingIdeal W) ^ n).map (Y.presheaf.germ W y hy).hom :=
        (Ideal.map_pow _ _ _).symm
    _ ≤ (Module.annihilator Γ(Y, W) Γ(K, W)).map (Y.presheaf.germ W y hy).hom :=
        Ideal.map_mono hn
    _ ≤ _ := hW.map_annihilator_le y hy

/-- **Coherent sheaves supported on the image of a morphism are killed by a power of its ideal.**
Let `Y` be a quasi-compact locally noetherian scheme, `i : T ⟶ Y` a morphism of schemes and `K` a
coherent sheaf on `Y` with zero stalks off the image of `i`. Then there is `n` such that for every
`y`, the `n`-th power of the ideal `I_y = i.pushforwardStalkIdeal y` kills the stalk `K_y`. -/
theorem exists_pow_pushforwardStalkIdeal_le_annihilator [IsLocallyNoetherian Y] [CompactSpace Y]
    (K : SheafOfModules.{u} Y.toLocallyRingedSpace.ringSheaf) [K.IsCoherent]
    (hK : ∀ y ∉ Set.range i.base, Subsingleton ((Y.toLocallyRingedSpace.stalkFunctor y).obj K)) :
    ∃ n : ℕ, ∀ y, i.toLRSHom.pushforwardStalkIdeal y ^ n ≤
      Module.annihilator (Y.presheaf.stalk y) ((Y.toLocallyRingedSpace.stalkFunctor y).obj K) := by
  classical
  let K' : Y.Modules := K
  haveI : K'.IsQuasicoherent := Scheme.Modules.isQuasicoherent_of_isCoherent K
  haveI : K'.IsFiniteType := SheafOfModules.IsCoherent.isFiniteType K
  have hloc : ∀ y : Y, ∃ W : Y.Opens, y ∈ W ∧ ∃ n : ℕ, ∀ y' ∈ W,
      i.toLRSHom.pushforwardStalkIdeal y' ^ n ≤ Module.annihilator (Y.presheaf.stalk y')
        ((Y.toLocallyRingedSpace.stalkFunctor y').obj K) := by
    intro y
    obtain ⟨U, hyU⟩ : ∃ U : Y.affineOpens, y ∈ (U : Y.Opens) :=
      Opens.mem_iSup.1 (by rw [iSup_affineOpens_eq_top]; trivial)
    obtain ⟨g, hyg, hfin⟩ := U.2.exists_module_finite_basicOpen K' y hyU
    have hW := U.2.basicOpen g
    haveI : IsNoetherianRing Γ(Y, Y.basicOpen g) :=
      IsLocallyNoetherian.component_noetherian ⟨_, hW⟩
    exact ⟨_, hyg, i.exists_pow_pushforwardStalkIdeal_le_annihilator_of_isAffineOpen
      (K := K') hW hK⟩
  choose W hyW n hn using hloc
  obtain ⟨s, hs⟩ := isCompact_univ.elim_finite_subcover (fun y ↦ (W y : Set Y))
    (fun y ↦ (W y).isOpen) (fun y _ ↦ Set.mem_iUnion.2 ⟨y, hyW y⟩)
  refine ⟨s.sup n, fun y ↦ ?_⟩
  obtain ⟨z, hz, hyz⟩ := Set.mem_iUnion₂.1 (hs (Set.mem_univ y))
  exact (Ideal.pow_le_pow_right (Finset.le_sup hz)).trans (hn z y hyz)

/-- On a reduced scheme, `I_y = i.pushforwardStalkIdeal y` vanishes at every point `y` having a
neighbourhood contained in the image of `i`. -/
lemma Scheme.Hom.pushforwardStalkIdeal_eq_bot [IsReduced Y] {y : Y} {V : Y.Opens} (hyV : y ∈ V)
    (hV : (V : Set Y) ⊆ Set.range i.base) : i.toLRSHom.pushforwardStalkIdeal y = ⊥ := by
  rw [eq_bot_iff]
  intro r hr
  obtain ⟨W, hyW, s, hs0, rfl⟩ := i.toLRSHom.exists_germ_eq_of_mem_pushforwardStalkIdeal y r hr
  let s' : Γ(Y, V ⊓ W) := Y.presheaf.map (homOfLE inf_le_right).op s
  have hs' : i.app _ s' = 0 := i.app_map_eq_zero inf_le_right s hs0
  have hbot : Y.basicOpen s' = ⊥ := by
    refine eq_bot_iff.2 fun z hz ↦ ?_
    exact (i.notMem_range_of_mem_basicOpen s' hs' hz
      (hV (inf_le_left (a := V) (b := W) (Y.basicOpen_le s' hz)))).elim
  rw [basicOpen_eq_bot_iff] at hbot
  rw [Submodule.mem_bot, ← TopCat.Presheaf.germ_res_apply _ (homOfLE inf_le_right) y
    ⟨hyV, hyW⟩ s]
  change Y.presheaf.germ _ y _ s' = 0
  rw [hbot, map_zero]

/-- The reduced induced closed subscheme structure on a closed subset is reduced. -/
instance Scheme.IdealSheafData.isReduced_subscheme_vanishingIdeal
    (Z : TopologicalSpace.Closeds Y) : IsReduced (IdealSheafData.vanishingIdeal Z).subscheme := by
  have (U : Y.affineOpens) :
      _root_.IsReduced (Γ(Y, U) ⧸ (IdealSheafData.vanishingIdeal Z).ideal U) := by
    rw [IdealSheafData.vanishingIdeal_ideal]
    exact (Ideal.isRadical_iff_quotient_reduced _).mp (PrimeSpectrum.isRadical_vanishingIdeal _)
  have (U : Y.affineOpens) :
      IsReduced ((IdealSheafData.vanishingIdeal Z).subschemeCover.openCover.X U) :=
    inferInstanceAs (IsReduced (Spec (.of (Γ(Y, U) ⧸ (IdealSheafData.vanishingIdeal Z).ideal U))))
  exact IsReduced.of_openCover (X := _) (IdealSheafData.vanishingIdeal Z).subschemeCover.openCover

end AlgebraicGeometry
