/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.AlgebraicGeometry.ProjectiveSpace.Hyperplane
import Oka.AlgebraicGeometry.Modules.CocycleTwistPushforward
import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# Base change of projective space

A ring map `f : R →+* A` induces (`Proj.map` of `MvPolynomial.map f`) a morphism
`map f : ℙ(n; A) ⟶ ℙ(n; R)` over `Spec A ⟶ Spec R`. It pulls back the standard opens `U i` to
`U i`, is `Spec` of `MvPolynomial.map f : R[Y] → A[Y]` in the standard charts, and exhibits
`ℙ(n; A)` as the base change `ℙ(n; R) ×_{Spec R} Spec A`. The standard cocycle `(Xⱼ / Xᵢ)`
defining the twisting sheaves pulls back to the standard cocycle.

## Main definitions and results

- `ProjectiveSpace.map f : ℙ(n; A) ⟶ ℙ(n; R)`, with `map_id`, `map_comp`, `map_preimage_U`,
  `map_toSpec`.
- `ProjectiveSpace.chart_comp_map`: `chart i ≫ map f = Spec.map (MvPolynomial.map f) ≫ chart i`.
- `ProjectiveSpace.isPullback_map`: **base change**, `ℙ(n; A) = ℙ(n; R) ×_{Spec R} Spec A`;
  `ProjectiveSpace.baseChangeIso` is the resulting isomorphism.
- `ProjectiveSpace.map_appLE_xDiv`: `(map f)^♯ (Xⱼ / Xᵢ) = Xⱼ / Xᵢ`.
- `ProjectiveSpace.cocycle_isPullback`: the standard cocycle of `ℙ(n; A)` is the pullback of the
  standard cocycle of `ℙ(n; R)`.
-/

open CategoryTheory Limits MvPolynomial HomogeneousLocalization
open scoped AlgebraicGeometry.ProjectiveSpace

universe u

namespace AlgebraicGeometry.ProjectiveSpace

variable {n : ℕ} {R A : Type u} [CommRing R] [CommRing A] (f : R →+* A)

variable (n) in
/-- `MvPolynomial.map f` as a graded ring homomorphism. -/
noncomputable def mapGradedHom :
    homogeneousSubmodule (Fin (n + 1)) R →+*ᵍ homogeneousSubmodule (Fin (n + 1)) A where
  __ := MvPolynomial.map f
  map_mem hp := ((mem_homogeneousSubmodule _ _).mp hp).map f

/-- `mapGradedHom n f` is `MvPolynomial.map f`. -/
@[simp]
lemma mapGradedHom_apply (p : MvPolynomial (Fin (n + 1)) R) :
    mapGradedHom n f p = MvPolynomial.map f p := rfl

/-- A polynomial lies in the irrelevant ideal iff its constant coefficient vanishes. -/
lemma mem_irrelevant_iff_coeff_zero {S : Type u} [CommRing S]
    (a : MvPolynomial (Fin (n + 1)) S) :
    a ∈ HomogeneousIdeal.irrelevant (homogeneousSubmodule (Fin (n + 1)) S) ↔ coeff 0 a = 0 := by
  rw [HomogeneousIdeal.mem_irrelevant_iff, GradedRing.proj_apply]
  exact (congrArg (· = 0) (decomposition.decompose'_apply a 0)).to_iff.trans (by
    rw [homogeneousComponent_zero, C_eq_zero])

/-- The irrelevant ideal over `A` is generated by the image of the irrelevant ideal over `R`. -/
lemma irrelevant_le_map_mapGradedHom :
    HomogeneousIdeal.irrelevant (homogeneousSubmodule (Fin (n + 1)) A) ≤
      (HomogeneousIdeal.irrelevant (homogeneousSubmodule (Fin (n + 1)) R)).map
        (mapGradedHom n f) := by
  intro b hb
  change b ∈ (HomogeneousIdeal.map _ _).toIdeal
  rw [HomogeneousIdeal.toIdeal_map]
  have h1 : b ∈ Ideal.span (X '' Set.univ) := by
    rw [mem_ideal_span_X_image]
    intro m hm
    by_contra! h
    have : m = 0 := Finsupp.ext fun i ↦ h i (Set.mem_univ i)
    subst this
    exact (mem_support_iff.mp hm) ((mem_irrelevant_iff_coeff_zero b).mp hb)
  refine Ideal.span_le.mpr ?_ h1
  rintro _ ⟨i, -, rfl⟩
  rw [← map_X f]
  refine Ideal.mem_map_of_mem (mapGradedHom n f)
    (show X i ∈ HomogeneousIdeal.irrelevant _ from ?_)
  rw [mem_irrelevant_iff_coeff_zero, coeff_X]
  simp

/-- The morphism `ℙ(n; A) ⟶ ℙ(n; R)` induced by a ring map `f : R →+* A`. -/
noncomputable def map : ℙ(n; A) ⟶ ℙ(n; R) :=
  Proj.map (mapGradedHom n f) (irrelevant_le_map_mapGradedHom f)

/-- `map f` pulls back the standard open `U i` to `U i`. -/
lemma map_preimage_U (i : Fin (n + 1)) : map f ⁻¹ᵁ U n R i = U n A i := by
  rw [U, map, Proj.map_preimage_basicOpen, mapGradedHom_apply, map_X, U]

variable (n) in
/-- The map `R[X₀, …, Xₙ]_(Xᵢ) → A[X₀, …, Xₙ]_(Xᵢ)` induced by `f`. -/
noncomputable def awayMapHom (i : Fin (n + 1)) :
    Away (homogeneousSubmodule (Fin (n + 1)) R) (X i) →+*
      Away (homogeneousSubmodule (Fin (n + 1)) A) (X i) :=
  HomogeneousLocalization.map (mapGradedHom n f) (by
    rintro _ ⟨k, rfl⟩
    exact ⟨k, by simp⟩)

/-- `awayMapHom` maps `Xⱼ / Xᵢ` to `Xⱼ / Xᵢ`. -/
lemma awayMapHom_awayXDiv (i j : Fin (n + 1)) :
    awayMapHom n f i (awayXDiv R i j) = awayXDiv A i j := by
  apply val_injective
  simp [awayMapHom, awayXDiv, Away.mk, HomogeneousLocalization.map_mk]

/-- `awayMapHom` corresponds to `MvPolynomial.map f` on the chart rings. -/
lemma awayMapHom_comp_toAwayX (i : Fin (n + 1)) :
    (awayMapHom n f i).comp (toAwayX R i) = (toAwayX A i).comp (MvPolynomial.map f) := by
  apply MvPolynomial.ringHom_ext
  · intro r
    apply val_injective
    simp [awayMapHom, toAwayX, awayXBase, fromZeroRingHom, HomogeneousLocalization.map_mk]
  · intro k
    simp [awayMapHom_awayXDiv]

/-- `map f` on the basic open `D₊(Xᵢ)` is `Spec` of `awayMapHom`. -/
@[reassoc]
lemma awayι_comp_map (i : Fin (n + 1)) :
    Proj.awayι _ (X i) (X_mem_homogeneousSubmodule_one i) Nat.one_pos ≫ map f =
      Spec.map (CommRingCat.ofHom (awayMapHom n f i)) ≫
        Proj.awayι _ (X i) (X_mem_homogeneousSubmodule_one i) Nat.one_pos :=
  Proj.awayι_comp_map_of_eq _ _ _ _ _ (map_X f i)

/-- **`map` in the standard charts** is `Spec` of `MvPolynomial.map f : R[Y] → A[Y]`. -/
@[reassoc]
lemma chart_comp_map (i : Fin (n + 1)) :
    chart i ≫ map f = Spec.map (CommRingCat.ofHom (MvPolynomial.map f)) ≫ chart i := by
  rw [chart, Category.assoc, awayι_comp_map, chart, ← Category.assoc, ← Category.assoc,
    ← Spec.map_comp, ← Spec.map_comp]
  congr 2
  ext p : 2
  apply (awayXEquiv A i).injective
  obtain ⟨p, rfl⟩ := (awayXEquiv R i).surjective p
  simp only [CommRingCat.hom_comp, CommRingCat.hom_ofHom, RingHom.coe_comp, Function.comp_apply,
    RingEquiv.toRingHom_eq_coe, RingEquiv.coe_toRingHom, awayXEquiv_symm_apply,
    awayXEquiv_apply, fromAwayX_toAwayX, toAwayX_fromAwayX]
  exact congr($(awayMapHom_comp_toAwayX f i) p)

/-- `map f` is a morphism over `Spec A ⟶ Spec R`. -/
@[reassoc]
lemma map_toSpec :
    map f ≫ toSpec n R = toSpec n A ≫ Spec.map (CommRingCat.ofHom f) := by
  refine (affineOpenCover n A).openCover.hom_ext _ _ fun (j : Fin (n + 1)) ↦ ?_
  change chart j ≫ map f ≫ toSpec n R = chart j ≫ toSpec n A ≫ _
  rw [chart_comp_map_assoc, chart_toSpec, chart_toSpec_assoc, ← Spec.map_comp, ← Spec.map_comp]
  congr 1
  ext r : 2
  simp

/-- The standard chart square is a pullback: `Spec A[Y] = ℙ(n; A) ×_{ℙ(n; R)} Spec R[Y]`. -/
lemma isPullback_chart_map (i : Fin (n + 1)) :
    IsPullback (Spec.map (CommRingCat.ofHom (MvPolynomial.map f))) (chart i) (chart i)
      (map f) :=
  IsOpenImmersion.isPullback _ _ _ _ (chart_comp_map f i) (by
    rw [opensRange_chart, opensRange_chart, map_preimage_U])

/-- Base change for affine space: `Spec A[Y] = Spec A ×_{Spec R} Spec R[Y]`. -/
lemma isPullback_SpecMap_mvPolynomialMap :
    IsPullback (Spec.map (CommRingCat.ofHom (MvPolynomial.map f)))
      (Spec.map (CommRingCat.ofHom (C : A →+* MvPolynomial (Fin n) A)))
      (Spec.map (CommRingCat.ofHom (C : R →+* MvPolynomial (Fin n) R)))
      (Spec.map (CommRingCat.ofHom f)) := by
  letI := f.toAlgebra
  letI : Algebra (MvPolynomial (Fin n) R) (MvPolynomial (Fin n) A) := algebraMvPolynomial
  exact isPullback_SpecMap_of_isPushout _ _ _ _
    (CommRingCat.isPushout_of_isPushout R (MvPolynomial (Fin n) R) A (MvPolynomial (Fin n) A))

/-- **Base change for projective space**: `ℙ(n; A) = ℙ(n; R) ×_{Spec R} Spec A`. -/
theorem isPullback_map :
    IsPullback (map f) (toSpec n A) (toSpec n R) (Spec.map (CommRingCat.ofHom f)) := by
  refine Scheme.isPullback_of_openCover _ _ _ _ (affineOpenCover n R).openCover fun i ↦ ?_
  change IsPullback (pullback.snd (map f) (chart i)) (pullback.fst (map f) (chart i) ≫
    toSpec n A) (chart i ≫ toSpec n R) (Spec.map (CommRingCat.ofHom f))
  have hc := (isPullback_chart_map f i).flip
  rw [chart_toSpec]
  refine .of_iso (isPullback_SpecMap_mvPolynomialMap (n := n) f) hc.isoPullback (.refl _)
    (.refl _) (.refl _) ?_ ?_ (by simp) (by simp)
  · simp
  · simp [chart_toSpec]

/-- The base change isomorphism `ℙ(n; A) ≅ ℙ(n; R) ×_{Spec R} Spec A`. -/
noncomputable def baseChangeIso :
    ℙ(n; A) ≅ pullback (toSpec n R) (Spec.map (CommRingCat.ofHom f)) :=
  (isPullback_map f).isoPullback

/-- The first projection of `baseChangeIso` is `map f`. -/
@[reassoc (attr := simp)]
lemma baseChangeIso_hom_fst : (baseChangeIso (n := n) f).hom ≫ pullback.fst _ _ = map f :=
  (isPullback_map f).isoPullback_hom_fst

/-- The second projection of `baseChangeIso` is `toSpec n A`. -/
@[reassoc (attr := simp)]
lemma baseChangeIso_hom_snd : (baseChangeIso (n := n) f).hom ≫ pullback.snd _ _ = toSpec n A :=
  (isPullback_map f).isoPullback_hom_snd

/-- `map f` on sections over `U i` is induced by `awayMapHom`. -/
lemma map_appLE_awayToSection (i : Fin (n + 1))
    (z : Away (homogeneousSubmodule (Fin (n + 1)) R) (X i)) :
    (map f).appLE (U n R i) (U n A i) (map_preimage_U f i).ge
      (Proj.awayToSection _ (X i) z) = Proj.awayToSection _ (X i) (awayMapHom n f i z) :=
  Proj.appLE_awayToSection_of_eq _ _ (X_mem_homogeneousSubmodule_one i) (map_X f i) _ z

/-- `map f` pulls back `Xⱼ / Xᵢ` to `Xⱼ / Xᵢ`. -/
lemma map_appLE_xDiv (i j : Fin (n + 1)) :
    (map f).appLE (U n R i) (U n A i) (map_preimage_U f i).ge (xDiv i j) = xDiv i j := by
  rw [xDiv, map_appLE_awayToSection, awayMapHom_awayXDiv, xDiv]

open Scheme.Modules in
/-- The standard cocycle `(Xⱼ / Xᵢ)` of `ℙ(n; A)` is the pullback along `map f` of the standard
cocycle of `ℙ(n; R)`. -/
theorem cocycle_isPullback :
    Cocycle.IsPullback (map f) id (fun i ↦ (map_preimage_U f i).ge) (cocycle n R)
      (cocycle n A) := by
  intro i j W hW
  have hWi : W ≤ U n A i := hW.trans inf_le_left
  rw [cocycle_g, cocycle_g, ores_res, appLE_res]
  refine (res_appLE (map f) (map_preimage_U f i).ge hWi (xDiv i j)).symm.trans ?_
  rw [map_appLE_xDiv]

section functoriality

variable {B : Type u} [CommRing B] (g : A →+* B)

/-- `map` sends the identity to the identity. -/
lemma map_id : map (n := n) (RingHom.id R) = 𝟙 ℙ(n; R) := by
  rw [map, ← Proj.map_id]
  congr 1
  ext p : 1
  simp [MvPolynomial.map_id]

/-- `map` is contravariantly functorial. -/
lemma map_comp : map (n := n) (g.comp f) = map g ≫ map f := by
  rw [map, map, map, ← Proj.map_comp]
  congr 1
  ext p : 1
  simp [MvPolynomial.map_map]

end functoriality

end AlgebraicGeometry.ProjectiveSpace
