/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Functor
import Oka.AlgebraicGeometry.ProjectiveSpace.Twist

/-!
# The hyperplane `{Xₙ₊₁ = 0}` in projective space

The graded surjection `R[X₀, …, Xₙ₊₁] → R[X₀, …, Xₙ]`, `Xₙ₊₁ ↦ 0`, `Xⱼ ↦ Xⱼ` (`j ≤ n`), induces
(`Proj.map`) the **hyperplane** `ι : ℙ(n; R) ⟶ ℙ(n + 1; R)`, a closed immersion over `Spec R` with
image `{Xₙ₊₁ = 0}`. It satisfies `ι⁻¹(Uⱼ) = Uⱼ` for `j ≤ n` and `ι⁻¹(Uₙ₊₁) = ∅`, and in the
standard charts it is `Spec` of `R[Y₀, …, Yₙ] → R[Y₀, …, Yₙ₋₁]`, `Yₙ ↦ 0`. On `Uⱼ`, `j ≤ n`, the
kernel of `ι^♯` is generated by `Xₙ₊₁ / Xⱼ`.

## Main definitions and results

- `MvPolynomial.killLast R n : R[X₀, …, Xₙ] →ₐ[R] R[X₀, …, Xₙ₋₁]`, `Xₙ ↦ 0`; its kernel is
  generated by `Xₙ` (`MvPolynomial.exists_eq_X_last_mul_of_killLast_eq_zero`).
- `ProjectiveSpace.hyperplane n R : ℙ(n; R) ⟶ ℙ(n + 1; R)`, with `IsClosedImmersion`,
  `hyperplane_toSpec`, `hyperplane_preimage_U_castSucc`, `hyperplane_preimage_U_last`.
- `ProjectiveSpace.chart_comp_hyperplane`: the hyperplane in the standard charts.
- `ProjectiveSpace.hyperplane_appLE_xDiv_castSucc`, `hyperplane_appLE_xDiv_last`: `ι^♯` maps
  `Xₗ / Xⱼ` to `Xₗ / Xⱼ` for `l ≤ n` and `Xₙ₊₁ / Xⱼ` to `0`.
- `ProjectiveSpace.hyperplane_app_U_eq_zero`: the kernel of `Γ(Uⱼ, 𝒪) → Γ(ι⁻¹Uⱼ, 𝒪)` is
  generated by `Xₙ₊₁ / Xⱼ`.
-/

open CategoryTheory MvPolynomial HomogeneousLocalization
open scoped AlgebraicGeometry.ProjectiveSpace

universe u

namespace MvPolynomial

variable (R : Type u) [CommRing R] (n : ℕ)

/-- The substitution `R[X₀, …, Xₙ] → R[X₀, …, Xₙ₋₁]`, `Xₙ ↦ 0`, `Xⱼ ↦ Xⱼ` (`j < n`). -/
noncomputable def killLast : MvPolynomial (Fin (n + 1)) R →ₐ[R] MvPolynomial (Fin n) R :=
  aeval (Fin.lastCases 0 X)

variable {R n}

@[simp] lemma killLast_X_last : killLast R n (X (Fin.last n)) = 0 := by simp [killLast]
@[simp] lemma killLast_X_castSucc (j : Fin n) : killLast R n (X j.castSucc) = X j := by
  simp [killLast]
@[simp] lemma killLast_C (r : R) : killLast R n (C r) = C r := by simp [killLast]

/-- `killLast` preserves homogeneity. -/
lemma killLast_mem_homogeneousSubmodule {m : ℕ} {p : MvPolynomial (Fin (n + 1)) R}
    (hp : p ∈ homogeneousSubmodule (Fin (n + 1)) R m) :
    killLast R n p ∈ homogeneousSubmodule (Fin n) R m := by
  have := (show p.IsHomogeneous m from hp).aeval
    (Fin.lastCases (motive := fun _ ↦ MvPolynomial (Fin n) R) 0 X) (n := 1) (fun i ↦ by
      induction i using Fin.lastCases with
      | last => simpa using isHomogeneous_zero (Fin n) R 1
      | cast j => simpa using isHomogeneous_X R j)
  rw [one_mul] at this
  exact this

lemma killLast_surjective : Function.Surjective (killLast R n) := by
  intro p
  refine ⟨rename Fin.castSucc p, ?_⟩
  induction p using MvPolynomial.induction_on with
  | C r => simp
  | add p q hp hq => simp [hp, hq]
  | mul_X p j hp => simp [hp]

/-- Every polynomial is `p(X₀, …, Xₙ₋₁, 0) + Xₙ q`. -/
lemma exists_eq_rename_killLast_add (p : MvPolynomial (Fin (n + 1)) R) :
    ∃ q, p = rename Fin.castSucc (killLast R n p) + X (Fin.last n) * q := by
  induction p using MvPolynomial.induction_on with
  | C r => exact ⟨0, by simp⟩
  | add p q hp hq =>
    obtain ⟨a, ha⟩ := hp
    obtain ⟨b, hb⟩ := hq
    exact ⟨a + b, by rw [map_add, map_add]; nth_rw 1 [ha, hb]; ring⟩
  | mul_X p j hp =>
    obtain ⟨a, ha⟩ := hp
    induction j using Fin.lastCases with
    | last =>
      refine ⟨rename Fin.castSucc (killLast R n p) + a * X (Fin.last n), ?_⟩
      rw [map_mul, killLast_X_last, mul_zero, map_zero, zero_add]
      nth_rw 1 [ha]
      ring
    | cast j =>
      refine ⟨a * X j.castSucc, ?_⟩
      rw [map_mul, killLast_X_castSucc, map_mul, rename_X]
      nth_rw 1 [ha]
      ring

/-- The kernel of `killLast` is generated by `Xₙ`. -/
lemma exists_eq_X_last_mul_of_killLast_eq_zero {p : MvPolynomial (Fin (n + 1)) R}
    (hp : killLast R n p = 0) : ∃ q, p = X (Fin.last n) * q := by
  obtain ⟨q, hq⟩ := exists_eq_rename_killLast_add p
  exact ⟨q, by rw [hq, hp, map_zero, zero_add]⟩

end MvPolynomial

namespace HomogeneousLocalization

variable {A B σ τ : Type*} [CommRing A] [SetLike σ A] [AddSubgroupClass σ A]
  [CommRing B] [SetLike τ B] [AddSubgroupClass τ B]
  {𝒜 : ℕ → σ} {ℬ : ℕ → τ} [GradedRing 𝒜] [GradedRing ℬ]

/-- A surjective graded ring homomorphism induces surjections on homogeneous localisations. -/
lemma Away.map_surjective (g : 𝒜 →+*ᵍ ℬ) (hg : Function.Surjective g) {d : ℕ} {s : A}
    (hs : s ∈ 𝒜 d) : Function.Surjective (Away.map g s) := by
  intro x
  obtain ⟨k, b, hb, rfl⟩ := Away.mk_surjective ℬ (g.2 hs) x
  obtain ⟨a, rfl⟩ := hg b
  refine ⟨Away.mk 𝒜 hs k _ (DirectSum.decompose 𝒜 a (k • d)).2, ?_⟩
  rw [Away.map_mk]
  congr 1
  rw [GradedRingHom.map_directSumDecompose, DirectSum.decompose_of_mem_same _ hb]

end HomogeneousLocalization

namespace AlgebraicGeometry.ProjectiveSpace

attribute [local instance] MvPolynomial.gradedAlgebra

variable (n : ℕ) (R : Type u) [CommRing R]

/-- The graded surjection `R[X₀, …, Xₙ₊₁] → R[X₀, …, Xₙ]`, `Xₙ₊₁ ↦ 0`. -/
noncomputable def hyperplaneGradedHom :
    homogeneousSubmodule (Fin (n + 1 + 1)) R →+*ᵍ homogeneousSubmodule (Fin (n + 1)) R where
  __ := (killLast R (n + 1)).toRingHom
  map_mem := killLast_mem_homogeneousSubmodule

lemma irrelevant_le_map_hyperplaneGradedHom :
    HomogeneousIdeal.irrelevant (homogeneousSubmodule (Fin (n + 1)) R) ≤
      (HomogeneousIdeal.irrelevant (homogeneousSubmodule (Fin (n + 1 + 1)) R)).map
        (hyperplaneGradedHom n R) := by
  intro b hb
  obtain ⟨a, rfl⟩ := killLast_surjective (R := R) (n := n + 1) b
  have ha : a - (DirectSum.decompose (homogeneousSubmodule (Fin (n + 1 + 1)) R) a 0 :
      MvPolynomial _ R) ∈
        HomogeneousIdeal.irrelevant (homogeneousSubmodule (Fin (n + 1 + 1)) R) := by
    simp
  have := Ideal.mem_map_of_mem (hyperplaneGradedHom n R) ha
  rw [map_sub, GradedRingHom.map_directSumDecompose] at this
  have hb' : ((DirectSum.decompose (homogeneousSubmodule (Fin (n + 1)) R)
      (hyperplaneGradedHom n R a) 0 : homogeneousSubmodule (Fin (n + 1)) R 0) :
        MvPolynomial (Fin (n + 1)) R) = 0 := by
    rw [HomogeneousIdeal.mem_irrelevant_iff, GradedRing.proj_apply] at hb
    exact hb
  rwa [hb', sub_zero] at this

/-- The **hyperplane** `{Xₙ₊₁ = 0}`, the closed immersion `ℙ(n; R) ⟶ ℙ(n + 1; R)` induced by
`Xₙ₊₁ ↦ 0`. -/
noncomputable def hyperplane : ℙ(n; R) ⟶ ℙ(n + 1; R) :=
  Proj.map (hyperplaneGradedHom n R) (irrelevant_le_map_hyperplaneGradedHom n R)

variable {n R}

@[simp]
lemma hyperplaneGradedHom_apply (p : MvPolynomial (Fin (n + 1 + 1)) R) :
    hyperplaneGradedHom n R p = killLast R (n + 1) p := rfl

lemma hyperplaneGradedHom_surjective : Function.Surjective (hyperplaneGradedHom n R) :=
  killLast_surjective

/-- `ι⁻¹(Uⱼ) = Uⱼ` for `j ≤ n`. -/
lemma hyperplane_preimage_U_castSucc (j : Fin (n + 1)) :
    hyperplane n R ⁻¹ᵁ U (n + 1) R j.castSucc = U n R j := by
  rw [U, hyperplane, Proj.map_preimage_basicOpen, hyperplaneGradedHom_apply, killLast_X_castSucc,
    U]

/-- `ι⁻¹(Uₙ₊₁) = ∅`. -/
lemma hyperplane_preimage_U_last : hyperplane n R ⁻¹ᵁ U (n + 1) R (Fin.last _) = ⊥ := by
  rw [U, hyperplane, Proj.map_preimage_basicOpen, hyperplaneGradedHom_apply, killLast_X_last,
    Proj.basicOpen_zero]

lemma hyperplane_app_surjective (j : Fin (n + 1)) :
    Function.Surjective (hyperplane n R |>.app (U (n + 1) R j.castSucc)) := by
  have h := Proj.awayToSection_comp_appLE (hyperplaneGradedHom n R)
    (irrelevant_le_map_hyperplaneGradedHom n R) (X_mem_homogeneousSubmodule_one j.castSucc)
  have h1 : Function.Surjective (Proj.awayToSection (homogeneousSubmodule (Fin (n + 1)) R)
      (hyperplaneGradedHom n R (X j.castSucc))) := by
    exact (Proj.basicOpenIsoAway _ _ ((hyperplaneGradedHom n R).2
      (X_mem_homogeneousSubmodule_one j.castSucc))
        Nat.one_pos).commRingCatIsoToRingEquiv.surjective
  have h2 := h1.comp (Away.map_surjective _ hyperplaneGradedHom_surjective
    (X_mem_homogeneousSubmodule_one (R := R) j.castSucc))
  rw [← CommRingCat.hom_ofHom (Away.map _ _), ← RingHom.coe_comp, ← CommRingCat.hom_comp,
    ← h] at h2
  rw [Scheme.Hom.app_eq_appLE]
  exact Function.Surjective.of_comp h2

/-- If `f^♯ : Γ(Y, U) → Γ(X, f⁻¹U)` is surjective, so is `Γ` of the restriction `f ∣_ U`. -/
lemma _root_.AlgebraicGeometry.surjective_appTop_morphismRestrict {X Y : Scheme.{u}}
    {f : X ⟶ Y} {U : Y.Opens} (h : Function.Surjective (f.app U)) :
    Function.Surjective (f ∣_ U).appTop := by
  have key : ∀ V W (e : W ≤ f ⁻¹ᵁ V), V = U → W = f ⁻¹ᵁ U →
      Function.Surjective (f.appLE V W e) := by
    rintro V W e rfl rfl
    rw [← Scheme.Hom.app_eq_appLE]
    exact h
  rw [Scheme.Hom.appTop, morphismRestrict_app']
  exact key _ _ _ (Scheme.Opens.ι_image_top _) (Scheme.Opens.ι_image_top _)

/-- The hyperplane `ℙ(n; R) ⟶ ℙ(n + 1; R)` is a closed immersion. -/
instance : IsClosedImmersion (hyperplane n R) := by
  rw [HasAffineProperty.iff_of_iSup_eq_top (P := @IsClosedImmersion)
    (fun i ↦ ⟨U (n + 1) R i, isAffineOpen_U i⟩) (iSup_U (n + 1) R)]
  intro i
  induction i using Fin.lastCases with
  | last =>
    refine ⟨?_, surjective_appTop_morphismRestrict fun x ↦ ⟨0, ?_⟩⟩
    · change IsAffineOpen _
      rw [hyperplane_preimage_U_last]
      exact isAffineOpen_bot _
    · have : Subsingleton Γ(ℙ(n; R), hyperplane n R ⁻¹ᵁ U (n + 1) R (Fin.last _)) := by
        rw [hyperplane_preimage_U_last]; infer_instance
      exact Subsingleton.elim _ _
  | cast j =>
    refine ⟨?_, surjective_appTop_morphismRestrict (hyperplane_app_surjective j)⟩
    change IsAffineOpen _
    rw [hyperplane_preimage_U_castSucc]
    exact isAffineOpen_U j

variable (n R) in
/-- The map `(R[X₀, …, Xₙ₊₁]_{X_j})₀ → (R[X₀, …, Xₙ]_{X_j})₀` induced by `X_{n+1} ↦ 0`. -/
noncomputable def hyperplaneAwayMap (j : Fin (n + 1)) :
    Away (homogeneousSubmodule (Fin (n + 1 + 1)) R) (X j.castSucc) →+*
      Away (homogeneousSubmodule (Fin (n + 1)) R) (X j) :=
  HomogeneousLocalization.map (hyperplaneGradedHom n R) (by
    rintro _ ⟨k, rfl⟩
    exact ⟨k, by simp⟩)

lemma hyperplaneAwayMap_awayXDiv (j : Fin (n + 1)) (m : Fin (n + 1 + 1)) :
    hyperplaneAwayMap n R j (awayXDiv R j.castSucc m) =
      Away.mk _ (X_mem_homogeneousSubmodule_one j) 1 (killLast R (n + 1) (X m))
        (by simpa using killLast_mem_homogeneousSubmodule (X_mem_homogeneousSubmodule_one m)) := by
  apply val_injective
  simp [hyperplaneAwayMap, awayXDiv, Away.mk, HomogeneousLocalization.map_mk]

lemma hyperplaneAwayMap_comp_toAwayX (j : Fin (n + 1)) :
    (hyperplaneAwayMap n R j).comp (toAwayX R j.castSucc) =
      (toAwayX R j).comp (killLast R n).toRingHom := by
  apply MvPolynomial.ringHom_ext
  · intro r
    apply val_injective
    simp [hyperplaneAwayMap, toAwayX, awayXBase, fromZeroRingHom, HomogeneousLocalization.map_mk]
  · intro k
    induction k using Fin.lastCases with
    | last =>
      have : j.castSucc.succAbove (Fin.last n) = Fin.last (n + 1) := by
        rw [Fin.succAbove_of_le_castSucc _ _ (Fin.castSucc_le_castSucc_iff.mpr (Fin.le_last j)),
          Fin.succ_last]
      simp only [RingHom.coe_comp, Function.comp_apply, toAwayX_X, this,
        hyperplaneAwayMap_awayXDiv, killLast_X_last, AlgHom.toRingHom_eq_coe, RingHom.coe_coe,
        map_zero]
      apply val_injective
      simp [Localization.mk_zero]
    | cast k =>
      simp only [RingHom.coe_comp, Function.comp_apply, toAwayX_X, Fin.castSucc_succAbove_castSucc,
        hyperplaneAwayMap_awayXDiv, killLast_X_castSucc, AlgHom.toRingHom_eq_coe, RingHom.coe_coe]
      rfl

/-- `Proj.awayι_comp_map` for an element `t` with `f s = t`. -/
lemma _root_.AlgebraicGeometry.Proj.awayι_comp_map_of_eq {A B σ τ : Type u} [CommRing A]
    [SetLike σ A] [AddSubgroupClass σ A] [CommRing B] [SetLike τ B] [AddSubgroupClass τ B]
    {𝒜 : ℕ → σ} {ℬ : ℕ → τ} [GradedRing 𝒜] [GradedRing ℬ] (f : 𝒜 →+*ᵍ ℬ)
    (hf : HomogeneousIdeal.irrelevant ℬ ≤ (HomogeneousIdeal.irrelevant 𝒜).map f) {i : ℕ}
    (hi : 0 < i) {s : A} (hs : s ∈ 𝒜 i) {t : B} (ht : t ∈ ℬ i) (h : f s = t) :
    Proj.awayι ℬ t ht hi ≫ Proj.map f hf =
      Spec.map (CommRingCat.ofHom (HomogeneousLocalization.map f (P := .powers s)
        (Q := .powers t) (by rintro _ ⟨k, rfl⟩; exact ⟨k, by simp [h]⟩))) ≫
        Proj.awayι 𝒜 s hs hi := by
  subst h
  exact Proj.awayι_comp_map f hf hi s hs

@[reassoc]
lemma awayι_comp_hyperplane (j : Fin (n + 1)) :
    Proj.awayι _ (X j) (X_mem_homogeneousSubmodule_one j) Nat.one_pos ≫ hyperplane n R =
      Spec.map (CommRingCat.ofHom (hyperplaneAwayMap n R j)) ≫
        Proj.awayι _ (X j.castSucc) (X_mem_homogeneousSubmodule_one j.castSucc) Nat.one_pos :=
  Proj.awayι_comp_map_of_eq _ _ _ _ _ (killLast_X_castSucc j)

/-- **The hyperplane in the standard charts**: over the chart `j` of `ℙ(n; R)` and the chart
`j.castSucc` of `ℙ(n + 1; R)`, the hyperplane is `Spec` of `R[Y₀, …, Yₙ] → R[Y₀, …, Yₙ₋₁]`,
`Yₙ ↦ 0`. -/
@[reassoc]
lemma chart_comp_hyperplane (j : Fin (n + 1)) :
    chart j ≫ hyperplane n R =
      Spec.map (CommRingCat.ofHom (killLast R n).toRingHom) ≫ chart j.castSucc := by
  rw [chart, Category.assoc, awayι_comp_hyperplane, chart, ← Category.assoc, ← Category.assoc,
    ← Spec.map_comp, ← Spec.map_comp]
  congr 2
  ext p : 2
  apply (awayXEquiv R j).injective
  obtain ⟨p, rfl⟩ := (awayXEquiv R j.castSucc).surjective p
  simp only [CommRingCat.hom_comp, CommRingCat.hom_ofHom, RingHom.coe_comp, Function.comp_apply,
    RingEquiv.toRingHom_eq_coe, RingEquiv.coe_toRingHom, awayXEquiv_symm_apply,
    awayXEquiv_apply, fromAwayX_toAwayX, toAwayX_fromAwayX]
  exact congr($(hyperplaneAwayMap_comp_toAwayX j) p)

/-- The hyperplane is a morphism over `Spec R`. -/
@[reassoc (attr := simp)]
lemma hyperplane_toSpec : hyperplane n R ≫ toSpec (n + 1) R = toSpec n R := by
  refine (affineOpenCover n R).openCover.hom_ext _ _ fun (j : Fin (n + 1)) ↦ ?_
  change chart j ≫ hyperplane n R ≫ toSpec (n + 1) R = chart j ≫ toSpec n R
  rw [chart_comp_hyperplane_assoc, chart_toSpec, chart_toSpec, ← Spec.map_comp]
  congr 2
  ext r : 2
  simp

lemma hyperplaneAwayMap_eq_zero {j : Fin (n + 1)} {z : Away (homogeneousSubmodule _ R) _}
    (hz : hyperplaneAwayMap n R j z = 0) :
    ∃ w, z = awayXDiv R j.castSucc (Fin.last (n + 1)) * w := by
  obtain ⟨p, rfl⟩ := toAwayX_surjective (R := R) j.castSucc z
  have h := congr($(hyperplaneAwayMap_comp_toAwayX (R := R) j) p)
  simp only [RingHom.coe_comp, Function.comp_apply] at h
  rw [h, ← awayXEquiv_apply, ← map_zero (awayXEquiv R j)] at hz
  obtain ⟨q, rfl⟩ := exists_eq_X_last_mul_of_killLast_eq_zero ((awayXEquiv R j).injective hz)
  have : j.castSucc.succAbove (Fin.last n) = Fin.last (n + 1) := by
    rw [Fin.succAbove_of_le_castSucc _ _ (Fin.castSucc_le_castSucc_iff.mpr (Fin.le_last j)),
      Fin.succ_last]
  exact ⟨toAwayX R j.castSucc q, by rw [map_mul, toAwayX_X, this]⟩

/-- `Proj.awayToSection_comp_appLE` for an element `t` with `f s = t`. -/
lemma _root_.AlgebraicGeometry.Proj.appLE_awayToSection_of_eq {A B σ τ : Type u} [CommRing A]
    [SetLike σ A] [AddSubgroupClass σ A] [CommRing B] [SetLike τ B] [AddSubgroupClass τ B]
    {𝒜 : ℕ → σ} {ℬ : ℕ → τ} [GradedRing 𝒜] [GradedRing ℬ] (f : 𝒜 →+*ᵍ ℬ)
    (hf : HomogeneousIdeal.irrelevant ℬ ≤ (HomogeneousIdeal.irrelevant 𝒜).map f) {i : ℕ}
    {s : A} (hs : s ∈ 𝒜 i) {t : B} (h : f s = t) (e) (z : Away 𝒜 s) :
    (Proj.map f hf).appLE (Proj.basicOpen 𝒜 s) (Proj.basicOpen ℬ t) e
      (Proj.awayToSection 𝒜 s z) =
      Proj.awayToSection ℬ t (HomogeneousLocalization.map f (P := .powers s)
        (Q := .powers t) (by rintro _ ⟨k, rfl⟩; exact ⟨k, by simp [h]⟩) z) := by
  subst h
  exact congr($(Proj.awayToSection_comp_appLE f hf hs) z)

lemma hyperplane_preimage_U_castSucc_le (j : Fin (n + 1)) :
    U n R j ≤ hyperplane n R ⁻¹ᵁ U (n + 1) R j.castSucc :=
  (hyperplane_preimage_U_castSucc j).ge

lemma hyperplane_appLE_awayToSection (j : Fin (n + 1))
    (z : Away (homogeneousSubmodule (Fin (n + 1 + 1)) R) (X j.castSucc)) :
    (hyperplane n R).appLE (U (n + 1) R j.castSucc) (U n R j) (hyperplane_preimage_U_castSucc_le j)
      (Proj.awayToSection _ (X j.castSucc) z) =
      Proj.awayToSection _ (X j) (hyperplaneAwayMap n R j z) :=
  Proj.appLE_awayToSection_of_eq _ _ (X_mem_homogeneousSubmodule_one j.castSucc)
    (killLast_X_castSucc j) _ z

/-- `ι^♯ (Xₗ / Xⱼ) = Xₗ / Xⱼ` for `j, l ≤ n`. -/
lemma hyperplane_appLE_xDiv_castSucc (j l : Fin (n + 1)) :
    (hyperplane n R).appLE (U (n + 1) R j.castSucc) (U n R j) (hyperplane_preimage_U_castSucc_le j)
      (xDiv j.castSucc l.castSucc) = xDiv j l := by
  rw [xDiv, hyperplane_appLE_awayToSection, hyperplaneAwayMap_awayXDiv, xDiv]
  congr 1
  apply val_injective
  simp [val_awayXDiv]

/-- `ι^♯ (Xₙ₊₁ / Xⱼ) = 0`. -/
lemma hyperplane_appLE_xDiv_last (j : Fin (n + 1)) :
    (hyperplane n R).appLE (U (n + 1) R j.castSucc) (U n R j) (hyperplane_preimage_U_castSucc_le j)
      (xDiv j.castSucc (Fin.last _)) = 0 := by
  rw [xDiv, hyperplane_appLE_awayToSection, hyperplaneAwayMap_awayXDiv]
  have h0 : ∀ h, Away.mk (homogeneousSubmodule (Fin (n + 1)) R)
      (X_mem_homogeneousSubmodule_one j) 1 (killLast R (n + 1) (X (Fin.last (n + 1)))) h = 0 :=
    fun h ↦ by apply val_injective; simp [Localization.mk_zero]
  rw [h0]
  exact map_zero _

/-- **The ideal of the hyperplane on the chart `Uⱼ`** is generated by `Xₙ₊₁ / Xⱼ`. -/
lemma hyperplane_app_U_eq_zero (j : Fin (n + 1)) {y : Γ(ℙ(n + 1; R), U (n + 1) R j.castSucc)}
    (hy : (hyperplane n R).app _ y = 0) : ∃ r, y = xDiv j.castSucc (Fin.last _) * r := by
  have hy' : (hyperplane n R).appLE (U (n + 1) R j.castSucc) (U n R j)
      (hyperplane_preimage_U_castSucc_le j) y = 0 := by
    change ℙ(n; R).presheaf.map _ ((hyperplane n R).app _ y) = 0
    rw [hy, map_zero]
  let e := (Proj.basicOpenIsoAway _ _ (X_mem_homogeneousSubmodule_one (R := R) j.castSucc)
    Nat.one_pos).commRingCatIsoToRingEquiv
  let e' := (Proj.basicOpenIsoAway _ _ (X_mem_homogeneousSubmodule_one (R := R) j)
    Nat.one_pos).commRingCatIsoToRingEquiv
  obtain ⟨z, rfl⟩ := e.surjective y
  change (hyperplane n R).appLE (U (n + 1) R j.castSucc) (U n R j) _
    (Proj.awayToSection _ _ z) = 0 at hy'
  rw [hyperplane_appLE_awayToSection] at hy'
  have : hyperplaneAwayMap n R j z = 0 := e'.injective (hy'.trans (map_zero e').symm)
  obtain ⟨w, rfl⟩ := hyperplaneAwayMap_eq_zero this
  exact ⟨Proj.awayToSection _ _ w, map_mul (Proj.awayToSection _ _).hom _ _⟩

end AlgebraicGeometry.ProjectiveSpace
