/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Oka.AlgebraicGeometry.ProjectiveSpace.HyperplaneSequence
import Oka.Geometry.RingedSpace.LocallyRingedSpace.ModulesClosedEmbeddingKilled

/-!
# The stalks of the ideal of the hyperplane in projective space

For the hyperplane `ι : ℙ(n; R) ⟶ ℙ(n + 1; R)`, `{Xₙ₊₁ = 0}`, and a point `x` of the chart
`U_l = D₊(X_l)`, the stalk at `x` of the ideal of the hyperplane, i.e. the kernel of
`𝒪_x → (ι_* 𝒪)_x` (`AlgebraicGeometry.LocallyRingedSpace.Hom.pushforwardStalkIdeal`), is
generated by the germ of `Xₙ₊₁ / X_l`
(`AlgebraicGeometry.ProjectiveSpace.pushforwardStalkIdeal_hyperplane_le`). For `l ≤ n` this is
`AlgebraicGeometry.ProjectiveSpace.hyperplane_app_basicOpen_eq_zero` on a basic open around `x`;
for `l = n + 1` the generator is `1`.
-/

open CategoryTheory TopologicalSpace Opposite

universe u

namespace AlgebraicGeometry.ProjectiveSpace

variable {n : ℕ} {R : Type u} [CommRing R]

/-- **The ideal of the hyperplane on the chart `U_l` is generated by `Xₙ₊₁ / X_l`, stalkwise.** -/
theorem pushforwardStalkIdeal_hyperplane_le (l : Fin (n + 1 + 1)) (x : ℙ(n + 1; R))
    (hx : x ∈ U (n + 1) R l) :
    (hyperplane n R).toLRSHom.pushforwardStalkIdeal x ≤
      Ideal.span {ℙ(n + 1; R).presheaf.germ (U (n + 1) R l) x hx (xDiv l (Fin.last _))} := by
  induction l using Fin.lastCases with
  | last =>
    rw [xDiv_self, map_one, Ideal.span_singleton_one]
    exact le_top
  | cast j =>
    intro r hr
    obtain ⟨W, hxW, s, hs, rfl⟩ :=
      (hyperplane n R).toLRSHom.exists_germ_eq_of_mem_pushforwardStalkIdeal x r hr
    obtain ⟨f, hfle, hxf⟩ :=
      (isAffineOpen_U (n := n + 1) (R := R) j.castSucc).exists_basicOpen_le
        (V := W ⊓ U (n + 1) R j.castSucc) ⟨x, hxW, hx⟩ hx
    have hDW : ℙ(n + 1; R).basicOpen f ≤ W := hfle.trans inf_le_left
    have hy : (hyperplane n R).app _ (ℙ(n + 1; R).presheaf.map (homOfLE hDW).op s) = 0 := by
      have hnat := congrArg (fun φ ↦ φ s)
        (congrArg CommRingCat.Hom.hom ((hyperplane n R).c.naturality (homOfLE hDW).op))
      exact hnat.trans ((CommRingCat.comp_apply _ _ s).trans
        ((congrArg _ hs).trans (map_zero _)))
    obtain ⟨r', hr'⟩ := hyperplane_app_basicOpen_eq_zero j f hy
    have hg : ℙ(n + 1; R).presheaf.germ _ x hxf (TopCat.Presheaf.restrictOpen
        (xDiv j.castSucc (Fin.last _)) _ (ℙ(n + 1; R).basicOpen_le f)) =
        ℙ(n + 1; R).presheaf.germ (U (n + 1) R j.castSucc) x hx (xDiv j.castSucc (Fin.last _)) :=
      TopCat.Presheaf.germ_res_apply _ _ _ _ _
    rw [← TopCat.Presheaf.germ_res_apply ℙ(n + 1; R).presheaf (homOfLE hDW) x hxf s, hr',
      map_mul, hg]
    exact Ideal.mul_mem_right _ _ (Ideal.subset_span rfl)

/-- `ι^♯ (Xₙ₊₁ / X_l) = 0` on the chart `U_l`, for every `l`. -/
lemma hyperplane_app_xDiv_last (l : Fin (n + 1 + 1)) :
    (hyperplane n R).app (U (n + 1) R l) (xDiv l (Fin.last _)) = 0 := by
  induction l using Fin.lastCases with
  | last =>
    have : Subsingleton Γ(ℙ(n; R), hyperplane n R ⁻¹ᵁ U (n + 1) R (Fin.last _)) := by
      rw [hyperplane_preimage_U_last]
      exact CommRingCat.subsingleton_of_isTerminal ℙ(n; R).sheaf.isTerminalOfEmpty
    exact Subsingleton.elim _ _
  | cast j =>
    have h := hyperplane_appLE_xDiv_last (R := R) j
    have e' : hyperplane n R ⁻¹ᵁ U (n + 1) R j.castSucc ≤ U n R j :=
      (hyperplane_preimage_U_castSucc j).le
    have hinj : Function.Injective (ℙ(n; R).presheaf.map
        (homOfLE (hyperplane_preimage_U_castSucc_le (R := R) j)).op) := by
      intro a b hab
      have := congrArg (ℙ(n; R).presheaf.map (homOfLE e').op) hab
      rwa [← CommRingCat.comp_apply, ← CommRingCat.comp_apply, ← Functor.map_comp,
        Subsingleton.elim (_ ≫ _) (𝟙 _), CategoryTheory.Functor.map_id] at this
    exact hinj (h.trans (map_zero (ℙ(n; R).presheaf.map
      (homOfLE (hyperplane_preimage_U_castSucc_le (R := R) j)).op).hom).symm)

/-- The germ of `Xₙ₊₁ / X_l` at a point of `U_l` lies in the ideal of the hyperplane. -/
lemma germ_xDiv_last_mem_pushforwardStalkIdeal (l : Fin (n + 1 + 1)) (x : ℙ(n + 1; R))
    (hx : x ∈ U (n + 1) R l) :
    ℙ(n + 1; R).presheaf.germ (U (n + 1) R l) x hx (xDiv l (Fin.last _)) ∈
      (hyperplane n R).toLRSHom.pushforwardStalkIdeal x :=
  (hyperplane n R).toLRSHom.germ_mem_pushforwardStalkIdeal x hx _ (hyperplane_app_xDiv_last l)

/-- **The ideal of the hyperplane on the chart `U_l` is the ideal generated by `Xₙ₊₁ / X_l`,
stalkwise.** -/
theorem pushforwardStalkIdeal_hyperplane_eq (l : Fin (n + 1 + 1)) (x : ℙ(n + 1; R))
    (hx : x ∈ U (n + 1) R l) :
    (hyperplane n R).toLRSHom.pushforwardStalkIdeal x =
      Ideal.span {ℙ(n + 1; R).presheaf.germ (U (n + 1) R l) x hx (xDiv l (Fin.last _))} :=
  le_antisymm (pushforwardStalkIdeal_hyperplane_le l x hx)
    ((Ideal.span_singleton_le_iff_mem _).2 (germ_xDiv_last_mem_pushforwardStalkIdeal l x hx))

end AlgebraicGeometry.ProjectiveSpace
