/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka.AlgebraicGeometry.Modules.CocycleTwistPushforward
import Oka.AlgebraicGeometry.Modules.LocallyExact
import Oka.AlgebraicGeometry.ProjectiveSpace.Hyperplane

/-!
# The hyperplane sequence on projective space

For the hyperplane `ι : ℙ(n; R) ⟶ ℙ(n + 1; R)`, `{Xₙ₊₁ = 0}`, and `m : ℤ`, the sequence of sheaves
of modules on `ℙ(n + 1; R)`

  `0 ⟶ O(m) --Xₙ₊₁--> O(m + 1) ⟶ ι_* O(m + 1) ⟶ 0`

is exact. The map `O(m) ⟶ ι_* O(m)` is `ι^♯` on the charts (`hyperplaneRestrict`): the standard
cocycle `Xⱼ / Xᵢ` of `ℙ(n + 1; R)` pulls back to that of `ℙ(n; R)`. Exactness is checked on
small opens (`Scheme.Modules.shortExact_of_locally_exact`): on a basic open `W` of the chart
`Uⱼ`, `j ≤ n`, the sequence of sections is `A --y--> A ⟶ A / (y) ⟶ 0` with `y = Xₙ₊₁ / Xⱼ`
(`hyperplane_app_basicOpen_eq_zero`), and on opens inside `Uₙ₊₁` multiplication by `Xₙ₊₁` is
bijective while `ι_* O(m + 1)` has no nonzero sections.

## Main definitions and results

- `ProjectiveSpace.hyperplaneRestrict n R m : O(m) ⟶ ι_* O(m)`.
- `ProjectiveSpace.mulX_comp_hyperplaneRestrict`: `Xₙ₊₁` vanishes on the hyperplane.
- `ProjectiveSpace.hyperplaneSequence n R m`: the short complex
  `O(m) --Xₙ₊₁--> O(m + 1) ⟶ ι_* O(m + 1)`, and `ProjectiveSpace.hyperplaneSequence_shortExact`.
-/

open CategoryTheory Limits TopologicalSpace Opposite

universe u

namespace AlgebraicGeometry.ProjectiveSpace

open MvPolynomial Scheme.Modules

variable {n : ℕ} {R : Type u} [CommRing R]

/-- The kernel of `ι^♯` on a basic open inside the chart `Uⱼ` is generated by `Xₙ₊₁ / Xⱼ`. -/
lemma hyperplane_app_basicOpen_eq_zero (j : Fin (n + 1))
    (f : Γ(ℙ(n + 1; R), U (n + 1) R j.castSucc))
    {y : Γ(ℙ(n + 1; R), ℙ(n + 1; R).basicOpen f)} (hy : (hyperplane n R).app _ y = 0) :
    ∃ r, y = TopCat.Presheaf.restrictOpen (xDiv j.castSucc (Fin.last _)) _
      (ℙ(n + 1; R).basicOpen_le f) * r := by
  let U₀ : ℙ(n + 1; R).affineOpens := ⟨U (n + 1) R j.castSucc, isAffineOpen_U _⟩
  have hk := (hyperplane n R).ker.map_ideal_basicOpen U₀ f
  rw [Scheme.Hom.ker_apply, Scheme.Hom.ker_apply] at hk
  have hle : RingHom.ker ((hyperplane n R).app (U (n + 1) R j.castSucc)).hom ≤
      Ideal.span {xDiv j.castSucc (Fin.last _)} := fun z hz ↦ by
    obtain ⟨r, rfl⟩ := hyperplane_app_U_eq_zero j hz
    exact Ideal.mul_mem_right _ _ (Ideal.subset_span rfl)
  have hy' : y ∈
      RingHom.ker ((hyperplane n R).app (ℙ(n + 1; R).affineBasicOpen (U := U₀) f).1).hom := hy
  rw [← hk] at hy'
  have := Ideal.map_mono (f := (ℙ(n + 1; R).presheaf.map
    (homOfLE <| ℙ(n + 1; R).basicOpen_le f).op).hom) hle hy'
  rw [Ideal.map_span, Set.image_singleton, Ideal.mem_span_singleton'] at this
  obtain ⟨r, hr⟩ := this
  exact ⟨r, hr.symm.trans (mul_comm _ _)⟩

variable (n R) in
/-- The standard cocycle of `ℙ(n + 1; R)` pulls back to the standard cocycle of `ℙ(n; R)` along
the hyperplane. -/
lemma cocycle_isPullback_hyperplane :
    Cocycle.IsPullback (hyperplane n R) Fin.castSucc hyperplane_preimage_U_castSucc_le
      (cocycle (n + 1) R) (cocycle n R) := by
  intro i j W hW
  rw [cocycle_g, cocycle_g, ores_res, appLE_res, ← res_appLE _ (hyperplane_preimage_U_castSucc_le i)
    (hW.trans inf_le_left), hyperplane_appLE_xDiv_castSucc]

variable (n R) in
/-- **Restriction to the hyperplane**, `O(m) ⟶ ι_* O(m)`, for the hyperplane
`ι : ℙ(n; R) ⟶ ℙ(n + 1; R)`: on `Uⱼ`, `j ≤ n`, it is `ι^♯`. -/
noncomputable def hyperplaneRestrict (m : ℤ) :
    twistingSheaf (n + 1) R m ⟶
      (Scheme.Modules.pushforward (hyperplane n R)).obj (twistingSheaf n R m) :=
  twistUnitToPushforward _ _ _ _ _ ((cocycle_isPullback_hyperplane n R).zpow m)

/-- The components of the restriction of a section to the hyperplane. -/
lemma twistComp_hyperplaneRestrict_app (m : ℤ) (V : ℙ(n + 1; R).Opens)
    (s : Γ(twistingSheaf (n + 1) R m, V)) (j : Fin (n + 1)) :
    twistComp (V := hyperplane n R ⁻¹ᵁ V) ((hyperplaneRestrict n R m).app V s) j =
      (hyperplane n R).appLE (V ⊓ U (n + 1) R j.castSucc) (hyperplane n R ⁻¹ᵁ V ⊓ U n R j)
        (preimage_inf_le _ _ hyperplane_preimage_U_castSucc_le V j) (twistComp s j.castSucc) :=
  rfl

variable (n R) in
/-- `Xₙ₊₁` vanishes on the hyperplane: `O(m) --Xₙ₊₁--> O(m + 1) ⟶ ι_* O(m + 1)` is zero. -/
@[reassoc (attr := simp)]
lemma mulX_comp_hyperplaneRestrict (m : ℤ) :
    mulX (SheafOfModules.unit _) m (Fin.last _) ≫ hyperplaneRestrict n R (m + 1) = 0 := by
  refine Hom.ext_apply fun V s ↦ twist_ext (V := hyperplane n R ⁻¹ᵁ V) fun j ↦ ?_
  rw [Hom.comp_app_apply, twistComp_hyperplaneRestrict_app, twistComp_mulX_app, unit_smul,
    map_mul, appLE_res, ← res_appLE _ (hyperplane_preimage_U_castSucc_le j)
      (inf_le_right), hyperplane_appLE_xDiv_last, ores_zero, zero_mul]
  rfl

/-- `ι⁻¹(W) ≤ Uⱼ` for `W ≤ Uⱼ`, `j ≤ n`. -/
lemma preimage_le_U_of_le {j : Fin (n + 1)} {W : ℙ(n + 1; R).Opens}
    (hW : W ≤ U (n + 1) R j.castSucc) : hyperplane n R ⁻¹ᵁ W ≤ U n R j :=
  ((hyperplane n R).preimage_mono hW).trans (hyperplane_preimage_U_castSucc j).le

/-- On the chart `Uⱼ`, `j ≤ n`, the restriction `O(m) ⟶ ι_* O(m)` is `ι^♯` in the
trivialisations of `O(m)` on `Uⱼ`. -/
lemma twistSectionsEquiv_hyperplaneRestrict_app (m : ℤ) {j : Fin (n + 1)}
    {W : ℙ(n + 1; R).Opens} (hW : W ≤ U (n + 1) R j.castSucc)
    (s : Γ(twistingSheaf (n + 1) R m, W)) :
    twistSectionsEquiv (cocycle n R ^ m) j (preimage_le_U_of_le hW)
      ((hyperplaneRestrict n R m).app W s) =
      (hyperplane n R).app W (twistSectionsEquiv (cocycle (n + 1) R ^ m) j.castSucc hW s) := by
  rw [twistSectionsEquiv_apply, twistSectionsEquiv_apply, twistComp_hyperplaneRestrict_app,
    unit_mres, unit_mres, res_appLE, Scheme.Hom.app_eq_appLE, appLE_res]

/-- Multiplication by `Xₗ` in the trivialisations of `O(m)` and `O(m + 1)` on `Uᵢ` is
multiplication by `Xₗ / Xᵢ`. -/
lemma twistSectionsEquiv_mulX_app (m : ℤ) (l : Fin (n + 1)) {i : Fin (n + 1)}
    {W : ℙ(n; R).Opens} (hW : W ≤ U n R i) (s : Γ(twistingSheaf n R m, W)) :
    twistSectionsEquiv (cocycle n R ^ (m + 1)) i hW ((mulX _ m l).app W s) =
      (xDiv i l |ₒ W) • twistSectionsEquiv (cocycle n R ^ m) i hW s := by
  rw [twistSectionsEquiv_apply, twistSectionsEquiv_apply, twistComp_mulX_app, mres_smul, ores_res]

variable (n R) in
/-- **The hyperplane sequence** `0 ⟶ O(m) --Xₙ₊₁--> O(m + 1) ⟶ ι_* O(m + 1) ⟶ 0` on
`ℙ(n + 1; R)`, for the hyperplane `ι : ℙ(n; R) ⟶ ℙ(n + 1; R)`, `{Xₙ₊₁ = 0}`. -/
@[simps]
noncomputable def hyperplaneSequence (m : ℤ) : ShortComplex ℙ(n + 1; R).Modules :=
  ShortComplex.mk (mulX (SheafOfModules.unit _) m (Fin.last _)) (hyperplaneRestrict n R (m + 1))
    (mulX_comp_hyperplaneRestrict n R m)

variable (n R) in
/-- **The hyperplane sequence is exact**: `0 ⟶ O(m) --Xₙ₊₁--> O(m + 1) ⟶ ι_* O(m + 1) ⟶ 0`
is a short exact sequence of sheaves of modules on `ℙ(n + 1; R)`. On `Uⱼ`, `j ≤ n`, it is
`A --y--> A ⟶ A / (y) ⟶ 0` for `y = Xₙ₊₁ / Xⱼ`; on `Uₙ₊₁`, `Xₙ₊₁` is a unit and `ι_* O(m + 1)`
vanishes. -/
theorem hyperplaneSequence_shortExact (m : ℤ) : (hyperplaneSequence n R m).ShortExact := by
  have : Mono (hyperplaneSequence n R m).f := mono_mulX_twistingSheaf m (Fin.last _)
  refine shortExact_of_locally_exact _ fun x V hxV ↦ ?_
  obtain ⟨i, hxi⟩ := TopologicalSpace.Opens.mem_iSup.mp ((iSup_U (n + 1) R).ge (Set.mem_univ x))
  induction i using Fin.lastCases with
  | last =>
    have hW : V ⊓ U (n + 1) R (Fin.last _) ≤ U (n + 1) R (Fin.last _) := inf_le_right
    refine ⟨V ⊓ U (n + 1) R (Fin.last _), inf_le_left, ⟨hxV, hxi⟩, fun b _ ↦ ?_, fun b ↦ ⟨0, ?_⟩⟩
    · refine ⟨(twistSectionsEquiv _ _ hW).symm (twistSectionsEquiv _ _ hW b), ?_⟩
      apply twistSectionsEquiv_injective _ _ hW
      refine (twistSectionsEquiv_mulX_app m _ hW _).trans ?_
      rw [LinearEquiv.apply_symm_apply, xDiv_self, ores_one, one_smul]
    · refine twist_ext (V := hyperplane n R ⁻¹ᵁ (V ⊓ U (n + 1) R (Fin.last _))) fun j ↦ ?_
      have := Scheme.subsingleton_sections_of_le_bot (X := ℙ(n; R))
        (W := hyperplane n R ⁻¹ᵁ (V ⊓ U (n + 1) R (Fin.last _)) ⊓ U n R j)
        (inf_le_left.trans (((hyperplane n R).preimage_mono hW).trans
          hyperplane_preimage_U_last.le))
      exact @Subsingleton.elim Γ(ℙ(n; R), _) this _ _
  | cast j =>
    obtain ⟨f, hfV, hxf⟩ := (isAffineOpen_U (n := n + 1) (R := R) j.castSucc).exists_basicOpen_le
      ⟨x, hxV⟩ hxi
    have hW := ℙ(n + 1; R).basicOpen_le f
    refine ⟨_, hfV, hxf, fun b hb ↦ ?_, fun b ↦ ?_⟩
    · have hb' := (twistSectionsEquiv_hyperplaneRestrict_app (m + 1) hW b).symm.trans
        ((congrArg (twistSectionsEquiv _ _ (preimage_le_U_of_le hW)) hb).trans (map_zero _))
      obtain ⟨r, hr⟩ := hyperplane_app_basicOpen_eq_zero j f hb'
      refine ⟨(twistSectionsEquiv _ _ hW).symm r, ?_⟩
      apply twistSectionsEquiv_injective _ _ hW
      refine (twistSectionsEquiv_mulX_app m _ hW _).trans ?_
      rw [LinearEquiv.apply_symm_apply, hr]
      rfl
    · obtain ⟨r, hr⟩ := (hyperplane n R).app_surjective _ ((isAffineOpen_U _).basicOpen f)
        (twistSectionsEquiv _ _ (preimage_le_U_of_le hW) b)
      refine ⟨(twistSectionsEquiv _ _ hW).symm r, ?_⟩
      apply twistSectionsEquiv_injective _ _ (preimage_le_U_of_le hW)
      refine (twistSectionsEquiv_hyperplaneRestrict_app (m + 1) hW _).trans ?_
      rw [LinearEquiv.apply_symm_apply, hr]

end AlgebraicGeometry.ProjectiveSpace
