/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka.AlgebraicGeometry.ProjectiveSpace.Twist
import Oka.AlgebraicGeometry.Modules.QuasicoherentSections
import Oka.AlgebraicGeometry.Modules.Coherent
import Oka.Algebra.Category.ModuleCat.Sheaf.Coherent.Locality
import Oka.Algebra.Category.ModuleCat.Sheaf.Coherent.Stability

/-!
# Serre's theorem A on projective space

Let `F` be a quasi-coherent `𝒪`-module of finite type on `ℙ(n; R)`. Then for all `m` large
enough the twist `F(m)` is generated by finitely many global sections.

The proof is Serre's. On the chart `Uⱼ`, `Xᵢ / Xⱼ` has basic open `Uᵢ ∩ Uⱼ` (`basicOpen_xDiv`),
so for a section `t` of `F` over `Uᵢ` the family `(Xᵢ / Xⱼ)ᵐ t` on `Uᵢ ∩ Uⱼ` extends to `Uⱼ` for
`m` large, and after enlarging `m` the extensions are compatible on `Uⱼ ∩ Uₖ`
(`IsAffineOpen.exists_restrictOpen_eq_pow_smul`, `IsAffineOpen.exists_pow_smul_eq_zero`): this is
a global section of `F(m)` with `i`-th component `t` (`exists_twist_section_eq`). Applying this to
finitely many generators of `Γ(F, D(g))` over finitely many basic opens `D(g)` covering `ℙ(n; R)`
(each inside some chart) gives finitely many global sections of `F(m)` generating it
(`Scheme.Modules.epi_of_surjective_app_affine`).

## Main results

- `ProjectiveSpace.basicOpen_xDiv`: `D(Xⱼ / Xᵢ) = Uᵢ ∩ Uⱼ` in the chart `Uᵢ`.
- `ProjectiveSpace.twistGlobalMk`: global sections of `F(m)` from compatible sections over the
  charts.
- `ProjectiveSpace.exists_twist_section_eq`: a section over `Uᵢ` is the `i`-th component of a
  global section of `F(m)` for all `m ≫ 0`.
- `ProjectiveSpace.exists_epi_freeMk_twist`, `ProjectiveSpace.exists_generatingSections_twist`:
  **Serre's theorem A**, `F(m)` has a finite family of generating global sections for all
  `m ≫ 0`.
- `ProjectiveSpace.exists_epi_twist_free`: an epimorphism `𝒪^I(-m) ⟶ F`, `I` finite, for all
  `m ≫ 0`; `ProjectiveSpace.twistFreeIso`: `𝒪^I(k) ≅ ⊕_I O(k)`.
- `ProjectiveSpace.isCoherent_twist`: twisting preserves coherence.
- `ProjectiveSpace.exists_epi_twist_free_isCoherent_kernel`: over a noetherian ring, a coherent
  `F` sits in a short exact sequence `0 ⟶ K ⟶ ⊕_I O(-m) ⟶ F ⟶ 0` with `K` coherent.
-/

open CategoryTheory MvPolynomial HomogeneousLocalization TopologicalSpace
open AlgebraicGeometry.Scheme.Modules
open scoped AlgebraicGeometry.ProjectiveSpace

universe u

namespace AlgebraicGeometry.ProjectiveSpace

variable {n : ℕ} {R : Type u} [CommRing R]

local notation "𝒜" => homogeneousSubmodule (Fin (n + 1)) R

/-- **The basic open of `Xⱼ / Xᵢ` in the chart `Uᵢ` is `Uᵢ ∩ Uⱼ`.** -/
lemma basicOpen_xDiv (i j : Fin (n + 1)) :
    ℙ(n; R).basicOpen (xDiv i j) = U n R i ⊓ U n R j := by
  have hi := X_mem_homogeneousSubmodule_one (R := R) i
  have hj := X_mem_homogeneousSubmodule_one (R := R) j
  have key : (U n R i).ι ⁻¹ᵁ ℙ(n; R).basicOpen (xDiv i j) = (U n R i).ι ⁻¹ᵁ U n R j := by
    have e1 : Proj.basicOpenToSpec 𝒜 (X i) ⁻¹ᵁ PrimeSpectrum.basicOpen (awayXDiv R i j) =
        (U n R i).ι ⁻¹ᵁ ℙ(n; R).basicOpen (xDiv i j) := by
      rw [Proj.basicOpenToSpec, Scheme.Hom.comp_preimage, SpecMap_preimage_basicOpen,
        Scheme.Opens.toSpecΓ_preimage_basicOpen]
      rfl
    have e2 : Proj.basicOpenToSpec 𝒜 (X i) ⁻¹ᵁ PrimeSpectrum.basicOpen (awayXDiv R i j) =
        (U n R i).ι ⁻¹ᵁ U n R j := by
      have := Proj.awayι_preimage_basicOpen 𝒜 hi Nat.one_pos hj Nat.one_pos
      have h3 : Away.isLocalizationElem hi hj = awayXDiv R i j := by
        simp [Away.isLocalizationElem, awayXDiv]
      rw [h3] at this
      rw [← this, ← Scheme.Hom.comp_preimage, ← Proj.basicOpenIsoSpec_inv_ι 𝒜 (X i) hi Nat.one_pos,
        ← Category.assoc, ← Proj.basicOpenIsoSpec_hom 𝒜 (X i) hi Nat.one_pos, Iso.hom_inv_id,
        Category.id_comp]
      rfl
    rw [← e1, e2]
  have := congrArg ((U n R i).ι ''ᵁ ·) key
  simp only [Scheme.Hom.image_preimage_eq_opensRange_inf, Scheme.Opens.opensRange_ι] at this
  rw [← this, inf_eq_right.mpr (ℙ(n; R).basicOpen_le _)]

/-- `Uⱼ ∩ Uₖ = D₊(Xⱼ Xₖ)` is affine. -/
lemma isAffineOpen_U_inf (j k : Fin (n + 1)) : IsAffineOpen (U n R j ⊓ U n R k) := by
  rw [U, U, ← Proj.basicOpen_mul]
  exact Proj.isAffineOpen_basicOpen _ _
    (SetLike.mul_mem_graded (X_mem_homogeneousSubmodule_one j) (X_mem_homogeneousSubmodule_one k))
    two_pos

variable (F : ℙ(n; R).Modules)

/-- A global section of `F(m)` from sections `sⱼ ∈ Γ(F, Uⱼ)` with `sⱼ = gⱼₖᵐ • sₖ` on
`Uⱼ ∩ Uₖ`. -/
noncomputable def twistGlobalMk {m : ℤ} (s : ∀ j, Γ(F, U n R j))
    (hs : ∀ j k, (s j |ₒ (U n R j ⊓ U n R k)) =
      (cocycle n R ^ m).g j k • (s k |ₒ (U n R j ⊓ U n R k))) : Γ(twist F m, ⊤) :=
  twistMk (fun j ↦ s j |ₒ (⊤ ⊓ U n R j)) fun j k ↦ by
    have := congrArg (fun x ↦ TopCat.Presheaf.restrictOpen x (⊤ ⊓ (U n R j ⊓ U n R k))
      (by order)) (hs j k)
    simpa only [mres_res, mres_smul, ores_res] using this

@[simp]
lemma twistComp_twistGlobalMk {m : ℤ} (s : ∀ j, Γ(F, U n R j)) (hs) (j : Fin (n + 1)) :
    twistComp (twistGlobalMk F (m := m) s hs) j = s j |ₒ (⊤ ⊓ U n R j) :=
  rfl

/-- The transition functions of `O(m)`, `m ∈ ℕ`: `(Xₖ / Xⱼ)ᵐ`. -/
lemma cocycle_natCast_g (m : ℕ) (j k : Fin (n + 1)) :
    (cocycle n R ^ (m : ℤ)).g j k = (xDiv j k |ₒ (U n R j ⊓ U n R k)) ^ m := by
  rw [zpow_natCast, Cocycle.pow_g, cocycle_g]

variable [F.IsQuasicoherent]

/-- **Extension to global sections of a twist.** For a quasi-coherent `F`, every section `t` of
`F` over the chart `Uᵢ` is the `i`-th component of a global section of `F(m)` for all `m ≫ 0`
(i.e. `Xᵢᵐ t` extends to a global section of `F(m)`). -/
theorem exists_twist_section_eq (i : Fin (n + 1)) (t : Γ(F, U n R i)) :
    ∃ m₀ : ℕ, ∀ m : ℕ, m₀ ≤ m →
      ∃ σ : Γ(twist F m, ⊤), twistComp σ i = t |ₒ (⊤ ⊓ U n R i) := by
  have hD (j : Fin (n + 1)) : ℙ(n; R).basicOpen (xDiv j i) ≤ U n R i := by
    rw [basicOpen_xDiv]; exact inf_le_right
  choose a u hu using fun j ↦ IsAffineOpen.exists_restrictOpen_eq_pow_smul (isAffineOpen_U j) F
    (xDiv j i) (TopCat.Presheaf.restrictOpen t _ (hD j))
  set A := Finset.univ.sup a
  set u' : ∀ j, Γ(F, U n R j) := fun j ↦ xDiv (R := R) j i ^ (A - a j) • u j
  have hu' (j : Fin (n + 1)) :
      TopCat.Presheaf.restrictOpen (u' j) (ℙ(n; R).basicOpen (xDiv j i))
        (ℙ(n; R).basicOpen_le _) =
      TopCat.Presheaf.restrictOpen (xDiv j i) (ℙ(n; R).basicOpen (xDiv j i))
        (ℙ(n; R).basicOpen_le _) ^ A • TopCat.Presheaf.restrictOpen t _ (hD j) := by
    simp only [u']
    rw [mres_smul, ores_pow, hu, smul_smul, ← pow_add,
      Nat.sub_add_cancel (Finset.le_sup (f := a) (Finset.mem_univ j))]
  clear_value u'
  have hd (j k : Fin (n + 1)) : ∃ b : ℕ, (xDiv j i |ₒ (U n R j ⊓ U n R k)) ^ b •
      ((u' j |ₒ (U n R j ⊓ U n R k)) -
        (xDiv j k |ₒ (U n R j ⊓ U n R k)) ^ A • (u' k |ₒ (U n R j ⊓ U n R k))) = 0 := by
    apply IsAffineOpen.exists_pow_smul_eq_zero (isAffineOpen_U_inf j k) F
    have hW : ℙ(n; R).basicOpen (xDiv j i |ₒ (U n R j ⊓ U n R k)) =
        (U n R j ⊓ U n R k) ⊓ (U n R j ⊓ U n R i) := by
      rw [Scheme.basicOpen_restrictOpen, basicOpen_xDiv]
    have h1 : ℙ(n; R).basicOpen (xDiv j i |ₒ (U n R j ⊓ U n R k)) ≤
        ℙ(n; R).basicOpen (xDiv j i) := by
      rw [hW, basicOpen_xDiv]; exact inf_le_right
    have h2 : ℙ(n; R).basicOpen (xDiv j i |ₒ (U n R j ⊓ U n R k)) ≤
        ℙ(n; R).basicOpen (xDiv k i) := by
      rw [hW, basicOpen_xDiv]
      exact le_inf (inf_le_left.trans inf_le_right) (inf_le_right.trans inf_le_right)
    have h3 : ℙ(n; R).basicOpen (xDiv j i |ₒ (U n R j ⊓ U n R k)) ≤ U n R j ⊓ U n R k :=
      ℙ(n; R).basicOpen_le _
    rw [mres_sub, mres_smul, ores_pow, mres_res, mres_res, ores_res,
      ← mres_res F (ℙ(n; R).basicOpen_le _) h1 (u' j), hu' j,
      ← mres_res F (ℙ(n; R).basicOpen_le _) h2 (u' k), hu' k,
      mres_smul, mres_smul, ores_pow, ores_pow, ores_res, ores_res, mres_res, mres_res, smul_smul,
      ← mul_pow, xDiv_mul_xDiv j k i _ h3, sub_self]
  choose b hb using hd
  set B := Finset.univ.sup fun p : Fin (n + 1) × Fin (n + 1) ↦ b p.1 p.2
  have hone (W : ℙ(n; R).Opens) (h : W ≤ U n R i) :
      TopCat.Presheaf.restrictOpen (xDiv (R := R) i i) W h = 1 := by
    rw [xDiv_self, ores_one]
  refine ⟨A + B, fun m hm ↦ ?_⟩
  obtain ⟨c, rfl⟩ := Nat.exists_eq_add_of_le hm
  refine ⟨twistGlobalMk F (m := ((A + B + c : ℕ) : ℤ))
    (fun j ↦ xDiv (R := R) j i ^ (B + c) • u' j) fun j k ↦ ?_, ?_⟩
  · have hbB : b j k ≤ B + c :=
      (Finset.le_sup (f := fun p : Fin (n + 1) × Fin (n + 1) ↦ b p.1 p.2)
        (Finset.mem_univ (j, k))).trans (Nat.le_add_right _ _)
    have hb' := hb j k
    have h0 : (xDiv j i |ₒ (U n R j ⊓ U n R k)) ^ (B + c) •
        ((u' j |ₒ (U n R j ⊓ U n R k)) -
          (xDiv j k |ₒ (U n R j ⊓ U n R k)) ^ A • (u' k |ₒ (U n R j ⊓ U n R k))) = 0 := by
      rw [← Nat.sub_add_cancel hbB, pow_add, mul_smul, hb', smul_zero]
    rw [smul_sub, sub_eq_zero] at h0
    rw [cocycle_natCast_g, mres_smul, mres_smul, ores_pow, ores_pow, h0, smul_smul, smul_smul,
      ← xDiv_mul_xDiv j k i _ le_rfl, mul_pow, add_assoc A B c, pow_add]
    congr 1
    ring
  · simp only [twistComp_twistGlobalMk]
    have hle : ℙ(n; R).basicOpen (xDiv (R := R) i i) = ⊤ ⊓ U n R i := by
      rw [basicOpen_xDiv, inf_idem, top_inf_eq]
    refine mres_injective_of_le (V := ⊤ ⊓ U n R i) F hle.le hle.ge ?_
    simp only [mres_smul, mres_res, ores_pow, hone, one_pow, one_smul]
    rw [hu' i, hone, one_pow, one_smul]


/-- Sections of `F(m)` over a basic open `D(f)` of an affine open `V ⊆ Uᵢ` extend to `V` after
multiplication by a power of `f`. -/
theorem twist_exists_restrictOpen_eq_pow_smul (m : ℤ) {V : ℙ(n; R).Opens} (hV : IsAffineOpen V)
    (i : Fin (n + 1)) (hVi : V ≤ U n R i) (f : Γ(ℙ(n; R), V))
    (s : Γ(twist F m, ℙ(n; R).basicOpen f)) :
    ∃ (k : ℕ) (t : Γ(twist F m, V)),
      TopCat.Presheaf.restrictOpen t (ℙ(n; R).basicOpen f) (ℙ(n; R).basicOpen_le f) =
        TopCat.Presheaf.restrictOpen f (ℙ(n; R).basicOpen f) (ℙ(n; R).basicOpen_le f) ^ k • s := by
  have hf : ℙ(n; R).basicOpen f ≤ U n R i := (ℙ(n; R).basicOpen_le f).trans hVi
  obtain ⟨k, u, hu⟩ := hV.exists_restrictOpen_eq_pow_smul F f
    (twistSectionsEquiv (cocycle n R ^ m) i hf s)
  refine ⟨k, (twistSectionsEquiv (cocycle n R ^ m) i hVi).symm u, ?_⟩
  rw [← twistSectionsEquiv_symm_res _ _ hVi (ℙ(n; R).basicOpen_le f), hu, LinearEquiv.map_smul,
    LinearEquiv.symm_apply_apply]


/-- `ℙ(n; R)` is quasi-compact. -/
lemma isCompact_univ : IsCompact (Set.univ : Set ℙ(n; R)) := by
  have := isCompact_iUnion (fun i ↦ (isAffineOpen_U (n := n) (R := R) i).isCompact)
  rwa [← Opens.coe_iSup, iSup_U, Opens.coe_top] at this

/-- **Serre's theorem A** on `ℙ(n; R)`: for a quasi-coherent `F` of finite type there is `m₀`
such that for all `m ≥ m₀`, finitely many global sections of `F(m)` generate it, i.e. give an
epimorphism `𝒪^I ⟶ F(m)` with `I` finite. -/
theorem exists_epi_freeMk_twist [F.IsFiniteType] :
    ∃ m₀ : ℕ, ∀ m : ℕ, m₀ ≤ m → ∃ (I : Type u) (_ : Finite I) (σ : I → Γ(twist F m, ⊤)),
      Epi (freeMk (twist F m) σ) := by
  choose i hi using fun x : ℙ(n; R) ↦ Opens.mem_iSup.mp ((iSup_U n R).ge (Set.mem_univ x))
  choose g hg hfin using fun x ↦
    (isAffineOpen_U (i x)).exists_module_finite_basicOpen F x (hi x)
  obtain ⟨S, hS⟩ := isCompact_univ.elim_finite_subcover
    (fun x ↦ (ℙ(n; R).basicOpen (g x) : Set ℙ(n; R)))
    (fun x ↦ (ℙ(n; R).basicOpen (g x)).isOpen) (fun x _ ↦ Set.mem_iUnion.mpr ⟨x, hg x⟩)
  choose T hT using fun x ↦ (hfin x).fg_top
  let I : Type u := Σ x : S, T x
  choose k t' ht' using fun p : I ↦
    (isAffineOpen_U (i p.1)).exists_restrictOpen_eq_pow_smul F (g p.1) p.2.1
  choose m₀ hm₀ using fun p : I ↦ exists_twist_section_eq F (i p.1) (t' p)
  refine ⟨Finset.univ.sup m₀, fun m hm ↦ ?_⟩
  choose σ hσ using fun p : I ↦ hm₀ p m ((Finset.le_sup (Finset.mem_univ p)).trans hm)
  refine ⟨I, inferInstance, σ, ?_⟩
  refine epi_of_surjective_app_affine _ (fun x : S ↦ ℙ(n; R).basicOpen (g x)) ?_
    (fun x ↦ (isAffineOpen_U _).basicOpen _)
    (fun x ↦ twist_exists_restrictOpen_eq_pow_smul F m ((isAffineOpen_U _).basicOpen _) (i x)
      (ℙ(n; R).basicOpen_le _)) fun x ↦ ?_
  · refine eq_top_iff.mpr fun y _ ↦ ?_
    obtain ⟨x, hx, hy⟩ := Set.mem_iUnion₂.mp (hS (Set.mem_univ y))
    exact Opens.mem_iSup.mpr ⟨⟨x, hx⟩, hy⟩
  have hDU : ℙ(n; R).basicOpen (g x) ≤ U n R (i x) := ℙ(n; R).basicOpen_le _
  let e := twistSectionsEquiv (F := F) (cocycle n R ^ (m : ℤ)) (i x) hDU
  let L : Γ((SheafOfModules.free I : ℙ(n; R).Modules), ℙ(n; R).basicOpen (g x)) →ₗ[
      Γ(ℙ(n; R), ℙ(n; R).basicOpen (g x))] Γ(F, ℙ(n; R).basicOpen (g x)) :=
    { toFun z := e (Hom.app (freeMk (twist F m) σ) _ z)
      map_add' z z' := by simp only [map_add]
      map_smul' r z := by
        simp only [Hom.app_smul, LinearEquiv.map_smul, RingHom.id_apply] }
  have hL : LinearMap.range L = ⊤ := by
    rw [eq_top_iff, ← hT x, Submodule.span_le]
    intro t ht
    let p : I := ⟨x, ⟨t, ht⟩⟩
    have hc : IsUnit (TopCat.Presheaf.restrictOpen (g x) (ℙ(n; R).basicOpen (g x))
        (ℙ(n; R).basicOpen_le _) ^ k p) :=
      (ℙ(n; R).toRingedSpace.isUnit_res_basicOpen (g x)).pow _
    refine ⟨(↑hc.unit⁻¹ : Γ(ℙ(n; R), ℙ(n; R).basicOpen (g x))) •
      PresheafOfModules.sections.eval (SheafOfModules.freeSection p)
        (Opposite.op (ℙ(n; R).basicOpen (g x))), ?_⟩
    have hp : L (PresheafOfModules.sections.eval (SheafOfModules.freeSection p)
        (Opposite.op (ℙ(n; R).basicOpen (g x)))) =
        TopCat.Presheaf.restrictOpen (g x) (ℙ(n; R).basicOpen (g x))
          (ℙ(n; R).basicOpen_le _) ^ k p • t := by
      change e _ = _
      rw [freeMk_app_freeSection, twistSectionsEquiv_apply, twistComp_res, hσ p, mres_res,
        mres_res]
      exact ht' p
    refine (L.map_smul _ _).trans ?_
    rw [hp, smul_smul, IsUnit.val_inv_mul, one_smul]
  intro y
  obtain ⟨z, hz⟩ : e y ∈ LinearMap.range L := hL ▸ Submodule.mem_top
  exact ⟨z, e.injective hz⟩


/-- **Serre's theorem A**, phrased with `SheafOfModules.GeneratingSections`: for `m ≫ 0`, `F(m)`
has a finite generating family of global sections. -/
theorem exists_generatingSections_twist [F.IsFiniteType] :
    ∃ m₀ : ℕ, ∀ m : ℕ, m₀ ≤ m →
      ∃ σ : SheafOfModules.GeneratingSections.{u} (twist F m), σ.IsFiniteType := by
  obtain ⟨m₀, h⟩ := exists_epi_freeMk_twist F
  refine ⟨m₀, fun m hm ↦ ?_⟩
  obtain ⟨I, hI, σ, hσ⟩ := h m hm
  exact ⟨⟨I, fun q ↦ SheafOfModules.sectionOfTerminal Limits.isTerminalTop _ (σ q), hσ⟩, ⟨hI⟩⟩

/-- **Serre's theorem A, untwisted**: for `m ≫ 0` there is an epimorphism
`𝒪^I(-m) ⟶ F` with `I` finite. See `twistFreeIso` for `𝒪^I(-m) ≅ ⊕_I O(-m)`. -/
theorem exists_epi_twist_free [F.IsFiniteType] :
    ∃ m₀ : ℕ, ∀ m : ℕ, m₀ ≤ m → ∃ (I : Type u) (_ : Finite I)
      (π : twist (SheafOfModules.free I) (-(m : ℤ)) ⟶ F), Epi π := by
  obtain ⟨m₀, h⟩ := exists_epi_freeMk_twist F
  refine ⟨m₀, fun m hm ↦ ?_⟩
  obtain ⟨I, hI, σ, hσ⟩ := h m hm
  let e : twist (twist F m) (-(m : ℤ)) ≅ F := twistTwistIso F m (-(m : ℤ)) ≪≫
    (twistFunctorCongr (congrArg (cocycle n R ^ ·) (add_neg_cancel (m : ℤ)))).app F ≪≫
    twistZeroIso F
  refine ⟨I, hI, (twistFunctor n R (-(m : ℤ))).map (freeMk (twist F m) σ) ≫ e.hom, ?_⟩
  haveI : Epi ((twistFunctor n R (-(m : ℤ))).map (freeMk (twist F m) σ)) :=
    @Functor.map_epi _ _ _ _ (twistFunctor n R (-(m : ℤ))) _ _ _ (freeMk (twist F m) σ) hσ
  exact @epi_comp _ _ _ _ _ _ this _ inferInstance

/-- `𝒪^I(k) ≅ ⊕_I O(k)`. -/
noncomputable def twistFreeIso (I : Type u) (k : ℤ) :
    twist (SheafOfModules.free I) k ≅ ∐ fun _ : I ↦ twistingSheaf n R k :=
  Limits.PreservesCoproduct.iso (twistFunctor n R k) fun _ : I ↦ SheafOfModules.unit _

/-- On the chart `Uᵢ`, `F(m)` and `F` restrict to isomorphic sheaves over the slice site. -/
noncomputable def twistOverIso (m : ℤ) (i : Fin (n + 1)) :
    (twist F m).over (U n R i) ≅ F.over (U n R i) :=
  (overEquiv (U n R i)).fullyFaithfulFunctor.preimageIso
    ((overFunctorEquiv (U n R i)).app (twist F m) ≪≫ twistRestrictIso F m i ≪≫
      ((overFunctorEquiv (U n R i)).app F).symm)

omit [F.IsQuasicoherent] in
/-- **Twisting preserves coherence.** -/
theorem isCoherent_twist [F.IsCoherent] (m : ℤ) : (twist F m).IsCoherent := by
  haveI (i : ULift.{u} (Fin (n + 1))) :
      SheafOfModules.IsCoherent.{u, u, u} ((twist F m).over (U n R i.down)) :=
    haveI := SheafOfModules.IsCoherent.over F (U n R i.down)
    SheafOfModules.IsCoherent.of_iso.{u} (twistOverIso F m i.down).symm
  refine SheafOfModules.IsCoherent.of_coversTop (twist F m) (fun i : ULift.{u} (Fin (n + 1)) ↦
    U n R i.down) ((Opens.coversTop_iff _ _).2 ?_)
  rw [IsOpenCover, ← iSup_U n R]
  exact le_antisymm (iSup_le fun i ↦ le_iSup (U n R) i.down)
    (iSup_le fun i ↦ le_iSup (fun i : ULift.{u} (Fin (n + 1)) ↦ U n R i.down) ⟨i⟩)


omit [F.IsQuasicoherent] in
/-- **Coherent sheaves on `ℙⁿ` over a noetherian ring are quotients of sums of `O(-m)` with
coherent kernel**: for `m ≫ 0` there is an epimorphism `π : 𝒪^I(-m) ⟶ F` (`I` finite,
`𝒪^I(-m) ≅ ⊕_I O(-m)` by `twistFreeIso`) whose kernel is coherent, i.e. a short exact sequence
`0 ⟶ K ⟶ ⊕_I O(-m) ⟶ F ⟶ 0` of coherent sheaves. -/
theorem exists_epi_twist_free_isCoherent_kernel [IsNoetherianRing R] [F.IsCoherent] :
    ∃ m₀ : ℕ, ∀ m : ℕ, m₀ ≤ m → ∃ (I : Type u) (_ : Finite I)
      (π : twist (SheafOfModules.free I) (-(m : ℤ)) ⟶ F),
        Epi π ∧ (twist (SheafOfModules.free I : ℙ(n; R).Modules) (-(m : ℤ))).IsCoherent ∧
          (Limits.kernel π).IsCoherent := by
  haveI := SheafOfModules.IsCoherent.isQuasicoherent F
  haveI : IsLocallyNoetherian ℙ(n; R) := LocallyOfFiniteType.isLocallyNoetherian (toSpec n R)
  obtain ⟨m₀, h⟩ := exists_epi_twist_free F
  refine ⟨m₀, fun m hm ↦ ?_⟩
  obtain ⟨I, hI, π, hπ⟩ := h m hm
  haveI := Scheme.isCoherent_free (X := ℙ(n; R)) I
  haveI := isCoherent_twist (SheafOfModules.free I : ℙ(n; R).Modules) (-(m : ℤ))
  exact ⟨I, hI, π, hπ, inferInstance, SheafOfModules.IsCoherent.kernel π⟩

end AlgebraicGeometry.ProjectiveSpace
